### PR TITLE
Specie update

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Major Specie Update to make them more intresting and belanced with the new Diet system as well as changing some values, everything that is changed is listed in the document: https://docs.google.com/document/d/1mCydwEijH7GfXXed5L6qygnIjL15ZkJGz8_G7yMVJ4E/edit?usp=sharing

I also recomend to merge this PR from upstream if possible as this will assist regarding the moth Diet: https://github.com/space-wizards/space-station-14/pull/21536

- [X] Humans
- [x] Vulpkanin
- [x] Reptilian
- [x] Felinid
- [x] Moth
- [x] Drawf
- [x] Arachnid
- [x] Diona
- [x] Slime
- [x] Oni
- [x] Size Attribute

## Why / Balance

We have now a "Diet" system and so lets uses it to its fully and to balance and fixes up some species, this PR will fix some issues found aswell as demands that were waiting.

Lets makes things intresting!

**Changelog**
:cl: FoxxoTrystan
- remove: Vulpkanin Speed bost (they are not default to 4.5 like all others species)
- remove: Vulpkanin Hunger/Thrist decay has been restored to default.
- tweak: Vulpkanin DamageModifier has been tweaked, Heat: 1.3, Cold: 0.8.
- remove: Vulpkanin TemperatureProtection.
- tweak: Changed Vulpkanin interaction from hugging to pats!
- tweak: Changed Vulpkanin/Reptilian "unarmed" melee. (4 Slash, 1 Blunt)
- add: Reptilian are immune to Misma.
- tweak: Vulpkanin/Repilian Diet has been changed to only eat: "Meat, Fruits, Eggs, Bread"
- tweak: Reptilian DamageModifier has been tweaked, Heat: 0.8.
- tweak: Changed Felinds "unarmed" melee. (3 Slash, 2 Blunt)
- fix: Fixed Felinds Organs (Including Diet)
- tweak: Moth DamageModifier has been tweaked, Cold: 0.8.
- tweak: Moth Diet has been changed to only eat: "Cloth, Fruits" (Still able to consume pills)
- tweak: Diona war against glass shards/dices is over!
- remove: Oni pry speed. (This is just... useless)
- tweak: Oni Melee bonus tweaked: Stun, Blunt, Slash, Piercing, Asphyxiation: 20%
- tweak: Oni using guns will have +20% spread.
- add: Arachnid has now a special diet of only: "Fruits, Soup, BloodFood", meaning they can drink Bloodbags or bite others creatures for food.
- add: Arachnid can now create cocoon that act like Straightjacket, cocoon bodies also prevent rotting!
- add: Arachnid can now put webs on the floor that will slow non-spiders species.
- fix: Fixed some spider web resistance from "Wood" to "Web"
- add: Added some new craftable web furnitures/objects.
- remove: Reverted Arachnid Melee to default (same as humans)
- add: Short/Tall Attribute. (There a special whitelist for species meaning not all specie will have the same effect).
- add: Gave Vulpkanins Short Whitelist, Felinds Tall Whitelist, Lizards Tall Whitelist.
- add: New recepies for moth! (Cotton Pizza, Mothmallow, MothMoffin, CottonSoup)
- tweak: Replaced Emercency Box Tin Food with prepacked sustenance bar (All species can eat it!)
- tweak: Nutribrick is eatable by all species.
- add: Custom sprites for reptilians (A jester will be happy now!)

### CODE REVIEW

**Review by Cheackraze — CHANGES_REQUESTED** [review]
This all looks fine, but theres 2 issues: 1, lizards should not be immune to miasma.  Especially if we are going to bring back diseases, this makes lizards far too strong. and 2, youve changed the diets of a lot of the races but you havent updated the food prototypes themselves to include the dietary flags, so these specie are just going to starve.  If you want to make another PR to accompany this one with all the food changes, then I can merge them together.

**Comment by FoxxoTrystan** [comment]
> This all looks fine, but theres 2 issues: 1, lizards should not be immune to miasma. Especially if we are going to bring back diseases, this makes lizards far too strong. and 2, youve changed the diets of a lot of the races but you havent updated the food prototypes themselves to include the dietary flags, so these specie are just going to starve. If you want to make another PR to accompany this one with all the food changes, then I can merge them together.

When looking Dietary flags seem to be there, i havent added new flags i was mostly using the existing ones.

**Comment by dvir001** [comment]
Make sure everyone cat eat crayons.

**Comment by FoxxoTrystan** [comment]
> Make sure everyone cat eat crayons.

What are you? a crayon gobbler?

But sure.

**Comment by Buldinn** [comment]
> This all looks fine, but theres 2 issues: 1, lizards should not be immune to miasma. Especially if we are going to bring back diseases, this makes lizards far too strong. and 2, youve changed the diets of a lot of the races but you havent updated the food prototypes themselves to include the dietary flags, so these specie are just going to starve. If you want to make another PR to accompany this one with all the food changes, then I can merge them together.

Awwwwww maaaaaan I really really wanted lizard miasma immunity. I dont think it makes them too strong as felinids are already immune to owonavirus being felinids, unless a majority of diseases are miasma based.... It only makes sense that some species are immune to specific diseases and you could balance it by making the lizards more susceptible to other diseases....

I really dont think its too strong, I'd be willing to remove tail grabbing for it to be honest which is much stronger.

Please reconsider UWU

**Review by Cheackraze — APPROVED** [review]
ok this all needs to be documented on the wiki as well

**Comment by octowo** [comment]
boss this dog scream aint it we gotta go back to the yapping board

**Pull request merged**
