### PR TITLE
Ceres (New) - Large restaurant

### PR DESCRIPTION
**Pull request by arimah**
## About the PR
Adds a new shuttle, NC Ceres, a high-class restaurant ship with a large seating area, spacious kitchen, integrated botany and a secluded dining room for VIP guests.

Named after [the Roman goddess of agriculture](https://en.wikipedia.org/wiki/Ceres_(mythology)), as well as [the dwarf planet in the Sol system](https://en.wikipedia.org/wiki/Ceres_(dwarf_planet)) in reference to the botany dome.

## Why / Balance
On the Frontier, if you want to serve food to people, at present there are basically three options:

* Bocadillo, a tiny and adorable restaurant that's great for small-scale, single-crew operations;
* Skipper, with its beautiful botany section and decent kitchen;
* McCargo, huge and stuffed to the brim with _stuff_, focused entirely on a fast food experience.

Where the Skipper can be seen as a step up from the Bocadillo, I can't see McCargo as being a successor to the Skipper, for those of us who want to focus on a fine dining feel with fresh ingredients and food cooked to order. The Ceres aims to fill this niche, by providing large amounts of seating, a luxurious atmosphere, and a decent-sized botany and kitchen. This ship is purposely made to be smaller than the McCargo, for a more intimate, less corporate feel.

Whereas the smaller restaurants can comfortably be run by a single person, the Ceres is explicitly designed with multi-crew in mind. The large separation between botany and the kitchen is a deliberate design decision intended to enforce this. The linked disposal units are a poor man's horizontal dumbwaiter for moving things back and forth. The ChefDrobe and HyDrobe both contain service headsets, for crews that wish to communicate that way, and of course roundstart chefs, botanists and service workers all spawn with them.

The ship seemed to work pretty well in playtesting!

Assorted design considerations:

* The service worker job is for a greeter/server/cleaner/generic helper type role.
* The space cleaner in the freezer room is primarily there for the entrance area, which I dirtied up a bit. The mop and bucket are for minor spills. I originally had a box of janitorial supplies, but (1) the mop bucket that pops out is a pain to shuffle about within the limited space, (2) if you have a more severe janitorial emergency, you should hire whoever's flying a Liquidator.
* The double emergency wall lockers are a result of the multi-crew-oriented design. The captain's locker has no hardsuit (felt unnecessary for a restaurant ship), and each wall locker contains only a single EVA suit. Not wishing to custom fill the locker, I opted for just adding a second one instead.
* I deliberately did _not_ include any soda or booze dispensers, as infinite chems interact poorly with the economy. There is a booze-o-mat that'll keep you going for a while, and beyond that, botany can always grow fruits for juicing. When researched by a science vessel, you can probably figure out somewhere to incorporate such dispensers.
* I originally tried putting carpets under and around _all_ the tables in the main seating area, but it became visually noisy, so I kept the carpet only for the largest table.
* The SMES is necessary to keep the wallmount substation from running out of juice before you've even had a chance to start the generators. If requested, the gyro and gravgen can be moved outside the ship and the distro canister be put inside the bridge if I need to switch the wallmount substation to a regular one. But I kinda like having power and distro tucked away in a tiny engineering room.

**Statistics & info:**

* **Tile count:** 381 (medium)
* **Appraisal price:** around 39,000
* **Shipyard price:** 43,800, ~12% markup – wanted it to be at least 10k more than the Skipper, still much cheaper than the McCargo
* **Recommended crew:** 2–4
* **Available roles:** Chef, Botanist, Service Worker

## Technical details
.yml

## Media
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no :)

**Changelog**
:cl:
- add: Added a new medium-sized fine-dining restaurant ship, NC Ceres.

### CODE REVIEW

**Comment by arimah** [comment]
Additional note: I am fully aware and understand that the new mapping guidelines for ships are not finalised, and that the review of this ship may be delayed as a result. Not expecting to make any major alterations on it, I consider my work more or less done, unless maintainers find huge issues with parts of the ship.

I hope I don't have to massively overhaul the layout... I like how it turned out. :)

**Comment by arimah** [comment]
Smol changes:

* Replaced emergency EVA wall closets with suit wallstorage units
* Added a latejoin spawn point – didn't realise job-specific spawn points were roundstart only!
* Enabled Pilot job

**Comment by Cheackraze** [comment]
it looks good at a first glance, the only thing that stands out to me is the doors on the bottom left being diagonal to eachother but its not the worst thing, I'd allow it still because theirs not much you can do there to get a better design anyhow. I will update this branch and fix any errors this week so we can get this reviewed properly, and implemented.

**Comment by arimah** [comment]
> the doors on the bottom left being diagonal to eachother

I did think about this when mapping, and found that diagonal doors work better than two docks parallel to each other for two reasons:

1. When docked for longer periods of time at Frontier, it gives the ship more flexibility in avoiding dock-blocking;
2. When out in space, you can dock a larger variety of customer vessels simultaneously, even if they have slightly wonky dock placements.

Thank you for the comment, I'm looking forward to your review. :D

**Comment by Cheackraze** [comment]
all I can see is that the price needs to be bumped up around 3-5k, otherwise it looks good and if @MagnusCrowe agrees we can merge

**Comment by arimah** [comment]
I increased the price to a nice round 47,500, in accordance with your comment, @Cheackraze. It seems the upstream merge has resulted in a higher appraisal price immediately after purchase!

**Comment by MagnusCrowe** [comment]
Going to test this today.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
I like the aesthetics of the nice organized kitchen through items being on the table.
However, I think that you could stand to remove items from the table that can be readily obtained from the vending machines you've placed in the kitchen.
Through use, players will fill out the table with the ingredients and tools they are using.

image
You might want to consider adding vacuum tiles to the glass corners.  Not 100% sure but I'm pretty sure that will solve the issue of the glass coming up.

**Comment by ThatOneGoblin25** [comment]
From what I've seen it's space wind being re-added that breaks the glass and yes vacuum tile does fix it.

**Comment by arimah** [comment]
@MagnusCrowe 

> However, I think that you could stand to remove items from the table that can be readily obtained from the vending machines you've placed in the kitchen.

Just to be clear before I start mapping, does this mean you want me to remove ever single item on the table that can be vended, or just "clean it up" a bit? Personally I think it's nice when there is at least a bit of equipment and a box of eggs (as eggs from cartons have twice the egg per egg). If you want all vendables gone, that would leave only the salt and pepper shakers. :)

I'll fix the corners, too - silly spesswind!

Thank you for the comment!

**Comment by arimah** [comment]
I did _not_ mean to close that! Sorry!

**Comment by arimah** [comment]
Here's my suggestion for a nerfed table:

image

With nothing on the table, the kitchen looks and feels completely empty. If you pay 47,500 for a restaurant, you should at least get some basic cooking equipment! I could be convinced to remove the variant cube box, but would really love to keep the eggies. :)

**Comment by arimah** [comment]
I went and just committed the tweaked table as suggested, and I'm happy to make any final adjustments as you see fit.

* Removed cooking ingredients from table, except egg carton and variant cube box.
* Added vacuum markers to exposed diagonals, and ran fixgridatmos.
* Replaced emergency EVA wallsuit lockers with basic EVA. The *only* other ship to feature emergency EVA is the Marauder, and considering this is a fork all about being on a ship in space, it would be bizarre to have emergency suits that can't survive in space.
* Replaced PACMANs with ship variants.

**Comment by MagnusCrowe** [comment]
> Just to be clear before I start mapping, does this mean you want me to remove ever single item on the table that can be vended, or just "clean it up" a bit? Personally I think it's nice when there is at least a bit of equipment and a box of eggs (as eggs from cartons have twice the egg per egg). If you want all vendables gone, that would leave only the salt and pepper shakers. :)
> 
> Thank you for the comment!

Just reduce it to lets say, the salt and pepper shakers and 2 other items.

**Comment by MagnusCrowe** [comment]
> Here's my suggestion for a nerfed table:
> 
> image
> 
> With nothing on the table, the kitchen looks and feels completely empty. If you pay 47,500 for a restaurant, you should at least get some basic cooking equipment! I could be convinced to remove the variant cube box, but would really love to keep the eggies. :)

That looks alright

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
