### PR TITLE
Update firelock.yml

### PR DESCRIPTION
**Pull request by dvir001**
Based on https://github.com/DeltaV-Station/Delta-v/pull/2330

### CODE REVIEW

**Comment by MilonPL** [comment]
you have no shame

**Comment by dvir001** [comment]
> you have no shame

No.

**Comment by whatston3** [comment]
> you have no shame

Thank you @deltanedas, well spotted, a good number.

@dvir001, the other electronics need roughly the same amount of materials, and even BaseElectronics has a value of 100.  Could we have a reasonable ratio given the material cost to make one to value these?

Apart from that, seems fine, larger problem here is that there's no real "intended processing stage" beyond "get materials" that isn't pure tedium and entity spam.  Sure, you can build a ship, but if there were bulk orders or demands for individual gubbins you could make, that might work.

**Comment by dvir001** [comment]
@whatston3 If ill be honest I think the only real fix is to have boards lost sell worth the more they are sold with a X per board lose (Anything that get printed from auto-lath should have an added comp to it when its printed to mark it for market price change)

This should be saved on global sell worth per ID match and every mass printed item should change the worth.

The other system that should be added is a general bounty one for X something order.

**Comment by dvir001** [comment]
Dont merge this ill cook something.

**Pull request closed without merging**
