### PR TITLE
Adds the KM Kaufman ship.

### PR DESCRIPTION
**Pull request by SrLupinotuum**
## About the PR
Adds a new shuttle, the KM Kaufman, a small-sized, highly specialized civilian taxi-like ship.

The Kaufman cab ship was designed for fun of operation and to allow an easy entry roleplaying rich activity. Its skeuomorphic figure was based around the feeling of being in an actual taxi. There's only room for two extra passengers that must be seated one next to another, where any sizable cargo must be set in the trunk of the vehicle and a front TV acts as a source of entertainment and conversation due to its intrusive nature.

## Why / Balance

**To increase player to player interaction:**
It fulfills an incoming role that is to ease transportation in an RP friendly way (It feels like an actual vehicle for moving regular people, not cargo) across the Frontier station and the ever more populated points of interest across the sector.
The deliberate inclusion of a TV is to encourage entertainment broadcasting gameplay.
It's reduced size allows for ease of traversal and docking in crowded spaces while cementing its role as a general public grade service.

**Inclusions/design considerations:**

Micro sized ship: Given the size of the vehicle, most obligatory safety equipment considering the maximum recommended number of passengers, was conveniently placed inside a single wallmounted emergency locker, being the following contents: 
- 3 emergency EVA suits
- 3 air tanks
- 1 fire extinguisher
- 1 defibrillator
- a single flare
- 1 whistle
- 1 GPS
- 1 full mechanical toolbox
- 1 dulled katana (It's a fun reference)

Engine: Following its design philosophy, the engine is outside the cabin, but it's toggleable from inside with a button. A note detailing the recommended settings lay on the table. 

Atmos: For extra safety, given the aesthetically pleasing non-reinforced windows at the back end, the air alarm is connected to window shutters, closing them in case of a breach. Another button allows the driver to open them again.

Lighting: Following its design principle, a continuous railing was placed at the front of the ship, supporting a pair of front lights, giving the impression that they are on a different level to the thrusters, being functional, visually pleasing and structurally sound.

Clown role inclusion: Someone said it could be used as a clown car when they first saw it. Who am I to deny a clown to run a cab service in space?

Purchase price: $7950

## How to test

Load up your dev environment, buy the ship, wear the Kaufman standard uniform included in the ship and drive away.

## Media
kaufman shipyard console
_Kaufman shipyard console_
kaufman nodevis on
_Kaufman nodevis_
kaufman uninitialised, lights and subfloor on
_Kaufman uninitialised_
kaufman spawned
_Kaufman spawned_
A video showcasing a prototype of the KM Kaufman:
https://www.youtube.com/watch?v=D0FJxzUIReY 

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None intended
**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: Lupino
- add: KM Kaufman Ship

### CODE REVIEW

**Comment by dvir001** [comment]
Were MRP, we don't accept joke submisions.

Please read the ship guide lines before submiting again.

**Comment by SrLupinotuum** [comment]
I did read them when designing the ship, could you please describe what elements could be interpreted as a joke so I can fix them?

**Comment by dvir001** [comment]
> I did read them when designing the ship, could you please describe what elements could be interpreted as a joke so I can fix them?

You didn't
https://frontierstation14.com/index.php/Ship_Submission_Guidelines

**Comment by jimmy12or** [comment]
> > I did read them when designing the ship, could you please describe what elements could be interpreted as a joke so I can fix them?
> 
> You didn't https://frontierstation14.com/index.php/Ship_Submission_Guidelines

I would like to point out that there have been MANY times that I have seen ayers asking for a ride from one POI to another, having been one of those folks myself from time to time. I think a taxi ship is a legitimate idea and can properly fill a niche.

**Comment by dvir001** [comment]
> > > I did read them when designing the ship, could you please describe what elements could be interpreted as a joke so I can fix them?
> > 
> > 
> > You didn't https://frontierstation14.com/index.php/Ship_Submission_Guidelines
> 
> I would like to point out that there have been MANY times that I have seen players asking for a ride from one POI to another, having been one of those folks myself from time to time. I think a taxi ship is a legitimate idea and can properly fill a niche.

PTS exists.
And its not breaking any rules.

**Comment by SrLupinotuum** [comment]
Thanks for the feedback, I'll try to improve on it and get second opinions in the discord before submitting again.

**Pull request closed without merging**
