### PR TITLE
Asteroids on Parallax

### PR DESCRIPTION
**Pull request by Kesiath**
## About the PR
This PR adds a desaturated, darkened, and reduced-amount version of the asteroids parallax background from upstream which should make space around the Frontier feel a bit more dense, and puts it into effect on Frontier.

## Why / Balance
While concerns were raised around making sure the background isn't too bright to make it easy to spot EVA people 'skylining' against it, this is hopefully still dark enough to not interfere with that.

## Media
image
https://gyazo.com/0e3db03aa3ec0adfd53e2a15725df019

**Changelog**
:cl:
- tweak: Frontier Station's orbit around Frontier Prime has entered a dense asteroid belt.

### CODE REVIEW

**Comment by Kesiath** [comment]
> Is that the moving one or none moving one?

It can move or not move depending on whichever we prefer, currently it'll move, two different layers with the rear one being slower on movement.

**Comment by dvir001** [comment]
> > Is that the moving one or none moving one?
> 
> It can move or not move depending on whichever we prefer, currently it'll move, two different layers with the rear one being slower on movement.

I was told people get sick by moving background on train in upsteam, this going to be wild.

**Comment by Kesiath** [comment]
> > > Is that the moving one or none moving one?
> > 
> > 
> > It can move or not move depending on whichever we prefer, currently it'll move, two different layers with the rear one being slower on movement.
> 
> I was told people get sick by moving background on train in upsteam, this going to be wild.

Train's movement is incredibly fast, this moves very slow.

**Comment by dvir001** [comment]
> > > > Is that the moving one or none moving one?
> > > 
> > > 
> > > It can move or not move depending on whichever we prefer, currently it'll move, two different layers with the rear one being slower on movement.
> > 
> > 
> > I was told people get sick by moving background on train in upsteam, this going to be wild.
> 
> Train's movement is incredibly fast, this moves very slow.

Im willing to give it a test run, worst case we can just stop it from moving.

**Review by dvir001 — APPROVED** [review]

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
