### PR TITLE
Caduceus minor fixes

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About the PR
Relatively minor fixes to Caduceus I've compiled from people who have used it over the week or so it's been in game.

Adds drain to cloner area, 
adds chemist clothes to chemist locker, 
adds labeler to chemistry lab, 
removes extra unused wall locker, 
wrenchs canisters so they start with air in distro, 
adds extra air can (cryo will likely take up a fair amount of distro air) 
Labels pumps, 
Gives CMO office shutters,
Replaces baton with flash for CMO locker,
 adds a few medical modules for the medical borg,
  adds coffe vendor to breakroom.

## Why / Balance

Mostly quality of life changes, and fixing minor mistakes on my end.
## Media

image

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Tweaked minor things on Caduceus with feedback!

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
merge conflicts?! Oh no, how could this have happened...

**Comment by YumiGumi** [comment]
> merge conflicts?! Oh no, how could this have happened...

the ship is already in the game, so it will have conflicts with the current files within the game, you'll just have to wait for checkraze to handle it like normal

**Comment by Cheackraze** [comment]
its because you are on the same branch. you need to make a new branch now that the original one was merged. You should be able to just make a backup of the ship file, and start a new branch based off from your master with a new name like caduceas-fixes and re-apply the commit there, and open a new PR.

**Comment by RadiantFlash7** [comment]
> its because you are on the same branch. you need to make a new branch now that the original one was merged. You should be able to just make a backup of the ship file, and start a new branch based off from your master with a new name like caduceas-fixes and re-apply the commit there, and open a new PR.


My bad! I'll get home in an hour ir so and do that! >_>;

**Pull request closed without merging**
