### PR TITLE
Searchlight Air-Alarm Fix

### PR DESCRIPTION
**Pull request by Actualcatmoment**
## About the PR

The searchlight has an incorrect air alarm configuration. This fixes it by adding the missing scrubber/vent to the network configuration.

## Why / Balance

Currently the air alarm can never tell what the air quality is like in the main room of the searchlight, and the fire locks will never trigger. Also it's nice when ships don't come with issues from the shipyard.

## How to test

Buy a searchlight in the current version, click on the air alarm next to the airlock, you'll notice there's a missing air vent and scrubber.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: connected air vent and scrubber to the rear air alarm in the searchlight.

### CODE REVIEW

**Review by ErhardSteinhauer — CHANGES_REQUESTED** [review]
Scrubber under the generator unit is not linked
Scrubber in the morgue is not linked

**Review by ErhardSteinhauer — CHANGES_REQUESTED** [review]
Also don't link firelocks to air alarm

**Review by MagnusCrowe — APPROVED** [review]

**Comment by MagnusCrowe** [comment]
> Also don't link firelocks to air alarm

Why not?

**Comment by MagnusCrowe** [comment]
> Scrubber under the generator unit is not linked

That looks intentional to me.  The generator is closed away in it's own little scrubber environment, it wouldn't make much sense for the central room to flip out every time the generator releases CO2.

**Comment by Actualcatmoment** [comment]
> Also don't link firelocks to air alarm

I didn't. The searchlight comes like that.
Also why not?

**Pull request merged**
