### PR TITLE
Caduceus as mothership

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
Adds a mothership console to the Caduceus, offering such small ships as the mailtruck, the pulse and the searchlight.

Before this can be merged, #808 must be merged first. The branch I was working on contains commits from there.

## Why / Balance
Caduceus is a big and not very maneuverable ship that's not very fitted for emergency responses. It's better to have a medical fleet of a caduceus as a hospital and a pulse/searchlight as a ship to carry wounded people. Adding a shipyard console to the caduceus makes it easier for it to fulfill the job of a mothership.

## Technical details
Yml changes, still requires #808 to be merged.

## Media
https://cdn.discordapp.com/attachments/732665247302942730/1192126411096457306/waaaaaaaaaaaaa.mp4?ex=65a7f13d&is=65957c3d&hm=12e481ebbf14733b6c7abd73dcc40dd6c11aa078e8ffd489fc625523d980a473&

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- add: Added a mothership console to the Caduceus, offering small medical ships.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
Okay ***I think*** it should be good now. I don't wanna bother rewriting the commit history of this branch and force-pushing since PRs are squash-merged anyway.

**Comment by Mnemotechnician** [comment]
Mapchecker seems to scream at me because the sec shuttles contain "illegal" sec-only stuff

**Comment by dvir001** [comment]
> Mapchecker seems to scream at me because the sec shuttles contain "illegal" sec-only stuff while having the "None" group. Nothing I can do here.

I rerun the test, going to see if its fine now and test this in game after.

**Comment by dvir001** [comment]
Can you update this with master to see if the error goes away?

**Review by dvir001 — APPROVED** [review]
Working as expected

image

**Pull request merged**
