### PR TITLE
Notice Board

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Notice Board:
- Wall-mounted.
- Stores documents.

## Why / Balance
Mostly RP. Post requests, steal posted requests and post ascii art instead..

## Technical details
.yml, .rsi

## Media
image
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- add: Added notice boards. Accessible through construction menu.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
Pretty sure this is something upstream already has.

**Comment by ErhardSteinhauer** [comment]
Haven't seen any, but quite possible that they have those.

**Comment by dvir001** [comment]
https://github.com/space-wizards/space-station-14/pull/21410

Is our more cool?
How do we compare?

**Comment by ErhardSteinhauer** [comment]
> [space-wizards/space-station-14#21410](https://github.com/space-wizards/space-station-14/pull/21410)
> 
> Is our more cool? How do we compare?

Pffff. Ofc our version is superior: I personally stole sprites from tgstation and done did yml.
But jokes aside both versions are fairly similar. The only real difference is that this version has 8 (9 if you count empty board) sprites for various states of fill whereas upstream has 5 (again, 6 if you count empty one). Also upstream doesn't include recipe for construction menu.

**Comment by dvir001** [comment]
> > [space-wizards/space-station-14#21410](https://github.com/space-wizards/space-station-14/pull/21410)
> > Is our more cool? How do we compare?
> 
> Pffff. Ofc our version is superior: I personally stole sprites from tgstation and done did yml. But jokes aside both versions are fairly similar. The only real difference is that this version has 8 (9 if you count empty board) sprites for various states of fill whereas upstream has 5 (again, 6 if you count empty one). Also upstream doesn't include recipe for construction menu.

I just need you to update our to have have a diffrent ID (Add NF to it) and also add Suffix "Frontier"

**Comment by ErhardSteinhauer** [comment]
> I just need you to update our to have have a diffrent ID (Add NF to it) and also add Suffix "Frontier" and we can just add it

Done.

**Comment by dvir001** [comment]
Tried it in game and getting it to open is a bit hard from angles unless you run into it in straight line, not sure if other one have the same issue from upstream but its very hard to open X_X

Other then that its good

**Comment by ErhardSteinhauer** [comment]
> Tried it in game and getting it to open is a bit hard from angles unless you run into it in straight line, not sure if other one have the same issue from upstream but its very hard to open X_X
> 
> Other then that its good

Fiddled with this thing for a bit, should now be easier to interact from distance. Also made sprites for rotated states.

**Review by FoxxoTrystan — APPROVED** [review]

**Review by dvir001 — APPROVED** [review]
Its working great now.

**Comment by dvir001** [comment]
If you want to map it on frontier you can go for it now.

**Pull request merged**
