### PR TITLE
Messenger Bags (ported from tgstation)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Port of messenger bags from TG Station (original sprites were made by Zydras) with addition of missing job/department specific or high-tech messenger bags by erhardsteinhauer. Stat-wise messenger bags are exactly the same as satchels/backpacks. New bags are distributed among corresponding vendomats. Messenger bag of holding is researchable and can be crafted. Thanks to dvir001 messenger bags are available as starting loadout.

### Added bags:
- [X] Atmospherics tech messenger bag (custom made).
- [X] Brigmedic messenger bag in new NFSD colors (palette made by GhostPrince).
- [X] Captain messenger bag.
- [X] Cargo messenger bag (custom made).
- [X] Chemistry messenger bag.
- [X] Clown messenger bag.
- [X] Engineering messenger bag.
- [X] Genetics messenger bag.
- [X] Hydroponics messenger bag.
- [X] Medical messenger bag.
- [X] Mercenary messenger bag (custom made).
- [X] Grey messenger bag.
- [X] Pilot messenger bag (custom made).
- [X] Salvage messenger bag.
- [X] Science messenger bag.
- [X] Security messenger bag in new NFSD colors (palette made by GhostPrince).
- [X] Virology messenger bag.
- [x] Syndicate messenger bag (custom made).
- [x] Mailperson messenger bag (custom made).
- [x] Janitor messenger bag (custom made).
- [x] Mime messenger bag (custom made).
- [x] Messenger bag of holding (custom made).

### To do:
- ~~[ ] Roboticist messenger bag.~~ I'll do it as soon as someone adds Surgery and Prosthetics. So probably next week or something.
- ~~[ ] Custom genetics messenger bag (right now looks identical to medical).~~ I'll do it as soon as someone adds Genetics. So probably right after surgery'n'stuff or something.
- [X] ~~Mime messenger bag?~~ Mimes aren't real.
- [ ] Other bags I forgot about?

## Why / Balance
Looks cool.

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer, dvir001 (cs magic), original sprites by Zydras
- add: Added a variety of messenger bags, check outfit vendomats near you. Thanks to dvir001 messenger bags are available as starting loadout.

### CODE REVIEW

**Comment by dvir001** [comment]
Need me to add it as a spawn option?

**Comment by ErhardSteinhauer** [comment]
> Need me to add it as a spawn option?

Would be neat

**Comment by dvir001** [comment]
> > Need me to add it as a spawn option?
> 
> Would be neat

Done

**Comment by dvir001** [comment]
Mimes aren't real?
Big sad

**Comment by Cheackraze** [comment]
Bummer, I liked a lot of these!

**Comment by ErhardSteinhauer** [comment]
> Bummer, I liked a lot of these!

I'm just updating it. Will reopen soon.

**Comment by ErhardSteinhauer** [comment]
I think it should be ready for review now.

**Review by dvir001 — APPROVED** [review]
Working great.

**Pull request merged**
