### PR TITLE
Add DSI Workbench engineering shuttle

### PR DESCRIPTION
**Pull request by Tegotia**
## About the PR
Adds the Workbench, a dedicated micro-size engineering shuttle. The shuttle has a total footprint of 8 tiles by 6 tiles, an engineering hardsuit locker, an engineering techfab, two racks with some materials and toolboxes, and a few other engineering-related items.

## Why / Balance
I felt that there was a niche open for a dedicated engineering ship in the micro/small category, so I decided to go with a "contractor's van" type of plan, with a tightly-packed space with loose equipment and a well-worn but not decrepit aesthetic. The Workbench would also be (I think) the smallest enclosed shuttle in the standard shipyard if added, though I didn't go through all the other ships to compare that for sure. Based on discussions about it on the Discord there's a couple of important points I want to cover:

First, as a micro-sized ship, there really wasn't a way to feasibly fit a dual-stage airlock in here. This isn't unprecedented in this category, and the Workbench is small even compared to some of the other micro ships that violate that rule. It's also less of a "civilian" vessel compared to some of the other micro shuttles like the Mail Truck and Legman that violate it since it's intended to be crewed by someone with a hardsuit and whose job would regularly involve EVA.

Second is the bigger point and what initially discouraged me from even trying to PR this, and that's the perception that there are "too many" micro-sized ships in the game. It's probably evident from my tone I personally disagree with this, but I do think even if it is that there is at least an argument to be made for this shuttle's inclusion and I'll cover both those points.

Because it's not an "official" category I don't have a full list, but best I can tell these are the ships that could be considered micro-sized:
UAC Canister
NT Cleric
NT Construct
NSF Fighter
NSF Hospitaller
NC Legman
NC Mail Truck
Menace
NC Pioneer
NSF Rogue
NSF Templar

Of those, the Cleric, Fighter, Hospitaller, Rogue, and Templar are all NFSD ships, so they aren't available for non-security jobs and as someone hasn't played NFSD yet I didn't even know they existed until I perused the list. The Menace is a black market ship, so isn't readily available and isn't really suitable for "civilian" gameplay. The Mail Truck is only available to Mail Couriers and really doesn't have anything useful on it for anyone else anyway. And finally, the Construct is arguably not even a proper shuttle but a platform to build your own custom shuttle on top of.

After eliminating all of those, these are the only micro-sized ships that are somewhat practical and readily available to most captains: the UAC Canister, NC Legman, and NC Pioneer. That feels like some pretty limited options, especially given that the nature of this size category means the ships are going to be very specialized and the demand is going to be higher because it's naturally much harder to get together a crew to staff a larger ship.

Having reviewed the list, I could maybe agree that NFSD could use a cut-back on its micro-sized ships, but in terms of civilian ones I feel like there's a lot of unmet demand.

And finally, I think there is more room for engineering gameplay that could be opened up by having a readily accessible small engineering ship. Most of the others are really science ships with some engineering capabilities or huge ships for large crews, so doing engineering work takes a backseat to research and selling high-tier equipment or whatever else the ship might be doing. There isn't really a ship that is a good fit for a repairman or contractor who can travel around helping ships in mechanical trouble or doing maintenance or repair work for hire, which is exactly what this shuttle is meant to be.

## How to test
Check out the branch, launch your local server, and run the loadgrid command.

## Media
_Uninitialized w/ subfloor + spawns_
image

_Uninitialized with lighting_
image

_Initialized with lighting_
image

_Shipyard menu with estimated value_
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
_None_

**Changelog**

:cl:
- add: The DSI Workbench, a micro-sized engineering contractor's shuttle, is now available in the Shipyard.

### CODE REVIEW

**Comment by Wolfking6116** [comment]
I really like this ship. It has a very cool premise of its occupation and I'd very genuinely love to see a repair operating in this being contracted to fix up a research vessel that's been torn apart. 

As a non-involved third party observer I only have two minor critiques;

1. The angled wall in the top right feels a bit awkward. I think I kind of see what you were trying to do with it - giving that window an angled view port for a little more visibility - but from anyone's outside perspective (when the ship is docked to others/station) it will look kind of strange.

- (subpoint)I realize now after typing it out that you have 5 thrusters, which is partly why the inconsistency of having 2 thrusters in that corner exists. Having an unbalanced number of thrusters tends to throw off ship's maneuvering capabilities, making it harder to strafe while moving forward when there's extra forward thrust. Does this ship have enough mass that it struggles getting up to top speed on base thrusters? If not, the additional thruster may not be necessary and save you some space. (source, attempted to overhaul my ships into speedsters far too many times in game)

2. You may want to increase the price point just a little bit to try to keep new players from purchasing it too often before it becomes apparent what its role/purpose is to the player base. With this ship coming with a techfab I'd honestly recommend some additional base materials to work with, maybe even an autolathe to produce some basics that the Engifab cannot - though I'm not sure if that might be "too strong" for a micro ship. I'd ask Magnus about it

**Comment by Qiler** [comment]
I would swap places of defib and hardsuit locker, makes more sense for eva to be next to airlock. Also a lot of people like to keep extra fuel on top of generator, opening and closing hardsuit locker will put all items on top of generator inside locker. The wall recharger will be hell to use due to how buggy it is, have not tested it on your design but knowing how wonky it behaves on sprinter, you will not be able to put battery in/out 80% of the time because game expects you to stand on a weird angle to it.

**Comment by Tegotia** [comment]
I went through and did a retrofit of the design based on the feedback. I've matched the forward and aft thrusters and made them all full-size now instead of the small thrusters I had before. Personally I think this helped make the exterior shape a lot more distinct and also makes it feel a bit more bulky. That change also added some internal space so I shifted things around and added dedicated engineering lockers and a crate that starts with some stored materials. All of this also makes the ship more expensive, so with adding a few more starting materials I think it'll be in a place where I can reasonably price it at least like 14-15k. Need to finalize a couple things but wanted to get thoughts before I commit the changes.

image

**Comment by MagnusCrowe** [comment]
image

1. Replace the generator with the ship version.
2. Replace the note with a guidebook entry.  We don't want notes because they can't be localized for the non-english downstream forks of Frontier.
3. Remove the custom filled crate of materials.
4. Remove the unnecessary air sensor.
5. Connect the air alarm to both the vent and scrubber.
6. Remove the engineer job from the shipyard file, replace it with contractor, pilot, and mercenary.
7. Remove the engineer spawn and add spawns for contractor, pilot, and mercenary.

**Comment by dvir001** [comment]
Leaving this PR closed till an update, when ready again you can ping us on the discord to either reopen this PR, reopen it yourself or you can just open a new PR.

Thanks.

**Pull request closed without merging**
