### PR TITLE
Restore missing Traits Postgres migration

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds the upstream Traits table Postgres migration from August 2022.

## Why / Balance

The Frontier BankBalance migration fails to run because the index it removes was added in this missing migration.  This should fix the issue.

## How to test

1. Build the Frontier server, point it at a clean, uninitialized Postgres database.
2. The server should initialize its database and start without issue.
3. Connect to the server, you should connect without issue.
4. The server should run.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

No changelog, internal feature.

### CODE REVIEW

**Review by dvir001 — APPROVED** [review]
Going to mark this as approved but I have no idea what im looking at.
Going to wait for @Cheackraze or @GreaseMonk to merge this.

If its critical self merge this.

**Review by arimah — COMMENTED** [review]
Question: No migrations for SQLite? Could that break private and development servers?

**Comment by whatston3** [comment]
> Question: No migrations for SQLite? Could that break private and development servers?

This is an existing, old migration - the SQLite version already exists:
[20220816163313_Traits.cs](https://github.com/new-frontiers-14/frontier-station-14/blob/dbd4a38f03cff05c5d606da0a341943217623a28/Content.Server.Database/Migrations/Sqlite/20220816163313_Traits.cs)
[20220816163313_Traits.Designer.cs](https://github.com/new-frontiers-14/frontier-station-14/blob/dbd4a38f03cff05c5d606da0a341943217623a28/Content.Server.Database/Migrations/Sqlite/20220816163313_Traits.Designer.cs)

The issue this fixes has been reported a few times when people were setting up servers:
https://discord.com/channels/1123826877245694004/1127687656084611214/1270719934737158194
https://discord.com/channels/1123826877245694004/1127687656084611214/1248950877708881930
https://discord.com/channels/1123826877245694004/1127687656084611214/1233741132748296203

**Comment by whatston3** [comment]
> Going to mark this as approved but I have no idea what im looking at. Going to wait for @Cheackraze or @GreaseMonk to merge this.
> 
> If its critical self merge this.

Not critical.

**Review by arimah — APPROVED** [review]

**Pull request merged**
