### PR TITLE
add jetpack to NFSD/advanced magboots

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Adds the jetpack functionality to the advanced magboots and adds NFSD advanced magboots.

## Why / Balance

Because they are advanced and need actually advanced features.
Fabrication requirements where edited to also need plassteel and durathread to fabricate the advanced magboots.

The new NFSD advanced magboots will be equal as the fabricated ones with the difference that they will cost 3 FUCs and wont have a small weapon slot for the pistol or knife.

All magboots versions can be recharged on canisters, tested on the dev enviroment

NFSD advanced magboots still need a new sprite(help)

## How to test

Spawn advanced magboots and go to the void of space.

## Breaking changes

**Changelog**

:cl: Leander
- add: Advanced magboots now have integrated jetpacks
- add: Added new NFSD advanced magboots you can get them for the price of 3 FUCs

### CODE REVIEW

**Comment by dvir001** [comment]
Feels a bit power creep but I'm not against it
I'll look into the balance on the numbers later

**Comment by Leander-0** [comment]
the new NFSD magboots wont have the weapon slot (mostly due to verb misspredict) the color of the maboots will be changed soon once the sprites for it are done.

the magboots jetpacks should only give enough for 3 minutes of flight

**Comment by Leander-0** [comment]
Sprites updated for the NFSD advanced magboots, courtesy of GhostPrince :^)

**Comment by ErhardSteinhauer** [comment]
I am opposed to this idea:
- it makes all other jetpacks completely irrelevant.
- it has no tradeoffs: with other jetpacks you need to choose which slot you want to sacrifice for mobility - hand slot/suit storage slot/backpack slot/belt slot. With this one you just get additional (and rather powerful) functionality for free (and no increasing item's manufacturing price isn't a tradeoff).

**Comment by Leander-0** [comment]
Advanced magboots already are just easy no-slips, yeah jetpacks require a slot to be used but also come with a lot more fly time, the boots at best will have enough for 2-3 minutes of flight then you are up to your own in the void.

Also the same you are describing could not be said about the hoverbikes? everyone can get an early one on uplinks  if not free on expeditions, they have infinite fuel, storage and light.

i believe the numbers can still be perfectly tweaked as just another option to have when it comes to EVA.

**Comment by ErhardSteinhauer** [comment]
> Also the same you are describing could not be said about the hoverbikes?

It could, yeah, and hoverbikes *should* be changed to consume some type of fuel (I just don't have the knowledge required to do that), those still have a bit of trade off to them: they take up your hand slot, can't use them to shoot in zero g, anyone close to you can steal your duffel strapped to the bike.

I still think that magboots with a jetpack is way too powergamey and no amount of finagling with numbers (short of making jetpack portion of boots completely impractical but at this point why even bother) will make this item more balanced.

**Comment by PeccNeck** [comment]
I think I'm fine seeing NFSD with these, but not literally anyone who can get advanced magboots, even with relatively shorter flight times and upped material cost.

I feel like an independent Jetboots item might be better, be it under its own research tree or share it with magboots. It'd still be an upgrade for most, since you're sacrificing your shoes instead of a valuable hand slot or your even more valuable backpack, but you'd also have to pick and choose between it and magboots.

**Comment by ErhardSteinhauer** [comment]
Jetpack magboots exclusive to NFSD is even worse

**Comment by PeccNeck** [comment]
Very much my personal opinion, then. Either way, yeah; too much function in one item. There's a niche to be filled, but this isn't how to fill it.

**Comment by GreaseMonk** [comment]
In my personal opinion i would not merge this for the same reason of:

> I am opposed to this idea:
> 
>     * it makes all other jetpacks completely irrelevant.
> 
>     * it has no tradeoffs: with other jetpacks you need to choose which slot you want to sacrifice for mobility - hand slot/suit storage slot/backpack slot/belt slot. With this one you just get additional (and rather powerful) functionality for free (and no increasing item's manufacturing price isn't a tradeoff).

**Comment by Cheackraze** [comment]
I think this is borderline power creep like @ErhardSteinhauer says. The only way I can see these being worthwhile is if the flight time is 45s or less, and non-refillable. More of an emergency "oh shit" function than an actual replacement to jetpacks.

**Comment by Leander-0** [comment]
After much discussion it has been decided this is powercreep so i will be closing it, it do be like that sometimes :P

**Pull request closed without merging**
