### PR TITLE
Automatic changelogs

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
About time!

Still had to use the .js version from Delta because the .py from stationware didn't seem to work on my test repo

# Setup required!!

The following secrets are required
`BOT_TOKEN` = A GitHub PAT with at least `contents Read & Write` for the repository, and the ability to bypass branch protections
`CHANGELOG_DISCORD_WEBHOOK` = A Discord webhook to send changelogs to

The following variables are required
`CHANGELOG_USER` = The username for the changelog commits
`CHANGELOG_EMAIL` = The email for the changelog commits (all metadata)
`CHANGELOG_MESSAGE` = The commit message shown. If set to something like "Automatic Changelog Update", commits will show up as "Automatic Changelog Update (#1234)"

Settings these all up before merging will mean its also tested upon merge. Changelogs will be published every day, but can also be manually triggered via a workflow dispatch.

**Changelog**

:cl:
- add: This is a test changelog to confirm that automatic changelogs are working

### CODE REVIEW

**Comment by DebugOk** [comment]
Also important, make sure the `server.id` is set to something unique, otherwise new changelogs dont show as "new" in game

**Comment by FrontierATC** [comment]
> 

pretty sure i did but i can always double check

**Comment by DebugOk** [comment]
> > 
> 
> pretty sure i did but i can always double check

Its not *super* important, as all it does it make the changelog button light up if theres new ones. Its still nice to have and takes little effort to change

**Comment by DebugOk** [comment]
Also, it might be better to change it to something new if you did have it set, as a majority of clients will still have the old changelog amount stored

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
