### PR TITLE
Add a signal receiver to thrusters (and gyros) for remote power control

### PR DESCRIPTION
**Pull request by spacedwarf14**
## About the PR

This PR adds the ability to link Thrusters and Gyros to a button, lever or a switch. This is a followup to https://github.com/new-frontiers-14/frontier-station-14/pull/2025.

In order to have thruster respond to remote signal events, I implement the OnSignalReceived signal handler for it. I modify OnActivateThruster so that the message args are optional; this way I can call it from inside the thruster system without sending another event.

## Why / Balance

This is the problem I am trying to tackle as described in #2025. Basically, I want to be able to turn systems on and off regardless of the APC network it is attached to, so that I can save power. This way I can make a switch for the science room, one for thrusters, and so on. Based on https://github.com/new-frontiers-14/frontier-station-14/pull/2025#issuecomment-2356115048

If this is merged I will add this to a few more things, starting with entities that take a lot of power: arti analyzers, robotics console, etc.

## How to test

Spawn a shuttle and start linking things. Test to see if the engines actually stop working when toggled and check power savings.

## Media

2024-09-17-135559_676x588_scrot
2024-09-17-135613_312x267_scrot
2024-09-17-135621_306x267_scrot

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Just adding an event handler and tweaking an existing event handler to be optionally called without event arguments.

**Changelog**

:cl:
- add: Thruster can now be switched on and off with remote buttons, switches, levers and signalers.

### CODE REVIEW

**Comment by Cheackraze** [comment]
i will say, this is a much better solution conceptually.

**Comment by spacedwarf14** [comment]
> i will say, this is a much better solution conceptually.

thanks, i try. This approach would also weave in to another modification I want to make -- a console that has a UI to indicate and send signals to devices. Basically the console would act as a switch with a lot of inputs and outputs.

**Comment by dvir001** [comment]
I find it funny since this is finally giving an actual use case for the code I added to toggle power off from thrusters and gyro.

Ill get around to testing this in game soon if no one else will before me.

**Review by whatston3 — CHANGES_REQUESTED** [review]
Any changes to Enabled should result in a change to the power draw.  I've made a set of suggestions here: 
[whatston3:power-switchable-machines-suggestions](https://github.com/spacedwarf14/frontier-station-14/compare/power-switchable-machines...whatston3:power-switchable-machines-suggestions?expand=1)

Looks alright otherwise.

**Comment by spacedwarf14** [comment]
thanks, makes sense. tested aand behaves as expected.

**Review by whatston3 — APPROVED** [review]

**Comment by spacedwarf14** [comment]
tested post-merge, works.

**Comment by whatston3** [comment]
Merging this: happy with it, and it's a fairly innocuous change.  Thanks for the feature.

**Pull request merged**
