### PR TITLE
Blue wreck loot rework

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added alot more items for salvage, added more raw items for recycle and re balanced the rewards to be more raw mats based.
Added more "lifes" to what the wrecks spawn and how they look
Made all wrecks bigger
Removed alot of the meds. left some basics.
Overall they should offer about the same income but now more fun.

## Why / Balance
Needed to update them to match the same level of vgroids, as they were left in the dark.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
This PR edit alot of unused maps from upstream back to base loot to avoid merge conflicts.

**Changelog**
:cl:
- tweak: Wrecks have new, interesting things on them.

### CODE REVIEW

**Review by whatston3 — COMMENTED** [review]
Generally looks alright.

I think there's a bit too much stuff as-is - I increased the base empty rate back to 2 and increased the frequency of the walls, created a new spawner for assorted goods crates, which are still _quite_ common.

Set the value of 1000 point research point disks to 300 (why not, tracks with others), grouped a few of the items together (don't need four different research disks spawning at once).

Might still need some work, but I think it's a good change overall.

Suggestions vs your branch: https://github.com/dvir001/frontier-station-14/compare/2024-12-07-WreckLoot...whatston3:2024-12-07-WreckLoot-suggestions?expand=1

Also, removed some of the now-craftable items from the uncommon food mail.  Should probably remove the unused nyano variants altogether.

**Comment by dvir001** [comment]
> Generally looks alright.
> 
> I think there's a bit too much stuff as-is - I increased the base empty rate back to 2 and increased the frequency of the walls, created a new spawner for assorted goods crates, which are still _quite_ common.
> 
> Set the value of 1000 point research point disks to 300 (why not, tracks with others), grouped a few of the items together (don't need four different research disks spawning at once).
> 
> Might still need some work, but I think it's a good change overall.
> 
> Suggestions vs your branch: https://github.com/dvir001/frontier-station-14/compare/2024-12-07-WreckLoot...whatston3:2024-12-07-WreckLoot-suggestions?expand=1
> 
> Also, removed some of the now-craftable items from the uncommon food mail. Should probably remove the unused nyano variants altogether.
> 
> Edit: also, we really need more locker types, it's seems to be mostly engineeering/electrical stuff. If we put some of the mail stuff in spawners and used those spawners in the assorted goodies crate, that'd be neat and cheap maintenance-wise.

Ya merg

**Comment by GreaseMonk** [comment]
Can we remove the research point disk (1000 points) ?
These things are worthless and almost never brought to scientists. finding one at 5000 and 10000 should be a rare find and feels more worth bringing to sci

**Comment by dvir001** [comment]
> Can we remove the research point disk (1000 points) ? Not sure if you removed it or not im on my phone These things are worthless and almost never brought to scientists. finding one at 5000 and 10000 should be a rare find and feels more worth bringing to sci

Fixed

**Comment by dvir001** [comment]
This is ready, I don't want to add to many images to leave it for players to see ingame.

**Review by whatston3 — APPROVED** [review]
Generally think these are pretty alright, should make salvaging wrecks more appealing.

DripLoot table could still use work, but I think that's fine for later.

**Pull request merged**
