### PR TITLE
Grifty's Gas and Grub Bluespace POI

### PR DESCRIPTION
**Pull request by DustScoundrel**
## About the PR

I added Grifty's Gas and Grub as a bluespace POI.

## Why / Balance

Grifty's is a simple, flavorful place with mild danger and rewards that also seeks to provide an additional resource for some of the more popular vending machines that are taken from static POIs, to reduce their removal.

## Media

image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

I added this to the bluespace maps folder, but don't know if there are any additional steps that need to be taken beyond the map, as it's not a standard shipyard entry.

:cl:
- add: Added Grifty's Gas and Grub bluespace POI

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
This is just a map file... if you want it as a POI, add it to the POI SpawnList.

Tho pretty sure there is a new system for randomly setting Poi by each round.
For that you will ask Checkraze, but this file alone wont do.

**Comment by Cheackraze** [comment]
I like the idea, but I do have some requests: swap out most of those vending machines for the RNG vending machine spawner instead so its different every round. 2. add a smuggling dead drop item as well (feel free to message me on discord to discover how)

**Comment by Cheackraze** [comment]
after that, I can assist you in getting this to spawn in-game.

**Comment by DustScoundrel** [comment]
Okay! I think I've got things added in correctly. I randomized the majority of the vending machines and added the dead drop.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
