### PR TITLE
Shuttle records system

### PR DESCRIPTION
**Pull request by GreaseMonk**
## About the PR

This adds a system that stores data about the transaction everytime a ship is sold onto the grid it was sold at.
The system adds or changes nothing to the current codebase except for the hook into the shipyard when ships are purchased.
I also cleaned some warnings in the shipyard system that was blocking me from accessing the EntityUid for the ship that was purchased.
Currently, it will make issues with motherships, but this is outside the scope of the changes in this PR.

## Why / Balance

This is needed to make a couple of new consoles that are coming to frontier.

## How to test

1. Buy a ship
2. Inspect the server components on the service entity
3. Ensure that the ShuttleRecordsDataComponent has the correct amount of data by checking the size of the array on the component.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

none 

**Changelog**

:cl:
- add: Added shuttle records system that logs everytime a ship is purchased.

### CODE REVIEW

**Comment by GreaseMonk** [comment]
Going to change this so it is stored globally

**Comment by GreaseMonk** [comment]
Using sector services now so is ready for review again

**Review by whatston3 — COMMENTED** [review]
Works fine.

A few suggestions:
1. I'd add a reference to the sector in the ShuttleRecordDataComponent just to reinforce it's a global database.
2. I've replaced a lot of "shuttleEntityUid.Value" references with one value - I hope "shuttleUid" is fine by you - also replaced a lot of "args.Actor" references with "player" for consistency and brevity.
3. I think most of the stuff Quigley's done would work well with an entity reference to person renting the ship - should be fine to add later.
4. Not sure about indexing this list, should be fine to kick the can given the interface in the records system.

Everything I recommended is up at [whatston3:fs-15-transaction-indexing-suggestions](https://github.com/new-frontiers-14/frontier-station-14/compare/fs-15-ship-transaction-indexing...whatston3:frontier-station-14:fs-15-transaction-indexing-suggestions?expand=1), seems fine under test.

**Comment by GreaseMonk** [comment]
updated the branch with the suggestions, good thinking. lets merge it

**Review by whatston3 — APPROVED** [review]

**Pull request merged**
