### PR TITLE
Add support for bosses in VGRoid

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
This PR add support code to allow us to add bosses to vgroids

Adding 3 comps to bosses when they step off the grid:
Pacified
Cell damage one per sec.
TimedDespawn for 15 sec

Removing the comps when they step back, making it impossible to leave the grid for a long time.

Added admin log for cases when someone going off and on a grid as a dungeon boss

## Why / Balance
We wanted to add bosses to the VGroid for a while now but we had no way to make sure they wont just be taken into frontier, this code fixes the issue. 

## How to test
Right now just spawn any dungeon boss on a grid, move it off grid, ghost it, use it to go on and off for testing.

## Media
N/A

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
None since we didnt add the bosses to vgroid yet.

### CODE REVIEW

**Comment by dvir001** [comment]
God dam TimedDespawn killing tests again
Going to swap it

**Review by ErhardSteinhauer — APPROVED** [review]
Works in game

**Comment by dvir001** [comment]
Test fail fixed by @whatston3 this is ready for merge

**Comment by whatston3** [comment]
Would be nice to ensure that this only happens when a player is active in the role, being able to bait a one star unit into space so it deletes itself is a little bit lame.

**Comment by whatston3** [comment]
> > Would be nice to ensure that this only happens when a player is active in the role, being able to bait a one star unit into space so it deletes itself is a little bit lame.
> 
> Tbh im not sure anyone will waste time trying to bait a boss and not die to it just to try to have it delete itself. Also it should work on mobs without a mind since people can still yoink a boss into frontier.

1. "Also it should work on mobs without a mind" - you check for ActorComponent yourself - the only thing is you don't check that the actor leaves.
2. "people can still yoink a boss into frontier" - better resolved with #2398

**Comment by whatston3** [comment]
Anyways, give me a minute, I'll get something written up.

**Comment by dvir001** [comment]
ActorComponent use just for log and alart unless I fucked up.

**Review by whatston3 — APPROVED** [review]
Fine, but I still think this is a magnet for cheese.

**Comment by dvir001** [comment]
> cheese

Could be but let admins deal with it for ones (If it is possible to cheese)

**Comment by dvir001** [comment]
> just passing through but I wanted to mention another solution for this at [space-wizards/space-station-14#30436](https://github.com/space-wizards/space-station-14/pull/30436) which would allow you to generically contain entities to grids / maps.
> 
> It does currently require a 1 line engine change that the PR was blocked over until I made and then promptly went unmerged for half a year but I'm not salty about it. If you want to avoid the engine issue just rip out the changes to NukeSystem, you all shouldnt need that anyway.

What is the difference with this code block? in my code just make them gain and lose comps based on enter / leave so we dont hardcode anything.

**Pull request merged**
