### PR TITLE
New shade for 100k bills

### PR DESCRIPTION
**Pull request by Unkn0wnGh0st333**
## About the PR
Resprites the 100k stack with a different shade, so it doesn't look like a fresh cut of salmon.

## Why / Balance
It was requested of me by @whatston3 for the redesign of it. 
I used different types of red and this one looked the least like meat when sprited and Whatstone liked this variant in the discord so it was the one I went with.

## How to test
Boot up an environment and spawn the (newly added with this PR) 100k stack. 

## Media
Screenshot 2024-12-08 211320
Screenshot 2024-12-08 210914

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None that I am aware of.

**Changelog**

### CODE REVIEW

**Comment by dvir001** [comment]
No need for Changelog

**Comment by Unkn0wnGh0st333** [comment]
> No need for Changelog

done

**Comment by Unkn0wnGh0st333** [comment]
Misclick lol

**Comment by whatston3** [comment]
Proposed:
image
Current:
image

Generally fine - prefer more contrast between the bill's face and the edge, I think the proposed top picture above looks a bit better - if it's fine by you, I'll get the other bills to be consistent (the brighter orange you used on the bottom seems to read alright even on the brown bill, will apply these changes, change the counterfeit versions as well, we should be good.

Apart from that, missed a pixel on the pink 250k face (bottom left of the rightmost field, it's still the old orange).

**Comment by whatston3** [comment]
Everything's up on [whatston3:New-Ink-suggestions](https://github.com/whatston3/frontier-station-14/tree/New-Ink-suggestions), changes on [this commit](https://github.com/new-frontiers-14/frontier-station-14/commit/9e068dc59bc3faa3572094374a6410806798d1b4), I can push them in if you'd like.

**Comment by Unkn0wnGh0st333** [comment]
> Everything's up on [whatston3:New-Ink-suggestions](https://github.com/whatston3/frontier-station-14/tree/New-Ink-suggestions), changes on [this commit](https://github.com/new-frontiers-14/frontier-station-14/commit/9e068dc59bc3faa3572094374a6410806798d1b4), I can push them in if you'd like.

Oh yeah just push it then

**Review by whatston3 — APPROVED** [review]
Happy with this.

**Comment by whatston3** [comment]
@Unkn0wnGh0st333 Thanks for the initiative, and sorry for the initial shitpost.

**Pull request merged**
