### PR TITLE
Make shuttle walls/windows constructable (#19255)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
https://github.com/space-wizards/space-station-14/pull/19255

## Why / Balance
Getting this added before a big merge since its was asked for.

## Media
N/A

## Breaking changes
N/A

**Changelog**
:cl: Velcroboy
- tweak: Shuttle walls and windows can now be constructed.

### CODE REVIEW

**Comment by Cheackraze** [comment]
This is literally coming in tlwith the merge in the next few weeks, we can wait a little bit, this is causing more work for upstream merge not less

**Comment by dvir001** [comment]
> This is literally coming in tlwith the merge in the next few weeks, we can wait a little bit, this is causing more work for upstream merge not less

Wanted to have it with #757 to keep all the protos at the same level.

**Comment by Cheackraze** [comment]
i mean you do realize that this adds 25 conflicting files and 448 conflicting lines of code when I go to merge, will likely not make it in until I do it. It just really adds a lot more work for me in the next week or two.

**Comment by dvir001** [comment]
Closing for now

**Pull request closed without merging**
