### PR TITLE
Refinement process for Artifexium

### PR DESCRIPTION
**Pull request by Wolfking6116**
## About the PR

Changed the reagent within Artifact fragments to a raw version that is 'less potent'.
ie simply gives drastically less amount, still works the same as regular artifixium otherwise.

Adds in five new recipes total.

3 of them "refine" the raw artifixium with another ingredient, producing the regular artifixum as we know it in reasonable quantities. 

One from a rare source, one from an uncommon source, and one from a more common source that might be painful.

The amount ratios are no way set in stone, just put together from my best judgement from when I've done science

## Why / Balance

-Why: A solution has been asked for regarding Artifexium for a while, this is an attempt to bring that to the table.

-Balance:  Doing this sort of change will add engagement with other systems within science and hopefully other groups because it;
1. Reduces the amount of base Artifexium in Fragments by a great degree, leading to an increased need to mine asteroids which will;
- give sci ships more reason to crew more miners/salvagers
- increase the likelihood of sci ships will buy ore/fragments from other ships
2. Adds new types of reagents sci ships need to get Artifexium production going, which may;
- increase engagement with mining ships and expo ships
- broaden the types of loot considered valuable on an expo, if they do it themselves
3. Includes some unstable reactions if ingredients are mixed together lazily, which encourages;
- interacting with some other science equipment like droppers with room to expand it to centrifuge and more. 

~~This is my rushed attempt to keep Darin from running down a code induced rabbit hole of CS. (mostly because CS is eldritch to me)~~

## Technical details

Interacting PRs in current submittals;

If Darin's advanced processor goes through I'd recommend not reducing the amount of Raw Artifexium in the fragments as much, but still think this would be a positive change over all even with the inclusion of an additional refining step of adequate technology.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Changes are untested aside launching local client, since this is just a proposal.

**Changelog**

:cl:
- add: Scientists in the Sector have discovered new ways to refine ground up Artifact fragments to make them more potent.

- tweak: It's been discovered that the quality of xenoartifacts has been degrading with excessive excavation.

### CODE REVIEW

**Comment by dvir001** [comment]
yml errors

**Comment by Cheackraze** [comment]
ok so heres my thoughts: is the amount of artifexium you get per ground up fragment is already trivial? Spray bottles work by aerosolizing equal fractions of each reagent in the bottle. What this means is cant you just dilute even 5u endlessly (floating point rounding being the actual limiter) with just water for instance? Its a fundamental flaw with the juice to begin with in my mind.

If im seeing this correctly, you can no longer just use the raw juice to make the effect, instead you have to refine it. I like this solution to the problem in theory.

**Review by Cheackraze — APPROVED** [review]

**Comment by ThatOneGoblin25** [comment]
> What this means is cant you just dilute even 5u endlessly (floating point rounding being the actual limiter) with just water for instance?

You can dilute artifaxium with water, but putting more water in than an even 1:1 water to artifaxium ratio means it doesn't work from what I've tested.

**Comment by Wolfking6116** [comment]
> ok so heres my thoughts: is the amount of artifexium you get per ground up fragment is already trivial? Spray bottles work by aerosolizing equal fractions of each reagent in the bottle. What this means is cant you just dilute even 5u endlessly (floating point rounding being the actual limiter) with just water for instance? Its a fundamental flaw with the juice to begin with in my mind.

To my knowledge, as far as the yml says, is that it will trigger an artifact so long as 5u of the reagent is present. I'm not sure if you could dilute it down to 1u with 4u water and still trigger it. I've never messed with it to that great of a degree, but I can try to do some testing.

> If im seeing this correctly, you can no longer just use the raw juice to make the effect, instead you have to refine it. I like this solution to the problem in theory.

I do want to clarify! I copied the .yml for artifexium and made a new id of the Raw version that is effectively the exact same, just coming in worse quantities and able to be refined. Originally I was just going to keep artifexium at low amounts and make refinements, but then realized people would just endlessly cycle it and I absolutely did not want that.

So, in essence, people /can/ still use Raw Artifexium to trigger the artifacts... albeit getting vastly less of it from artifact fragments than before. so they'll need 10x the fragments to do things at the rate things currently have been, or they can go through methods of refining it to make more.

**Pull request merged**
