### PR TITLE
Pirate's Cove Modifications

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

This is step 1 in moving pirates off to a more automated, less admin hands-on approach.
## Why / Balance

Changes in the way piracy happens on frontier to help improve the RP and gameplay
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Pirates have gained a more firm foothold in the sector.
- tweak: Pirate Captains are now a whitelisted role. See the discord for more information.

### CODE REVIEW

**Comment by VividPups** [comment]
Is this going to be like how Sec currently is?  Whitelisted sheriff (pirate captain)  comes on and open slots up?

**Comment by Cheackraze** [comment]
> Is this going to be like how Sec currently is? Whitelisted sheriff (pirate captain) comes on and open slots up? Or like the captain comes in and there is limited crew slots for pirates (like in normal upstream)

this is a back-end way for an admin to open up a late-join captain slot if NFSD forces exist. It is not currently automatic, but it does restrict the captains to whitelisted + some requirements. For now, we will operate the same way as a player (ahelp to request piracy) however we will likely open a slot here and have you respawn fresh on the cove with full pirate gear. In the future, we will definitely look at uplink currencies for them to get better geared

**Review by dvir001 — APPROVED** [review]

**Comment by WallaceLordofOwls** [comment]
There is a quite large issue with this PR, namely that pirates that spawn on the pirate cove start out with next to no supplies in terms of medical, food, fuel, and water, and have no reliable way of getting them since they are clearly marked as pirates, and thus, can't go to Frontier. 
Pirating ships is not a reliable way to get supplies. We ran out of fuel and got caught by the NFSD in a shift today because we had no fuel and weren't able to find a mining ship to pirate before we ran out. I'd recommend that this PR be rolled back until methods to allow pirates to get supplies are available to add, or some patch fix is implemented. As it stands right now, this is killing piracy in my opinion.

**Comment by WallaceLordofOwls** [comment]
@Cheackraze The piracy changes have been quite good so far, but one issue I've noticed is that because pirates don't start with common comms, only freelancer comms, if someone starts chasing you you have no way of telling them to fuck off or be blown up, so you have to immediately escalate to cannons if they keep chasing you. You can get common comms by stealing them, but if someone chases you before you've had a chance to rob anyone, as happened to me in the previous shift, you can't do proper escalation. Thus, I think pirates should start with common comms in their freelancer headsets.

**Comment by dvir001** [comment]
Its intended so they wont know whats going on till they steal headsets, there is a lot of power in radio.

**Pull request merged**
