### PR TITLE
Pathfinder: small update

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
It felt about time the Pathfinder received an update pass as the game has changed a lot over the past few months. 

## Why / Balance
Lots of new things have been changed/added since the Pathfinder was last updated. I've played on it quite a bit recently, and I really felt like some things could improve to make it both visually nicer and introduce some small functions it currently doesn't have.

List of changes:
- Smoothed out the cockpit window now that the sprites mesh properly. 
- Smoothed out some lines on the hull to make it prettier.
- Replaced lattice on diagonals with glass.
- Moved the lateral thrusters to incorporate the above smoothing of lines but also to remove LV from under walls.
- Moved some atmos things around and did a bit of re-wiring.
- Removed the broken computers from the breakroom, shifted the chairs forward, added a water cooler and removed the water bottles. The computers are still there, but now outside of the breakroom.
- Removed one EVA locker (why were there two?) and moved the gas tank dispenser there instead. 
- Added a couple of windows to improve visibility.
- Replaced gas mixer with the 'on' variant. 
- Replaced firelocks in front of doors with glass firelocks.
- Linked firelocks to air alarm.
- Added emergency locker and firefighting locker.
- Removed custom fill locker in engineering and put an empty locker with AME jar on the ground.

## How to test
Checkout the branch, load the ship.

## Media
2024-08-22 15_42_11-Window
Uninitialised, spawns and subfloor visible.

2024-08-22 15_42_39-Window
Uninitialised, subfloor visible.

2024-08-22 15_44_02-Window
Initialised, subfloor visible.

2024-08-22 15_44_20-Window
Initialised, correct lighting and no subfloor.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Updated the Pathfinder.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
@Kesiath tagging you due to these being proposed changes to a ship you originally mapped

**Comment by ErhardSteinhauer** [comment]
You can (and probably should) replace that maintenance wall locker and loose ame jars with AME wall locker.

**Comment by Tych0theSynth** [comment]
> You can (and probably should) replace that maintenance wall locker and loose ame jars with AME wall locker.

That's a thing now? Cool! Then I shall.

**Comment by Tych0theSynth** [comment]
2024-08-22 16_37_59-Window
Added.

**Review by arimah — CHANGES_REQUESTED** [review]
Looking good! Small changes, still feels like the Pathfinder but a bit better. I like it.

One tiny thing and we can get it merged:
image
The distro mixer has the wrong ratio. :)

**Comment by Tych0theSynth** [comment]
Fixed ratio!

**Review by arimah — APPROVED** [review]

**Pull request merged**
