### PR TITLE
Remove the Marauder

### PR DESCRIPTION
**Pull request by arimah**
## About the PR
Removes the NSF Marauder.

## Why / Balance
This ship's age is definitely showing. It has a number of issues that necessitate a ground-up rework. In its current state, it is not a good fit for Frontier.

## How to test
1. Don't buy the Marauder, because you can't.

## Media
N/A

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
No.

**Changelog**
:cl:
- remove: The NSF Marauder is no longer available for purchase.

### CODE REVIEW

**Review by dvir001 — APPROVED** [review]
I have seen this in a dream

**Comment by chrome-cirrus** [comment]
F in the chat for the old warhorse

**Comment by Tych0theSynth** [comment]
Saving the mental health of all the mappers who tried to rework this thing.

**Comment by foob1** [comment]
Whenever I see the Marauder being used as the NFSD mothership I refuse to play NFSD. The ship is really crammed and outdated, glad it's being removed.

**Pull request merged**
