### PR TITLE
The DEMAG

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added the DEMAG to allow fixing vending machine, doors and lockers.
More to be added later, but for now just the critical stuff.

## Why / Balance
We had to destroy vending machines before since there was no way to fix them.

## Technical details
C#
YML

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, 

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- add: NT Now provide the SR and Sheriff with the new DEMAG cryptographic resequencer, currently allowing them to unhack vending machines, doors and lockers with more to come soon.

### CODE REVIEW

**Comment by GentleButter** [comment]
DEMAG

**Comment by Everturning** [comment]
where is it obtained from?

**Comment by GentleButter** [comment]
> where is it obtained from?

I beleive it spawns on the Sheriff and SR just like the door configurator and the door access emotes

**Comment by dvir001** [comment]
DEMAG Now works with doors and lockers.

**Comment by TheShuEd** [comment]
https://github.com/space-wizards/space-station-14/pull/23097

**Comment by dvir001** [comment]
> [space-wizards/space-station-14#23097](https://github.com/space-wizards/space-station-14/pull/23097)

Yooo thats fucking cool

Whlle having this as a tech and one time use per key wont 100% fit the frontier style, this has alot of the code work done that I wanted to make for this

Also we have the DoorSystem code done and I will love to share it if it will help in that PR

For now to not waste time on more code ill wait a bit and see how this upstream PR goes and reuse the code later

Keep In mind for frontier use our version is ready for now.

**Comment by Tornado-Technology** [comment]
> > [space-wizards/space-station-14#23097](https://github.com/space-wizards/space-station-14/pull/23097)
> 
> Yooo thats fucking cool
> 
> Whlle having this as a tech and one time use per key wont 100% fit the frontier style, this has alot of the code work done that I wanted to make for this
> 
> Also we have the DoorSystem code done and I will love to share it if it will help in that PR
> 
> For now to not waste time on more code ill wait a bit and see how this upstream PR goes and reuse the code later
> 
> Keep In mind for frontier use our version is ready for now.

There is an Advanced key that is not wasted, but in general you can use ``DeemagComponent``.

**Comment by Cheackraze** [comment]
id say we keep this pr open or in draft mode until more movement is made on the upstream one, and then we can customize it for here and either add or augment whatever functionality its missing. I'm thinking of removing it from the sci tech tree and putting them in sec fabs as 1 time door fixers or something, but very nice to see both applications tbh

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
