### PR TITLE
Smooth transition for walls and windows icons

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Commented out some lines I know nothing about to restore smooth transitions between walls/windows/secret doors icons

## Why / Balance
Visual QoL

## How to test
Place different walls and windows, observe smooth transition from one entity to another

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
changes to base game files

**Changelog**
:cl: whatstone and whatstone
- tweak: Walls/windows/secret doors icons once again smoothly transition into each other.

### CODE REVIEW

**Comment by whatston3** [comment]
I'll need to look into this, but I'll bookmark it for later.

**Comment by GiggIess** [comment]
Hey, picture number five, near the bottom fire alarms; Are the diagonal walls supposed to "merge" into the door like that?

**Review by whatston3 — CHANGES_REQUESTED** [review]
After looking into this, I've put up a suggestion set at [whatston3:2024-07-14-5-state-diagonal](https://github.com/whatston3/frontier-station-14/tree/2024-07-14-5-state-diagonal).

As far as I can tell, having the diagonal walls set to window is a bug, they don't merge with other windows or walls.  Setting them to the walls key explicitly, rather than removing them (which does it implicitly through inheritance), seems fine.

I've also added a feature for a 5-state diagonal wall/window state, to better show connected state with other walls and windows, and added smoothing checks so you don't smooth a wall into the blank side of a diagonal wall.  The wood, uranium, and reinforced diagonal walls now use this new smoothing mode, and I think they look alright.  I think these changes are ready, and should be good to add.

Anything that's labeled as bricks or webs should probably be left separate, but I think walls can merge cleanly with shuttle/solid/reinforced walls without problem, diagonal or otherwise.

**Comment by ErhardSteinhauer** [comment]
> After looking into this, I've put up a suggestion set at [whatston3:2024-07-14-5-state-diagonal](https://github.com/whatston3/frontier-station-14/tree/2024-07-14-5-state-diagonal).
> 
> As far as I can tell, having the diagonal walls set to window is a bug, they don't merge with other windows or walls. Setting them to the walls key explicitly, rather than removing them (which does it implicitly through inheritance), seems fine.
> 
> I've also added a feature for a 5-state diagonal wall/window state, to better show connected state with other walls and windows, and added smoothing checks so you don't smooth a wall into the blank side of a diagonal wall. The wood, uranium, and reinforced diagonal walls now use this new smoothing mode, and I think they look alright. I think these changes are ready, and should be good to add.
> 
> Anything that's labeled as bricks or webs should probably be left separate, but I think walls can merge cleanly with shuttle/solid/reinforced walls without problem, diagonal or otherwise.

I, mean, you probably should merge your branch here then.

**Review by whatston3 — APPROVED** [review]
Merged it in.  Approving for now.

Sprites for windows and shuttle walls would be appreciated (could open an issue).

Might need to check again, but I think something's up with the diagonal tests for smoothing.

**Pull request merged**
