### PR TITLE
Technology disks: cleanup, removing references, upstream values

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Remove tech disks fully from the game.

## Why / Balance
This has made sci work into a single goal job, farm as many points as possible, print disks make millions.
No point in selling techs, no point in selling items, why even? when the profits wont match the millions made by just point farming for 6 hours.

## How to test
N/A

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
This PR will be merged only with https://github.com/new-frontiers-14/frontier-station-14/pull/2537

**Changelog**
Already in main PR

### CODE REVIEW

**Comment by Houtblokje** [comment]
> People do not buy enough tech to pay for a science ship. The specter would be a loosing prospect without the tech disks. They absolutely need a nerf but completely killing the disks without something else being provided as an option will just mean the only science ships you see are the small ones. My idea is severely cut the value, and also require people to have already filled the server before they can research tech disks.

Science is in a weird spot where people will shout for science and not get any, and scientists will advertise with science and nobody will hear them, and at the end of the round both customer and scientist will complain the other doesn't exist.

**Comment by dvir001** [comment]
> People do not buy enough tech to pay for a science ship. The specter would be a loosing prospect without the tech disks. They absolutely need a nerf but completely killing the disks without something else being provided as an option will just mean the only science ships you see are the small ones. My idea is severely cut the value, and also require people to have already filled the server before they can research tech disks.

Based on your feedback, I have removed all disk printing from the game fully as to avoid having any points to not unlock techs for sci to be selling them.

Buffs to over all sci will be coming in another PR.

**Comment by dvir001** [comment]
Were ready

**Review by whatston3 — COMMENTED** [review]
Generally looks alright.

Added a $200 price to 1k point discs (consistent with 5k/10k rates, and why not, I've seen them littered around before) - did something similar in the pending blue wreck rework, but these values seem fine.

Added a few comments in places.

Will double check vs. upstream when I can, but changes make sense.

**Review by whatston3 — APPROVED** [review]

**Pull request merged**
