### PR TITLE
Add Sakazuki (Sake cups) to Boozeomat

### PR DESCRIPTION
**Pull request by MoistBiscuits**
## About the PR

Adds the traditional sake cups to the boozeomat, inspired by @captainhonesty request on discord to make them more accesable
Added a new prototype that is empty since the current cup comes pre-filled with sake

## Why / Balance

clay cups are cool.

## How to test

Use the entity spawner and mess around with the boozeomat

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added sakasuki (sake cups) to the Booze-O-Mat

### CODE REVIEW

**Comment by dvir001** [comment]
Nice

**Comment by dvir001** [comment]
Please sync your pr with master.

**Comment by MoistBiscuits** [comment]
Branch synced, something else isn't happy. I will check this locally this evening for why the tests are failling.

**Comment by dvir001** [comment]
> Branch synced, something else isn't happy. I will check this locally this evening for why the tests are failling.

This is an issue on our side.

**Comment by dvir001** [comment]
Please pull again to remove all errors

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
