### PR TITLE
Gas Changes

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Updated gas worth numbers per upstream https://github.com/space-wizards/space-station-14/pull/32407

Removed all canisters from cargo, you can find them on about every single wreck on space or in dungeons

Upped canisters to 1000 base, added new small canisters that are worth 300 to all small ships.

## Why / Balance
Much needed balance pass for gas worth + canister base worth.

Make small ships start with small canister to encourage more game play related to filling them up and replacing them with the normal size ones (If you actually ever run out of air as they are still big to a point they last a shift on small ship)

## How to test
N/A

## Media
image

Presure and temps are the same, gas amount is 30% of a normal sized one.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Ship prices might shift a bit up and down, but wont change the sell back price to be lower since the gas themself have no added worth.

**Changelog**
:cl:
- tweak: Adjusted gas prices, replaced small and tiny ships canisters with smaller canisters.

### CODE REVIEW

**Comment by Houtblokje** [comment]
> Removed all canisters from cargo, you can find them on about every single wreck on space or in dungeons

Okay, sorry, I am concerned by this change, as nitrogen and oxygen tanks are very vital to the functioning of any ships. I understand the other ones, but those two seem too vital to remove.
This change seems like it could actively make the game worse, since it would push food ships and other ships that have no business salvaging into salvaging, and I would like a little more information as to how you would see these changes impacting the gameplay and how it would improve gameplay?

> Make small ships start with small canister to encourage more game play related to filling them up and replacing them with the normal size ones (If you actually ever run out of air as they are still big to a point they last a shift on small ship)

I do like this change, and I think there could be merit in replacing the ones bought in cargo with small ones so you would have to swap them frequently if you go the cargo-only route.

**Comment by arimah** [comment]
No. You will not restrict people's access to _air_. It doesn't matter that they're "on every wreck". There are no downsides to people having easy access to _the shit they need in order to breathe_. I also disapprove of you changing 50-odd map files in the same PR. This is a pointless change that solves no problem whatsoever.

**Comment by Tych0theSynth** [comment]
I don't like this one bit. Seriously making it harder for people to get something they need to breathe? Come on, Darin. 
Encouraging 'gameplay' of filling canisters up is...awful micromanaging. This is not meaningful, it will not encourage roleplay. 
Something that would be FAR more useful would be to alter the gas canisters on Frontier Outpost so people can't grief the station by opening them and leaving them open. 
I'm sorry to sound so negative, but I don't think this adds anything positive to the game.

**Comment by dvir001** [comment]
You all missed what this pr is and closed it, holy hell.

The canisters can very much stay a large ones with no price changes to ships at all, that was not even the notable change as this was added as a idea to have smaller ones that still last 6 hours.

Can you not just close it and let me actully comment and make changes?

I'll reopen it with my changes as new pr.

**Pull request closed without merging**
