### PR TITLE
Fix Pseudo Code

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Match ``PseudoItemSystem`` and ``CarryingSystem`` with DeltaV
Update some of the old ``SizeAttributeSystem`` with new in backpack sizes.

## Why / Balance
Was very weird to have humanoids take close to no storage.

Also needed for https://github.com/new-frontiers-14/frontier-station-14/pull/2009 if we ever merge it

## How to test
Put felinid and goblins in backpack.
Small vulp and small lizard.

## Media
image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by whatston3** [comment]
image
Yes.

**Review by whatston3 — APPROVED** [review]
Made the Goblin shape into a 4x4 parallelogram, they still fit into a backpack, but are more reasonably sized compared to the felinids' 26 square kidney bean shape.  Added fields for storedOffset, storedRotation, and shape into the Short/TallWhitelistComponent, and added the storedRotation to the PseudoItemComponent.

For a reason I don't currently quite understand, the angle being used for storeRotation in the PseudoItem needs to be half of what it should be.  I have a feeling this is why the goblin was upside down by default.  I've noted it as a bug, but as written, it works alright.

image

**Comment by dvir001** [comment]
Nooo it wasss funny

Oh well, looks fine.

**Comment by ErhardSteinhauer** [comment]
Still not a triangle 😭

**Pull request merged**
