### PR TITLE
Expeditionary Lodge: Small QoL Update

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Mapped NonLethalVend to practice range.
- Mapped mass scanner and disposal bin by shipyard consoles.
- Some additional vendomats by the dock 2.

## Why / Balance
QoL

## How to test
1. Spawn in, 
2. Get to exped lodge.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Small QoL update of the Expeditionary Lodge.

### CODE REVIEW

**Review by whatston3 — APPROVED** [review]
Changes look good.  The new vendors around dock 2 are the ones at the corner of the stall, right?  New vendors are a tank dispenser and the AstroVend?  Nice to have, no problems there.

One thing I'll ask (not really relevant, but while you're here) - the red airlocks near dock 4 don't have techmaint flooring under them, you can see the exposed pipe and wires.  Could this be fixed here?

Finally, nerf range.

**Comment by ErhardSteinhauer** [comment]
> One thing I'll ask (not really relevant, but while you're here) - the red airlocks near dock 4 don't have techmaint flooring under them, you can see the exposed pipe and wires. Could this be fixed here? Edit: this is also true for the external airlocks at docks 1 and 2.

Good catch! Should be fixed now.

**Comment by ErhardSteinhauer** [comment]
> Changes look good. The new vendors around dock 2 are the ones at the corner of the stall, right? New vendors are a tank dispenser and the AstroVend?

Yeah, those. However I'll probably replace one of them with FuelVend someday.

**Review by whatston3 — APPROVED** [review]
Thank you!  Retested, reapproved.

**Pull request merged**
