### PR TITLE
McCargo Changes

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Updated the tables, added a lock toggle for the back door area to stop people from running into back room storage,
Moved the cow away from the freezer to make sure its not eating the monkey meat.
Updated the AME area look.
Added mirrors in restroom area
Replaced the safe with empty new safe for captain.
Update decals next to entry area

## Technical details
Mapping changes

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame,

image

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
image
For whatever reason, shutters and blast doors will not close over opaque airlock doors but they will over glass airlock doors.  Something you might want to consider when using this type of layout.

**Comment by ErhardSteinhauer** [comment]
> You might want to change this to bolt the door instead of having a shutter on it.

Would like to point out small quirk with this proposition: bolting doors is instantaneous whereas shutter closing animation takes a bit of time, so it's possible to desynchronize door bolts with shutters if you aren't careful with that button.

**Comment by MagnusCrowe** [comment]
> > You might want to change this to bolt the door instead of having a shutter on it.
> 
> Would like to point out small quirk with this proposition: bolting doors is instantaneous whereas shutter closing animation takes a bit of time, so it's possible to desynchronize door bolts with shutters if you aren't careful with that button.

Fact.

**Comment by MagnusCrowe** [comment]
Other than the weird door stuff that you may or may not want to fix, I approve.

**Comment by dvir001** [comment]
> Other than the weird door stuff that you may or may not want to fix, I approve. Just let me know if you're not going to fix it and I'll merge this.

Its doing bolt and shutter, its intended when upstream fix this issue.
Its fine.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
