### PR TITLE
Adds the NSF Blade M EMP Vessel

### PR DESCRIPTION
**Pull request by UncaughtEx**
## About the PR
Adds the NSF Blade.

## Why / Balance
We needed something to replace the Marauder

## How to test
Spawn in as NFSD
Buy the Blade for 40k

## Media
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
N/A

**Changelog**
:cl:
- add: Introducing the NSF Blade, a replacement for the Marauder which comes with a homey RV Feel.

### CODE REVIEW

**Comment by dvir001** [comment]
Do not use syndicate airlocks

**Comment by UncaughtEx** [comment]
Noted regarding the Airlocks
And how would I go about giving the grid EMP immunity

**Comment by MagnusCrowe** [comment]
image
Don't put lattice under docking ports, unless you love this happening whenever someone with wirecutters is pissed at you.
image

image
Tight Squeeze...perhaps re-locate the thruster?

image
I feel like the fancy diamond tile is a little to extravagant for an exterior walkway.  I recommend something a bit more utilitarian.
image
image

image
Uh oh...I just EMPed my pants (and the rest of the ship).

image
All of your NFSD doors are not access locked.  They probably should be brig locked at the very least.  

image
This is brig locked, it should be security locked...so lawyers can't just walk in and out.

image
Please don't place drink vendors on ships.  You may use a sink or a water cooler where appropriate though.
See this example.
image

image
For a ship meant to interdict criminals, it strikes me as extremely extravagant.  It's the type of ship that is likely to be the first ship on the scene of an altercation, one that will see combat as it's main function.  I don't really think it's the type of ship that should have full length runner carpets, arcade games, or nice sitting/lounge areas.  I'd like to see this space used more wisely and with the intention of the ship in mind.

There is a possible use case for a fancy NFSD ship though.  A VIP armored transport ship would be pretty sick...would be able to use something like that in future special events...I digress.

I would recommend a remodel to something similar to what is below.  vvv
image
This gives you the same power generation/storage, gyros, atmos, lockers...It also gives you an armory for storing weapons and dangerous contraband and a more protected nook for bunks (cozy counts).
image
I also redid the power and atmos layout...woops I forgot to hook the new armory into the atmos system.

**Comment by UncaughtEx** [comment]
I like that remodel
Could I get the file for that?

**Comment by MagnusCrowe** [comment]
> I like that remodel Could I get the file for that?

I didn't save it 😱

**Comment by UncaughtEx** [comment]
> > I like that remodel Could I get the file for that?
> 
> I didn't save it 😱

Damn
Ill get around to modifying it when I have the energy

**Comment by dvir001** [comment]
Closing this till issues addressed, feel free to reopen at any point ones the PR ready again.

**Pull request closed without merging**
