### PR TITLE
NSF Broadhead (New) - Medium Detective NSFD Vessel

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR

Adds a new shuttle, the NSF Broadhead, a medium-size detective shuttle with a brig & interrogation room, combined evidence storage & armoury and mortuary with autopsy facilities. Comprehensive detective roleplay is this intention with this shuttle, providing a space where multiple investigators can work together.

This shuttle gets its name from the profile, inspired by the arrowhead of the same name. The name is somewhat metaphorical, as broadheaded arrows are designed to do a lot of damage and be hard to remove; much like the effect that an adept detective's work can have on your criminal enterprise. 

This shuttle is a joint project between myself and @Gotimanga who have both wanted to see a detective ship in the game that provides an alternative to the Interceptor and the Inquisitor, both of which we have found a bit lacking and seem to rarely be used.

A little lore, with the above in mind: The Broadhead was designed by Aila Azure of BlueBird Shipbuilding (SBB) and Deeja-Wujeeta (detective) under contract for NanoTrasen. 

## Why / Balance

At the moment, detectives currently have two specialised shuttles to choose from, which, in my opinion, both have issues that make them offputting and difficult to use:
- The Interceptor is very small, has unlinked shutters at the start, but other than that is fine for a solo detective. You have some office space, a little brig which also works for questioning, but not much beyond that. 

- The Inquisitor, which feels like a larger and more weirdly shaped Interceptor. Other than an extra cell, it doesn't feel like it really adds anything considering its increase in size. It also feels very strange to fly, considering the orientation of the shuttle itself.

Because of this, I've had several shifts as detective where I've either joined a Prowler, taken a different ship or reworked an Esquire in conjunction with other detectives as opposed to using the two available det ships. 

In particular, my experience reworking an Esquire as a detective cooperative ship with two other dets made me wonder: what if there was a larger detective ship that had some more comprehensive facilities for deeper casework and enough space for multiple detectives to work together? This is the result of that.

I've tried to keep wiring and piping under walls to a minimum, but what is there is unavoidable. In testing, it felt very comfortable with between 2-4 people on board, but feels a little big if you're solo. Hopefully that'll encourage detectives to work together or work with a deputy! The detective's office has plenty of room for holding a discussion between multiple persons. 

What she's got/why she's got it (design notes): 
- An AME, as she's quite power hungry.
- A detective's office and a small bunk room which has a deputy's locker, so that a detective and deputy can work together.
- A single cell brig with prisoner locker and a wall locker for prisoner EVA. There is an adjacent interrogation room with an extra chair for a lawyer and a button which bolts the door and turns off the light, allowing for aggressive use of the interrogation lamp.
- A combined armoury/evidence lockup with two evidence lockers, a sectech, a gun rack and a deputy's locker secured behind a windoor. The intention with the extra secure locker would be to use it to store ammunition or highly sensitive evidence or contraband.
- Extra detective equipment for detectives who do not join with the job at spawn.
- An NFSD deputy hardsuit locker at each airlock, respectively. 
- A bridge with included IFF console and mass scanner. As the forward visibility isn't the best, the mass scanner is quite handy for navigation.
- Strong forward acceleration from the eight forward thrusters. Turning and reverse performance feels adequate at the start and only gets better with upgrades. 
- A medical forensics lab composing of a surgery table and two morgues for storing corpses. Now you have a place to roleplay determining the cause of someone's death!
- An aggressive profile. I'd feel nervous if I saw this thing begin to follow me.
- A sustenance vendor for prisoners or long sorties. 
- The narrow corridors allow for ambush opportunites by/against boarding parties.

Statistics: 
- Tile count: 331 (medium).
- Appraisal price: 47600.
- NFSD Shipyard price: 50000 (just above 5% in order to make it a round number. Exactly 5% is 49980 and that annoyed me.)
- Recommended crew: 2-4.
- Available roles: Detective, Deputy (SecurityOfficer).

## How to test

Checkout the PR and buy it at the shipyard!

## Media
broadhead_uninit
(Unitialised, showing subfloor and spawns)

broadhead_init_nolights
(Initialised, shadows off)

broadhead_init_lights
(Initialised, shadows on)

Broadhead_radar
(Radar profile)

broadhead_bridge
(Command rooms)

broadhead_brig
(Brig and interrogation room)

broadhead_armoury
(Evidence room & armoury)

broadhead_morgue
(Morgue and autopsy lab)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None!

**Changelog**

:cl: Tych0theSynth and Deeja
- add: Added the NSF Broadhead, a new medium-size detective vessel.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
As I was writing the PR, I realised we forgot to add both a fire extinguisher and defibrillator. This will be rectified in a later commit (probably tomorrow).

**Comment by Tych0theSynth** [comment]
> > As I was writing the PR, I realised we forgot to add both a fire extinguisher and defibrillator. This will be rectified in a later commit (probably tomorrow).
> 
> You will have to redo all floors and doors to the new NFSD colors Also map no guns or weapons, they are getting cut off ships No books mapping, they are all broken in upstream update. Do not open any jobs, or add job spawns, it has to be 0 unless its a capital ship (Not the case here). Use the security folder to save the ship file

Thanks for the feedback, Dvir!
- The doors and decal work were done before the NFSD recolour so I had a feeling we might be asked to change that. Easily fixed!
- Noted about the book and weapons. I'll find something to put in their place. 
- Is not including the job spawns an NFSD shuttle thing? I was not aware, but it will be changed.

Once I've done all of this, it'll be moved to the security folder.

**Comment by Tych0theSynth** [comment]
Made the following changes to the NSF broadhead following review:
- Recoloured relevant decals to be in line with the new NFSD colour scheme.
- Removed books.
- Removed weapons. Replaced with empty gun rack and deputy locker.
- Removed job spawns.
- Replaced security lockers and vendors with their new NFSD variants. 
- Replaced security hardsuits with NFSD hardsuits.
- Added defibrillator and fire extinguisher.
- Redesigned prisoner cell to be slightly more humane. 
- Replaced custom fill wallmount prison closet with a filled prison locker.
- Moved the shipyard file and grid file to their respective security folders.

(PR description will be updated accordingly and screenshots replaced)

**Comment by MagnusCrowe** [comment]
Does this ship really need an AME?

**Comment by Tych0theSynth** [comment]
> Does this ship really need an AME?

If you look at basic power consumption: nope! It'll probably work just fine with a couple of regular PACMAN generators. The reasoning for it was that, like the Prowler, this thing could spend a decent amount of time away from a fuel source and that AME longevity might be useful.

**Comment by dvir001** [comment]
Update with master to get the new gyro and thrusters.

**Comment by Tych0theSynth** [comment]
> Update with master to get the new gyro and thrusters.

Security thrusters and gyro have been replaced with the new NFSD ones

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
Replace the nanotrasen bedsheets with NFSD sheets.
image
Remove the badge from the desk.  Players will start with those when they spawn and we aren't in the business of mid-round sec hires nowadays.
image
Remove the vending machines.  Players will start with whatever loadout equipment they need or they will purchase it from the NFSD station, not aboard ships.
Also, remove the spare forensic gloves, there's already a pair in the cabinet in the captain's quarters and also it's part of detective loadout.
image
Remove the vending machine, patronize your local eateries instead.
image
Stick a jar of AME fuel in and turn on the AME before saving the grid so the ship comes in already started.

Other than all that, another banger of a ship!

**Comment by Tych0theSynth** [comment]
Requested changes have been made, along with some extra bits:
- Removed vendors.
- Removed forensic gloves and badge.
- Replaced bedsheets with the NFSD variants.
- Moved suit storage lockers to where the vendors were located.
- Changed some doors now that the windowless versions are available.
- Replaced NFSDTech vendor in secure storage with a filing cabinet. (for super special case files)
- Added button frames.
- Replaced glass airlocks and lockers as their prototypes were changed.
- Replaced Seclite with NFSDlite.
Broadhead Update
2024-06-03 11_15_12-Frontier Station

**Comment by MagnusCrowe** [comment]
> Requested changes have been made, along with some extra bits:
> 
> * Removed vendors.
> * Removed forensic gloves and badge.
> * Replaced bedsheets with the NFSD variants.
> * Moved suit storage lockers to where the vendors were located.
> * Changed some doors now that the windowless versions are available.
> * Replaced NFSDTech vendor in secure storage with a filing cabinet. (for super special case files)
> * Added button frames.
> * Replaced glass airlocks and lockers as their prototypes were changed.
> * Replaced Seclite with NFSDlite.
>   Broadhead Update
>   2024-06-03 11_15_12-Frontier Station

Thanks, I'll probably merge it this weekend after I review it.  Looks good.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
