### PR TITLE
Fix biogenerator and cutter machine board not accepting modular compo…

### PR DESCRIPTION
**Pull request by KieueCaprie**
## About the PR

As of the recent update, certain machine boards have been unable to be crafted via the machine frame method. Initially, I had thought something was absolutely wrong until I checked the code and found the culprits being out of sync with the rest of the boards, so I've updated them.

It's worth noting that the station anchor machine board also doesn't accept modular components but I've left it untouched for now because I'm unsure about its purpose in the grand scheme of things when it comes to Frontier.

## Why / Balance

Because being unable to craft a biogenerator or cutter makes me sadface.

## How to test

* Step 1: Spawn a machine frame construction ghost and do the steps as normal up until you apply a machine board. Spawn in a biogenerator machine board or a cutter machine board.
* Step 2: Follow the component guide for the machine board, inserting the requisite materials and components.
* Step 3: Use a screwdriver to complete the construction
* Step 4: Type *claps! in chat for a job well done!

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- fix: Station anchors, biogenerators and cutters can now be assembled properly.

### CODE REVIEW

**Comment by dvir001** [comment]
PR Has to contain frontier comments and same as other machines logic

**Comment by KieueCaprie** [comment]
Ah, rookie mistake (I mean, I _am_ but still), will fix.

**Comment by GreaseMonk** [comment]
Hey it's your first (technically second but that one closed) PR! Welcome to the contributors club

**Comment by KieueCaprie** [comment]
Yeah, the first one auto-closed because I forgot about the branch thing, lol. I _think_ I did this correctly now?

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
