### PR TITLE
The SBI Beaker

### PR DESCRIPTION
**Pull request by UncaughtEx**
## About the PR
Adds the SBI Beaker, a Chemistry focused ship with a closed off Atmos setup.

## Why / Balance
I've noticed in the wide array of ships we have on offer, that we lack a purely Chemistry option.

## How to test
Spawn in
Buy Beaker from Shipyard
COOK
## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: With permission from the NT Pharmaceuticals branch, fresh from the Fabs, SBI would like to introduce the Beaker Shipyard License approved for distribution! Yeah, Science!

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Chemistry ship, my beloved.

**Comment by ThatOneGoblin25** [comment]
Consider swapping the docking airlocks to glass variants, and the maints airlocks to the thrusters to red external airlocks.

**Comment by UncaughtEx** [comment]
> Consider swapping the docking airlocks to glass variants, and the maints airlocks to the thrusters to red external airlocks.

I like the idea of the airlocks being opaque since it gives the Ship a more concealed feel.
As for the thruster airlocks, I think the dilating airlocks add to the aesthetic.

**Comment by MagnusCrowe** [comment]
> > Consider swapping the docking airlocks to glass variants, and the maints airlocks to the thrusters to red external airlocks.
> 
> I like the idea of the airlocks being opaque since it gives the Ship a more concealed feel. As for the thruster airlocks, I think the dilating airlocks add to the aesthetic.

They aren't wrong about the red airlocks.  If you want an external door it should be obvious to players that it is an external door.
That being said, I'm open to the creation of new styles of external doors.  If you want a cool aperture door like that, you'll want to create a new one that unambiguously indicated that it is a door to space.

I don't care if you use opaque or clear docking ports, that's up to you.

**Comment by UncaughtEx** [comment]
> > > Consider swapping the docking airlocks to glass variants, and the maints airlocks to the thrusters to red external airlocks.
> > 
> > 
> > I like the idea of the airlocks being opaque since it gives the Ship a more concealed feel. As for the thruster airlocks, I think the dilating airlocks add to the aesthetic.
> 
> They aren't wrong about the red airlocks. If you want an external door, it should be obvious to players that it is an external door.
> 
> That being said, I'm open to the creation of new styles of external doors. If you want a cool aperture door like that, you'll want to create a new one that unambiguously indicates that it is a door to space. That's going to involve creating/finding a new sprite and creating a prototype for the door.
> 
> I don't care if you use opaque or clear docking ports, that's up to you.

Then I concede on the thruster airlocks, I'll change them over when I get a chance.

**Comment by UncaughtEx** [comment]
image

**Comment by MagnusCrowe** [comment]
image
Can I recommend you to treat the superpacman as if it were radioactive?  Just incase we decide to make that generator emit radiation in the future?

**Comment by UncaughtEx** [comment]
Recommendation noted
Ill add the suggested changes in a bit

**Comment by UncaughtEx** [comment]
Made the engineering a bit more rad proof
Added an engineering access locked button

**Comment by UncaughtEx** [comment]
image

**Review by MagnusCrowe — APPROVED** [review]
image

**Pull request merged**
