### PR TITLE
Mail Menace (New) - The blackmarket mail ship

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
_"Mail is no longer an option: you either receive it or you die."_, - Shipyard.
**Ship size:** Small
**Recommended crew:** 1-3
**Cost:** 76000
**Power Gen Type:** AME
**Expeditions:** No
**IFF Console:** Yes
**Available Roles:** None

## Why / Balance
Black market mail truck.

## Technical details
.ymls

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- add: Added The Menace - black market mail truck.

### CODE REVIEW

**Comment by KM-Catman** [comment]
I think this is a new record on smallest AME ran ship

**Comment by ErhardSteinhauer** [comment]
Should place an expedition console there tbh.

**Comment by Wolfking6116** [comment]
I love this.

**Comment by dvir001** [comment]
Updated this to match master, make sure to pull changes

**Comment by MagnusCrowe** [comment]
Why does this ship have an AME?

**Comment by dvir001** [comment]
> Why does this ship have an AME?

For suicide.

**Comment by ErhardSteinhauer** [comment]
> Why does this ship have an AME?

Intimidation tactics.

**Review by Cheackraze — APPROVED** [review]
funny

**Pull request merged**
