### PR TITLE
buff ore box (DeltaV #2468)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
https://github.com/DeltaV-Station/Delta-v/pull/2468

## Why / Balance
https://github.com/DeltaV-Station/Delta-v/pull/2468

## How to test
N/A

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: deltanedas
- tweak: Ore and plant box storage has been increased from 60 to 200 slots.

### CODE REVIEW

**Comment by whatston3** [comment]
Not against it - 4x storage?  Do note that our ore stacks are larger.  Also, doing this for the plant box would probably be nice.

**Comment by archemical** [comment]
I'm assuming this is in preparation of removing infinite storage from ore processors, because if not--why? Ore processors already serve as infinite storage for ores, and an ore box with 4x the storage is all but infinite, especially for something that appears to be a simple cardboard box. This seems antithetical to recent dialogue around 'infinite storage bad.'

**Comment by dvir001** [comment]
> Not against it - 4x storage? Do note that our ore stacks are larger. Also, doing this for the plant box would probably be nice.

Done

**Comment by whatston3** [comment]
Fine overall, if it needs a tweak later, so be it.

**Review by whatston3 — APPROVED** [review]

**Pull request merged**
