### PR TITLE
Adds station guard uniform jumpsuit and skirt

### PR DESCRIPTION
**Pull request by MagnusCrowe**
## About the PR

Adds a uniform for a station guard officer.  It can be found in the uniform printer with the rest of the uniforms.  I left it out of the secdrobe because it is not an official security position.

## Why / Balance

We may want to add a station guard and I was struck by inspiration to create a uniform for them.

## Technical details

Uniform costs 3 pieces of cloth in the uniform printer like the other jumpsuits/jumpskirts.

## Media

image

image

image

image
Monkey get's a piece of the drip too.

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: MagnusCrowe
- add: Added station guard jumpsuit and jumpskirt.

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]
Linter happy, files goods.

Good job! and im thinking if we should have a Station Guard Job.
But that to debate.

**Comment by dvir001** [comment]
> Linter happy, files goods.
> 
> Good job! and im thinking if we should have a Station Guard Job. But that to debate.

Honestly we can just add it, if feedback is bad just remove it from the list and call it a day.
No issues with giving it a go.

**Comment by FoxxoTrystan** [comment]
> > Linter happy, files goods.
> > Good job! and im thinking if we should have a Station Guard Job. But that to debate.
> 
> Honestly we can just add it, if feedback is bad just remove it from the list and call it a day. No issues with giving it a go.

True that.

**Comment by Buldinn** [comment]
Looking forward to being station security in style

**Review by dvir001 — APPROVED** [review]
Love it

**Pull request merged**
