### PR TITLE
Adds the "Opportunity" prison expedition ship.

### PR DESCRIPTION
**Pull request by MagnusCrowe**
## About the PR
Introducing the "Opportunity" prison expedition ship. A medium ship for the New Frontier Sheriff's Department. 
It holds up to 4 prisoners and can accommodate a warden and several prison guards (probably 3-4 would suffice). 

Ship costs 70000 spesos and is only available at a security shipyard console.
The ship runs off of one uranium generator which should be set to 50 at all times.

The ship comes equipped with:
- Exterior blast door access for guards to release prisoners to the planet surface from their cells.
- Prisoner EVA suits for hostile planetary environments.
- Warden and 3 secoff suit lockers
- Warden locker
- Gun locker with a Kammerer and ammo, and body bags
- A non-lethal crate
- A uranium crate
- 4 ore crates for prisoner ore storage
- 4 pickaxes and 4 orebags
- Prison guard uniforms
- Standard perma accommodations
- Air alarms!

## Why / Balance
This will enable prisoners the option to be taken down to a planet to serve their prison terms mining ores.
This should enhance the prisoner experience by providing unique opportunities to sincerely serve their terms or to get up to shenanigans.

Forced labor is not alright, so prisoners shall not be forced to work.  They may stay in their cells or perhaps even in the perma common area during expeditions if they wish.

Prisoners should have their ores returned to them once their term is up unless they wish to part with some or all of them to shorten their term.

## Media
In glorious color!
Opportunity Normal
Full bright!
Opportunity Fullbright
Subfloor and spawns!
Opportunity Subfloor

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: MagnusCrowe
- add: Added the "Opportunity" prison expedition ship.

### CODE REVIEW

**Comment by Everturning** [comment]
add prisoner spawn

**Comment by Cheackraze** [comment]
just some incredibly minor things and this ones ready. Mostly that its missing a fax machine. The other is this sin against mappers everywhere:

image

poster on top of windows look funky.  Other than that, I think one of your buttons shares a wall spot with an APC and makes it hard to click.  But basically just need a fax machine put somewhere and I'll merge it, everything else looks fantastic.

**Comment by MagnusCrowe** [comment]
> just some incredibly minor things and this ones ready. Mostly that its missing a fax machine. The other is this sin against mappers everywhere:
> 
> image
> 
> poster on top of windows look funky. Other than that, I think one of your buttons shares a wall spot with an APC and makes it hard to click. But basically just need a fax machine put somewhere and I'll merge it, everything else looks fantastic.

Yeah forgot the fax. Also I'm not married to the window label.

**Comment by MagnusCrowe** [comment]
image
I've moved the APC, removed the docking poster, and added the fax machine.  The baliff suit storage was removed to make room for the fax and the baliff locker has been updated to be a baliff locker+hardsuit.

**Comment by MagnusCrowe** [comment]
image
Also, toilets!!

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
