### PR TITLE
Bureaucracy Loadouts, Doctor, Engineer Stamps

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds a bureaucracy loadout group with paperwork and stamps.  Available for non-NFSD/antag jobs.
Adds a squiggly signature sprite.
Adds loadout options for an engineer's stamp, doctor's stamp.
Cleans up some Frontier-specific stamps into _NF folders.
Pirate bounty reminders now spawn with a pirate stamp (should look like a tiny skull).

## Why / Balance

Part of this: https://discord.com/channels/1123826877245694004/1265352033205223546

## How to test

1. Experiment with the loadouts, pick some bureaucracy options, they should spawn in-game.
2. Sign a paper, note the stamp.
3. Spawn a pirate bounty, note the stamp (note: not currently actually stamped, should fix this.)

## Media

image

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Bureaucracy loadout options are now available for all jobs apart from NFSD and antag roles.

### CODE REVIEW

**Comment by whatston3** [comment]
Cleanup needed, one moment.

**Comment by whatston3** [comment]
History's been cleaned up, testing again, everything seems fine.

**Review by dvir001 — APPROVED** [review]

**Comment by Moomoobeef** [comment]
I know the PR is two years old, but I thought someone should know that you forgot to add your new sprites to the "copyright" section of either of the meta.json files where you made changes/added sprites.

I'm working on a PR that would port your signature sprite to another fork, and I noticed this detail, so again, I thought I should point it out.

**Comment by whatston3** [comment]
Should all still be CC-BY-SA 3.0, the basis for the work for the doctor/engineer's stamp was the existing CE and MD's stamp [taken from] https://github.com/tgstation/tgstation/commit/fb1012102257b7b0a08d861fd2b8ba963c416e93

paper_stamp-nf-pirate and paper_stamp-nf-signature are WhatstoneOriginals™, still fine under CC-BY-SA 3.0.

paper_stamp-nf-doctor and -engineer also based on existing tgstation work [taken from] https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432.

If I was happy enough to waive [adding my dumb name] the copyright, it's a good sign that it's not that big of an issue to me.

**Pull request merged**
