### PR TITLE
Esquire, Lawyer Ship

### PR DESCRIPTION
**Pull request by terezi4real**
## About the PR

Adds the Esquire, a classy mid-sized vessel with a lawyers office, waiting room, prisoner handling/intake, a small cell, sec breakroom and a decently sized engineering area.

This ship can be bought by fledgling attorneys looking to defend the wrongfully, and rightfully, arrested clients of the frontier, or purchased by HoS, allowing for a lawyer to spawn in the latejoin slot and possibly work as defense or prosecution alongside sec. This ship is also well equipped to be quickly gutted and transformed into an transport, luxury, or cargo vessel.

Made a new pull request as i started this on one branch, tried to move it to a renamed branch, which got vscodium angry, this was the simple way out.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Esquire

### CODE REVIEW

**Review by Cheackraze — APPROVED** [review]
27k is a bit pricy for an RP ship IMO. If it appraised at 21k, I'd say this is the perfect candidate for like, a 24k ship.  Gives a new "Lawyer Character" exactly 1k to spend on lunch for the shift loool.

**Comment by Cheackraze** [comment]
also you dont have to close and reopen, you can just make a small edit and push the commit before I merge it.

**Comment by terezi4real** [comment]
price pushing in a second here, and yes i kno, but i did some fuckery with renaming a branch and trying to move the stuff over and it ended up just being easier to make a new PR.

**Comment by terezi4real** [comment]
oops no gyro, will add when i feel like opening mapping tools

**Comment by terezi4real** [comment]
requested note: ship spawns off station when i try to buy it, unsure

**Comment by sTiKyt** [comment]
> requested note: ship spawns off station when i try to buy it, unsure

It's because of `Debug` or `Tools` build, should spawn properly on `Release`

**Comment by Cheackraze** [comment]
image
this is why it wasnt docking, you only have the assembly frames not the complete dock.  I'm going to make just some slight tweaks and then get this in game rq

**Pull request merged**
