### PR TITLE
Mission Shuttle - A Religious Ship

### PR DESCRIPTION
**Pull request by kennedytcooper**
## About the PR

Adds the Mission a religion and cleaning shuttle featuring a chapel, crematorium, and full janitorial services.

**Media**

Screenshot from 2023-07-30 11-56-21

**Changelog**

:cl:
- add: the mission ship, a religious & cleaning shuttle

### CODE REVIEW

**Comment by Cheackraze** [comment]
i went to review this one to try to add it soon but I think you made a mistake when you were copying files. You have 2x the same file in both places, but it looks like you meant to have the ship file itself there.

**Comment by kennedytcooper** [comment]
Oops! Try it again at your convenience, it's fixed now

**Comment by Cheackraze** [comment]
I like the overal design and the compact feel, but there are just a few minor things that would make it even better
image
the big glass structure/window is a great idea and we can keep that aesthetic and view, but it makes the whole shuttle vulnerable to pirate laser fire, so I suggest replaceing the areas marked in green circles with shuttle walls.
Angled walls don't block vision properly either, and when used like where you have them marked in blue makes the view look bad, so try to put a few solid walls here to actually block vision, even if you have to make that wall 'thicker' by doing so.

**Comment by kennedytcooper** [comment]
ready fore review again

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
