### PR TITLE
SS14 Sign 

### PR DESCRIPTION
**Pull request by potato1234x**
## About the PR

might as well do some minor changes check off some of the list

**Media**

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Potato1234_x
- tweak: The SS14 sign now says Frontier Station.

### CODE REVIEW

**Comment by Cheackraze** [comment]
its good, dont get me wrong, but I think you could make it even better, give it some flair or something idk, you're pretty dang good with sprites I believe in you

**Comment by potato1234x** [comment]
maybe make it gold kinda like the fulpstation sign? any specific ideas?

**Comment by Cheackraze** [comment]
maybe some kind of object in the background, kind of like uh I think origin station has a custom one with a planet? maybe a space ship or something or maybe just like a better border or something idk, overall it might be better to try to keep it greyscale for color so that mappers can customize it

**Comment by potato1234x** [comment]
just a concept but something like this?
image

**Comment by potato1234x** [comment]
image
or in between the text?

**Comment by No-Dad-Not-The-Belt** [comment]
> image or in between the text?

+1 to this if the ship is angled at a 45 behind the text for the sign, but before the face-plate. Design is cool regardless.

**Comment by potato1234x** [comment]
> >  or in between the text?
> 
> +1 to this if the ship is angled at a 45 behind the text for the sign, but before the face-plate. Design is cool regardless.
image
like this? (again just a prototype)

**Comment by Cheackraze** [comment]
> > > or in between the text?
> > 
> > 
> > +1 to this if the ship is angled at a 45 behind the text for the sign, but before the face-plate. Design is cool regardless.
> 
> image like this? (again just a prototype) or this? image

coming along great, I like this a lot (with more polish of course) but I think that idea is great

**Comment by potato1234x** [comment]
added some more shading to it, this is it in game
image

**Comment by potato1234x** [comment]
no idea how to improve more, committed

**Comment by Cheackraze** [comment]
> no idea how to improve more, committed

looks good as is, always could be improved upon later too if you or anyone else gets inspired.

**Review by Cheackraze — APPROVED** [review]
since we are replacing the old station plaques, I'm approving this but going to wait to merge till the next time I can go over the station map again. I recently did a hasty edit to add borg support but I want to better organize the mail area and make a few more significant station changes in the next 1-2 weeks.  Just know its approved 100%, just may not get merged for a little bit yet, and if you feel inspired you're welcome to continue improving it in the meantime.

**Pull request merged**
