### PR TITLE
Added Empess cryosleep

### PR DESCRIPTION
**Pull request by DmitriTheDemon**
## About the PR

Added cryosleep chamber to empress in place of morgue slab

## Why / Balance

As a flagship the empress when pulled typically remains in the game for the remainder of the round as a pseudo-headquarters. It also frequently collects SSD players from prisoners quitting when incarcerated and officers who are unable to return to NFSDO independently. This would allow for them to be placed into cryosleep without having a wall of Zzz bodies.

Additionally, because the ship typically remains the entire round not being able to uncryo for returning players is not as significant of a concern.

## How to test

Spawn empress, validate cryopod exists, cryo, uncryo

## Media

Empress Cryosleep
Empress Uncryo

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

N/A

**Changelog**

:cl:
- tweak: Added cryosleep pod to Empress

### CODE REVIEW

**Comment by dvir001** [comment]
Can't map them on ships till we fix the code,
Right now if you cryo then someone sell the ship you get nuked and cannot respawn out from cryo.

**Comment by whatston3** [comment]
> to be honest if you cryo on a ship and ship gets sold, we kinda need a system that , in case it gets sold, it moves the body to frontier or something- ideally.

Gimme a sec.

**Comment by dvir001** [comment]
This PR is fine now

**Comment by dvir001** [comment]
@DmitriTheDemon 
image

You will need to redo this PR as you saved this as a map and not a grid

**Comment by dvir001** [comment]
Fixed the map issue for you.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
