### PR TITLE
Salvage Expeditions Rebalance: randomized loot, cash only rewards, extended time

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### General expedition tweaks
- Extended expedition time limit to 15 min.
- Limited rewards for completed expeditions to cash only, sum depends on expedition difficulty: minimal - 5k, minor - 10k, moderate - 15k, hazardous - 20k, extreme - 25k.
- Removed edible food items and food vendomats from dungeon templates.
- Replaced almost every single one static loose item in dungeon templates (including new templates added after upstream merge) with randomized spawner of loosely same type thematically.
- Replaced locked doors on snowy labs with unlocked.
- Added new dungeon theme: virology lab.

### Other changes:
- Extended frontier color palette: more merc colors, added virology colors.
- Guns, obtainable in expeditions (either loose or in secure crates or in weapon cases), are classified as contraband since they aren't "registered".
- Guns on expeditions now spawn in weapon cases with spare magazines or ammunition.
- Weapons that are hard to see on their own (like energy swords/daggers/shields) spawn in small weapon cases.
- Duffel bags with shuttle guns were replaced with newly added weapon cases.

### Randomized loot and fluff item spawners.
A bunch of randomized spawners for common items and machines encountered in expedition dungeons so to bring more visual variety to mundane things scattered about and to add a little bit more valuables to the loot pool expeditions offer. 
Generally spawners are thematically tied to departments (rn engineering, medical, hydroponics, science, sec/mercenary, salvage and kitchen are present) and loosely divided between the following categories:
- Clutter. It's mostly fluff, but occasionally can yield valuable items. Utilizes spawners from other categories.
- Tools. Individual tools or toolkits. In case of sec/mercs tools = weapons.
- Clothes. Self-explanatory, includes hardsuits. In case of sec/mercs also includes armor.
- Furniture/Lockers. Mostly lockers.
- Machines. Covers vendomats and lathes.
- Other. Materials (full stacks and individual items), ores (full stacks and individual items), parts (T1-T4), circuits (a chance to find any existing in the game circuit), cash stacks (10 - 30000), medkits and healing items (full stacks and individual items) stuff like that.

## Why / Balance
To increase variety of loot available from expeditions. No more 1000 upon 1000 of power drills.
And to make expeditions slightly more profitable than they are right now, so it could compete with low to mid effort mining or science.

## How to test
Delve into salvage expedition.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
yml file, that contained duffels with gun for shuttle safes was edited and moved:
/Resources/Prototypes/_NF/Catalog/Fills/Backpacks/duffelbag_guns.yml -> /Resources/Prototypes/_NF/Catalog/Fills/Items/weapon_cases_shuttle_guns.yml

**Changelog**
:cl: erhardsteinhauer
- tweak: Salvage expedition dungeons now feature a more varied loot/fluff items pool.
- tweak: Extended salvage expeditions time limit to 15 minutes.
- tweak: Limited rewards for completed expeditions to cash only, sum depends on expedition difficulty.
- tweak: Edible food can not be found in salvage expedition dungeons anymore.
- add: Added new salvage expedition dungeon theme - Virology Lab.
- add: Added weapon cases. Guns and energy melee weapons on expeditions now spawn in weapon cases with spare magazines.
- tweak: Duffel bags with shuttle guns were replaced with newly added weapon cases.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
I believe this PR needs `Status: Need Discussion` label

**Comment by ThatOneGoblin25** [comment]
Similar to what @VividPups is working on in #1173 but orientated for expedition rather than bluespace events.

**Comment by ErhardSteinhauer** [comment]
> Similar to what @VividPups is working on in #1173 but orientated for expedition rather than bluespace events. Nice.

It is. But it's less about gaemer loot and more about visual variety of mundane things like tools, vendomats, lathes etc.

**Comment by ThatOneGoblin25** [comment]
Alright I have an idea for a spawner for different techfabs (salvage, medical, engineering) to be found but that brings me to a point.
Machine boards or flatpacks.
Personally, I would prefer machine boards to be found but I can see either.

**Comment by ErhardSteinhauer** [comment]
> Alright I have an idea for a spawner for different techfabs (salvage, medical, engineering) to be found but that brings me to a point. Machine boards or flatpacks. Personally, I would prefer machine boards to be found but I can see either.

Randomized machines and more varied circuitry already present in this PR. Guess I should write in the PR description what spawners were made thus far.

**Comment by WallaceLordofOwls** [comment]
This is a massive change to expeds, so I have questions about the drop rates of exped reward only items like eswords and double eswords, IFF boards, SMG's, bluespace parts, etc. Are the drop rates on them reasonable, or is it super easy to go dry for hours upon hours if you're looking for a specific item? Additionally, Another issue I have that this introduces an even more extreme variable of randomness to exped loot than there was before. Previously, you had some control over the RNG by reviewing exped rewards and choosing the ones you want, but with this change exped rewards are only RNG, there's no control whatsoever. Do you have a way to address this concern?

**Comment by BluCottonCandy** [comment]
My only concern is, this is how expeds were done before. 
No one liked it because you could have expeds with such bad visibility you literally didn't see the rewards
Or they spawned in spots that made them hidden. 
Is this going to be an issue on this PR again?

**Comment by ErhardSteinhauer** [comment]
> eswords and double eswords, IFF boards, SMG's, bluespace parts, etc

eswords and double eswords are exceedingly rare (gonna buff eswords drop rate though), SMGs are somewhat common - from testing I usually get an SMG every second exped or so as (no counting ones that come from downed syndies), same for couple blue space parts (gonna buff 'em too I guess). With IFF boards I can't tell, since I haven't tested them yet, but I'm about to make a couple runs to see if they need to be buffed. In theory they should be too rare: while they have low  %chance on the spawner prototype, spawners with them are very common (multiples per room).

> there's no control whatsoever

There is no control on player's end. However with extended timer you got enough time to loot entire dungeon after you complete the objective, and there are enough spawners so unless you're get screwed by rng, you'll bring at least 1 full stack of all resources available from single expedition. Except bananium.

**Comment by ErhardSteinhauer** [comment]
> Or they spawned in spots that made them hidden.

They are not hidden. Item spawners are placed on tables or racks in dungeon rooms. Unless it's mineshaft or haunted dungeon templates - there are no tables on those ones.

**Comment by WallaceLordofOwls** [comment]
My main concern is that the community will react very negatively to these changes because of the extra factor of RNG it introduces to expeds, which are already incredibly RNG heavy. I'd actually suggest making a post on the discord to get feedback on this before merging it, because the vast majority of people do not use github. You'll get a much larger amount of feedback if you use the discord.

**Comment by ErhardSteinhauer** [comment]
With those changes I was able to consistently turn 100k+ profit per hour if I survive. Which brings profit from expeditions almost to the level of asteroid mining. Roughly 40% of that sum comes from completion rewards, the rest - loot from dungeons.

Sure it's randomized to a degree: if the room had full stack of plasteel, now it is full stack of plasteel/reinforced uranium glass/gold/silver/reiforced plasma/durathead. If it was reinforced uranium glass, now it is plasteel/reinforced uranium glass/gold/silver/reiforced plasma/durathead. And so on. You get the same resources, they just distributed through rooms differently.

**Comment by WallaceLordofOwls** [comment]
> With those changes I was able to consistently turn 100k+ profit per hour if I survive. Which brings profit from expeditions almost to the level of asteroid mining. Roughly 40% of that sum comes from completion rewards, the rest - loot from dungeons.
> 
> Sure it's randomized to a degree: if the room had full stack of plasteel, now it is full stack of plasteel/reinforced uranium glass/gold/silver/reiforced plasma/durathead. If it was reinforced uranium glass, now it is plasteel/reinforced uranium glass/gold/silver/reiforced plasma/durathead. And so on. You get the same resources, they just distributed through rooms differently.

I'm more concerned that people will not be happy with the increase in randomness regarding specific exped rewards, ie not stuff they sell but things they're looking for, like IFF consoles and the like, hence my suggestion that you make an ideas post to get feedback before the PR is merged in order to avoid a potential backlash once it is merged.

**Comment by UncaughtEx** [comment]
Hopefully boards aren't a pain to find

**Review by dvir001 — APPROVED** [review]
This will need another balance pass for sure, but after testing this for some time and fixing few issues its good to go as its now.

**Pull request merged**
