### PR TITLE
Add wall mounted Brigmedic suit storage to Hospitaller ship

### PR DESCRIPTION
**Pull request by blueDev2**
## About the PR

Add wall mounted Brigmedic suit storage to Hospitaller ship

## Why / Balance

The Hospitaller lacks any EVA suits and generally ships should have some form of EVA.

## Media

image

image

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: blueDev2
- tweak: Added a brigmedic wallmounted suit storage to Hospitaller

### CODE REVIEW

**Comment by dvir001** [comment]
@MagnusCrowe Didnt we agree to remove all suits so Nfsd buy them from uplink?

**Comment by Salvantrix** [comment]
Yes. I'll have to look again and make sure brigmed has it in the uplink, aside from just on spawn

**Comment by blueDev2** [comment]
Sorry, I did not hear anything about that
The uplink does have brigmedic patrol suits for purchase

**Comment by blueDev2** [comment]
> @MagnusCrowe @Salvantrix Didnt we agree to remove all suits so Nfsd buy them from uplink?

Doesn't the Prowler still have suits though?

**Comment by Salvantrix** [comment]
It doesn't, or at least it shouldn't. I'll work on getting a brigmedic uplink with their kit, and maybe some chems or something or other.

**Comment by blueDev2** [comment]
Wait are you saying brigmedics will get a uplink or is this a new purchasable item to the current uplink?

**Comment by Salvantrix** [comment]
> Wait are you saying brigmedics will get a uplink or is this a new purchasable item to the current uplink?

Brigmeds maybe their own uplink, don't quote me on it pls :), but I will try given their offset from the general department

**Comment by blueDev2** [comment]
I'd be perfectly content if all sec ships are having hardsuits removed, but is there a specific reason why?

**Comment by MagnusCrowe** [comment]
> I'd be perfectly content if all sec ships are having hardsuits removed, but is there a specific reason why?

We don't want people to feel pressured to buy a certain ship just because it has a piece of loot they want.

If we remove all the loot from all the sec ships and place it all in the uplink instead, it decouples the desire for loot from the desire for a particular ship.

**Comment by blueDev2** [comment]
I'll just close this now then. You may want to add a reference about this in the submission guidelines so people know about this rule pertaining to security ships.

**Pull request closed without merging**
