### PR TITLE
Goblin blood

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Changed the color of goblin blood to dark green. Goblin blood will temporarily give goblin accent upon consumption (and has a 2.5% chance to make drinker vomit). Evaporates.
- Changed the color of brute damage overlay for goblins to dark green.

## Why / Balance
Goblin

## How to test
1. Make an innocent goblin bleed.

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Changed the color of goblin blood and brute damage overlay on goblins to dark green.

### CODE REVIEW

**Comment by dvir001** [comment]
Need to be "GoblinBlood" and not "BloodGoblin" per all other blood names

**Comment by ErhardSteinhauer** [comment]
They all are wrong, `BloodGoblin` is superior to `GoblinBlood`, but I'll change it, sure.

**Review by dvir001 — APPROVED** [review]

**Comment by whatston3** [comment]
Made the brute damage overlay a bit brighter, still reads fine as bloodied, but looks less dark on-model:

image

**Comment by whatston3** [comment]
Also seems to read better on dark-skinned models.

**Review by whatston3 — APPROVED** [review]

**Pull request merged**
