### PR TITLE
Canisters Sprites (Update)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added new gas canister sprites from stagnation

## Why / Balance
Looking good.

## How to test
In game sprite swap

## Media
N/A

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by QRQ-2817** [comment]
Gotta be honest, not a fan of them. I like the traditional canisters.

**Comment by dvir001** [comment]
> how do they look with a tank inserted?

image

**Review by whatston3 — APPROVED** [review]
Very chunky, look like they weigh a lot.  The subtle lettering and warning icons on the plasma and tritium are nice touches.  I like the red valves on the top.

Bit tricky to read when the tanks are loaded in, but that might work out with more use.  The sprites also seem a bit more of a side-on look, where the previous ones look as if viewed from above.

Curious, why was the default status of a canister changed to locked?

**Comment by dvir001** [comment]
> Very chunky, look like they weigh a lot. The subtle lettering and warning icons on the plasma and tritium are nice touches. I like the red valves on the top.
> 
> Bit tricky to read when the tanks are loaded in, but that might work out with more use. The sprites also seem a bit more of a side-on look, where the previous ones look as if viewed from above.
> 
> Curious, why was the default status of a canister changed to locked?

Safety first

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
