### PR TITLE
Bounty hunter clothes sprites, inf BountyVend

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Used old HoS trench coat and hat sprites for Bounty Hunter stuff.
- Made inventories of BountyVends on POIs infinite.
- Added bounty hunter mantle and jackboots to the BountyVend.
- Reclassified jackboots, combat boots and combat gloves as C1.

## Why / Balance
Aesthetics, bug fixes.

## How to test
1. Spawn BountyVend. Inventory should be finite, you should be able to unanchor the machine.
2. Spawn BountyVend [POI]. Inventory should be infinite, you should be unable to unanchor the machine.

## Media
image

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- add: Added bounty hunter mantle and jackboots to the BountyVend.
- tweak: Used old HoS trench coat and hat sprites for Bounty Hunter stuff.
- tweak: Made inventories of BountyVends on POIs infinite.
- fix: Reclassified jackboots, combat boots and combat gloves as C1.

### CODE REVIEW

**Comment by dvir001** [comment]
> I think I'll just comment out BountyVend from exped loot tables.

Fine by me, is also on any ship other then Nfsd?

**Comment by ErhardSteinhauer** [comment]
> > I think I'll just comment out BountyVend from exped loot tables.
> 
> Fine by me, is also on any ship other then Nfsd?

Nope, only on NFSD shuttles. However, I don't think it should be mapped on NFSD shuttles at all.

**Comment by ErhardSteinhauer** [comment]
Aight, made POI variant with infinite inventory and replaced vendomats on POIs with it.

**Comment by Eagle0600** [comment]
Unsurprisingly, the HoS's longcoat and mantle looks like security uniform. It should be recoloured brown for bounty hunters.

**Comment by ErhardSteinhauer** [comment]
> Unsurprisingly, the HoS's longcoat and mantle looks like security uniform.

Fair point.

> It should be recoloured brown for bounty hunters.

Brown? Nah. Mercenary green more likely.

**Comment by ErhardSteinhauer** [comment]
image

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
