### PR TITLE
Eagle, Phoenix (Guidebook Entry)

### PR DESCRIPTION
**Pull request by Mygnol**
## About the PR

Adds guidebook entry and schematic for the Honker and Sparrow.

## Why / Balance

Greyed out manual button bad.
Entry submissions will continue until guidebook improves.

## How to test

 - Go to shipyard
 - Find eagle and phoenix
 - Manual button now has accompanying entries
 
## Media

image
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

If I say it won't, it will.

**Changelog**

Trivial feature, no changelog.

### CODE REVIEW

**Comment by Mygnol** [comment]
Leaving as draft due to comment by @ErhardSteinhauer on #2150 and #2128.
Do let me know if I should hold this till the new guidelines are out, or omit the checklist section, or push only the sprites.

**Comment by GreaseMonk** [comment]
@Mygnol if it is ready for review just set it as ready for review

**Comment by ErhardSteinhauer** [comment]
Can merge it since it's already done, but regarding making new PRs - still might wanna wait 'til maptainers come up with new standard for guidebook.

**Comment by Mygnol** [comment]
It's already done, feel free to merge it. Was leaving it as draft for courtesy in case the standard was coming out soon.

**Review by ErhardSteinhauer — APPROVED** [review]
Works, prolly should merge it after https://github.com/new-frontiers-14/frontier-station-14/pull/2273

**Pull request merged**
