### PR TITLE
January 2024 Upstream Merge

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

big upstream merge
## Why / Balance

catches us up
## Technical details

fryer code ported from Delta-V https://github.com/DeltaV-Station/Delta-v/pull/723
Currently only worked through the several hundreds of merge conflicts. Likely does not build or run yet.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Ships that are in-progress will likely need to be manually updated. Feel free to ping @Cheackraze to help manually fix them.
**Changelog**

:cl: Checkraze, Dvir001, MagnusCrowe
- tweak: Changed some ghost roles to require white list
- tweak: Enabled Shadow biome for expeditions
- tweak: Merged Upstream. See adjacent tab for more info.
- tweak: Helix, Caduceus, and Crescent has new chemistry machines.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Holy shit, everyone hold onto your butts!

**Comment by Cheackraze** [comment]
> Holy shit, everyone hold onto your butts!

dont get too excited, since this also means a migration to dotnet 8, it will likely remain on the shelf for several days while I remain on dotnet 7 to do some current frontier things.  And it will likely be a good week's worth of effort to bring it back to a playable state after that anyhow.

**Comment by FoxxoTrystan** [comment]
Holy moly, also i never asked but what exactly is the difference with dotnet?
Also good luck lads at making it not conflict, il assist if yall need.

**Comment by Cheackraze** [comment]
> Holy moly, also i never asked but what exactly is the difference with dotnet? Also good luck lads at making it not conflict, il assist if yall need.

its one number bigger now

In all seriousness, I have no actual idea, I just know that dotnet 7 was an insanely short lifetime of support, seemingly just a little over a year, and that 8 is supposed to at least be a version microsoft says they will support for longer.  Microsoft themselves are dropping support for 7 in april already so yea

**Comment by dvir001** [comment]
The most wild thing about this merge conflict, that we had a single conflict.
the tips file.

**Comment by FoxxoTrystan** [comment]
> The most wild thing about this merge conflict, that we had a single conflict. the tips file.

your serious?

**Comment by Everturning** [comment]
this will remove machine upgrades, no? if so, then either we need to add them back or create new machines that go faster

**Comment by dvir001** [comment]
> this will remove machine upgrades, no? if so, then either we need to add them back or create new machines that go faster

Were restoring them in later.

**Comment by Everturning** [comment]
> > this will remove machine upgrades, no? if so, then either we need to add them back or create new machines that go faster
> 
> Were restoring them in later.

ah, great

**Comment by Cheackraze** [comment]
look at those beautiful green build checkmarks

**Pull request merged**
