### PR TITLE
Harpy Playable Species

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR
This is a port of the Harpy Species from DeltaV over to Frontier. Harpies are a playable species whose primary feature is that of "Mimicry". They are capable of mimicking almost any game sound through a huge library of sound emotes, as well as imitate a selection of musical instruments through their Harpy Singer System. 

## Why / Balance
For all balance details concerning Harpies, they are exactly as stated here in the DeltaV wiki:

image

## Technical details
This PR touches a single line of wizden code, otherwise all other Harpy code is self contained within the DeltaV namespace. There are several code systems I have developed for this species, but the largest of which is the "Harpy Singer System", which is responsible for enabling a player character entity to have access to an innate midi player. It also contains extremely extensive logic for conditions by which a Harpy is or is not allowed to "sing"

## Media
image

"Chirp!" -Farida

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
The accessibility feature for toggling Ultraviolet Vision on and off currently doesn't work on this version of Robust Toolbox. 

**Changelog**
:cl: VMSolidus
- add: Harpies have made their way from the Delta sector to Frontier, and are now a new playable species!

### CODE REVIEW

**Comment by VMSolidus** [comment]
So I need to point out a few things that *must* be gone over by Maintainers before merging this. 

- [ ] Harpies came with a unique species locked traitor item, the Bionic Syrinx. Since traitors don't exist on Frontier, there's no actual way to obtain it. It would have to be added elsewhere, or possibly just be something the birbs can buy on station. 
- [ ] The accessibility option for toggling off Ultraviolet vision doesn't work on this codebase. However if requested, I can comment it out so it's not a default for birbs.

**Review by FoxxoTrystan — COMMENTED** [review]
Saldy i cannot test the PR but i have some questions:

1. What does Harpy exactly bring to frontier, like a unique gameplay feature? because the "Mimicry" from what i hear seem a bit, meh, i mean its unique but i feel a bird specie could bring more.

2. We got unique clothes, EVA, ect... and looking at the files, not all of them are filled up, would you provide the new sprites or edit the Harpy to fit default clothing?

3. You added new Vulpkanin files sounds, those are duplicates as we already got Vulpkanin with sounds, not the exact sounds tho.

4. 5 Peircing in melee attack is high.

5. Remove the "MovementSpeedModifier" as all Species on Frontier should have the same walkspeed.

**Comment by VMSolidus** [comment]
> Saldy i cannot test the PR but i have some questions:
> 
>     1. What does Harpy exactly bring to frontier, like a unique gameplay feature? because the "Mimicry" from what i hear seem a bit, meh, i mean its unique but i feel a bird specie could bring more.
> 
>     2. We got unique clothes, EVA, ect... and looking at the files, not all of them are filled up, would you provide the new sprites or edit the Harpy to fit default clothing?
> 
>     3. You added new Vulpkanin files sounds, those are duplicates as we already got Vulpkanin with sounds, not the exact sounds tho.
> 
>     4. 5 Peircing in melee attack is high.
> 
>     5. Remove the "MovementSpeedModifier" as all Species on Frontier should have the same walkspeed.

1. I've spent 6 months and nearly 3000 lines of code making Harpies as unique as I could possibly imagine, there's more code in this PR for Harpies than there is for every wizden species combined. I genuinely don't know how I would somehow make them more unique. Please, do not ask me to do this. 

2. Yes, I can provide sprites for every EVA item in the game. The reason they weren't filled up previously was because to save time(it takes about 10 minutes per suit to make the appropriate modifications), I omitted suits that were unused in DeltaV. If you give me a list of what suits are used in Frontier that aren't in the list of birb suits, I can make them trivially. 

3. Yea, I can remove those. This came up when copying DV files over as Birbs being able to mimic Vulpkanin was part of their original code, and there is some negative overlap between your version of Vulp and DV's version of vulp. I was planning on removing them anyway. 

4. It's mechanically no different from any other damage type, and is objectively speaking the worst damage type in the game due to Pierce being the most common, and all-around highest value armor across the board. Lizards also deal 5 pierce melee, this isn't unusual.

5. Sure. However if I do this I'm cutting back on their oxygen costs, since that was what I balanced against the 10% movespeed.

**Comment by Wolfking6116** [comment]
> 1. What does Harpy exactly bring to frontier, like a unique gameplay feature? because the "Mimicry" from what i hear seem a bit, meh, i mean its unique but i feel a bird specie could bring more.

If the mimicry is not considered a unique mechanic, especially in one where checkraze asked for this PR to be sent in, what do you really expect to be unique about a race?

**Comment by FoxxoTrystan** [comment]
> > 1. What does Harpy exactly bring to frontier, like a unique gameplay feature? because the "Mimicry" from what i hear seem a bit, meh, i mean its unique but i feel a bird specie could bring more.
> 
> If the mimicry is not considered a unique mechanic, especially in one where checkraze asked for this PR to be sent in, what do you really expect to be unique about a race?

After some talks, even if its not, there a lot of more features that is really intresting (Breathing, ect...), i give it green thumb of birb.
I mostly asked that question because i did not know what their features was "exactly"

**Comment by cynical24** [comment]
my favorite feature of the birb by far is the fact that it utilizes other species sounds for their own, like screaming

**Comment by Cheackraze** [comment]
i will likely dive in and review this sometime this week, targeting this weekend to have them playable, its just a huge PR so i'll have to block out some time to do so

**Comment by VMSolidus** [comment]
Oh looks like the test fail is a false negative.

**Comment by dvir001** [comment]
> Oh looks like the test fail is a false negative.

Push master into your PR, it will go away.

**Comment by VMSolidus** [comment]
I actually can't lol, there's no master to push into the PR. Normally I'd just go to tests and rerun failed, but I don't have perms to do that.

**Comment by dvir001** [comment]
> I actually can't lol, there's no master to push into the PR. Normally I'd just go to tests and rerun failed, but I don't have perms to do that.

I rerun the tests but your current branch isn't up to latest updates with the main repo, the error is indeed false but it wont go away unless you pull into your PR, either way this isn't a big issue.

**Comment by dvir001** [comment]
@VMSolidus Also can you please add them to be attacked by pitbulls?

**Review by Cheackraze — APPROVED** [review]
sure why not, they are interesting visually, have unique gameplay, and arent hyper tuned for combat, lets welcome the birbs

**Pull request merged**
