### PR TITLE
Dungeons (Update)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Moved all dungeon files to _NF to not be mixed with upstream, except the upstream ones. 
Upgraded all files to v6 except templates 
Nothing changes in the dungeons files other them moving and upgrades.

## Why / Balance
Groundworks for future edits, after that ill be redoing rewards and then layout updates with new content.

## Technical details
Mapping

## Media
N/A

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Cheackraze — CHANGES_REQUESTED** [review]
Dont move upstream files here please, keep upstream files where they belong, this will just make merging upstream a nightmare.

**Comment by dvir001** [comment]
> Dont move upstream files here please, keep upstream files where they belong, this will just make merging upstream a nightmare.

Im fine with leaving files on the upstream folder but wont it be more easy to just let the upstream ones go there and our to stay on _NF since we have balance changes on them, so we dont mess with our custom ones?

I can also just make a "copy" of the files and leave them in the original folders and the new _NF if its fine with you.

**Comment by Cheackraze** [comment]
because if you move upstream files, git is going to re-add them when I do a merge and then the game is going to crash when it tries to load duplicate yml prototypes and then I have to spend time figuring out why and where and for what reason we have duplicates. Its a nightmare, so dont move upstream files please

**Comment by dvir001** [comment]
> because if you move upstream files, git is going to re-add them when I do a merge and then the game is going to crash when it tries to load duplicate yml prototypes and then I have to spend time figuring out why and where and for what reason we have duplicates. Its a nightmare, so dont move upstream files please

I got the original current files from upstream, and made sure the ones were using keep to a new format name, let me know if this fix is fine.

**Comment by dvir001** [comment]
No need anymore

**Pull request closed without merging**
