### PR TITLE
Eagle (New) - Medium sized medical & engineering shuttle

### PR DESCRIPTION
**Pull request by ThatOneGoblin25**
## About the PR
Adds the Eagle vessel, a medium sized medical & engineering shuttle. Priced at $42550. Expect to hold a crew of 3-6 players.

## Why / Balance
With ship weapons around the corner, a niche ship that fulfills engineer and medical duties is expected to come into demand. No cloning as I like the idea that only pure medical ships hold cloning.

## Technical details
Adds eagle.yml to Maps/_NF/shuttles. Adds eagle.yml to _NF/shipyard.

## Media
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

:cl:
- add: Added the Eagle shuttle

### CODE REVIEW

**Comment by ThatOneGoblin25** [comment]
The full description is cut off, it's "A modern, medium-sized medical & engineering vessel. Focusing on responding to shuttle distress, Eagle bears the motto 'Recover, Restore, Repair!'."

**Comment by dvir001** [comment]
Chem area missing all the new cool machines,
Remove the drink vend, no food vends on ships.
Remove advanced medical kit and replace with basic one / remove it.

**Comment by ThatOneGoblin25** [comment]
Fixed issues, minor touch ups and decals, merged the waiting room and break room, chem now has shiny new machines.

**Comment by ThatOneGoblin25** [comment]
Fixed firelock links and added two glass ones over doors. 
Swapped random poster spawner to random legit poster spawner.

**Comment by Cheackraze** [comment]
i like the design and the idea behind the ship, though dvir makes a good point that the combined engineering would make this the perfect kind of ship to add all the special chem machines to. Besides that, I dont see anything egregious or bad, and the map checker came back fine, so with @MagnusCrowe approval we can get this in with some likely very minor revisions. Nice work and thank you!

**Comment by MagnusCrowe** [comment]
Med and engineering is a pairing that I would not expect. Can you share what inspired this ship and how you see it being used?

**Comment by ThatOneGoblin25** [comment]
> Med and engineering is a pairing that I would not expect. Can you share what inspired this ship and how you see it being used?

Listening to Quinley talking about poking ships full of holes with AP rounds that gave me the inspiration. II thought about the need for a ship to answer this problem. Engineering is a niche but if ships can be poked full of holes would have a higher demand but currently all our engineering ships are attached to science ones. So I combined engi with the other department that responds to distress, medical. Really can be summarised with the description motto of "Recover, Restore, Repair!". 
In terms of balancing is it almost too good for its price tag of $42550, but the Helix is $44600 and has cloning, making it a safer alternative to saving people's characters. (You can always use the morgue or bodybag bodies on the eagle and fly to Frontier cloning but let's not talk 'bout that).

Additionally here's the updated image as the PR screenshot underwent slight revision.
Screenshot 2024-02-22 073246

**Comment by ThatOneGoblin25** [comment]
Really nitpicky changes. Forgot chemist jobspawn, trimmed down the amount of lv cables as they have a range of three and I had them going under walls to touch thrusters. Added engi and med banners because I saw them in the entity menu.
Screenshot 2024-02-22 192037

**Comment by ThatOneGoblin25** [comment]
@MagnusCrowe review?
Also final FINAL image, for the wiki, with the only noticeable change being two lv cable I forgot. Technically my first serious PR I'll try to be more straightforward and cleaner with future PRs.
Screenshot 2024-02-24 004120

**Comment by ThatOneGoblin25** [comment]
@MagnusCrowe review?
Also final FINAL image, for the wiki, with the only noticeable change being two lv cable I forgot. Technically my first serious PR I'll try to be more straightforward and cleaner with future PRs.
Screenshot 2024-02-24 004120


> Heowdy swooping in with review
> 
>     * The glass tiles under diagonal walls can safely be lattice or glass tile, whatever you prefer for your design.
> 
>     * Waste line coming from scrubbers does not need a pump.
> 
>     * Any reason why there are 3 firelocks on entry to engi ? Just keep the main fire lock door in my opinion
> 
>     * If you can, add a fire alarm inside engineering and only hook up the fire doors to it so its easy to open up all the fire doors again
> 
>     * Preferably add another air alarm in the atmos area to go with the air sensor there,  then  add another air sensor in the engine room and only have that one hooked up to the air alarm there.  (currently if fire breaks out in engine room i think nothing will happen unless it is sensed by the atmos air sensor ? anyways...)
> 
> 
> Overall this ship design is awesome and i'd be very happy to see it merged soon. Also liked the curtains over the doors
It was just a bit of redundant fire locking, since Engineering will be the first to be handling any problems on another shuttle and fixing atmos on it. Everything in atmos and engineering was linked to the one fire alarm above the pacmans as well as the main hallway area. I will split the the fire alarms so there is one for the lounge and main hall and one for atmos+engi. Both engi room and atmos air senors are linked to the same alarm and there is only firelocks under the atmos and engi doors. Firelocks is something I'm not familiar with but when I tested a fire in engi I wanted atmos to get locked down as well, as I couldn't fit a waste scrubber in there without it going under walls.
Thanks for the response I'll add a slight touch-up with the firelocks, fire alarms and air alarms soon.

**Comment by ThatOneGoblin25** [comment]
> Heowdy swooping in with review
> 
>     * The glass tiles under diagonal walls can safely be lattice or glass tile, whatever you prefer for your design.
> 
>     * Waste line coming from scrubbers does not need a pump.
> 
>     * Any reason why there are 3 firelocks on entry to engi ? Just keep the main fire lock door in my opinion
> 
>     * If you can, add a fire alarm inside engineering and only hook up the fire doors to it so its easy to open up all the fire doors again
> 
>     * Preferably add another air alarm in the atmos area to go with the air sensor there,  then  add another air sensor in the engine room and only have that one hooked up to the air alarm there.  (currently if fire breaks out in engine room i think nothing will happen unless it is sensed by the atmos air sensor ? anyways...)
> 
> 
> Overall this ship design is awesome and i'd be very happy to see it merged soon. Also liked the curtains over the doors

It was just a bit of redundant fire locking, since Engineering will be the first to be handling any problems on another shuttle and fixing atmos on it. Everything in atmos and engineering was linked to the one fire alarm above the pacmans as well as the main hallway area. I will split the the fire alarms so there is one for the lounge and main hall and one for atmos+engi. Both engi room and atmos air senors are linked to the same alarm and there is only firelocks under the atmos and engi doors. Firelocks is something I'm not familiar with but when I tested a fire in engi I wanted atmos to get locked down as well, as I couldn't fit a waste scrubber in there without it going under walls.
Thanks for the response I'll add a slight touch-up with the firelocks, fire alarms and air alarms soon.

**Comment by ThatOneGoblin25** [comment]
Oh I didn't mean to merge master into my branch, it should be fine?
Also vc'd with GreaseMonk and we sorted out the firelock issues and added lattice to the exterior diagonals. 
Ready for merge.

Screenshot 2024-02-25 203643

**Comment by MagnusCrowe** [comment]
> Oh I didn't mean to merge master into my branch, it should be fine? Also vc'd with GreaseMonk and we sorted out the firelock issues and added lattice to the exterior diagonals. Ready for merge.

What was wrong with the glass under the diagonals?

**Comment by MagnusCrowe** [comment]
image

:O

**Comment by MagnusCrowe** [comment]
image
There are far too many lights in this ship.  Please remove some of them.

**Comment by ThatOneGoblin25** [comment]
> > Oh I didn't mean to merge master into my branch, it should be fine? Also vc'd with GreaseMonk and we sorted out the firelock issues and added lattice to the exterior diagonals. Ready for merge.
> 
> What was wrong with the glass under the diagonals?

From what I've stress tested, if they ever get updated with atmos they still fly off even with the vacuum tile.
Screenshot 2024-02-26 090959

**Comment by ThatOneGoblin25** [comment]
Upped the price to 57550, I was incorrectly using appraisegrid which spits out 37.8k
Reduced the number of lights on the ship.
Added an exterior hull plating for the very tip of the ship for the searchlight.
Screenshot 2024-02-26 090643

**Comment by ThatOneGoblin25** [comment]
Renamed the button in bridge to "searchlight button"
Went around placing cleanable dirt decals.
Screenshot 2024-02-26 093057

**Comment by Cheackraze** [comment]
> > > Oh I didn't mean to merge master into my branch, it should be fine? Also vc'd with GreaseMonk and we sorted out the firelock issues and added lattice to the exterior diagonals. Ready for merge.
> > 
> > 
> > What was wrong with the glass under the diagonals?
> 
> From what I've stress tested, if they ever get updated with atmos they still fly off even with the vacuum tile. 

This is because you need to run `fixgridatmos` after placing the marker, then save the grid and re-test it.

**Comment by ThatOneGoblin25** [comment]
> > > > Oh I didn't mean to merge master into my branch, it should be fine? Also vc'd with GreaseMonk and we sorted out the firelock issues and added lattice to the exterior diagonals. Ready for merge.
> > > 
> > > 
> > > What was wrong with the glass under the diagonals?
> > 
> > 
> > From what I've stress tested, if they ever get updated with atmos they still fly off even with the vacuum tile.
> 
> This is because you need to run `fixgridatmos` after placing the marker, then save the grid and re-test it.

I ran fixgridatmos in mapping after placing the vacuum tile. Saved the grid, moved it to _NF/Shuttles, purchased it in host and did that test.

**Comment by MagnusCrowe** [comment]
image
Intentionally missing dashed lines?

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
Final request for you, then it's merge time. Please replace the specialized medkits with their empty versions.  Let your chemist flex and fill them with some custom contents.

The one medkit in the back room of medbay, near the morgue, can stay.

**Comment by ThatOneGoblin25** [comment]
> image Intentionally missing dashed lines?

Yes. As it the door directly to the cockpit door it's going to be used more. The other door is for basically non-crew wanting enter the lounge to wait for their comrades to get fixed and not get in the way of the crew.

**Comment by ThatOneGoblin25** [comment]
@MagnusCrowe I have returned and can finally swap the medkits out.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
