### PR TITLE
Slugcats

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Added our most beloved creature... the Slugcat... Very smart and able to pick up object and manipulate it like monkeys but extremely weak...

Peoples wanted it... i wanted it and honestly having a sort of smart pet could be very interesting and also... its an extreme support animal! (Its like a monkey but cute and interesting! pehaps even... the better pun pun!)

He can only wear EVA: SuitEva and Blood-red.
He can wear a breath mask and have internals.His back slot is only for spears.
The NPC/AI will always have a Ghost takeover open, if there no ghost/AI its will act like a normal animal.
The animal will be targetted by hostile mobs (Carps, Syndicate Turrets, Xenos).
~~Fear the pitbull~~

Stats of the slugcat is like the monkey.

## Why / Balance

Slugcat

## Technical details

Added a simple NPC with custom inventory slot, some tags for whitelists and added a new cargo crate.
## Media

image
image
image
image
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Add 1 NPC with Ghost Role and added a "Slugcat Spawner" for mappers.
**Changelog**

🆑 FoxxoTrystan
- add: Some strange and silly creatures named Slugcats has arrived at the Frontier Sector.
- tweak: Slugcat Crates can be brought in cargo.

### CODE REVIEW

**Comment by MatthewBadger** [comment]
I'm concerned about the addition of an existing IP into the game. Might be better to change it's name and appearance. maybe snail cat would be better?

**Comment by FoxxoTrystan** [comment]
> I'm concerned about the addition of an existing IP into the game. Might be better to change it's name and appearance. maybe snail cat would be better?

The addition of an existing IP "slugcats" is not a problem, were not selling the slugcat or using it for our gain + SS13/SS14 got a ton of existing IP from others games "Xenomorph, ect..." AND... Upstream/Frontier already got a slugcat cookie.

**Comment by Cheackraze** [comment]
yea idk about this. Would need to get some explicit permission from the rainworld folk to add this like this.  A slugcat donut is a funny reference, is not representative nor trying to emulate anything about rainworld, and would be covered under fair use.

Literally adding the main character as like a player controlled mob that can act and do things crosses that line

**Comment by FoxxoTrystan** [comment]
> yea idk about this. Would need to get some explicit permission from the rainworld folk to add this like this. A slugcat donut is a funny reference, is not representative nor trying to emulate anything about rainworld, and would be covered under fair use.
> 
> Literally adding the main character as like a player controlled mob that can act and do things crosses that line

How explain so can i fix this?

Name change or permission from the rainworld folks?

**Comment by Cheackraze** [comment]
i mean its cute and all and I like it but i dont really want playable characters from other games just inserted into frontier. it needs to be more of a parody/transformative or just referential, not just the character with a different name

**Comment by FoxxoTrystan** [comment]
> i mean its cute and all and I like it but i dont really want playable characters from other games just inserted into frontier. it needs to be more of a parody/transformative or just referential, not just the character with a different name

Noted then at this point its better to close this PR until i get a new idea to replace the sprites and features, even tho the sprites is not owned by Rainworld its still very resamblance so il look for something.

**Pull request closed without merging**
