### PR TITLE
Changelog rewrites

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Fixes up existing changelogs.

## Why / Balance

Literally 1984.  Some old entries weren't particularly descriptive, or outright missing.

## How to test

Run game, check changelog.

## Media

TBD?
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

No changelog for editing changelogs.

### CODE REVIEW

**Comment by whatston3** [comment]
This has been put up as a draft so others can edit or suggest other changelog entries that could be more descriptive.  Thanks.

**Comment by dvir001** [comment]
Mfw no changelog for changelog

**Comment by Houtblokje** [comment]
The party crate changelog says "cups of juice" twice. I think its supposed to say:
The party crate now costs 3000 at Trade Outpost cargo, and it contains 5 party hats, 5 cups of juice, 5 glowsticks & a microphone.

**Comment by Kei-Shin** [comment]
#1668 and #1929 changelogs weren't formatted correctly so auto changelog didn't do the thing.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
