### PR TITLE
Goblin speech bubble, water/space cleaner spray reaction

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Added speech bubble specific for goblin.
- Made goblins scream if they are prayed with water or space cleaner.
- Updated guidebook entry.
- Goblins are less affected by slowdown from wounds.

## Why / Balance
QoL, (un)ballance, memes.

## How to test
Be goblin.

## Media
Ignore Toxin damage entry in guidebook - it's no longer the case.
image
- [x] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
none afaik

**Changelog**
:cl: erhardsteinhauer
- add: Added goblin speech bubble.
- tweak: Added to goblins low tolerance for cleanliness.
- tweak: Goblins are less affected by slowdown from wounds.

### CODE REVIEW

**Comment by Kesiath** [comment]
tbh i don't think toxin damage for the attack is a good move, toxin is a pain to heal with the normal meds most folk can readily get

**Comment by dvir001** [comment]
All fine except the toxin damage

**Comment by ErhardSteinhauer** [comment]
eh, I don't mind removing it.
it just feels appropriate for toilet-diving species.

**Comment by ErhardSteinhauer** [comment]
fine, I'll remove it

**Comment by ErhardSteinhauer** [comment]
gotta change the .xml too

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
