### PR TITLE
Smuggling posters are now random and NFSD gets rewarded for getting prints of posters and dead drops

### PR DESCRIPTION
**Pull request by Shroomerian**
## About the PR

The PR changes several things about the smuggling posters and their mechanics:

- Changed their activation rate down from a of 15-90 minutes range to a 5-10 minutes range and made the distance that the drop pod is spawned at smaller as well: 362ebec , 7670a6d, 3bcca71, d454abd

image

- Only 2 dead drop posters can be active at a time (have the verb to spawn the paper with the dead drop) as per the request of @whatston3: d454abd

> lots of good stuff in here. With the whole '1 active per POI' deal, i was actually considering expanding this to be more of a sector-wide phenomenon in order to both A. Slow down the rate of the dead drops being used and B. Have it be 'available' more frequently to the players who do participate, so that they dont ever feel like they are just 'waiting'.
> 
> So, instead of a per-POI basis, you could theoretically re-write it so that there are only ever X amount active _server-wide_. In that way, we can mostly forego any kind of timer limit (probably still keep a short one to prevent spam/hyper abuse), while still gauranteeing it is 'available' at any given time, while also still providing the challenge of the players still having to venture out and search multiple locations/posters for wherever the next 'drop' may have activated from.
> 
> Thoughts on making it more a sector-wide "2 active at a time" limit?

- NFSD is now warned about the location of dead drops after 15 minutes have passed: 7670a6d

image

- NFSD get partial hints about the location of each POI, 1st time no hint, 2nd time they get fed two locations, one being fake and 3rd time it's the actual location: 3bcca71

image

- Made every poster on tinnia.yml, arena.yml and caseyscasino.yml roll for being a DeadDrop poster, this poster abundance is not an issue as only 1 can be active per POI: 7c80217 , 5f6b3f3

image

- NFSD detectives are now rewarded for scanning any used contraband posters with 3 FUC and any spawned dead drops with 6 FUC with a forensic scanner: 27dc7f6 , 470fd58, a47f678

image
image

- New guidebook paragraph in the Forensics entry detailing how to get prints of posters, Freelance now has a 1/3 chance of getting the smuggler's current ship ID after 15 minutes and lowered the chance of posters spawning back from 0.9 to 0.5: 3fee8c8

image
image

## Why / Balance

Discord idea thread: https://discord.com/channels/1123826877245694004/1260704805282910321

Currently the dead drop system or "smuggling" is not worth doing for newer players, a lot of the profitability from them comes from the fact whether you know EXACTLY which posters to search on each of the main locations and whether you get lucky enough to be on the timer.

To be exact the bullet point reasons are:

- Non-intuitive to new players
- Bad profit per hour considering the 15-90 minute wait time and low amount of dead drop posters
- No additional incentive for NFSD to interact with the system other than selling off contraband crates
- Long boring wait time to get to the dead drops themselves
- Nobody except the smugglers can find the dead drop unless it's done on accident

## How to test

To test the systems this is what I did:

- Change the Content.Server/_NF/Smuggling/Components/DeadDropComponent.cs CoolDowns to their suggested value in the comment above them
- Start up the server
- Admin ghost to Tinnia's or other POIs
- Check any posters with DD appended to their internal name at the end and see whether NFSD and Freelance (1/3 chance) radio sparks up
- Spawn Urist McHands, headset with NFSD and Freelance encryption keys, Detective PDA or higher (Warden, Sheriff, SR, etc.) and forensic scanner (you need to be inside an entity for the DeadDropSystem to add the verb to the poster, this was unchanged behaviour)
- Afterwards get prints of the activated poster with a Detective ID or higher access to ensure it gives 3 FUC, make sure it can't give multiple rewards per same poster and that it only works for people with Detective access or higher (it's done this way so detectives don't lose their ability when they get promoted to "Captain" after buying a ship)
- Get to the dead drop location by going into B->Ghost, and then Admin->Objects->Syndicate Supply Drop->Right Click->Follow
- Spawn Urist with all his gear again there
- Scan any object inside the dead drop and ensure that it gives 6 FUC and doesn't give more than that if you scan more objects.
- Try to spawn more than 5 dead drops and see if there's more than 5, the oldest one should disappear (dequeue)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: More object types can be used as dead drops (more than posters).
- add: Hints for dead drop locations spawn randomly at round start and mid-round through faxes.
- add: The detective now has a module for their forensic scanner that gives spesos & FUCs on scanning dead drops and pods.
- add: Adds smuggling guidebook entry with a better (NFSD-side) explanation of mechanics.
- add: Both pirates and NFSD may receive the location of a drop pod about 15 minutes after a smuggling note is taken.
- add: Compromising a dead drop (by scanning or unanchoring it) moves it to another random location.

### CODE REVIEW

**Comment by BluCottonCandy** [comment]
If possible I would love if it could alert pirates as well. 
On freelance channel. 
It's been talked about to have pirates and smugglers go at each other. 
Feel like the 15 mins ping going to NFSD and pirates could be a great way to cause RP. 
Maybe reward the pirates their coins for scanning the drop with some kind of pirate scanner?

**Comment by Shroomerian** [comment]
> If possible I would love if it could alert pirates as well. On freelance channel. It's been talked about to have pirates and smugglers go at each other. Feel like the 15 mins ping going to NFSD and pirates could be a great way to cause RP. Maybe reward the pirates their coins for scanning the drop with some kind of pirate scanner?

Hey that would be a great idea, I am going to also probably make it so posters which are waiting for others to finish also reset their timer, because after some thinking I realized that posters would activate one after another if they were left untouched for far too long.

As for the scanner I don't know since I don't know how to make a different sprite, I could just grab the forensic one and change its colors to red or something, or I could just make it so pirates get rewards if they dock.

**Comment by Shroomerian** [comment]
> If possible I would love if it could alert pirates as well. On freelance channel. It's been talked about to have pirates and smugglers go at each other. Feel like the 15 mins ping going to NFSD and pirates could be a great way to cause RP. Maybe reward the pirates their coins for scanning the drop with some kind of pirate scanner?

Do you think something like this sprite would work? I've basically just changed the colours of the terminal from blue to red and the plastic to wood similar to Pirate's ID

image

**Comment by BluCottonCandy** [comment]
> > If possible I would love if it could alert pirates as well. On freelance channel. It's been talked about to have pirates and smugglers go at each other. Feel like the 15 mins ping going to NFSD and pirates could be a great way to cause RP. Maybe reward the pirates their coins for scanning the drop with some kind of pirate scanner?
> 
> Do you think something like this sprite would work? I've basically just changed the colours of the terminal from blue to red and the plastic to wood similar to Pirate's ID
> 
> image

Definitely a neat idea! 
Would be fine imo if someone felt so inclined they could resprite it to be a coconut or something lol

**Comment by Shroomerian** [comment]
I think that in the end it's better not to implement it even if it's a cool idea because it would make accidentally smuggling for pirates really easy, and as long as that's a rule I don't think that adding rewards for pirates to check out dead drops isn't that good of an idea.

**Comment by dvir001** [comment]
If you speed it up again this is going to force security again to only fight SMUGGG for the full shift and doing nothing else like it was before.

**Comment by Shroomerian** [comment]
> If you speed it up again this is going to force security again to only fight SMUGGG for the full shift and doing nothing else like it was before.
> 
> Also this should be added in some guidebook entry there isn't anything in game to tell you about the scan posters.

Alright, I can probably get a guidebook entry in the forensics part, also what happened before? I didn't play back then.

**Comment by ray-boop** [comment]
Telling the NFSD the location of the pod is defeating the purpouse of smuggling imo. With that you just have a race with the nfsd who gets there first.

**Comment by dvir001** [comment]
You need to consider the type of people you going to have to deal with as NFSD

The people who will micro shuttle, tier 4 thrusters, ripley, going to fly in a line into it to min max this for a full shift.

If you think im making this up, this was the actual setup before we lowered the time, and now with people forced to speed run this will just be the meta.

**Comment by Shroomerian** [comment]
> You need to consider the type of people you going to have to deal with as NFSD
> 
> The people who will micro shuttle, tier 4 thrusters, ripley, going to fly in a line into it to min max this for a full shift.
> 
> If you think im making this up, this was the actual setup before we upped the time, and now with people forced to speed run this will just be the meta.
> 
> Cant wait to have to look for 6 contraband alarms going one after another and feeling hopeless having no way to combat this again, to a point NFSD again just ignore the alerts.
> 
> This also not fixing the meta knowledge issue that people "just know" posters are hidden in POI and running into every single poster in a poi spamming them.
> 
> And NFSD are just going to go to POI to scan posters and destroy them, making it also into some new meta.

Ok, I think I have something to fix that I'll test it first then I'll commit if everything is good

**Comment by Shroomerian** [comment]
> You need to consider the type of people you going to have to deal with as NFSD
> 
> The people who will micro shuttle, tier 4 thrusters, ripley, going to fly in a line into it to min max this for a full shift.
> 
> If you think im making this up, this was the actual setup before we upped the time, and now with people forced to speed run this will just be the meta.
> 
> Cant wait to have to look for 6 contraband alarms going one after another and feeling hopeless having no way to combat this again, to a point NFSD again just ignore the alerts.
> 
> This also not fixing the meta knowledge issue that people "just know" posters are hidden in POI and running into every single poster in a poi spamming them.
> 
> And NFSD are just going to go to POI to scan posters and destroy them, making it also into some new meta.

The 3fee8c8 commit should fix this issue, I lowered the chance of posters spawning at 0.5 so there should be less of them available, also only 1 can be active at a POI and if any others try to become active their timers are reset and have to try again as per 98cff11

There's only 1 poster per POI, so metagammers can try all they want they will not get more than 1 dead drop per POI visited, this also applies to NFSD as they will not get rewarded if a poster is a dead drop one but has never been activated, so they can also metagame all they want but they could only remove used posters and since there's only 1 active poster per POI then they can only destroy 1 at at time out of all possible posters available.

Also the latest commit adds risk for smugglers since they can smuggle all they want but if their ship id gets revealed to pirates and they get caught with IFF on it's over for their smuggling days, both from the NFSD side since on Frontier gloves don't help against prints on posters, and pirate side looking to get their booty from smuggling.

**Comment by Shroomerian** [comment]
Next commit I'll make it so dead drops dequeue and the oldest is deleted after 6 of them are on the map and so dead drop rewards for NFSD are limited to once per unique prints on posters and 10 times for dead drops themselves per shift.

Also I'll probably limit the scanner to only give rewards if the detective is using them, because if not smugglers could just grab a scanner and waste the FUC

**Comment by dvir001** [comment]
Seems to be answering the issues, well done.

**Comment by Shroomerian** [comment]
Hey, sorry for interrupting I didn't realize that pushing removes the workflows that require approval, I still need to commit a few things like removing an empty file I accidentally created and buffing the sell price of contraband crates and adding a roll for a syndicate enemy AI inside the dead drop for a bit more risk/reward.

I'll try to commit these last things and after that I'll await your review and approval.

**Comment by Shroomerian** [comment]
Commit a47f678 should be the last one I post unless there's some breaking stuff or requested review changes. Thank you for being patient with me.

**Comment by dvir001** [comment]
image

No need to update with master so many times unless there is a conflict, seems ready for testing.

**Comment by Shroomerian** [comment]
> image
> 
> No need to update with master so many times unless there is a conflict, seems ready for testing.

Alright, sorry, I just kept clicking on the update branch thing thinking it would help.

**Comment by K4rlox** [comment]
> NFSD detectives are now rewarded for scanning any used contraband posters with 3 FUC and any spawned dead drops with 6 FUC with a forensic scanner

wouldnt this just cause nsfd to rush POIs and scan each poster?

**Comment by Shroomerian** [comment]
> > NFSD detectives are now rewarded for scanning any used contraband posters with 3 FUC and any spawned dead drops with 6 FUC with a forensic scanner
> 
> wouldnt this just cause nsfd to rush POIs and scan each poster?

Yes and no, the if condition to give you FUC isn't just a "if (isDeadPoster)"
but a "if (isDeadPoster && hasBeenActivated)" so even if they scan other dead drop posters they will only get rewarded for the ones which have been used.

And with the update to radio, NFSD doesn't know exactly where smuggling has occurred on smuggle 1 and 2 3bcca71 so there's a bit of leeway and advantage smart smugglers can use but also newbies too.

**Comment by Cheackraze** [comment]
lots of good stuff in here.  With the whole '1 active per POI' deal, i was actually considering expanding this to be more of a sector-wide phenomenon in order to both A. Slow down the rate of the dead drops being used and B. Have it be 'available' more frequently to the players who do participate, so that they dont ever feel like they are just 'waiting'.

So, instead of a per-POI basis, you could theoretically re-write it so that there are only ever X amount active _server-wide_. In that way, we can mostly forego any kind of timer limit (probably still keep a short one to prevent spam/hyper abuse), while still gauranteeing it is 'available' at any given time, while also still providing the challenge of the players still having to venture out and search multiple locations/posters for wherever the next 'drop' may have activated from.

Thoughts on making it more a sector-wide "2 active at a time" limit?

**Comment by Cheackraze** [comment]
otherwise, loads of good things happening in this PR, im hoping to review and merge this one some time this week

**Comment by Shroomerian** [comment]
Alright sounds great! I'll get to it in my free time.

Also do you mind if I squash the merge commits together? 

It's just so they don't unnecessarily clutter up the PR when only one  of the latest commits can do the job.

**Comment by Shroomerian** [comment]
I've successfully removed all of the previous "Merge branch 'master' into smuggling-buff" commits and replaced them with just one at the end. 

I was going insane.

**Comment by Cheackraze** [comment]
> Alright sounds great! I'll get to it in my free time.
> 
> Also do you mind if I squash the merge commits together?
> 
> It's just so they don't unnecessarily clutter up the PR when only one of the latest commits can do the job.

We do squash commits for direct contributions, so you shouldnt worry

**Comment by Shroomerian** [comment]
@whatston3 Alright, I've finished with the idea of making the dead drop posters limited to 2 at a time. I've lowered the cooldown period down to 5-10 minutes as a result. 

I had to force push something because I pushed that commit on another account which I don't want to be here, I don't know if the history is permanent but whatever, I hate how the vscode github extension just forces the account it's logged in as even though you specified in terminal to use another.

Anyway sorry for the rambling, that is done and I think it's better this way because there's no longer a hypothetical situation where 5-7 people smuggle at the same time and one or more dead drops delete themselves because somebody else got off the cooldown and it dequeued the oldest one to save on server memory and processing.

**Comment by whatston3** [comment]
> @whatston3 Alright, I've finished with the idea of making the dead drop posters limited to 2 at a time. I've lowered the cooldown period down to 5-10 minutes as a result.
> 
> I had to force push something because I pushed that commit on another account which I don't want to be here, I don't know if the history is permanent but whatever, I hate how the vscode github extension just forces the account it's logged in as even though you specified in terminal to use another.
> 
> Anyway sorry for the rambling, that is done and I think it's better this way because there's no longer a hypothetical situation where 5-7 people smuggle at the same time and one or more dead drops delete themselves because somebody else got off the cooldown and it dequeued the oldest one to save on server memory and processing.

Working on a set of suggestions at the moment, I'll post them here when I'm finished with them to get feedback.  Pardon the delay.

**Comment by Cheackraze** [comment]
I just wanted to chime in and thank you again for this contribution, I understand our review and development process is a bit slower than other similar platforms but I know I'm pretty excited about these ideas and changes and others are as well, so we very much appreciate your hard work and patience with us

**Comment by Shroomerian** [comment]
https://www.youtube.com/watch?v=l2fMh9nXWR0

There might be a merge conflict with the new DNA stuff.

**Comment by Cheackraze** [comment]
i think whatstone is working on some suggested code changes but conceptually this is all fantastic. Im still just a tad concerned with a low timer that its going to overwhelm security again, but those are easy to tune balance numbers after the fact.

**Comment by whatston3** [comment]
After an age and a half, I've got a set of rework that I'm remotely happy with.  Values probably need tweaking, might be bugs in the woodwork, but all of the suggestions are up here compared to this PR: https://github.com/Shroomerian/frontier-station-14/compare/smuggling-buff...whatston3:frontier-station-14:smuggling-buff-suggestions-2?expand=1

Major changes:
1. Items are identified as potential dead drop targets, and associated with a string describing what they are (chairs, disposal bins, vendors, posters, etc.)
2. Stations are now identified as being dead drop targets.  Grifty's, Casey's, etc. are all dead drop targets.
3. On world generation, there are a number of dead drops that are assigned (random within a defined range, you will have some variability in how viable smuggling is per round), and these get assigned randomly to each station, up to a maximum number that is specified per station (as-is at the time of writing, Trade Outpost has 3, Expeditionary Lodge has 1, others have 2).
4. For each station, we randomly select that number of entities from the list of potential dead drop candidates and set up our smuggling parameters (which have largely been moved to CVARs).
5. The detective now receives a module that slots into a forensics analyzer.  Instead of being tied to the specific role, the sheriff (and only the sheriff) is able to purchase additional chips through their uplink to assign to other officers to assist with anti-smuggling/dead drop patrols.
6. When the forensics analyzer with the module scans a dead drop target that has either been used, or has a dead drop available, it credits the NFSD bank account with a fixed number of spesos, and credits an accumulating bank of FUCs.  Upon receiving some number of FUCs, this is redeemed and given to the scanning officer.
7. The FUC payouts have been reduced across the board.  Compromising a contraband dead drop before it is used is valuable, otherwise, you should be tracking down and ambushing smugglers and retrieving their loot.  Giving extra FUCs for visiting the drop pod seems odd when the pod itself contains 15 FUCs of contraband value on average.
8. When a dead drop is compromised, it moves to another location (currently on the same station), and its timeout is reset.
9. The messages being sent have been moved to a prototype, and are associated with a particular station's prototype (the cove and the NFSD outpost).
10. NFSD messages are now received 80% of the time, and are independently received for the dead drop use and the pod location.  You may get one without the other, or neither at all.
11. Pirate messages now give the location of the dead drop (still 33.3% of the time), and again, this is delayed.  The intention here is to set up possible ambushes and three-way conflict.  Since all messages are now generated from uncertain probabilities, this allows for some tension and uncertainty in how safe your smuggling drops are.
12. All delays for smuggling reports, for both the NFSD and pirates are now random (currently between 14 and 16 minutes).
13. Smuggling crates now turn in for 2 doubloons each, incentivizing pirates to either hunt or work with smugglers (since taking dead drops as a pirate is against code - this could be hardcoded).
14. The specific NFSD dead drop messages are now based on the number of events happening in the past hour, not through the entire shift.

Thank you for your hard work on this feature, and my apologies for taking so long with this.  I think it may need some tweaks, but I think it'll improve smuggling gameplay overall.  There should be more things around, but they should be harder to find without having hints.

At the moment, there is no real way to get hints - if the messages could be faxed in as a random event during the shift, and if there were maybe one or two hints randomly spawning at roundstart, you could get more players knowing the locations of where these dead drops actually are.  Apart from that, and from a bit of testing, I think this looks alright.

**Comment by Shroomerian** [comment]
> targets.

Oh wow, that's a lot of hard work, I didn't realize you were modifying my fork, I didn't have notifications set up for it, hahaha.

So now all that's left is to test to see if everything works, modify the changelog and features comment at the top of the pull request and make sure everything is mergeable with master right?

**Comment by Houtblokje** [comment]
> Items are identified as potential dead drop targets, and associated with a string describing what they are (chairs, disposal bins, vendors, posters, etc.)

Won't that mean it will be even more of a pain to figure out what item is a deaddrop? because right now its already annoying having to rightclick basically every post to find it, and if that gets changed to "You now need to rightclick every item on a POI and the deaddrop might not even be on that POI" that seems like a really bad change to me?

**Comment by Tych0theSynth** [comment]
> > Items are identified as potential dead drop targets, and associated with a string describing what they are (chairs, disposal bins, vendors, posters, etc.)
> 
> Won't that mean it will be even more of a pain to figure out what item is a deaddrop? because right now its already annoying having to rightclick basically every post to find it, and if that gets changed to "You now need to rightclick every item on a POI and the deaddrop might not even be on that POI" that seems like a really bad change to me?

It's basically already like this.
Right now, it's a specific poster on the POI and it has a chance to not spawn a note or have a really long cooldown, so smuggling has a chance to just not exist at all during a round.

This new system is definitely better, has a lot more randomness and will be less easy to powergame.

**Comment by Cheackraze** [comment]
> Oh wow, that's a lot of hard work, I didn't realize you were modifying my fork, I didn't have notifications set up for it, hahaha.

So how we usually do big PRs like this is, we only directly make commits as maintainers to help pull master and keep updated there, or if a PR has been abandoned, or specific help is requested or something vital needs changed before merging.

When we do big reviews and suggestions, like what Whatstone did, is that he actually made a fork of this fork, made the suggestions there, and is making a sort of pull request into your pull request, should you agree and accept those changes! We've been fairly excited for this PR too!

Whatstone's changes aren't yet made into this PR, you'll have to pull those in for them to be included.

**Comment by whatston3** [comment]
> > Items are identified as potential dead drop targets, and associated with a string describing what they are (chairs, disposal bins, vendors, posters, etc.)
> 
> Won't that mean it will be even more of a pain to figure out what item is a deaddrop? because right now its already annoying having to rightclick basically every post to find it, and if that gets changed to "You now need to rightclick every item on a POI and the deaddrop might not even be on that POI" that seems like a really bad change to me?

This is the importance of the _hints_.  Right now in that suggestions branch, there are a set of 4 notes that generate on the consoles on Expeditionary Lodge telling you the location of a few (2-4) dead drops - "a vending machine at Tinnia's", "a stool at Trade Outpost".  Stupid placeholder, but a few should spawn in randomly.  By selecting from a larger pool of objects, if you are stumbling around in the dark, yes - this is intentionally hard to find.  The reason dead drops work for covert business is that there are very few people who know the location of the dead drop, and the dead drop is in a reasonably inconspicuous spot.

Having dead drops be a pain in the ass to find without knowledge gives you a few things: you can put a lot more of them around, and if you want to smuggle without having a hint, you need to put in some work.  If they were easy to find, the NFSD, with more staff than you, will be all over all of them with their extra budget and resources.  Add in an event to fax a ship or two with one of these hints, and I think we're good.  Once you know which disposal bin or poster one's at, it won't change unless compromised.  For the NFSD as well, it makes it harder to find these, and with the dead drop callouts, unfortunately the best source of easy FUCs is ambushing smugglers, considering an average pod gives you 3 contraband crates at 5 FUCs each.

The balancing on this is hard because of that, it's extremely swingy.  Maybe it should be reduced and the value of the dead drops and pod forensics could be increased.  Ideally, there should be reward for the detective (which I would like to tie into paying the NFSD so splitting the banks is more reasonable), reward for the smugglers, and opportunistic reward for the NFSD/pirate interlopers.  Hell, if the dead drop note told you that "a new note will be available here at XX:YY:ZZ" (could throw in some error, things happen), you could even plan your smuggling runs better.

**Comment by Shroomerian** [comment]
> > Oh wow, that's a lot of hard work, I didn't realize you were modifying my fork, I didn't have notifications set up for it, hahaha.
> 
> So how we usually do big PRs like this is, we only directly make commits as maintainers to help pull master and keep updated there, or if a PR has been abandoned, or specific help is requested or something vital needs changed before merging.
> 
> When we do big reviews and suggestions, like what Whatstone did, is that he actually made a fork of this fork, made the suggestions there, and is making a sort of pull request into your pull request, should you agree and accept those changes! We've been fairly excited for this PR too!
> 
> Whatstone's changes aren't yet made into this PR, you'll have to pull those in for them to be included.

Ah I see. The only thing is that currently when I check my fork on Github I don't see any pull requests yet. I assume that's because there's still changes to be made.

**Comment by whatston3** [comment]
Added an event to the suggestion branch to generate and send a set of 2-3 dead drop locations to a given ship.  Currently doesn't care about ship type, so it could go to an NFSD ship, or to a ship without faxes.  Event seems to work alright, though.  Currently added to the default event pool, and should occur at most hourly.

**Comment by whatston3** [comment]
Added a VariationPass on stations to randomly generate dead drop hints at round start [about a 2% chance to spawn on each table] (and removed the placeholders from Expeditionary Lodge).  You now should have about 5ish pieces of paper strewn about on tables (not on Frontier Outpost, the NFSD Outpost, the Courthouse or the Anomalous Lab/Geode), with the possibility of extra fakes if RNG works out.

Between this and the smuggling fax hints, this should be enough to provide some reasonably reliable information to the players (both security and smugglers) about where the dead drops are.

I might want to add an approximate timer to the dead drops so the smugglers have some idea about when to return rather than just checking back periodically without any idea when it'll show up again, and maybe fiddle with the payouts (probably increased spesos and FUCs for the detective work, and less for contraband crate bring-in) though I think what's here is still an improvement.

**Comment by whatston3** [comment]
Fiddled with spawner values and frequency.  Syndie drop pod contraband crates are now actually contraband (out of sector goods, Syndicate association), but are also worth more (3K for low, 5K for high - fairly arbitrary).  Reduced contraband crate value to 3 FUCs per crate, increased FUC payouts for detective work.  Reduced the frequency of banner spawns and normal crate spawns.  37.5% chance for a random crate, roughly works out to about 12 FUCs on average for a drop pod (vs. the older 15, can add 2 for detective work, a slight compromise, and far less swingy for godly RNG).

Moved the smuggling Guidebook bit to its own page, removed some irrelevant security details (bomb defusal, wizden space law).

Might put a "come back around XX:YY:ZZ shift time" on the smuggling notes, but I think apart from that this should be good to go.  May need tweaks in the future, but better than nothing.

**Review by whatston3 — APPROVED** [review]
Pulled in the changes, happy with the state of this.  Would prefer a second set of eyes, but I do think it's alright.

Fixed remaining issues with printed vector precision, smuggling rewards should be marginally increased, pirates and NFSD should be getting messages (somewhat unreliably).

**Comment by Shroomerian** [comment]
> Pulled in the changes, happy with the state of this. Would prefer a second set of eyes, but I do think it's alright.
> 
> Fixed remaining issues with printed vector precision, smuggling rewards should be marginally increased, pirates and NFSD should be getting messages (somewhat unreliably).

You are amazing! <3

The only thing left right now is to add the changes to Changelog in the comment above, no? Or is it not necessary at this point?

Tell me what to do and I'll try to finish it off so this can be pulled fully.

**Comment by whatston3** [comment]
> The only thing left right now is to add the changes to Changelog in the comment above, no? Or is it not necessary at this point?
> 
> Tell me what to do and I'll try to finish it off so this can be pulled fully.

Gave the changelog an attempt - I think it's brief but descriptive enough.  Feel free to make changes as you'd like.

Testing it for bugs and getting your thoughts would be great.  Config's a bit all over the place to get shorter delays, but _most_ of it can be set through server-side CVARs (run `cvar ?` for a list of them in the server terminal), and there's the message types to reduce the 15ish minute delay between dead drop and pod message.

I do think it's alright, but it's worth taking another look with fresher eyes.

**Comment by whatston3** [comment]
A few small changes:
* Tweaks to smuggling generation params at Dvir's request (seem reasonable to me)
* Fax events now send 1-2 faxes, happen at minimum 50 minutes apart down from 60.
* Ships cannot be sold with contraband crates on them (apart from pirate and syndicate shipyards) - also added the nuke, nuke disk, and mail teleporter to this set.
* Slightly fewer overall objects being generated, hints now contain 1-2 hints down from 2-4.
* 3-5 random hints generated at round start.

Again, I think we'll have to see how this plays out, but again, works well under test.

**Review by whatston3 — APPROVED** [review]

**Comment by whatston3** [comment]
Smuggling activity detected in your sector.

**Pull request merged**
