### PR TITLE
Mayflower- Abandon Bounty hunter ship

### PR DESCRIPTION
**Pull request by VividPups**
## About the PR 
Add Mayflower - https://github.com/new-frontiers-14/frontier-station-14/pull/653#issue-2024966179 - (Links to the close report)

## Why / Balance
As far as I was able to see the only Bounty Hunter/Expedition ship was the KC Sprinter. So I would like to add more that is more dedicated in bounty hunting/ Expeditions

(I had to reinstall the Local Repository. Lost the branches)

As far as I was able to see the only Bounty hunter/Expedition ship was the KC Sprinter. So I would like to add more that is more dedicated in bounty hunting/ Expeditions
## Media

Mayflower

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added the USS Mayflower expeditions shuttle

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Seem a lot of things are fine but there some flaws that im looking at:

• Horible wiring, some things are not even connected, ect... like missing substation connected, 2 APC only? and MV/HV Cable mess, i recomend to kinda rewire ya ship.

• Only scrubber network on a ship this big?

**Comment by VividPups** [comment]
The wires are intended that way and the Scrubber system was intended. I didn't know about the Substation which I corrected now  However it isn't showing as an change when I am trying to connect it so far. Im trying to get it fix

**Comment by VividPups** [comment]
The substation has been Fix, Requesting to be looked at again.

**Review by TsjipTsjip — COMMENTED** [review]
Facts:
- Price: 50000 spesos
- Initial valuation (expeditions console): 44965 spesos, seems okay to me.

Major notes:
- Light in the doorway leading from the entrance hallway to the bar/medical area has to be moved.
- Tiny fans right of the AME appear to be useless.
- Tiny fans protecting the bridge aren't really necessary, neither are the ones on the firelocks close to the left and right docks.
- Top left thruster is not turned on. So are the lower right thrusters.
- AME appears to be enabled as soon as the ship spawns.
- Cable terminals are not correctly placed (Hv Producer-to-consumer loop introduced by the wiring under the AME.

Minor notes:
- Salvage equipment locker without salvage specialist on the ship proto.
- You could spray-paint the door to the cell for it to be not blue, but retain the same access. (Might not save tho, not sure.)
- Four spider webs under the right armoury door seems a bit much.
- Power setup is still a hot mess. Cables are going everywhere and go under walls a lot of the time, this should be avoided where possible for ease-of-access in game. (Thruster wiring obviously cannot avoid this, but Mv wiring and Hv wiring generally should be easily accessible unless they are electrifying a window grille.)
- There appear to be four egress passive vents connected to four separate scrubber networks. Is this intentional?

All in all I like the vibe of this ship, but I would not buy it in-game in its current state. I'll also attach this diagram that indicates how a power setup should work. While this one was made with full stations in mind, the principles surrounding SMES banks carry over to shuttles if they have them. Pay specific attention to the Hv wiring that should not touch outside of the cable terminals.
Power Setup

**Comment by VividPups** [comment]
explain why it has to be moved?  
That Fan was from a much older design of the ship and needed to be removed
I will take a look at those thrusters and see what happen
AME is supposed to be on when the ship spawns I don't know why you wouldn't want it on. I even had Trystan and Darvin show me how to get it to be on. 
Ill take a look at the AME cable terminals and the loop

Checkraze has already approved the Salv locker
The door is post to be blue like it is on the Sprinter
I intend to put multiple webs in the same stop around the ship
I design the Power system to be a mess like that 
yes the Scubber was set up like that intentional

**Comment by VividPups** [comment]
image
 
 
 
 Update as of now

**Comment by TsjipTsjip** [comment]
From the image above, Hv wiring is correct now.

> explain why it has to be moved?

To have a light in a doorway makes it appear as if it it crushed every time the door closes onto the tile. It isn't, that's not how this game works, but to me this is essentially the same as placing a light not attached to a wall at all. I am not aware of what the game does with this light in its current specific place, but I am of the opinion that it has to be moved, if anything to prevent clipping issues.

> I will take a look at those thrusters and see what happen

Should be as simple as just clicking them to turn them on.

Remaining notes:
- Tiny fans in the bridge hallways still were not addressed.
- Would recommend running a colornetwork of each of your scrubber networks, as not all pipes appear to be colored. (Unless intentional.)

**Comment by VividPups** [comment]
The fans in the Bridge hall way is Intenational

When you was talking about the Light I thought you was talking about the hallway light. I didn't noticed that I left an light in the actual door itself. 

Also, yes I have Fix the thrusters. One of them wasn't even in range of the wiring until I change it.

Also there is only like 4 pipes that aren't color because I accidentally deleted them when doing other things. Which is why I didn't bother fixing the color. However, if someone would to be looking at it. They would clearly know that it's all part of the same network.

I spoke to checkraze a good bit about the ship.  Between the Ship&dev and on the older close (and link) request.

**Comment by MagnusCrowe** [comment]
image
Remove the personalized ship description and replace it with an accurate description of the function of the ship.  These descriptions are to help players decide which ship to purchase.

**Comment by MagnusCrowe** [comment]
image
Please do not use custom filled lockers, there are prefilled lockers to use. If you don't see the prefilled gun safes then update your branch to the latest.

Remove the web from the left side dock.

If this ship is supposed to be an archaic 2nd hand ship in desperate need of maintenance, IDK if I like that it has fully stocked vending machines.  Makes little sense to me.  If you could figure out a way for them to be empty at the start that would make sense to me.   Also the chem vend does not need to be there, it might be more satisfying for players who choose this ship to find a chem dispenser board on expedition and build it into the medbay as a desperately needed upgrade to the ship.

Overall, there's too much light, and it is all homogenous.  You could probably remove a lot of those lights and replace some of them with dimmer lights, like red.  Even a few broken lights might fit the vibe better too?

**Comment by MagnusCrowe** [comment]
image
Pretty sure the discrepancy here indicates that your whole 2 core AME could be easily replaced with a single SUPERPACMAN generator running at 31-32 kW.  Which might help with the next issue...

image
Your cargo loading pathway and cargo areas are constricted.  I would certainly find it annoying to bring cargo from an expedition onto the ship.  The docking hallways are WAY too narrow and winding for that, so the only other option is the double door at the back.  Hope I explained that well enough.  You might consider replacing the AME or reducing it to a single core and shifting it to either side?

**Comment by dvir001** [comment]
> gun safes

Still missing from code, for now they can do something basic, and we can replace it later with real spawner.

**Comment by MagnusCrowe** [comment]
Oh yeah, if you want to put a personal indicator on the ship I recommend you use the gold plaque.
image
Just be aware of roleplay consequences, it might be weird for people to see that Sam American is a ship architect if that's not really in his wheelhouse as a character.  Or even worse if the ship is from a bygone era, it would be extremely weird for whoever the architect is to be alive.

**Comment by VividPups** [comment]
New Pictures of it With and without Mapinit


image




image

I removed some of the lights to make it darker

I replace the Mabela with Python(or inspector) I switch them for the Firing speed. I was going to put a Mosin with speed loaders instead but, it seems like those speedloaders don't work 

The description of the ship should be different now

The AME was changed from a 2-core to a 1-core.  Since the 2 cores isn't needed. it gives more space in the bottom 

Chem vending was removed and replaced with 3 chem crates instead

Mr Chang's vending was removed and replaced with 1 box of Donk Pockets

removed Gunsafes and added Gunracks.

**Comment by Cheackraze** [comment]
lgtm as long as it all works in game, should be ready to merge

**Comment by dvir001** [comment]
> lgtm as long as it all works in game, should be ready to merge

I think @MagnusCrowe was still looking for some changes.

**Comment by VividPups** [comment]
@dvir001 Like what

**Comment by dvir001** [comment]
> @dvir001 Like what

I pinged him to confirm, if he gives the green light he will just merge it.

**Comment by VividPups** [comment]
I spoke to Magnus Crowe in VC as I was making addition changes as far as I know he doesn't have anything.

**Comment by Cheackraze** [comment]
I know you've put a lot of work into it and we are in the final stretch, but the Prototype checker found a security intercom. switch that out for a generic intercom and I'll merge it

**Comment by VividPups** [comment]
@Cheackraze Intercom was Changed

**Comment by MagnusCrowe** [comment]
- You need to add a late join spawn point.  
- You need to remove the loose guns and ammo. Replace with a T2 gun safe.
- The merc EVA suit wall locker is glitchy where it's placed, you might want to test it out and consider moving it.

**Comment by VividPups** [comment]
I'm sorry but, I had rebuilt this from the ground up twice. I have made so many changes that I was against and disliked(some that was EXTREMELY long changes). Been told about merging so many times and had the feeling of being ready, done and set to Stone. 
Then told to make significant more changes to the ship. I make those changes wait Even longer. Just to get told to do more changes Over and over again. To now it kinda of feels like it isnt design/vision of the ship now

I been extremely cooperative and patiences during the changes and proccess.
I understand that yall are setting guidelines and making sure my ship is close to the guidelines and within the guidelines as much as possible So, I won't do more work in the Future and I appearicate that.

I understand the late join spawn and the Merc  and those I willing to change. 

The reason why I don't want to do the T2 safe is because I want guarantee a 45cal(44?) 6 shot revolver. Which from looking at the PR for the gun safes its random. I also dislike the Deckard due to the fact that have are force to have 1 less bullet in the chamber. Which I feel having 1 more bullet is more valuable to the player in a Life or death. Which in my personal case. I have die more because of having to reload vs the speed of the firing rate. I originally wanted the Mabala but I change it to the inspector due to the Speed and power the mabala will do. 

 I am willing to remove both Sawoffs and the Shotgun ammo in order to have the single inspector with its ammo and if that isn't a compromise that can happen. 
I would rather just close the PR.

**Comment by dvir001** [comment]
The gun lockers are required to stop the need to buy a ship just for the weapons on board
This is taking effects on all ships with any guns, this isnt an attack on you but a long time fix we need to do in order to stop "I just added this laser" or "I just added this shotgun" power creep of people trying to top other ships by adding more guns to them

Ships are not about the weapons that come in them
The weapons are a nice bonus, and by keeping all ships to a random system we can ensure all ships get the same guns baseline to make it fair for everyone. 

You can get more guns from expo, gun vends, and find them on space salvage.

**Comment by VividPups** [comment]
The random system within itself isn't balanced in t2 you have 50% of getting a shotgun verse getting an MK58 or the Deckard (25% chance). Expedition-based ships should have a different gun pool versus other non-expedition ships and sec ships. Because ships aren't post to be equal.. why should Medical, mining, and/or sec ship have the same types of weapons versus a ship whose main designs (or even secondary designs) are going on missions where they 100% will have combat? what use are rubber rounds going to be to people who are doing expeditions "you can buy lethal" not for 45. 
why do I need to waste more money buying ammo for a gun? which brings me to my other point. 
Lets say you do get a Deckard in the T2. you get 11 rounds total  (if it's rubber then you are fuck. The total damage you can do with that is 385. the MK58 has 20 rounds is 320, the shotgun has 22 rounds is 1584, Argenti has 66 rounds 1122, and the Mosin has 66 rounds is 1140 (which barely anyone uses the Mosin) this also isn't talking about bleed damage or the DPS that happens with combat
So instead of having gun safes that are random, why not make a list (with the rules) of all weapons that can be mapped and cant be mapped with additional restrictions on how many guns can be mapped of each Tier with pricing threshold that must also be met in order for you to have said weapons. and if someone wants to spend all the money to just be able to get better chances in combat then they should.

**Comment by dvir001** [comment]
Mining and medical ship should not have full guns safes on round start
We did make a list of guns you can spawn, in the automated safe spawner.
You can buy lethal ammo for your none lethal gun in the vender, that exists in the expo area you can get a ship from.

If you find any ammo that is missing from the vender let us know and we can fix it.

**Comment by Cheackraze** [comment]
The very fact that you're having a gun balance debate on a ship PR is exactly the reason why they are removed from ship spawns.  Buying a ship solely for a single item it has on it is not good gameplay, design, nor rp.  Having a gun balance debate is fine, but we are removing all gun spawns from ships.

I shouldn't have to come in here and repeat what the maintainers say. Their review is equally as valid.  The non-dterminitve nature of the safe is the exact goal, so people stop buying an entire ship for 1 item.

The gun will need removing, and you may place a gun safe in its place appropriate to the value of the ship.

**Comment by VividPups** [comment]
All the guns I am referencing is from the gun safe spawner list and I am really talking about you having an additional 25% chance of getting a shotgun versus the other 2 weapons all the guns; t2 and below you can buy (but the Deckard) in order to make that more balance I suggest adding the Cobra which is exactly like mk58 but a different caliber (and also class 1 with the mk) if doing so Cobra would need to be added to the less then lethal and to the liberty station with lethal ammo  (nonlethal 25 is already in less than lethal) and the inspector which I will feel is more balance because even tho you have 6 shots instead of 5 you also have less firing rate. where about the mabela is the most powerful one and the python has the same firing rate as the 

If the Inspector and Cobra was added It would balance out the chances of the weapons to each weapon group would be 33 percent chance then  50% for double barrel shotgun, 25% for the other (deckard and mk58) 

 You are also not able to get a .45 caliber lethal ammo. So if you get a 45cal weapon from the T2 and it spawns with nonlethal. then you are just force to use T1 weapon (which isn't the case for the other t2 weapons)

**Comment by Cheackraze** [comment]
Like I said, this is not the place for a gun balance discussion.

**Comment by VividPups** [comment]
@MagnusCrowe the Merc locker seem to be working fine. can you tell me more about what do you mean by glitchy?

**Comment by MagnusCrowe** [comment]
> @MagnusCrowe the Merc locker seem to be working fine. can you tell me more about what do you mean by glitchy?

Yeah, when I went up to it, as a player and not a ghost, I could not open it unless I was standing in an extremely specific spot off to the side of the locker. Same issue closing it.

**Comment by VividPups** [comment]
> > @MagnusCrowe the Merc locker seem to be working fine. can you tell me more about what do you mean by glitchy?.
> 
> Yeah, when I went up to it, as a player and not a ghost, I could not open it unless I was standing in an extremely specific spot off to the side of the locker. Same issue closing it.
> 
> If you're ok with that then you can leave it alone. Maybe it is something wrong with the locker itself that will get patched.

were you standing inside the Merc room or the loungething room?

**Comment by MagnusCrowe** [comment]
> > > @MagnusCrowe the Merc locker seem to be working fine. can you tell me more about what do you mean by glitchy?.
> > 
> > 
> > Yeah, when I went up to it, as a player and not a ghost, I could not open it unless I was standing in an extremely specific spot off to the side of the locker. Same issue closing it.
> > If you're ok with that then you can leave it alone. Maybe it is something wrong with the locker itself that will get patched.
> 
> were you standing inside the Merc room or the loungething room? because in the Merc room it seem ok. But, I am seeing the problem (which I bet is the same problem) with the prisoner which... it does look ugly there.

Really? I was in the merc room.

**Comment by VividPups** [comment]
requested changes were made

**Review by MagnusCrowe — APPROVED** [review]

**Comment by Cheackraze** [comment]
> > > > @MagnusCrowe the Merc locker seem to be working fine. can you tell me more about what do you mean by glitchy?.
> > > 
> > > 
> > > Yeah, when I went up to it, as a player and not a ghost, I could not open it unless I was standing in an extremely specific spot off to the side of the locker. Same issue closing it.
> > > If you're ok with that then you can leave it alone. Maybe it is something wrong with the locker itself that will get patched.
> > 
> > 
> > were you standing inside the Merc room or the loungething room? because in the Merc room it seem ok. But, I am seeing the problem (which I bet is the same problem) with the prisoner which... it does look ugly there.
> 
> Really? I was in the merc room. Maybe it has something to do with the rotation of the ship.

wall object interactions have had a history of being difficult to be in range of, you often have to be like faceplanted into the damn things sometimes, im not sure theres anything we have the power to fix. so long as its 'facing' the appropriate direction and it looks good it should be fine

**Comment by VividPups** [comment]
> > > > > @MagnusCrowe the Merc locker seem to be working fine. can you tell me more about what do you mean by glitchy?.
> > > > 
> > > > 
> > > > Yeah, when I went up to it, as a player and not a ghost, I could not open it unless I was standing in an extremely specific spot off to the side of the locker. Same issue closing it.
> > > > If you're ok with that then you can leave it alone. Maybe it is something wrong with the locker itself that will get patched.
> > > 
> > > 
> > > were you standing inside the Merc room or the loungething room? because in the Merc room it seem ok. But, I am seeing the problem (which I bet is the same problem) with the prisoner which... it does look ugly there.
> > 
> > 
> > Really? I was in the merc room. Maybe it has something to do with the rotation of the ship.
> 
> wall object interactions have had a history of being difficult to be in range of, you often have to be like faceplanted into the damn things sometimes, im not sure theres anything we have the power to fix. so long as its 'facing' the appropriate direction and it looks good it should be fine

after I look at it... then the Prisoner Wall closet just wasn't working (when I put fill in) so I just Moved the Eva suit wall locker to where the prisoner wall closet was at. and then just put a regular locker to be a replacement. I think just the worst thing when trying to place something is when you rotated  there is an actual indicated of it turning (with the expectation of somethings)

**Pull request merged**
