### PR TITLE
Replaced Beaker tiny fans with directional fans.

### PR DESCRIPTION
**Pull request by dustylens**
## About the PR

@UncaughtEx Hi, doing a small update to the fleet to replace tiny fans with directional fans. Give a shout if you would prefer to do that yourself!

Removed and replaced tiny fans with directional fans.
Added fuel locker, removed loose fuel.

## Why / Balance

Compliance.

## How to test

Check airlock doors for tiny fan replacements.
Check that the fuel locker is accessible.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

🆑 
- tweak: Replace Beaker tiny fans with directional fans.

### CODE REVIEW

**Comment by UncaughtEx** [comment]
Sounds good to me

**Comment by chrome-cirrus** [comment]
Tested locally. Fans work, didn't get suffocated. Fuel source is accessible with the generator access shutters raised. Seems good to go.

fans1
fans2
fans3
fans4
fans5
fuel

**Review by whatston3 — APPROVED** [review]
Removed some cruft, but the directional fans seem fine.  Fixed the gas mixer ratio.

Seems fine to me.

**Review by ErhardSteinhauer — APPROVED** [review]
Looks good, working

**Pull request merged**
