### PR TITLE
Shuttle clean up follow up

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
PR will be in draft until changes made to the shuttles are tested.
Following yml-edits to the files were made:
- Removed job spawners.
- Removed trash spawners.
- Removed kitchen related machines (primarily microwaves) from non-food trucks.
- Removed food.
- Replaced filled weapon safes with empty ones.
- Removed Chemical machines and supplies from non-medical shuttles.
- Removed medical items from non-medical shuttles: removed medkits, filled cabinets are replaced with empty ones, vendomats replaced either with cabinets or machine frames.

## Why / Balance
Clean up, push towards narrower shuttle specialization.

## How to test
1. Load shuttles from the list

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Possible everything

**Changelog**
:cl: erhardsteinhauer
- remove: Removed food items and machines from non-food shuttles.
- remove: Removed medical/chemistry related items and machines from non-medical shuttles.

### CODE REVIEW

**Comment by arimah** [comment]
Re Stellaris: That's a service ship with an integrated kitchen. The idea is that it can serve simpler meals and refreshments alongside whatever performance is being put on. Removing its microwave and ChefVend leaves it with a crippled, non-functional kitchen. The ship should either be reworked not to include a kitchen at all, or be allowed to keep its kitchen. If the kitchen is removed, the ship will likely see even less use as one of its selling points is negated.

**Comment by ErhardSteinhauer** [comment]
> Re Stellaris: That's a service ship with an integrated kitchen. The idea is that it can serve simpler meals and refreshments alongside whatever performance is being put on. Removing its microwave and ChefVend leaves it with a crippled, non-functional kitchen. The ship should either be reworked not to include a kitchen at all, or be allowed to keep its kitchen. If the kitchen is removed, the ship will likely see even less use as one of its selling points is negated.

irc the original PR, the shuttle was supposed to be a theatre. and the PR was submitted before the guidelines were a thing (I think), hence the kitchen.

**Comment by ErhardSteinhauer** [comment]
Hm. Perhaps Stellaris should be delisted until someone reworks it?

**Comment by arimah** [comment]
> the shuttle was supposed to be a theatre

I mean... theatres in real life also sell food. That's where the profits are!

**Comment by dvir001** [comment]
> > the shuttle was supposed to be a theatre
> 
> I mean... theatres in real life also sell food. That's where the profits are!

Alot of them do catering or outside service and don't actually hire kitchen stuff.

**Comment by whatston3** [comment]
> I mean... theatres in real life also sell food. That's where the profits are!

What if there was a specialized "junk food prep kit" you got for theatre concessions instead of ye olde stocked pantry?

Okay, you can serve food, but it's a pack of C&Ds, DIY popcorn and a large soda.

**Comment by ErhardSteinhauer** [comment]
You know what? I'll redo this PR and make it a bit cleaner. And will not touch vending machines in updated version.

**Comment by ErhardSteinhauer** [comment]
Reworked the PR, should be good for testing

**Comment by ErhardSteinhauer** [comment]
Left the kitchen on that **_theatre_** shuttle untouched

**Comment by ErhardSteinhauer** [comment]
Right, so I bought every shuttle I changed. They spawned upon purchase without errors.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
