### PR TITLE
Frontier NFSD QoL

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

Changelist for Sheriff/Bailiff box (primary role-play value: NFSD administration and command):
- Removed 1 mass scanner (1 -> 0)
- Removed 1 criminal records console (1 -> 0)
- Added 1 ID card computer (0 -> 1)
- Added 1 station administration console (0 -> 1)

Changelist for general NFSD brig area (primary role-play value: brig management):
- Removed 1 security shipyard console (1 -> 0)
- Added 1 criminal records console (0 -> 1)
- Added 1 wallmount ATM on the southeast wall of the box, primarily for payroll deposits, but could also be used for roleplaying paying off bail amounts (0 -> 1)

Changelist for NFSD reception (primary role-play value: talking to people needing services from NFSD, this does not entirely hit the mark, I know):
- Removed 1 station administration console (1 -> 0)
- Added 1 security shipyard console, potential problem here is it's only 1 windoor to get to this computer now (0 -> 1)
- Added 1 fax machine, named Frontier Outpost NFSD (0 -> 1)

**Overall changelist for entirety of NFSD:**
- Removed 1 mass scanner console (2 -> 1)
- Added 1 ID card console (0 -> 1)
- Added 1 ATM (1 -> 2, if you're counting the one just outside of reception)
- Added 1 fax machine (0 -> 1)

## Why / Balance

Attempt to streamline some tasks that have been outlined as tedious in [this discord thread](https://discord.com/channels/1123826877245694004/1187938250577412106).

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

This is what NFSD looks like after this patch:
Screenshot from 2023-12-23 12-47-53

**Changelog**

No CL!

### CODE REVIEW

**Comment by dvir001** [comment]
Dont remove the station administration console we need it there to remove the access of sheriff from SR room
And then remove sheriff SR access

**Comment by dvir001** [comment]
> Dont remove the station administration console we need it there to remove the access of sheriff from SR room And then remove sheriff SR access

My bad you just moved it.

**Comment by TsjipTsjip** [comment]
> My bad you just moved it.

Yup! Sorry, split changelists might not have been the best idea...

**Review by Cheackraze — APPROVED** [review]

**Comment by dvir001** [comment]
@TsjipTsjip When you get the time
Need to fix the SR office so we can remove SR permas from sheriff

Sheriff still need to be able to get to the ptech for new hiring, or give sheriff a private ptech, your call

**Comment by TsjipTsjip** [comment]
> @TsjipTsjip When you get the time Need to fix the SR office so we can remove SR permas from sheriff Doors need to have general frontier command on them and not just SR.
> 
> Sheriff still need to be able to get to the ptech for new hiring, or give sheriff a private ptech, your call
> 
> We made sure sheriff can use the Frontier ATM + Ptech with sheriff permas so this wont be an issue.

@dvir001 No worries! I will look at it when I can.

**Pull request merged**
