### PR TITLE
Plushie update

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Adds a TON OF PLUSHIES and new ways to get plushies with PrizeBall/Prize Tickets! Aka making playing arcades games and plushies selection more intresting!

Note: @Cheackraze please review and gives opinion for those 2 plushies: "Janitor Plushie and Office Vulp Plushie"

- [x] Prize Counter System + Prize Ticket.
- [x] Prize Ball.
- [x] Arcade Machines gives prize ticket.
- [x] Adds a ton of new plushies (Correctly coded and added)

Minor: Fixes Nuke Toy sprite to our current nuke sprite.

## Why / Balance

We need MORE PLUSHIES AND TOYS!
And more fun way to get them!
So i have delivered!

MORE PLUSHIES AND TOYS ARE NEEDED!

NOTE: Prize Counter is not mapped on Frontier for the current reason that i want this PR to be simple and only have yml and sprite changes, Prize Counter should be mapped on Frontier when possible.

## Technical details

Mostly .yml files and changes, only add new things and only change the arcade machine reward pool and cuddlycritter inv, this PR also avoid any C# changes.
## Media

image
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: FoxxoTrystan
- add: A ton of new plushies has arrived on the sector!
- add: Prize counter are here, get your prizes by winning games and getting prize tickets! and find prize balls!

### CODE REVIEW

**Comment by GentleButter** [comment]
3 rocks feels like beating the joke out of funny - i would just do one

also this needs to have the same components as mr chips and mr dips

**Comment by Ghost-Prince** [comment]
The pet rock needs to be a ghost role like Mr Chips the dummy, and also need to do some damage when thrown at someone making the rock go into crit. :)

**Comment by FoxxoTrystan** [comment]
ITS JUST A ROCK!

**Comment by Ghost-Prince** [comment]
Its not just a rock it's a real pet

**Comment by GentleButter** [comment]
i want the rock to know what love is. And also pain. I want the rock to feel what I feel.

**Comment by Cheackraze** [comment]
Was curious how you were planning to implement the counter, lathe is a clever solution.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
