### PR TITLE
Migration file split

### PR DESCRIPTION
**Pull request by dvir001**
Using DeltaV code to split the file.

https://github.com/DeltaV-Station/Delta-v/pull/673

### CODE REVIEW

**Review by whatston3 — COMMENTED** [review]
Looks alright - only concern is that a completely predictable order would be useful (rather than relying on the order `ContentFindFiles` returns).  Since the list of migration files we care about is small (currently two), I think it'd be fair to define the list statically (["/migration.yml", "/_NF/migration.yml"]) and avoid any order mixups or unwanted additions later.

Frontier comments would be nice.

**Comment by dvir001** [comment]
> Looks alright - only concern is that a completely predictable order would be useful (rather than relying on the order `ContentFindFiles` returns). Since the list of migration files we care about is small (currently two), I think it'd be fair to define the list statically (["/migration.yml", "/_NF/migration.yml"]) and avoid any order mixups or unwanted additions later.
> 
> Frontier comments would be nice.

Sure

Per comments file so changed at that points its the all file

**Review by whatston3 — APPROVED** [review]
Pushed a set of changes.

A few takeaways:
1. You can't have elements with the same ID (Dictionary.Add throws if a key already exists).
2. With two migrations A->B, B->C, these are not chained.  A is replaced by B and not C.  This might result in some trickier behaviour - if we need to have a replacement like A->C, and A->B exists upstream, we need to comment out A->B and add A->C explicitly in our migration file.

Give this another look when you can, seems fine and working on my side.

**Comment by dvir001** [comment]
> Pushed a set of changes.
> 
> A few takeaways:
> 
>     1. You can't have elements with the same ID (Dictionary.Add throws if a key already exists).
> 
>     2. With two migrations A->B, B->C, these are not chained.  A is replaced by B and not C.  This might result in some trickier behaviour - if we need to have a replacement like A->C, and A->B exists upstream, we need to comment out A->B and add A->C explicitly in our migration file.
> 
> 
> Give this another look when you can, seems fine and working on my side.

Honestly this should be fine

**Comment by whatston3** [comment]
Tests looked good, merging this.

**Pull request merged**
