### PR TITLE
pin dotnet to 8.0.204

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

Replicates https://github.com/DeltaV-Station/Delta-v/pull/1199 but pins to a slightly newer version for kicks
## Why / Balance

https://github.com/dotnet/core/issues/9309
## How to test

update your branches and push and let the comfort of the green check marks wash back over you
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Cheackraze** [comment]
packager still failing

**Comment by dvir001** [comment]
> packager still failing

Ca you merge it and see if it fixed after?

**Comment by Cheackraze** [comment]
sure merge it

**Review by dvir001 — APPROVED** [review]
Yolo

**Pull request merged**
