### PR TITLE
Remove Bing Guss Legs

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Long time coming

## Why / Balance
Its time

## How to test
Be Bing Guss
Legs no work

## Media
ss+(2024-09-08+at+04 26 11)

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Bing legs

**Changelog**
:cl:
- remove: Removed Bing Guss legs

### CODE REVIEW

**Comment by CautionDev** [comment]
This is critical, should be immediately merged to prevent Bing's legs from further terrorizing the server

**Review by ErhardSteinhauer — APPROVED** [review]
Come to think of it: why stop at legs? Remove hands too. Or lungs? Maybe something to consider next PR though.

**Comment by KyuPolaris** [comment]
> Come to think of it: why stop at legs? Remove hands too. Or lungs? Maybe something to consider next PR though.

Here's the thing, we need her to still make us cool lobby art. So hands may not be the best thing to also remove

**Comment by Everturning** [comment]
can't run away again

**Comment by dvir001** [comment]
Going to let Bing Guss keep her legs for a bit longer.

**Comment by dvir001** [comment]
Ok for real this time.

**Review by whatston3 — APPROVED** [review]
Not sure what this'll do to game balance, but I think it's worth a shot.

**Review by ErhardSteinhauer — APPROVED** [review]

**Comment by ErhardSteinhauer** [comment]
Balance, you see

**Comment by KyuPolaris** [comment]
the mad lad

**Comment by Tych0theSynth** [comment]
I just wanted to comment too because FOMO

**Pull request merged**
