### PR TITLE
Add Pious trait, blessing water/blood requires faith

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds a new trait, Pious, to get a bible and the ability to use it at round start.  For balance, Pious also includes the pacified trait.

The PR adds a (currently unused) "faith implanter" to get the BibleUserComponent.  This is intended to ship in mail along with those bibles, and provides players with a way to opt into Chaplain roleplay mid-round.

Blessing water into holy water or blood into wine now requires the BibleUserComponent.  Pious characters will be able to do this on round start with their equipped bible.

When a user is not Pious, they will get a notice when trying to summon familiars or bless water into wine.

### Potential Issues

I do not like how the order of operations is enforced here with the before parameter in event handler registration, and I don't like how temporary data is being stored in the BibleComponent.  This current solution is more fragile than I'd like, but I don't think I can do it with fewer changes.  Happy to hear advice to the contrary.

## Why / Balance

Removal of chaplain role made this difficult to get outside of admemes.  This should be useful for better chaplain RP, and I'd like to throw the faith implanter in mail packages with the bible if you get one.

The pop-up messages for the failure to bless or summon with a bible were added for extra feedback.

The holy water change seems fitting to the role, and should result in fewer impromptu miracles on station from the unwashed masses.

## How to test

Build and run locally.
1. Check the trait list.  Piety should show up with a sensible description.
2. Spawn in as a Pious character.  You should have a bible, and the bible should work as usual (see steps 9-11).
3. Run /golobby, spawn in as a non-Pious character.
4. Spawn a faith implanter, a bottle of water, and a bible.
5. Try to use the bible to pray, you should get a notice that you aren't worthy.
6. Try to use the bible to bless the water, you should get a notice that you aren't worthy.
7. Try to use the bible to summon a familiar, you should get a notice that you aren't worthy.
8. Inject the faith implanter.
9. Use the bible to pray.  It should work.
10. Use the bible to bless the water.  It should work.
11. Use the bible to summon a familiar, it should work.

## Media

Traits:
image

Faith implanter in use (note: prototype exists, but is not used in-game):
https://github.com/new-frontiers-14/frontier-station-14/assets/166147148/e8a2c81f-8f0e-4f7c-9131-c2023cc30528

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

Adds `BlockMix`, `LastInteractingUser` public fields to `BibleComponent`.

**Changelog**

:cl:
- add: Characters can now select the Pious trait to start with a bible, the ability to use it, and a vow of pacifism.
- tweak: Water and blood can only be blessed with a bible if the user is Pious.

### CODE REVIEW

**Comment by dvir001** [comment]
Isnt this just a free buff?

**Comment by whatston3** [comment]
> Isnt this just a free buff?

To get BibleUserComponent, a very cheap one, yes, but currently it isn't available without admin intervention.  I'd like some mechanical way to get the Chaplain role back again, and this is a proposal to do it.

**Comment by whatston3** [comment]
> We need to add something like a pacifist trait to anyone using it

That's interesting.

**Comment by dvir001** [comment]
> > Isnt this just a free buff?
> 
> To get BibleUserComponent, a very cheap one, yes, but currently it isn't available without admin intervention. I'd like some mechanical way to get the Chaplain role back again, and this is a proposal to do it.

Any powergamer will be using this as a base line

**Comment by dvir001** [comment]
Sorry missclick

**Comment by dvir001** [comment]
> > We need to add something like a pacifist trait to anyone using it
> 
> That's interesting.

Im not sure how else we balance 1000 spesos for buffs without making it RP role.

**Comment by whatston3** [comment]
> Im not sure how else we balance 1000 spesos for buffs without making it RP role.

Could only stock it in PietyVends, that way you need to make the trek to get the role.  Not much of a barrier to entry.

I'll look into forcing the pacifism trait on anyone that injects it, that seems reasonable to me.

**Comment by dvir001** [comment]
> > Im not sure how else we balance 1000 spesos for buffs without making it RP role.
> 
> Could only stock it in PietyVends, that way you need to make the trek to get the role. Not much of a barrier to entry, but still.
> 
> I'll look into forcing the pacifism trait on anyone that injects it, that seems reasonable to me.

Its either that or everyone on the server are now paladins LAMO.
pacifism is just a comp you can add with the ensure comp here, easy fix.
One issue I can think of is someone removing the implant and then adding it back, you can make it impossible to be removed tbh, or just make it a trait.

**Comment by whatston3** [comment]
Requires some rework, will reopen when it's ready.

**Comment by whatston3** [comment]
Implanter is no longer obtainable in game, though the prototype still exists.  Added Pious trait in its place.

**Comment by whatston3** [comment]
Updated the branch.  The tools tab in loadout selection now contains an option for the bible and faith implanter for 5000 spesos (increased from 2500).  The Pious trait still exists with the downside of pacifism.  Happy with either (slight preference towards the tool) or both, take your pick.

Should settle on an approach to this issue.  Any solution is a restriction on access to holy water compared with the current state of master, and an increase in access to prayer (possible admin spam), familiars (more ghost roles, yay), and healing (powergaming?).

I think that the benefits to chaplain gameplay outweigh the downsides, but that's my bias.

**Comment by K4rlox** [comment]
being able to be holy again is nice

being permenetly pacist is i think a too heavy of a negative

**Comment by whatston3** [comment]
> being able to be holy again is nice
> 
> being permenetly pacist is i think a too heavy of a negative

What would you pay to be holy?

**Comment by VividPups** [comment]
100% is too negative and dumb.

**Comment by VividPups** [comment]
It shouldn't really be a  pay to be holy thing really

**Comment by whatston3** [comment]
> It shouldn't really be a pay to be holy thing really

Ideally, I think it would be fun to go through some in-character rigmarole to become holy - travelling to the omnichurch to visit some POI-unique thing and going through a minigame or something to get your trait.  That's fun, but tricky, and will take considerably more effort to create, so this exists as a stop-gap.  Compared to what currently exists (_nothing_), I believe this is a step up.

On the current head of the feature, you can get an injector for $5k and your tool slot or by taking the Pious trait.  I will argue that, without chaplain slots, this is a mechanical improvement over having to pester the admins to become a chaplain.

**Review by Cheackraze — APPROVED** [review]

**Comment by Cheackraze** [comment]
i agree with having some kind of 'trial' or 'challenge' to get the powers, but this is the best solution we have right now with existing game systems

**Pull request merged**
