### PR TITLE
Changed the detective's spawn clothing options

### PR DESCRIPTION
**Pull request by RangerXVII**
## About the PR

Added a grey fedora, detective noir jumpsuit and jumpskirt to the detective's loadout.

## Why / Balance

Everything I added was already available in the DetDrobe, I just made it so that a detective does not need to go to their office for a grey fedora or noir jumpsuit.

## How to test

1. Open the detective loadout page.
2. Note the new items in the head and jumpsuit categories.
3. Choose any of them.
4. Spawn as detective and note that you spawn with what you chose.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added new clothes to the detective's loadout.

### CODE REVIEW

**Comment by whatston3** [comment]
Looks fine, seems reasonable, might change the names while we're here if that's fine by you.

**Comment by whatston3** [comment]
Suggestions here: [whatston3:nfsd-detective-clothing-options-change-suggestions](https://github.com/RangerXVII/frontier-station-14/compare/nfsd-detective-clothing-options-change...whatston3:frontier-station-14:nfsd-detective-clothing-options-change-suggestions)

More consistent with other loadouts, pardon the mess - detectives will probably lose their outfits given the ID changes, but what better time to pick your outfit than with entirely new wardrobe options.

**Comment by RangerXVII** [comment]
yeah those names do make a lot more sense.

**Review by whatston3 — APPROVED** [review]
Looks good to me.

**Comment by whatston3** [comment]
I'll resolve the conflicts, test and merge, thanks for the PR.

**Pull request merged**
