### PR TITLE
Liquidator (Update)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
_"A small vessel equipped with everything you need to make even the dirtiest ship squeaky clean (ducky slippers included)."_, - Shipyard.
**Ship size:** Small (175 tiles)
**Recommended crew:** 2
**Cost:** 31600
**Power Gen Type:** Uranium
**Expeditions:** No
**IFF Console:** No
**Available Roles:** Janitor, Pilot, Atmospheric Technician, Chemist

## Why / Balance
Updated NC Liquidator in accordance with current mapping standards.

## Technical details
- Atmos rework.
- Added Janitor Locker and JaniDrobe.
- Added disposals.
- Replaced PACMAN with SUPERPACMAN.
- The Engine Room is radiation proof: added Radiation Shutters, covering windows and airlock of the engine room.
- Enabled Pilot Job.
- Moved ship.yml to /Maps/_NF/Shuttles/

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated NC Liquidator to current mapping standards, simplified atmos setup.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
I do not see a reason for a janitor ship to have a full captain and atmos hardsuit locker.  Thematically, I do not think the ship should even have a captain's locker with full dress uniform with gloves, cloak, armor, etc. 

Please remove the atmos locker and the captain's locker.  You can replace it with an empty captain's locker and an EVA locker if you think the ship needs an EVA suit.

**Review by MagnusCrowe — DISMISSED** [review]
I do not see a reason for a janitor ship to have a full captain and atmos hardsuit locker.  Thematically, I do not think the ship should even have a captain's locker with full dress uniform with gloves, cloak, armor, etc. 

Please remove the atmos locker and the captain's locker.  You can replace it with an empty captain's locker and an EVA locker if you think the ship needs an EVA suit.

**Comment by ErhardSteinhauer** [comment]
> I do not see a reason for a janitor ship to have a full captain and atmos hardsuit locker. Thematically, I do not think the ship should even have a captain's locker with full dress uniform with gloves, cloak, armor, etc.
> 
> Please remove the atmos locker and the captain's locker. You can replace it with an empty captain's locker and an EVA locker if you think the ship needs an EVA suit.

- Replaced captain's locker with Suit Storage Unit [EVA].
- Replaced AtmosTech Locker with Radiation suit Storage locker.

**Comment by arimah** [comment]
> Thematically, I do not think the ship should even have a captain's locker with full dress uniform with gloves, cloak, armor, etc.

I agree with this in general, but will note that _some_ captain clothing is nice as a means of allowing ship-owning janitors to distinguish themselves from the station janitor. Personally I always wear the mantle, but YMMV.

> Replaced captain's locker with Suit Storage Unit [EVA].

A captain's locker, empty or not, is nice for keeping your earnings and other valuables in.

> Replaced AtmosTech Locker with Radiation suit Storage locker.

If you remove this locker (and I think it should be removed – the Liquidator is a bit overkitted for a janitor vessel), then the atmos tech job should probably go away too. I'm not sure what an atmos tech would even _do_, other than... drag a scrubber back and forth?

**Comment by ErhardSteinhauer** [comment]
> I do not see a reason for a janitor ship to have a full captain and atmos hardsuit locker. Thematically, I do not think the ship should even have a captain's locker with full dress uniform with gloves, cloak, armor, etc.

Technically, shipowner right now holds the position of captain. There isn't half-filled variant of captain's locker - it is only full or empty (and I don't think it should be changed). I personally only care about captain's mantle as a token that differentiates shipowner from other people. (And I actually forgot to map it separately. ACK!)

**Comment by ErhardSteinhauer** [comment]
> If you remove this locker (and I think it should be removed – the Liquidator is a bit overkitted for a janitor vessel), then the atmos tech job should probably go away too. I'm not sure what an atmos tech would even _do_, other than... drag a scrubber back and forth?

Most likely I will simplify the atmos setup even further in one of the next updates. When that happens atmos tech role will be removed too.

**Comment by ErhardSteinhauer** [comment]
Added `chief researcher mantle` because its color palette matches janitor's. Renamed it in chief janitor's mantle.

**Comment by dvir001** [comment]
Janitor cloak with plunger slot added to replace the ``chief researcher mantle``.

**Review by dvir001 — APPROVED** [review]

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
