### PR TITLE
Forge Ship - Repair/Rescue Shuttle

### PR DESCRIPTION
**Pull request by kennedytcooper**
## About the PR

Adds the forge, a highly DIY-ready ship suited for repair, rescue, construction, or of course some classic salvaging. A paramedic with ample medbay rounds out the engineering-focused crew. A bit of assembly may be required.

**Media**

Screenshot from 2023-07-30 16-00-10

**Changelog**

:cl:
- add: the Forge, a civilian construction/rescue ship

### CODE REVIEW

**Comment by kennedytcooper** [comment]
I'm going to commit a more exciting version of this ship after thinking about it some more later, so don't worry about approving this or not until you see another commit

**Comment by kennedytcooper** [comment]
ok now it's ready for review

**Comment by Cheackraze** [comment]
i like the direction this has taken, like a chunk of a station broken off. the inclusion of med makes me ponder it's intended purpose but the quality and direction of the design has improved and I like where its going. maybe we can iterate on this in a more unique way on discord.

**Comment by kennedytcooper** [comment]
closing this for now casue I wanna focus on the other ships in the queue that have a lot of potential to see use right away

**Pull request closed without merging**
