### PR TITLE
Stinky trait

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added a new trait, stinky.

Gives you an examine action that tells you and others that you stinks.
Adds a popup every 5-10 minutes to remind people you stink if there around you.
Allow you to keep an air freshener in your pocket to remove the effect while you have it.

Thats all.

## Why / Balance
Some lizards will want this.

## Technical details
New trait, mostly yml and C#
There is a disabled option to use any type of gas with the trait, cannot be used unless you add gas type and activate the bool.

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame,

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- add: Some of our crew started skipping on showers to save water.
- add: Added the air freshener to the vendomat vending machine to allow our water saving crew to not smell so bad.

### CODE REVIEW

**Comment by Cheackraze** [comment]
I dont think having an innate ability to kill people is a good idea

**Comment by dvir001** [comment]
> I dont think having an innate ability to kill people is a good idea

It takes more then 2 hours in a small room to be noticeable, more more longer then any dead body takes.
Either way I lowered the amount even more. 

```
    - type: StinkyTrait
      timeBetweenIncidents: 5, 15
      durationOfIncident: 0.1, 0.1 // 0.01 per Incident
```

**Comment by dvir001** [comment]
Miasma is set to false, popup added.

**Comment by dvir001** [comment]
Reworked it for the last time, Its working as it need to be working, no gas per base trait, just the harmless popup.

**Review by Cheackraze — CHANGES_REQUESTED** [review]
This still has all the code in it for atmos, please remove

**Comment by dvir001** [comment]
> This still has all the code in it for atmos, please remove

The code block?
Ill like to use it for a mob later on that will show up on events, its fully disabled for the stinky trait, and even if was set on without having to say what gas you want it to use its still auto off.

If its still an issue I can un comment it till much later, but ill like to have it ready for later please.

**Comment by Cheackraze** [comment]
> > This still has all the code in it for atmos, please remove
> 
> The code block? Ill like to use it for a mob later on that will show up on events, its fully disabled for the stinky trait, and even if was set on without having to say what gas you want it to use its still auto off.
> 
> If its still an issue I can un comment it till much later, but ill like to have it ready for later please.

i think if you want this functionality for a future system, it should be implemented in that system instead and leave the pure trait code to be just the popup + air freshener

**Pull request merged**
