### PR TITLE
Bocadillo Ship - A Food Truck For One

### PR DESCRIPTION
**Pull request by kennedytcooper**
## About the PR

Adds the Bocadillo, a very small food truck ship perfect for a crew of one, or two people that really like each other. Fits in the budget of a new player, docks easily in more than one configuration, set up to handle sales and has just enough of everything but not too much of anything.

**Media**

Screenshot from 2023-07-31 16-57-07

**Changelog**

:cl:
- add: the Bocadillo, the perfect cheap and small food truck ship for one

### CODE REVIEW

**Comment by Cheackraze** [comment]
instead of the booze vender it needs chef vend, in fact maybe even the plasteel dinnerware as well since that's how you get plates and knifes and bowls and skewers. Wallmount withdraw only ATM is made for this as well. I like the idea, but having the windows and walls flipped like that on the left side of the ship is an odd choice. going to give strange sight lines for trying to pilot.

Be sure your ship has a station records console and that your job prototypes are set to [0,0] for spawning, as per https://github.com/new-frontiers-14/frontier-station-14/pull/122

**Comment by kennedytcooper** [comment]
ok this one is ready

**Comment by kennedytcooper** [comment]
The screenshot still shows the wrong vending machine but the actual yml is fixed to have both the chef vends

**Review by Cheackraze — CHANGES_REQUESTED** [review]
image
this glass structure makes the entire interior vulnerable to pirate laser fire and has weird sight lines.  Consider replacing the divider with solid wall and using a windowed door instead.

Also, use dirt for now instead of trays or you can wait for the heavy trays to get a better sprite.  Up to you, but I don't need another cheap way for people to get hydro trays.

**Comment by kennedytcooper** [comment]
happy to change the wall but I'll wait for the heavy hydro trays, dirt would seem odd here I think

**Comment by Cheackraze** [comment]
Heavy trays just got in, feel free to ping me when this is ready again

**Comment by kennedytcooper** [comment]
ready for review again

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
