### PR TITLE
Mail Carrier uniform accessibility

### PR DESCRIPTION
**Pull request by PeccNeck**
## About the PR

- Wardrobe restock boxes now work with the Boxing Drobe, MailDrobe, and RepDrobe
- Normalized Mail Carrier uniform names
- Uniform printer can now print Mail Carrier uniforms and coat

## Why / Balance

Restocking seems like a no-brainer. Mail Trucks also only come with a winter coat and not full uniforms, which were otherwise previously available from the (non-renewable) MailDrobe as Mail Trucks also lack a records console for job openings.

## Technical details

- New entries to `Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml` (frontier-specific clothing vendors)
- `mail carrier uniform` is now `mail carrier jumpsuit`
- (internal) `ClothingUniformMailCarrier` is now `ClothingUniformJumpsuitMailCarrier`
- (internal) `ClothingUniformSkirtMailCarrier` is now `ClothingUniformJumpskirtMailCarrier`
- New file `Resources/Prototypes/_Nyano/Recipes/Lathes/clothing.yml` (define recipes)
- New entries to `Resources/Prototypes/Entities/Structures/Machines/lathe.yml` (add recipes)

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

- Redefined `ClothingUniformMailCarrier` as `ClothingUniformJumpsuitMailCarrier`
- Redefined `ClothingUniformSkirtMailCarrier` as `ClothingUniformJumpskirtMailCarrier`

**Changelog**

:cl:
- add: Added Mail Carrier's jumpsuit, jumpskirt, and winter coat to uniform printer's recipes
- add: BoxingDrobe, MailDrobe, and RepDrobe are now restockable with wardrobe restock boxes

### CODE REVIEW

**Comment by dvir001** [comment]
You have to update the `migration.yml` file for the new ID changes or its going to error out Frontier and the mail ships.

https://github.com/new-frontiers-14/frontier-station-14/blob/4ddcef7159250feadeca8b7bf5b356b04f074c49/Resources/migration.yml#L4

**Comment by Cheackraze** [comment]
great change.  Dvir is right, however, and that anytime you change the ID name of an existing item in game, it needs an entry into the migrations file.

**Review by Cheackraze — APPROVED** [review]

**Comment by PeccNeck** [comment]
Apologies, wasn't aware. I did test briefly, including with the Mail Truck, and had no issues, but I've gone ahead and added it to `migration.yml` regardless.

**Comment by Cheackraze** [comment]
> Apologies, wasn't aware. I did test briefly, including with the Mail Truck, and had no issues, but I've gone ahead and added it to `migration.yml` regardless.

its a 'best practice' kind of thing. While it may not have broken anything for us, its possible a potential downstream may become broken without it, or somebody's work in progress may be affected and break if we dont have it.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
