### PR TITLE
Space Traffic Control Part 2

### PR DESCRIPTION
**Pull request by Partmedia**
This is Part 2 of Space Traffic Control. This plots the dock names (from the last part) on the radar console. Then, update Frontier Station's docks to have dock names.
stc

### CODE REVIEW

**Comment by Partmedia** [comment]
I messed up nullability references again; hang on before merging.

**Comment by Cheackraze** [comment]
> I messed up nullability references again; hang on before merging.

let me know when its ready, be nice to get this in it looks great

**Comment by Partmedia** [comment]
> > I messed up nullability references again; hang on before merging.
> 
> let me know when its ready, be nice to get this in it looks great

**Comment by Partmedia** [comment]
This PR is now ready.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
