### PR TITLE
Added the praeda cargo ship

### PR DESCRIPTION
**Pull request by drhat**
## About the PR
Introduces the Praeda, a large cargo/salvage vessel capable of expeditions.

**Media**
Praeda-Final-Datasheet

**Changelog**
:cl: AllfatherHatt
- add: Added the Praeda, a large salvage and expedition capable vessel.

### CODE REVIEW

**Comment by Cheackraze** [comment]
this is very nicely done, high effort, unique design, clear role intentions. its def. worthy of a further review, I see a few things I want to investigate like airlock entrances and wall mount ATM and stuff etc. but as far as basic/intended design and execution its good work.

**Comment by drhat** [comment]
The Wall ATM is a "withdraw only"-variant and is there for the QM to pay the crew, paying bribes- I mean problem solving money, doing on-ship trades etc.

**Comment by drhat** [comment]
Some atmos pipes were dual-layered going the same way so I removed those. QM office had cargo bounty computer so I changed that to Mass Scanner (so QM can scan for salvage targets), and most importantly I adjusted Steve The Hampter's burger fort so he has more space, also made sure he is more clearly holding hatchet and his latte.

**Comment by drhat** [comment]
I promise I'm done fiddling with details now

**Comment by drhat** [comment]
Okay I added missing firelocks and buttons for turning them on and off. I'm done now.

**Comment by Cheackraze** [comment]
image
a couple of these maints areas could use different tiles or underplating + catwalk to give a more utilitarian feel

**Review by Cheackraze — CHANGES_REQUESTED** [review]
the above 2 things and mostly just the overfilled armory are the only 2 things I think blocking this from getting merged into the game, this is a very nice luxury cargo~~nia~~ ship

**Review by Cheackraze — APPROVED** [review]

**Comment by drhat** [comment]
Sounds good to me, I'll get to work on making more polished changes

**Pull request merged**
