### PR TITLE
Adding more lobby art to te game!

### PR DESCRIPTION
**Pull request by wendyribstonpippin**
## About the PR
I added three lobby screen arts to the list of arts that can show up, and I hope you like them!

## Why / Balance
I originally made these pieces for other servers (and also to just have fun), but I think they'd fit nice enuff' here! I just really like contributing to open source projects, I think art should be shared and given freely for the fun of it, and so this is my way of showing my appreciation.

## How to test
I don't have the energy to just restart a whole buncha rounds until the artz show up, but I'm hoping i did things right and that no one has to bother doing that. éwè

## Media
staresblankly
xisters
secmakeover

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: xisters.png, secmakeover.png and staresblankly.png to the lobby screen rotation
- tweak: changed attributions.yml to reflect the cc status of the pieces i added (cc-by-nc-sa 4.0)
- tweak: changed lobbyscreens.yml so that the artworks would be pulled
- accidental tweak: i kinda sorta deleted lines of code and added identical ones? idk how that happenned. seems to still be as it was before so i guess it's fine but i just thought id mention it just in case.
-->

### CODE REVIEW

**Comment by dvir001** [comment]
I'll be honest here, while the art is fine we only have Frontier specifically made art added right now.

I'll leave this open if another maintainer think otherwise.

**Comment by wendyribstonpippin** [comment]
That's completely reasonable! I might make NF-specific art later anyways, so this was also just kind of me taking the opportunity to create a branch specifically for that, for art I'll add later. (also the mime art *is* a character that i *do* play quite often on frontier, fwiw)

**Comment by GreaseMonk** [comment]
I second Dvir's opinion the art looks good, just not relevant to frontier all that much- thank you for submitting your PR though i greatly appreiciate it

**Comment by dvir001** [comment]
Going to close this for now, feel free to open another PR if you would like to submit something else.

Thanks.

**Pull request closed without merging**
