### PR TITLE
LVHI Broom Shuttle (New)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### New shuttle:
- Micro shuttle for round start janitors. The shuttle can be bought from Outpost Staff Shipyard Console at Frontier Outpost by Janitor/SR. Cheap, but has all the tools a janitor might need to perform his duties outside Frontier Outpost.

### Bundled changes:
- Renamed SR Shipyard Console -> Outpost Staff Shipyard Console and moved it to the corner by the Dock 6c.
- Moved mail carrier shuttles to Outpost Staff Shipyard Console, removed Mail Carrier Shipyard Console.
- Mapped additional Station Beacons to the Outpost.
- Mapped cell recharger and recharger to SR's Office. Removed wall-mounted recharger.
- Mapped materials wall locker to mail carrier room on Frontier.
- Moved grid .yml for mailpod and parcel to SR folder.
- Made fixtures on small gyro and small thruster smaller.

## Why / Balance
Cheap micro shuttle to encourage round start janitors to clean not only the Frontier Outpost, but other POI too.

## How to test
1. Spawn as janitor, insert your ID into Shipyard Console and buy LVHI Broom.
2. Spawn as contractor/pilot/mercenary, insert your ID into Shipyard Console, observe lack of LVHI Broom on the list.
3. Spawn any ID that has Janitor access level or above (SR/ERT/Sheriff), insert spawned ID into Shipyard Console and buy LVHI Broom.

### Mail Carrier room changes

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- add: Added new micro shuttle LVHI Broom, available only to personnel with janitorial access from Outpost Staff Shipyard Console at Frontier Outpost.
- tweak: Placed Outpost Staff Shipyard Console in the nook by the Dock 6c (to the North from SR's office), , removed SR and Mail Carrier Shipyard Consoles from Frontier Outpost.
- tweak: Moved mail carrier shuttles and SR shuttle to Outpost Staff Shipyard Console.

### CODE REVIEW

**Comment by whatston3** [comment]
A nice little shuttle.  Little bit of a shame that it's only accessible by Frontier staff.

LVHI supporting the heaviest of industries, mopping the floor.

**Comment by arimah** [comment]
I _almost_ love this because it has _almost_ everything it needs. But where is the mop bucket?!

**Comment by ErhardSteinhauer** [comment]
> I _almost_ love this because it has _almost_ everything it needs. But where is the mop bucket?!

You either take those with you from jani room or you print them with 10 plastic/steel/glass you can found in wall-mounted locker.

**Comment by ErhardSteinhauer** [comment]
> 10 plastic/steel/glass

But I'm still not sure how much "free" materials is ok to map at shuttles.
(and custom filled locker is disgusting)

**Comment by arimah** [comment]
Unfortunately, I have discovered a problem with printing a mop bucket:
image

It is very stuck.

**Comment by ErhardSteinhauer** [comment]
Oh no

**Comment by ErhardSteinhauer** [comment]
space osha might not be too pleased about it
image

**Review by whatston3 — APPROVED** [review]
Pushed my old recommendation for the reskin of the SR console's screen.  Console seems good, access on ships make sense.  It's currently a bit hard to tell that the material locker is in the ship and not just a wall with the new sprites, might just be down to glare & low contrast.  Maybe the locked state on the lockers should be unshaded.

Regardless, seems fine to me.

**Comment by ErhardSteinhauer** [comment]
> Maybe the locked state on the lockers should be unshaded.

Wait, it isn't unshaded? My bad.

**Comment by ErhardSteinhauer** [comment]
> > Maybe the locked state on the lockers should be unshaded.
> 
> Wait, it isn't unshaded? My bad.

Will fix lockers in separate PR though

**Pull request merged**
