### PR TITLE
Add a vestine vial to the contravend

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
Adds a vial of vestine (30u) to the contravend at the cost of 15k spesos per vial.

## Why / Balance
Vestine is a crucial component of syndicate chemicals, and is unobtainable on frontier (unless you raid a syndicate vault, which is nearly impossible most shifts). Adding it to the contravend should open up new opportunities for pirates and other criminals.

Currently the contravend offers 6 vials, the price and count can be a subject for discussion.

## Technical details
3 added yml lines

## Media
- [X] this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl:
- add: The contravend now sells vials of vestine, a precursor to a few powerful chemicals.

### CODE REVIEW

**Comment by dvir001** [comment]
I honestly think this should not be added.

**Comment by Mnemotechnician** [comment]
Weren't you dreaming of adding more money sinks? Well, I can guarantee some people would love to waste a ton money in order to brew funny chemicals.

**Comment by Cheackraze** [comment]
i dont really follow most of the chemistry changes stuff, what does vestine do? Or i guess, what can you do with the vestine?

**Comment by amacura** [comment]
most usefull Nocturine, Stimulant, and Lexorin

**Comment by dvir001** [comment]
> Weren't you dreaming of adding more money sinks? Well, I can guarantee some people would love to waste a ton money in order to brew funny chemicals.

"Funny"
Insta sleep and insta death
So funny.

**Comment by Mnemotechnician** [comment]
> Having an option to bulk buy easy to make death and sleep drugs in not a good change.

Amatoxin kills anyone with just 10 units (6 damage per second, 0.5 units per second), and it's easier to grow than lexorin and harder to heal.

Nocturine... the recipe for this one could be removed whatsoever, if you think it's a big deal.

**Comment by Cheackraze** [comment]
hm i see, these chems are indeed very overpowered.  If anything, limit it down to 2 vials for sale _total_, since you cannot restock the contravend.  This would limit how much is actually available for use. I'm always loathe to completely remove something. Our point of view has always been that if a thing is fun and interesting but unbalanced, we should rebalance it instead of removing it. Doesnt always fit the situation (singulo, tesla, warp gates and teleportation for instance come to mind), but for things like this I'd rather the option still be open to players to participate in the gameplay.

**Comment by Mnemotechnician** [comment]
Limited it down to 2 as requested.

**Comment by dvir001** [comment]
I still think this chem should be a rare find from syndicate crates only.

IMO this chem do not bring any fun or engaging game play, instant killing or instant sending someone to sleep is an anti RP mechanic used for antgs to green text, as it goes against general RP.

**Review by FoxxoTrystan — APPROVED** [review]
Code Good!

**Comment by MagnusCrowe** [comment]
You can get vestine out of the syndicate cache from the random loot crates, can you not?

**Comment by Cheackraze** [comment]
with the recent changes to the hypos i'm willing to allow this i guess. at least for now, but if i see it abused will likely revert

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
