### PR TITLE
Behemoth NFSD Shuttle

### PR DESCRIPTION
**Pull request by Vladimir-Gonchar**
## About the PR

The Behemoth class cruiser is a universal NFSD vessel.

The shape is inspired by the cruisers from Starcraft 2.
Functionally, it is close to the outdated Marauder corvette.

Estimated crew - 6 employees.

Description of the vessel parts:
The glass bridge contains 6 posts for the entire crew, corresponding consoles and an EMP generator.

The middle narrow part of the vessel is designed for docking small vessels, namely Templar, Hospitaller and smaller ones (see attached file).
That is, the vessel can be used both as an independent patrol vessel and as a small base.

For each of the 6 crew members there is a personal locker for storing excess equipment, wall-mounted spacesuit storage.
Number markings on the walls can be used both to indicate a locker and to indicate an exit to the outside.
By analogy with Empress, it is possible to close the pressure doors before each exit or docking.

In the rear part of the ship, in front of the engineering compartment, there is a kind of parade ground for the formation of personnel.

In the left wing is a compact kitchen, minimally functional to be useful. The kitchen is present, firstly, by analogy with the Marauder corvette, secondly, since the possibility of self-catering should be present on combat vessels, and thirdly, for the possible hiring of a cook as a civilian worker.

At the left dock there is a brigmed post, minimally functional.

In the right wing there is an arsenal and a recreation area. The Armory is just that: an Arsenal, not a storage compartment for personal equipment. It contains additional armor, non-lethal weapons, tracker and mind shield implants, training bombs, and sapper equipment.

At the right dock there is a post for a warden, baliff or other person in charge of the ship's armory and cameras.

All airlock clearances are brig level, with the exception of the arsenal - armory, and entrance airlocks to the shuttle at the left and right docking points are public.

## Why / Balance

Something between middle and large ship possible for 2-6 crewmembers, in nice shape, with compact and usful contents inside, possible both as indepepndent ship and small base.
Alternative to outdated Maurder ship.

## How to test

Like any other shuttle on your server, save prototype file in:
frontier-station-14\Resources\Prototypes_NF\Shipyard\Nfsd
and grid map file in:
frontier-station-14\Resources\Maps_NF\Shuttles\Nfsd
just buy like any other shuttle on NFSD outpost.

## Media
behemoth_color
behemoth_connection
behemoth_light
behemoth_radar

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Nothing yet. You've read till the end - you're awasome!

### CODE REVIEW

**Comment by dvir001** [comment]
image

**Comment by Vladimir-Gonchar** [comment]
> image
> 
> What

Erm, what's wrong? Button in red frame is for right airlocks blust door. Toilet... well, it was located by residual principle, so it's public facility coincedentally =)

**Comment by MagnusCrowe** [comment]
image
Battlecruiser operational.  😛 

That being said, not an enormous fan of a mothership with side docks from a functionality point of view.  I'm pretty sure that isn't going to fly here.  Prepare for some hard news about re-designing the ship's spine.

image
Problematic.  Fix this.

image
Inaccessible wall accessories.  Remove the chemmaster.   

image
https://frontierstation14.com/index.php/Ship_Submission_Guidelines 

image
Xeno scum.  Remove, use a randomized poster instead.  You have to EARN your sexy posters, you can't cheat the system.

image
https://frontierstation14.com/index.php/Ship_Submission_Guidelines
Get rid of all this free weaponry.  Read the guidelines.

image
Autio

image
image


There's more about this ship that needs consideration.  I'll be back with more at a later date.  Dvir will probably have something to say about your kitchen.

**Comment by dvir001** [comment]
Closing this till issues addressed, feel free to reopen at any point ones it ready again.

**Pull request closed without merging**
