### PR TITLE
Sprinter shuttle update

### PR DESCRIPTION
**Pull request by Eagle0600**
## About the PR
Replaced tiny fans with directional fans.
Named O2 and N2 ports and added decals.
Replaced medical doctor's locker with wallmount.
Added dirt where the locker used to be.
Replaced AME fuel rack with wall locker.

## Why / Balance
Tiny fans create an enclosed atmosphere box that will quickly become unbreathable. Directional fans fix this problem.
Connector port changes bring the shuttle in line with other shuttles such as the Gasbender.
Wall lockers are preferred, especially for AME fuel.

## How to test
Load the Sprinter and walk around. Open all the airlocks while watching the atmosphere for any sudden drops or other changes. check that two AME fuel bottles are supplied in the wall locker.

### Directional fans
starboarddockfans
portdockfans
evafans
### Medical locker
medicallocker
### Engineering
engineering

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Retrofitted the Sprinter with directional fans and tweaked storage.

### CODE REVIEW

**Comment by dvir001** [comment]
Do not rename anything, this breaks forks translation

**Comment by dvir001** [comment]
Remove mapped coat

**Comment by Eagle0600** [comment]
Requested changes made and tested.

**Comment by Eagle0600** [comment]
> Base Transform removal's interesting.
I was tired of `tp` coordinates not lining up with `pos` coordinates when loading the map. And technically it inflates the filesize for no benefit, so I saw no sense in keeping it.

> colours seem a bit strange
The canister decals I added or the lights that already existed? I'm annoyed with the sodium lights but I'm not sure of the design intent behind them so I was being cautious about touching them.

**Pull request merged**
