### PR TITLE
Bank Data (Take 2)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
While it worked overall fine, we need to make it run with less lag overall,
Will require a small rewrite.

## Why / Balance
Open admin panel players tab and check balance

## How to test
N/A

## Media
image

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by dvir001** [comment]
@GreaseMonk @Cheackraze 
I will need your help, or anyone else who want to help for editing this PR to try and optimize it.

**Comment by dvir001** [comment]
Updated the code, need possible optimize.

**Review by whatston3 — CHANGES_REQUESTED** [review]
Pushed a small fix - all deposit requests (even with values of 0) are valid.  Also moved the balance up and the (ANTAG) value down (I do not think it gets shown apart from admemes), thought it looked better, can revert if you'd prefer it as it was.

This looks good to go, but should wait for #1909 to avoid performance issues.

**Review by whatston3 — APPROVED** [review]
Branch up to date, seems to work alright locally.  Should have less message passing than the prior take.

**Comment by dvir001** [comment]
Here we go again, hope this time will be cool.

**Pull request merged**
