### PR TITLE
Syndie Vessel Interception, WizFed Probe, Blood Moon (New NPCs, Bluespace Events, Dungeon Enemies)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### New mobs and factions
The main focus of this PR is adding new hostile humanoid NPCs to use in dungeons (they do in fact appear as dungeon enemies) and on wrecks that function better/differently that basic Hostile Salvager. NPC Features:
- Different factions: Syndicate, Wizard Federation, Blood Cult. All hostile towards each other, wildlife and NT.
- Varying gear loadouts for looks, loot and difficulty. And to give some love to items (or sprites) that exist in game files but aren't normally obtainable.
- Ability to chatter: from time to time the mobs will say flavour text.
- Usable for mapping: new mobs have spawners.

### New structures
Added some structures for Syndicate and Blood Cult (mostly for blood cult):
- cybesun dataminer - dungeon objective for syndie.
- bloodcollector - dungeon objective for cult.
- blood cult wall (indestructible, animated).
- blood cult glass airlock.
- blood cult floor hole and glowing tile (kind of carpets).
- blood cult gravity generator.
- blood cult wall light (animated).
- blood cult props (no functionality tied to those structures yet): forge, tome altar.

### New bluespace Events
Added 3 new Bluespace Events to demonstrate newly added NPCs and add some variety to the shifts:
- Intercepted Syndicate Vessel: __"Attention all available NanoTrasen personnel! NanoTrasen Naval Command disrupted the FTL-jump of Syndicate Vessel, according to our deepspace scanners the vessel either already entered the real space in your sector or is about to enter. Code: Intercept, Expunge, Exterminate, Cauterise. Expect armed opposition, use of lethal force against enemy agents is authorized. Do note: any loss of NT affiliated personnel lifes will not be compensated."__

- Detected Wizard Federation Probe: __"Attention all available NT personnel! NT Naval Command detected bluespace anomaly in your sector with the signature indicative of imminent arrival of a Wizard Federation micro vessel. Code: Intercept, Detain, Incarcerate. Arrest the intruders and prepare them to be handed over to NT Special Forces Unit for enhanced interrogation."__

- **Blood Moon Rising:** __"A̴̗̕ť̸͓t̸͍̂en̵̠̑t̸̗̅i̸̜̓on ̷̘̿all Sē̷͓curity ̶͗͜peṟ̴͆s̶̹̋onnel! NT ̸̛̯N̸͙̓ava̸̰̒l C̶̡͊omm̶͉̉a̷͖̾nd dete̷͙̽c̴̱͗te̶͓̓d bl̵͎͆uesṗ̴͉ać̴͉e an̵͚͋o̸̤͑må̴̫l̷̜͂y ̵̨͋in yȍ̴̠ų̶͝r sect̸̬̅or ̵͈͝w̴͍͊ith the s̶̖͌ig̵̰̓na̷͖͊t̶̲̑urē̴̮ ̸̪͛i̴̝͆ndicative of ̶͎̽imminent arri̸̞̅vaḽ̵̓ of ̷̣͛a̸̞͛ B̵̖͊loő̸̳d C̶̨̽u̵̥̇lti̵̐͜s̵̰̏t'̴̢͘s ̸͓̌vessel.̷̳͠ Security C̴̹͝ò̶̤de̴̦̕: In̴̛͎terc̸̨͆ep̴̤̉t̴̰̆, ̶̫̄Expunge, E̶̺͝xt̷͔̅erminate, C̸̮̽aut̶͉̕e̶̥͝rise. Expe̶̛̦ct armed̴̠̒ ̴̢̅op̷̤̄poś̸̗it̵̜̎ion, ̸̥̆u̵̪͂se o̵̠͂f̵̺̿ lē̸͕t̸͖͗hal fȏ̵̦rce ̶̻̍ag̷̠͒ain̵͖̏st enemy agen̸̳̎t̵̥̀s is autho̵͙͑ri̷̺͗zed̷̼̊. ̵̰̇Pȓ̸͚event N̵̯͛T-affiliate̸̺̓d ̷̞͐captains ̵̣̒wi̸̬̚t̴̝͆hout security̷̨̔ access from̸̖̓ gain̶̜̋ing access to the enemy ̵͔͛ve̸̖̋ssel and i̵̫͌ts coń̷̞te̷͋ͅnts. And ȑ̷̰e̶̬͗mê̴̬mb̶̨͘er:̷̜͠ ̸̤̎Na̶͘ͅr̶̳̚'Sie is n̸̮͆ot real ̸̝̀and can̸̦̽ nó̵̳t hurt ̵̛̭yoū̸ͅ."__

### New dungeon enemies
Syndicate Naval Forces and Blood Cultists can now be encountered in dungeons.
Syndicate related dungeons missions:
- Hunt down Syndicate Naval Commander.
- Destroy Cybersun Dataminers.

Blood Cultist related dungeons missions:
- Hunt down Ascended Cultist.
- Destroy Blood Collectors.

## Why / Balance
Spessmen need more things to shoot at (or get killed by).

### Event: Intercepted Syndicate Vessel
Use the following command to spawn the syndicate event: `addgamerule BluespaceSyndicateFTLInterception`
10 new hostile AI controlled mobs with set loadouts and spawners, new mobs are immune to low pressure and lack of oxygen, can't slip:
- Syndicate Naval Commander (effectively armed with AKMS), acts as megafauna in dungeons, has death acidifier implant. **Loot:** captain's sabre, AKMS, 2 rifle mags, syndicate commander hardsuit. Can not be encountered in bluespace event.
- Syndicate Naval Captain (effectively armed with Python loaded with AP rounds). **Loot:** Python with regular bullets, plasteel sword, syndicate captain armored coat.
- Syndicate Naval Second Officer (effectively armed with Advanced Laser Pistol). **Loot:** Advanced laser pistol, bulletproof vest.
- Syndicate Naval Engineer (effectively armed with Bulldog). **Loot:** Kammerer, bulletproof vest.
- Syndicate Naval Medic (effectively armed with Poisonous Darts, darts despawn). **Loot:** advanced circular saw, medical armored coat.
- Syndicate Naval Operator (effectively armed with Atreides SMG). **Loot:** Atreides SMG, kukri knife, bulletproof vest.
- Syndicate Naval Grenadier (effectively armed with China Lake). **Loot:** bomb suit.
- Syndicate Naval Saboteur (effectively armed with Viper loaded with EMP rounds). **Loot:** bulletproof vest.
- Syndicate Naval Deckhand (effectively armed with Viper). **Loot:** Viper, bulletproof vest.
- Victim of Experimentation (not syndie). **Loot:** shiv.

NPCs can't close gun bolts, so instead of giving them the ability to actually use guns, I "implanted" the guns inside them, works the same way as xeno spitters do. Gave mobs corresponding weapons just for looks/loot.

Other than the stuff on mobs, players will be able to find several contraband crates (those are random spawners, so no guarantee) scattered around the ship, 110k of loose cash, 1 bloodred hardsuit.

### Event: Detected Wizard Federation Probe
Use the following command to spawn the syndicate event: `addgamerule BluespaceWizardFederationScout`
5 new hostile AI controlled mobs with set loadouts and spawners, new mobs are immune to low pressure and lack of oxygen, can't slip, wield wizard's staffs (melee weapons that don't cast spells), have 25% reflect chance, have death acidifier implant, very high stamina:
- Blue Wizard (has "hardsuit" variation): conjures Blue Curacao Elementals (despawn after 30 seconds). **Loot:** wizard staff (no spells on it, just melee weapon) or same wizard staff and Blue Magus armor set.
- Red Wizard (has "hardsuit" variation): sets you on fire. **Loot:** wizard staff (no spells on it, just melee weapon) or same wizard staff and Red Magus armor set.
- Violet Wizard (has "hardsuit" variation): chokes you. **Loot:** wizard staff (no spells on it, just melee weapon) or same wizard staff and wizard hardsuit.
- Soap Wizard (has "hardsuit" variation): hurls bars of conjured soap (despawn after 10 seconds). **Loot:** wizard staff (no spells on it, just melee weapon) or same wizard staff and clown hardsuit.
- Blue Curacao Elemental (Based on Reagent Slime, but belongs to the Wizard Faction and doesn't breathe or suffers from low pressure). **Loot:** shit ton of blue curacao in your blood stream, I guess.

### Event: Blood Moon Rising
Use the following command to spawn the syndicate event: `addgamerule BluespaceBloodMoon`
7 new hostile AI controlled mobs with set loadouts and spawners, new mobs are immune to low pressure and lack of oxygen, can't slip, utilize cult equipment, primarily deal lots of slashing damage:
- Ascended Cultist (summons 2 drained ones), has 50% reflect chance, acts as megafauna in dungeons. **Loot:** none.
- Blood Cult Priest (caster), has 30% reflect chance. **Loot:** wizard staff (no spells on it, just melee weapon), set of acolyte armor.
- Blood Cult Acolyte (melee), has 30% reflect chance. **Loot:** ritual dagger, set of acolyte armor.
- Blood Cult Zealots (Melee and Ranged warriors), has 10/30% reflect chance. **Loot:** ritual dagger or crossbow, set of cultist armor.
- Leech (Melee). Fast. Leeches. **Loot:** none.
- Drained One. Summoned by Ascended Cultist, despawns in 45 seconds. **Loot:** puddle of liquid miasma. Yay!
- Blood Pylon (stationary turret). **Loot:** none.
Added some blood cult themed structures (most of them tgstation conversions). Purely cosmetic for now, might add functionality later.

### Event: Intercepted Syndicate Vessel
image
image
image
### Event: Detected Wizard Federation Probe
image
image
image
### Event: Blood Moon Rising
image
image
image
### New dungeon factions
image
### New structures
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Breaking changes
I'm not exactly an expert on matters of **balance**, so might be rough around the edges. From my tests all three events can be cleared solo, but it requires a bit of knowledge about the events themselves, good gear, meds and taking it slow. The Syndicate event (and syndicate mobs in general) is easily the hardest one among added.

**Changelog**
:cl: erhardsteinhauer
- add: New Bluespace Event. NT Naval Command disrupted the FTL-jump of Syndicate Vessel.
- add: New Bluespace Event. NT Naval Command detected a Wizard Federation Scouting Probe entering Frontier Sector.
- add: New Bluespace Event. NT Office of Faith and Believes issues aa announcement about seemingly increased Blood Cult related activity in the Frontier Sector and warns against worshiping fictional deities.
- add: New dungeon factions. Syndicate agents and Blood Cultists can now be encountered planetside.

### CODE REVIEW

**Comment by Cheackraze** [comment]
i like where this is going, though im concerned about giving out things like china lakes so easily. Let me know if you need any assistance in getting any of these up and running

**Comment by ErhardSteinhauer** [comment]
> i like where this is going, though im concerned about giving out things like china lakes so easily. Let me know if you need any assistance in getting any of these up and running

Yeah, I would appreciate help with balance. I already nerfed NPC loadouts (effectively loot from them) couple times but might not be enough. Might also remove NPC with china lake from expedition table entirely due to how easily it can be cheesed in expeds.

I think at this point both Syndie and Wizard Bluespace Events are functional, Syndie and Blood Cult expedition factions functional too. Right now I think I need a couple more props and assets for Blood Cult Bluespace Event/POI to make it look less like a conventional spacefaring vessel and mole like something infused with eldritch magic.

**Comment by dvir001** [comment]
Stick to hand and unrecoverable items like the evil clown has,
You can create a new parent for this and then sub items that has the original and this new perent on it

**Comment by ErhardSteinhauer** [comment]
I can actually turn human-NPC with china lake into mob without equipment and top it off with death acidifier implant.

**Comment by dvir001** [comment]
Keep in mind power gamer will find a way to out them to sleep so that gear need to not exists or fully embedded and not able to remove

**Comment by Leander-0** [comment]
would be just better to have a robot enemy that has the embedded chinalake to it.

**Comment by ErhardSteinhauer** [comment]
In all honesty I'm not too stocked about turning NPCs with gear into just mobs because changing their looks later will be horrible pain in the ass. Not to mention that they wont have such important for gameplay things like randomized appearance and names. Who can say no to being blasted to pieces by syndie who looks like your average internet SJW because of NPC hair cut and color?

How about I make damage resistances for those NPCs and give them nerfed gear, that inherits from corresponding pieces: "shredded bulletproof vest", "chocked china lake" (explodes in your hands when you try to fire it), "bent AKMS" (horrible spread), "california compliant Atreides SMG" (accepts only mk58 pistol mags, no full auto) and so on.

**Comment by ErhardSteinhauer** [comment]
I believe this PR is in decent enough state to no longer be a draft. From my testing things appear to be working: bluespace events spawn, mobs spawn and hostile both on events and in expeditions.

I would appreciate somebody else testing it and giving feedback.

**Comment by ErhardSteinhauer** [comment]
Gave this another pass and toned down loot from NPCs (removed china lake, bulldog, eldritch blade). Updated PRs description to reflect current state of mobs and loot from them. Some images are a bit dated, I'll update them eventually.

**Comment by ErhardSteinhauer** [comment]
Updated screenshots in PR

**Comment by ErhardSteinhauer** [comment]
Surprisingly not much was broken here after updates

**Comment by Cheackraze** [comment]
ok this is looking like its in a good spot for a formal official review, but it will take a good while. I will likely have time this thursday to do an in-depth review and maybe get this in and testing

**Comment by Cheackraze** [comment]
Ok, I split up reviewing this over a few days, but I couldnt find anything that jumped out at me. It is like, 20k lines of yml, so im trusting the linter quite a bit here.

Everything seems to work as described in-game, but I have 2 issues. For one, the summoned soap is too transparent and difficult to see. At first I thought it wasnt firing properly but it was just nearly impossible to see the soap, especially with the wizard lighting. Second thing, is the blood cult blood bolt guns shoot too fast, both the turrets and the NPCs. Their fire rate should be toned down a bit and maybe make the recharge time longer for the innate recharging. Syndicate enemies felt balanced only because the china lake NPCs had a tendency to just fire point blank, which is hilarious and accurate.

Once those 2 things are tweaked, I would say this is good to merge.

**Comment by ErhardSteinhauer** [comment]
Lowered fire rate for cultist and turret from 8 to 1 and 2 respectively, made conjured soap unshaded and added glow component to it.

**Comment by ErhardSteinhauer** [comment]
and increased recharge cooldown for cultists from 1 to 1.5

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
