### PR TITLE
More radars consoles

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Added 3 new Consoles and edited some, and edited the Empress map slightly.

(Range is the range of the radar and spawnrange is the range where asteroid will spawn.)
* Shuttle Console - Range: 256 - SpawnRange: 256.
* Advanced Shuttle Console - Range: 768 - SpawnRange: 256 (Circut Added)
* Syndicate Shuttle Console - Range: 1024 - SpawnRange: 256
* Station Traffic Control Console - Rabge: 512 - SpawnRange: 0

* Mass Scanner Console - Range: 512
* Advanced Mass Scanner Console - Range: 1024  (Circut Added)
## Why / Balance

Why does the Syndicate Consoles used for ship has a spawnrange of 1000? WE DONT NEED THAT!
SpawnRanges should be kept at 256, like normal shuttle do.

And add more Circuits so its may be added in gamerules events/expedition as a reward, ect...

Also replaced Empress Syndicate Console with the advanced one.

## Technical details

Added new Consoles and edited some, added some new circut and edited the Empress

## Media

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: FoxxoTrystan
- add: Advanced Shuttle Console / Mass Scanner Console.
- tweak: Replaced the Syndicate Console on the empress with an advanced one.

### CODE REVIEW

**Comment by Cheackraze** [comment]
After discussion, we likely will not allow any larger than 512 radar radius. Mostly because of performance reasons.

**Comment by FoxxoTrystan** [comment]
> After discussion, we likely will not allow any larger than 512 radar radius. Mostly because of performance reasons.

Question tho is the performance issue due to the WorldRadius that handle the asteroids/derlicts generation or something else?

**Comment by Kesiath** [comment]
Traffic control console is certainly needed and could probably have the longest range out of all the consoles since it's meant to stay on Frontier, but the range of other consoles probably shouldn't extend beyond 512. I'd personally be fine with the advanced shuttle console being a science research board with 512 range, meaning you no longer need to steal a mass scanner to have a decent radar.

**Comment by FoxxoTrystan** [comment]
Closing this as i supose those wont be added event with the spawn radiusedited but i will make a future PR to optimize current "Syndicate Consoles" on ships as we can edit those values in debug menu.

**Pull request closed without merging**
