### PR TITLE
Replaced Stellaris tiny fans with directional fans.

### PR DESCRIPTION
**Pull request by dustylens**
## About the PR

Fans.
Slight remodel to the engineering bay to allow for atmos compliance. Atmo systems repiped slightly to accommodate new space requirements.
Added fuel locker.
Looked around and reflected on how maybe the old bird may be yearning for retirement.

## Why / Balance

Compliance.

## How to test

Check atmos.
Check power.
Check locker.
Check fans.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 
- tweak: Replace Stellaris tiny fans with directional fans.

### CODE REVIEW

**Comment by chrome-cirrus** [comment]
Checked this out, tiny fans on both docks, atmos looks good. Revamped engineering room has the right stuff connected to the right stuff. Fuel is accessible. 

atmos
dock1
dock2

Minor note: Air alarm in the freezer was going off right when I bought/first boarded the ship. It recovered pretty quickly so doesn't really matter. Might need fixgridatmos run for the prefill to be right?

**Comment by Tych0theSynth** [comment]
> Minor note: Air alarm in the freezer was going off right when I bought/first boarded the ship. It recovered pretty quickly so doesn't really matter. Might need fixgridatmos run for the prefill to be right?

It's more likely that the air alarm is linked to the freezer vent, which it doesn't really need to be. If it is, unlinking will mitigate that problem.

**Comment by dvir001** [comment]
This will need a remake if the issues still there since the ship got edited on another PR.

**Comment by dvir001** [comment]
The food PR, the fans and stuff were replaced in it so the yml got broken.

**Pull request closed without merging**
