### PR TITLE
Science Rebalance: The Point of Points

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

A proposal to rebalance science and incentivize researching technologies.

Anomaly cores (both inert and active) and artifacts receive value for the research points earned (0.4:1), with anomalies capping at a fixed value ($30k at time of writing).  This supplants technology disks as a source of income.  "PvE" income is to come from selling researched materials (anomaly cores and artifacts) for cash - the points themselves are yours, and can be spent on technology, which can be used to make fun things and/or sell to other players.

Recipes for the technology disk console and anomaly synchronizer circuitboards have been removed, and the anomaly synchronizer has been unmapped from the Anomalous Geode - science gameplay should be active and involve player input, and turning science into an idle game is not desirable; you should be keeping track of your anomalies.  Technology disks as-is do not make sense in a point-rich environment, and so their values have been nullified.  If there were rare, disk-only technologies that you could come across, this would make more sense.

TODO: need to incorporate Dvir's reversions to tech disks from #2418 where appropriate.

## Why / Balance

Science should primarily be about scientists actively doing things to learn how to make stuff, and then making said stuff.  The points are a means to make stuff, and having them sellable undermines that.

With this set of changes, artifacts seem to be the stronger of the two - anomalies generated need to be rotated out, and optimally, fairly regularly (~12 minutes at 100 pt/s).  If anomalies could work on a prestige-like system where you can extract a core once it's given you enough points, but doing this makes it more dangerous, that could be interesting, and give some choices to keeping anomalies beyond "babysit as many as you can before swapping them out".

## How to test

1. Purchase a science ship, spawn an alien artifact, research it partially.
2. Check the number of points you've received.
3. Appraise the artifact, it should be equal to 40% of that value.
4. Spray the artifact when on an unresearched node.
5. Appraise the artifact, it should maintain its value.
6. Spawn an anomaly trap, step into it.
7. Hook yourself up to an anomaly vessel.
8. Generate some points.
9. Stabilize yourself and decay the anomaly.  It should spawn an anomaly core.
10. Appraise the anomaly core, it should be equal to 40% of the number of points it generated.  This value should not change over time.
11. Generate a normal anomaly.  Do not hook it up to an anomaly vessel.
12. Decay the anomaly.  Its core should be worth 100 spesos.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

Preliminary:
:cl:
- tweak: Artifacts and anomaly cores are valued at 40% of the points generated.
- remove: The technology printer and anomaly synchronizer are no longer printable.

### CODE REVIEW

**Comment by blackknight954** [comment]
Hmmmm. How do the artifact values work right now? Having a bunch of half used artifacts always drove me crazy, but this is better than funny discs

**Comment by whatston3** [comment]
> Hmmmm. How do the artifact values work right now? Having a bunch of half used artifacts always drove me crazy, but this is better than funny discs

Current 17.5% vs. proposed 40% research point to speso conversion, a 25% bonus if you can traverse the entire tree, and spraying to active should add no value or points.

**Review by dvir001 — APPROVED** [review]
Tested, made small extra data line edit

Good to go.

**Comment by wolfchild1990** [comment]
Please, if anoms are supposed to generate money by selling cores, either allow infectious anoms to pop out cores. or Kill infectious anoms alltogether. I will be sad to see the anomaly engine go. But I guess I accept this., still if anoms cannot be automated, maybe reduce the markup on the Spectre a little?

**Comment by whatston3** [comment]
> Please, if anoms are supposed to generate money by selling cores, either allow infectious anoms to pop out cores.

They do now, this was added.

**Comment by wolfchild1990** [comment]
Actually some conversations I had in the discord. Artis can be put on pause. But anomalies without Synchs CANNOT. this will stifle Rp while you are doing science, unless you SCRAM all of your anoms every time you wanna chat

**Comment by whatston3** [comment]
> Actually some conversations I had in the discord. Artis can be put on pause. But anomalies without Synchs CANNOT. this will stifle Rp while you are doing science, unless you SCRAM all of your anoms every time you wanna chat

Miners also need to go out and mine to earn money.  You can put your funny orb away and have a small break.  Take a treat for doing good science. :)

**Comment by wolfchild1990** [comment]
"Miners also need to go out and mine to earn money" not quite the same equivilent For an anomaly researcher to "put their orb away". The currently need to kill the anomalies that they have rolling, the generation of which takes a 5 minute cooldown and resources, to roll on a random table and maybe get one you cant deal with anyway. I am actually just asking for something that could let us put the anom in 'stasis' so it stops genning points and cannot start growing. So that when a friend pops arround for a chat, we can put the orb DOWN instead of throwing it in the trash, that is all, I actually do get killing synchronisers.

I mean you got an anomaly rolling, just started. im not even talking about still making points. Give us like a stastis platform or something thap puts the anomalies in TIME OUT where they dont make points but also dont start growing. Say someone spends a few minutes trying to get a decent anom and setting it up. and now thier friend comes for a chat. Im just asking for the ability to actually put it down. rather than 'starting from scratch' this isnt r

**Comment by Houtblokje** [comment]
> > Actually some conversations I had in the discord. Artis can be put on pause. But anomalies without Synchs CANNOT. this will stifle Rp while you are doing science, unless you SCRAM all of your anoms every time you wanna chat
> 
> Miners also need to go out and mine to earn money. You can put your funny orb away and have a small break. Take a treat for doing good science. :)

That is most likely not going to happen, and what is instead going to happen is that scientists are going to become even more hyperfocused because they cannot pause the anomaly and won't even respond to chat. 
They will simply babysit their anomalies for money instead of chatting to others.

I might be assuming the worst here, but I think that the removal of the anomaly synchroniser might have the exact opposite effect as what you are trying to achieve. Not to mention that people might just simply give up anomaly science altogether.

**Comment by DesignerHere** [comment]
Removing tech printer ain't a problem. But removing anomaly engine would kill the anomaly research or at would make less time for RP.

**Comment by whatston3** [comment]
If the only draw to anomalous research is to put them into an infinitely stable state and sit and farm points, I'd like a more engaging alternative.  All ears.

Anomalous research likely needs love as-is.  I've said as much in the description.  That said, given the goal of "propose an alternative to cashing out research points as money", I maintain that this is a reasonable first step.

**Comment by Houtblokje** [comment]
> Anomalous research likely needs love as-is. I've said as much in the description. That said, given the goal of "propose an alternative to cashing out research points as money", I maintain that this is a reasonable first step.

Valid points. Though I think the cap for earning money could be a bit higher on anomalies, since they are significantly more dangerous than artifacts (with an artifact, the worst outcome is that an artifact spawns, which kinda proofs my point) so they should earn more money, but that can always be tweaked later I suppose. I think that the solution @wolfchild1990 proposed could actually be a good idea, giving a way to "freeze" anomalies, possibly reducing their value by a percentage every time you do it? and not gaining points while it is frozen, just to give scientists some breathing space in case roleplay comes along their path.

**Comment by DesignerHere** [comment]
Out of curiousity Whatston3, is it possible to make synchronizer needing resources to work? Like the higher anomaly gives research points, more resource it needs.

**Pull request merged**
