### PR TITLE
NFSD Resprite

### PR DESCRIPTION
**Pull request by Salvantrix**
## About the PR

NFSD Respirtes, revamped all aspect of NFSD and how they're lookin'.

Still a WIP, only thinG left to add is the on-spawn loadouts.

## Technical details

Mostly completed, just need to finish updating spawn-in loadouts.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
The blue looks too dark and too saturated.

**Comment by Kesiath** [comment]
I think the green would be a better option, as long as it's desaturated enough to not be mistaken with CentCom attire.

**Comment by Cheackraze** [comment]
I wanna bundle this in with the space law changes + server rules changes, etc, and these all look great to me so as soon as conflicts are finished we can merge this.

**Review by Cheackraze — APPROVED** [review]

**Comment by Cheackraze** [comment]
ok something funky is going on with git merge so im going to have to come back to this later this week, sorry about that

**Comment by Cheackraze** [comment]
ok I think I fixed it, just ignore the 8 or so commits i had to push hah

**Comment by ThatOneGoblin25** [comment]
Will this resprite also include airlocks, vendors and nfsd computers?
Or maybe not because then we'll have to redecal every ship...

**Pull request merged**
