### PR TITLE
Shielded cables : Add Shielded LV cables and Shielded APC that only powers objects on top of them

### PR DESCRIPTION
**Pull request by spacedwarf14**
## About the PR

(90% finished, so this is the bulk of the PR and I think ready for feedback. See TODO)

This PR introduces shielded LV cables and a shielded APC. Normal LV cables power objects up to 3 tiles away from the cable. shielded LV cables only power the objects on top of them. The Shielded APCs will not power any neighboring entities, either.

To make this work flexibly, I decided to introduce the Shielded LV cables as a separate network from the normal LV cables. This way, they don't connect to each other, and they can both be laid on the same tile. As a result, I made modification to the power monitor and some components (electrified, powerprovider) to accommodate using the new cable network.

Since LV and Shielded LV cables can be placed on the same tile, I added a rule to the provider selection mechanism to prioritize selecting the shielded cable if it is underneath, regardless of any other LV cables in the vicinity. This lets the player de-select objects from normal LV networks by placing the shielded lv cable underneath it. A separate circuit can then be made that only powers airlocks, for instance, without the airlock being affected by LV cables that are routed underneath them for other reasons. Turning off science should no longer affect your ability to move around!

This PR introduces the following specific changes:
  - Shielded LV cables as a separate network (they will not connect to normal LV cables)
  - Shielded APCs specialized for shielded lv cables. like the shielded cables, shielded APCs do not provide power at a distance
  - Power Monitor modifications to draw the Shielded LV network
  - art (WIP)
  - random spawn, supply and recipe prototypes
  - Component modifications to electrifiable and powerswitchable to support shielded cables
 
I tried to make the code changes as minimal as necessary. I also avoided, to my knowledge so far, changing the default rules for provider and receiver selection; I did append one rule that I mentioned above that should only affect networks where shielded LV cables are explicitly laid down.

In order to treat the Shielded LV networks as a separate power network, it had to be mapped as its own "voltage" which in-turn has a matching nodeGroupID. This enables setting up a shielded APC prototype to provide power to a shielded cable and prevents the shielded cables from connecting to any other network. These are mostly field / enum additions and adding cases to handle the new cables (identically to LV cables, basically).

The ExtensionCableSystem is modified slightly so that receivers prioritize shielded cables placed underneath, regardless of the presence of normal LV cables.

The power monitor allocates another line array for selecting and drawing the shielded APC network, sizes and enums adjusted accordingly.

Cases to handle Shielded APC have been added to ElectrocutionSystem, and PowerSwitchable systems.

I still need to tweak a few things, TODO:
- [ ] sprites need to be re-aligned, there are gaps after shifting their XY positions (so that they show on the tiles w/ normal LV cables) (probably just copy the pixels to the gaps)
- [ ] power monitor line alignment
- [ ] guidebook entry
- [ ] Shielded APC sprite (magenta stripes?)
- [ ] stretch goal: Maybe some way to make it clear which networks power receivers are connected to
- [ ] maybe change materials used for insulated wire
- [ ] maybe make a recipe to turn insulated cable into normal cable and back

## Why / Balance

There's are at least two distinct ways to look at an APC:
  - The APCs are /spatially oriented/: they will turn off everything in the vicinity, defaulting to 3 tiles away
  - The APC are /functionally oriented/: they will turn off everything related to a function

Extended range for power systems made sense in vanilla SS14, where gameplay takes place in large space. Corridors >= 3 tiles wide, big rooms that corresponded to their functions (science, engineering, bar, etc). This means that it was easy to have the function of the power systems that the APC affect map to the space in-which they occupied. That is, because rooms were separated enough from each-other, it wasn't really much of a thought about whether APCs were functionally oriented or spatially oriented -- the space was the function, allowed for the functions to coexist with the ranges that are expected by power receivers and providers.

FS14 typically takes place in smaller spaces, which means it is more difficult to make the APCs functional. There are tradeoffs between the ship layout and the functions an APC affects. In an example situation, that means that if you want to turn off science, you end up turning off airlocks and occasionally some thrusters. Almost every ship I've played on has an issue like this -- and if you /try/ to make the APCs functional, you end up with ridiculous wiring schemes and room extensions just to prevent entities from connecting to things 2 tiles away. I've spend many hours on a ship to try to make this possible.

FS14 also introduces fuel requirements on tighter supply cycles, so there's more of an incentive to shut down an unused part of the ship in order to reduce fuel consumption.

There was some brief discussion on discord about whether cable selectivity was a problem, but no discussion about whether this is an entity worth introducing. This shouldn't affect the gameplay if a player wants to stick to the default behavior. I started doing this to learn how my favorite game works, and to recover from some programming burnout. If this PR is merged, I will make a map that takes advantage of shielded cables.

## How to test

Spawn a map; manufacture some shielded cable, place a shielded APC construction ghost, build; connect shielded cable to it, make network, place power consumer (power monitor).

When there are neighboring LV providers, a power receiver entity anchored on top of an existing Shielded LV cable will always select it as the provider. If a cable is placed under a receiver which already has a provider, the receiver will remain connected to that provider until it is re-anchored on top of the shielded LV cable. This is actually default behavior that you can observe with LV cables as well.

## Media

Shielded LV Cable on tile (I will fix the gap soon)
2024-09-16-193801_302x320_scrot

etc:
2024-09-16-194034_836x388_scrot
2024-09-16-194114_374x229_scrot
2024-09-16-194000_1368x1209_scrot

description (TODO change color of "Shielded LV Cable")`
2024-09-16-193822_406x252_scrot

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

The changes are mostly additive, to support the shielded lv network, and should not change how existing cases are handled. The most significant change I would say is the addition to the TryFindAvailableProvider, which is optional but makes the shielded cables more useful.

**Changelog**

:cl:
- add: Added Shielded LV Cables and Shielded APC. Unlike normal LV cables and APCs, Shielded power network components only power object on top of them and cannot power objects on neighboring tiles. If an LV and a Shielded LV cable is placed before an object is anchored on top of it, the Shielded LV cable will always be used as the power provider. Now you can build an Airlock APC! They are also less likely to routinely cause cancer. Note: You can't connect a normal LV cable to a shielded APC and vice versa.

### CODE REVIEW

**Comment by Cheackraze** [comment]
Not really a fan of making changes like this to power systems, especially since I feel power is already needlessly over-complicated. On an ideal world, we would drop lv cables altogether and just have apc's have a larger power broadcast. The 3 existing cable types and power conversion is already too complicated of a system for our use case on frontier.

The real solution to your specific use case you outlined would be to implement power switch verbs onto machines that don't have them to turn them off individually

**Comment by spacedwarf14** [comment]
@Cheackraze yeah that makes a lot of sense. Would a PR with those changes be considered?

**Comment by dvir001** [comment]
Before my opinion this PR has issue with yml that 100% could have been under _NF folders, and missing comments to mention ``# Frontier`` / ``// Frontier`` on them

Not a fan of this change tbh, this feels like it over complicated a system, why not just add a toggle on APC that turn the APC into this range mod?

**Comment by spacedwarf14** [comment]
> Not a fan of this change tbh, this feels like it over complicated a system, why not just add a toggle on APC that turn the APC into this range mod?

I actually started with this. It decided against the dynamic behavior since was not immediately intuitive which provider an entity would attach to once it is anchored. Receivers cannot have more than one provider so it would attach to neighboring networks if the APC's range is turned off. This means there's both the anchor state and the APC's range/nearfield state to keep track of when determining which network the entity attaches to.

**Comment by spacedwarf14** [comment]
Please see https://github.com/new-frontiers-14/frontier-station-14/pull/2027!

**Pull request closed without merging**
