### PR TITLE
Restore Tech disks to upstream numbers.

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Restore the tech disks to upstream numbers.

## Why / Balance
Part of a bigger sci rework, this has to be changed back since it made people focus on just standing in place printing none stop disks then selling techs to people

The end goal is to buff overall worth from tech and research itself then mass entity spam of 3000 disks.

## How to test
Spawn a printer, print.

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: NT Tech disk economy broke, disks now worth less.

### CODE REVIEW

**Comment by Cheackraze** [comment]
we changed it higher for a reason, because this doesnt stop people from printing disks

People instead will make 100 disk printers all printing 1000 disks for the same effect. The science rework needs to come first, and then we can turn this back down

**Comment by Erol509** [comment]
All this changes about disks is the fact that you now how to print 100k disks since you can mek easily milion points per hour. Go afk with autoclicker and I dont believe its better than it was before.

**Comment by dvir001** [comment]
> All this changes about disks is the fact that you now how to print 100k disks since you can make easily milion points per hour. Go afk with autoclicker and I dont believe its better than it was before.

Fair, Ill see about adding requirements to add plastics or other stuff for crafting.
In general we going to try and move away from the points having the worth and the research itself paying more.

**Comment by Cheackraze** [comment]
> Fair, Ill see about adding requirements to add plastics or other stuff for crafting. In general we going to try and move away from the points having the worth and the research itself paying more.

What do you mean by research itself paying more? You mean on the artifacts themselves because that can be an easy change. Blueprints sales or something of higher value would be ok too.

**Comment by dvir001** [comment]
> artifacts themselves

Stuff like:
Artifacts themselves, waiting for whatstone to possibly help me balance it as there might need to be more then just adding higher multi worth
Anom cores and how they are worth selling (No lost of worth over time and some balance to price based on lifetime of anom)
Possibly R&D Server worth based on unlocked techs to encourage unlocking more techs, possible system to reward based on techs unlocked?

Still working on ideas but in general just thinking how we can make it more engaging.

**Comment by dvir001** [comment]
Going to remake this

**Pull request closed without merging**
