### PR TITLE
Latejoin ui tweaks

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
- Adds job count indicators to each shuttle/station entry in the list (taken from #814, by @GreaseMonk)
- Fixes shuttle/station sorting and filtering
- Moves the files from Content.Client/NewFrontier to Content.Client/_NF for consistency

## Why / Balance
Screaming

## Technical details
Client-side changes only.

The whole sorting/filtering fix was a matter of replacing the old code that was basically "remove only outdated items and add only new ones" with "remove all items and re-add them"

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl: Mnemotechnician and GreaseMonk
- add: Added job counters to the late-join menu.
- fix: The late-join menu now correctly sorts and filters shuttles.

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by dvir001** [comment]
Can you add a single space before the (X)?

**Comment by Mnemotechnician** [comment]
> Can you add a single space before the (X)?

I did. The screenshot be a bit outdated.

**Comment by Cheackraze** [comment]
Iirc, I was having difficulties with the xaml compiler not liking its home folder not having exact directory listing ad it'd namespace is why it's not in _nf.  Also one of the very first custom UIs I had to implement during early development

**Comment by Mnemotechnician** [comment]
Yea, the generator for xaml bindings uses the exact directory path as the namespace, so you gotta include _NF in the namespace

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
