### PR TITLE
Despawn Timers For Mobs

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Adds despawn times for commonly encountered mobs.
- Syndicate agents, Blood Cultists and Argocytes: 50 minutes (max blue space event duration involving those mobs - 40 mins).
- Wizard Federation mages and Arcadia Industries machines: 30 minutes (max blue space event duration involving those mobs - 20 mins).
- Space fauna (bears, carps, spiders, ticks etc.): 3 hours (I believe asteroids and wrecks despawn after 3 hours after appearing hence the value).

## Why / Balance / Discussion
This change might alleviate some issues that stem from limit on active AI numbers, but I don't think that it is a good solution in the long run (and I'm not sure how effective it'll be).

## How to test
Wait and see

## Media
- [x] This PR does not require an ingame showcase.

## Breaking changes
Edits to base game files

**Changelog**
:cl: erhardsteinhauer (discord)
- tweak: Added despawn times for commonly encountered mobs.

### CODE REVIEW

**Comment by Kesiath** [comment]
A better general fix would be proper tying of a spawned salvage/hostile mob to their grid, so that when the grid is deleted so is the mob. This was done through the SalvageMobRestrictionsSystem previously afaik, and would just delete the mob on grid despawn. Hopefully this will do some good in the meantime however, and would still be a decent catch-all.

**Comment by dvir001** [comment]
Going to hold up on this one

**Comment by ErhardSteinhauer** [comment]
> A better general fix would be proper tying of a spawned salvage/hostile mob to their grid, so that when the grid is deleted so is the mob. This was done through the SalvageMobRestrictionsSystem previously afaik, and would just delete the mob on grid despawn. Hopefully this will do some good in the meantime however, and would still be a decent catch-all.

How does that component work? It despawns only mobs that happen to be on the despawning rock/wreck?

**Comment by ErhardSteinhauer** [comment]
> Im going to try to code fix

Famous last words. (Sounds good though).

**Comment by Kesiath** [comment]
> > A better general fix would be proper tying of a spawned salvage/hostile mob to their grid, so that when the grid is deleted so is the mob. This was done through the SalvageMobRestrictionsSystem previously afaik, and would just delete the mob on grid despawn. Hopefully this will do some good in the meantime however, and would still be a decent catch-all.
> 
> How does that component work? It despawns only mobs that happen to be on the despawning rock/wreck? Or does it catch mobs that drifted away from that rock/wreck too?

Actually to clarify, it looks like that system doesn't delete the mobs but instead kills them and gibs them, but that'd generally accomplish the same goal for removing them from the AI list.
image

**Comment by ErhardSteinhauer** [comment]
Huh. Gibbing doesn't seem to be a good move tbh.

And god damn, the edge of known space used to be terrifying - filled with floating organs and body parts for inexplicable reason. Lovecraftian levels of horror.

**Pull request closed without merging**
