### PR TITLE
PTK Rework

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Largely supercedes #2436, created from suggestions mentioned in comments there.

Gives the PTK a niche purpose: destroying hard rocks.  Walls on asteroids are no longer obstacles to avoid PTK use, but sources of denser ore deposits.  These "supercompacted rock" walls require specialized equipment to destroy (PTK bolts, diamond drills, and/or holopickaxes).  The reflection from walls has been removed.

PTKs in particular now overpenetrate softer rocks, destroying any ore gathered from them.  This requires you to either:
A. be careful with PTK shots, using it to surgically remove higher value ore (that you know about through dwarven intuition or mining analyzers).
B. clear the asteroid in multiple passes, destroying the softer rocks before using the PTK to remove the harder targets
C. use a diamond drill or holopickaxe (generally requiring salvagers to purchase or otherwise source these) and clear the asteroid in one pass

## Why / Balance

Flying around an asteroid with zero threat, blasting rocks away is not good design, and the reflect chance was a bad bandage fix.

## How to test

1. Use the PTK to mine on an asteroid.  Softer rocks should be destroyed leaving nothing, harder rocks (walls) will be destroyed leaving their ore.
2. Use a holopickaxe and diamond drill to mine an asteroid.  All rock types should be destroyed and leave their ores.
3. Use a glaive, pickaxe, any other mining tool you can think of to mine.  Soft rock types should be destroyed, and harder rock types should be unaffected.

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Walls on asteroids can now contain ore denser than regular rocks and require diamond drills, a holopickaxe, or a PTK to mine.
- tweak: PTK bolts destroy ore in softer rock, but "walls" no longer reflect shots.

### CODE REVIEW

**Comment by whatston3** [comment]
Going to move this to draft - branch is feature complete, but the loot tables might benefit from a rebalance, and ideally there's a way to specify the way asteroids spawn without needing so much configuration.

**Comment by arimah** [comment]
Conceptually, I really like the idea of requiring more powerful equipment to do the job that a person cannot reasonably with a (normal) pickaxe or crusher, _and_ it gives us a way to clear those pesky wall things, with a nice little reward for doing so.

**Comment by GreaseMonk** [comment]
Pros:
- PTK mines hard rocks

Cons:
- PTK no longer mines soft rocks, losing its primary use.
- Diamond drill does the same without setup and travel time to collect
- PTK requires time to setup and time to go to ship to shoot and back to asteroid to collect
- Can probably still be used to shoot any POI to smithereens for looting which happens.

I hope this is constructive enough, my vote is to remove PTK altogether, because there is no point in keeping it.

**Comment by Eponymic-sys** [comment]
Generally I like this, I'm not sure it's enough to actually make the PTK good, but it gives it a niche and adds a trade off between visiting a science ship for a drill or just doing it yourself. 

I do with there were an easier way to split the difference, PTK gives lower ore on softer, but looking at your changes that'd be a lot of work.

This is a good change even if the PTK gets removed.

**Comment by DmitriTheDemon** [comment]
>     * Can probably still be used to shoot any POI to smithereens for looting which happens.

As I understand it this change won't revert that issue which was addressed by lowering the PTK damage.

**Review by dvir001 — APPROVED** [review]
Pew Pew Pew

**Comment by whatston3** [comment]
image

Thanks in part to Dvir's hard work, we now have rare clusters of high value material spawning on asteroids.

image

The cave's diamonds have also been swapped over to these.

**Pull request merged**
