### PR TITLE
Mercenary QOL

### PR DESCRIPTION
**Pull request by dvir001**
## Why / Balance
Mercenary got full gear now.
Mercenary rank, to use for lockers and airlocks.
Mercenary rank added to all security members
All items with ``Merc`` in entity name updated to ``Mercenary``
Every single O2+N2 tanks been replaced with a single Air tank in all lockers to save on entity spam.
Mercenary vest nerfed to match security vests
Mercenary jumpsuit got a tracker added
Added VendPrice to Pinpointer, Disabler & HandHeldMassScanner to allow ship selling to not go up (Price stay same on vending machines)
Added Mercenary locker
Added all mercenary cloth to the ``VendingMachineBountyVend`` vendor
Added bounty hunter cloth to the ``VendingMachineBountyVend`` vendor
Removed detective gear from the ``RepDrobe`` vendor (Reporter Vend)

## Technical details
.yml

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame,

## Breaking changes
N/A

**Changelog**
:cl: dvir01, ErhardSteinhauer
- tweak: The mercenary job has received improvement, new gear, new locker, and new access.

### CODE REVIEW

**Comment by RealIHaveANameOfficial** [comment]
I feel like switching out o2/n2 to airtanks should probably be a separate PR, but it's a good change anyway

**Comment by dvir001** [comment]
> I feel like switching out o2/n2 to airtanks should probably be a separate PR, but it's a good change anyway

Keep in mind with how things are im already forced to "fix" merge conflicts issues that are 2 lines every single time im doing big changes that collide, this is just to allow me to not need to do this yet again. X_X

**Comment by Cheackraze** [comment]
@dvir001 were you waiting for textures to finish this one?

**Comment by dvir001** [comment]
> @dvir001 were you waiting for textures to finish this one?

Working on it now.

**Comment by dvir001** [comment]
> @dvir001 were you waiting for textures to finish this one?

Done

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
