### PR TITLE
Remove Goblinbane

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Removes Goblinbane from codebase.

## Why / Balance
Halloween is over, the mob wasn't meant to stick around, not exactly fitting for Frontier thematically.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: erhardsteinhauer
- remove: Goblinbane was banished.

### CODE REVIEW

**Comment by dvir001** [comment]
Forks might want it for the memes, can we hide it from spawn and nuke the spawner?

**Comment by ErhardSteinhauer** [comment]
> Forks might want it for the memes

They can restore it if they wish to: original PR is still in the internets.

**Comment by arimah** [comment]
I say let downstreams maintain it if the want to. No need for us to impose that burden on ourselves just because someone else _might_ want it.

**Comment by ErhardSteinhauer** [comment]
Also, sprites for this thing are very rough, and I have no desire to improve upon them. As a one-off event this is almost fine, but as a permanent addition - very dubious.

**Review by dvir001 — APPROVED** [review]
So be it.

**Review by whatston3 — APPROVED** [review]
Looks fine, works fine.

Good night, sweet prince.

**Pull request merged**
