### PR TITLE
Move tank harness to outer clothing

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Moves tank harness to outer clothing rather than being hidden in their own category.

## Why / Balance

#2022.

## How to test

1. Create a new vox character.
2. Swap between jobs in character setup.
3. Your outfit should include your weird tank harness.

## Media

Default pirate captain outfit.  Fearsome.
image

Default valet outfit.  Nice arm holes.
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: The tank harness for Vox is now in the outer clothing option.  Double check your loadouts.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
Tried spawning with different outer clothing articles (including ones compatible with voxes), the harness still spawns instead of selected item.

**Comment by whatston3** [comment]
> Tried spawning with different outer clothing articles (including ones compatible with voxes), the harness still spawns instead of selected item.

Any particular role/loadout?  Retested as contractor bringing a voidmedic suit, no issue, same with the valet and the valet vest.

**Comment by ErhardSteinhauer** [comment]
Tried merc with lab coat, the branch is correct, but might not be the latest (grabbed it yesterday, when we were in VC)

**Comment by whatston3** [comment]
> Tried merc with lab coat, the branch is correct, but might not be the latest (grabbed it yesterday, when we were in VC)

Should be resolved.  I missed one GroupTankHarness reference.  Sorry about that.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
