### PR TITLE
Vend change

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
The action to eject machine items is disabled,
Multitool, EMP, Player controlled or damage to vend machines will not drop any items.
Machines worth is now static of 1000 and will ignore any content in it.

### CODE REVIEW

**Comment by BugsStrider** [comment]
first of all, PR 69, nice

second of all, selling sectechs for 17k is one of the best pieces of exped loot, pls reconsider!

**Comment by sTiKyt** [comment]
But why? It makes sense for machine to drop some items when you break it

**Comment by dvir001** [comment]
> But why? It makes sense for machine to drop some items when you break it

Not when some items cost 75k
This is a temp fix to a bigger issue, we can go back and read this function to some machines later.

**Comment by sTiKyt** [comment]
> > But why? It makes sense for machine to drop some items when you break it
> 
> Not when some items cost 75k This is a temp fix to a bigger issue, we can go back and re do this function to some machines later.

Let's just fix that specific item?

**Comment by dvir001** [comment]
> > > But why? It makes sense for machine to drop some items when you break it
> > 
> > 
> > Not when some items cost 75k This is a temp fix to a bigger issue, we can go back and re do this function to some machines later.
> 
> Let's just fix that specific item? I'm working on some price rebalancing rn as well, we could team up a bit and figure it out

Its every single machine, and it need bigger changes, you can start making the changes and PR it later.

**Comment by sTiKyt** [comment]
> > > > But why? It makes sense for machine to drop some items when you break it
> > > 
> > > 
> > > Not when some items cost 75k This is a temp fix to a bigger issue, we can go back and re do this function to some machines later.
> > 
> > Let's just fix that specific item? I'm working on some price rebalancing rn as well, we could team up a bit and figure it out
> 
> Its every single machine, and it need bigger changes, you can start making the changes and PR it later.
> This PR only un-comment few lines related to abuse that is going around as we speak, and it can be reverted ones all machines had changes to allow stopping of free items.

Makes total sense to me, understood

**Review by Cheackraze — APPROVED** [review]
this is ok for now but not ideal. In the end, if you could remove the eject on wire pulse and player controlled eject but leave in the eject on damage. last I tested, you can only get 2-3 items to eject until the vending machine is 'broken' and so I think that's still kind of funny behavior that's ok

**Pull request merged**
