### PR TITLE
Brand New Announcer for New Frontier!

### PR DESCRIPTION
**Pull request by Wolfking6116**
## About the PR

This PR adds an entirely new announcer to Frontier with re-recorded lines of all the stock announcement audio files, several new recordings for many more vanilla Station Events, and recorded announcements for every currently existing event crafted specifically for New Frontier.

This also comes with renaming "Shuttle called" to "Shift's End" in the game announcements, with accompanying audio recordings to match such a change.

## Why / Balance

Several people have been brought this up a couple times over the past few months as something that would be nice for the server. Given the popularity of Frontier and all of its wonderful growth and development it definitely feels like it deserves its own announcements!

## Technical details

~~I have not yet tested this in full, this PR in its current state exists for feedback that it is looking okay and to be certain that this is in fact a desired change before too much more effort is put into it only to be shot down.~~

I've gone through and tested all of the events that these sound files are part of to the best of my abilities. The only issues I have encountered so far is that the 'Gas Leak' event seems to end abruptly after starting when tested on my local machine, so the endAudio overlaps the startAudio. I don't have the knowledge of a work around so I commented it out.

For all of the 'Bluespace' events that are specific to Frontier there appears to be something baked into the "BluespaceErrorRule" that causes a global alert that plays the announcement "do-**do**-do!" noise. This overlaps with the 'startAudio' for each of them that may make some of them a bit harder to hear.

Some sound files are quieter than the others. I'll be posting a thread in the Ideas section of the discord for feedback to see which ones need to have their volume increased. I attempted to do so via .yml with params: volume: 4 as a reverse to the one seen on line 232 of the basegame events.yml - but doing so did not seem to have any noticeable effect.

I can't seem to get the original shuttle_dock.ogg to trigger, thus I cannot get the file replacing it - andy1_shift_end.ogg - to trigger to test that it is working correctly. The path for it replaces the original shuttle_dock.ogg so it should still trigger under normal server conditions even if I cannot do so locally.

## Media

I'm not certain how easy it is to listen to the audio files via looking at them in this PR. If desired I'll see about getting together a video of all the clips together for ease of access.

To solve an easy method of listening to all the audio files I've set up a post in the discord.
https://discord.com/channels/1123826877245694004/1221648600082157648
If a different method is preferred, let me know!

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

This does touch a fair bit of base game files, but I am not certain there is any way to get around that easily.

**Changelog**

:cl:
- add: A new Radio Personality has moved out to the Frontier to grace our ears and warm our hearts.

### CODE REVIEW

**Comment by Wolfking6116** [comment]
@dvir001 Why is linter unhappy after your merge? o.o

**Comment by dvir001** [comment]
Keep in mind we moved events around and this PR will need to pull master and then update locations

**Comment by Cheackraze** [comment]
I know the creator had some updated clips but I dont know if they ever decided on ones for the final versions. Be sure to ping us when this is ready and if need be, we can assist in getting the conflicts/file locations set properly

**Comment by Wolfking6116** [comment]
Attempted to update repo to get everything set up for the sound files to be added, neglected to squash when fetching. Makes this look terrifying. Will open a new pull request shortly.

**Comment by Wolfking6116** [comment]
Re-opening in a new ticket

**Pull request closed without merging**
