### PR TITLE
Experimental NFSD suit, NFSD Doors, and wall/suit storage containers.

### PR DESCRIPTION
**Pull request by Salvantrix**
## About the PR

Adds Experimental NFSD hardsuit, Wall and Suit storage containers, and fixes a small error in description.

## Why / Balance

Added stuff.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by VividPups** [comment]
You have an Error with someone about the Meta.json file

**Comment by dvir001** [comment]
@Salvantrix Just fix the jobs ```icon:``` please

**Comment by dvir001** [comment]
Ill fix the rest of the issues later reee

**Comment by MagnusCrowe** [comment]
Fixed the issue with the lobby screen and icons.

**Pull request closed without merging**
