### PR TITLE
Removed whitelists from belts

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Commented out whitelists on every single belt.
- Belts now have uniform storage capacity.
- Renamed 'wand belt' -> 'wizard belt'.
- Swapped grappling gun with screwdriver in pilot webbing.

## Why / Balance
With webbings so widely available, belts become completely irrelevant, this PR fixes it.

## How to test
Grab a belt, use it like you'd use a webbing

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Belts now function like webbings.

### CODE REVIEW

**Review by whatston3 — COMMENTED** [review]
Looks alright at first glance, will give a closer look later.

**Comment by Cheackraze** [comment]
tend to agree, people just metagame the web vests so they can stuff more things in them any how.

We should just enforce sizes for them across the board as well, if they arent. Make em just cosmetic at this point basically.

**Review by whatston3 — APPROVED** [review]
Works fine.  Not entirely sure about the holster, considering that you're removing the capability to store 4x4 weapons in them, though that's also a bit odd.  Quiver still exists as a separate case, but seems reasonable to me.

Seems alright.

**Comment by ErhardSteinhauer** [comment]
> Not entirely sure about the holster

Me neither, however if I keep original storage capacity for it, no one will use it.

**Pull request merged**
