### PR TITLE
Market Sale Update

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Updated the market sale

VeryHigh: 1.75 (Can be used on cargo event as EG, not mapped right now)
High: 1.5 (Trade Depo) (Was 1.59~)
Normal: 1.0 (Not used)
Low: 0.75 (POI) (was 0.6~)
VeryLow: 0.5 (Antag) (Was 0.4~)

## Why / Balance
Round numbering it a bit to make it more easy to work with.
A bit of a balance to the sell price.

## How to test
Spawn sale computer and a sell pad, sell stuff.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

## Breaking changes
Selling price on depos down a tiny bit overall, all other sells computer are a bit up.

**Changelog**
N/A

### CODE REVIEW

**Comment by arimah** [comment]
I feel like this could absolutely do with a player-facing changelog, so people don't start reporting bugs that things are selling for peanuts at cargo depots. 1.25 is down around 21% from the previous value.

**Comment by arimah** [comment]
Wait a minute – the PR description doesn't match the code! Is High meant to be 1.25 or 1.50?

**Comment by dvir001** [comment]
> Wait a minute – the PR description doesn't match the code! Is High meant to be 1.25 or 1.50?

Hold up

**Comment by dvir001** [comment]
Moved it to draft as we need to fix the verb

**Review by whatston3 — APPROVED** [review]
Seems alright.  If you wanted to be nice to freighters, consider reducing the cargo price for trade crates to 900/1800.

~~With 1.5x payout at cargo, you'll get a margin of 1200 (roughly consistent from before): 2000 (market rate) * 1.5 (computer payout rate) - 1800 (cargo purchase cost).~~ Disregard this.

**Pull request merged**
