### PR TITLE
Eagle (Update) - Flatpacker built in and RCD removed

### PR DESCRIPTION
**Pull request by MagnusCrowe**
## About the PR

The flatpacker is now FUSED with the ship and should not be removable.

Removed RCD.

## Why / Balance

So people won't buy the ship for the gamer loot.

### CODE REVIEW

**Comment by ThatOneGoblin25** [comment]
Damn.

**Comment by MagnusCrowe** [comment]
I'm not sure this PR is necessary now that I know flatpacker boards are coming to the circuit vend

**Comment by ThatOneGoblin25** [comment]
I *half-heartedly* agree that the RCD has to go, it would make sense on a more expensive ship, I just misunderstood how rare the RCD is meant to be since they spawn in engi lockers upstream. If people are really paying 57k just for the RCD then it makes sense to remove it, no?

**Comment by MagnusCrowe** [comment]
Before anyone merges this I need to undo the flatpacker being fused to the ship.  It's not necessary with the circuitboard being put in the vendor.

**Pull request closed without merging**
