### PR TITLE
NFSD Badges, Loadout Decency

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Two disparate minor features.

Adds titles to the NFSD badges.

Hides topless boxer shorts and the gladiator jumpsuit for female characters.

## Why / Balance

NFSD: quality of life, PTech now explicitly shows which badges are which.

Loadouts: decency.

## How to test

1. Open the Character Setup screen
2. Create a female character.
3. Open the Contractor loadout setup, open the jumpsuit tab.
4. Scroll down.  You should not see an entry for boxer shorts or the gladiator jumpsuit.
5. Create a male character.
3. Open the Contractor loadout setup, open the jumpsuit tab.
4. Scroll down.  Select the boxer shorts.
5. Change your sex to Female.
6. Egads.  Save your loadout.  Grey jumpsuit.
7. Start the round.
8. Warp to the NFSD Outpost.  Check the PTech, all of the badges should be properly labelled.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** ***this PR does not require an ingame showcase***

## Breaking changes

**Changelog**

Minor fix, no changelog.

### CODE REVIEW

**Comment by K4rlox** [comment]
why cant females get a gladiator outfit?

**Comment by whatston3** [comment]
> why cant females get a gladiator outfit?

image

**Comment by K4rlox** [comment]
> > why cant females get a gladiator outfit?
> 
> image

some people like having a ashwalker gladiator costume as a female lizard

**Review by dvir001 — APPROVED** [review]
Works

**Comment by dvir001** [comment]
> some people like having a ashwalker gladiator costume as a female lizard

You can still find it in vending.

**Pull request merged**
