### PR TITLE
New cooked meatball sprite + make meatballs cookable

### PR DESCRIPTION
**Pull request by arimah**
## About the PR
* New cooked meatball sprite, taken from Goonstation. Actually looks like a cooked meatball!
* Added a construction graph for cooking meatballs, by heating them to 354 K (80.85 °C). Yum!

## Why / Balance
The cooked meatball sprite from upstream doesn't really look like a cooked meatball. It has no real texture and the colours are a bit off. This new sprite, courtesy of Goonstation, actually resembles a meatball!

Additionally, there was no way to actually _make_ a cooked meatball. This PR adds a construction graph that lets you cook raw meatballs by heating, same way you cook steak.

## How to test
1. Spawn or make a raw meatball.
2. Put the raw meatball in a microwave for 10 seconds or so, or put it on an electric grill.
3. Marvel at the beautiful, mouthwatering sprite.
4. Eat and enjoy. *(Skip this step if you are vegetarian or vegan.)*

### Known problems
The sizzle sound doesn't play when you cook the raw meatball. Inherited from upstream; steaks all have the same bug.

## Media
https://github.com/user-attachments/assets/07757281-fc6f-4a5a-a028-629d12d106e6

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Negatory.

**Changelog**
:cl:
- add: Raw meatballs can now be cooked on a grill or in a microwave. Yum!

### CODE REVIEW

**Comment by Cerebral-Error** [comment]
I am 100% in support of this addition. In fact I would go so far as to say it is vital to the playability of Frontier.

**Review by whatston3 — APPROVED** [review]
Looks fine, didn't test, would honestly prefer an "# End Frontier" or per-line comment for the construction graph addition in meat.yml:1482.

**Comment by arimah** [comment]
> Looks fine, didn't test, would honestly prefer an "# End Frontier" or per-line comment for the construction graph addition in meat.yml:1482.

No problem. I added `#End Frontier` comments. :D

**Review by whatston3 — APPROVED** [review]
Tested, works well.

**Pull request merged**
