### PR TITLE
STC Hat and free laceup shoes

### PR DESCRIPTION
**Pull request by MagnusCrowe**
## About the PR

Adds a new hat for STC. I removed the red coloring from the syndicate master at arms hat and changed the brim from white to green. If someone wants to redo the sprite, be my guest, replace it after this PR is merged.
They can receive it only from loadout, but it's free for them.
I've also made laceup shoes free for STC.
## Why / Balance

I thought STC deserved their own hat.  
## How to test

Give yourself laceup shoes and a hat in loadouts.

## Media

image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a new hat for STC!
- tweak: STC now gets free laceup shoes!

### CODE REVIEW

**Review by whatston3 — CHANGES_REQUESTED** [review]
Clothing looks reasonable.  I'd add a hamster sprite version and add the wearable tag for it (happy to do it if you don't want to).  Do keep the loadout groups in the same order - I believe it populates the loadout screen options based on the order in that list.

I'll look into a fix for that loadoutGroup (for a separate PR), because the SR and STC's loadout groups shouldn't need to recite the whole list and add three or four things.

**Comment by whatston3** [comment]
image
Reasonable?

**Comment by whatston3** [comment]
My suggestions are up here: https://github.com/new-frontiers-14/frontier-station-14/commit/da4421cff3722530178773a5e82a5430abf55d21

If you'd like to test, you can checkout and run [whatston3:2024-07-23-stc-hat-suggestions](https://github.com/whatston3/frontier-station-14/tree/2024-07-23-stc-hat-suggestions)

I'd approve the branch with this set of changes.

**Comment by MagnusCrowe** [comment]
Excellent, thank you.

**Review by whatston3 — APPROVED** [review]
Approved.  Will address STC/SR list redundancy shortly.

**Pull request merged**
