### PR TITLE
Ship category audit

### LINKED ISSUE #1962: Multiple shuttles are of incorrect size groups
## Description
The following vessels currently (potentially) belong to the incorrect size groups:
- Shipyard Console
  - LVHI Legman: 63 (8*8) (should be Micro, currently Small)
  - LVHI Pioneer: 43 (5*9) (should be Micro, currently Small)
  - SBB Hammer: 205 (17*14) (should be Small, currently Medium)
  - NM Caduceus: 737 (37*40) (should be Medium, currently Large)
  - NR Spectre: 752 (35*43) (should be Medium, currently Large)
- Black Market Shipyard Console
  - Falcon: 245 (15*22) (should be Small, currently Medium)
  - Schooner: 255 (13*29) (should be Small, currently Medium)
- Expedition Shipyard Console
  - KC Anchor: 1011 (43*43) (should be Medium, currently Large)
  - SLI Gourd: 1011 (33*45) (should be Medium, currently Large)

**Reproduction**
`gridtc`

**Screenshots**
N/A

**Additional context**
These are based upon __solely the tile counts__ of the [Ship Submission Guidelines](https://frontierstation14.com/index.php/Ship_Submission_Guidelines), wherein:
> <html><body>

Size Category | Maximum Tiles | Target Profile Limits
-- | -- | --
Micro | 64 | 8 tiles long and 8 tiles wide
Small | 256 | 16 tiles long and 16 tiles wide
Medium | 1024 | 32 tiles long and 32 tiles wide
Large | 2304 | 48 tiles long and 48 tiles wide

</body>
</html>

Including size limitations, at least one vessel still qualifies (Legman), and I feel like tile limitations are a more reasonable standard in any case. The Pioneer shares the same dimensions as several other Micro vessels (5\*9/9\*5) and is even 2 tiles smaller than most of them (as multiple share a 45-tile design); so either Pioneer is supposed to be Micro, or every single "Micro" but the Legman, Construct, and Canister belong to Small.

Even if the initial list is wrong, there's definitely inconsistencies to be resolved, and if nothing else, I want to at least highlight that they do exist.

### PR DESCRIPTION
**Pull request by DmitriTheDemon**
## About the PR
Updated categories based on ship submission guidelines to be consistent. resolve #1962 

## Why / Balance
Categories for some ships were inconsistent with standards applied to other ships

Spreadsheet of current ship sizes and dimensions [here](https://docs.google.com/spreadsheets/d/1D4cii7fmX3AbP5dqDYnDnJTyUyPqvaF3/edit?usp=sharing&ouid=103554193349621686381&rtpof=true&sd=true)

## How to test
Go to each shipyard terminal
Verify ships show up in correct category
Buy and sell ships to ensure they do not break on load

## Media
Ship Category - Exped Medium
Ship Category - Frontier Medium
Ship Category - Frontier Micro
Ship Category - Frontier Small
Ship Category - Scrap Medium

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: Updated category (size) for pathfinder, hammer, legman, pioneer, and orange

### CODE REVIEW

**Comment by dvir001** [comment]
Based

**Review by dvir001 — APPROVED** [review]

**Comment by Tych0theSynth** [comment]
May end up changing again in the future if the submission guidelines are updated

**Review by arimah — CHANGES_REQUESTED** [review]
Please see my comment on the issue you're attempting to fix: https://github.com/new-frontiers-14/frontier-station-14/issues/1962#issuecomment-2336707821

Tile count is _not_ the only determiner. With this change, given the current rules, several ships actually get an incorrect size classification. Please update your PR according to the rules and we can get this merged. :)

**Comment by DmitriTheDemon** [comment]
> Please see my comment on the issue you're attempting to fix: [#1962 (comment)](https://github.com/new-frontiers-14/frontier-station-14/issues/1962#issuecomment-2336707821)
> 
> Tile count is _not_ the only determiner. With this change, given the current rules, several ships actually get an incorrect size classification. Please update your PR according to the rules and we can get this merged. :)

In the spreadsheet I linked I manually gathered the dimensions (height and width) of the ships and compared that to the guidelines as well as evaluated the total footprint (area of length x width) compared with tile count in order to come up with a list of ships to adjust.

19 ships did not match based on the longest dimension (width/height).
7 of those were very narrow and well within the recommended tile count, so I did not adjust those.
7 are mail pod variants which are only 1 tile over at 9x5, so I believe it is correct to leave them in the micro category
5 remaining are changed in this pull request

The Hammer is currently a Medium, but it is only 1 tile over at 17x14 and I believe the 'feel' of the ship is that of a small vessel, so I added a change to small which is in line to how the mail pod is currently handled. If others do not agree with that suggestion I can revert it.

The Pioneer is 9x5 as the other mail pod variants, but it is the only one listed as a small. I changed this one to micro for consistency as even though it is not strictly speaking the same layout as a mail pod it does share the same dimensions.

If you have any specific alterations you would like to recommend for individual ships, please let me know and I will address them based on the consensus of the group.

**Comment by whatston3** [comment]
Whenever a suitable criterion is found, it should be added to the shipyard tests.

**Comment by DmitriTheDemon** [comment]
> Whenever a suitable criterion is found, it should be added to the shipyard tests.

My understanding is that there was not an automated solution to determining the dimensions and tile counts of a given ship file when I was skimming through discord? That might involve parsing the mapping file which would be Fun

**Comment by dvir001** [comment]
Why closed?

**Pull request closed without merging**
