### PR TITLE
Anomalous Lab Point of Interest

### PR DESCRIPTION
**Pull request by RealIHaveANameOfficial**
The Anomalous Lab is a point of interest dedicated to, as the name suggests, anomalous research. It's unknown why the station is uninhabited...Maybe it's up to you to find out?

## About the PR

This PR adds the Anomalous Lab. It features a cargo dock, a few docking ports, atmospherics, cryogenics and medical, an incomplete AME, solars, dormitories, a janitor's closet, a rather robust bar, and a large science area.

## Why / Balance

This is an alternative to Crescent anomalous research. If/When we end up retooling anomalies into larger events, this PoI may be changed to a Bluespace Harvester center, a bluespace event, or some other formfactor, or simply removed. Depending on how/if this gets added, I may add more/less loot, enemies, resources, lockers, power, and anything and everything else.
## Technical details

I do not actually know how to add a point of interest, so I copied the yml for the lodge and replaced all the stuff with the anomalous lab. I doubt that's enough to get it working, but I'll figure out how this works later/via this draft.
## Media

AnomalousLabCompile
Big thanks to Charcoal in the discord for putting this image together of it! Should be useful for the wiki too.
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The Anomalous Lab has appeared as a dangerous point of interest in Frontier space.

### CODE REVIEW

**Comment by McBosserson** [comment]
Please color the pipes, and add a few mobs.

This almost looks like a fully functional ship, and I personally would have loved it to be so.
(I almost thought it was)

**Comment by RealIHaveANameOfficial** [comment]
> Please color the pipes, and add a few mobs.

How do I color the pipes? Something about colornetwork, right?

**Comment by McBosserson** [comment]
Can you replace the bluespace matter bins with bluesspace part spawners?

**Comment by RealIHaveANameOfficial** [comment]
> Can you replace the bluespace matter bins with bluesspace part spawners?
They actually already are! They just look like matter bins and not part spawners when you're mapping.

**Comment by Cheackraze** [comment]
do we have an anomaly spawner you could put on there? if its supposed to be a challenge to get to or clear, i would think an already pulsing anomaly would be the perfect thing. otherwise, my only other critique is for the docks to be built with a little more clearance, or perhaps another dock added somewhere, and then a bit more decal work in the hallways to break the monotony.

**Comment by RealIHaveANameOfficial** [comment]
There is an anomaly spawner, but I had concerns of an anomaly going supercritical and blowing up the station before anyone could get to it. I suppose that might serve to be decently interesting, but I don't suspect having to rebuild the lab every single shift would be super fun.

**Comment by RealIHaveANameOfficial** [comment]
image
Changes as you requested. I'm still hesitant to put an already-going anomaly, though.

**Comment by Cheackraze** [comment]
> There is an anomaly spawner, but I had concerns of an anomaly going supercritical and blowing up the station before anyone could get to it. I suppose that might serve to be decently interesting, but I don't suspect having to rebuild the lab every single shift would be super fun.

I think this could be a great oppurtunity for some engineering teamup play tbh. And, it will provide a variety to each shift for anyone who wants to use the lab. So long as you spawn them far enough away from the critical components (basically, just the anom generator itself).

For the amount of loot inside, i think it would be a great thing to help bump the difficulty up.

**Comment by McBosserson** [comment]
Because it's to be a poi, I believe placing an anomaly would be more annoying and easier rather than harder.

Unless someone goes straight for it at round start, the anomaly will likely go crit before anyone arrives. This would only lead to it being spaced, or the need to do so, killing the mobs in the process. It also makes sense that a rouge liquid anom already lead to its abandonment, and a random anom would detract from this narrative.

Maybe add the partially contained liquid anom, to add to its story and because I don't think it explodes (damages floors and walls) when crit. Perhaps it could just have iff off, like the syndi outpost.

**Comment by Cheackraze** [comment]
I understand that, but as it is this is just a giant Loot POI that will only reward the very first person to step foot on it and provides 0 challenge, detterent, or any reason whatsoever to work with anyone else.

The danger needs to be present, I cannot allow a POI that jsut *gives* players an entire science lab to use for free, bypassing all the other game mechanics.

**Comment by RealIHaveANameOfficial** [comment]
image
image

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
