### PR TITLE
Replaces Anchor tiny fans with directional fans.

### PR DESCRIPTION
**Pull request by dustylens**
## About the PR

Tiny fans out directional fans in.
Tiny fans out directional fans in.

## Why / Balance

Frontier hazing ritual. 

## How to test

Check dem doors.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 
- tweak: Replaces Anchor tiny fans with directional fans.

### CODE REVIEW

**Review by arimah — CHANGES_REQUESTED** [review]
The tiniest of fans has been forgotten, neglected, rejected, left to spin all alone:

image

**Comment by arimah** [comment]
After having a good long look at the Dart-X, I've discovered numerous other issues with the ship. It will be making a separate PR to retire it pending a rework.

**Comment by arimah** [comment]
Iiiii close the WRONG DANG PR. I'm so sorry.

**Review by whatston3 — APPROVED** [review]
Directional fans seem fine, all 8 accounted for on the docks.

I've restored the shield sign by the mercenary locker (picture attached at the bottom of the post - improvements on sprites more than welcome).  I've also added a ~30% margin to the price to put it in line with other expedition ships

As with the Sprinter, I'm going to give this one a few days for additional review, but it seems fine to my eyes.

image

**Pull request merged**
