### PR TITLE
Cyborg Advanced Modules (Mining, Medical)

### PR DESCRIPTION
**Pull request by Myzumi**
## About the PR

This adds in two new Cyborg Modules called Advanced Mining Module and Advanced Paramedical Module.
The Modules are a upgraded version of the previous modules that are the following;

Mining (MassExcavation Reseach);
Drill -> Diamond Drill
Ore Bag -> Bluespace Ore Bag

Medical (MechanizedTreatment Reseach);
Bute Packs -> Sutures
Ointment -> Meshes
Syringe -> Bluespace Syringe

All other items in said base modules has not been touched (As theres no upgraded versions of said items.)
Prices where also incresed to include Bluespace Crystal costs and the Diamond Drill cost
Paramedical Module can refill their Suture and Mashes via the ingame items like normal.
Sprites for the module icons where made by GhostPrince.

## Why / Balance

This allows Cyborgs to also get some Upgrades and be useful in later Reseach Stages
## How to test

- Run the Fork
- Reseach the Requred Reseach for the modules
- Print said Modules
- Insert into a Cyborg
- Get to Mining or Tending Persons

## Media

_I would upload a video here but i blame github for its 10MB limit_
image
image
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: New Cyborg Modules, Advanced Mining and Advanced Paramedic
- add: Cyborg Tool modules now have a Maintenance Jack

### CODE REVIEW

**Comment by dvir001** [comment]
No need for any

```
# New Frontiers - This file is licensed under AGPLv3
# Copyright (c) 2024 New Frontiers Contributors
# See AGPLv3.txt for details.
```

The all repo is AGPLv3 except when stated otherwise or the code has an upstream origin and no changes, this text isn't needed.

**Comment by Myzumi** [comment]
> No need for any
> 
> ```
> # New Frontiers - This file is licensed under AGPLv3
> # Copyright (c) 2024 New Frontiers Contributors
> # See AGPLv3.txt for details.
> ```
> 
> The all repo is AGPLv3 except when stated otherwise or the code has an upstream origin and no changes, this text isn't needed.

I shall blame the [Markers Markdown file](https://github.com/new-frontiers-14/frontier-station-14/blob/master/MARKERS.md)...
I removed them.

**Comment by whatston3** [comment]
Minor set of suggestions, curious what you think.

https://github.com/Myzumi/frontier-station-14/compare/Cyborg-Advanced-Modules...whatston3:frontier-station-14:Cyborg-Advanced-Modules-suggestions?expand=1

- Adds an unpowered advanced mineral scanner to the advanced mining module (consistent with the base mining module after the upstream merge)
- Replaces the crowbar with a jaws of life in the advanced mining module
- Renames the "advanced paramedical module" to "advanced paramedic module"

Seems fine, works fine.

**Comment by whatston3** [comment]
Thought of one more thing - if you wanted to put the maintenance jack (the thing that tears up plating) on some of the borg modules where it'd make sense, that might be a good idea.

**Comment by Myzumi** [comment]
> Minor set of suggestions, curious what you think.
> 
> https://github.com/Myzumi/frontier-station-14/compare/Cyborg-Advanced-Modules...whatston3:frontier-station-14:Cyborg-Advanced-Modules-suggestions?expand=1
> 
> * Adds an unpowered advanced mineral scanner to the advanced mining module (consistent with the base mining module after the upstream merge)
> * Replaces the crowbar with a jaws of life in the advanced mining module
> * Renames the "advanced paramedical module" to "advanced paramedic module"
> 
> Seems fine, works fine.

Merged the suggestions, I kinda forgot that the jaws of life exists as mostly admining tends to give you more tools ;-;


> Thought of one more thing - if you wanted to put the maintenance jack (the thing that tears up plating) on some of the borg modules where it'd make sense, that might be a good idea.

I can put it on some of the Construction Modules made for Building etc. Might be the best place for them or even just directly in the Tool module

**Comment by Myzumi** [comment]
Added the Maintenance Jack to the Normal and Advanced tool module as the Maintenance jack is buyable at roundstart

**Comment by Myzumi** [comment]
Something to note of, i saw this one while playing on another fork, this comes directly from upstream and could actually conflict with this.

https://github.com/space-wizards/space-station-14/pull/32487

**Review by whatston3 — APPROVED** [review]

**Comment by ColdDead** [comment]
I got a idea/question to the adv medical threatmeant moduls, why is there no crew handheld monitor and/or the defi build in? Find it still odd use 1 modul slot just for a defi

**Pull request merged**
