### PR TITLE
Investigator (Update)

### PR DESCRIPTION
**Pull request by ThatOneGoblin25**
## About the PR
Updated and rework, and moved investigator.yml to _NF/Shuttles.
- added missing HV power cable to right solar array so now it will actually give power.
- added station records console
- added circuit imprinter
- added vacuum tags to outside tiles
- replaced consoles with tabletop variants. 
- replaced pacmans with ship variants which start with plasma
- reworked artifact room
- replaced interior reinforced walls with solid walls
- replaced cargo and sci airlocks with glass equivalents 
- nerfed bar, booze-o-mat replacing soda dispenser
- added a random drink spawner on the counter
- fixed conveyor belts under outer blast doors not linked properly
- replaced storage canisters with one extra artifact container
- removed donut vendor
- replaced traffic intercom with science intercom
- added gas pump for distro line
- replaced metal tables with reinforced tables
- minor touch ups and decal work
- moved yml from Maps/Shuttles to Maps/_NF/Shuttles

## Why / Balance
It's a commonly used ship and its really starting to show its age and issues. It's also on the list of ships that need to be reworked for new mapping standard on the ship megathread #908.

## Media
Screenshot 2024-02-17 210709

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

:cl:
- tweak: Updated and reworked the Investigator.
- moved yml from Maps/Shuttles to Maps/_NF/Shuttles.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
Everything you put below :cl: should go in "about this pr", the changelog should look something like this (it will be displayed in-game):
```
:cl:
tweak: Reworked the Investigator
```

**Comment by ThatOneGoblin25** [comment]
> Everything you put below 🆑 should go in "about this pr", the changelog should look something like this (it will be displayed in-game):
> 
> ```
> :cl:
> - tweak: Reworked the Investigator
> ```

Ah thank you this is really my first PR.
Also fixed atmos pipes to no longer go under two solid walls, and added some cleanable dirty decals.

**Comment by UbaserB** [comment]
As the person who made the investigator, could you remove the reinforced tiles in the artifact room? I had purposely left them out. (of course if it was part of the new mapping guidelines, which i think it wasn’t last i checked, feel free to keep it in). Otherwise, looks fine!

**Comment by ThatOneGoblin25** [comment]
> As the person who made the investigator, could you remove the reinforced tiles in the artifact room? I had purposely left them out. (of course if it was part of the new mapping guidelines, which i think it wasn’t last i checked, feel free to keep it in). Otherwise, looks fine!

Ah will do. Forgot to track down the make author for a ping.

**Comment by ThatOneGoblin25** [comment]
I think we're done now. If #1032 gets merged I might come back and re-add the space gap between the artifact room and shuttle because it was a popular design feature.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
