### PR TITLE
ContrabandClothing faction

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Added 2 ai factions: `ContrabandClothing`, `ContrabandDetection`
- Distributed `FactionClothing` component through wearable contraband clothes: now when players wear contraband armor they gain `ContrabandClothing` faction.
- Made contraband denying turret: shoots disabler bolts at members of  `ContrabandClothing` (and ant hostile to NanoTrasen faction members).

## Why / Balance
Horrible idea

## How to test
1. Obtain clothes classified as contraband (cult robes/syndie/wizard).
2. Map 'contraband denying turret'.
3. Wear those closes, get shot.
4. Stop wearing contra, don't get shot.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
some edits to base game files

**Changelog**
:cl: erhardsteinhauer
- add: Added contraband denying turret that stuns players wearing contraband.

### CODE REVIEW

**Review by whatston3 — COMMENTED** [review]
No entry on ClothingOuterHardsuitSyndieEliteUnremoveable and ClothingOuterHardsuitSyndieBloodRedUnremoveable because they're only NPC-equippable and therefore automatically targeted by turrets?

What about entries for:
- ClothingHeadsetAltSyndicate
- ClothingEyesHudSyndicateAgent
- ClothingEyesGlassesHiddenSecurity
- ThievingGloves
- ClothingHandsGlovesNorthStar
- ClothingHeadHelmetSyndicate (helmet, not used?)
- ClothingHeadHatHoodCulthood (helmet, not used?)
- ClothingShoesChameleonNoSlips

Apart from that, seems fine, will test - might be on and off, expect delays.

**Comment by ErhardSteinhauer** [comment]
> No entry on ClothingOuterHardsuitSyndieEliteUnremoveable and ClothingOuterHardsuitSyndieBloodRedUnremoveable because they're only NPC-equippable and therefore automatically targeted by turrets?

Player should not be able to obtain those at all.

>What about entries for:
>  ClothingHeadsetAltSyndicate
> ClothingEyesHudSyndicateAgent
> ClothingEyesGlassesHiddenSecurity
> ThievingGloves
> ClothingHandsGlovesNorthStar
> ClothingHeadHelmetSyndicate (helmet, not used?)
> ClothingHeadHatHoodCulthood (helmet, not used?)
> ClothingShoesChameleonNoSlips

Missed those, will fix. They probably also missing `contraband` component too.

**Comment by ErhardSteinhauer** [comment]
Should be fixed now

**Review by whatston3 — APPROVED** [review]
Changes work well.  Approving and closing for now, curious to see when these get mapped.

**Pull request merged**
