### PR TITLE
Interceptor (Update Shuttle)

### PR DESCRIPTION
**Pull request by chrome-cirrus**
## About the PR
Updates the NSF Interceptor to modernize things a bit:
- Replace tiny fans with directional fans
- Replace loose plasma sheet fuel with a pre-filled locker
- Add firelocks to interior doors
- Remove some duplicate wiring elements
- Replaced some fixed wall posters with random poster spawners
- Replaced wall recharger with a tabletop model

## Why / Balance
Compliance with the Tiny Fan Reduction Act of 2024, general modernization.

## How to test
Spawn one in and take it for a spin.

## Media
docked
mapping
nodevis

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**

:cl:
- tweak Update the NSF Interceptor

### CODE REVIEW

**Comment by chrome-cirrus** [comment]
Two things:
- Still has a single can atmos setup. I like to change these to two can ones, but opinions vary so I left it alone.
- I noticed some custom labels on buttons for the shutters. Do we want to rip out existing examples of that, or is it just a new ship guideline to not do them?

**Comment by chrome-cirrus** [comment]
Found a duplicate scrubber I missed on earlier passes. Also rerouted the waste vent for a cleaner look.

atmostweak

**Comment by Tych0theSynth** [comment]
> Two things:
> 
>     * Still has a single can atmos setup. I like to change these to two can ones, but opinions vary and it would require moving a bunch of crap in the cockpit, so I left it alone.
> 
>     * I noticed some custom labels on buttons for the shutters. Do we want to rip out existing examples of that, or is it just a new ship guideline to not do them?

I was the person who reworked this ship a while back, and it was done before Vox happened. Thank you for fixing some of my mapping errors! Yes the button labels can be removed as they are no longer allowed because of translation issues. 
I used set posters to give more of a specific detective theme, but random ones are fine. They're just posters after all, but I would keep them legit as these are NT vessels!
All looks good to me!

**Comment by dvir001** [comment]
image

Air canister sucks

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
