### PR TITLE
Orebox tweaks

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

Added an option to the context menu of the ore box and ore bag to toggle the magnet on/off.
Increased the price of ore box to 1000 (for real this time).
Updated description of ore box.

## Why / Balance

The ore box needed a better way to turn its magnet off and there have been times where I wished the ore bag magnet had an off switch.
The price increase was necessary, because at the moment an ore bag costs more than the box.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Moved the MagnetPickup component from Content.Server namespace to Content.Shared namespace to match their locations in the file structure.
The default action for the ore bag is now to toggle its magnet, not dump its contents.

**Changelog**

:cl:
- tweak: The magnet on the ore box (and ore bag) can now be toggled through the context menu.
- tweak: The ore box can now go under plastic flaps.

### CODE REVIEW

**Comment by dvir001** [comment]
**Lowered the value of the ore box to 0 to prevent selling it.**
This wont block selling it

**Comment by YumiGumi** [comment]
if possible, i would suggest a toggle for the magnet, since if you dump it, it just auto vacuums up what is dumped on the floor

**Comment by ErhardSteinhauer** [comment]
Would you consider adding to ore boxes component that allows containers to pass through plastic flaps?

**Comment by Wolfking6116** [comment]
Oh please please please. Erhard you're a genius. Yes. Can we do that? There's several things I'd like to see get added to that, at least the most commonly shipped items along conveyors.

**Comment by crystalHex** [comment]
The ore box (and ore bag) now has an option in the context menu to toggle the magnet on/off. This is also now the default action, when Alt-clicking either the box or bag. The state of the magnet can be seen by examining the box/bag.

**Comment by crystalHex** [comment]
Ore boxes can now also go under plastic flaps.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
