### PR TITLE
Removes all blocks from research

### PR DESCRIPTION
**Pull request by rbertoche**
it seems pretty self explanatory
cheers
edit:
I left code that won't get executed after the return to reduce contact area for merge conflicts which kdiff3 won't autosolve

### CODE REVIEW

**Comment by EmmaFaith** [comment]
Well i dont think this is necessary for frontier at all, because you can literally make multiple RD servers from chip vend that we have on frontier station, it will cause issues like people powergaming way too hard with combination of every tier 3 loot. and i think not every person should be able to do EVERYTHING that they want, so they will interreact/roleplay with other people to get their other needs. via trade/piracy etc.

**Comment by Cheackraze** [comment]
yea im kind of either or on this one tbh. On one hand, if you're in it for some deep science gameplay, probably frustrating if you hit the 2-3 hour mark and have to start over with the rng system.  On the other hand, it does encourage specializing and focusing your research still and actually having a plan/strategy about what you might want to focus on and unlock to make money selling or using etc.  Im not directly opposed but maybe we should do like some kind of more visible community poll of the scientists to see what they think.  I would still like them to be restricted on a per-grid basis no matter what so that scientists could sell servers to people for example.

**Comment by rbertoche** [comment]
Sorry to not replying to this earlier.
My main reason behind this change is: The whole idea of having a "main" branch is presented in game as if it were something you had achieved, and the way it is presented it reads at least to me personally as if it were a good thing, to have a "main branch" at your RD server. But in practice, this was nothing more than a block towards the other tech. I just noticed I lost this change locally when I merged with frontier again.
Maybe a poll was indeed a great idea anyway, I have done this on my codebases also due to players supporting it. What's better, to foster having more servers/and/or more research ships, or just make research more available and easier to everyone, even the Pioneer captain Research Director?
As long as having a main branch entails no advantages I would still personally prefer an unblocked RD server.
Also now with grid restricted RD servers, the whole game is way more interesting to play as science!

**Comment by dvir001** [comment]
If were doing this change we should also consider having servers take power per unlocked tech and not just flat % to make it fair.

**Comment by dvir001** [comment]
Closing this as this has gone stale, feel free to reopen in the future as we doing some sci reworks later after the upstream update.

**Comment by rbertoche** [comment]
How do I reopen?
I would love to push more for this since it's a clear improvement with little to no compromise as far as I can see.
I strongly disagree with this "feature" as explained before due to it adding absolutely nothing to R&D gameplay other than a research block, I fail to see how having a lot of research data stored in the server would cause more power usage or be power gaming and would be glad if someone pointed an actual advantage to the limitations, like Checkraze saying it pushes players to planning stuff ahead, which kinda makes sense but it's a very weak point stilk to justify having to build up to 4 of the same thing with no benefit if you wanted to unlock it all, plus the user experience cost of having to shift servers in the lathes - again with no benefit from this action.

As an unrelated side note I would probably also consider using whatever comes out of new R&D in Frontier in our Pirata codebase, which is not frontier-PT, so it's very in my interest to make sure frontier reasearch doesn't have this quite arbitrary limitation IMO.

Cheers

**Comment by rbertoche** [comment]
It's also worth noting the "lottery" type of research unlocking, where you only have 1 option of research to unlock in every field, gives you a slim benefit of being able to "reroll" the research slots by researching something from a tree which isn't the one you're focusing right now. But if you ever want T3 of that other tree, then doing that would waste the research points.

**Comment by Cheackraze** [comment]
sure lets try it why not, ive always been 50/50 on this if its needed or not because of how long are rounds are anyway.

**Review by Cheackraze — APPROVED** [review]

**Comment by rbertoche** [comment]
Nice!
As a response to GreaseMonk's comment, I can appreciate get that limitations can be interesting to the gameplay sometimes. But in this case it just seems to be a mechanic which gives the user trouble with no reward to compensate it. If unlocking T3 by itself and getting a "Main branch" had any meaningful benefit to users, I might not consider this change.

**Pull request merged**
