### PR TITLE
New clothing options for Chaplains.

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Added some new (mostly old actually) clothes for Chaplains. Accessible through PietyVend. Stuff added:
- New hats: kippah, wide-brimmed hat, cardinal's hat, bishop's mitre, witch hunter hat, pilgrim hat.
- New neck pieces: chaplain's stole (purple scarf thingy), crucifix.
- New coats: cardinal's robes (has toggleable hood), bishop's robes, witch hunter's coat (has toggleable hood).
- New jumpsuits: pilgrim's jumpsuit.
- New belt: chaplain's sash, that can hold job related items (censer, bible, bottle, crucifix, wooden stake).
- Misc items: censer (can be filled with ground tobacco/cannabis and lit), wooden stake (for, uh, camping in the woods, I swear. Need to emag PietyVent to get it though).

## Why / Balance
RP. Smoking censer! RP!

## Technical details
New .yml and .rsi, changes to PietyVend catalogue.

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- add: Added new clothes for Chaplains. Check nearest PietyVend.

### CODE REVIEW

**Comment by dvir001** [comment]
YAML Machine broke, please fix

Also need to add the bible change religion action soon...

**Comment by ErhardSteinhauer** [comment]
YAML threw errors, but I'm having hard times figuring out what caused it. New Tags in my PR?

**Comment by ErhardSteinhauer** [comment]
> Also need to add the bible change religion action soon...

Yeah, there was some progress upstream regarding chaplain job: candles and ability to create holy water with bible.

**Comment by ErhardSteinhauer** [comment]
Right, figured what was the problem, will make another PR because I have no idea how to fix it without scrapping this PR.

**Pull request closed without merging**
