### PR TITLE
Adds Chisel ship.

### PR DESCRIPTION
**Pull request by Blackszedows**
## About the PR
Added a reclaiming vessel , Chisel 

## Why / Balance
I wanted to make a ship meant for scrapping abandoned ships in case the ship's captain's ID wasn't aviable, however after concluding that using shuttle apu's wouldn't be balanced and using PACMAN's instead , I had to give the ship some form of mining capabilities.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added Chisel shuttle

### CODE REVIEW

**Comment by terezi-station** [comment]
great start to a better prospector, good shape and layout but needs work on the interior and walls, non connected diagonals dont exist on any other ship or station

**Comment by AjexRose** [comment]
maybe add a nitrogen canister along with the oxygen canister, or replace it with a general air canister for slimes.

**Comment by Cheackraze** [comment]
this is actually a super cute prospector-like 'variant', or simple upgrade. I like it.  My only critique is the triple thick wall chunk in the lower right.  I have an idea about that actually... how about a secret door for a smuggling compartment back there! Maybe move the generator or locker over and put a secret door would be friggen cool

**Comment by Blackszedows** [comment]
Judging by the seemingly unnecessary commits it adds, in the possible future PR's i'll try not to sync branches mid-review.

**Comment by Cheackraze** [comment]
> Judging by the seemingly unnecessary commits it adds, in the possible future PR's i'll try not to sync branches mid-review.

we do squash commits when merging, meaning it takes all of your changes and rolls them up into 1 commit, so dont worry about the # of commits you have on your branch

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
