### PR TITLE
NT Fishbowl (New) - Central commander personal transport/office (admin only)

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Added the Fishbowl, a small shuttle intended as a transport/office for an individual central commander.
The name and design is taken from the slang term for those managers offices which are made entirely of glass, so they can keep an eye on their delegates and so that said delegates always know they're being watched.
This shuttle is intended only for admin usage.

## Why / Balance
There's not an awful lot to say about this one. It was originally made as a random little thing for a bit of fun, but people seemed to like it and then it was suggested that it could make for an admin ship.
As it is intended as an admin ship, _there is no shipyard file_. The grid will need to be loaded manually as there is not yet such as thing as an admin shipyard. Should one exist in the future, I will update it accordingly. The grid YAML does contain a prototype name, so it will load in as 'NT Fishbowl'. I have also taken a couple of liberties with the ship submission guidelines. 

It felt appropriate to place it in its own 'admin' dir within the Maps/Shuttles/_NF/ dir.

Features and design considerations:
- CC locked doors (not the external airlocks).
- Security thrusters and gyro as they felt appropriate for this shuttle.
- APUs provide enough power for all thrusters and other machinery.
- Basic sustenance supplies and a coffee machine in case you're out there for a while. Also so you can grab a hot drink prior to a meeting.
- CC fax machine.
- Station records computer.
- Privacy shutters on the office.
- The main feature is the office space, of course. My inspiration was those glass offices/meeting rooms you see in some modern office buildings which prevent any sort of privacy and constantly allow your manager to watch what's going on. Personally, I hate them, but they are far too fitting for the dystopian megacorp aura of NanoTrasen. Naturally, the commander gets carpet.

## How to test

Load it in using loadgrid once you've checked out the branch, and off you go!

## Media
2024-04-16 13_33_49-Window
Uninitialised with subfloor, spawns.

2024-04-16 13_33_15-Window
Uninitialised with lighting.

2024-04-16 13_35_58-Window
Initialised with lighting.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None.
**Changelog**
:cl:
- add: Added the NT Fishbowl - a personal transport/office for central commanders.

### CODE REVIEW

**Comment by dvir001** [comment]
> > We will probably add a admin shipyard to allow admins to spawn it in later, so dont worry about needing a ship file for now.
> 
> No worries at all. I'm happy to add a shipyard file as and when it's needed in the future :)

Dont add a ship file now as we have no shipyard for it, lamo

**Comment by Tych0theSynth** [comment]
> > > We will probably add a admin shipyard to allow admins to spawn it in later, so dont worry about needing a ship file for now.
> > 
> > 
> > No worries at all. I'm happy to add a shipyard file as and when it's needed in the future :)
> 
> Dont add a ship file now as we have no shipyard for it, ill take care of it later, dont worry

Okay!

**Comment by Kesiath** [comment]
> We will probably add a admin shipyard to allow admins to spawn it in later, so dont worry about needing a ship file for now.
> 
> Please also add a normal ship fax there, just so it can get fax'd back as the centcom one is one way I think.

I'm pretty certain the Centcom fax is 2 way, should be fine to keep that in since I'd just replace it with that one when spawned in anyways.

**Comment by dvir001** [comment]
@Tych0theSynth Can you run an update on this PR, I will like us to test and get it added now that were done with the big update.

**Comment by Tych0theSynth** [comment]
> @Tych0theSynth Can you run an update on this PR, I will like us to test and get it added now that were done with the big update.

Away on holiday right now, but I will do this when I'm back.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
