### PR TITLE
Energy Guns (#385)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
The Head of Security special energy gun and the normal energy gun from TG.

## Why / Balance
The sheriff deserves a new tool and this one has _two_ firemode, using the same amount of shots as the TG version. It can shoot disabler bolts and projectile lasers specifically made for it (None hitscan).

It spawns on the back slot of sheriff.

## Technical details
A new system and component was made for the EnergyGun that allows for it to change between lethal and disable firemode while also changing sprites. It's the stunbaton and firemode system duct taped together.

## Media
https://github.com/DeltaV-Station/Delta-v/pull/385

## Breaking changes
N/A
 
**Changelog**
:cl: FluffiestFloof, dvir01
- add: Added the X-01 MultiPhase Energy Gun for the Sheriff.

### CODE REVIEW

**Comment by dvir001** [comment]
This will need some changes before we can consider a merge, leaving this as WIP

**Comment by Cheackraze** [comment]
please be more descriptive for changes like this. The lack of info and the PR and 46 changed files is going to make me ignore this since I have no idea what the intent even is.

**Comment by dvir001** [comment]
> please be more descriptive for changes like this. The lack of info and the PR and 46 changed files is going to make me ignore this since I have no idea what the intent even is.

Sorry I was in the middle of fixing it, you got here before I got to add it

**Comment by dvir001** [comment]
Its ready for frontier now.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
