### PR TITLE
NT Brigand (New) - Expedition-capable vessel

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
_"Civilian conversion of an old military light frigate from the early days of humanity's expansion to the stars, predating FTL technology."_, - Shipyard.
**Ship size:** Medium (323 tiles)
**Recommended crew:** 4-5
**Cost:** 54265
**Power Gen Type:** AME
**Expeditions:** Yes
**IFF Console:** No
**Available Roles:** Pilot, Mercenary, Salvage Specialist

## Why / Balance
With several expedition-capable ships scheduled to be removed, I felt like it was a good opportunity to offer a new expedition vessel. I tried to keep available amenities minimal, less of fully functional departments but more of a suggestion of where things might go. Also, I tried to cut down on the number of entities, so instead of filled lockers, I opted to use salvage techfab filled with some raw mats that should allow to print enough tools to equip the crew with tools and EVA suits.

## How to test
Spawn expedition shipyard console, buy NT Brigand.

## Media
Screenshots are a bit dated, changed a few minor things since those were taken:
- Removed medical beds and medkits from medbay.
- Removed microwave and mugs from kitchen
- Removed drain, mop and bucket from toilet.
- Replaced gun safes spawners with empty gun safes.
- Moved waste line pump to cargo bay, added disposals routed to southern part of the ship.

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Breaking changes
None afaik

**Changelog**
:cl: erhardsteinhauer
- add: Added NT Brigand - new expedition-capable vessel.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Egad, how did this not get the shuttle tag?!

**Comment by dvir001** [comment]
> Egad, how did this not get the shuttle tag?!

Cuz the tags fucked since I moved the ships to sub folders.
Ill need to make a PR to fix it.

**Comment by ErhardSteinhauer** [comment]
Removed medical beds and medkits from medbay, removed microwave from kitchen, removed drain from toilet

**Comment by dvir001** [comment]
> Removed medical beds and medkits from medbay, removed microwave from kitchen, removed drain from toilet

Based

**Comment by ErhardSteinhauer** [comment]
Updated screenshots
image
image

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
Remove the free mats.
image
IDK about that...common radio only please.
image
Your AME isnt fueled at ship spawn.
image
Please remove that bountyvend. 
You can replace a single gunsafe with a T2 gunsafe spawner. 
It looks like you have hidden all but one vent and one scrubber, it looks very weird to not be able to clearly see any of the vents...I need to think about that...

**Comment by ErhardSteinhauer** [comment]
> Remove the free mats.

Those aren't free, you pay for them when you buy the ship, but sure, I'll remove them

> common radio only please.

A'ight

> Your AME isnt fueled at ship spawn.

Yes. AMEs can't be fueled at round start since the latest upstream merge.

>Please remove that bountyvend.
You can replace a single gunsafe with a T2 gunsafe spawner.

Gunsafe spawners are getting axed, so I'll just remove bountyvend.

**Comment by ErhardSteinhauer** [comment]
> It looks like you have hidden all but one vent and one scrubber, it looks very weird to not be able to clearly see any of the vents...I need to think about that...

Most of the rooms in this ship don't have enough space for displaying vents/scrubbers and vents/scrubbers imo look bad when placed under carpets or catwalks, so I hid them everywhere for visual consistency (kinda). Can remove vent and scrubber from double staged airlock.

**Comment by ErhardSteinhauer** [comment]
Made the following changes:
- Removed bountyvend
- Removed mats from techfab
- Removed all encryption keys except common from telecomm server
- Removed vent and scrubber from docking airlock.

**Review by MagnusCrowe — APPROVED** [review]
You just needed to put an AME canister in the AME to get it working on spawn.
Also added the T2 weapon safe so the ship comes with the same weapon loadout as the Mayflower.

**Pull request merged**
