### PR TITLE
sawn-off shotgun in boots

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Well.. its is 10 in size..

## Why / Balance
Small size as the other small sidearms.

## Technical details
.yml changes

## Media
- [X] this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: Sawn-off shotgun can fit in all combat boots now

### CODE REVIEW

**Comment by PeccNeck** [comment]
I dunno about this one... Even if it _technically_ fits in terms of numbers, something tells me that a sawed-off wouldn't fit in boots. Doesn't really make sense, but that's just my opinion.

**Comment by Cheackraze** [comment]
would consider if the sawn-off itself wasnt already so powerful. And shotguns in general I guess are just really strong, probably still the best gun type outside of explosives. :minusone: from me for balance reasons

**Comment by dvir001** [comment]
Just keep in mind its still 10 storage in your backpack, coat, webvest, pocket or armor vest.
It can fit into all of them, so just giving you the option to also have it in boots isn't a game changer.

**Comment by Kesiath** [comment]
The sawn off fitting inside of 10 slots is definitely a good example of the inventory being a little goofy. Boots should be able to hold a hidden knife, holdout pistol, some extra cash under the insole, etc. Probably not an entire sawn-off shotgun, however. Might be better to just revisit the size of guns altogether instead of making a sawn-off fitting inside of a boot.

**Comment by GrandKadoer** [comment]
If it can fit in your pocket, it should fit in your boots. that doesn't seem unreasonable to me.

**Comment by Cheackraze** [comment]
TBH i dont even agree with the boot guns in general.

If any gun should be able to fit into a boot it, it should only be like a flare gun or some new 1-shot derringer pistol or something.

An MK-58 in a boot already is a little sus, same with the disabler.

**Comment by PeccNeck** [comment]
> TBH i dont even agree with the boot guns in general.
> 
> If any gun should be able to fit into a boot it, it should only be like a flare gun or some new 1-shot derringer pistol or something.
> 
> An MK-58 in a boot already is a little sus, same with the disabler.

I don't know enough about balance to speak to that end, but I do know (or at least think, I'm not an expert) that concealing firearms in boots _is_ at least a feasible thing IRL. With that said, I strongly doubt that sort of practice extends to larger firearms like _entire shotguns_ (even sawed-off).

**Comment by Cheackraze** [comment]
> > TBH i dont even agree with the boot guns in general.
> > If any gun should be able to fit into a boot it, it should only be like a flare gun or some new 1-shot derringer pistol or something.
> > An MK-58 in a boot already is a little sus, same with the disabler.
> 
> I don't know enough about balance to speak to that end, but I do know (or at least think, I'm not an expert) that concealing firearms in boots _is_ at least a feasible thing IRL. With that said, I strongly doubt that sort of practice extends to larger firearms like _entire shotguns_ (even sawed-off).

boot holsters are a real thing but they typically arent 'concealed', thats for sure. And they also typically cant hold all handguns, only smaller ones.  You wouldnt put a Judge in your boot holster for example, and thats still not even sawn-off sized.

**Comment by dvir001** [comment]
Closing this one.

**Pull request closed without merging**
