### PR TITLE
<Gourd Ship Fixes> Forgot to add Tiny fans under docking airlocks

### PR DESCRIPTION
**Pull request by YumiGumi**
## About the PR
Added 6 tiny fans under main docking airlocks

## Why / Balance
opening airlocks would space the ship

## Technical details
N/A

## Media

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added tiny fans on airlocks for the SLI Gourd

### CODE REVIEW

**Comment by dvir001** [comment]
Remove that changelog or have it a single line with your ship name in it

**Comment by YumiGumi** [comment]
> Remove that changelog or have it a single line with your ship name in it

done.

**Comment by dvir001** [comment]
Also you are using a fireaxe locker that cannot be open by anyone other then:
  - type: AccessReader
    access: [["Atmospherics"], ["Command"]]

**Comment by YumiGumi** [comment]
do not merge this, i have found the issue and need to fix it, but am tired as fuck tonight and will do it tomorrow.

**Comment by YumiGumi** [comment]
fixed and should be good to merge.

**Comment by Cheackraze** [comment]
Be sure to sync your master branch before making new branches! Thanks for the fixes!

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
