### PR TITLE
Carrying/escape-inventory tweaks

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
- Adds a new action that stops the "escape inventory" do-after. The action only appears when you try to struggle out of the inventory, e.g. while being carried or sitting in a bag. Should affect mice and such as well.
- Fixes dropping the carried person when walking over to a different grid (I can't count how many times I've been dropped when someone tried to carry me out of a shuttle!)
- Makes sure the carried person always stays at (0, 0) relative to the carrier. It used to be possible to offset the carried person by walking near a ~~singuloose~~ gravitational anomaly or by enclosing the carried person in a container while staying just outside it.

## Why / Balance
🥺

## Technical details
New action is a bit of C# changes + new yml and texture files

The second change is achieved by changing the OnParentChanged callback to check if the new ParentUid is the same as GridUid, which means the new parent is a grid and not chair/another carrier

The third change is achieved by iterating over all entities with BeingCarriedComponent and making sure their LocalPosion is approximately equal to (0, 0)

## Media
The third and second changes should not require media, but here's a showcase of the new action:

https://github.com/new-frontiers-14/frontier-station-14/assets/69920617/ae774992-e940-4f07-9950-da12f1819388

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None? I think.

**Changelog**
:cl:
- tweak: You no longer drop the carried person when walking across different grids.
- add: You can now halt your attempt to escape from a bag or someone's hands.
- add: Trying to take someone out of a bag now results in carrying them.
- add: You can now insert carried people into bags.

### CODE REVIEW

**Comment by Leander-0** [comment]
would it not be better to change the do_after so you can escape inventory when pressing the action than just canceling it after moving? sounds more intuitive to me.

**Comment by Mnemotechnician** [comment]
> would it not be better to change the do_after so you can escape inventory when pressing the action than just canceling it after moving? sounds more intuitive to me.

I'm not sure, but people are already used to the old system...

**Comment by Leander-0** [comment]
i mean the old system hasn't been changed since a year or more ago and its not like its a complete change from ground up will be very clear when the action shows to escape since there is little tie to react to the escape do_after to when you want to cancel it, its more easy to just try to escape when you want if you dont try it then it means you dont want.

**Comment by Mnemotechnician** [comment]
I don't want to change things that already work, because if I fuck up while doing it, it will be a much more serious problem than if I introduce a smaller change to fix the issue in hindsight...

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by Mnemotechnician** [comment]
More changes:
- Trying to take someone out of a bag results in you trying to carry them (since this is what *picking up someone* is meant to do, don't you think?)
- Added a verb to insert someone you *carry* into a bag

**Comment by dvir001** [comment]
Let me know when this is ready for review.

**Comment by Mnemotechnician** [comment]
> Let me know when this is ready for review.

It was ready for review 3 weeks ago.

**Comment by Cheackraze** [comment]
sorry for the delay while we handled The Big Merge ™️ , feel free to pull an updated master and I'll give this a full review. I had to put a bit of work into getting PsuedoItem to even work with the new grid inv in the first place, so there may or may not be some additional work needed on this as well

**Comment by Mnemotechnician** [comment]
It's up-to-date now, and it does compile and work. Also fixed another bug introduced by the merge (pressing shift would make you try to escape an inventory)

I was trying to fix throwing carried people, but after an hour of fiddling with the debugger I had no luck so far, I guess it's to be fixed in another pr

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
