### PR TITLE
Restore mass contests & fix carrying

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
First off, the latest upstream merge included this vile upstream PR that removed the contest system, which included the mass contest: https://github.com/space-wizards/space-station-14/pull/25425. The said mass contest was used in various places:
- Melee weapon system - disarming and shoving chance
- Escape inventory system - escape do-after time
- Carrying system - carrying and escape do-after times

I don't know the logic behind this PR, but it totally broke a few minor things. Felinids can now easily shove onis, while onis struggle to shove even someone as small as a mouse. Same applies to carrying and escaping invetories.

This PR fixes the above by reverting the PR that introduced this change, and also:
- Restores various mass contests in carrying (was removed as a part of the upstream merge, check probably didn't want to fix it)
- Restores carrying slowdown (same fate as above)
- Restores virtual items being put in the carrier's hands when they pick someone up (was removed for some unknown reason)
- Fixes the mass contest in escaping from carrying being inverted (compared to how it was before it was removed in the first place - for example, now it takes a long time for a felinid or (god forbid) a mouse to escape oni's hands)
- Fixes the bug that caused carried people placed inside a matter bin/cryosleep chamber to be teleported to the (0, 0) point of the grid, unable to escape

## Why / Balance
~~Nerf them felinids~~

While upstream is unaffected by this change due its LRP nature and the lack of mass difference among species, it does matter on frontier because we have smaller and bigger species. It removes practically the only disadvantage felinids and small vulps have in combat, and also sometimes negatively affects roleplay.

## Technical details
Reverted a pr and some changes made during the upstream merge.

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Should be none.

**Changelog**

:cl:
- fix: Shoving and disarming, as well as escaping inventories and carrying, are once again affected by the weight of the people involved in the interaction.
- fix: Several minor carrying bugs were fixed.

### CODE REVIEW

**Comment by Cheackraze** [comment]
Mass contests were bad, they were right to remove that mechanic. I don't want it re-added in any form whatsoever.  If ancillary systems were affecte, they should be fixed. Restoring mass contest is the wrong solution.  It was only ever used to power game, I don't want it back.

**Comment by Mnemotechnician** [comment]
So, how exactly they should be "fixed"? I suppose that means the mass contest in shoving should be gone, okay. What about the other two systems - escaping inventories and carrying?

**Comment by MagnusCrowe** [comment]
Guess we need to write up character sheets for everyone.

**Comment by dvir001** [comment]
Just like running speed balance to all races, shoving should be kept the same.

Think of a new system for ones that isn't around combat bonuses and is more for actual RP.

**Comment by Mnemotechnician** [comment]
Shoving has been restored to the uncontested state, I'm waiting on check to tell what to do with the other systems that do not affect combat

**Comment by Mnemotechnician** [comment]
Closing in favor of a smaller pr

**Pull request closed without merging**
