### PR TITLE
Handheld Mass Scanner

### PR DESCRIPTION
**Pull request by Temoffy**
Added handheld mass scanner.

Very useful for spacewalks, search and rescue, and related spacewalk-inducing situations, like guiding a ship toward you rather then hoping they are good enough with a gps. Or making a short trip to a spaceship that spawned near the station.

No changelog entry as the mass scanner is not accessible for players yet.

One yaml file, 2 pngs, and an extra if statement in the radar code.

## Media

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none

**Changelog**

### CODE REVIEW

**Comment by Temoffy** [comment]
I just realized that this included nearly 900 files, but I have no idea why or how to fix it.

**Comment by Cheackraze** [comment]
Hm, it looks like you had some issues and merged and reverted some things on your master branch. Im not exactly sure the best route to fix this, but I remember working through the changes with you to get it to work. We may need to start fresh on a new branch and bring the changes

**Comment by Temoffy** [comment]
Will do, should be pretty quick. How do you delete a merge request?

**Comment by Temoffy** [comment]
oh, that works

**Pull request closed without merging**
