### PR TITLE
More unshaded bluespace bag sprites

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Creates a new set of sprites for bluespace bags (X of holding) where inhand sprites are also unshaded.

## Why / Balance

Pretty lights.

## How to test

Spawn a bunch of bags, check that the alignment in your hands makes sense with each of them, in both hands.

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Bluespace bags should all light up properly now.

### CODE REVIEW

**Comment by dvir001** [comment]
Do you also need to update the tech tree in sci pictures?

**Comment by ErhardSteinhauer** [comment]
> Do you also need to update the tech tree in sci pictures?

Most likely not

**Comment by ErhardSteinhauer** [comment]
It would seem that neither plant bag of holding nor ore bag of holding have unshaded sprite bits when those are worn. (And also looks like I somewhat cooked unshaded bits for worn construction bag of holding).

**Comment by jimmy12or** [comment]
I had no idea how to do this when making the plant bag version, thanks for the adjustment!

**Review by dvir001 — APPROVED** [review]

**Comment by dvir001** [comment]
image

Funny

**Pull request merged**
