### PR TITLE
shotgun utility shells

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Posting as a draft so someone could stop me or add more ideas. So far added a variety of (soon craftable) shotgun shells:
- High-ex slug. 2 tile radius. Pretty weak.
- Flashbang slug. 2 tile radius.
- Net. Functions like bola.
- Laser shell. Fires 1 laser bolt.
- Disabler shell. Fires 1 disabler bolt.
- Syringe shell. Custom fillable, 2u.
- Anti-matiriel shell. Not as powerful as actual .60 but does something.
- Soap shell. Important.
- Trash shell. A shell stuffed with garbage.

### TODO:
- [ ] Modular shotgun shell recipe.
- [ ] Missing sprites.
- [ ] Better way of making gunpowder.
- [ ] Smoke shells. Custom fillable?
- [ ] Metal foam shells?
- [ ] Revolver shotgun?

## Why / Balance
Utility, fun.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: erhardsteinhauer
- add: Added a variety of craftable shotgun utility shells.

### CODE REVIEW

**Comment by Houtblokje** [comment]
love the syringe shell idea, not sure what one could do with 2 units though?
Also, net ammo? Can we get those for NFSD? ~
Very cool concepts.

**Comment by ErhardSteinhauer** [comment]
> love the syringe shell idea, not sure what one could do with 2 units though?

As turns out quite a lot. 4u that was OP.

**Comment by ErhardSteinhauer** [comment]
> Also, net ammo? Can we get those for NFSD? ~

everyone is getting it one way or another. nfsd might get factory made net shells though. not that those gonna be any different from makeshift ones.

**Comment by ThatOneGoblin25** [comment]
Could anti-material be changed to the breaching shell from tg?
https://tgstation13.org/wiki/Guide_to_Combat#Shotgun_Shells

**Comment by ErhardSteinhauer** [comment]
tbh I'm having doubts about this PR because shotguns are obscenely OP imo and adding more utility to them will make shotguns even better which is questionable thing to do.

**Comment by ErhardSteinhauer** [comment]
Gotta think about it some more

**Comment by ErhardSteinhauer** [comment]
Going to close this PR until I get the energy to work on it (probably never).

**Pull request closed without merging**
