### PR TITLE
Mechs Balance

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Realistic carry amount for mechs.

## Why / Balance
Using mechs to load 30 crates into a single robot is not RP based. its a mech not a fucking clown car.

## Technical details
Lower upgrades to 2.
Big clamp Lower carry from 10 to 8.

## Media
- [X] This PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl: dvir01
- tweak: Mechs carry amount adjusted to be logical.

### CODE REVIEW

**Comment by githubuser4141** [comment]
This is odd, crates arent that big and a ordinary forklift could probably carry at least five stacked on top of each other. Even if the mech clamps are a bit smaller then a forklift clamp each should carry at least 3 or 4?

**Comment by Cheackraze** [comment]
while I agree that 30 crates at a time is a bit much, I also think that 6 crates max is a bit low, since thats the entire purpose of the ripley is to haul cargo faster. Could we compromise at a 18 or similar?

**Comment by dvir001** [comment]
> while I agree that 30 crates at a time is a bit much, I also think that 6 crates max is a bit low, since thats the entire purpose of the ripley is to haul cargo faster. Could we compromise at a 18 or similar?

I made it use 2 max arms istead of 3 max (We all know where that arm was placed...)
SO you want it to be 9 per hand?

**Comment by dvir001** [comment]
> while I agree that 30 crates at a time is a bit much, I also think that 6 crates max is a bit low, since thats the entire purpose of the ripley is to haul cargo faster. Could we compromise at a 18 or similar?

Made the small one back to 4, big one 8 (2 times the size)

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
