### PR TITLE
Add FuelVend vendor.

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds the FuelVend vendor, which sells ship fuel and welding fuel.  The machine's supply is infinite, but the stock is expensive.  It is currently left unmapped.

Adds support for infinite-stock vending machines.

## Why / Balance

Players getting stuck on Frontier Outpost without a source of fuel.

Note: fuel prices still need work.  FuelVend should be a fixed markup (~30% for sake of argument) on crates, and crates should be appropriately priced to how much energy (N.B. _not_ power) they can generate.

## How to test

1. Build and run local server.
2. Spawn in FuelVend vendor.
3. Note the inventory prices.
4. Check that the deny state exists.
5. Note the pretty little rocket animation when you purchase fuel.
6. Note the snarky comments as you leave.
7. Try to open the panel, smash up the machine.
8. Try to unwrench the machine, it shouldn't work.
9. Warp to the Cargo Depot.
10. Spawn a stack of uranium, sell it, it should sell for $954.
11. Spawn a stack of plasma, sell it, it should sell for $954.
12. Spawn a jug of welding fuel, sell it, it should sell for $15.
13. Spawn a jar of AME fuel, sell it, it should sell for $636.
14. Compare all sale prices with the prices in the vendor, the vendor prices should be much higher.

## Media

image

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: A FuelVend machine has been added to Frontier Outpost.
- tweak: Tools and flatpacks now have unlimited inventory.

### CODE REVIEW

**Comment by whatston3** [comment]
Needs to be reupdated with master, and the StaticPriceComponent vendPrice might need to be extended into StackPriceComponent.

**Comment by whatston3** [comment]
Should be good to go.

A few notes:
* vendPrice was added to StackPriceComponent.
* If vendPrice is in both StackPriceComponent and StaticPriceComponent, it will add the two (similar behaviour to the material & solution values).  This is likely an error, and we should really pick one over the other - nothing currently inherits and defines both.
* vendPrice, if defined and greater than zero, overwrites default value.  **Always**, not only if higher.  Full plasma and uranium stacks are worth 6k by default (0.2 per plasma unit, 100 units per sheet, 30 sheets per stack), and that's ridiculous.

Testing instructions will be updated in the PR description shortly.  I have validated that the sale prices of plasma and uranium stacks, welding fuel jugs, and AME fuel jars has not changed at the cargo depot, that the vending machine prices are accurate and make sense (except for uranium, which needs a crate price decrease, per my [Energy Comparison sheet](https://docs.google.com/spreadsheets/d/12UVcNejDCND4KJ1Skt_GVx1WsZMF0bxnaGmmEK9to5w/edit?gid=0#gid=0)

**Comment by ErhardSteinhauer** [comment]
> Try to open the panel, smash up the machine.

Fun fact: if you open the panel and pulse vend contact pin with multitool the machine will eject 3 random items before "vending protection" activates.

**Comment by dvir001** [comment]
> > Try to open the panel, smash up the machine.
> 
> Fun fact: if you open the panel and pulse vend contact pin with multitool the machine will eject 3 random items before "vending protection" activates.

I added it since just removing the option to get any free items was too boring

I will however remove the tool use on this vend so people cannot cut wires

**Comment by ErhardSteinhauer** [comment]
To much C# for me to review, but it does work in game.

**Review by dvir001 — APPROVED** [review]
Good

**Comment by whatston3** [comment]
Dvir's happy with it, and the newest changes seem fine by me.  Merging once tests pass.

**Pull request merged**
