### PR TITLE
Praeda rework

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR
- Remove command encryption key
- Remove engineering encryption key
- Replace fully filled telecomms server with ship (non-sec) variant
- Move fax machine closer to shuttle console
- Remove custom-filled captain locker
- Add standard captain locker
- Move captain suit storage
- Remove deckard and ammo
- Remove CE's python and ammo
- Remove docking airlock insanity (the extra labels each. and. every. single. docking. airlock. had. STC's rejoice)

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Screenshot from 2024-01-06 14-46-32

## Breaking changes

**Changelog**
:cl:
- tweak: Praeda was reworked.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
Draft until #821 is merged. Diff is messy until this is done, as this branch contains commits from #821 .

**Comment by MagnusCrowe** [comment]
> Draft until #821 is merged. Diff is messy until this is done, as this branch contains commits from #821 .

Merged #821

**Comment by dvir001** [comment]
Can you set the AME to working on 4? and add a fuel tank to it.
It best if its running with the ship as you buy it

**Comment by TsjipTsjip** [comment]
Requested changes applied. Mapchecker will fail on a different shuttle, fixing that one in a separate PR.

**Comment by dvir001** [comment]
This is command locked, not captain locked
image

**Review by Cheackraze — APPROVED** [review]

**Comment by drhat** [comment]
Can I get some explanations as to what is meant by the airlock stuff? I labeled them so they were easy to identify when docking

**Comment by ThatOneGoblin25** [comment]
> Can I get some explanations as to what is meant by the airlock stuff? I labeled them so they were easy to identify when docking

Naming entities means they have English characters for non-english players. I also noticed in your ship there's a lot of named items and session modified items. Comb through your yml and look into the items with the metadata component, you shouldn't really have any item with that.

**Pull request merged**
