### PR TITLE
Jerry Cans

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds spill-proof jerry cans for welding fuel.  FuelVend now dispenses those.

Would have better parenting, but both the Jug and beverage carton have undesirable components.

## Why / Balance

Avoiding slippery, flammable fuel spills.

## How to test

1. Spawn onto Frontier Outpost.
2. Buy a jerry can of welding fuel from the vendor.
3. Throw it, it should not spill.
4. Spawn a JRPACMAN and an empty welding tool.
5. Fill them with welding fuel.

## Media

image

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: dvir001
- add: The NFSD Outpost now has a FuelVend vendor in the lobby.

### CODE REVIEW

**Comment by whatston3** [comment]
> Can you drink from it? Should be disabled, seemed like it is from the yaml.

Yes.  You should also not be able to drink from the sulfuric acid jugs, but you can.  Honestly, I was thinking I'd like to keep this definition as close to the jug as possible.

**Comment by ErhardSteinhauer** [comment]
> Should be disabled, seemed like it is from the yaml.

What's next? Prevent me from eating sheets of uranium? 1984 fr nc.

**Comment by dvir001** [comment]
> Can whitelist fuel

Not fixing the other drinking issue X_X
Also I think it will be fine for other liquids in general.

**Comment by Leander-0** [comment]
> > Can whitelist fuel
> 
> Not fixing the other drinking issue X_X Also I think it will be fine for other liquids in general.
> 
> (Blood engine when?)

Money engine when? i want to feel like the US government (burning spessos directly for fuel)

**Comment by ErhardSteinhauer** [comment]
Besides folks griefed by being force fed uranium/welding fuel on frontier is an admin issue

**Comment by whatston3** [comment]
Apparently I'm full of crap, but now the force feed delay should be increased to 5 seconds, and the drink time should be 1.5 seconds.  Damn lousy NT nanny state, not letting me drink my gas.

**Comment by dvir001** [comment]
> Apparently I'm full of crap, but now the force feed delay should be increased to 5 seconds, and the drink time should be 1.5 seconds. Damn lousy NT nanny state, not letting me drink my gas.

Real

**Review by dvir001 — APPROVED** [review]

**Comment by whatston3** [comment]
Subbed out the pirate console for the time being (needs rework related to #1748 before it's useful, otherwise will only confuse players).  Took a look at Dvir's changes, everything looks good to me.

**Pull request merged**
