### PR TITLE
Alterations of the Gourd and Bazaar into new mapping standards

### PR DESCRIPTION
**Pull request by YumiGumi**
## About the PR
Updated the Gourd and the Bazaar to align with new mapping standards and guidelines

## Why / Balance
Balance and alignment of preexisting ships to newer and more regulated standards

## Technical details
N/A

##Media
Bazaar1
gourd

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- tweak: Altered the SLI ships to bring them into line with mapping standards

### CODE REVIEW

**Comment by YumiGumi** [comment]
sorry about the long wait for alot of these rolling changes. but wanted to be sure what 100% needed changed before committing half of my free time to endlessly fixing the same 4 things over and over, if any concerns or alterations need to be made atop this, they shall be tackled tomorrow when i awake

**Comment by TsjipTsjip** [comment]
Please modify `.github/mapchecker/whitelist.yml` to not list Gourd and Bazaar under the technical debt section.

**Comment by YumiGumi** [comment]
> Please modify `.github/mapchecker/whitelist.yml` to not list Gourd and Bazaar under the technical debt section, so the mapchecker will start checking against these prototypes which were previously present on these ships.

i dunno what this is, so i'm gonna assume you aren't asking me to do something.

**Comment by TsjipTsjip** [comment]
> i dunno what this is, so i'm gonna assume you aren't asking me to do something.

I am. I need you to go on your branch, sync it with master via the big green button on the Github UI, and remove lines 35, 36, 47 and 48 from `.github/mapchecker/whitelist.yml`.

**Comment by YumiGumi** [comment]
> > i dunno what this is, so i'm gonna assume you aren't asking me to do something.
> 
> I am. I need you to go on your branch, sync it with master via the big green button on the Github UI, and remove lines 35, 36, 47 and 48 from `.github/mapchecker/whitelist.yml`.

alrighty, then would i push that updated file to this branch?

**Comment by TsjipTsjip** [comment]
Yup!

**Comment by YumiGumi** [comment]
> Yup!

gotcha, my branch was already synched, so i'll just alter that file and push, please hold, should be handled in about a min.

**Comment by TsjipTsjip** [comment]
Mapchecker is happy! Thanks for doing the technical bit for me, I appreciate that.

**Comment by YumiGumi** [comment]
> Mapchecker is happy! Thanks for doing the technical bit for me, I appreciate that.

not a problem

**Comment by MagnusCrowe** [comment]
image

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
