### PR TITLE
Paladin (New Shuttle)

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Adds the paladin, a templar like ship for the NFSD that comes included with a Duster type ship mounted grenade launcher, with this it will complete the templar trifecta of general, medic and assault ships.

## Why / Balance

Adds a ship with a mounted ship gun with 2 caded of 5 EMP grenades for the NFSD that does not require a whole empress to be bought to have.

Price is 34K and selling price is around 10K, the difference is mostly due to the shipgun included on the ship.

## How to test

Load game and buy the ship at the NFSD outpost.

## Media

Imagine with lights.

Version with floor active and no lightning.

**Changelog**

:cl: Leander
- add: add the paladin NFSD small ship

### CODE REVIEW

**Comment by Houtblokje** [comment]
so it is the Templar but I get to breathe while doing NFSD patrols?

**Comment by Leander-0** [comment]
Templar but included cannon and 10 rounds plus front facing zone to shoot or jump from. Templar is more for general transportation.

**Comment by chrome-cirrus** [comment]
This rips! I love it.

Nitpicky small review things:
-One duplicate LV cable right above the vent in the prisoner cell
-Could use atmos fix vacuum markers on space exposed tiles
-Firelock probably would be good between the main compartment and forward airlock, maybe for the rear crew cell too
-Firing button directly north of the shuttle console doesn't seem accessible without climbing on the table
-Base grid name is still 'Templar', doesn't show up when you buy one but does when you load it in mapping mode and such

**Comment by Leander-0** [comment]
Updated

**Comment by Cheackraze** [comment]
After investigating, the mapchecker is having issues specifically with shuttle guns it appears. In an effort to clean out the ship backlog, I've added it to the tech debt list along with the rogue, since thats been the only thing blocking this one.

**Comment by Cheackraze** [comment]
guh now arbitrage breaks for unrelated ships due to upstream merge or something so im just gunna ignore and merge to get it in

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
