### PR TITLE
Public Affairs Official

### PR DESCRIPTION
**Pull request by Salvantrix**
~Almost donezo just needs a badge and a stampo and its good.~

All done now, everything's added as far as NFSD spawn point, new role specific items (folders with included forms, badge, pen, stamp) and its good for review.

## About the PR

Adds the new role, and functional items for it, the Public Affairs Official. 
Designed to aid NFSD in administrative tasks such as: Dispatch, Civilian Liaison issues, paperwork and court proceedings.
Feel free to use your new fancy folders to beat unsuspecting deputies who are disregarding space law or SOP's.

## Why / Balance

Helps create a civilian liaison position to assist the command staff of NFSD and the general public with basic tasks.
## How to test

Just do it.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

## Breaking changes

**Changelog**

:cl:
- add: The NFSD has a new civilian role, the Public Affairs Liaison, who interacts with the public and handles NFSD bureaucracy.
- remove: The Lawyer role has been removed, and all lawyer-related items are now available in Contractor/Pilot/Mercenary loadouts.
- tweak: The NFSD now has a new set of forms available in the PAL's folder, and some standard SR forms have been updated.

### CODE REVIEW

**Comment by whatston3** [comment]
I would recommend moving away from Official to Liaison for the following reasons:
* Cannot be mistaken for "Officer" in the acronym if you're gunning for this position to be a _civilian_ above all else.
* Explicitly reinforces that you liaise with the public.  You should be the point of contact, not some untouchable Byzantine bureaucrat.
* "PAL" is a cutesy acronym, and easier to remember since it's a word - either it'll soften the blow perceptually when interacting or further reinforces the corporate hellscape SS14.  Both are wins in my book.

**Comment by Salvantrix** [comment]
> I would recommend moving away from Official to Liaison for the following reasons:
> 
> * Cannot be mistaken for "Officer" in the acronym if you're gunning for this position to be a _civilian_ above all else.
> * Explicitly reinforces that you liaise with the public.  You should be the point of contact, not some untouchable Byzantine bureaucrat.
> * "PAL" is a cutesy acronym, and easier to remember since it's a word - either it'll soften the blow perceptually when interacting or further reinforces the corporate hellscape that is the SS14 universe.  Both are wins in my book.
-----------------------------------------------------------------------------------------------------------------------------------------------
> I think as far as the naming schema is concerned it works as it should, their responsibilities include being the point of contact for the public but they are much more than just that. 
>
> The job duties they're expected to perform should alleviate any misunderstandings as they'll never be in a place to be confused with the certified employees necessarily and will be expected to correct any misconceptions (unless rp moment?).

**Comment by Salvantrix** [comment]
> Personally I think "liaison" is a tricky word for non-native speakers, and I'd wager a lot of native speakers can't even spell it right. That triple vowel combo, whew.
> 
> ~Plus, I worked at a company where all of HR was renamed to PAO ("People And Organisation"), so the extra trauma points are a plus for me.~

_Not me literally misspelling it in the original post_

**Comment by whatston3** [comment]
> Personally I think "liaison" is a tricky word for non-native speakers, and I'd wager a lot of native speakers can't even spell it right. That triple vowel combo, whew.
> 
> ~Plus, I worked at a company where all of HR was renamed to PAO ("People And Organisation"), so the extra trauma points are a plus for me.~

NFSD is already full of tricky points, apparently, I see this as a non-issue, and kind of hilarious.
- sheriff
- bailiff
- sergeant
Why not liaison too?

Honourable mention to Tinnia's.

**Comment by whatston3** [comment]
Did a little bit of cleanup here: [whatston3:Public-Affairs-Official-suggestions (GitHub)](https://github.com/Salvantrix/frontier-station-14/compare/Public-Affairs-Official...whatston3:frontier-station-14:Public-Affairs-Official-suggestions?expand=1)

Lawyer role is gone from the NFSD Outpost, but all lawyer items (badge, suits) are available in contractor (and therefore pilot and merc) loadouts - stamps are already in bureaucracy loadouts.

I am once again recommending the use of Liaison.  Do it for your ol' PAL. :)  Can pull this in when ready.

Still need to proofread the NFSD forms and give the loadout for the new role another look.  Apart from that, I think this looks good.

**Comment by whatston3** [comment]
Pretty much happy with the forms.

SR forms now have dark blue headings and the forms they have that are more NFSD-oriented say that there should be no serving Sheriff to issue, for example, contraband permits, contraband amnesties.  Unsure if this is currently covered by space law, but it seems reasonable for somebody to be in charge in particular circumstances.

Took a look over the NFSD forms.  The existing arrest warrants and search warrants were merged with the new PAL-specific forms.  Sheriff might want to start with a folder, but I haven't done that as of now.  I've replaced the ticket with an "arrest report", which is intended for officers processing arrests.  Won't lie, pretty far out of my wheelhouse, but what's there is my best attempt.

I'd appreciate a look over the changes to the paperwork in particular, but I believe everything else is alright.  Might give this another look in a day or two.  Approving this from my side as-is, but additional review is more than welcome.

**Review by whatston3 — APPROVED** [review]

**Comment by whatston3** [comment]
Paperwork time.

**Pull request merged**
