### PR TITLE
Added Maximum IFF Distance Slider to NavScreen

### PR DESCRIPTION
**Pull request by BoettcherDasOriginal**
## About the PR

**QoL improvement:**
Adds an Range Filter to the Nav Screen in the Shuttle Console UI.
-> Filter IFFs by distance

## Why / Balance

Sometimes you want to know the IFFs around your Shuttle or around Frontier as STC, but don't want to get spammed with those over 40 IFFs that are 2km away
It simplifies the work as STC since you just see the IFFs near Frontier when set to like 256m. 

The "Show Shuttles" Toggle isn't an option cuz you cant see the IFFs anymore!

## How to test

1. Get yourself a Shuttle Console
2. Enter any float you want into the "Range Filter" Input Box (Non Floats are handled (bascily ignored))
3. Have Fun!

## Media

Screenshot (843)
Screenshot (845)
Screenshot (847)
Screenshot (849)
Screenshot (851)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added a IFF Range Filter to the Shuttle Console!

### CODE REVIEW

**Comment by arimah** [comment]
I like the idea of being able to filter IFFs by distance. Too often do faraway IFFs make it hard to coordinate movement past nearby things. That said, I have two comments about this implementation:

* "Range Filter" does not strike me as the most intuitive name for the feature. Is it maximum or minimum distance? Can I enter something like "200 - 500" to specify an interval? It's also not clear that the range filter applies to IFFs. I think something like "Maximum IFF Distance" better expresses the intent.
* A free-form text input is generally a bad way to accept numeric input, especially when the value is heavily constrained (0 up to some maximum). If possible, a slider would probably work better, perhaps with a text input next to it for finer control.

**Comment by dvir001** [comment]
Need more frontier comments on added lines / blocks that are missing

FTL Need to be under _NF

**Comment by dvir001** [comment]
Also range filter should be a slider with min to max

**Comment by BoettcherDasOriginal** [comment]
Screenshot (853)
Slider with Min 0 and Max 3000

**Comment by BoettcherDasOriginal** [comment]
- [x] Need more frontier comments on added lines / blocks that are missing
- [x] FTL Need to be under _NF
- [x] slider with min to max
- [x] understandable clear name 

Anything else?

**Comment by BoettcherDasOriginal** [comment]
Screenshot (854)

- fixed SpinBox margin
- set default Slider value to 3000
- SpinBox doesn't accept non-numbers by default

**Review by whatston3 — COMMENTED** [review]
Changes look good - I've created a branch with a set of suggestions and merged in the current head of master.  Wish that spinbox margin was more easily accessible through the control.  Oh well.

Cleanup's here: https://github.com/whatston3/frontier-station-14/commit/77dc128ec61150d38b397d813d3f844ab6670482

Branch is here: [whatston3:RangeFilter-suggestions](https://github.com/whatston3/frontier-station-14/tree/RangeFilter-suggestions)

Changes:
* Changes check in ShuttleNavControl.Draw to positive floats vs. explicit -1, adds "shouldDrawIff" to avoid unneeded transforms.
* Pushes SliderIntInput Value initialization to the .XAML file
* AGPL modification comments

Happy with this small set of changes.  Pardon the wait.

**Comment by Cheackraze** [comment]
yea this looks really nice with the slider control, once requested changes are complete lets get this in

**Review by Cheackraze — APPROVED** [review]

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
