### PR TITLE
Shotgun spread refactor Cherry Picked

### PR DESCRIPTION
**Pull request by VividPups**
## About the PR
This is Cherry-picked from this PR https://github.com/space-wizards/space-station-14/pull/27773
(I'm not quite sure how to give Proper credit and whatnot to the OG people)

## Why / Balance
Needed for a guns
## Testimonial 
" I added a new component, ProjectileSpreadComponent. The new component now holds the projectile count and spread data that was previously in the CartridgeAmmoComponent, as well as an additional entity prototype field. In the GunSystem, the code for spawning the original bullet uses the switch case's preferred method (spawning the bullet from the cartridge prototype for CartridgeAmmoComponent and just launching the projectile it already has for AmmoComponent) but uses the ProjectileSpreadComponent to launch the rest of the spread. "  - [RiceMar1244](https://github.com/RiceMar1244)

## Media

- [x] this PR does not require an in-game showcase

## Additional Info

I'm not sure if this would cause in huge breaking or problems. I know the guns from frontier would need to be look at first before merge

**Changelog**
No CL!

### CODE REVIEW

**Comment by VividPups** [comment]
imma wait for a maintainer before attempting to fix any Conflicts so, a better understanding can happen

**Comment by whatston3** [comment]
Should be fine, tests seem alright, clamp is still wonky, unsure why - projectiles will never hit unless user is within 1 m of the mob.

**Review by whatston3 — APPROVED** [review]
Approving, hope the tests pass.

**Comment by VividPups** [comment]
> Should be fine, tests seem alright, clamp is still wonky, unsure why - projectiles will never hit unless user is within 1 m of the mob.

Clamp?

**Comment by whatston3** [comment]
Talked through the changes with Erhard, happy enough with this.  Blood cult janitor might need another look.

**Pull request merged**
