### PR TITLE
Pioneer (Update) + Guidebook

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Cleaned the table a bit from junk
Replaced the generator with a ship one
No more errors?

## Why / Balance
Cleanup

## How to test
Start and spawn ship

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
Can you move the air scrubber to the place where the air sensor is? And ditch the sensor then.

**Comment by MagnusCrowe** [comment]
> Can you move the air scrubber to the place where the air sensor is? And ditch the sensor then.

Why bother moving the scrubber? Just remove the sensor. It's useless when placed next to the vent.

**Comment by dvir001** [comment]
> > Can you move the air scrubber to the place where the air sensor is? And ditch the sensor then.
> 
> Why bother moving the scrubber? Just remove the sensor. It's useless when placed next to the vent.

Ill replace it, sure.

**Comment by dvir001** [comment]
> > > Can you move the air scrubber to the place where the air sensor is? And ditch the sensor then.
> > 
> > 
> > Why bother moving the scrubber? Just remove the sensor. It's useless when placed next to the vent.
> 
> Ill replace it, sure.

Fixed

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
