### PR TITLE
Raw Plasma Generator

### PR DESCRIPTION
**Pull request by Wolfking6116**
## About the PR

This adds a generator that runs entirely and solely on raw plasma ore. It sits on a power level in between the Jr. Pacman and the regular Pacman.

## Why / Balance

This is to return the concept of using raw plasma to power Pacmans, since it was unintentionally removed during one of the changes upstream. No mention of its intention to remove this feature was mentioned in the PR that caused it to no longer work, so I presume it wasn't intended.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Some of the yokels of the Frontier have brought some older generators into use.

### CODE REVIEW

**Comment by dvir001** [comment]
You have to add auto starting one and new sprites for it to or its going to confuse players

**Comment by Wolfking6116** [comment]
I'm not a spriter, so that's out of my realm. 

I'll get an auto starting one set up though.

**Comment by Cheackraze** [comment]
to be honest, i would kinda like the feature just returned to normal generators, I guess i wasnt aware that function was removed

**Comment by dvir001** [comment]
> to be honest, i would kinda like the feature just returned to normal generators, I guess i wasnt aware that function was removed

Removed by upstream,

but on the logical level it means anyone can just yeet ore into a generator from mining without processing it, making it a bit less of a process if every ship can just refuel from mining.

In general we should keep this feature so only mining focused ships can fuel by mining since they have ore processors.

**Comment by Wolfking6116** [comment]
> to be honest, i would kinda like the feature just returned to normal generators, I guess i wasnt aware that function was removed

I'm of similar mindset, since it will always be less efficient to use raw plasma ore as fuel because an ore processor with even the slightest upgrades immediately makes it more efficient. 

> but on the logical level it means anyone can just yeet ore into a generator from mining without processing it, making it a bit less of a process if every ship can just refuel from mining.

At best it's an emergency measure that gives players **options** of calling for help, or strugglebussing to try and some ore. If they're considering that as an option they're probably already running desperately low, or have already run out of fuel and are running on back up power and trying to get close to an asteroid before going dead in the water.

**Comment by dvir001** [comment]
> > to be honest, i would kinda like the feature just returned to normal generators, I guess i wasnt aware that function was removed
> 
> I'm of similar mindset, since it will always be less efficient to use raw plasma ore as fuel because an ore processor with even the slightest upgrades immediately makes it more efficient.
> 
> > but on the logical level it means anyone can just yeet ore into a generator from mining without processing it, making it a bit less of a process if every ship can just refuel from mining.
> 
> At best it's an emergency measure that gives players **options** of calling for help, or strugglebussing to try and some ore. If they're considering that as an option they're probably already running desperately low, or have already run out of fuel and are running on back up power and trying to get close to an asteroid before going dead in the water.

When running low on fuel I just radio for help, so far every single time it happen I RP got helped by another player and will not trade something like this for just "mine it yourself"

**Comment by Wolfking6116** [comment]
In the same vein, I've had times where I've radio'd for help and gotten no response. Which ended up with some fun RP amongst the crew where someone had to fling themselves off to a nearby asteroid, only to realize they didn't actually have anything that could mine rock. 

Just because it exists as a possibility doesn't mean suddenly everyone is going to bring a pickaxe on every ship, just as they weren't before

**Comment by dvir001** [comment]
> In the same vein, I've had times where I've radio'd for help and gotten no response. Which ended up with some fun RP amongst the crew where someone had to fling themselves off to a nearby asteroid, only to realize they didn't actually have anything that could mine rock.
> 
> Just because it exists as a possibility doesn't mean suddenly everyone is going to bring a pickaxe on every ship, just as they weren't before

Power gaming.

**Comment by Wolfking6116** [comment]
Undoubtedly some of those times you called for help as a civilian ship were more than 2 months ago, and yet even then you didn't just mine it yourself then and instead chose to call for help, no? 

Power gaming happens, sure. It doesn't happen all the time, nor in the majority of cases. Even with power gaming those people who are pushing for pure and absolute efficiency aren't going to power game solely around inefficiently using ore to power their engines

**Comment by Wolfking6116** [comment]
Although I do want to say that I do still think the Raw Fuel Only generator that Darin proposed - that this PR is about - is still a cool idea and should be a thing even if it gets added back to other generators

**Comment by dvir001** [comment]
> Although I do want to say that I do still think the Raw Fuel Only generator that Darin proposed - that this PR is about - is still a cool idea and should be a thing even if it gets added back to other generators

Tier 0 generator is fine in for this case.

**Comment by Wolfking6116** [comment]
That being the JR one, or this 'Proto' thing here?

**Comment by Cheackraze** [comment]
if we go that route, then maybe it should accept urainum and plasma fuel and just use it far less efficiently as a baseline? Im fine with this either way.

**Comment by dvir001** [comment]
YAML
PrototypeID ProtoPortableGeneratorPacmanMachineCircuitboard
All machines require a Circuitboard
This means it need to be added to sci in the tech, printer, and need to have construction cost to it
Sprite can use generic boards.

Please reopen it ones it added.

**Pull request closed without merging**
