### PR TITLE
Adds the Apothecary ship.

### PR DESCRIPTION
**Pull request by dustylens**
## About the PR
Adds the Apothecary ship in addition to relevant in game guide data.

## Why / Balance
The purpose of the Apothecary is to bridge the medical gameplay loop between smaller ambulances and larger hospital ships by providing an access point for smaller crews and low pop server times.

## How to test

Take it for a spin.

Power systems checked good. Atmo systems checked good. Doors and buttons checked good. Hatches and panels checked good. All requested dev commands performed and atmo pipes colored appropriately and function when tested.

## Media

ss+(2024-07-03+at+04 13 28)

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**

:cl:
- add: Adds the Apothecary. A vessel designed to be crewed by 1-3 people to serve as a bridge between smaller ambulances and the larger hospital ships. The vessel's game play loop is meant to be proactive, providing medical support to distant ships, responding to distress and working to produce medical supplies and salvaging for missing resources.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
You still need resolve issues flagged by Map Prototype Checker. Namely remove Passenger Spawn Point

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
Buy price and sell price are too close.  Makes the ship a target for powergamers who want to just buy the ship to yoink shit and then sell it.

**Comment by MagnusCrowe** [comment]
Sadly I can't buy or spawn the ship anymore.
image

**Comment by dvir001** [comment]
``git pull origin master`` or just pull using the web on the PR

**Pull request closed without merging**
