### PR TITLE
Barge Guidebook Entry

### PR DESCRIPTION
**Pull request by Mygnol**
## About the PR
Adds guidebook entry and schematic for the Barge.

## Why / Balance
Filling in some of the missing manual entries seemed decent enough for a first PR. Picked the Barge due to it not having an active maintainer listed (or at least doesn't seem to have been worked on recently). The Hauler is done as well pending a sprite, if this goes well I'll put that up for review too.

The preflight checklist is copied and adjusted from other solar-powered vessels; do double-check my work to see if the sidenotes are correct.

## How to test
 - Go to shipyard
 - Find barge
 - Manual button now has accompanying entry

## Media

image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

If I say it won't, it will.

### CODE REVIEW

**Comment by dvir001** [comment]
No need for changelog

**Comment by Mygnol** [comment]
Goodbye changelog.

**Review by ErhardSteinhauer — APPROVED** [review]
Looks good

**Review by whatston3 — APPROVED** [review]
RSI validator passes here: https://github.com/whatston3/frontier-station-14/pull/7

**Comment by whatston3** [comment]
Will remember to squash next time.  Sorry.

**Pull request merged**
