### PR TITLE
make all cognizined mobs into free agents

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

1 line change, makes all cognizined creatures that where not a ghost role previously into a free agent.

## Why / Balance

Making a wild animal sentient should be a gamble and this will make the ghost role open to more trouble making towards the people that made them sentient.

**Changelog**
:cl: Leander
- tweak: Cognizined creatures will show more unpredictable behavior.

### CODE REVIEW

**Comment by dvir001** [comment]
To anyone who wonder what it means:

`You are a [color=yellow][bold]Free Agent[/bold][/color]. You are free to act as either an antagonist or a non-antagonist.
                                         You don't remember any of your previous life, and you don't remember anything you learned as a ghost.
                                         You are allowed to remember knowledge about the game in general, such as how to cook, how to use objects, etc.
                                         You are absolutely [color=red]NOT[/color] allowed to remember, say, the name, appearance, etc. of your previous character.`

**Comment by whatston3** [comment]
Uplifted monkey goes on killing spree, 10 dead.

We could draft a set of custom Free Agent rules if this is undesirable.

**Comment by Leander-0** [comment]
> @Leander-0 Are we ok with the "antagonist" part?

If it becomes too much of an issue it can be changed, ghost roles that get given cognizine will remain with the same non antag rules(tested), and for the ones that where not a ghost role previous that it means it would be a gamble and a risk to cognizine said wild animal which im fine with>

And about 10 people dying to the same monkey i would say it would be a skill issue.

**Comment by whatston3** [comment]
Added a line about this to the description of cognizine.  A refinement process to a friendlier version would be nice to have.  Still don't think it's a great idea.

**Comment by ErhardSteinhauer** [comment]
While I agree that giving cogni to a wild animal should be a gamble (I dread to think what my cat would do if it suddenly gained human level intelligence, probably would become prolific mass murderer tbh), but I'm fairly certain that shitters will always opt for violence because  "it's not against the rules".

**Comment by NafenX** [comment]
As someone who plays ghost roles a lot, I've always found it a bit silly how quick players are to be all like "Oh we have animals, let's make them all sentient/sapient!" and then when they do inject the cogni they expect full cooperation. I'm not on the shitter side where I'd always resort to violence, but it would be nice to have that bit of leeway so that you can RP as a creature that is conflicted due to suddenly gaining potentially a lot more intelligence than they what had, and the ability to speak to the regular people around them. 

Cogni right now, a lot of the time, is more of a tool for "We want you to be able to give us the information we need, and we want the ability to order you around and make use of you!" and less "We care about you as a pet and want to be able to chat with you and have you communicate your needs and desires" or, hell, even "We're scientists and our hubris is leading us to do potentially dangerous things!"

I've been pretty disappointed with how most people who do Science roleplay it. I find that hardly any people working on science capable ships treat the role of scientist as someone who is dedicated to a life of study, and that each breakthrough is utterly fascinating to them. Sure, because of the shift by shift nature of the game and the fact that prior shifts sort of form a canonical series, it's hard to really be excited when you unlock a certain research for the hundredth time, but I wish people would treat things with a little more of a flair of a scientist and not just a money maker. WELP this last paragraph is more another whole thing entirely, but I do hope that changing the rules for cogni'd creatures will be one step towards making scientific play more varied.

**Pull request merged**
