### PR TITLE
Honker Update

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Updated Barge:
- Added atmos setup, mapped emergency lights.

## Why / Balance
To curb CO2 build up.

## Technical details
.yml changes

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Tweaked Honker - added atmos setup.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
Is there a passive vent underneath the top right thruster for waste egress?

Rest looks good to me.

**Comment by ErhardSteinhauer** [comment]
Aye, passive vent is under thruster.

**Comment by TsjipTsjip** [comment]
This feels.... very very cursed to the point that I would go as far as to ask for it to be moved, as I do not think it is possible in-game to re-anchor the thruster on top of it if you unanchor it.

**Comment by ErhardSteinhauer** [comment]
I'll check if it prevents anchoring thruster.
Also clown ship is cursed as a concept in general.

**Comment by TsjipTsjip** [comment]
Fair, I was just told it works by @dvir001 , so this looks fine. There's a clown PDA in the locker that was not added in this PR that should be removed (because it gives an ID card), and the nitrous oxide should also probably be removed. Could you roll that into this PR? Rest looks good to me.

**Comment by ErhardSteinhauer** [comment]
> Fair, I was just told it works by @dvir001 , so this looks fine. There's a clown PDA in the locker that was not added in this PR that should be removed (because it gives an ID card), and the nitrous oxide should also probably be removed. Could you roll that into this PR? Rest looks good to me.

Actually I believe all (like all 5) of those lockers are custom. Do we have clown-specific lockers/vendors? I don't have nearly enough hours as clown to know what one needs for power clowning.

**Comment by dvir001** [comment]
> > Fair, I was just told it works by @dvir001 , so this looks fine. There's a clown PDA in the locker that was not added in this PR that should be removed (because it gives an ID card), and the nitrous oxide should also probably be removed. Could you roll that into this PR? Rest looks good to me.
> 
> Actually I believe all (like all 5) of those lockers are custom. Do we have clown-specific lockers/vendors? I don't have nearly enough hours as clown to know what one needs for power clowning.

Clown lockers were added from upstream but were missing this update for now,
The lockers are ok for now but need just the pda removed.

Cloth vender (Generic) will have clown gear on it soon, so you can add it.

**Comment by ErhardSteinhauer** [comment]
Removed PDA, replaced one locker with AutoDrobe

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
