### PR TITLE
Empress 3.2 update

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Just do a little more finishing touches and decals to the empress and changing everything to the NFSD prototypes.

:cl: Leander
- tweak: Empress got a new coat of paint

### CODE REVIEW

**Comment by VividPups** [comment]
I would like to note here, that the Pistol racks can be access from outside the armory, and the Weapon racks locks are broken 
as in they do not lock when you lock them

**Comment by dvir001** [comment]
> I would like to note here, that the Pistol racks can be access from outside the armory, and the Weapon racks locks are broken as in they do not lock when you lock them

Also on the same note he should use the sec ones that are sec locked, and we need to add NFSD ones to replace them later (Can just yaml swap it after)

**Comment by dvir001** [comment]
Update with master and test again

**Comment by Leander-0** [comment]
yeah no, it no longer loads and its all broken, gonna nuke this and do the changes again all over.

**Comment by dvir001** [comment]
> yeah no, it no longer loads and its all broken, gonna nuke this and do the changes again all over.

No need to nuke, just yaml edit NFSD to Nfsd
And nfsd to also Nfsd in yml

**Pull request closed without merging**
