### PR TITLE
USS Mayflower Bug Fixs

### PR DESCRIPTION
**Pull request by VividPups**
## About the PR
Fix the Locker Problems that I was told about but couldn't see on my end. Until after Players during a round showed me what MagnusCrowe experiencing. Also, remove the 45 ammo and speedloaders that I accidentally left.

## Why / Balance 
Couldn't open Wall lockers. Change to standard lockers and 45 ammo wasn't posted to be on the final edition 

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes in-game

**Changelog**
:cl:
- tweak: Mayflower - Replaced wall-mounted lockers of the Merc and Prisoner with regular ones, removed loose .45 cal ammo and speedloaders.

### CODE REVIEW

**Comment by Cheackraze** [comment]
looks good, but in your change log, be sure you are specifying that those changes are being done to this specific ship. It would be confusing and pretty much incorrect to players reading the changelog.

**Comment by VividPups** [comment]
I clarify it now in the changelog part

**Comment by dvir001** [comment]
Made changes to keep with guidelines with tsjiptsjip approving it live on stream.

**Review by dvir001 — APPROVED** [review]

**Review by TsjipTsjip — APPROVED** [review]
Changes at current state are sane.

**Comment by VividPups** [comment]
Why are you changing the Name template?

**Comment by TsjipTsjip** [comment]
> Why are you changing the Name template?

USS makes the name on radar scans too long. No other ships have this either.

**Comment by VividPups** [comment]
That doesn't make sense. SIL,  KC and all the other ships have Name templates like that

**Comment by TsjipTsjip** [comment]
> That doesn't make sense. SIL, KC and all the other ships have Name templates like that

Correct, and this change does not touch that at all. Map name template is used for the name a ship gets on radar, not in the shipyard.

**Comment by VividPups** [comment]
Yes thats the point. The Orginal Mayflower name is The HMS Mayflower. Which was use during the actual time of the Mayflower. I Change it to USS because of how significant that was in American history. Removing that is removing part of the value and understanding of the name

**Comment by dvir001** [comment]
> That doesn't make sense. SIL, KC and all the other ships have Name templates like that

Please find me a template that also have the radar line with the prefix and ill go and fix it.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
