### PR TITLE
NT Legman: A Microshuttle for Reporters

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Compact, fast, and reliable (most likely) micro shuttle (63 tiles) with low operational costs for reporters who want to be first on a scene. Ideal for journalists with a tight budget - the shuttle price is only 12499 spesos.

## Why / Balance
- It's hard to make money working as a reporter, so a low price tag with the low operational cost of this shuttle can make the reporter role more attractive.
- Micro shuttle. The more the merrier. Maybe?

## Media
NT Legman
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: NT Legman - a maneuverable microshuttle with low operational costs for reporters who want to be first on a scene.

### CODE REVIEW

**Review by dvir001 — CHANGES_REQUESTED** [review]

**Comment by dvir001** [comment]
Remove the wireless camera server, there is an infinite range one on the pit, there is no need for more then one in the world.

**Comment by ErhardSteinhauer** [comment]
Is it ok to keep Shuttle APUs for power generation needs or it'll be better to put PACKMAN?

**Comment by dvir001** [comment]
> Is it ok to keep Shuttle APUs for power generation needs or it'll be better to put PACKMAN?

Didnt even notice it, best to replace it with a generator, yes.
Im going to replace all APUs in small service ships soon also with new types based on ship functions.

**Comment by ErhardSteinhauer** [comment]
Ok, I'll ditch the server and APUs and put PACKMAN.

**Comment by ErhardSteinhauer** [comment]
- Removed Server and Shuttle APUs;
- Mapped PACKMAN, plasma sheets and wrench;
- Moved APC and Substation;
- Adjusted price tag (gone up by 1k from previous value, so it's 13500 now);

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
