### PR TITLE
2023 12 24 food price fix

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Food price 210

## Why / Balance
Market worth

## Technical details
.yml

## Media
N/A

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: Junk food price adjust to inflation.

### CODE REVIEW

**Comment by dvir001** [comment]
Wtf was going with my code to fuck this merge list holy hell

**Comment by FoxxoTrystan** [comment]
The economy... noooo the prices!

**Comment by Estataa** [comment]
Sobbing, first thing done immediately after the announcement is raising food prices. how am i supposed to feed my family now.

**Comment by dvir001** [comment]
> Sobbing, first thing done immediately after the announcement is raising food prices. how am i supposed to feed my family now.

Ill be honest with you the prices were bugged all along at the actual price was 275
You actually paying less now, think im joking? go buy snacks now and see how much the actual price is.

**Review by Cheackraze — APPROVED** [review]

**Comment by MagnusCrowe** [comment]
> Sobbing, first thing done immediately after the announcement is raising food prices. how am i supposed to feed my family now.

Donner party.

**Pull request merged**
