### PR TITLE
Partycrate Birthday Cake Balancing

### PR DESCRIPTION
**Pull request by Houtblokje**
## About the PR

<s>Replaced the party cake in the party crate with a "store-bought" variant, where eating the whole cake is about equivalent to eating a single donut.</s>
Changed the contents of the party crate, to remove the cake and make it feel more fun.
Also changed the contents of the crate according to @whatston3 's feedback.

## Why / Balance

People would abuse the party crate by buying it only for the cake, because it had flavorol in it. This PR deletes it from the crate and changes the crate to be more unique.
## How to test

Buy a party crate.
See that the cake is no longer in it.
There is now a procedure on how to have a good party in it.

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Should not be any.

**Changelog**

:cl:
- tweak: the partycrate is now more expensive and its contents have been changed.

### CODE REVIEW

**Comment by whatston3** [comment]
Compromise?

Let's take over the party crate.  How many people is it suitable for? 4?
Make it more expensive, say, 7500 spesos (~2000 per guest?), 1 glow stick and hat per guest, make the "grape juice" actually grape juice (we have lean, yes, but this seems more childish).

Suggestions up at [whatston3:BirthdayCake-Partycrate-Update-suggestions (GitHub)](https://github.com/Houtblokje/frontier-station-14/compare/BirthdayCake-Partycrate-Update...whatston3:frontier-station-14:BirthdayCake-Partycrate-Update-suggestions?expand=1) for your perusal.

**Comment by Houtblokje** [comment]
> Compromise?
> 
> Let's take over the party crate. How many people is it suitable for? 4? Make it more expensive, say, 7500 spesos (~2000 per guest?), 1 glow stick and hat per guest, make the "grape juice" actually grape juice (we have lean, yes, but this seems more childish).
> 
> Suggestions up at [whatston3:BirthdayCake-Partycrate-Update-suggestions (GitHub)](https://github.com/Houtblokje/frontier-station-14/compare/BirthdayCake-Partycrate-Update...whatston3:frontier-station-14:BirthdayCake-Partycrate-Update-suggestions?expand=1) for your perusal.

So we change the party crate so its for 4 people, make the grape juice actual grape juice and keep the party cake changes? yeah that sounds fine to me. I do think 7500 could be a bit too expensive though, especially when the cake basically gives no food so you are just paying 7.5k for some cosmetic items. I think 4.5k or 5k would be a sufficient pricing for this crate, but what are your thoughts?
Also, the cake gives 5 slices of cake i think, so it would be for 5 people?

**Comment by dvir001** [comment]
No food in cargo please, even if it's that amount

**Comment by Houtblokje** [comment]
> No food in cargo please, even if it's that amount

I have removed the cake from the crate and I have instead added a cake recipe note (for flavour).

**Comment by whatston3** [comment]
Here's another suggestion, curious of your thoughts.

https://github.com/Houtblokje/frontier-station-14/compare/BirthdayCake-Partycrate-Update...whatston3:BirthdayCake-Partycrate-Update-suggestions?expand=1

Restores the base party crate to how it was - unpurchaseable, but with default resources (could still be pared down, but just a starting position).  I replaced the cake recipe with my best quick go at a crushing corporate party guide (referring to the guidebook in case any poor soul reads it, but it is close to the top).  Reduced the price of the thing to 1500, and left the inventory of the new crate more or less unchanged.

**Comment by Houtblokje** [comment]
> Here's another suggestion, curious of your thoughts.
> 
> https://github.com/Houtblokje/frontier-station-14/compare/BirthdayCake-Partycrate-Update...whatston3:BirthdayCake-Partycrate-Update-suggestions?expand=1
> 
> Restores the base party crate to how it was - unpurchaseable, but with default resources (could still be pared down, but just a starting position). I replaced the cake recipe with my best quick go at a crushing corporate party guide (referring to the guidebook in case any poor soul reads it, but it is close to the top). Reduced the price of the thing to 1500, and left the inventory of the new crate more or less unchanged.

Looks pretty good. I have added a long disclaimer to the end of the guide (as Nanotrasen would have done that), I have added a microphone for the karaoke vibes and I upped the price to compensate for the inclusion of the microphone instrument.

**Review by whatston3 — APPROVED** [review]
Pushed a change to set the price to 3000, mic's already 2k in the autotunevend (200 static price, 10x static modifier).  Added a line break to the doc.  Fun idea, seems fine by me.

**Comment by Houtblokje** [comment]
> Pushed a change to set the price to 3000, mic's already 2k in the autotunevend (200 static price, 10x static modifier). Added a line break to the doc. Fun idea, seems fine by me.

Yeah that seems fine to me, I wasn't really sure what to price it at.

**Comment by dvir001** [comment]
If I get a syndicate pen we have an issue with this one

image

**Comment by Houtblokje** [comment]
> If I get a syndicate pen we have an issue with this one
> 
> image

image
Is this an acceptable change for you?

**Pull request merged**
