### PR TITLE
Change type from int32 to uint64 for bank

### PR DESCRIPTION
**Pull request by user424242420**
Fix possible bug. If bank account will get more than 2^31, games crash. I did migration from int to ulong
https://github.com/new-frontiers-14/frontier-station-14/pull/1355
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Increase amount of money that you can have

### CODE REVIEW

**Comment by dvir001** [comment]
Ignore the failed tests for now as its a different issue.

**Comment by user424242420** [comment]
I got it https://github.com/new-frontiers-14/frontier-station-14/commit/716aa35e01af83394e54ce173aff68180eb32873

**Comment by dvir001** [comment]
> I got it [716aa35](https://github.com/new-frontiers-14/frontier-station-14/commit/716aa35e01af83394e54ce173aff68180eb32873)

I think we need to update something else also, I didnt look into it yet as I dont have the time right now.

**Comment by user424242420** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1363

**Pull request closed without merging**
