### PR TITLE
Ambition compliance pass

### PR DESCRIPTION
**Pull request by blackknight954**
Remade to resolve some issues I was having with my repos

## About the PR
Added the following to the Ambition:

Directional fans in place of tiny fans
Oxygen/Nitrogen distribution in place of an air mix
a fully connected air distro in place of the seperate two distro network
AME fuel locker in place of the two AME fuel juggs
A sink as a source of water in the janitor area

## Why / Balance
Compliance pass on the Ambition, adding a water source.

## How to test
Load up a local server,
Spawn an Ambition,
Find the new changes.

## Media
image
image
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None that I can think of
**Changelog**
:cl:
Tweak: modified aspects of the Ambition to comply with ship guidelines.

### CODE REVIEW

**Comment by MWGMorningwood** [comment]
> Why is distro in storage when there are perfectly good holding tanks? it would even fit in the bow docking area honestly.

With the new atmos changes requiring you to delve into Tritium and Frezon, these tanks will probably be ripped apart more than used separately. In my latest run, I felt the need to merge them all into large tanks for bulk storage. This made finding a spot for distro gasses to live a little tricky. I ended up making a can-based supply method to save space, which is basically what this is proposing.

**Comment by blackknight954** [comment]
> Why is distro in storage when there are perfectly good holding tanks? it would even fit in the bow docking area honestly.

Having a distributor in an air tank would restrict modifications yeah, those tanks are merged into two bigger ones a lot

**Comment by Cheackraze** [comment]
To be completely honest, with the upcoming atmos mining changes and cross-grid gas transfer, I will likely personally re-work both of the atmos focused ships to come mostly-prebuilt to interact with the new gas mining mechanic, which likely means re-piping them entirely.

**Comment by MWGMorningwood** [comment]
> To be completely honest, with the upcoming atmos mining changes and cross-grid gas transfer, I will likely personally re-work both of the atmos focused ships to come mostly-prebuilt to interact with the new gas mining mechanic, which likely means re-piping them entirely.

Agreed, but directional fans, AME locker, and sink are still nice to get now

**Comment by blackknight954** [comment]
> To be completely honest, with the upcoming atmos mining changes and cross-grid gas transfer, I will likely personally re-work both of the atmos focused ships to come mostly-prebuilt to interact with the new gas mining mechanic, which likely means re-piping them entirely.

Fine by me.

**Comment by blackknight954** [comment]
@arimah Changes are finished.

**Review by arimah — APPROVED** [review]
Lovely! Thank you, @blackknight954!

**Pull request merged**
