### PR TITLE
SBB Hammer (New): Medium engineering shuttle

### PR DESCRIPTION
**Pull request by arimah**
## About the PR
Adds a new medium-size engineering shuttle, the SBB Hammer. This ship is a smallish single-person engineering platform intended to provide repairs to those who need them and machines to those who want them. I imagine (and hope) that engineering work will be more lucrative as ship-to-ship combat becomes increasibly common.

This ship is made by BlueBird Starship Design & Construction.

## Why / Balance
Some design considerations:

* The ship has absolutely no mining equipment. It's an engineering vessel. If you want materials, either pay extra for the ore processor or, preferably, talk to people. To help the aspiring engineer get started, there is a materials crate and a bulk cable crate.
* ~~The main engineering bay is spaced. This ~~open-air~~ open-space design is more of a gimmick than a strict necessity – I'm happy to introduce blast doors over the opening at the front if requested – but I'm very fond of it and hope I get to keep it. In testing the shuttle, I did not find the open front was prone to catching dangerous fauna.~~ Changed, N/A.
* The wide open and empty-looking floor surface is totally intentional: An engineering shuttle needs somewhere to place down machine and computer frames during construction.
* A flatpacker is included to simplify multi-machine deliveries.
* The ship comes with a CE locker and CE hardsuit. Though CE stuff is usually reserved for larger vessels, the normal engineering hardsuit slowdown is _so painful_ compared everything else. Considering you're likely to be fixing ~~science ships that have blown up~~ spaced ships, that mobility is kinda crucial.
* The shuttle comes with oxygen and nitrogen canisters so you can keep breathing for longer regardless of species. There is also handy gas tank dispenser to help further.
* Despite not being atmos-focused, you get the world's tiniest mixing setup and an extra air canister to help repressurise whatever you're fixing.
* Since the entire ship is engineering-focused, the engine room uses a regular maintenance access, and the engineering door instead leads to the indoors workshop.
* Advanced industrial welders are not hard to find on space wrecks, and engineers do a LOT of welding, so I put one in the indoors workshop. I would prefer not to remove it, as the regular welding tool is kinda garbage.
* Secret tiny storage area access through a secret door, so you can hide ~~the emag you liberated your protolathe with~~ whatever you fancy.
* The ship consumes a downright annoying 15115 W. I edited the YAML file so the generator starts at 16 kW (94.1% efficiency). It's not ideal, but if you buy an engineering shuttle, you can figure out how to improve the situation with no issue. Hell, you can even use your engineering techfab to make a SUPERPACMAN.
* Correct lateral lights.

**Statistics & info:**

* **Tile count:** 205 (small), but 17 tiles wide so technically medium
* **Appraisal price:** just over 28,000
* **Shipyard price:** 31,500, ~13% markup
* **Recommended crew:** 1–2

## How to test
Spawn in and buy it. :)

## Media
Preinit, with subfloor and spawners:
image_2024-07-05_22-11-14

Postinit:
image_2024-07-05_22-11-14 (2)

Rotated blast doors are intentional, to make for a cleaner appearance when open:
image_2024-07-05_22-11-14 (3)

Location of secret door:
image

Guidebook page (rest is standard stuff):
image_2024-07-05_14-41-58

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Nopers.

**Changelog**
:cl:
- add: Added the SBB Hammer, a medium-sized engineering shuttle.

### CODE REVIEW

**Comment by dvir001** [comment]
Please replace air tank to a O2 + N2 mix for vox support.

**Comment by arimah** [comment]
> Please replace air tank to a O2 + N2 mix for vox support.

I'm not saying I won't do it, but in practice, how will that help? `fixgridatmos` will fill the entire ship with standard air, there's no quick way to vent all the starting air, and you'd need _way_ more than a single N2 tank to refill a ship bigger than a Pioneer to a safe pressure. Do you expect vox players will habitually replace the atmosphere on their ships? 🤔

**Comment by ErhardSteinhauer** [comment]
They can at least refill their N2 tanks from canister.

**Comment by arimah** [comment]
The ship already has an N2 canister (and one O2) mapped for this very reason! Also for slime people.

**Comment by dvir001** [comment]
> > Please replace air tank to a O2 + N2 mix for vox support.
> 
> I'm not saying I won't do it, but in practice, how will that help? `fixgridatmos` will fill the entire ship with standard air, there's no quick way to vent all the starting air, and you'd need _way_ more than a single N2 tank to refill a ship bigger than a Pioneer to a safe pressure. Do you expect vox players will habitually replace the atmosphere on their ships? 🤔

It was about filling canisters but its fine since they can fill from the side one

**Comment by arimah** [comment]
Okay, so, after a bit more testing and feedback, despite kinda liking the spaced workshop area, I decided to give it a proper atmosphere even before receiving any feedback on it. The code, PR description and screenshots have been updated accordingly. I've also added air alarms, which I forgor the first time around despite going through the ship submission guidelines about forty times.

**Comment by arimah** [comment]
> I hate that you put the blast doors sideways AND that I DONT hate it.

I can't tell if you're asking me to change it or not 🤔 Personally I prefer how it looks, especially when open. You get one continuous hazard line instead of a whole bunch of vertical ones!

**Review by MagnusCrowe — APPROVED** [review]
Hope this clears things up for you.

**Pull request merged**
