### PR TITLE
Fix power monitoring console dependencies

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Retrieves the TransformSystem in the power monitor through the EntityManager rather than through the IoC manager.

## Why / Balance

Throws exceptions.

## How to test

1. Spawn on Frontier.
2. Enter the bridge.
3. Use the power monitor console.
4. It should pop up.

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: The power monitoring console should work correctly.

### CODE REVIEW

**Comment by dvir001** [comment]
Is this upstream issue or ours?
Also was this fixed on upstream?

**Comment by whatston3** [comment]
> Is this upstream issue or ours? Also was this fixed on upstream?

Ours (mine), no.

**Review by dvir001 — APPROVED** [review]
Fair

**Comment by whatston3** [comment]
Might be able to remove the MapCoordinates from the NavMapBlip and reference the TransformSystem to convert them to world coords in the crew monitor to avoid changing that blip.  Something for later at any rate.

**Pull request merged**
