### PR TITLE
Edison Power POI

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

This is just a new POI with a bit of puzzle with a handful of circuitboards, and a TEG. This is step one to introduce the "Matter Compressor" (name still work in progress) which may or may not make AME fuel, RCD ammo, and maybe some other shipyard-focused things out of pure energy.

This is a part of a larger project to implement more engineering focused gameplay. Original draft proposal below:

With the player market recently added, our overall goals to make most gameplay-important items include providing a source for AME fuel, and this finally provides us with an opportunity to start making some engineering gameplay on Frontier. Before this, engineering specific gameplay was minimal at best, with basically just some advanced atmos gameplay that isnt all that enjoyable.

There also hasnt been a need to harnass the various larger power engine options, which we can also incorporate into the machine as a massive power requirement to create the fuel.  The machine itself will turn raw energy (in excess of 200-300kw of power to start, up to 1-4MW of power consumption) and a bit of steel, into AME jars at least 1 byproduct, possibly 2. The first planned byproduct is a hazardous gas output, Tritium, that will have to be piped and handled sufficiently to not clog the machine. The faster an engineer tries to make the machine work, the more tritium 'waste' will be output, and likely higher temps. While this could, in theory, be discarded, it also provides a potential avenue for either direct profit through capture, cooling, and selling, or it could potentially be used within the TEG loop to synthesize more efficient coolant (frezon), or to make for a more intense burn mixture, or both, depending on how much oxygen they are able to obtain (likely will not have any gas miners in the final version be warned).

This is only supposed to be the first step, albeit likely the most routine and important one, for introducing engineering type game loops into frontier. There have also been some good ideas for some additional optional activities engineers can participate in to occupy any downtime once they get the engines fine-tuned to their preferences.
## Why / Balance

Engineering game play and 
## How to test

Load the map, warp to the power plant, look around.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Cheackraze** [comment]
Ready for review, but i'm headed out the door soon so I'll have to provide screenshots later.

**Comment by dvir001** [comment]
Keep in mind we moved all warp points and fax protos to be .yml based so forks can translate them, should be an easy yml swap on our side.

**Comment by Cheackraze** [comment]
It has a warp point but no fax machine. A lot of the machines and stuff are
placeholder until we get more engi stuff

**Comment by whatston3** [comment]
Prototypes/_NF/PointsOfInterest/edison.yml:
26-34: If this is a spawnable station, consider making the jobs into overflow jobs (i.e. tuples of `[-1, -1]`), and adding some ships to the shipyard console (maybe an engineering-specific console with a restricted ship listing and maybe a transit ship included if things don't work out?) and a FuelVend (possible issues with an infinite, but expensive[??] supply of welding fuel?).  If not, inherit from StandardFrontierOutpost.

Maps/_NF/POI/edison.yml:
* L19705: Not LockerWallMaterialsFuelWeldingFilled?  As far as I can tell, there's no actual mapped source of welding fuel at all on the station, which seems a bit odd considering it's an engineering POI.  400u shouldn't be too bad anyways.
* No transit docks, no StationTransit component?
* Curious, what's the reason to have a big atrium area?

Apart from the questions above, looks good on the first pass, will give this a more thorough look over when I can.

**Comment by Cheackraze** [comment]
Its missing some of those things like station transit, round-start spawns, and actual shipyards because its not intended to be start point until theres actual engineering gameplay implemented. Until then its just a blank slate where people can hire through if need be.

Welding fuel was just a bit of an oversight and can be added. The atrium area is where the matter compressor will live eventually, with the space around it intended for possible pipes in the future. The singularity area and the supermatter area are a bit placeholder as well, pending code porting/singularity rewriting.

**Comment by dvir001** [comment]
Fixups all around the place,
Made it no spawn for now, just need to restore the POI file when we want.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
