### PR TITLE
Add wheelchair accessible ramps

### PR DESCRIPTION
**Pull request by MoistBiscuits**
## About the PR

Dvir brought it to my attention that the Skipper was not wheelchair accesible; the frontier is for all pioneers!
Adds ramps and replaces the stairs on the Skipper with ramps

## Why / Balance

Wheelchair users need every buff they can get, we cannot deny them access to our fine service shuttles, what if they trip on the stairs and get a boo boo?

## How to test

Use the entity spawner to map the new ramp prototype

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The NC Skipper has been fitted with new wheelchair accessible ramps

### CODE REVIEW

**Comment by dvir001** [comment]
Use _NF folders please

**Comment by MagnusCrowe** [comment]
Doesn't look much like a ramp to me... 🤔

**Comment by MoistBiscuits** [comment]
Spriting a ramp was way harder than I thought it would be, I'll see if anyone on the discord can have a try at it.

**Comment by MoistBiscuits** [comment]
Putting this back on draft to whip up a different ramp sprite.

**Comment by ErhardSteinhauer** [comment]
Closing this PR for lack of activity. Feel free to reopen it if you get back to working on it.

**Pull request closed without merging**
