### PR TITLE
Remove rewards from expeditions

### PR DESCRIPTION
**Pull request by GreaseMonk**
## About the PR

We need to revisit the loot pools to make sure we have unique items in them that can be obtained without making sci obsolete.
I'm opening this PR so we can merge it either now or in pair with another change.

Linked pr: https://github.com/new-frontiers-14/frontier-station-14/pull/2386

## Why / Balance

Expeditions need to go back to fun items on them, not a first order profit, separate the idea of expedition = money. thus remove the money rewards altogether.  You need to sell the fun items you get to players like they used to be.

## How to test

Check expedition console , rewards should no longer be listed.

**Changelog**

:cl:
- remove: Removed expedition rewards

### CODE REVIEW

**Comment by dvir001** [comment]
Ideal we might want to cvar this for forks.

**Comment by DoomAngelBlade** [comment]
So what is purpose of Expeds then?

Just a much worse alternative to salvage?

**Comment by GreaseMonk** [comment]
> So what is purpose of Expeds then?
> 
> Just a much worse alternative to salvage?

Honest, adding hard rewards like spesos or the crates how it used to be, was a mistake.

Expeditions is supposed to be a more difficult group activity with better rewards in de map itself the higher the difficulty-, whereas salvaging in the main map is the solo activity of it.

**Review by ErhardSteinhauer — COMMENTED** [review]
I am going to approve this PR once I finish testing it.

As someone who introduced this change I don't think it was a mistake, but I do agree that it should be removed. The reasons why I made those changes a while ago:
- to incentivize trade between players by giving out more cash (you need cash on hands to buy stuff from other players, flying to the nearest ATM hinders the process - not every shuttle is equipped with ATM);
- encourage captains to hire more crew for harder expeditions since with cash rewards captains could plan their budget better.

Non of that worked the way I though it would. An argument could be made that it might've the opposite effect.

**Review by ErhardSteinhauer — APPROVED** [review]
Works well, no errors and no cash upon completion of expeds.

**Comment by DoomAngelBlade** [comment]
Buff exped loot?
You can get a ship and go salvage mats from wrecks. This gives much more cash RIGHT NOW.
Expeds give alot of items that have their value in trading with other people but. . . Not many people do trading/like to trade.

**Comment by ErhardSteinhauer** [comment]
> Buff exped loot?
Eventually. Exped loot tables do require a rework.

**Comment by DoomAngelBlade** [comment]
> Eventually. Exped loot tables do require a rework.
Then don't nerf the expeds to the ground until it's done?
By nerfing expeds - players have no monetary incentive to do them.
It becomes a mechanic. . . that's useless?

**Comment by ErhardSteinhauer** [comment]
> Then don't nerf the expeds to the ground until it's done?

You still can earn roughly 40k per run without too much effort on maps with scarce loot. And if you start dismantling machines you can add about 5k-10k to that. On maps with more loot, numbers get closer to 100k per run. With running expeditions back to back, you'll get 100k-300k. Hardly a "nerfed to the ground" type of deal.

**Comment by DoomAngelBlade** [comment]
> > Then don't nerf the expeds to the ground until it's done?
> 
> You still can earn roughly 40k per run without too much effort on maps with scarce loot. And if you start dismantling machines you can add about 5k-10k to that. On maps with more loot, numbers get closer to 100k per run. With running expeditions back to back, you'll get 100k-300k. Hardly a "nerfed to the ground" type of deal.

Explain to me how the heck can you get 300k?
Espec. as solo.

**Comment by ErhardSteinhauer** [comment]
Pick higher difficulty with humanoid mobs (preferably with explorers), get lucky with map (salvage outpost is loot heavy map tend to spawn more often on cave and shadow), loot. 300k per hour is possible, but it absolutely **is** a higher end of what is possible.

> Espec. as solo.

How about no? Expeditions are not intended to be a solo experience.

**Comment by DoomAngelBlade** [comment]
> Pick higher difficulty

20%

> with humanoid mobs

Xenos,Dinos,Explo,syndie,punks,mercs,AI,Flesh,Cult, other creatures that arent' dinos.
So 5 Humanoid, 5 non humanoid.
50%

>lucky with map 

Let's say it's 50% chance to get the base you need

> How about no? Expeditions are no  solo experience.

Let's say team is of 2 peeps.

So odds are 1/2*1/2*1/5 = 5% to get a good map?
Exped is 15 mins + 5 min for prep.
3 consecutive hits on lucky map with lucky stuff to get 150k per hour for a guy.
100k if it's 3 peeps.

The highs are highs, and if you're real lucky - spessos will pour on you from the skies.
But what are averages?
I know for sure I can mine 500k from a rock as solo.
Espec. if it rolls like 25 diamonds and 25 bluespace crystals.
How lucky do I get with that? Rarely. 
Is it valid to consider it as a high of mining? Yeah.
Is it valid to consider it as a norm of income? Heck no.

**Comment by ErhardSteinhauer** [comment]
Well, don't go to expeds then? Perfectly reasonable solution if you're here only for grinding money. Damn, print some tech disks, pays better than mining.

Even with this nerf, you're still getting net positive on cash (if you survive), and have a PvE entertainment.

**Comment by chrome-cirrus** [comment]
So, I don't disagree with removing cash rewards. I do disagree with removing cash rewards before adding the things that would replace those rewards. Nerf-first feels bad, and depending on how the winds blow with people involved in the project, other priorities coming up, and so on, often becomes nerf-only for months or more. Not saying that's you in particular here, but it's a thing that happens often enough in this ecosystem. Just wishing the norm could be the order of operations that doesn't frequently leave people feeling hard done by changes.

**Comment by Cheackraze** [comment]
Expeds were never ever supposed to be pure money making ventures, and changing the rewards to spesos was a massive mistake on our part. The entire intent was that expeds gave you _items_, which you then traded for/sold. This is bringing it back in line to where it should have been all along, and is perfectly fine without any accompanying "buffs" since it's correcting a design choice mistake in the first place.

But don't fret! We did in fact already add replacements, the vgroids. So now that the replacement was added _**first**_, it's perfectly acceptable now to change this back to where it should have been all along.

**Comment by chrome-cirrus** [comment]
I mean... vgroids aren't exactly, "...revisit the loot pools to make sure we have unique items in them that can be obtained without making sci obsolete." That was what I was referring to with my comment. Whatever though, the maintainer consensus is clear, discussing it further is going to lead nowhere satisfying.

**Comment by DoomAngelBlade** [comment]
>replacements

Why do we have expeds then?
Why not double amount of VGroids and jsust straight up remove expeds?

> then traded for/sold

Trading is . .  hard in this game.
This is offtopic, yes, but . . .
There's no saving your ship / progress.
Thatere's mandatory reset each 6 hours.
Not everyone is capable of playing 6 hours straight to max the results of what they want.
Or just optimize.
Heck, getting  some upgrades from SCI is nearly impossible unless you do it yourself or in a predetermined team.

I started doing those VGroids and had ATGs, industrial ore processors and bluespace parts for sale, radio'd it for hour. 0 Purchases. 
There's nearly noone doing sci.
Heck, getting FOOD is nearly impossible - your best best is just go find Nul on Bahmama or find memory leeks/kitchen closet on salvage to feed yourself. Or just go to TO /Bahamas and buy variant cubes/monkey cubes.

At this point the trading part is usless because no proper incentives + factors that push you away from investing in something ... thatll be removed in hour or two after you bought it.

**Comment by dvir001** [comment]
Moving back to ``Status: Need Discussion`` for a while.

**Comment by Limesly** [comment]
> There's a few problems here but the clearest and probably easiest to solve is the lack of means to communicate trades. A bounty system exists already, it could be duplicated/altered to work as a marketplace for trade offers.
> 
> Now even a global market exists in form of buying sold materials, but that has such a steep markup for a buyer that it's a joke compared to just mining/salvaging yourself. It's also severely limited in what can be bought, as far as I know it's only materials, ores and seeds. This market system could be expanded to offer more player products, like better science parts, medicine, guns, ammo, techboards, blueprints, you get the idea. It needs to be competitively priced to be usable, as it's currently not with inflated prices.
> 
> I know player interaction is a big thing that should be encouraged, but there's only so much time players have in a round and spamming chat messages about trade offers, then flying through empty space to meet for 5 seconds is not enticing. Especially when the time could be spent doing actually fun things like doing everything yourself.

 I agree with Jimmy (on basically everything in this original message), the level of communication needed in several parts of this game is way too much for just Radios to handle, and absolutely needs to be supplemented with some kind of in game communication board, like an pda app or a console - easily accessible, and could look like a forum or like the wanted system GUI for sec officers.
(complete tangent, but hiring crew via the crew console also needs information, players joining the round right onto a ship need to have some way of knowing what they're getting in to, and Captains need to be able to clarify what they want from crew before they join.)

Another tangent - 20 m/s is only ~45 miles/hr or 72 km/hr. So very slow... which obviously makes player interactions harder to attain, as all interactions require closing the space. A little speed is definitely one way to endorse player interaction - I think, by lowering the real-world time cost to meet those people.

**Comment by DoomAngelBlade** [comment]
IMO - keep rewards.
There's no need to make or care about perfect balance right now.
There are much more lucrative ways for a player to earn money, gutting Expeds right now is no good.
Revert cooldown.

Gut them when/if
a) Trade is at better state
b) Loot is more specialized depending from enemy type/difficulty
c)A way is found to earn alot money per hour this way.
d)Saves between shifts of equipment/ships/anything is implemented(never, lol)

**Comment by noldevin** [comment]
I agree with what i think the overall sentiment will be, don't remove the cash until the loot is adjusted to compensate. Expeditions are basically one of the only ways you can permadie with no hope of recovery. They should be very rewarding to make up for that. If the cash is removed before the loot is adjusted I think you will see very few people running expeditions.

**Comment by DoomAngelBlade** [comment]
Why?

**Comment by Cheackraze** [comment]
> Why?

https://github.com/new-frontiers-14/frontier-station-14/pull/2385#issuecomment-2466910465

**Comment by DoomAngelBlade** [comment]
Expeds now: 
Get in, and die for gestio. 
Die permanently. Great choice of balancing. 
Expeds were dead cause of time nerf. Now they are dead for no reason of doing them. . . At all.

**Pull request merged**
