### PR TITLE
Fix to NPCs not targeting Ripleys and Turrets

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### Main changes:
- Added `MobState` component to `BaseMech` that'll allow NPCs to target mechs.
- Added destruction thresholds for mechs, so they can be destroyed beyond repair.
- Added `MobState` component to `BaseWeaponTurret` that'll allow NPCs to target turrets.

### Bundled changes:
- Fixed solution transfer for syndicate darts.
- Enabled `MovementIgnoreGravity` for hostile NPCs to aid AI in space (might make it harder to cheese AI by tricking them into jumping off the grid).

## Why / Balance
Bug fix

## How to test
Spawn turret and NPCs from different ai faction (xeno-syndie, for example) in close proximity, spawn mech and syndie agent.

## Media
- [x] This PR does not require an ingame showcase

## Breaking changes
edits to base game files

**Changelog**
:cl: erhardsteinhauer (discord)
- tweak: NPCs now able to target mechs and turrets.
- tweak: Mechs can be destroyed beyond repair now.
- fix: Fixed solution transfer for syndicate darts.

### CODE REVIEW

**Comment by dvir001** [comment]
Honestly no idea how adding ``MobState`` to them can affect other systems.
Will need a lookup in testing to see if its possible to add a new component to fix this issue.

**Comment by ErhardSteinhauer** [comment]
True, but both turrets and mechs are kinda mobs, so shouldn't be too bad

**Comment by dvir001** [comment]
> True, but both turrets and mechs are kinda mobs, so shouldn't be too bad

Its probably fine but ill try to find what systems its talking to make sure nothing funny.

**Comment by dvir001** [comment]
Looked into this and MobState can have some weird implication with the system its connected to.
Leave this PR open, ill try to find a fix with a new comp.

**Comment by ErhardSteinhauer** [comment]
Closing for there is a better solution to those issues

**Pull request closed without merging**
