### PR TITLE
The YC Convergence

### PR DESCRIPTION
**Pull request by choccy4**
## About the PR

Adds the YC Convergence ship to the game, that is all.
## Why / Balance

I created this ship to fill in the gap that the Metastable left, when it - well, left. Basically, as a ship to allow other ships to dock together nicely, without the Metastable's overly expansive features - which seems to be at odds with the current design ethic of the ships as single role units.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the YC Convergence shuttle

### CODE REVIEW

**Comment by dvir001** [comment]
This ship breaks so many guidelines notes, please make sure to read them again and ask for help on discord if you need.

**Comment by VividPups** [comment]
image

Im looking at the ship and I will say this is probably be one of the big things they will ask you to change

**Comment by VividPups** [comment]
Just going to put some stuff here to give you some things to do before the maintainers do a full run through
1 your power system is bork (your smes not connected properly) 
2 your doors do not have fire locks on alot of places  including the first door when entering the ship (the one right after the docking ship) which is a big big space osha violation
3 the vending machines. they will probably ask you to remove a good bit of them (they WILL tell you to remove the food ones)
4 the mircowave. they hate us having food. (also would probably say something about the chef belt)
5 the lights oh lord they are going to have field day with the lights. best to have it 1 color for the most
6 no emerency lights  wont be able to see shit when power is out "
7 fax machine big no no cant have centcom be out and about.  must used the one label (ship) ( when you send a fax it will be from Centcom)
9 WARP POINT, i say boy BOY, how do you expect the ghost to haunt you without no warp point 
10 atmos markers  need the markers for the outside diagonal walls
11  fire alarms  arent link to the doors  
12 the air alarms arent link tot he scrubbers/sensors
 SUB FLOORING
  - waste pipes.  they are going to tell you to change this. having mulitple scubbers and vents arent a problem however  they all need to be in on the same network.  (also why dont you want your animals to breath?)
  - wiring, try to keep wiring out of the walls. (its a pain in the ass to having to repair in the field)
  
  
and btw i understand any frustation that comes from this. nearly everyone has it happen.   Darin does make some points about reading the guidelines some things he are saying arent ACTAULLY in the guideline wiki page however, the page itself does need another look over to be updated 

also i would recommend another way to enter the cockpit without  having to go into the power room... sense really power room is urgey the most important room in the ship 

hope this helps give you some direction

**Comment by choccy4** [comment]
> Just going to put some stuff here to give you some things to do before the maintainers do a full run through 1 your power system is bork (your smes not connected properly) 2 your doors do not have fire locks on alot of places including the first door when entering the ship (the one right after the docking ship) which is a big big space osha violation 3 the vending machines. they will probably ask you to remove a good bit of them (they WILL tell you to remove the food ones) 4 the mircowave. they hate us having food. (also would probably say something about the chef belt) 5 the lights oh lord they are going to have field day with the lights. best to have it 1 color for the most 6 no emerency lights wont be able to see shit when power is out " 7 fax machine big no no cant have centcom be out and about. must used the one label (ship) ( when you send a fax it will be from Centcom) 9 WARP POINT, i say boy BOY, how do you expect the ghost to haunt you without no warp point 10 atmos markers need the markers for the outside diagonal walls 11 fire alarms arent link to the doors 12 the air alarms arent link tot he scrubbers/sensors SUB FLOORING
> 
>     * waste pipes.  they are going to tell you to change this. having mulitple scubbers and vents arent a problem however  they all need to be in on the same network.  (also why dont you want your animals to breath?)
> 
>     * wiring, try to keep wiring out of the walls. (its a pain in the ass to having to repair in the field)
> 
> 
> and btw i understand any frustation that comes from this. nearly everyone has it happen. Darin does make some points about reading the guidelines some things he are saying arent ACTAULLY in the guideline wiki page however, the page itself does need another look over to be updated
> 
> also i would recommend another way to enter the cockpit without having to go into the power room... sense really power room is urgey the most important room in the ship
> 
> hope this helps give you some direction

very much understandable, i knew a lot was wrong and i wondered if there would be feedback and thank you very much for it, but yes as you said - there is like, SERIOUSLY a lack of documentation on ship building so i winged it as a draft expecting someone to help and i guess it worked - anyway, off to fix it!

**Pull request closed without merging**
