### PR TITLE
Revert "Optimize Debris Code"

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

its just deleting people now, needs a revert

### CODE REVIEW

**Comment by Dysh3s** [comment]
I believe it was fixed by https://github.com/Corvax-Frontier/corvax-frontier-14/pull/80

**Comment by dvir001** [comment]
> I believe it was fixed by [Corvax-Frontier#80](https://github.com/Corvax-Frontier/corvax-frontier-14/pull/80)

We have that code, can it be something else?

**Comment by dvir001** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1384
Fixed, please merge.

**Comment by Cheackraze** [comment]
It's also causing tps hitching with 5 whole ms to calculate the queue, this needs reverting

**Review by dvir001 — APPROVED** [review]
Going to fix it all in ones

**Pull request merged**
