### PR TITLE
ICR Lithos - Medium class expeditionary ship

### PR DESCRIPTION
**Pull request by Blackszedows**
## About the PR
I've made a medium size expedition ship for the ICR.
Priced 68151 Spesos for now.

(Appraised is 50k, didn't feel right)

## Why / Balance
Felt like i should make at least one more ship considering I've made a separate manufacturer's ID. 
And also wanted to do some more field-testing with my decals.(Found few issues with them that i could potentially fix)

## Media

*After first edit pass

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Edits
First pass :
- Chef locker replaced in favor of botanical locker as there were no botanical tools previously
- One of material reclaimers replaced with autolathe
- Added gas dispensers that i forgot about when first making the PR
- Minor interior changes
- Fixed missing wiring in some places

:cl:
- add: Added Lithos shuttle

### CODE REVIEW

**Comment by McBosserson** [comment]
With 18 thrusters and 4 gyros, that price seems right to me.

**Comment by Blackszedows** [comment]
> With 18 thrusters and 4 gyros, that price seems right to me.

Thruster count might be a mistake on my part, since it originally had 12 of those but the acceleration was very slow, but after adding those i didn't note much of a difference. If need be i can propably trim some of those up

**Comment by Cheackraze** [comment]
i love the shape and design. Flooring is a bit noisy and its a touch empty of space, but I can see this being a great platform to customize and make your own actually.  My only thing is, swap one of the material reclaimers for a different machine, maybe a proper recycler or maybe some other fabricator like an autolathe or similar, maybe a unique vending machine or something. Once thats in, this looks good to merge so I'll keep an eye on it this week for changes.

**Comment by Blackszedows** [comment]
Not sure if i should turn the PR back to a draft or just close it, but withhold with merging for now, figured i'll remove the "pavement" diagonals afterall and don't want any errors coming in because of that. While at it i'll also rework the other diagonals so they look more like regular tile decals.

**Pull request closed without merging**
