### PR TITLE
Anchored hydro tray

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
* New hydro tray that cannot be moved or reconstructed, but it can be removed by hitting it.

To be used in ships and stations to make it impossible to steal or move them to other locations.

### CODE REVIEW

**Comment by mirddes** [comment]
this is actually fucking stupid.

ive been moving my tray around in hydro ever since i discovered the wrench, on every single ss14 server ive ever played on, even ones wihtout additional trays.

imagine if someone came into your house and nailed down every single bit of furniture and said FUCK YOU YOU CANT MOVE IT HAHAHAHAHAHAHAHAHAHAHA

thats this PR.

and unless you're gonna do it to everything else, this PR is targeted and petty.
go imagine real balance and stop shitting on enjoyable gameplay loops.
learn good design.

**Comment by mirddes** [comment]
ALSO!!!!, have you met the dirt tray? its exactly what you want.

**Comment by Cheackraze** [comment]
be civil in discussion please

**Comment by Norletic** [comment]
I feel like this is targeted against kitchenfarms. This is incredibly petty imo and it could also affect others which are trying projects casually.

**Comment by mirddes** [comment]
> be civil in discussion please

im being civil, im also being candid and expressive. i mean no disprect to anyone, only to the idea being expressed.

how long until a PR removing the ability to build the normal ones?

**Comment by mirddes** [comment]
furthermore, why would anyone want trays that can be damaged by combat?

**Comment by dvir001** [comment]
> furthermore, why would anyone want trays that can be damaged by combat?

This is the same function as the normal ones, 100 health points.

The idea behind this added hydro is to add a new type of hydro tray that could be used to replace existing ones, this isn't a talk about if we should replace them right now or where we replace them.

The ideal will be on stations, and possibly on ships that come with hydro pre installed, the option to build hydro as normal isn't effected by this. 

In the end of the day this is a better looking "dirt tray", with the normal icons, water storage and overall good stats.
https://github.com/new-frontiers-14/frontier-station-14/blob/39f04795f5ecb1911b1966f7a1fcbe9f5304f8ea/Resources/Prototypes/Entities/Structures/soil.yml#L38

**Comment by mirddes** [comment]
> > furthermore, why would anyone want trays that can be damaged by combat?
> 
> This is the same function as the normal ones, 100 health points.
> 
> The idea behind this added hydro is to add a new type of hydro tray that could be used to replace existing ones, this isn't a talk about if we should replace them right now or where we replace them.
> 
> The ideal will be on stations, and possibly on ships that come with hydro pre installed, the option to build hydro as normal isn't effected by this.
> 
> In the end of the day this is a better looking "dirt tray", with the normal icons, water storage and overall good stats.
> 
> https://github.com/new-frontiers-14/frontier-station-14/blob/39f04795f5ecb1911b1966f7a1fcbe9f5304f8ea/Resources/Prototypes/Entities/Structures/soil.yml#L38

fair enough. ill be using dirt trays on the agricultural dome and "kitchenfarms diner" when i design them. 
heavy tray should be better than the base model if it has all these drawbacks, good enough and i wont use dirt.

**Comment by Cheackraze** [comment]
it would actually be an interesting in-between tho maybe it should get fully resprited. its nice having the indicator lights and knowing what the plot needs, and dirt provides none of that visual feedback.

**Comment by mirddes** [comment]
i second a resprite

**Comment by mirddes** [comment]
they should have greater capacity and starting values of all hydro tray stats. the model sould be significantly thicker... not quite twice as thick.. otherwise identical form and function.

not being able to dismantle doesn't make sense though. ideally everything should be able to be built and broken.

maybe it should be hightech dirt, all the monitoring of trays, but for dirt.

**Comment by dvir001** [comment]
Added a new look, made by GentleJester.

**Comment by Cheackraze** [comment]
Ideally I was hoping for a much more distinct sprite to make it look very clear it will function differently.  I also hope to use these to more well balance most of the growing on frontier, and leave the base hydrotrays at vanilla and let them be movable/rewards/customizable variants. so ships would spawn with these kinds always, the trays would be extra boards purchased from vending machine or from scientists or salvaged from expeds/wrecks etc.

**Comment by Cheackraze** [comment]
i was hoping more square base like a flower planter

**Comment by mirddes** [comment]
i think an important consideration from an RP perspective is "why is it heavy, what makes it heavy?" plenty of other much heavier things can be dragged.
 
 significantly greater capacity is just the start of justifying the extra girth.

**Comment by dvir001** [comment]
> i was hoping more square base like a flower planter

Redoing it, ill update when there is a new one.

**Comment by potato1234x** [comment]
what if i want to turn my prospector into a farm? what then?

**Comment by mirddes** [comment]
Then make trays

**Comment by potato1234x** [comment]
> it would actually be an interesting in-between tho maybe it should get fully resprited. its nice having the indicator lights and knowing what the plot needs, and dirt provides none of that visual feedback.

image
why not use the alt hydro sprites from tg

**Comment by dvir001** [comment]
> > it would actually be an interesting in-between tho maybe it should get fully resprited. its nice having the indicator lights and knowing what the plot needs, and dirt provides none of that visual feedback.
> 
> image why not use the alt hydro sprites from tg and edit them a little bit

They have no sprites for the light indicators

**Comment by dvir001** [comment]
image

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
