### PR TITLE
Vulpkanin Race

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Add the Vulpkanin race from Delta-V as a playable race from spawn.

The Vulpkanin (vulp-ka-nin) are a race of humanoid canine-like beings.
- Has an animal stomach.
- Is the fastest race. (SprintSpeed: 5 / WalkSpeed: 3 / 0.5 Faster then moth)
- Able to withstand cold environments.
- Takes less Cold damage. (Same as moth)
- Takes twice burn damage when on fire. (Rip Fur)
- Get 10% more hungry.
- Get 2.5% more thisty.
- Has 3 Emotes. (Barks, Growls, Howls)
- Talking Sounds. (Growls Like)
- Lot of customizable markings.
- Cannot speak Common Language and need a Translator to translate thier speech.
- Vulpkanins spawn with the Translator in thier hand.
- Vulpkanins without a translator will speak Canilunzt and only others Vulpkanins will understand them.

So far during my local test everything seem to work correctly, but take note that its my first time working with SS14.

**Media**

Capture2
Capture
Capture
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
- [x] Add Clothwarp Shoes.
- [x] Unique Gameplay Feature.
- [x] Canilunzt langauge system.

**Changelog**

:cl: FoxxoTrystan
- add: The Vulpkanin race has arrived to the Frontier Sector they are a race of humanoid canine-like beings that are confortable in the cold but cannot speak common without a translator and also have their own langauge!
- add: Cloth footwarps
- tweak: Cloth footwarps can be found in Clothesmate
- add: Canilunzt translator
- tweak: Canilunzt translator can be found in Vendomat, Vulpkanins spawns with them.

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
If this PR is merged i will also work on fixing/respriting some of the Hardsuits, Masks and others clothing that does not fit due to how vulps head are.
This will be mostly made inanother PR if this one is merged.

Example here:
head
(Basic Hardsuit, Salvage Hardsuit, Blood-Red Hardsuit)

**Comment by rbertoche** [comment]
Adding my personal take on vulpkanin/foxes, I hope it doesn't get added with speed bonus and slash damage when unarmed. They both make sense, although they make too much of a difference ingame, movement speed makes you considerably harder to hit since gunfire is slow and may also allow you to hit opponents in melee without them having the same chance of hitting you, so having a speed bonus can't easily be balanced by other combat nerfs cause it's too powerful
About slash damage, it does make sense for claws, it's just that bleeding being currently a fast steep spike, so bleeding adds up a lot of damage soon after the blow, making slash too much at an advantage against brute. But are the claws really _that_ sharp? :P
My main reason to dislike such race features is that they make a fair unarmed fight with foxes - or felinids - impossible.

**Comment by FoxxoTrystan** [comment]
> 

Regarding the felinids they have the same stats in regards of the current damage damange.
Tho indeed pehaps we could change it to 3 Piercing and 1 Blunt and change the speed to be the same as moth.

**Comment by FoxxoTrystan** [comment]
Final Balances has been done:
- Removed Unarmed Slash Melee (Now its has Default melee like humans)
- Get 10% more hungry.
- Get 2.5% more thisty.

Now all the changes will be updated in the main PR Description and i will mostly not touch anything until there changes required.

Aka, PR ready for review.

**Comment by rbertoche** [comment]
I think moths have same speed as humans here. I would merge this right away in my stuff if it had no walk or sprint modifier on the legs, same as felinids here.
Can I use this on Pirata? :)

**Comment by FoxxoTrystan** [comment]
> I think moths have same speed as humans here. I would merge this right away in my stuff if it had no walk or sprint modifier on the legs, same as felinids here. Can I use this on Pirata? :)

Pirata? I dunno what is this this but sure.
And rechecking the code does confirm that Moth have a MovementSpeedModifier of 2.5 and 4.5 but if you wana remove it go in "Body -> Parts -> Vulpkanin" and remove the modifier there.

**Comment by rbertoche** [comment]
> Pirata? I dunno what is this this but sure. And rechecking the code does confirm that Moth have a MovementSpeedModifier of 2.5 and 4.5 but if you wana remove it go in "Body -> Parts -> Vulpkanin" and remove the modifier there.
Oh you're right. I was looking at the mob's legs, it's just at the mob prototype instead.
Pirata is a ss14 code base and community and currently the most popular pt-BR server, and also thanks! Already started a branch for adding it.
 
> Tho does the MovementSpeedModifier in Ent/Species and Body/Parts are the same?
I have no idea, I can't even figure out what human speeds are anyway, or if those modifiers are really adding up or just assigning a new value. Anyway. I'm assuming human speed is 4 for sprint, 2 for walk? :shrug: 

cheers

**Comment by Cheackraze** [comment]
let me know when this is ready for review

**Comment by FoxxoTrystan** [comment]
> let me know when this is ready for review

PR Ready for review.

**Comment by FoxxoTrystan** [comment]
> code looks good, lemme test locally

I am praying that everything is good and nice.

**Comment by FluffiestFloof** [comment]
Would it be possible to know where the bark, growl1, growl2, growl3 and howl sound come from? They lack a license or attribution file and I'm interested in adding some of them to DeltaV.

**Comment by FoxxoTrystan** [comment]
> Would it be possible to know where the bark, growl1, growl2, growl3 and howl sound come from? They lack a license or attributions file and I'm interested in adding some of them to DeltaV.

Growls sounds comes from Paradise.
Barks from TG.

Il update the attributions files when i work on fixing some stuff with vulps after the upstream merge.

**Pull request merged**
