### PR TITLE
Mob/Turret Laser Reflect Chance

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Added 85% chance to reflect laser shots to some mobs (if the mob has some sort of a space suit or is silicon) and to all turrets.
Replaced plastitanium windows with walls on syndie cache bluespace event.

## Why / Balance
Laser abuse.

## How to test
1. Spawn syndicate voidsmen, try to shoot them with lasers.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Added to some hostile mobs (mostly the ones that wear some sort of space suits) and all turrets a high chance of reflecting laser shots.

### CODE REVIEW

**Review by whatston3 — APPROVED** [review]
Seems alright.  Reflect seems strong, but could see how it pans out.

**Comment by VividPups** [comment]
Making it where they reflect is just going to completely kill the since side of the weapon pool.  For example the Captain Sabre that had a 50% chance and people kept saying "it's OvER PoWeR". Until it was nerf to the ground. Instead of adding reflect chance. Heat reduction protection would make more sense and gameplay wise and Lore wise. Furthermore the only actual clear solution is to make it where mobs can shoot/see through glass.

**Comment by ErhardSteinhauer** [comment]
> I believe if you make it a reflect chance, for just lasers is just going to cause players to just not used laser weapons.

Yes, that is why the reflect is only for lasers.

> I believe the best course lf action would to add Heat protection.

Heat protection doesn't give as clear visual confirmations that attack failed, as reflection.

> The only real Solution to this "abused" is to get it where turrets/mobs can see/attack through the glass

Yep. WYCI.

**Comment by VividPups** [comment]
> > I believe if you make it a reflect chance, for just lasers is just going to cause players to just not used laser weapons.
> 
> Yes, that is why the reflect is only for lasers.
> 
> > I believe the best course lf action would to add Heat protection.
> 
> Heat protection doesn't give as clear visual confirmations that attack failed, as reflection.
> 
> > The only real Solution to this "abused" is to get it where turrets/mobs can see/attack through the glass
> 
> Yep. WYCI. But until this happens (or a better solution arrives), band aid stays.



They don't need a clear indicator for a fail attack. Protection wouldn't cause a fail attack. But would cause way more time to destory it. 

Again, making where it just reflect lasers will cause people to just continue using ballistic weapons more then ever (since most people used ballistic anyway). There is a difference between bandaid and killing one of the since great uses of  1/3rd of the weapon pool

**Comment by ErhardSteinhauer** [comment]
> They don't need a clear indicator for a fail attack

I disagree. Clear clue that players should not use lasers to in this situation is important imo.

> continue using ballistic weapons

Which is fine, because when they do, they are more likely to put themselves into a position when mob can retaliate.

> and killing one of the since great uses of 1/3rd

Ah, yes, "great use" - abusing inability of AI to see you behind the window and retaliate.

**Comment by VividPups** [comment]
> > They don't need a clear indicator for a fail attack
> 
> I disagree. Clear clue that players should not use lasers to in this situation is important imo.
> 
> > continue using ballistic weapons
> 
> Which is fine, because when they do, they are more likely to put themselves into a position when mob can retaliate.
> 
> > and killing one of the since great uses of 1/3rd
> 
> Ah, yes, "great use" - abusing inability of AI to see you behind the window and retaliate.

They never had a "clear clue" before because it doesn't matter. They will find out that they shouldn't used in time. 

And yes it is the best quality of a laser weapons has was the ability to go through windows.

And no it really doesn't put them in that situation where the mobs can retaliated. Majority of the rooms in Expeditons you do not need to enter at all (which cuts the combat down)  when in space you can cause them to get trap in Space (They can't move) and is able to fire at them out of their range. With the used of a jetpack or ship.

**Comment by ErhardSteinhauer** [comment]
> They never had a "clear clue" before because it doesn't matter. They will find out that they shouldn't used in time.

The result is the same. With clues it'll happen faster. Either way, the solution will most likely work, and I don't care to change it in favor of heat protection.

> weapons has was the ability to go through windows.

That quality is still there, you can shoot players through the windows just fine.

> Majority of the rooms in Expeditons you do not need to enter at all

Which is a separate problem addressed in separate PR.

**Comment by VividPups** [comment]
No with the reflect it isn't a "clue" it's a complete rejection of the damage.  Where Heat Protection I'll still damage the mob but takes longer to destory.  If anything the reflection chances should be lower. How is it captain Sabre reflection chance was "ToO Op" when a player uses it but, when it's a mob. It's ok with even a higher reflection chance?


I wouldn't really say the "quality" is still there when there is barely any PVP compare to PVE.

**Comment by ErhardSteinhauer** [comment]
The goal is to stop players from shooting mobs with lasers from behind glass. If anything laser reflect chance should be 100%, because with 85% there is a 15% chance for player to land a shot. Which is 15% too much.

**Pull request merged**
