### PR TITLE
Prison "POI"

### PR DESCRIPTION
**Pull request by NkoKirkto**
Adds the long awaited, hopefully decent enough to do its job Prison POI.

## About the PR

Credit goes to Slav for this PR. Im just a little thieve

This adds the Prison POI complete with a fully function perma which holds up to 7 prisoners at a time and includes activities such as Hydroponics, prisoner ran Bar and Kitchen and nice reading corner to find out how to beat your case! Also included are 4 short term holding cells for minor sentences, visitation room, public docks for interested players to stop by for some grub or a drink, Lawyer's office, surveillance room for the plethora of cameras littered around the station, Wardens office and leisure area, and prison guard locker and break rooms.

## Why / Balance
As discussed in the Community Meeting and in the NFSD issues thread, once this is implemented fully criminal sentences can start to carry some weight given our six hour round timeframe. This will also help balance out the lack of want and need to arrest and contain prisoners who commit felonious or capital offenses.
## How to test

Fully functioning with self sufficient atmos and power. Download throw it in your maps file and load 'er up!

## Media

The POI in Totality:
image

Frisk Area and Survaliance:
image

NFSD Docks:
image

Perma:
image

Public Space and Docks:
image

Storage Wing (Including Medical, Lawyers Office and of course Prisoner Storage):
image

Wardens Wing: (Including Wardens Office/Meeting area, Guard Break and Locker rooms)
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: The Prsion so you little criminals get punished properly :)

### CODE REVIEW

**Comment by mrscratch** [comment]
image

This part right here could use two-three rows of tables for when chow gets delivered. One of the few rights prisoners have is that they are entitled to food/water, so for compliance sake the wardens usually make them all eat at the same time (this can also double as a head count to make sure no one is missing).

**Comment by NkoKirkto** [comment]
Good idea will work on it.

**Comment by Vonsant** [comment]
Wazzup, still working on the Prison?

**Comment by NkoKirkto** [comment]
> Wazzup, still working on the Prison?

Nah im done i just have no idea how to solve this merge conflict as is just dont have enough knowlege on how to resolve those.

**Comment by VividPups** [comment]
@dvir001 might be able to help with that help point you in the right direction

**Comment by MagnusCrowe** [comment]
image
Can you fix this please?

**Comment by MagnusCrowe** [comment]
image
These hallways are straight up cursed.  I have no idea how to salvage that in its current form, I recommend redesigning this. Perhaps not all corridors need to be interior/atmos.  Perhaps a EVA catwalk and an electrified grille fence could do instead, maybe you could work in a spaced hanger for hoverbikes?

image
What's the intent here?  There's a countertop but no way for anyone to send food to the other side.  Is the intention to use mail delivery units to send food to the other side?  Goblins can use that to escape.  If you want to do prison jobs like that, which I love by the way, I recommend you design the prison in a way that splits up the low security prisoners from the high security prisoners.  This gives prisoners an incentive to behave, they will get more freedom and activities for being downgraded from high security to low security. 
image
I think people are going to find it a little difficult to get into the kitchen with that vending machine and that mail unit in the way.
image
Soft external walls on a prison?  Also, no camera or glass on the freezer with the meat spikes?

image
All of the appeal of using glass floors on the exterior of a ship or station is lost when the floor is lit up from above.  
I recommend just using a lattice "support" instead, see below.
image

image
Unpowered light.

image
Confusing mixture of different types of wall and window...Please don't mix reinforced walls with plastitanium windows. Also, plastitanium windows in the same wall as reinforced windows 😬.

image
The floor inside the prison is plastic but the floor outside is steel?  Looks weird to me.

image
The grey border on this glass looks weird to me.  Also the grey border mimics steel floor tiles, not plastic so there's more weirdness there.
image


image
What is this? A boxing ring for ants?

image
Two things going on here.  1) use the unmovable hydroponics here please.  2) ick, the floor tile you chose shows wire.

image
One of these things is not like the other.

image
This image is pretty representative of the weird sub-floor layout throughout the station. It's very strange that you chose to put the vents off to the side here. On the picture above, it's very strange that the scrubber was over a decal in front of the door instead of in the middle of the room with the vent.

In some places on the station, there seems to be too few vents and scrubbers.
image
For example, in this whole hallway there's one set of scrubber/vent and it's even offset to the left.
image
Not even a scrubber in the chem lab, a place that really needs one.  Also, in this picture you can see that there's an inconsistency in what you're placing under windows.  Please just put plating under them, not floor tiles.

image
Unanchored logic gates...Also, do you want those maintenance airlocks to be unlocked for anyone to use? They lead to an area that's locked behind NFSD access doors...seems like a huge security oversight.

image
The airlocks are dark and full of terrors.
image
Except these airlocks, which are WAY too bright.

image
I don't know why, but this floor detail gives me the willies.  It's very odd.  It would probably do better spiced up with a color?
image
Like that or something?

image
Likely too many emergency lights...

image
Missing floor tile.

image
Maybe spice up the doorframes with a different tile?  Like below?
image


That's all for now, I'll continue reviewing this later.

**Comment by arimah** [comment]
For subflooring in 3-wide hallways, I _strongly_ suggest doing something very similar to the upstream stations:

image

Distro and waste pipes on opposite sides of the hallway, with vents and scrubbers in the middle. It tends to look more balanced _and_ the regularity makes it real easy to lay things out. Cables and disposal pipes (when necessary) go in the middle. Remember that especially long hallways need more than one set atmos devices, and would generally benefit from intermittent firelocks so spacing doesn't spread too far.

**Comment by NkoKirkto** [comment]
@MagnusCrowe What would you suppose for the diagonal Hallways?
The fun thing about the station (like the court for example) is that it is shaped like a badge so i would be hesitant to remove it and replace it with a boring square design. I could lay the pipes trough the Cell Area but that would mean that prisoners could cut off all the atmos for the station. 

Why is it a issue that goblins can escape trough the mail delivery units? As far as I am aware you cant play a goblin except if you are in a gohst role? The thing with Low Security and High security was my idea at first.
image
How about i split this part of the station of as High Sec? Security Officers wouldnt need to pass through the Low Sec Area to reach it and could transfer Prisoners between the Areas via the Blast Doors?

**Comment by NkoKirkto** [comment]
> If I were building a high and low sec prison I would have them both be mirrored and sharing a common glass wall with each other, running through the activity room. I would furnish the low sec half with more activities and nicer furniture so that high sec prisoners can see what they are missing but also communicate with the low sec prisoners.

Then people that are only there for limited time would always get spit out into the high sec part because without redesigning the entire prison there is no way i can make that work+ Space for the cells would get quit limited. I rather would only have 1/4 of the Area dedicated to High Sec. I will see how i can design it.

**Comment by dvir001** [comment]
Closing this for the main time, you can reopen if needed.

**Pull request closed without merging**
