### PR TITLE
Sleeping inside bags

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
Allows pseudo-item creatures (small cats and vulps) to sleep while being placed inside a bag.

37 added lines, 0 removed

## Why / Balance
Amimir

I need it. Seriously.

## Technical details
Created a new component, AllowsSleepingInside, and added it to the base backpack item. Modified PseudoItemSystem to add/remove the sleep action when a pseudo-item entity gets into/out of a container with that component, and show a popup when it falls asleep.

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/69920617/2845d58c-bd9a-4821-a99a-55754fa79914

(Note: in the video the popup can show even when the entity is already asleep, I changed the code to prevent that)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- add: Scientists have discovered that small creatures can sleep inside bags.

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]
Mimir

**Review by TsjipTsjip — COMMENTED** [review]
CL entry here feels extraneous, as people will run into this as they go along, and it will make sense if it uses the existing sleeping system.

**Comment by dvir001** [comment]
Is this bed container has the same healing of a normal bed?

**Comment by Mnemotechnician** [comment]
> CL entry here feels extraneous, as people will run into this as they go along, and it will make sense if it uses the existing sleeping system.

Maintainers want frontier-specific stuff in the _NF namespace whenever possible, so I made a new ftl file as none of the existing fit. And it already uses the existing sleeping system - the sleep action is handled by SleepingSystem; PseudoItemSystem just handles adding/removing the action

> Is this bed container has the same healing of a normal bed?

No, that one is provided by some component, something like HealOnBuckle. Since entities inside a bag are __not__ buckled to it, it's inapplicable.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
