### PR TITLE
Jester Outfit 4 Pixel Fix

### PR DESCRIPTION
**Pull request by terezi4real**
## About the PR

Fixes 2 pixels on the jester outfit 1 that showed the players shins. recolors 2 other pixels to make it match.
this always bugs me.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: jester outfit sprite

### CODE REVIEW

**Comment by potato1234x** [comment]
why not fix this upstream instead

**Comment by terezi4real** [comment]
> why not fix this upstream instead

can i do that without cloning the repo, i tried to fix it upstream and i couldnt make a PR cuz i needed to do it from a fork and when i tried to make a fork it said i already had one, so i looked for it and i dont, unless it means my fork of the Red Eclipse fork for me and stikyts server, which i couldnt PR from either cuz it dragged along all that servers changes, basically help i hate github.

**Comment by potato1234x** [comment]
are you using some third party program or github desktop

**Comment by terezi4real** [comment]
> are you using some third party program or github desktop

i have VScodium and usually just make my PRs in browser

**Comment by potato1234x** [comment]
basically just get github desktop and click this to find the fork you already have
image

**Comment by potato1234x** [comment]
if that dont work just go to #howdoicode on the discord

**Pull request closed without merging**
