### PR TITLE
Crescent Intro

### PR DESCRIPTION
**Pull request by Kesiath**
## About the PR
Adds the Crescent, a massive expedition sustain vessel capable of service, medical, and science. Acting primarily as a mothership for smaller expedition ships who don't want to deal with the main station and need better medical aid, off-load research materials, or obtain provisions.

**Media**
image
image
image

**Changelog**
:cl: Kesiath
- add: Added the Crescent, a massive expedition sustain vessel capable of service, medical, and science.

### CODE REVIEW

**Comment by Kesiath** [comment]
Done working on it for today but I plan on doing a decal pass tomorrow, just wanted to push this for initial review.

**Comment by potato1234x** [comment]
holy shit thats huge good work

**Comment by Kesiath** [comment]
Okay, fixes pushed and decals done, totaling to 208k total cast with 188k appraised. This ship is MASSIVE and approaching the upper limit of what's possible.

**Comment by Cheackraze** [comment]
eh why not, I trust you havent put too much powergame in there. besides it costs 200k, also HoP should evict it within 2 minutes of existing jfc its almost bigger than the station itself

**Review by Cheackraze — APPROVED** [review]

**Comment by CarVeryCool** [comment]
I hope to see these in the wild every once in a while

**Pull request merged**
