### PR TITLE
Departmental EVA resprite + helmet lights

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Added toggleable lights to departmental EVA suit helmets.
Ended up respriting departmental EVA suits: used sprites from Baystation12 as base. Slightly altered original sprites and then greyscaled them and split into layers.
- For suit used "space" taken from Baystation12 at https://github.com/Baystation12/Baystation12/blob/dev/icons/mob/onmob/onmob_suit.dmi
- For helmet used "spacebowl" taken from Baystation12 at https://github.com/Baystation12/Baystation12/blob/dev/icons/mob/onmob/onmob_head.dmi

## Why / Balance
QoL

## How to test
Spawn departmental EVA suits, equip them, toggle helmet piece, toggle lights

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Added toggleable lights to departmental EVA suit helmets.
- tweak: Resprited departmental EVA suits.

### CODE REVIEW

**Comment by whatston3** [comment]
Two points:
1. The battery in the suit lights doesn't drain, seems like unexpected behaviour from the comments, though this is consistent with the existing suit lights.  I think that 3 watt figure is pulled from thin air - it defaults to .8 W, though this also doesn't matter, since the light doesn't draw power from a battery since it doesn't have a power cell slot entity.  Upstream issue, I suppose, but weird.
2. The equipped light overlay having hard square borders seems strange to me, I tried to get something that's a bit more rounded, but I'm still not really happy with it.  Pictures below, curious what you think.

Overlay on the head of the feature.
image

My attempt at a softer overlay
image

**Comment by ErhardSteinhauer** [comment]
> The battery in the suit lights doesn't drain, seems like unexpected behaviour from the comments, though this is consistent with the existing suit lights. I think that 3 watt figure is pulled from thin air - it defaults to .8 W, though this also doesn't matter, since the light doesn't draw power from a battery since it doesn't have a power cell slot entity. Upstream issue, I suppose, but weird.

Yeah, this thing is odd. Sadly, I was unable to make it work without that battery block. Actually, I didn't try to add just the battery  component without the rest of code. Gonna try it now.

> The equipped light overlay having hard square borders seems strange to me, I tried to get something that's a bit more rounded, but I'm still not really happy with it. Pictures below, curious what you think.

Yep, I'd go with your variant

**Comment by whatston3** [comment]
> > The battery in the suit lights doesn't drain, seems like unexpected behaviour from the comments, though this is consistent with the existing suit lights. I think that 3 watt figure is pulled from thin air - it defaults to .8 W, though this also doesn't matter, since the light doesn't draw power from a battery since it doesn't have a power cell slot entity. Upstream issue, I suppose, but weird.
> 
> Yeah, this thing is odd. Sadly, I was unable to make it work without that battery block. Actually, I didn't try to add just the battery component without the rest of code. Gonna try it now.

Give me a bit, I'll test a power draw fix.

**Comment by whatston3** [comment]
Got it working on [whatston3:2024-10-07-helmet-light-powerdraw](https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-10-Departmental-EVA-Headlights...whatston3:frontier-station-14:2024-10-07-helmet-light-powerdraw?expand=1)

This makes the suits work as commented (light for 10 minutes, recharge for 5).  The flashing light when very low on charge looks weird with the overlay being constantly on.  If this fix was in with the wattage left at 0.8 W, the light should still be on all the time.
I think it's fine as a bugfix, but I'm not sure if you want suit lights going out - it's not immediately obvious that they recharge (though you'd figure out pretty quickly if it dies and then can turn back on if you wait).

Happy with this regardless.

**Review by whatston3 — APPROVED** [review]

**Comment by ErhardSteinhauer** [comment]
> I think it's fine as a bugfix, but I'm not sure if you want suit lights going out - it's not immediately obvious that they recharge (though you'd figure out pretty quickly if it dies and then can turn back on if you wait).

I'm not sure about it either. Would it be better if EVA helmets accepted actual power cells to power light and such? Idk. imo should be untouched until comes up with actual design document for EVA/hardsuit systems.

**Comment by ErhardSteinhauer** [comment]
Forgor to edit inhand sprites yesterday, fixed now. Also added unshaded layer to suits. Attempted to add a bit more details to suit base sprite, so it'll look less flat in comparison with original sprite from Baystation12.

**Pull request merged**
