### PR TITLE
Holoflare pistol

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Adds a selfrecharging energy pistol that shoots holographic light sources. Has three modes of fire: cyan, red and yellow. The projectiles, holoflares, don't deal any damage and don't set anything on fire, last for 15 minutes.

## Why / Balance
I like the idea of flare guns, I believe that they can add to the atmosphere of the game, but actually using flare guns is a nightmare due to how inconvenient the whole process is. This PR tries to solve this issue.

## How to test
Spawn in, spawn holoflare pistol or buy it from lesslethal vendomat.

## Media
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: erhardsteinhauer, whatston3
- add: Adds a self recharging energy pistol that shoots holographic light sources. Available from LessLethal vendomat.

### CODE REVIEW

**Comment by whatston3** [comment]
Pushed a suggestion onto [whatston3:2024-10-31-holoflare-suggestions](https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-10-Infinite-Flaregun...whatston3:frontier-station-14:2024-10-31-holoflare-suggestions?expand=1)

* Reduced flare length to 4 minutes from 15, consistent with the thrown emergency flares (up for debate, but I think it's more reasonable)
* Changed the red color to #FF8080, used for emergency flares
* Used yellow/red magic ball sprites for flares where appropriate
* Added firing mode enum values for red/cyan/yellow flares (naming might not be great, feel free to change, but the in-game sprite does update properly now)
* Named the flares with their color (now they show up appropriately in the right click menu)
* Minor grammar pass
* Reduced some redundancy in the red/yellow flare definition

Really nice feature.  Might even suggest removing the existing flare gun from the LessLethalVend.

A few pictures showing the new red flare colour:
image
image

**Review by whatston3 — APPROVED** [review]
Welp.

**Comment by ErhardSteinhauer** [comment]
I buffed lifetime of a light source to 9 mins. Not sure how useful 4 min flare is. From experience of using emergency flares - they are not great, you have to change them pretty often. But you at least can carry them with you.

**Comment by ErhardSteinhauer** [comment]
All of a sudden not sure if this thing is actually that useful: between long charge regeneration, light source you can't carry around and low lifetime of light source might end up not used at all. (Still better than a regular flare imo). Probably will have to adjust the values down the line.

**Comment by whatston3** [comment]
My thoughts on this:
Since the flares recharge in fairly short order, a shorter lifespan isn't too penalizing.  The existing flares are already pretty long lived, though you do lose the ability to carry them around (honestly, wouldn't care too much if it shot out disposable glowstick flares).

Between this and their larger light radius, those are the reasons you might want to still use flares, but they're still a pain.  Even with a four minute lifespan, I imagine these are fine.

**Comment by Leander-0** [comment]
prism
Dark souls prism stone but it is a flare i do love it, my only nitpick is that it needs another version but the color is random or RGB :^)

**Comment by ErhardSteinhauer** [comment]
> My thoughts on this: Since the flares recharge in fairly short order, a shorter lifespan isn't too penalizing. The existing flares are already pretty long lived, though you do lose the ability to carry them around (honestly, wouldn't care too much if it shot out disposable glowstick flares).
> 
> Between this and their larger light radius, those are the reasons you might want to still use flares, but they're still a pain. Even with a four minute lifespan, I imagine these are fine.

I recon it's mighty fine in a situation when you don't need to move too far from the light source, so good for looting wrecks and mining rocks. But it becomes less useful for illuminating abandoned installations on expeditions during the night time.

**Comment by ErhardSteinhauer** [comment]
> prism Dark souls prism stone but it is a flare i do love it, my only nitpick is that it needs another version but the color is random or RGB :^)

Yeah, probably could be added later. Would work fine with punk stuff I think.

**Comment by ErhardSteinhauer** [comment]
> Pushed a suggestion onto [whatston3:2024-10-31-holoflare-suggestions](https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-10-Infinite-Flaregun...whatston3:frontier-station-14:2024-10-31-holoflare-suggestions?expand=1)

Almost forgot to say thank you for your additions, very nicely done.

**Comment by whatston3** [comment]
> I recon it's mighty fine in a situation when you don't need to move too far from the light source, so good for looting wrecks and mining rocks. But it becomes less useful for illuminating abandoned installations on expeditions during the night time.

There's likely a sweet spot in terms of number of charges, charge time, and despawn timer.
Funnily enough, DRG might have some useful lessons there.

> Almost forgot to say thank you for your additions, very nicely done.

N-no you 👉👈

**Comment by ErhardSteinhauer** [comment]
> Funnily enough, DRG might have some useful lessons there.

Don't tell anyone, but charge replenish rate and number of charges were taken from DRG...

**Comment by dvir001** [comment]
Have to lower this to like 4 minutes since the upstream merge going to make it a pain with the light issues.

**Pull request merged**
