### PR TITLE
New Large Salvage Mothership. Colossus (plus a sub shuttle)

### PR DESCRIPTION
**Pull request by nyozzl**
## About the PR
added a brand new salvage mothership the colossus with its sub shuttle the colo

## Why / Balance
there was a distinct lack of large salvage ships

I am merely just filling in the niche

## Media
Colo sub shuttle 
image

Back of Colossus {ingame}
image

Middle of Colossus {ingame}
image

Front of Colossus {ingame}
image

Back of Colossus {mapping}
image

Middle of Colossus {mapping}
image

Front of Colossus {mapping}
image

Colo sub shuttle {mapping}
image

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->[X]

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none found
**Changelog**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added a large salvage mothership the colossus with a sub shuttle

### CODE REVIEW

**Comment by nyozzl** [comment]
do note will be unable to check in on this for.... 3 days due to me moving houses

**Comment by ThatOneGoblin25** [comment]
Distro still needs connectors for adding canisters and air injectors with gas filters for the chambers.

**Comment by ThatOneGoblin25** [comment]
Your map prototype checker test failed because you have security holoprojector on the grid.

**Comment by nyozzl** [comment]
Man this was rushed during a move

**Pull request closed without merging**
