### PR TITLE
Up to new player bank from 25k to 30k

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
With some changes over all to ship prices, new loadout system and overall worth of stuff I think its finally time to adjust the starting bank to give new player a small starting boost.

## Why / Balance
While you can still get starting with 25k its a bit more limiting now then it  used to be before, putting it up to 30k can help while having no big effect on the overall systems.

**Side note, before this PR is made into the game, we should have a system to block buying ships we might consider as noob traps for the first 3 hours.**

## How to test
Create a new player.

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: New players bank upped from 25k to 30k.

### CODE REVIEW

**Review by ErhardSteinhauer — APPROVED** [review]
Ca-ching

**Comment by dvir001** [comment]
Actually, looking into this I want to also edit this to be a server setting in cvar.

**Review by whatston3 — APPROVED** [review]
Think this is fine, reasonable increase, gives you _three whole Pioneers_ (whooa), and some more wiggle room if you goof without needing a new character.

Tried adding a check for the cvar in the default profile constructor but I think it's more trouble than it's worth.

**Comment by dvir001** [comment]
Going to make another PR to change all canisters base worth, this will be needed after I think as it will up all ships by 2k

**Comment by NafenX** [comment]
For the side note, there is an idea on the ideas forum in Discord about a newbie specific role. If the available ships for purchase in the shipyard console can be changed depending on the type of ID used, maybe the ID card for the newbie role (if it was something that got added) would only have cheaper and easy to use ships?

**Comment by dvir001** [comment]
> For the side note, there is an idea on the ideas forum in Discord about a newbie specific role. If the available ships for purchase in the shipyard console can be changed depending on the type of ID used, maybe the ID card for the newbie role (if it was something that got added) would only have cheaper and easy to use ships?

Not this PR scope

**Comment by dvir001** [comment]
image

Seems admins are ok with this overall,
Going to merge this later today.

**Pull request merged**
