### PR TITLE
Add an Alt verb to handicomms, to allow more convenient toggling

### PR DESCRIPTION
**Pull request by Alkheemist**
## About the PR

Added an Alt verb to RadioDeviceSystem for RadioMicrophoneComponents that calls ToggleRadioMicrophone.
Added an FTL entry for the new verb

## Why / Balance

QOL change for easily toggling the mic on handicomms.

## How to test

Hold down alt and click on a handicomm

## Media

https://github.com/user-attachments/assets/38b49981-1fd1-403d-a7fe-ad074519b2c4

dotnet_19_22-02-53

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None identified.

**Changelog**

:cl:
- tweak: Handicomm mics can now be toggled with an alt-click

### CODE REVIEW

**Comment by dvir001** [comment]
Cool beans

**Comment by chrome-cirrus** [comment]
Oh hell yeah!

**Comment by Temoffy** [comment]
yes please!

**Review by whatston3 — APPROVED** [review]
Works fine, mobile radios and intercoms work well, artifacts should probably be fine as well.

Might suggest pushing this upstream.

**Comment by whatston3** [comment]
Just going to note this - there are two minor inconsistencies with intercoms.
First, they check that the user has access before the microphone activates - this is only an issue with the STC's traffic consoles at the moment.
Second, this alternate verb doesn't actually update the intercom's state if it is one, so the intercom UI might be inconsistent.

Fixes here - maybe not the cleanest, but it works fine: [whatston3:handicom-alt-intercom](https://github.com/Alkheemist/frontier-station-14/compare/handicomm-alt...whatston3:handicomm-alt-intercom)

**Pull request merged**
