### PR TITLE
Crab And Clawbreaker

### PR DESCRIPTION
**Pull request by RealIHaveANameOfficial**
## About the PR

Adds the Crab to the shipyard console and the Clawbreaker to the black market console.
## Media

image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Hopefully, none.

**Changelog**

- add: Adds the Crab and Clawbreaker.

### CODE REVIEW

**Comment by PeccNeck** [comment]
this truly is one of the ships of all time

**Comment by dvir001** [comment]
This looks like what a 6 year old will paint when he asked what a space ship is like (This isn't an insult for the record just had to say it),

Can we drop the infinite power generators? trying to get them all reworked out of ships not added more 😭

**Comment by McBosserson** [comment]
Is the SMES intentional not hooked up right?
I love the bananium reactor, but could see it as problematic, like no rad protection. Hopefully it doesn't fall under the blacklisted starting power sources.
And no FoxxoTrystan, the bananium won't irradiate the station, unless someone brings it there. Bananium's radiation range is only 2 tiles.

**Comment by FoxxoTrystan** [comment]
> Is the SMES intentional not hooked up right? I love the bananium reactor, but could see it as problematic, like no rad protection. Hopefully it doesn't fall under the blacklisted starting power sources. And no FoxxoTrystan, the bananium won't irradiate the station, unless someone brings it there. Bananium's radiation range is only 2 tiles.

Damn your right, the SMES is not recharging, its only draining.

**Comment by Leander-0** [comment]
Lacks a theme or a reason besides "funny haha crab hands" in the radar, the crab hands block the way to jump form the area of the shutters, the uranium windows might look "OP" but have anyone with a laser and now you become a mice inside a microwave glass box, this is something anyone can recreate with a construct in an hour. also using radiation collectors is absurd since they would output like 4MW and also they require the small plasma tanks that are not provided in the clawbreaker. also on the photos provided none of the windows have grilles under them. 

Overall you should scratch up this ship and start again with a more thought off design.

and yeah the SMES dont have the connector port so they wont even charge.

**Comment by RealIHaveANameOfficial** [comment]
Thank you everyone for the feedback, I'll be updating the design and elaborating on the things brought up.

-Simplistic, too Construct-y
Honestly, this was the entire purpose of the Crab; An alternative jumping-off point compared to a Construct with a larger atmosable area via tinyfans with a large open bay. I added the crab arms/legs to provide solar power, and with the recent new addition of ore crabs, I actually thought it was quite a charming design, even if it's appearance is a bit crude or childish

-Grill under windows
A large part of the idea of this ship was it being fragile, to sort of help encourage one to replace it with something more robust. To that end though, I may want to add some rudimentary atmos for when someone tears down their windows. If pressed I might throw down grills under the windows, I'm not married to them not being there.

-SMES not charging
Completely missed that. Forgor they needed the cable thingy. Will fix.
-Radiation collector power output
Since my SMES wasn't charging I kept thinking I needed more and more rad collectors. I will fix it to have an appropriate amount.

-No plasma tanks available
Do radiation collectors not start with filled plasma tanks? I provided a plasma tank on the clawbreaker explicitly to refill the rad collector tanks. If they do not, I will add an appropriate amount of plasma tanks based on the updated amount of rad collectors.

-Weapons
Other black market ships come with weapons included, as does the pirate cove itself, so I didn't think it would be much of an issue to include some nice weaponry. Perhaps the Krammerers are overkill, and maybe too many cannonballs. I didn't want someone buying this vessel to want for firepower, given the fragility.

I'll update the designs and resubmit with a more fleshed out PR, if only because I still really want to buy these ships.

**Pull request closed without merging**
