### PR TITLE
Minor Pit additions

### PR DESCRIPTION
**Pull request by RealIHaveANameOfficial**
-Moves starting bell to a more reasonable location inside the commentator's box.
-Adds a microwave, donk pockets, and a hot food cart to the concession stand.

## About the PR

Round start bell is fun and should be in a good spot to encourage use.
Deep fried food at the arena. Seems thematically appropriate. Let there be fried donk pockets.
## Why / Balance

image
Very minor for now, but there have been talks about increasing PoI pull, and I think a good quality of life pass on some stuff might be nice. If this is welcomed I'll look into doing more of this on older maps, shuttles or etc.

## Technical details

-Removes the old bell and places a new one in a more appropriate location.
-Adds a microwave and donk pockets to the concession stand for quick munching, a deep fryer for event food, and a hot food cart for deliveries.
-No other changes.
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The round-start bell at the Pit has been moved to a more sensible location.
- add: The Pit now has a microwave, donk pockets, a hot food cart, and a deep fryer with oil.

### CODE REVIEW

**Review by Cheackraze — CHANGES_REQUESTED** [review]
no to the deep frier, not every place needs entire full kitchen we need to stop it, people just loot it and its not restaurant themed

**Comment by RealIHaveANameOfficial** [comment]
I could remove the microwave instead? It really is just the cooking machine until cooking gets the whole of its refactor so I might get rid of it specifically and leave the deep fryer

**Comment by Cheackraze** [comment]
> I could remove the microwave instead? It really is just the cooking machine until cooking gets the whole of its refactor so I might get rid of it specifically and leave the deep fryer

its more that the theme of the pit doesnt really necessitate a cooking station larger than the mini-booth it has. My idea was more for a full kitchen ship to dock and use the stall to just sell at, or to have very bare-minimum service available, and the fryer is like the premium cooking machine right now.

**Comment by RealIHaveANameOfficial** [comment]
> > I could remove the microwave instead? It really is just the cooking machine until cooking gets the whole of its refactor so I might get rid of it specifically and leave the deep fryer
> 
> its more that the theme of the pit doesnt really necessitate a cooking station larger than the mini-booth it has. My idea was more for a full kitchen ship to dock and use the stall to just sell at, or to have very bare-minimum service available, and the fryer is like the premium cooking machine right now.

I was considering that without any botany or kitchen, the only thing you'll be deep frying on the pit are vending machine snacks and those donk pockets. If a cooking ship were to dock with the pit, then they also already have a deep fryer. If the deep fryer and microwave are unanchorable (they are now in this PR if I did this right) then surely there's no issue there, yeah?

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
