### PR TITLE
Star Runner Expedition shuttle!

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About the PR

Adds a small class, cheap expedition vessel.
## Why / Balance

Adds a cheap alternative for expeditions. 29k price point.
## Media

image

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Starunner class expedition vessel!

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
I'm not sure whether the ship needs an AME? If thats the case I can always figure out a way to re-arrange something so I can fit one in, but I'll wait till I get feedback before fussing with it.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
- Your ships tile are "262" witch should fall in the Medium category.
- Atmos pipes are uncolored, you should use the "colornetwork" cmd to correctly color them.
- 3 Thrusters are unconnected/unpowred on init, you should connect them with LV Cables.
- Docking section should be lower as currently its will be blocked by the side section (thrusters)
- This is a recomendation but your atmos should have a pump going out from the canisters to regulate pressure.

Also price may be too low for an expedition ship as this is cheaper then the pathfinder.

**Comment by terezi-station** [comment]
cute, has potential and a good shape, but needs a general "feel" pass of decals, objects, and ideas to make it feel lived in and real. Also impossible to dock haha

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Most of the bugs/issues has been fixed, tho my recomendation still stands.

- Its should fall in Medium category. (269 Tiles)
- 29k is way too cheap in my opinion, tho this is just my opinion. (Note that from what i have read on discord, Expedition ship should be priced minimum at 50k and need to have an AME, but that is again what i read what check said on discord)

**Comment by RadiantFlash7** [comment]
> Most of the bugs/issues has been fixed, tho my recomendation still stands.
> 
> * Its should fall in Medium category. (269 Tiles)
> * 29k is way too cheap in my opinion, tho this is just my opinion. (Note that from what i have read on discord, Expedition ship should be priced minimum at 50k and need to have an AME, but that is again what i read what check said on discord)

Got super busy by stuff. Will make a few changes on the weekend.

**Comment by RadiantFlash7** [comment]
After thinking about this, I don't think the star-runner really fills any niches. It can't be cheaper then the cheapest expedition ship, so you'd lose like half your investment if you had to pay 50k for it. Ontop of needing an AME installed in it- I think I'll just close the PR. I've got another ship I want to work on, anyhow.

**Pull request closed without merging**
