### PR TITLE
Chisel (Update and Revamp)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Less than faithful revamp of the ICR Chisel in attempt to make it more enticing to choose over other salvage ships in the same category. Changes made to the ship:
- Atmos rework.
- Changed flooring and decals.
- Added double staged airlocks.
- Doubled the amount of thrusters.
- Replaced salvage vendor with salvage techfab.
- Moved material reclaimer to rec room.
- Replaced common plasma generator with [ship] version.
- Added second plasma generator.
- Added cell charger.
- Replaced substation with wall mounted one.
- Removed water cooler.
- Mapped withdrawal only wall-mounted ATM.
- Adjusted the price.
- Moved gyro and gravity generator to the bridge.
- Added button for bolting exterior airlocks.
- Rearranged ore processor setup.
- Replaced exterior light with sodium light.

Changes to salvage techfab:
- Moved drill to round start recipes.
- Moved PKA to round start recipes.
- Added recipe for crafting ore bags.
- Deleted some duplicated recipes.
- Enabled refining for fuel ores.

## Balance / Why
Apart from reasons mentioned in About section, some of the things weren't up to current mapping standards: lack of double-staged airlocks and outdated generators.

## Issues
SMES is causing flickering. Mapped MV cables under the generators, so upon purchase owner could switch generators to MV line.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Revamped ICR Chisel.
- tweak: Enabled additional recipes in salvage techfab.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
Ship owner: @Blackszedows
Just tagging you to make sure you're aware there's proposed changes on your ship.

**Comment by Wolfking6116** [comment]
> * Doubled the amount of thrusters.

Ugh. I love you.

**Comment by ErhardSteinhauer** [comment]
> > * Doubled the amount of thrusters.
> 
> Ugh. I love you.

Slapped additional rear thruster. Gotta accelerate fast.

**Comment by Pear120** [comment]
Why double airlock the blast doors? No other ship has this, and it not only defeats the purpose of the blast doors, but should tiny fans be removed, the blast doors themselves become useless.

**Comment by ErhardSteinhauer** [comment]
> Why double airlock the blast doors?

Maybe I overdone it.

> it ... defeats the purpose of the blast doors

Defeats how exactly? Double airlock somehow prevents you from getting into space or move salvage from platform into the ship?

> should tiny fans be removed, the blast doors themselves become useless.

Logic gates can read and set conditions of a blast door just like it can do it for regular airlock. You can create a functional logic gate operated double-staged airlock that has blast doors on one of it's ends when/if tiny fans are gone.

**Comment by ErhardSteinhauer** [comment]
Still kinda can't decide which locker would be best for bridge: QM's, captain's or salvager's

**Comment by MoistBiscuits** [comment]
> Still kinda can't decide which locker would be best for bridge: QM's, captain's or salvager's

QM's is best imo, its a slavagers ship so the colours fit plus the previous version used the QM's hardsuit locker. Ships with a full bridge make more sense as having a captains equipment.

Also love how their isn't any diagonal walls inside on the new model, they are a bit strange with collision inside a ship.

**Comment by Pear120** [comment]
> Defeats how exactly? Double airlock somehow prevents you from getting into space or move salvage from platform into the ship?

The point of blast doors on mining ships is easy in/out, the ability to just throw loot into your ship. There's no point in having them if there's just a second airlock in the way taking up cargo space.

> Logic gates can read and set conditions of a blast door just like it can do it for regular airlock. You can create a functional logic gate operated double-staged airlock that has blast doors on one of it's ends when/if tiny fans are gone.

Once tiny fans go extinct, blast doors on mining ships should too, unless you have a depressurized cargo bay. It doesn't matter that you can logic gate them, they just don't make sense to have when a double airlock does the exact same thing, except with more convenience. With a blast door airlock, you'd have to manually hit a button to cycle it every time if the blast door is closed. It's inconvenient and stupid all for the sake of removing tiny fans. Personally, I feel like cargo bays like this should be the ONLY exception for tiny fans, purely for the open-to-space cargobay feel. Like, fuck, we have bluespace travel and crazy tech shit, why can't we have Star Wars hangar forcefields so we can have our cool and useful cargobays??

**Comment by ErhardSteinhauer** [comment]
> The point of blast doors on mining ships is easy in/out, the ability to just throw loot into your ship. There's no point in having them if there's just a second airlock in the way taking up cargo space.

You can turn on the conveyor belt and throw your loot on it, the belt will get your loot into your ship just fine. Less than a second of a delay from external airlock isn't exactly an obstacle.

> (part about staged airlocks without tiny fans)

So the setup I'd prefer to make is the one that forces you to depressurize the airlock chamber before opening it so not only to avoid wasting breathable gas, but also to avoid being propelled into space with said gases (depend on the size of the chamber though). In such setup blast doors would be marginally preferable to airlocks as external doors since they will allow you to keep the bay open until you return to your ship from EVA.

> Star Wars hangar forcefields so we can have our cool and useful cargobays

Holofans do exist. But also this is hella boring.

**Comment by ErhardSteinhauer** [comment]
> > Still kinda can't decide which locker would be best for bridge: QM's, captain's or salvager's
> 
> QM's is best imo, its a slavagers ship so the colours fit plus the previous version used the QM's hardsuit locker. Ships with a full bridge make more sense as having a captains equipment.
> 
> Also love how their isn't any diagonal walls inside on the new model, they are a bit strange with collision inside a ship.

Haven't touched the hardsuit locker. Pros for having salvager's locker there is in getting second full mining kit (although you can print it on salvage techfab once you get enough resources). Cons - it contains items that usually aren't used by players.

QM's locker is almost empty, apart from filled utility belt.

**Comment by Spatulaodoom** [comment]
The changes as currently displayed would make me less likely to choose the Chisel. In short, it has less usable space and more superfluous options for a ship that is more expensive to buy and to run.

The old chisels main workspace (including exterior catwalkl has 50 open tiles, not including space taken up by structure with 3 diagonals (a pain but do offer a bit of usable space). The new version has 41, and no diagonals. Call it ten less.
The air tank dispenser is superfluous. A salvage ship has access to so many sources of air tanks why would you bother?
The cell charger and recharger are superfluous except under fairly specific use cases. I personally use a recharger most rounds for retrolasers, but what else might it be used for, and should it be there by default?
The cell charger has a conceptual reason to be there, but does it have a practical one? Floodlight batteries and nothing else, I guess.

Does the new versions ore processor still have the dump ore bag onto ground and magnet option, or are you going to have to load it by hand? The Chisel and Bulker both use the conveyor belt to bring dumped stuff into contact the same way station waste reclaimers work.

I do appreciate more thruster, but 7 might be overkill. It's most of why a second generator is required, yes?

Not going to comment on the techfab. I consider it superfluous, but others might get use.

If the PR  is about double airlocks and ship generators being required, then just do that.

**Comment by ErhardSteinhauer** [comment]
> The old chisels main workspace (including exterior catwalkl has 50 open tiles, not including space taken up by structures, and 3 diagonals (a pain but do offer a bit of usable space). The new version has 41, and no diagonals. Call it ten less. A pretty big difference

Work space was eaten mostly by the double-staged airlock on the left. While loss of work space is noticeable imo there is more than enough space left as is: 1 tile can hold 2 chests (and each chest can hold up to 30 items/stacks) or about 3 canisters with out spamming collision. Interior diagonal walls imo is cancer and mustn't exist.

> The air tank dispenser is superfluous. A salvage ship has access to so many sources of air tanks why would you bother?
The cell charger and recharger are superfluous except under fairly specific use cases. I personally use a recharger most rounds for retrolasers, but what else might it be used for, and should it be there by default?

Sure, might as well get rid of that tank dispenser (it's mostly there for double-emergency tanks, but can easily get some on Frontier, your hired through console crew will be out of luck but whatever). Recharger is more of the convenience too, but, yeah, might not be fitting thematically.

> Does the new versions ore processor still have the dump ore bag onto ground and magnet option, or are you going to have to load it by hand? The Chisel and Bulker both use the conveyor belt to bring dumped stuff into contact the same way station waste reclaimers work.

Conveyor belt is still there: dump your bag on the table by the processor, belt will carry ores to the processor.


Even with additional 5 thrusters it still feels cumbersome and slow, but not as painful as it was with 4. With default power setup you have wiggle room for 2 additional thrusters before you start accumulating fuel inefficiency penalty, so once you add 3rd additional thruster, you might as well add 2-10 more since you sort of have to upgrade generators at that point anyways.
New price tag is almost exclusively due to additional thrusters. Can't run those on 1 plasma generator without severe fuel inefficiency penalty. With double plasma gens, you can lower target power output to 10 kW on each: fuel consumption wont go down all the way back to single plasma gen levels, but will noticeably extend how long fuel supply will last. But it doesn't matter, since you got practically infinite plasma supply as a miner. I would love to use a single uranium generator instead of 2 plasma ones, but it's rather difficult to make an aesthetically pleasing radiation shielding in that room.

**Comment by Spatulaodoom** [comment]
Conceptually I think of the Chisel as a deluxe Prospector that is better at salvage. I do think that eating up all the space, not just with the airlock, but also extra machines like the lathe and extra generator and

Here's a thought. 
It's really a pretty small ship, does it really need three entrances?

Why not simply get rid of the starboard side airlock entirely, and widen the aft one to three tiles?
You can get the space on the aft by making that ore processor change.
You can bump the wall beside it out one more to fit the techfab in beside the ore processor.
Put the gyro back where it was with the other engine components, and the reclaimer back in the workspace where it really should be. The air tank too. That lets you get rid of the weird little bump in the wall between cockpit and main floor.

Why are there four conveyor controlls while there appears to only be three conveyors?

Aesthetics. I'd keep the new nicer flooring in the break/engine room, but switch back to clean tiles in the industrial work area. It makes sense to have that be a tough no-nonsense area, and keeps down on the visual clutter. It's hard enough to see through the clutter at the best of times.

I might have to figure out how to do ship modeling on m potato laptop eventually.  This is kind of fun.

**Comment by ErhardSteinhauer** [comment]
> I do think that eating up all the space, not just with the airlock, but also extra machines like the lathe and extra generator etc, would kill its usability.

Those machines don't occupy extra space: salvage techfab replaced salvage vendor, space for the second generator was freed by replacing substation with wall-mounted version. Again, I don't really see why and how going from roughly 50 tiles to roughly 40 would "kill" the ship functionality. Hell, nothing stops you from bolting open red airlocks on the left to get additional 6 tiles worth of space.

> the weird little bump in the wall between cockpit and main floor.

Part of the original design, I like it, I'll keep it.

> Why are there four conveyor controlls while there appears to only be three conveyors?

FAFO

> Aesthetics. I'd keep the new nicer flooring in the break/engine room, but switch back to clean tiles in the industrial work area.

Makes sense, I'll see what I can do.

**Comment by ErhardSteinhauer** [comment]
I'll convert this PR to draft until the design is finalized.

**Comment by ErhardSteinhauer** [comment]
A'ight, I feel like I've finalized the design, going to open PR back.

**Comment by ErhardSteinhauer** [comment]
> > the weird little bump in the wall between cockpit and main floor.
> 
> Part of the original design, It stays.

In fact, the same thing goes for excessive docking ports and smuggling compartment "everybody knows about". All those things are part of the original design and imo is what makes up the "soul" of this ship which I very much would like to preserve.

**Comment by ErhardSteinhauer** [comment]
I believe this PR is ready for review.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
