### PR TITLE
Gat Cut

### PR DESCRIPTION
**Pull request by dvir001**
Cut the gat

## About the PR
The Gut was Cut

### CODE REVIEW

**Comment by Cheackraze** [comment]
hm not ideal, they will just inherit the base staticprice of 20 this way and be worth even more rofl.  If anything lower it to 1 or something idk

really we just cant let this kind of entity spam happen to the detriment of the server.  This has been a fundamental problem with botany in vanilla SS14 since the dawn of the job role sadly.

**Comment by mirddes** [comment]
i dont think it's a problem with the price.
if it's not gatfruit, it'll be something else.
the solution is goodRP in response to blatant bullshit.
im gonna farm gatfruit with cows on the cargopad at the cargo depot to avoid massive stacks of entities.
if pirates and SEC want to travel all the way out there to play with kitchenfarm's militia, then that's goodRP.
farming 16k gatfruit at station with no opposition from SEC is not goodRP, BUT FUCK IT WAS A FUN ROUND.

**Comment by mirddes** [comment]
> > hm not ideal, they will just inherit the base staticprice of 20 this way and be worth even more rofl. If anything lower it to 1 or something idk
> > really we just cant let this kind of entity spam happen to the detriment of the server. This has been a fundamental problem with botany in vanilla SS14 since the dawn of the job role sadly.
> 
> Set to 1, please merge before they crash the server again.

the explosion crashed the server. the entities lagged the ship, but not the rest of the server from what i can tell?
nerfing the price  into the ground makes no sense, nerfing it by up to 90% probably makes sense
ultimately gatfruit isn't the problem.
like cheackraze said its a systemic problem with botany since it's inception.
and money only makes it worse.
if its not gatfruit, ill be wood, or wheat, or cheese when we can breed cows.

maybe cargo bounties will do the trick, it sounds promising.

skill issue of not butchering the animals was the only reason the ship never sold and any of this became an issue worth noticing.

**Review by Cheackraze — APPROVED** [review]

**Comment by sTiKyt** [comment]
But how would that help with crashes? People can still grow tons of those and if they explode server crashes, right?

Maybe some way of additional stacking would make sense

For example, allow stack on the ground be of any size, so no matter how many thousands of same plant are just in 1 entity

But disallow picking that entire stack up, and pick up 30(or whatever max stack size is supposed to be) instead

**Pull request merged**
