### PR TITLE
Botany: drop items when harvesting or clipping seeds

### LINKED ISSUE #1910: Hoverbike item storage glitch
## Description
Playing as a wheelchair-bound character, I was looting dungeon mobs while riding a hoverbike. The items would stick to the hoverbike if from lootbox containers (punk's bags, etc).
**Reproduction**
1. Get a hoverbike
2. Go on expedition with punks, cultists, explorers, salvagers, syndies, etc (any humanoid one)
3. Kill a humanoid
4. Loot the body and open the bag while on the bike.

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Explicitly drops items next to the user when harvesting plants or getting their seeds.

## Why / Balance

Gets stuck on vehicles (ATV, wheelchair, etc.).

Because your character is parented to the vehicle, anything spawned at its location will inherit the parent of the vehicle, thus you drag it around.

Fixes #1910.

## How to test

1. Spawn hydro trays, wheat seeds and a wheelchair.  Get in the wheelchair.
2. Grow wheat.
3. Clip wheat, seeds should fall on the floor.
4. Harvest wheat, wheat should fall on the floor.
5. Take hydro tray with grown wheat outside into space.
6. Clip wheat, harvest wheat, both should be floating in space.
7. Spawn ClothingBackpackPunkLootA, open on wheelchair, contents should fall on the ground (or in space).

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Harvesting while riding vehicles or wheelchairs no longer spawns produce attached to the vehicle.
- fix: Using loot boxes while riding vehicles or wheelchairs no longer spawns the items on the vehicle.

### CODE REVIEW

**Comment by dvir001** [comment]
Killer tomato?

**Comment by whatston3** [comment]
Think I found a better function, fewer changes, also fixing issues with SpawnItemsOnUse.

**Comment by whatston3** [comment]
Fixes #1910.

This isn't a general solution, but we can whack-a-mole vehicle-related popups with the same strategy.  Simple enough, shouldn't be a huge issue.  Good to go.

**Review by dvir001 — APPROVED** [review]
Logical

**Pull request merged**
