### PR TITLE
Mail Handheld Rapid Parcel Delivery System

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### New entities:
- Mail Capsules: a robust container to store mail, documents, books, cash of food.. Sticks to surfaces, breaks and spills contents upon retrieval, doesn't do damage on impact. Can be crafted at Service Techfab.
- Mail Rapid Parcel Delivery System (RPDS): a China Lake derivative launcher that shoots only mail capsules. fr, doesn't accept grenades.

### Changes:
- Visual change to Nyano's Mail Envelopes: they are 0.7 of their original size (done in .yml).
- Added Mail RPDS and box of mail capsules to Mail Vendomat.
- Added Mail Capsule to Service Techfab.

### How to use:
1. Put mail envelop/document/book/cash/food in mail capsule.
2. Put mail capsule in Mail RPDS (holds up to 4).
3. Take aim and shoot.

## Why / Balance
To enhance Mailman gameplay. Fphoomp.

### Video demonstration:
https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/c6613f24-7107-4bc9-8706-3e27d53e3d53

### Screenshots*:
image
image
image
`*` screenshots and video above a bit outdated - I resprited the capsule.:
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
Some changes to Nyano's base_mail.yml and lathe.yml

**Changelog**
:cl: erhardsteinhauer
- add: NT is concerned with work performance of Mail Delivery Service and issued new equipment to enhance it: mail capsules and mail capsule launcher.

### CODE REVIEW

**Comment by dvir001** [comment]
Do not merge till upstream update to avoid sizes and grid nightmare

**Comment by Everturning** [comment]
we need a way to put stuff in letters and then be able to send those letters to the mail department
like, a machine that prints empty letters and can then bluespace filled letters to the mail maker

**Comment by ErhardSteinhauer** [comment]
Updated to the most recent build

**Comment by ErhardSteinhauer** [comment]
Oh, wow, test packaging test appears to be working

**Review by dvir001 — APPROVED** [review]
Works as intended

**Pull request merged**
