### PR TITLE
Empty Welders

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
For https://github.com/new-frontiers-14/frontier-station-14/pull/1720

## Why / Balance
Why are we getting free weld.

## How to test
Print from autolate a welder, comes empty.

## Media
N/A

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: Printed welders now comes empty.

### CODE REVIEW

**Review by whatston3 — APPROVED** [review]
Works.

**Comment by jimmy12or** [comment]
But... why? What is wrong with welders starting off with welding fuel?

**Comment by dvir001** [comment]
> But... why? What is wrong with welders starting off with welding fuel?

Where did the fuel came from?
Fill it with a weld tank.

**Comment by ray-boop** [comment]
you need plasma to make a welder... thats where the fuel comes from

**Pull request merged**
