### PR TITLE
Port researchable syringe gun (DeltaV#2169, DeltaV#2249)

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Ports the syringe gun and mini-syringes as researchable technologies from Delta-V, reduces maximum mini syringe volume to 5u.

Many thanks to @Radezolid (DeltaV#2169), @Stop-Signs (DeltaV#2249) for the original PRs.

## Why / Balance

Fun!  Cheeky chemistry shenanigans.

## How to test

1. Unlock technologies via an R&D server.
2. Syringe gun and mini syringes should be printable from a medical techfab and an emagged protolathe.
3. Look at the mini syringe, confirm it's only loadable to 5u.

## Media

|==|________|----( ' ___  ' )

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Radezolid and Stop-Signs
- add: The syringe gun and mini syringes are now accessible through research.

### CODE REVIEW

**Comment by dvir001** [comment]
image

One dart with 5u amatoxin

**Comment by whatston3** [comment]
> One dart with 5u amatoxin

Still better than an average McCargo meal.

**Comment by dvir001** [comment]
Hold up on merge, this will be a new meta issue for combat,
Need a slow down on inject.

**Comment by Radezolid** [comment]
Keep in mind that CLF3 can be made by injecting chlorine and fluorine into people. It do be scary.

**Comment by whatston3** [comment]
Injection rate reduced to 0.5u init, 0.5u/2s.  Seems really slow, but works better for medical drips - 15u of ranged, single-target chemical delivery.

> Keep in mind that CLF3 can be made by injecting chlorine and fluorine into people. It do be scary.

I think the existing crossbow bolts are worse, at the downside of being fiddlier to use.

**Review by dvir001 — APPROVED** [review]
Honestly fuck it, worst comes we make it a rare find or something.

**Pull request merged**
