### PR TITLE
Gasbender and Searchlight Minor Tweaks

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### Searchlight changes
- Freezer Atmos Markers mapped to morgue.
- Mapped health analyzer.
- Mapped withdraval-only atm.
- Replaced generator with proper one.
### Gasbender changes
- Removed microwave.
- Removed soda dispenser. Mapped water cooler instead.
- Removed medical bay. Mapped cinema lounge room instead.
- Removed paramedic role.
- Mapped withdraval-only atm.
- Reduced amount of loose materials.

## Why / Balance
Changes to Gasbender were made to encourage interaction with medical and chef players.
Changes to Searchlight - mostly QoL.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**
:cl: erhardsteinhauer
- tweak: NC Gasbender tweaks: replaced medical bay with cinema lounge, removed microwave, added withdrawal-only ATM.
- tweak: NM Searchlight tweaks: added withdrawal-only ATM, temperatures in morgue lowered, added health analyzer.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
image
Do me a favor and replace your pacman on the search light with the ship version.  The ship version starts anchored, half filled, and running.

**Comment by MagnusCrowe** [comment]
It has come to my attention that the water coolers come with built in paper cup dispensers.  Do with that knowledge what you will.

**Comment by ErhardSteinhauer** [comment]
> image Do me a favor and replace your pacman on the search light with the ship version. The ship version starts anchored, half filled, and running. Do that to the gasbender too if it has a normal pacman. After that's done, I'll merge it.

Done.

**Comment by ErhardSteinhauer** [comment]
> It has come to my attention that the water coolers come with built in paper cup dispensers. Do with that knowledge what you will.

Holy shit, that's true.
P.S.: I did nothing with that knowledge.

**Review by MagnusCrowe — APPROVED** [review]
Thanks

**Pull request merged**
