### PR TITLE
Floor safe

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Adds constructible floor safe in 2 variants: no access restrictions and captain locked. Floor safes can be hidden under carpets/tables/machines.

## Why / Balance
To support our local crime lords.

## How to test
Build one.

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/a0e2ef33-314d-4539-8780-0d93b5877a71

- [x] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
none afaik

**Changelog**
:cl: erhardsteinhauer (discord)
- add: Added constructible floor safe.

### CODE REVIEW

**Comment by dvir001** [comment]
Can you see it with a t-ray?

**Comment by ErhardSteinhauer** [comment]
nope

**Comment by ErhardSteinhauer** [comment]
Isn't t-ray stuff hardcoded?

**Comment by dvir001** [comment]
> Isn't t-ray stuff hardcoded?

Ill need to look again

**Comment by ErhardSteinhauer** [comment]
Closing this PR until I figure out how to add a counter-play for safes, which might take awhile.

**Pull request closed without merging**
