### PR TITLE
Add the Valentine

### PR DESCRIPTION
**Pull request by VividPups**
## About the PR
Adds the Valentine Pistol
## Why / Balance
The original idea of this gun was to have it added to the T2 gun safe to help balance out the changes of getting the other guns than just a shotgun however, I do not know how to add that to that loot pool so, I also seem to notice that there isn't a lot of other Legal firearms on Frontier/SS14 within itself.  So I am attempting to make More and different varieties of the current guns to add more Legal weapons and eventually illegal ones) at the same time, I want to make more references to beloved game franchises and irl guns that we love.  This is to help expand on the current quite small Weapon list. Help give a lot more options when mapping 

This gun is based on the Mk58
Firing rate of 5  with a magazine size of 10 + 1 
So PR will add the Valentine pistol 
 "There is S.T.A.R embedded inside the wooden and textured pistol grip, with a Silver Barrel. Chamber in .35 auto."
 Firing rate of  2.5 
 Magazine size 10 + 1 
This is Jill Valentine's Variation of the pistol 

I have tested it with all 35 auto ammo and seems to work 
Also a NonLethal Verison of the gun 

## Technical details
adds the Pistol.yml file 
## Media
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes in-game

**Changelog**

### CODE REVIEW

**Comment by dvir001** [comment]
RSI Broken

**Comment by VividPups** [comment]
How is it broken?

**Comment by dvir001** [comment]
> How is it broken?

RSI Validator / Validate RSIs (pull_request)

**Comment by VividPups** [comment]
I saw that, however, I do not know how to fix it. But, by reading it. It sounds like it's something with the Copyright?

**Comment by TsjipTsjip** [comment]
> I saw that, however, I do not know how to fix it. But, by reading it. It sounds like it's something with the Copyright?

I think the test checks if you used a valid license type. Your license given is not one of the ones that's allowed, and you should check the output for which one is most appropriate and aligns most closely to what you have in mind.

**Comment by VividPups** [comment]
I was thinking that also, Hopefully this is the fix for it

**Comment by VividPups** [comment]
I also realize that there isn't an actual way to obtain The Valentine. I figure for a trial It would be added to the Liberty station. until more POI/Events/Dungeons. This might help let people know about the gun

**Comment by VividPups** [comment]
The RSI has been fix

**Comment by dvir001** [comment]
Still need to inspect this for balance, adding @MagnusCrowe on it also.

**Pull request closed without merging**
