### PR TITLE
The NC Bullseye

### PR DESCRIPTION
**Pull request by SirMcSlushers**
## About the PR

I added a ship called the NC Bullseye.

## Why / Balance

Its a miniature restaurant slapped to a firing range with some practice disablers.
31000 Spesos, Medium. The kitchen button toggles the shutters and secure window.
That way someone can't just grab the disabler and walk out as easily.
Captain, Botanist, Chef, and Valet jobs available.

## How to test

Load it up and check it out.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by dvir001** [comment]
Remove:
Captain spawn
Music vend machine
Glass half windows over machines
None anchored Hydroponics
The hidden sin in the wall

**Comment by SirMcSlushers** [comment]
Believe i've done everything ya asked.

image

**Comment by dvir001** [comment]
The Hydroponics wrong ones still, and don't map extra boards on the floor

**Comment by SirMcSlushers** [comment]
Ya mighta be checkin' the not latest update 
And if ya meant the one that was infront of the desk, it was a valet
I set the hydroponics to None in it's flags

**Comment by SirMcSlushers** [comment]
And with the boards whole idea was for it to look incomplete, so ya had to do some work. Otherwise it'd just be 4 hydros and the seed extractor, which I could do.

**Comment by dvir001** [comment]
> And with the boards whole idea was for it to look incomplete, so ya had to do some work. Otherwise it'd just be 4 hydros and the seed extractor, which I could do instead.
> 
> image

Yes and use *the achorched hydrotray that are a diffrenct prototype and has black color*

**Comment by SirMcSlushers** [comment]
> > And with the boards whole idea was for it to look incomplete, so ya had to do some work. Otherwise it'd just be 4 hydros and the seed extractor, which I could do instead.
> > image
> 
> Yes and use _the achorched hydrotray that are a different prototype and has black color_

**Comment by SirMcSlushers** [comment]
oops, gotcha.

**Comment by SirMcSlushers** [comment]
image

**Comment by dvir001** [comment]
Mind adding a guide book for the ship?

image

**Comment by SirMcSlushers** [comment]
Sure, lemme figure out how to do that.

**Comment by dvir001** [comment]
> Sure, lemme figure out how to do that.

https://github.com/new-frontiers-14/frontier-station-14/pull/1344/files#diff-8c5d42a5a76641be89a6e804c1aa57cbba76dcf18fb92c41fbcf25562e345198

Like in here, 3 files edits

**Comment by SirMcSlushers** [comment]
Added a Docking Area
image
Fixing something real quick

**Comment by SirMcSlushers** [comment]
Any idea how to fix this?
image

**Comment by ErhardSteinhauer** [comment]
> Any idea how to fix this? image

You are missing definition in ftl file `\Resources\Locale\en-US\_NF\guidebook\guides.ftl`
Also can you keep guides in alphabetical order?

**Comment by SirMcSlushers** [comment]
Gotcha, thanks

**Comment by ErhardSteinhauer** [comment]
> > Any idea how to fix this? image
> 
> You are missing definition in ftl file `\Resources\Locale\en-US\_NF\guidebook\guides.ftl` Also can you keep guides in alphabetical order?

So Bullseye should be under Brigand...
Looks like you haven't updated your branch in a while

**Comment by SirMcSlushers** [comment]
Yeah I should do that since the update came out recently

**Comment by SirMcSlushers** [comment]
image

**Comment by SirMcSlushers** [comment]
I believe it's ready for proper review. Lemme know what else I fucked up.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
The sell and buy prices are nearly identical...the buy price needs to be raised to about 40k.
image
This door should not be security locked...nobody will be able to use it except NFSD.
image
Mapping sin, don't put posters on windows.
image
Not a 2 stage airlock...door to space...spooky.
image
This button on top of a poster looks pretty jank, don't do that.
image
Not a 2 stage airlock, door to space, spooky.
image
Cockpit windows extra thick for some reason and the diagonal portions have no grilles.
image
Walls and windows together...cant's see through a wall.
image
What's the point of these 1 stage airlocks behind the targets?  also...not a 2 stage airlock, door to space, spooky.
image
Glass under corners in space really only has the intended effect if they arent lit up, you should just use lattice instead in this case.
image
Remove the custom filled locker.  If you want an emergency wall locker, use the prefilled version.
image
This thruster placement is cursed...find a way to migrate it to the other side of the ship....
image
There's space down here for it.
image
There's an inconsistency in the type of windows you're using... you should probably go with shuttle windows and leave out the reinforced windows.
image
The standing light post embedded in the window is not good.  Use a wall light and put it on a solid wall.
image
Lights on doors, not good.
image
I recommend removing the normal hardsuit locker and instead placing a cool botanist EVA suit on the table. :)

Notes on Atmos:
1. You're running pipes down the walls, don't do that, they need to be accessible.
2. You're missing a scrubber from your main dining room. Probably want a couple, its a big room. Same goes for vents and scrubbers in the dart room, huge room serviced by 1 vent and 1 scrubber...not ideal.
3. Make sure your air alarms are all hooked up properly, I didn't check but you're going to be adding some stuff so double check all that.
Notes on Electrics:
1. One APC for this size ship is not ideal, you should consider sharing the load so if you have one failure the whole ship doesn't lose power.

Where's the station records computer?
Remove the botanist and chef job and spawns, instead use Contracter, Pilot, and Mercenary jobs and spawns.

**Comment by SirMcSlushers** [comment]
I'll get to it tomorrow some time probably.

**Comment by SirMcSlushers** [comment]
Im gonna probably just redo it from the ground up eventually. Getting burnt out.

**Comment by MagnusCrowe** [comment]
Going to close this PR for now.  Feel free to re-open it when/if you come back to it.

**Pull request closed without merging**
