### PR TITLE
Disable health icons in HUDs

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Band aid fix to a problem: if you wear any glasses with medical HUD, health status icon (not to be confused with health bar) is displayed on top of speech bubbles, which makes it nearly impossible to tell, if a person is typing something in chat.

Small tangent: as of right now health status icon do not provide any additional information - all relevant information can be gleamed either from health bar or from visual state of a character or from health analyzer, which begs a question why health status icon even a thing.

## Why / Balance
In a game where all communications are text based it is fairly important to know if the person is trying to talk to you.

## How to test
1. Spawn.
2. Wear any glasses with medical HUD (medical HUD, secmed HUD, infoshades).
3. Start typing in chat.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Moved health status icons for medical HUDs.

### CODE REVIEW

**Review by dvir001 — APPROVED** [review]
Is this a Frontier issue that got fixed on upstream or an issue that they have also?

Either way this is fine.

**Comment by arimah** [comment]
The health bar uses colour to communicate information. Per accessibility guidelines, one should never rely on colour _alone_ to deliver important information. A secondary information channel, such as an icon or text, must be present. That's why there are icons too. They're important.

**Comment by ErhardSteinhauer** [comment]
> Is this a Frontier issue that got fixed on upstream or an issue that they have also?
> 
> Either way this is fine.

No, the same problem is present on wizden.

**Comment by ErhardSteinhauer** [comment]
> The health bar uses colour to communicate information. Per accessibility guidelines, one should never rely on colour _alone_ to deliver important information. A secondary information channel, such as an icon or text, must be present. That's why there are icons too. They're important.

Health bar uses color and **_fill levels_**. The icon in question has 3 states: healthy, in crit (easily identifiable by character sprite and gasping emote) and dead (again, easily identifiable by character's sprite and upon closer inspection of a body). The "healthy" status icon not only doesn't provide additional information, but also prevent you from gaining vital piece of info - if some one is typing.

**Comment by ErhardSteinhauer** [comment]
Well, alternatively, I can make "healthy state" of status icon completely transparent.

**Comment by whatston3** [comment]
A few alternate solutions:
* Stack the health icon on the right (you might now have three icons on the right - job icon (sec), health (med), wanted status (sec, rare?)
* Start the left accumulator in StatusIconOverlay at one icon's height, offsetting the health icon lower on the overlaid character.

Also, could you inherit ShowMedicalIcons in your punk infoshades?

**Comment by ErhardSteinhauer** [comment]
> A few alternate solutions:
> 
> * Stack the health icon on the right (you might now have three icons on the right - job icon (sec), health (med), wanted status (sec, rare?)
> * Start the left accumulator in StatusIconOverlay at one icon's height, offsetting the health icon lower on the overlaid character.

This would be a much better solution, but it requires C# magic and I wasn't born with a talent for that.

> Also, could you inherit ShowMedicalIcons in your punk infoshades?

I couldn't because infoshades display both organic and silicon health, and base game parents for those 2 are incompatible.

**Comment by whatston3** [comment]
image
Outside of being off by one (why the SecurityIcon prototype has an offset of 1 I don't quite know), this is how it looks with an offset of 8 pixels.

image
And without any speech bubble.

image
And with only medical icons shown.

**Comment by ErhardSteinhauer** [comment]
I'm in awe!
Also would it be reasonable to perch the icon above health bar on the left side?

**Comment by whatston3** [comment]
> I'm in awe! Also would it be reasonable to perch the icon above health bar on the left side?

It's a hack as it is - the SSD icon (green ZZs) is also displayed as a StatusIcon on the left, and this'll muck around with that (we can get it to display "normally" but it'd be hacks on hacks).  If you wanted things positioned beyond one stack of icons on the left and one on the right, it's possible but needs extra changes.

Perhaps talking could also be displayed as a status icon with medical huds and you could avoid this offset.

image

**Comment by dvir001** [comment]
> > I'm in awe! Also would it be reasonable to perch the icon above health bar on the left side?
> 
> It's a hack as it is - the SSD icon (green ZZs) is also displayed as a StatusIcon on the left, and this'll muck around with that (we can get it to display "normally" but it'd be hacks on hacks). If you wanted things positioned beyond one stack of icons on the left and one on the right, it's possible but needs extra changes.
> 
> Perhaps talking could also be displayed as a status icon with medical huds and you could avoid this offset.
> 
> image

Seems like a bigger issue for Upstream X_X

**Comment by ErhardSteinhauer** [comment]
> Seems like a bigger issue for Upstream X_X

Nah, they (and by they I mean a very specific young-adult person) called it a "non-issue", so I doubt it'll be fixed anytime soon.

**Comment by Cheackraze** [comment]
> > I'm in awe! Also would it be reasonable to perch the icon above health bar on the left side?
> 
> It's a hack as it is - the SSD icon (green ZZs) is also displayed as a StatusIcon on the left, and this'll muck around with that (we can get it to display "normally" but it'd be hacks on hacks). If you wanted things positioned beyond one stack of icons on the left and one on the right, it's possible but needs extra changes.
> 
> Perhaps talking could also be displayed as a status icon with medical huds and you could avoid this offset.
> 
> image

Could we have the SSD icon (the Zzz) share the same position as the chat bubble? Logically these are both indicators of the same state of activity, and serve the same "Level of Player-Alertness" indication? That way we are still reserving space for any other potential overlapping visualizations.

**Comment by whatston3** [comment]
> Could we have the SSD icon (the Zzz) share the same position as the chat bubble? Logically these are both indicators of the same state of activity, and serve the same "Level of Player-Alertness" indication? That way we are still reserving space for any other potential overlapping visualizations.

image

Looks alright.  Everything's up on `whatston3:2024-08-Disable-Health-Icon-suggestions`.  I think it's alright to go through, changes are fairly minimal, but it's a tad gross.

**Comment by ErhardSteinhauer** [comment]
> Looks alright. Everything's up on `whatston3:2024-08-Disable-Health-Icon-suggestions`. I think it's alright to go through, changes are fairly minimal, but it's a tad gross.

Looks good. Probably should go with **_your_** variant.

P.S.: tbh I personally still prefer that icon to be flatout disabled bcz it doesn't provide any useful info rn imo (maybe it'll change once virology dlc will hit the shelves after surgery update).

**Review by whatston3 — APPROVED** [review]
Barring cleanup, I think this is good to go.

**Pull request merged**
