### PR TITLE
Common parent for Contraband Clothing

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Added abstract clothing: ContrabandClothing that has Contraband and FactionClothing (commented out) components and distributed it as a second parent.

## Why / Balance
Clean up

## How to test
Dress in any contraband garb, examine character's list of factions.
Teleport to listening point bravo or ftl to an expedition with syndicate or cult factions - mobs should be hostile towards the character.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
not needed

### CODE REVIEW

**Comment by VividPups** [comment]
Lol, like fallout NV type of shit?

**Comment by ErhardSteinhauer** [comment]
Yep, exactly like it. But without message that "You dressed like Fiend".

**Comment by VividPups** [comment]
Would the npcs start attacking if your wearing clothing's and then shoot them?

**Comment by ErhardSteinhauer** [comment]
Don't think so. I forgor to give them the same component the monkey mob has on them. Will fix it in different PR though.

**Comment by VividPups** [comment]
Well, I was thinking it would be a neat future. But just thinking of it... it would be abuse so badly

**Comment by ErhardSteinhauer** [comment]
Yep, you just can walk up to npc and strip it.

**Comment by ErhardSteinhauer** [comment]
Yeah, gl with that: seems C# heavy.

**Comment by ErhardSteinhauer** [comment]
linter is finally happy with me

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
