### PR TITLE
Derelicts, a new way to make money in salvage

### PR DESCRIPTION
**Pull request by Crysoskis**
**Preface:** This PR is an open document, any suggestions or additions you wish to may are encouraged!

## About the PR
The main aim of this PR is to enhance the salvage experience, by adding new valuable salvage objects for players to gather, instead of just crates, canisters or regular machines. The ones in this PR are mainly meant for a new class of "derelict" vessel which will randomly generate similar to how normal asteroids/debris spawn, at a very decreased rate.

Included in this PR are some examples of what I believe are decent examples of what types of "derelict" vessel, such as a ship or station. These are only meant as examples to convey an idea, not a concrete set of rules.

I admit I will need help getting this fully implemented, the biggest point being the vessels themselves sense I would prefer there to be a very large variety of them. The requirements of a derelict vessel will be much more loose to get added I feel, but they should still follow a level of balance, such as equivalent danger to the value of a vessel. What the vessel is can be whatever the creator wants it to be, not necessarily a ship if they have different ideas.

## So, what's in this thing anyways?

Here is a showcase of the new objects this PR adds for salvagers to find and gather:

# General Salvage
image

Common parts of any ship, in smashed and broken states. Entirely nonfunctional, and worth either equal or slightly less then their functional counterparts.

The pictured RTG, SMES, Substation and APC all have a spawner prototype that can spawn a regular functioning version of the machine instead of its destroyed variant. This can allow for a ship's powernet to have a chance to be partially intact at random, adding some variety.

# Preserved Salvage 
image

A group of very old, nonfunctional machines in decent enough condition to make them quite valuable. All of these machines minus the terminal have a spawner prototype, that can rarely spawn one of them, more commonly spawn their "ancient" variant, or not spawn anything at all.

# Ancient Salvage
image

The less valuable variant of the old machines, meant to spawn more frequently then their preserved counterparts.

# Sealed Shipping Crates
image

The golden egg of any salvage operation. These large, cumbersome containers are very valuable and will make a considerable payday for any salvaging team that finds them due to how much they sell for at cargo depots. Highest sell value of any salvageable, just under that of a contraband crate.

## Why / Balance
I think salvage needs more variety. The randomly-generated dungeon stations are neat but generally disappointing, especially in the looks department. And that's if your lucky enough to find one, most of the time your going to be picking over debris. These new objects are meant to serve a similar function to high value crates, but they come in colorful varieties and cant just be bought at a cargo request computer.

On top of that, if someone just wants to use them to detail their grid because they like they way they look, then more power to them. 

## How to test
The included example grids can be found in /Maps/_NF/Salvage/Example.
Textures added are all filed under /Textures/_NF/Objects/Decoration/Scrap.
All of the objects added can be found in /Resources/Prototypes/_NF/Structures/Decoration in scrap.yml.
All prototypes can all be found with the [Salvage] suffix in the entity spawn menu.

- [ ] Implement spawning system that loads in derelict ships, which the list of said ships can be expanded easily
- [ ] Get a handful more derelict variants

**Changelog**
:cl: crysoskis
- add: Salvage objects, to be sold at depots for cash.
- add: Derelicts, which can be rarely found in the frontier.

### CODE REVIEW

**Comment by dvir001** [comment]
This feel like entity blout adding broken machines.

Also confusing to players if there is no fixing.

**Comment by Crysoskis** [comment]
> This feel like entity blout adding broken machines.
> 
> Also confusing to players if there is no fixing.

The broken machines are only a part of it, the other more significant part is the derelict ships to be found and salvaged.

I feel people wouldn't try to fix them based on how far gone they look, unless they were desperate.

**Comment by nyozzl** [comment]
this is cool 👍

**Comment by ErhardSteinhauer** [comment]
This PR hasn't received any updates in quite some time now, so I'm going to close it. Feel free to reopen it, if you ever go back to this PR, @Crysoskis.

**Pull request closed without merging**
