### PR TITLE
Hauler (New) - Salvage and cargo ship

### PR DESCRIPTION
**Pull request by Letholldus**
## About the PR

Adds the NC Hauler ship to the Frontier outpost

## Why / Balance

This was partly an experiment to test with the map editor for SS14, but also to add a more semi-self sustaining long haul salvage vessel to the game that isn't a dedicated expedition vessel. It's a medium sized 'premium' salvage vessel, equipped for mining and cargo shipment operations, and the first of potentially many other ship concepts I've had.

Some major notes about the ship:
- Has a dedicated docking port for loading and offloading cargo easily with cargo and salvage related vendors and two hardsuit salvage pods. The left features a secondary port designed to load and unload ore and processed ore materials efficiently. It also contains a scrapper that outputs into the cargo hold, while not very efficient it does match the salvage/scrapper vibes, and can be a viable way to get some raw materials from certain garbage items in a pinch

- Features a large cargo hold for long trips out or moving large amount of cargo at once. Just be careful of the risk such endeavors may pose.

- Contains a moderate sized, well stocked bar to keep your crew hydrated and happy, the bar also features a very small attached kitchen. the kitchen however does not come stocked with food or utensils, but does contains a freezer, sink, and microwave. Stock up yourself at stations or from other players, or use the basic tools provided to cook whatever you can manage find while salvaging and mining.

- Crew quarters are provided with 4 empty bunks (for rp or to just afk in), a break room with a tv, and a bathroom with shower.

- A small medical bay is also available, though it only contains the bare minimum, a defib cabinet, a table, a medical bed, and two medkits. But it does give you a dedicated place to bring your sick and injured, and a space to manually upgrade yourself with better equipment should you so desire.

- Straight forward engine setup with a compact but effective engine room also with a prelaunch checklist similar to the Pioneer's

- Fairly advanced bridge. Contains the shuttle piloting computer, a mass scanner for its longer scan radius, useful for finding far off structures in space. An internal camera system that allows the pilot or co-pilot to view the rear and sides of the ship. The standard station records computer, fax machine, writing tools and file cabinet. And finally a panic button that will lock down blast doors over every exterior window in the event of a threat. Good for keeping out xenos, but it does not cover airlocks or docking ports, so a dedicated pirate can still get in through other means.

- Contains other small details and QoL features but tried to keep everything within scope for what it was.

- It's a big ship even for medium size and is partially limited by power draw. It is slow to turn and move when not going forward. But it's also a bulky cargo ship as well, so this isn't exactly abnormal.

- Slightly higher than average markup (20% instead of 15%) due to some of the extra features it provides over similar cheaper salvage vessels. Though this is just a personal opinion of mine and it can be marked back down if the price point is deemed to high. (currently priced at 49500)

Known Issues:
Besides the secondary port sometimes needing to be carefully aligned when docking or the conveyors may have a small chance of catching on the edges, there are no major issues I've seen thus far. I've taken it out mining and scrapping, tried to use every facility in it, smashed it up to and patched up holes in the hull to test atmos, etc etc. If any issues do crop up now or later, I'm more than willing to correct them and/or update the ship as well.

## Technical details
.yml

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Hauler-Class Ship

**Changelog**

:cl:

- add: Adds the NC Hauler-Class Cargo and Salvage vessel to the game and the Frontier outpost shipyard

### CODE REVIEW

**Comment by dvir001** [comment]
Shuttles have to be saved under ``Shuttles/_NF/hauler.yml``
Lower case in file name only

**Comment by Letholldus** [comment]
> Shuttles have to be saved under `_NF/Shuttles/hauler.yml` Lower case in file name only

I've fixed the file name to lowercase but I can't find the folder location `_NF/Shuttles` on my end, is this a path not on my version or am I missing something?

**Comment by dvir001** [comment]
> > Shuttles have to be saved under `_NF/Shuttles/hauler.yml` Lower case in file name only
> 
> I've fixed the file name to lowercase but I can't find the folder location `_NF/Shuttles` on my end, is this a path not on my version or am I missing something?

Update your fork and its PR

**Comment by Letholldus** [comment]
Deleted the old hauler file, and moved it to the new folder as requested, fixed the name to be lowercase as well.

**Comment by Letholldus** [comment]
> I like it, the layout and design are really nice. Dont be surprised if the soda/booze dispensers get changed, those may or may not either receive a rework or get restricted on most ships.
> 
> Is that garbage recycler on top of a wall? it appears it may be.
> 
> Design-wise, you have done an excellent job decaling, however the bridge and break room feel a bit lacking and a bit too same-y. May I suggest wood (and possibly a bit of carpet?) in the little break room? And possibly a swap back to the dark steel tiles for the bridge, maybe with a command colored stripe along the north windows to make it pop a little bit. Most bridges should look a bit ritzier. Glass flooring is also a popular option to make the bridge feel a bit fancy.
> 
> Otherwise, from the image, I dont see really anything egregious that stands out, nothing powergamey or anything. Will still want magnus' opinion and to load it up and test it in game, but I quite like this ship

Thank you! I felt the same about the bridge and break room looking back at it after posting the PR, I'll likely go back and change it tonight or tomorrow and update it. If the soda and booze machines end up having to be pulled or changed when they're re-worked it's no big deal.

The recycler is actually over flaps! It makes the wall look connected to it but it still works, already tested it on my end and ran some garbage through it.

**Comment by Letholldus** [comment]
Alright, made the suggested changes
1764fdc3699c2d57c42064b94008c392

**Comment by Letholldus** [comment]
Fixed one other small issue with the shipyard yml, and uploaded a short video showing off and doing some basic testing with the ship.

https://www.youtube.com/watch?v=Mo1L0oYXp60&feature=youtu.be

**Comment by Letholldus** [comment]
Added double stage airlocks to the ship, which also lead into a slightly larger engine room but not changed much with it besides adding a tool cabinet and moving the gyroscope into it. It also lead to the creation of an odd little cubby in the walls I decided to leave with a bit of cobweb with the idea of it possibly being a smuggling space for the ship later
d5b757c18d82c5f9f9792d8b785d4f9d
9f48ff9f4327e46531661a3311a3eaa2

**Comment by Cheackraze** [comment]
just today, we implemented secret doors for shuttle walls if you wanted to pre-build it in, otherwise this is looking good for merging to me. I'll update your branch here to the latest build, so make sure to update your branch before doing any more changes.

**Comment by Cheackraze** [comment]
fixed up the file and tested. The map file found a bad APC mapped in, which is an easy fix. The price also needs to be raised by about 15-20%, since it is way too low. That may have to do with some things changing with the big update, but it should be updated regardless.

The only other thing is that @MagnusCrowe whether or not we will allow blast doors over shuttle windows, i think we only allow shutters now, so that will need to be updated, and then we can merge this in. cargo haulers have been begging for something in the middle of preada and barge size.

**Comment by MagnusCrowe** [comment]
image
Really nice ship.  Three notes:
1. Are you sure you want the windowless docking ports?  Up to you, most people go with the clear version, just wanted to make sure you knew you used the windowless version.
2. Replace your APCs with the basic versions.  The high capacity APCs are not needed anyway.
3. You probably want to replace the generator with the newer ship version.  These ship versions start with a bit of fuel, they start anchored, and most importantly, they start running.

**Review by MagnusCrowe — DISMISSED** [review]
image
Really nice ship.  Three notes:
1. Are you sure you want the windowless docking ports?  Up to you, most people go with the clear version, just wanted to make sure you knew you used the windowless version.
2. Replace your APCs with the basic versions.  The high capacity APCs are not needed anyway.
3. You probably want to replace the generator with the newer ship version.  These ship versions start with a bit of fuel, they start anchored, and most importantly, they start running.

**Comment by MagnusCrowe** [comment]
Oh yeah, one more thing, you need to replace the blast door window covers with shutters.

**Comment by Letholldus** [comment]
I'll get on the changes ASAP, would have started sooner but was gone on a bit of a trip. Should have them done in the next day or two.

**Comment by Letholldus** [comment]
Alright it should be up to date with the requested changes, took a bit longer than I wanted, visual studio was being finicky

**Review by Cheackraze — APPROVED** [review]

**Comment by Letholldus** [comment]
I'll check tonight and try to push a patch to make sure the price is what it's supposed to be.

**Comment by ThatOneGoblin25** [comment]
> I'll check tonight and try to push a patch to make sure the price is what it's supposed to be.

It's because of the lockers, when you're mapping they don't have the items in them. Thus they only contribute to the price when you buy it ingame.

**Pull request merged**
