### PR TITLE
Shuttle atmost markers

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added new atmost markers for shuttles
Fixed condor and rigger to use the new markers.

Also fixed some general entity related stuff in rigger as per new vend changes.

## Why / Balance
Balance

## Technical details
.yml
and some c# to add the new markers

## Media
N/A

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
wonder how your changes will merge with mine here:
https://github.com/new-frontiers-14/frontier-station-14/pull/654

**Comment by dvir001** [comment]
> wonder how your changes will merge with mine here: #654

Ill probably just re-base it on your changes.

**Comment by dvir001** [comment]
If this update done before #654 its fine ill just go back and do a new PR to fix its atmost again.

**Comment by dvir001** [comment]
Removed the rigger form the PR for now, we can fix the atmost levels on it later

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
