### PR TITLE
Sawn-off PKA

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Adds an option to saw off bits from PKA so it would occupy less space.
**Pros:**
- PKA now fits neatly in your pocket or combat boots.
- Full Auto firing mode.

**Cons:**
- Recoil kicks harder.
- Can not be wielded, so no way to mitigate the recoil.
- It still holds only one charge and recharges at the same rate as unmodified PKA.

## Why / Balance
It's a trap. Side note: I removed use delay and buffed fire rate so it would be possible to shoot 2 sawn-off PKAs by quickly switching between them. Impossible to hit anything smaller than a side of a barn reliably, but somewhat fun to use.

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- add: Now you can make a sawn-off PKA. But should you though?

### CODE REVIEW

**Comment by VividPups** [comment]
what do you mean by Full auto

**Comment by ErhardSteinhauer** [comment]
That it is firing in full auto instead of semi auto

**Comment by dvir001** [comment]
> That it is firing in full auto instead of semi auto

https://www.youtube.com/watch?v=zyC-F_7QXtk

**Comment by ErhardSteinhauer** [comment]
> > That it is firing in full auto instead of semi auto
> 
> https://www.youtube.com/watch?v=zyC-F_7QXtk

Damn, now we'll have to add to the Space Law that firing this weapon in enclosed space is illegal.

**Review by dvir001 — APPROVED** [review]
This is an actual sin

**Pull request merged**
