### PR TITLE
Blueprints

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Upstream introduced new feature - blueprints. This PR slightly expands upon it by adding more blueprints that could be printed by scientists and sold to players.
- Added a small collection of printable blueprints. Unlocked through research along with the corresponding items (includes advanced tools, T3 parts, bluespace bags and some hardsuits). Blueprints can be stamped, signed, burned, eaten and recycled. Fax can be used to send printed blueprints.
- Added a small collection of blueprints obtainable in expeditions only (uranium and incendiary ammo, laser cannon and x-ray cannon). Those cannot be faxed. Can be eaten though.
- Added Blueprint Lithograph - new lathe available from flatpackvend or science bundle; machine board printable from circuit imprinter at round start.
- Techfabs (most of them) can accept blueprints now.

## Why / Balance
Hopefully this will give a small boost to interaction between science players and the rest of the server.

## How to test
1. Spawn R&D server, R&D computer, blueprint lithograph, debug research disk.
2. Unlock technologies and watch how the list of available for printing blueprints grows.
3. Print blueprints, insert them in techfabs.

## Media
image
image

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- add: Blueprints can now be printed or found on expeditions.  They unlock recipes in lathes or techfabs and can be stamped, signed, burned, eaten, recycled and faxed (destroying the original - exped blueprints cannot be faxed).
- add: Added the Blueprint Lithograph, a new lathe available from the FlatpackVend, science bundle, or circuit imprinter.  It prints blueprints from stacks of paper.

### CODE REVIEW

**Comment by whatston3** [comment]
> Blueprints can be stamped, signed, burned, eaten and recycled.
Finally, engineering gameplay. :^)

I think this feature could be really useful, will give it a look.

I might look into getting something that can pull in researched recipes, so anything that's researchable can be printed off without needing to define extra entities, but man this was really fast.

**Comment by ErhardSteinhauer** [comment]
> I might look into getting something that can pull in researched recipes, so anything that's researchable can be printed off without needing to define extra entities, but man this was really fast.

Man, halfway through this PR I wished I wasn't C#-illiterate to make it happen.

**Comment by ErhardSteinhauer** [comment]
Gonna add some blueprints that can't be copied/faxed as exped loot and then I'm done with this.

**Comment by whatston3** [comment]
> Gonna add some blueprints that can't be copied/faxed as exped loot and then I'm done with this.

I think that all blueprints should be destroyed on faxing (so a copy does nothing, and a "send" destroys the original).  If you don't have this, the value of selling a blueprint is questionable.  I'll get this working in short order, and I can add it to this if you'd like, or give you the diff.

**Comment by ErhardSteinhauer** [comment]
> I think that all blueprints should be destroyed on faxing (so a copy does nothing, and a "send" destroys the original). If you don't have this, the value of selling a blueprint is questionable. I'll get this working in short order, and I can add it to this if you'd like, or give you the diff.

Sounds good to me. Just add to this PR then. For now I just removed "faxable" component from exped loot blueprint parent.

**Comment by ErhardSteinhauer** [comment]
A'ight, it is done.

**Comment by dvir001** [comment]
I think the next step is to make the blueprints costs small number of sci points to print (Can be in later PR)
Allowing us to remove the disk print meta, and have a blueprint sell meta.

**Comment by dvir001** [comment]
Also please don't kill me but keep the NF in entity names as suffix, not prefix.

**Comment by ErhardSteinhauer** [comment]
> Also please don't kill me but keep the NF in entity names as suffix, not prefix.

I've done it this way, because I believe sooner or later upstream will add a bunch of blueprints and we'll have some issues with IDs because of that.

**Comment by ErhardSteinhauer** [comment]
> Allowing us to remove the disk print meta, and have a blueprint sell meta.

I doubt that selling blueprints to players will ever become meta

**Comment by ErhardSteinhauer** [comment]
> Also please don't kill me but keep the NF in entity names as suffix, not prefix.

Ugh, wait. Wdym? Suffix goes to the end of the ID, prefix goes to the beginning of the ID, is it not? NF is a suffix there.

**Comment by dvir001** [comment]
> prefix

*prefix my bad

**Comment by ErhardSteinhauer** [comment]
Ugh, sure. 😭

**Review by whatston3 — APPROVED** [review]
RSI validator passes on whatston3#4, no changes to sprites in the meantime, should be good.  Happy with the state of this.

Ideally, I think blueprints should be restricted in terms of what machines accept them (i.e. no salvage blueprints in medical techfabs), but otherwise this seems fine.

I'd like a second pair of eyes on this, but it seems good to me.  Fax destruction seems useful for sensitive docs, might be have for other things.

Nicely done, good feature.

**Comment by whatston3** [comment]
What if we removed the BlueprintReceiver from the autolathe and tinkered with the techfabs that would accept each blueprint type?

**Comment by whatston3** [comment]
> What if we removed the BlueprintReceiver from the autolathe and tinkered with the techfabs that would accept each blueprint type?

https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-09-Blueprint-Printing...whatston3:frontier-station-14:2024-09-Blueprint-Printing-suggestions?expand=1

Here's a set of changes that should enable it.
* Inserting the wrong blueprint type prints out a message saying so (I think we should include this regardless of what happens, useful QoL)
* Blueprint parents are associated with one or more NF-prefixed blueprint techfab tag (could move to components, but it's a tag for now)
* The description on each blueprint states which machines it should work on (manually upkept, at least for now)
* Techfabs are associated with their respective tags, and not to the autolathe tag.
* Armory blueprint parenting is a bit of a mess as there may be blueprints you want in the NFSD fab but not the merc/ammo fab (shuttle guns at the moment if they were printable)
* It might be interesting if the hacked mercfab could accept NFSD blueprints but I've left it to only accept base merc prints for now.

Here's a trivial video of the system in use, showing a science-labelled blueprint failing to insert in a med/ammofab, then a blueprint being inserted into each successfully.

https://github.com/user-attachments/assets/1ac53b9b-1750-4090-b501-0f9142890f59

**Comment by ErhardSteinhauer** [comment]
I'm ugh still not sold on the idea of limiting which techfab/lathe can take which blueprints, I think it mostly detracts from QoL side of things: the way I think this feature going to work is that majority of players will get 1-2 blueprints with something small that needs to be produced in fairly large numbers (like T3 parts, power cells or something like that), but if they need another lathe only to use that 1-2 blueprints then.. Why even bother at this point? Worse yet, if you need 2 blueprints only to find out that you need 2 more lathes for them to work.

**Comment by ErhardSteinhauer** [comment]
Not that lathes are hard to acquire, but the proposed feature feels like unnecessary complication to me. I might be wrong though.

**Comment by whatston3** [comment]
> I'm ugh still not sold on the idea of limiting which techfab/lathe can take which blueprints, I think it mostly detracts from QoL side of things: the way I think this feature going to work is that majority of players will get 1-2 blueprints with something small that needs to be produced in fairly large numbers (like T3 parts, power cells or something like that), but if they need another lathe only to use that 1-2 blueprints then.. Why even bother at this point? Worse yet, if you need 2 blueprints only to find out that you need 2 more lathes for them to work.

The counterpoint to this is that, if we were able to get a _bunch_ of blueprints, and for pretty much anything, if you can insert them into anything, the separation between techfabs becomes moot.  Not insisting on this, but I do think that some separation might be useful.

Regardless, I've touched up a few of the sprites, the in-hand blueprints looked a bit odd to me having only one shade in the text and the coloured background.  Thoughts?

image

image

**Comment by whatston3** [comment]
> Not that lathes are hard to acquire, but the proposed feature feels like unnecessary complication to me. I might be wrong though.

Perhaps then you could also add a universal techfab that accepts all blueprints (arriving back at the autolathe point, but gating it behind other research)

**Comment by ErhardSteinhauer** [comment]
> The counterpoint to this is that, if we were able to get a bunch of blueprints, and for pretty much anything, if you can insert them into anything, the separation between techfabs becomes moot. Not insisting on this, but I do think that some separation might be useful.

I don't think that it is a bad thing, because at this point player spent a bit of effort into making his favorite techfab into ultimate fabricator unit that is horrendously annoying to use due to how long the list of craftable items has become. I don't think that this is going to be a common occurrence though. A thought (that I'm not going to act upon right now in this PR): maybe limit blueprints shenanigans to autolathe then, just like it was in the base game? Will make the machine relevant again.

> Regardless, I've touched up a few of the sprites, the in-hand blueprints looked a bit odd to me having only one shade in the text and the coloured background. Thoughts?

Looks way better than original ones, good stuff.

**Comment by ErhardSteinhauer** [comment]
> Erhard are you saying that if I put the blueprint into a service techfab that fabricator should be able to thereafter make whatever the blueprint was for? That a service fabricator could, with the proper blueprint, make recipes that otherwise would be unlocked for the exosuit fabricator?

Yes. At least now.

**Comment by ErhardSteinhauer** [comment]
> But downstream of that I do not think that it connects that lathes that are specialized for a task, such as an exosuit fabricator, are equipped to produce ammunition. Unless the thinking here is that every lathe is exactly the same with a different candy shell. As it stands aren't there complications in that not all lathes will accept all materials?

imo if a lathe can make something as complicated as articulated borg's appendages or MMI, then it can produce something as dumb as ammo (provided it has instructions - a blueprint - and materials). miracles of far-future fdm printing or whatever.

the fact that you **_can_** put a blueprint into a lathe doesn't mean that you **_will_**.

**Pull request merged**
