### PR TITLE
Scrapyard Ship Disciple (new)

### PR DESCRIPTION
**Pull request by nyozzl**
## About the PR
Added a new scrapyard ship disciple.yml

## Why / Balance
Ive looked at the amount of religious ships and thought a scrap one would be perfect for the amount maint cults ive seen

## Media
image

image

scrap church description

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: New scrapyard ship disciple

### CODE REVIEW

**Comment by nyozzl** [comment]
do note the image of the ship has shadows turned off

**Comment by nyozzl** [comment]
what is a yaml.....

**Comment by ThatOneGoblin25** [comment]
You named the .yml wrong "Resources/Maps/_NF/Shuttles/discipel.yml"

**Comment by nyozzl** [comment]
i cant find the mispelling

**Review by ThatOneGoblin25 — COMMENTED** [review]
Misspelt commit
Nevermind that's not actually the file? I probably shouldn't be answering because I'm a GitHub newb too but that latest commit has the .yml wrong.

**Comment by nyozzl** [comment]
> This looks like an excellent addition to the shipyard fleet! very well made. The ONLY two things i have to say about this is that it needs a defib and a fire extinguisher according to mapping rules, not sure if it really applies since its such a cheap ship And the other thing is that you can replace the glass from diagonal walls back to lattice because its more of a suggestion to make ships prettier, and it feels like lattice fits more with this ship

i do believe the svtide doesnt have a defib or fire extinguisher

**Comment by nyozzl** [comment]
let me know if anything else needs to be changed

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image

Walls, especially external walls, should not only touch on a corner.  After you fix this, the ship is ready to merge.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
