### PR TITLE
Update salvage_mods.yml

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
I CANT SEE SHIT

## Why / Balance
Ok this is ok now.

### CODE REVIEW

**Comment by MWGMorningwood** [comment]
I kinda liked collecting water vapor directly :(

**Comment by dvir001** [comment]
> I kinda liked collecting water vapor directly :(

There are still 3 with H2O over 10%

**Review by whatston3 — APPROVED** [review]
Fine.  You could keep one or two of them water-filled if they still exist elsewhere, which they do, but all of them's a bit silly.

**Comment by dvir001** [comment]
Love me some water

**Pull request merged**
