### PR TITLE
alcohol v2 electric boogaloo

### PR DESCRIPTION
**Pull request by ray-boop**
## About the PR
Five more drinks: Gin and Sonic, Golden Cat, Pineapple Blast, Torpedo Juice and Bees Knees.

## Why / Balance
Fun

## How to test
1. Spawn metamorphic glasses with new drinks.

## Media
New drinks - first five on the left side of the table 

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None (I think)

**Changelog**
:cl: ray-boop
- add: Added a set of new drinks for bartenders to mix: Gin and Sonic, Golden Cat, Pineapple Blast, Torpedo Juice and the Bee's Knees.

### CODE REVIEW

**Comment by ray-boop** [comment]
dont have much time right now, cant say when im able to continue, gonna open it for your review

**Review by ErhardSteinhauer — CHANGES_REQUESTED** [review]
Right, so the stuff works, but imo drink sprites are way too big in comparison with other glass sprites and unfortunately they aren't scalable on yml side, so they need to be scaled down in graphical editor. I don't think that I'm interested in doing it, unless someone is willing to take this burden I'll close this PR soon(ish).

image

**Review by ErhardSteinhauer — APPROVED** [review]
Updated the sprites, good to go. Would like someone else to check it before merging though.

**Comment by whatston3** [comment]
Giving it a look.

**Comment by whatston3** [comment]
Touching up a few of the sprites, will ask for your thoughts when I'm done with them.  Don't think it's anything huge.

**Review by whatston3 — APPROVED** [review]
Looks good to go.  Enlarged the base on the gin and sonic, flipped the metal bit on top (difficult to read with so few pixels, looks more like an opening), moved the straw over on the bee's knees, cleaned up the lines on the chest in the golden cat, and added some more fill states to most drinks.

Minor rewrites to descriptions, fixed up the fast flavour reference.  Looks good on my end.  @ErhardSteinhauer, a sanity check would be appreciated when you can.

**Comment by ErhardSteinhauer** [comment]
Changes work fine.

**Pull request merged**
