### PR TITLE
Pipe tobacco pouches

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Added a pouch for pipe-weed. Can be recycled and/or butchered for cloth.
- Added 3 more pipe-smokeable tobacco powders: stonecut tobacco, fungal whiff tobacco and sweet dreams tobacco. All are lased with questionable chemicals (nothing crazy, just flavor). Stonecut tobacco will make your character cough and gasp, fungal whiff will make your character see rainbows, giggle, gasp, hiss, mutter. Sweet Dreams will make your character yawn and feel stuff.
- Added pipe-weed pouches to ShadyCigs and as a loadout option.
- Added new microwave recipe - dried shrooms: spaceshrooms + chanterelle + fly amonita  for 15 seconds which gives you dried shrooms that can be ground into fungal whiff tobacco.

## Why / Balance
"After some time he felt for his pipe. It was not broken, and that was something. Then he felt for his pouch, and there was some tobacco in it, and that was something more. Then he felt for matches..."

## How to test
1. Spawn new pouches, smoke the contents.
2. Follow crafting instructions.

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer and whatston3
- add: Added a pouch for pipe-weed. Can be recycled and/or butchered for cloth.
- add: Added 3 more pipe-smokeable tobacco powders: stonecut tobacco, fungal whiff tobacco and sweet dreams tobacco. All are lased with questionable chemicals. Can't be grown in hydroponics.
- add: Added pipe-weed pouches to ShadyCigs and as a loadout option.
- add: Added new microwave recipe - dried shrooms: spaceshrooms + chanterelle + fly amanita  for 15 seconds which gives you dried shrooms that can be ground into fungal whiff tobacco.

### CODE REVIEW

**Review by whatston3 — APPROVED** [review]
Looks alright - I've got a suggestion for another tobacco pouch here: https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-09-Tobacco-Pouch...whatston3:frontier-station-14:2024-09-Tobacco-Pouch-suggestions?expand=1

It makes you yawn and puts you at ease - I do find the psicodine popups to be a bit oddly written, "you feel completely fearless" sounds more like supersoldier serum to me.  Might be overly strong (still uses 30 u of stuff), might be better as haloperidol only, no psicodine.  Dunno, but if it tickles your fancy, feel free to include it.

Works fine, looks fine.  I do wish there was something that put out a nice aroma when put in a censer.

**Comment by ErhardSteinhauer** [comment]
> Looks alright - I've got a suggestion for another tobacco pouch here: https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-09-Tobacco-Pouch...whatston3:frontier-station-14:2024-09-Tobacco-Pouch-suggestions?expand=1
> 
> It makes you yawn and puts you at ease - I do find the psicodine popups to be a bit oddly written, "you feel completely fearless" sounds more like supersoldier serum to me. Might be overly strong (still uses 30 u of stuff), might be better as haloperidol only, no psicodine. Dunno, but if it tickles your fancy, feel free to include it.
> 

Looks good to me.

> Works fine, looks fine. I do wish there was something that put out a nice aroma when put in a censer.

Yeah, would be nice.

**Review by whatston3 — APPROVED** [review]
Touched up the psicodine descriptions, decreased how often the messages get printed out, fixed my scuffed sprite definition.  Think it's reasonable, but revert it if you aren't fond.  Happy with the state of this.

**Comment by whatston3** [comment]
Actually, your fungal whiff stack has the same issue - it inherits the same brown colour from the parent, which fiddles with the colours of each of the layers.

**Comment by whatston3** [comment]
Removed it, looks like this:

image

If the darker sparkles were intentional, my mistake.

**Comment by ErhardSteinhauer** [comment]
> Actually, your fungal whiff stack has the same issue - it inherits the same brown colour from the parent, which filters the colours of each of the layers.

Huh. This is odd, (I thought that inheritance works differently that it's enough to declare new colors), but thanks for fixing it.

**Comment by ErhardSteinhauer** [comment]
> If the darker sparkles were intentional, my mistake.

This is fine. I have only one question: the hell is going on with that picture? Why Urist has tobacco cape?

**Comment by ErhardSteinhauer** [comment]
Ah, wait, that harpy... Ugliest bastard I've ever seen.

**Pull request merged**
