### PR TITLE
The Clown Shoes

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
The R&D department of Honk! Co with the insightful guidance of the NT Engineering Department had a breakthrough: you can put a whoope cushion in your clown shoes! Moreover, you can put a ketchup bottle in there too! And a mustard bottle! Or even combine a whoopie cushion with a ketchup bottle (not with mustard - that's too far)! Please refer to the embedded educational video for more details (to fully appreciate how mindboggling this invention is, turn the sound on).

_"!!FUN!! was never more accessible than now!"_, - John Honk, anonymous Honk! Co employee.

## Why / Balance
I shouldn't have, but I could and here we are.

## Technical details
.yml

## Media
https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/4b7abc04-6bc6-4c37-9d0f-4dd553116c0d
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: You can customize you clown shoes. Check out construction menu.

### CODE REVIEW

**Comment by dvir001** [comment]
Yml machine broke, duplicated stuff?

**Comment by ErhardSteinhauer** [comment]
Too many shoes I guess. No matter. While I figure out the cure I'll also will look into how I can drip-feed shoes from a backpack-tank.

**Comment by ErhardSteinhauer** [comment]
Here, all fixed.

**Review by dvir001 — APPROVED** [review]
I have lost my will to live.

**Review by FoxxoTrystan — APPROVED** [review]
I hate it, even tho code wise its good.

I dont see anyone using this really much... and those who will... i may commit... murder...
Good job tho on ya work.

**Comment by GentleButter** [comment]
i hate it here.

**Comment by Cheackraze** [comment]
i regret adding maintainers

**Pull request merged**
