### PR TITLE
Eagle (Medical Assembler-Update)

### PR DESCRIPTION
**Pull request by ThatOneGoblin25**
## About the PR
- added medical assembler
- added uranium wall locker [2 generator]
- added tiny surgery and surgical duffel bag [filled]
- added flatpacker 1001
- rebalance posters and decals

## Why / Balance
New stuff and a refresher for the engineering-medical ship. Flatpacker 1001 used to be on this ship two updates ago, but I removed it because I was struggling with space. After reworking the space in the last update, I didn't bother re-adding it even when Magnus suggested I could. Moving the engineer locker to a wall variant created an empty space which I decided to fill with flatpacker.
Tiny surgery is here for future-proofing:tm:

## Media
eagle3

**Changelog**
:cl:
- tweak: Eagle has received the medical assembler and slight tweaks.

### CODE REVIEW

**Comment by dvir001** [comment]
image

**Comment by dvir001** [comment]
> I confirmed it can still be accessed by brushing against the superpacmans. Realistically, the player will only ever open it once, so it doesn't need to be convenient.

Feels a bit off if locker range / generator fixture change a bit.

**Comment by dvir001** [comment]
image

**Comment by dvir001** [comment]
image

**Comment by ThatOneGoblin25** [comment]
Can we keep the wall-mounted engineer hardsuit locker? Replace the fire extinguisher cabinet in Atmos with it. Otherwise the changes are fine.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
