### PR TITLE
Novalite C1 Nanofornia Edition

### PR DESCRIPTION
**Pull request by mrscratch**
## About the PR

This adds the SW LLC's "Novalite C1" semi-auto rifle to the game. The concept was originally tossed around as a more legal means for Mercenaries/Miners/etc to have a better Mid-Tier weapon to protect themselves with.

After the recent community/staff decision to firmly uphold the automatic weapons ban after the recent... space law headaches... I was inspired to actually setup this fork and attempt to make the rifle myself with a new "theme" in mind.

**The gun:**

novalite_closedbolt
novalite_openbolt

It is essentially what you would get if you applied some of the strictest gun law loophole aftermarket modifications to a Lecter. It's auto sear has been replaced with a semi-automatic sear, removing it's ability to be fired in full auto. It has a "Featureless Grip" or "Shark Fin" which is used to skirt around pistol grip laws. It has an internally locked magazine that is reloaded by using a Break-Action Receiver which allows you to quickly access the locked magazine. It comes with a SW LLC patented "High Capacity Assault Clip" which can attach or detach from the locked magazine to quickly load ammunition. 

## Why / Balance

Originally I just left it with the same stats as the Lecter except it is now Semi-Auto and has a 15 round "magazine". However to save future headaches I have lowered the rate of fire from 5 to 4. All Semi-Auto Pistols in the game currently have a firerate of 4-5 so for semi-automatic that seems to be the baseline.

## How to test

Search Novalite in the entity spawner.
nova

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/9546775/3c160c90-334a-4d54-9d02-48742ec4a440

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Kesiath** [comment]
This is both cursed and hilarious, and super fitting. I'd love to see this in the game but I'm wondering where you would be able to get it from. Probably worth mapping it as one of the random ship lockers or expedition findable bags, but unsure.

**Comment by dvir001** [comment]
expedition findable probably

I think most guns can go there.

**Comment by mrscratch** [comment]
I'm hoping it can make it's way into the LibVendor as a luxury buy but honestly its also fine if it's just something that can be discovered during Expeditions.

I know SS14 isn't real life but irl these fully modded gun law skirting rifles when purchased pre-built can easily hit the $1500-2000 range. They're expensive.

**Comment by Kesiath** [comment]
> I'm hoping it can make it's way into the LibVendor as a luxury buy but honestly its also fine if it's just something that can be discovered during Expeditions.

When comparing this gun to the other guns currently in the liberation station, the most stark contrast is that this (despite legally not having magazines) uses a clip for quick reloading. In comparison, all the current liberation station guns need to be manually loaded one bullet at a time and don't accept any quick reloading items except maybe the mosin (although I don't think this currently works?).

I can absolutely imagine, if in the lib vendor, someone buying 5 of them and just ripping the clip out of four of them and dumping them on the floor. Money is not a hurdle for players currently so we can't effectively use that as a balancing point.

I think tying it to some more bluespace events and expeditions could be a neat idea, have it next to some dead private security guards or something along those lines.

**Comment by mrscratch** [comment]
That's perfectly reasonable.

**Pull request closed without merging**
