### PR TITLE
Gestio burst-fire 20 rifle

### PR DESCRIPTION
**Pull request by Qulibly**
## About the PR

Adds a new civilian (class 1 contraband) tier 2 burst-fire marksman firearm to Frontier.
The caliber used is .20 rifle, same as Lecter, the NFSD assault rifle but also Argenti, tier 1 revolver.

It is obtainable through expeditions as a reward. In future if needed the methods of obtaining can be expanded.

## Why / Balance

There is no burst-fire firearms out there. But mainly as people desperatly lacked a decent firearm option that isn't a contraband. As well as to expand options in the longer ranges category. A perfect middle option.

Balance wise weapon itself contains power when it stays in range.
And utilises its tempo: burst fire -> cover -> burst fire -> cover
Up close it will loose to options like shotguns, pistols, smgs and more.

It's design is to reward utilising the burst fire mode and heavily punishes trying to spam fire it.
As sadly due to how burst fire is coded it isn't possible to add a delay between bursts.
It is the reason why recoil approach was taken.

If it keeps its range and shooter approaches strategically, it is capable of beating lecter, or with team even a bloodred hardsuit with l6 saw.

When it comes to magazines. If people manage to somehow obtain standard sized .20 rifle magazines from NFSD, this can provide an improvement to firearm.
Conversely, NFSD could find use to low capacity magazines from Gestio, either to get more total shots at cost of needing to reload more. Or to fill in any empty slots in inventory with these smaller magazines to have more spare ammunition in case of need.

## How to test

Ran through expedition, playtested on private server with people to test both PvE and PvP capabilities.
But also just spawn, pick it up and test fire on various targets and in varied situations

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/52052459/709b27f5-f0c9-4d12-9c4a-72c3504c686f
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

BaseWeaponRifle in yaml may potentially cause issues in the firearm if those changes vastly modify how weapon operates.

Changes to how burst-fire is coded in gun system.

Additionally balance could be diminished if standard sized Lecter magazines are easily obtainable to everyone.

**Changelog**

:cl:
- add: Added Gestio. A burst-fire .20 rifle, a tier 2 civilian firearm. It may be antique but could still prove useful to prospectors. Obtainable through expeditions.

### CODE REVIEW

**Comment by Cheackraze** [comment]
I think the burst is way to slow, and the time between firing is too quick as well, essentially turning this into almost an autofire  weapon. In theory, I think we could allow a civilian burst fire rifle, but im not sure what ammo/damage we should really allow from it as well.

**Comment by Qulibly** [comment]
> I think the burst is way to slow, and the time between firing is too quick as well, essentially turning this into almost an autofire weapon. In theory, I think we could allow a civilian burst fire rifle, but im not sure what ammo/damage we should really allow from it as well.

Sadly when it comes to burst, if were to add a delay between firing I would need to touch the gun code and fixup the burst in there so you can actually add a delay. This is why went the recoil route.   Burst speed is ok, definetly if could be faster it would be awesome but as now burst is "automatic but if you hold left click stops firing after X shots" cant get it too high either.

Given playtesting that done with few players it performed decently in PvP and PvE.


Damage wise, single burst deals 51 dmg without armor. Against NFSD armor it takes 3 perfectly accurate bursts to take down.

**Comment by Qulibly** [comment]
obraz
obraz

Tested ingame, all generates from expedition as it should. Spawner wise.
Hopefully will fit nicely as tier 2 firearm.

**Comment by dvir001** [comment]
Pull master into this PR please.

**Comment by Qulibly** [comment]
Don't merge yet. Tested and wielding is completely borked on the gun as it wasn't made to be wielded.
WIll have to work to either fix that OR turn this gun into usable with one hand...

**Comment by Qulibly** [comment]
Now time to decide if sticking with .20 rifle caliber
OR
change it to .30 rifle caliber instead...

AS well as if expedition only OR make it purchasable in liberation vend...

**Comment by VividPups** [comment]
no to the Vending because people will ONLY buy that also.. (honestly the Repeater shouldn't be in there and it should be buff really)   it isn't legal because it is burst, you would need a permit. also, I would also say that the SVT is a chamber in 30cal but if this is posted to be an early Lector I would say keep it in the same Cal

**Comment by Leander-0** [comment]
Again, dual-wielded argentis already act better than the gestio on this way, it should be a .30 with magazines of 15 bullets, then it can be upgraded with AKMS magazines or from the ammo techvend and yeah it should be available on the liberation vend along with magazines.

there is no point on getting a gestio from a gun case when i can get better weapons on the liberty vend already and with the same ammo and if you are on expedition you can get an AKMS more easily too on the syndicate expos.

**Comment by dvir001** [comment]
I would like to see it on expos like the AKMS

**Comment by Qulibly** [comment]
Now question is. Where would it be better positioned?

Compared to dual-wielded argentis:
has lower capacity, may have lower accurancy, the bullets fly slightly faster, it may be easier to reload with magazines
if used one handed and with shield you may be capable to fire faster though without accurancy

As well as where it could fit?
Gestio most definetly is designed to be a fully legal weapon, with burst attempting to make it slightly more unique

**Comment by BluCottonCandy** [comment]
I think this is a solid weapon.
I dare say I think it belongs in the Lib Vend, I know this is probably an unpopular opinion.
However, it's slower than the Argenti, so DPS can not be the argument here.
It's got a small mag, and why would I choose this over any other SMG, or even the AKMS as it were.
I think this should be a round start weapon, if nothing else maybe make it obscenely expensive so people don't just grab it right away every single time.

As for why NT would sell it to us, were frontier, NT sells us their handmedowns all the time.
Why not sell the backwater NT space mining town these old ass rifles they found in a dusty supply closet?

**Comment by ErhardSteinhauer** [comment]
Damn, resolving those conflicts took some effort.
Most of the changes made are related to expedition aspects: I've put Gestio on T2 of expedition weapon pool which should make it fairly common weapon, changed crate with Gestio rifles on expeds a bit and moved GestioExped prototype to the file where other exped weapon prototypes reside.

**Review by ErhardSteinhauer — APPROVED** [review]
Tested, works as expected: rifle rifles.

**Review by ErhardSteinhauer — DISMISSED** [review]
gotta merge master into this

**Review by ErhardSteinhauer — APPROVED** [review]
yolo

**Pull request merged**
