### PR TITLE
Casey's Casino

### PR DESCRIPTION
**Pull request by terezi4real**
## About the PR
Adds Casey's Casino, a new small PoI for shady dealings and gambling. Equipped with an incredibly secure "high rollers lounge", those who want to make sure they will be safe from sec while they win big will feel secure. The center room of Casey's is so well fortified in fact, that legendary gangster "Spaceclamps Johnson" notably died there after a 74 hour standoff with security forces, during which the center hold of Casey's remained impenetrable.

## Why / Balance
More poi = gooder

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Casey's Casino, Win big!

### CODE REVIEW

**Comment by Cheackraze** [comment]
more poi indeed gooder.

Just a few questions, is this a syndicate, neutral, or NT-aligned type POI? What color IFF (in hex preferrably, will accept rgba = 255 values as well) and should it show IFF signal round-start? If its syndicate or neutral aligned, will it sell contraband or shady goods or ships?

Also, part of that decal work is security-themed and I'd like to avoid mixing up the visual language and indicators if we can for that. Specifically, the half-tile decals in the southern hallway. I suggest either going with the quarter-tile border like you have started, or some other pattern, but dont use specifically the sec color if you can avoid please, try for the emagged red instead etc.

**Comment by terezi4real** [comment]
it was syndie themed for about 98% of development and then i was like eh, neutral, and never redid the decals. but now i am revitalized by a new day, and will redo them in orange i think. hex color also orange idgaf what it is specifcally. Show on IFF, wont sell anything of note, just another gathering place for gambling or a secure last stand against sec.

**Comment by terezi4real** [comment]
done 👍

**Comment by Cheackraze** [comment]
And you want it named 'Casey's Casino' or something cooler like 'Casey's Last Resort' or something

**Comment by Cheackraze** [comment]
otherwise it looks good to go, though Im also about to merge your faction vendor in case you wanted to add that before I coded its spawn in

**Comment by terezi4real** [comment]
> And you want it named 'Casey's Casino' or something cooler like 'Casey's Last Resort' or something

Yeah i dunno i want the last stand aspect to be hinted and discovered rather than blatant, i dunno "Casey's Crazy Cash Casino" or something i dont mind if you find something good

**Pull request closed without merging**
