### PR TITLE
The SBI-Crown

### PR DESCRIPTION
**Pull request by UncaughtEx**
## About the PR
Adds the SBI Crown, a civilian and mercenary Templar style vehicle. With the idea to evoke the same emotional response as the Victoria Crown.

## Why / Balance
I believe that we need more smaller mercenary vehicles designed for quick response much in the same vein as the standard Templar. A more Civilian oriented pursuit vehicle for those looking to hunt down bounties in style!

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Introducing from SBI, with Blueprints graciously supplied by the NT archives, the Crown, for all your Civilian Templar oriented needs!

### CODE REVIEW

**Comment by UncaughtEx** [comment]
I'll take a look and bring my ship up to modern mapping standards when I get a chance, thanks Grease Monk

**Comment by UncaughtEx** [comment]
image
Added 2 stage airlock to bridge
Redid wiring
Not Shown, but added reinforced table with Fax Machine

**Comment by UncaughtEx** [comment]
image

**Comment by UncaughtEx** [comment]
image

**Comment by MagnusCrowe** [comment]
> image

I like that a lot better.

**Comment by UncaughtEx** [comment]
Is there any further changes I should make?

**Comment by MagnusCrowe** [comment]
I'll review it this weekend and let you know

**Comment by MagnusCrowe** [comment]
image
Too many lights in this room and your gyro is off.
image
The effect of using glass as a floor on external areas where you want to hide the floor is lost when you light it up. I recommend you re-think this.
image
I recommend you move the APC to a place that makes more sense, like up and over one square to the back wall of the cockpit.
image
Clean up the unnecessary wiring.
image
Add contractor and add all 3 job spawns to the ship.
image

You have waste gas venting but consider adding an air supply system.  I think there's space, see above.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
Too many lights in this room and your gyro is off.
image
The effect of using glass as a floor on external areas where you want to hide the floor is lost when you light it up. I recommend you re-think this.
image
I recommend you move the APC to a place that makes more sense, like up and over one square to the back wall of the cockpit.
image
Clean up the unnecessary wiring.
image
Add contractor and add all 3 job spawns to the ship.
image

You have waste gas venting but consider adding an air supply system.  I think there's space, see above.

**Comment by MagnusCrowe** [comment]
Also, change all the doors on the ship to be the unlocked version except the cell door.

**Comment by UncaughtEx** [comment]
Thanks mate, I'll look into applying these changes when I can.

**Comment by UncaughtEx** [comment]
And regarding the job spawns 
Dvir said something about only needing the Latejoin spawn point and that the contractor spawn point messes with the round start spawning.

**Comment by UncaughtEx** [comment]
Correction 
Late join
Screenshot_20240519_035509_Discord

**Comment by dvir001** [comment]
You actully don't need to map any jobs spawns exept late join as they all going to use it.

**Comment by UncaughtEx** [comment]
I also removed all the locked airlocks besides the brig windoor
I was unable to link the windoor to a button for a bolting function as I kept getting a Pressed refused and Access denied response despite trying three different AA IDs and Sandbox AA.
This seems to affect all airlocks on the ship and I don't know why.

**Comment by UncaughtEx** [comment]
Weirdly enough I can link the airlocks/windoor just fine while its init and loaded into the game such as docked to the frontier

**Comment by UncaughtEx** [comment]
Correction
you can link the windoor and airlocks when the map is initialized in general. No Clue why it won't let you link when its in the mapping mode.

**Comment by MagnusCrowe** [comment]
> You actully don't need to map any jobs spawns exept late join as they all going to use it.

REEEEE MAKE UP YOUR MIND

**Comment by UncaughtEx** [comment]
Did all the changes you requested 
Wanted to keep the headlights, so I made the tile below the lights into none glass

**Comment by MagnusCrowe** [comment]
image

Red Circles: you must have left clicked these in development, they are off.  Turn them back on.
Blue Circle: What happened to the prisoner bed?
Yellow Circles: You do not want passive vents, you just want normal vents.
Green Circle: Instead of a skull and pirate bandana, you might want a prisoner outfit or better yet, replace that locker with a wall mounted prisoner space suit locker.

**Comment by UncaughtEx** [comment]
I have no clue how I forgot to put the prisoner bed back LMAO

**Comment by UncaughtEx** [comment]
I'll implement the suggested changes in a timely manner

**Review by MagnusCrowe — APPROVED** [review]
Forgot to mention to add a coat of space dirt.  Took care of it for you.

**Comment by UncaughtEx** [comment]
Thanks Magnus

**Pull request merged**
