### PR TITLE
NSF Whiskey: Sprite update and decal redecorate

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Updated the NSF Whiskey to use the new NFSD sprites and reapplied the floor decals.

## Why / Balance
As per #1230 the Whiskey needed an update.
While reworking the floor decals, I found a lot of them did not mesh well with the tiles used, so I replaced the decals to be less high contrast and visually intrusive. 

Removed the books and replaced with book spawners. 

## How to test
Checkout branch, loadgrid.

## Media
Whiskey

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None!

**Changelog**

:cl:
- tweak: Added new NSFD sprites to the NSF Whiskey and tweaked decals.

### CODE REVIEW

**Comment by dvir001** [comment]
No
image

Also you cab wrench your air tanks.

**Comment by Tych0theSynth** [comment]
> No image
> 
> Also you can wrench your air tanks.
> 
> Dont use air injectors, use passive vents

Ah, all that stuff was stuff that was on the shuttle already. I didn't touch those things but I can change them.

**Comment by dvir001** [comment]
> > No image
> > Also you can wrench your air tanks.
> > Dont use air injectors, use passive vents
> 
> Ah, all that stuff was stuff that was on the shuttle already. I didn't touch those things but I can change them.

Dam, lamo I was not even aware.

**Comment by Tych0theSynth** [comment]
> > > No image
> > > Also you can wrench your air tanks.
> > > Dont use air injectors, use passive vents
> > 
> > 
> > Ah, all that stuff was stuff that was on the shuttle already. I didn't touch those things but I can change them.
> 
> Dam, lamo I was not even aware.

Easy enough to change if they aren't meant to be there :)

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
