### PR TITLE
Ambition Directional fans (and sink)

### PR DESCRIPTION
**Pull request by blackknight954**
## About the PR
Replaced the tiny fans on the Ambition with directional fans, Added a sink to the janitor closet to provide a source of water (There were previously none)
## Why / Balance
Keeping ships up to regulation, providing water for a ship with no water

## How to test
Load a server,
Load the Ambition
Observe the changes

## Media
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A
**Changelog**
🆑 
- tweak: Swapped tiny fans for directional fans on all entrances of the Ambition, added a sink.

### CODE REVIEW

**Comment by dvir001** [comment]
Changelog is broken, use the format, no more then one line also

File is not right place.

**Comment by blackknight954** [comment]
> Changelog is broken, use the format, no more then one line also
> 
> File is not right place.
> 
> You left tiny fans

I believe it's all fixed, albeit I do not know if there is a way to mention the addition of the sink in the changelog without making a new PR for it, but if not, I can't really do much about it

**Comment by blackknight954** [comment]
After learning that I accidently "Crossed wires" with some of my branches so to speak, bumping this to ensure that it is fine to be merged and not cause any issues

**Comment by blackknight954** [comment]
Redoing changes to fix some file conflicts I found, will reupload soon

**Pull request closed without merging**
