### PR TITLE
MailPod (New)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added to new Mail Pod ship for the mail man

## Why / Balance
Small, effective and reliable mail ship for mail operations.
Build to be able to dock to all ships, with intention to support a bigger mail ship in the future.

## Media
image

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- add: Added the new mail ship, the Mail Pod, available for the mail carrier in the mail office.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
uh-oh! someone got caught smuggelin' dem APUs in his ship!

**Comment by ThatOneGoblin25** [comment]
We need wall mounted Pacman variants fr

**Comment by dvir001** [comment]
> I thought there was a new rule that APU weren't allowed to be mapped on ships anymore, outside of Sec?

Its a mail man only ship.

**Comment by Wolfking6116** [comment]
What was the purpose of nerfing the original then...? 😅

**Comment by dvir001** [comment]
> What was the purpose of nerfing the original then...? 😅

Original one used to be public facing.
After rework truck will also be getting them.

**Comment by MoistBiscuits** [comment]
Im not sure why this ship has an ATM, mail carriers are on SR's payroll.

**Comment by dvir001** [comment]
> Im not sure why this ship has an ATM, mail carriers are on SR's payroll.

Tipping

**Comment by dvir001** [comment]
Updated.

**Review by MagnusCrowe — APPROVED** [review]

**Comment by Danchi299** [comment]
Substations' input is HV Cable and output is MV Cable, it does not need a terminal, due to that the ship's power does not work.

**Comment by dvir001** [comment]
> Substations' input is HV Cable and output is MV Cable, it does not need a terminal, due to that the ship's power does not work.

I'll fix it in a new pr.

**Pull request merged**
