### PR TITLE
Updates bluespace syringe recipe to follow conventions

### PR DESCRIPTION
**Pull request by dustylens**
## About the PR

Changes the bluespace syringe to use the same materials types and same material cost per unit as the bluespace beaker and vial.
## Why / Balance

The bluespace syringe prices seemed very high given the new bluespace crystal component.

The 100u bluespace syringe materials cost is now 10% of the 1000u bluespace beaker. In between the syringe/beaker/vial.

Glass was removed from the recipe in favor of plastic. In line with the other bluespace devices and to mirror the vial change requests.

This seems pretty reasonable to me. 

## How to test

Check syringe recipes on medicaltechfab. Attempt to print using requested mats.

## Media

BSsyringe

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None.

**Changelog**

:cl:
- tweak: The bluespace syringe has had its recipe changed, it now costs less bluespace.

### CODE REVIEW

**Review by dvir001 — APPROVED** [review]
Fair

**Comment by whatston3** [comment]
Price should be marginally higher - you're getting the ability to suck large amounts of reagents off the floor without issue.  How expensive is a normal syringe compared to a normal beaker?

Comparing the vial vs. the beaker is closer to apples-to-apples than the syringe vs. the beaker.

**Comment by dvir001** [comment]
> Good consideration. I took a look at the differences between the basic beaker and syringe and found that the material difference between the two was closer to 62%.
> 
> I made the appropriate adjustments here and I think that the resource values feel more reasonable.

image
Fix please

**Comment by whatston3** [comment]
Happy with the new values.  Thanks.

**Review by whatston3 — APPROVED** [review]

**Pull request merged**
