### PR TITLE
grilled cheeses

### PR DESCRIPTION
**Pull request by immortalartisan**
## About the PR
adds grilled cheeses thats about it

## Why / Balance
Grilled cheese to go with the all the tomato soups

## How to test
Attempt to oven bake 2 slices of bread and any slice of cheese for 10 units of time. should result in a grilled cheese of each repsectivly 

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added Grilled cheeses
-->

### CODE REVIEW

**Comment by immortalartisan** [comment]
needs grilled cheese sprites still

**Comment by whatston3** [comment]
A few suggestions.

1. This exists upstream: https://github.com/space-wizards/space-station-14/pull/33807 - not sure of the fate of the thing, but grilled cheese might be used in time, and it might be odd to have two separate versions hanging about.  If you feel particularly strongly about your grilled cheese, fair enough, but make the case that yours is better.
2. There's a boatload of recipes and sprites from the talented people maintaining tgstation: https://tgstation13.org/wiki/Guide_to_food#Sandwiches

**Comment by whatston3** [comment]
> A few suggestions.
> 
> [snip]

If you'd like a hand with porting tgstation sandwiches or other recipes, do let me know, I think it'd be a good addition.

**Comment by ThatOneGoblin25** [comment]
The prototype and sprite already exists on DeltaV if you want to port that to Frontier.
https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Food/meals.yml

**Comment by immortalartisan** [comment]
going to close this assuming the upstream PR for grilled cheese is merged

**Pull request closed without merging**
