### PR TITLE
Allow linking defaults on conveyors

### PR DESCRIPTION
**Pull request by Alkheemist**
## About the PR
Split OnAddAlternativeSaveDeviceVerb into 3, so that the verb appears on entities with the DeviceLinkSink and DeviceLinkSource components.

## Why / Balance
Conveyors go brrrrrr
Probably other things that used links but lacked DeviceNetworkComponents also go brrrrrr

## How to test
With a multitool, start linking a lever, then alt click on as many conveyors as you like. Pull the lever.

## Media

https://github.com/user-attachments/assets/ea44b775-e730-4434-8d5c-ceb0fdfb03e3

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Made conveyors mass linkable with alt-clicking

### CODE REVIEW

**Comment by Alkheemist** [comment]
Actually this will also fix it for shutters too

**Comment by dvir001** [comment]
If you are doing the PR on frontier you need to add frontier comments.

In general this looks like it should be made a pr on Wizden also.

**Comment by Alkheemist** [comment]
You're right, it's a simpler fix to add the DeviceNetwork component to the conveyor, but that only fixes it for the conveyor. My implementation fixes it for any entity that is linkable but lacks DeviceNetwork.

I have no idea how the whole upstream upstream workflow works, do I just add wizden as an upstream in git and PR it there? Should I add it as a comment to the existing PR?

**Comment by whatston3** [comment]
> I have no idea how the whole upstream upstream workflow works, do I just add wizden as an upstream in git and PR it there? Should I add it as a comment to the existing PR?

You'd probably be best cloning the other repo, though I think you could add it as an upstream, checkout _its_ master, then branch off of that, add your feature, and PR it.

As-is, wouldn't this add two entries in the right-click menu for some linkable items if they _were_ setup with both DeviceLinkSourceComponent, and DeviceLinkSinkComponent (e.g. signal timer) and used with a multitool?  Couldn't you give the checks some priority (add for sources no matter what, add for sinks if not a source)?

**Comment by whatston3** [comment]
It's a reasonable addition, and unless there's some major complaint upstream (doubt it, but not my circus), I think it could be added on both sides (added here before the next upstream merge, combined at that point).

https://github.com/new-frontiers-14/frontier-station-14/pull/2457 Probably doing the same thing here.

**Comment by Alkheemist** [comment]
Added whatstone's suggested changes and frontier comments
dotnet_01_09-26-55

**Comment by Alkheemist** [comment]
matching PR on wizden, for reference: https://github.com/space-wizards/space-station-14/pull/33673

**Review by whatston3 — APPROVED** [review]
Looks good, works.  Changed a few of the comments, hope you don't mind.

**Comment by whatston3** [comment]
Going to merge this - if having a DeviceLinkSink/Source pair without a network is fine (and as-is, it's functional), this change makes sense irrespective of https://github.com/space-wizards/space-station-14/pull/32688.

**Pull request merged**
