### PR TITLE
Sprinter rework

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

Rework the sprinter:
- Remove spesos (Add some gold in its place)
- Remove hardcoded gun safe fill (Replaced with T1 shuttle gun safe)
- Remove hardcoded suit storage fill (Replaced with regular EVA suit storage)
- Remove all of atmos
- Re-add all of atmos, properly this time (Actually an upgrade cause the sprinter can now take both normal air tanks and oxygen/nitrogen tank combo)
- Remove all of power wiring
- Re-add all of power wiring, properly this time
- Remove plastitanium walls (Replaced with regular rwalls)
- Remove command intercom
- Remove (hopefully?) security intercom

**Lowers** the price from `75020` to `61250` (Spawned highest price point I rolled over 5 rolls was `53264`, I added 15% to this.)

## Why / Balance

Balance, that's why.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**

:cl:
- tweak: Sprinter was reworked.

### CODE REVIEW

**Comment by dvir001** [comment]
Can you also remove the security trackers?
They only need medical ones, as security report to security channel when someone die and needed for only sec forces.

**Comment by dvir001** [comment]
Also here is a cool trick, 
image

Place a pipe on top of it and color it then remove the pipe and it will fix the color on the port.

**Comment by TsjipTsjip** [comment]
Yeah I fucked up somewhere. The security intercom is still in even tho I explicitly deleted it, and so are the walls. Give me a moment.

**Comment by TsjipTsjip** [comment]
> Also here is a cool trick, image
> 
> Place a pipe on top of it and color it then remove the pipe and it will fix the color on the port.

Actually deliberately not colored.

**Comment by dvir001** [comment]
> > Also here is a cool trick, image
> > Place a pipe on top of it and color it then remove the pipe and it will fix the color on the port.
> 
> Actually deliberately not colored. (Parity with base SS14, where atmosia also only starts with colored pipes from the distro pump and onwards.)

Its since mappers dont know you can fix this :(

**Comment by TsjipTsjip** [comment]
> Its since mappers dont know you can fix this :(

How dare you do us like that man. (I'll fix it.)

**Comment by TsjipTsjip** [comment]
Ready for review.

**Comment by dvir001** [comment]
image

Made more changes:
Added Firelocks to internal doors, glass to glass, not glass to not glass
Updated the merc room to be a merc room
Added emergency lights since there were 0 of them
Wrenched airtank to floor
Made the AME start powered
Spliced the paramedic locker and the salvage to suit storages (Filled locker + Suit locker)
Added a lock toggle bolt next to prisoner door
Made the "kitchen" be an alcohol bar, left sink for water.
Moved the records computer to bridge
Added a fire extinguisher next to AME
Moved the deffib to the side wall for faster access
Removed the combat medic kit
Removed the random food vendors, go buy food some other place.

**Comment by Kesiath** [comment]
I'm fine with a rebalance pass, but please keep the engine nacelles on their distinct APCs. The gun closet area was never intended to be a merc room, it was the Captain's smuggling/gun storage room, and the bed was meant to hold bounty prisoners. Also, the stairs look so ugly on a dark floor :(

**Comment by mnemosynium** [comment]
Is the ship captain not having access to the prisoner room and armory an intended change with the mercenary airlocks?

**Comment by dvir001** [comment]
> I'm fine with a rebalance pass, but please keep the engine nacelles on their distinct APCs. The gun closet area was never intended to be a merc room, it was the Captain's smuggling/gun storage room, and the bed was meant to hold bounty prisoners. Also, the stairs look so ugly on a dark floor :(

Merc doors are captain and merc, the armory door was changed to also be merc for the holding cell to allow a merc to lock someone in there.

> Is the ship captain not having access to the prisoner room and armory an intended change with the mercenary airlocks?

Merc doors are captain and merc.

**Comment by mnemosynium** [comment]
> Merc doors are captain and merc.

[mercdoors.webm](https://github.com/new-frontiers-14/frontier-station-14/assets/153693227/5ba630fd-b004-4007-81e9-35ccbea5127b)

**Comment by dvir001** [comment]
> > Merc doors are captain and merc.
> 
> mercdoors.webm

https://github.com/new-frontiers-14/frontier-station-14/pull/838

**Comment by MagnusCrowe** [comment]
> Also, the stairs look so ugly on a dark floor :(

image
I recommend you find a solution that is as good or better than the original for the stairs, or revert that change.

**Comment by MagnusCrowe** [comment]
> I'm fine with a rebalance pass, but please keep the engine nacelles on their distinct APCs. 
I agree with Kes on this.
image

**Comment by MagnusCrowe** [comment]
If you're really worried about gasses from expedition making their way into the waste pipes, I recommend using a passive gate or a valve instead of a pump.

**Comment by TsjipTsjip** [comment]
This is what's on this PR now. RFR again.

image

**Comment by TsjipTsjip** [comment]
I have no clue what happened with those security ships in the mapchecker run but this PR does not impact that. Praeda and Wasp already have PR's open to fix that failure.

**Comment by Cheackraze** [comment]
> I have no clue what happened with those security ships in the mapchecker run but this PR does not impact that. Praeda and Wasp already have PR's open to fix that failure.

those 3 ships were removed from the generic 'Security' group and are in a custom group now, only spawnable through the empress' shipyard console

**Comment by TsjipTsjip** [comment]
> those 3 ships were removed from the generic 'Security' group and are in a custom group now, only spawnable through the empress' shipyard console

Thaaat.... makes sense. I'll modify the mapchecker to account for that in a separate PR.

**Review by dvir001 — APPROVED** [review]
Tested in game, everything in place,
One new issue I found is the ``SuitStorageMercenary`` missing perms for captain but this need to be fixed in its own PR.

**Comment by MagnusCrowe** [comment]
Good work!

**Pull request merged**
