### PR TITLE
Cargo permissions

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Fix issue with borgs able to place orders
Give order rights to everyone.

## Why / Balance
Require an ID to place orders

## Technical details
.yml

## Media
N/A

## Breaking changes
Placing cargo orders require an ID card, all roles comes with ``Orders``
Losing PDA / Card wont allow placing orders.

**Changelog**
:cl: dvir01
- tweak: Cargo require you to have your ID when placing orders to verify your identity, make sure to not lose your ID.

### CODE REVIEW

**Comment by Cheackraze** [comment]
idk that seems kind of harsh, what exactly was the issue? borgs being able to buy things? Why was that an issue?

**Comment by dvir001** [comment]
> idk that seems kind of harsh, what exactly was the issue? borgs being able to buy things? Why was that an issue?

Borgs link to your "real" body bank when you spawn as a borg on round start, so you can buy based on it, its a bit silly that you can do it.

This will also remove your right to use cargo if you been borged technically, but its for the best since based on RP someone can force you to buy stuff for free LAMO

**Comment by Cheackraze** [comment]
You need to remove the requirement to have an ID.  Bank accounts aren't linked to ID, it's linked to the character/mind.

**Comment by dvir001** [comment]
> You need to remove the requirement to have an ID. Bank accounts aren't linked to ID, it's linked to the character/mind.

Im not sure I understand what you asking me to change
Is there another way around this?

You mean you want me to set the cargo permission on the player entity itself?
I think it can work considering thats how Borgs work with door perms, kinda.

If this what you mean let me know and ill assign it to the players based on all races except silicon.

Assuming this will work it will need some testing to make sure its not fucking with something else.

**Comment by Cheackraze** [comment]
i think borgs using machines is just fine, and I dont really have much of an issue with them being able to withdraw from their main's accounts.  In any case, it should in no way ever be tied to or require an ID. Bank accounts are not at all associated with ID and that will make the system feel broken and unfinished.

**Comment by dvir001** [comment]
> i think borgs using machines is just fine, and I dont really have much of an issue with them being able to withdraw from their main's accounts. In any case, it should in no way ever be tied to or require an ID. Bank accounts are not at all associated with ID and that will make the system feel broken and unfinished.

The borg thing is more of an RP issue then a bug
Ill close it for now, if its still needed ill look into editing the borgs to have limits.

**Pull request closed without merging**
