### PR TITLE
Pacified Zone: filter immune users by playtime

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds an optional time requirement to the pacified zone.  This has been set to 10 hours for the default Frontier zones.

The common update logic in the PacifiedZoneSystem was pushed into a function to reduce redundancy.

## Why / Balance

On Frontier, the pacified zone's most useful on Frontier Station for preventing raiders, this makes it more in tune with that.

Changing the prototypes might be annoying for downstream forks - we could create ones specifically for the bus and Frontier that we use with these time limits.  Also, if this was to be used for anything else (e.g. NFSD riot beacons), this field would need to be removed.

## How to test

1. Spawn as a new character (connect as a new user to your local server).
2. Frontier's under pacified zone, the bus is under pacified zone (either check the dev map or wait for it to FTL)
3. Give your character 10 hours of playtime (`playtime_addoverall <localhost@JoeGenero> 36000`)
4. Respawn.  No pacified zone.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Frontier's pacified zone now only affects users with 10 hours of playtime or less.

### CODE REVIEW

**Comment by dvir001** [comment]
Might want to add same protos with and without the time thing as to allow us to just pick from them

**Comment by whatston3** [comment]
> Might want to add same protos with and without the time thing as to allow us to just pick from them, then we can also add this to more POI

Changes pushed to add "Panic Bunker" variants, base set are only NFSD-immune.  Seems fine under test.

**Comment by whatston3** [comment]
> I'm personally convinced there are different ways to solve this than to query someone's playtime in a update function, and i dont understand why the 10 hours matter during a round.
> 
> Hear me out for this potential solution; Add or modify a component on the client's mind that identifies them as someone under 10hr playtime upon entering a shift.
> 
> Save it into a boolean on the mind and use that in the update check.
> 
> I dont feel that there is a need to switch this mark suddenly at the 10hr mark to be that important

Imagine being able to remove the panic bunker altogether.

**Comment by dvir001** [comment]
Main goal will be to have it used on all main players spawn safe POI's if we can adjust it to just detect 10 hours or less of play time it will allow us to adjust panic bunker or even removing it.

**Comment by whatston3** [comment]
Swapped out the way the playtime was being checked, seems to work fine under tests - GetCachedPlayerInfo seems fine, reads from an internal dictionary kept up-to-date by the AdminSystem, no DB hits.

I'm happy with this.

This should give the potential to have differently vetted zones by time (can't see a use case to be frank), and requires less event finagling.

Thought about checking for set membership before pacifism preconditions, decided against it - a newly connected user should not be pacified in a zone where they meet the time requirements.

**Pull request merged**
