### PR TITLE
(NEW) NFS Vitalis - Brigmedic's Ship

### PR DESCRIPTION
**Pull request by Myzumi**
## About the PR

This adds in a new NFSD Brigmedic ship designed for about 2 Brigmedic's. It is equiped with a Medbay aswell as an Cryogenic Area. This is also a reason that it gotten an Chemical Area aswell as a small Botany Area to be ready to make Cryogenetic Chemicals. 

**The Ship has been Mapped by Yukari while myself have done the YML work to add in into the Shipyard & the Github PR.**

The Corsair is a Medium Medical Ship with a total tile count of 398, Priced at 60k (Appraisal is 48680) made for the Deployment of Cryogenetic's Brigmedics to help out the Frontier Space with Medical and their Deparment.

## Why / Balance

There has been many Brigmedic Ships like the Whiskey or Hospitaler, yet they either dont have any Cryogenetics (Kinda the current Medical "meta") or are discontinuted and not Serviced anymore. With that Background we have decided to make a new Brigmedic ship, most of the work was done by Yukari while me and some others gave feedback onto this.

## How to test

- Spawn as Brigmedic
- Go to Shipyard
- Buy Ship
- Blow up While mixing Chemicals
- Enjoy Ship

## Media

image

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added the NFS Vitalis, The Ship for the Brigmedic's

### CODE REVIEW

**Comment by whatston3** [comment]
Not the greatest name, won't lie.

image
[Wiktionary, coursair](https://en.wiktionary.org/wiki/corsair)

**Comment by Temoffy** [comment]
What about calling it the Hacksaw?

**Comment by Temoffy** [comment]
Or Bonesaw

**Comment by BlueHNT** [comment]
At that point you could go choosing some more interesting names Temoffy... Like Triage, Vena Cava, Exsanguinator, Sanitorium or even Patchwork.

**Comment by Myzumi** [comment]
As something interesting is, It has been renamed to NFS Vitalis already >.>

**Comment by BlueHNT** [comment]
> As something interesting is, It has been renamed to NFS Vitalis already >.>

I like the name :)

**Comment by Houtblokje** [comment]
> As something interesting is, It has been renamed to NFS Vitalis already >.>

The changelog still says corsair.

Honestly, this ship looks really good, though I am personally not a huge fan of two uranium generators, especially as you should have enough space to put an AME in there. But yeah, as a somewhat sporadic NFSD player I would love to see this ship be added. It does look really nice. I hope the maintainers look at this when the contribution freeze ends and that they aren't too hard on it.

**Comment by MagnusCrowe** [comment]
I fear this will encourage brig medics to operate independently.  The same issue we had to remove the Whiskey for.

**Comment by GiggIess** [comment]
> I fear this will encourage brig medics to operate independently. The same issue we had to remove the Whiskey for.

I'm coming out of the wood works to say this was never really an issue, and if it was, it must've been a VERY small amount of players who did this. There's already nothing stopping Brigmedics from operating independently, as they can buy a multitude of small ships after spending 10 minutes in a chem lab to get what they need for the rest of the shift. 

I've always disagreed with removing the Whiskey, as it felt it was needlessly removing content for non-existent problems. I think the NFSD and community are in a healthy enough place right now where Brigmedics can be trusted not to silently fuck off in their own ship, and if they do, they can just be ordered back. Same as anybody else in the department buying their own ship and fucking off, really. Should we disallow deputies from buying their own ships too?

**Comment by dvir001** [comment]
I didn't forget why we removed brigmedic ships, the brigmedic job is to work on a ship with his team not to have a private oversized ship for the job.

**Comment by MagnusCrowe** [comment]
> The NFSD appears to lack access to medical infrastructure unless they pull an Empress.
> 
> Magnus and Dvir don't want the brigmed to have a ship with medical infrastructure.
> 
> If the lack of medical infrastructure without an Empress is the concern. Adding it to the NFSD HQ seems to be the solution.
> 
> Complaint: NFSD HQ shouldn't get medical equipment because X Counter: They'll just pull an Empress to get the equipment regardless. If the desire is to reduce the reliance on the Empress that appears to present the logical solution.

I personally have no issue giving NFSD some more medical facilities for the brig medic to use.

**Comment by arimah** [comment]
> Magnus and Dvir don't want the brigmed to have a ship with medical infrastructure.

I'll happily add myself to that list. The NFSD should work more with civilians. Break the silos, encourage collaboration and building of trust. >:3

**Comment by dvir001** [comment]
Ill probably need to get @Salvantrix to comment on this, since there was few incident that led to the removal of whiskey.

**Comment by Salvantrix** [comment]
> I fear this will encourage brig medics to operate independently.  The same issue we had to remove the Whiskey for.

I will agree with Magnus on this one, I've witnessed many a brigmed screw off into infinity when they have the capability. The Brigmedic should operate off of the capital ships or from the comfort of the NFSD poi.

**Comment by GreyMario** [comment]
Why are we once again "resolving" problem players by taking content away from everyone? Brigmedics are a much smaller subset of players and a lot easier to job ban for fucking off into the abyss.

**Comment by DonkElfLawyer** [comment]
I love brigmedic, and this ship clearly has alot of soul put into it. While I'd personally rather just have chemstations on the outpost, I think that multiple playstyles should be encouraged. Moderate by player instead of by an incident months ago.

**Comment by GiggIess** [comment]
What the others have said already, why are the rest of us being punished for the actions of problem players? Why not just job ban the problem players and let us have the option to use a ship if the Sheriff allows us too? Your arguments for why this ship shouldn't exist boils down to Brigmedics not doing their jobs, and that should be a non-issue because if people can't do their job, then they don't get to play as their job. 

I've seen it commonly brought up by the Admins that Brigmedics don't know how to properly balance civilian medical, and their duties as an Officer. And by god, I just want to tie you all to chairs and force you to watch me play, because it is SO incredibly easy to balance your duties first, and help out with civilian medical when the docs are overwhelmed. Citing that all Brigmedics can't properly balance their work as reason for them not getting ships or in an extreme case, the straight up removal of the job, is a genuinely pathetic strawman.

**Comment by GiggIess** [comment]
> It's not punishment.

It feels like one when Brigmedics lose out on content and playability because of the actions of some other people time ago.

**Comment by MagnusCrowe** [comment]
> > It's not punishment.
> 
> It feels like one when Brigmedics lose out on content and playability because of the actions of some other people time ago.

If it helps you feel better, the Whiskey wasn't removed because of bad actors, it was removed because it encouraged bad actors.

So removing it wasn't a punishment.  Consider it a revision in overall game design, like removing the captain's bar from Frontier outpost back in the day.  The bar was encouraging behavior that Checkraze did not want to encourage.  Nobody was being punished for their behavior, Checkraze just recognized the design was causing something he did not want to cause and removed it.

**Comment by Myzumi** [comment]
Me and Other Admins aswell as Maintainers/Maptainers have Discussed this and will be Denied as an NFSD ship.
The Vitalis will be Recolored in the Coming days as an Civilian Ship

**Pull request closed without merging**
