### PR TITLE
Point (New) - Scrap science ship

### PR DESCRIPTION
**Pull request by Spessmann**
## About the PR
Adds the ship SV Point, a science ship purchasable from the salvage terminal.

## Why / Balance
This ships acts as a cheap ($16,000) and simple artifact research ship that comes with a few downside of having to run two P.A.C.M.A.N. generators to power the ship (artifact scanner is very power hungry), and having to walk into space to get to the lab or to refuel generators. It also it only has one docking port.

## Media
Screenshot 2024-01-19 171438
(Not shown in screenshot: a scientist spawn and a passenger spawn)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the ship, SV Point, a science ship purchasable from the scrap terminal.

### CODE REVIEW

**Comment by dvir001** [comment]
Make sure you move the map file under _NF

**Comment by Spessmann** [comment]
point.yml has been put under _NF, it should now be aligned with the new formats

**Comment by Wolfking6116** [comment]
Please be kind and give the ship a tiny fan on where its "intended" docking bay doors (plural, for stability since can glitch out if only connected at 1 point) are suppose to be, otherwise all it takes is a SEC Hospitaller to dock to them to space the entire ship.

**Comment by dvir001** [comment]
> Please be kind and give the ship a tiny fan on where its "intended" docking bay doors (plural, for stability since can glitch out if only connected at 1 point) are suppose to be, otherwise all it takes is a SEC Hospitaller to dock to them to space the entire ship.
> 
> Super excited to see more SV ships, especially a janky sci ship, by the way!

This is actually required and will be added to all SV as reworks so please add one to the dock if there is none.

**Comment by Spessmann** [comment]
> Please be kind and give the ship a tiny fan on where its "intended" docking bay doors (plural, for stability since can glitch out if only connected at 1 point) are suppose to be, otherwise all it takes is a SEC Hospitaller to dock to them to space the entire ship.

I'm confused by the wording of this request. If you are asking for a tiny fan under the existing docking bay door, there is currently a tiny fan under the door. However if you are requesting for another door with a tiny fan, I can add that then.

**Comment by Wolfking6116** [comment]
> > Please be kind and give the ship a tiny fan on where its "intended" docking bay doors (plural, for stability since can glitch out if only connected at 1 point) are suppose to be, otherwise all it takes is a SEC Hospitaller to dock to them to space the entire ship.
> 
> I'm confused by the wording of this request. If you are asking for a tiny fan under the existing docking bay door, there is currently a tiny fan under the door. However if you are requesting for another door with a tiny fan, I can add that then.

Apologies on the wording; I'm not one of the testers so I could not / do not know how test your ship, and was unaware if there was already a Tiny Fan or not. Most all of the other SV ships have the current issue of lacking them on their docking ports, so I wanted to mention it just in case! 

Otherwise I was requesting a second door be added - or at least a broken spot where a second door 'could be' if someone fixed it. Generally if a ship doesn't have at least 2 points of contact when docked and something bumps them they can cause erratic shaking, possibly breaking off and glitching out.

**Comment by dvir001** [comment]
> > Please be kind and give the ship a tiny fan on where its "intended" docking bay doors (plural, for stability since can glitch out if only connected at 1 point) are suppose to be, otherwise all it takes is a SEC Hospitaller to dock to them to space the entire ship.
> 
> I'm confused by the wording of this request. If you are asking for a tiny fan under the existing docking bay door, there is currently a tiny fan under the door. However if you are requesting for another door with a tiny fan, I can add that then.

All good then.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
1. Replace the generator with the "ship" version that starts half filled and running.
2. The gyroscope seems to be off by default.
3. The shuttle console is broken somehow.
image
4. Color your waste pipe.
5. You have no jobs?  Intentional?
image
6. Space wind is going to rip up any floor tile on the exterior of the ship so you should add vacuum tiles to anything you don't want being ripped up.

Fix these things and I'll review again.

**Comment by MagnusCrowe** [comment]
> * Ship needs a filled defib cabinet and a fire extinguiser according to mapping rules
> * right click a waste pipe, check it's net id and run `colornetwork <_netid> Pipe #990000`  on it, replacing `<_netid>` with the _netId of the pipe.
> * Do same for distro line pipe but color `#0055cc`

We don't force people into specific piping colors. Warm colors for waste, cool colors for distro.  

Also there is a fire extinguisher, it's in the fire wall locker.  IDK what you mean about the file cabinet...there is one.

**Comment by Spessmann** [comment]
@MagnusCrowe  I have updated the ship as you requested. The shuttle console _should_ work now. The jobs not being in there was because I was recommend to remove them on discord (this applies to all salvaged ships) "because a new player could join and die to a hazard (space, shotty construction) on board"
Screenshot 2024-02-27 214608

**Review by MagnusCrowe — APPROVED** [review]
Had to increase the price and turn on your gyro.

**Pull request merged**
