### PR TITLE
Make the shuttles compatible with MapRenderer

### PR DESCRIPTION
**Pull request by lermal**
## About the PR
Made all shuttles available to MapRenderer by adding or changing their BecomesStation values to the correct ones.

## Why / Balance
This is required for easy MapRenderer rendering of any shuttles.

## How to test
Use `dotnet run --protect Content.MapRenderer shuttle_name`  in server console.

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- fix: Fixed MapRenderer rendering for all shuttles

### CODE REVIEW

**Comment by lermal** [comment]
> Is this creating a new issue in some way for russian servers that need it localized?
> 
> This should be a code side fix not yaml probably.

This is the only solution I've used to render all the shuttles. As far as I know mappers themselves have to add BecomesStation component to their maps.

**Comment by whatston3** [comment]
Largely fine.

The Chauffeur isn't an "actual shuttle", it should not have a separate map unless it has _actual changes_ vs. the PTS.  Get the GameMapPrototype to point to the PTS map, change the entry under `stations` to match the BecomesStationComponent in that file - this should work?

```yml
- type: gameMap
  id: Chauffeur
  mapName: 'NC Chauffeur'
  mapPath: /Maps/_NF/Shuttles/pts.yml
  minPlayers: 0
  stations:
    PTS:
      stationProto: StandardFrontierVessel
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Chauffeur {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: '14'
```

Vessels do not have to be 1:1 with GameMaps, and that BecomesStation does not have to match the actual ID of any game map - all of this is fine.  If you want the MapRenderer to work with vessel IDs, that can work, the VesselPrototype points to a file that you can load and render.

**Comment by lermal** [comment]
> Largely fine.
> 
> The Chauffeur isn't an "actual shuttle", it should not have a separate map unless it has _actual changes_ vs. the PTS. Get the GameMapPrototype to point to the PTS map, change the entry under `stations` to match the BecomesStationComponent in that file - this should work?
> 
> ```yaml
> - type: gameMap
>   id: Chauffeur
>   mapName: 'NC Chauffeur'
>   mapPath: /Maps/_NF/Shuttles/pts.yml
>   minPlayers: 0
>   stations:
>     PTS:
>       stationProto: StandardFrontierVessel
>       components:
>         - type: StationNameSetup
>           mapNameTemplate: 'Chauffeur {1}'
>           nameGenerator:
>             !type:NanotrasenNameGenerator
>             prefixCreator: '14'
> ```
> 
> Vessels do not have to be 1:1 with GameMaps, and that BecomesStation does not have to match the actual ID of any game map - all of this is fine. If you want the MapRenderer to work with vessel IDs, that can work, the VesselPrototype points to a file that you can load and render.

I originally tried to do that, however, when I tried to buy a shuttle - my server crashed

**Comment by lermal** [comment]
And the renderer doesn't work if BecomesStation is not specified

**Comment by dvir001** [comment]
> Largely fine.
> 
> The Chauffeur isn't an "actual shuttle", it should not have a separate map unless it has _actual changes_ vs. the PTS. Get the GameMapPrototype to point to the PTS map, change the entry under `stations` to match the BecomesStationComponent in that file - this should work?
> 
> ```yaml
> - type: gameMap
>   id: Chauffeur
>   mapName: 'NC Chauffeur'
>   mapPath: /Maps/_NF/Shuttles/pts.yml
>   minPlayers: 0
>   stations:
>     PTS:
>       stationProto: StandardFrontierVessel
>       components:
>         - type: StationNameSetup
>           mapNameTemplate: 'Chauffeur {1}'
>           nameGenerator:
>             !type:NanotrasenNameGenerator
>             prefixCreator: '14'
> ```
> 
> Vessels do not have to be 1:1 with GameMaps, and that BecomesStation does not have to match the actual ID of any game map - all of this is fine. If you want the MapRenderer to work with vessel IDs, that can work, the VesselPrototype points to a file that you can load and render.

Its fine, we plan to make it a real shuttle later, the copy paste isnt an issue for now.

**Comment by dvir001** [comment]
Going to merge this but we really need a fix that wont require fucking with yml everytime

**Pull request merged**
