### PR TITLE
Weapon Racks Update

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Some changes to weapon racks:
- Weapon racks no longer act like lockers in disguise.
- Cleaned up .yml files.
- Cleaned up .rsi.
- Started introducing departmental variations: Security, Command (Captain), Salvage, Mercenary (will add more thematically fitting weapon sprites to racks later).
- Crossbows now can be stored in gun racks.

## Why / Balance
Bugfixes.

## Technical details
.yml changes, .rsi folder structure changes

## Media
image image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Breaking changes
Some entities were deleted: `WeaponRackRestricted`, `WeaponRackWallmountedRestricted`, `WeaponRackMeleeRestricted`, `WeaponRackMeleeWallmountedRestricted`, `WeaponRackPistolRestricted` and `WeaponRackPistolWallmountedRestricted`

**Changelog**
:cl: erhardsteinhauer
- add: Added Weapon Racks variations - Security, Command, Salvage, Mercenary.
- fix: Fixed Weapon Rack acting as lockers in disguise.

### CODE REVIEW

**Comment by dvir001** [comment]
Im using one in the merc dungeon tileset.
Can you add some migration to it or edit the map to fix it on the same PR?

**Comment by ErhardSteinhauer** [comment]
Dunno how to add migration.
I guess I can create merc specific variation with the freshly deleted IDs.

**Comment by dvir001** [comment]
> Dunno how to add migration. I guess I can create merc specific variation with the freshly deleted IDs.

No need, just replace it on the grid with map editor
Its in the bounty hunter office.

**Comment by ErhardSteinhauer** [comment]
> > Dunno how to add migration. I guess I can create merc specific variation with the freshly deleted IDs.
> 
> No need, just replace it on the grid with map editor Its in the bounty hunter office. lava_mercenary.yml

Do I save it as grid after editing?

**Comment by dvir001** [comment]
> > > Dunno how to add migration. I guess I can create merc specific variation with the freshly deleted IDs.
> > 
> > 
> > No need, just replace it on the grid with map editor Its in the bounty hunter office. lava_mercenary.yml
> 
> Do I save it as grid after editing?

Yes

**Comment by ErhardSteinhauer** [comment]
Prolly fixed now

**Review by dvir001 — APPROVED** [review]
Working fine.

**Pull request merged**
