### PR TITLE
Brigantine

### PR DESCRIPTION
**Pull request by Helicaste**
Remake of previous post due to not wanting to fight git.

## About the PR

Adds the Brigantine, a Small Security Hub-ship.

## Why / Balance

This ship fills the gap of being a low-price small ship designed to accommodate permabrig prisoners.

It comes with;
1 Baliff hardsuit, 2x Security Hardsuit, Secfab, Kammerer Safe, WT550 Safe, a few bits of assorted Security gear, and is powered by an RTG and one PACMAN.

## Technical details

.yml additions

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
(Image is barely cutoff, only thing not shown is some engines and the dock.)

image

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added the Brigantine, a cheap Security ship designed to accommodate Permabrig prisoners.

### CODE REVIEW

**Comment by Helicaste** [comment]
Any status update?

**Comment by YumiGumi** [comment]
this amount of plasma glass at round start would be impossible to balance, my suggestion is reduce the amount to as low as you can get it.

**Comment by Cheackraze** [comment]
its getting there, much better than the first version, i just wasnt aware it had been updated.  The decals in your screenshot seem like they arent aligned properly, but I'll load it up in game to make sure once its all ready.

So, we have special plastititanium windows now that you should use instead of plasma windows.  And for the second point, the corners of your ship are very weak when mapped like that. The kitty-corner pieces should be filled out with at least angled wall sections to connect them.  Other than that, I appologize for thinking this was still waiting for other changes, and let me know here or on discord once you make those 2 changes and then I can do final review and merge it!

**Comment by MagnusCrowe** [comment]
This has been inactive for a while so I am going to close it for now.  Please feel free to reopen if you still want to work on it.

**Pull request closed without merging**
