### PR TITLE
Power Cell/Svalinn Laser Pistol Projectile Change

### PR DESCRIPTION
**Pull request by The048**
## About the PR
Changes the projectile type of power cells to RedLaser [which deals 14 damage] instead of RedLightLaser [which does 7 damage].
## Why / Balance
As of right now, the Svalinn Laser pistol is, in almost every way outclassed by any other ranged weapon. While the ability for an energy weapon to reload its power source is interesting and useful, dealing a pitiful 7 damage per shot means that it would require a full medium-capacity power cell plus a few extra shots to deal a minimum of 100 damage. This makes the Svalinn generally unviable for just about every purpose, since a weapon that cannot deal reasonable damage just does not compare to the much stronger offerings of other weapons.

While this may somewhat intrude on the viability of the Advanced and Antique laser pistols, I believe that the need to carry extra power cells as ammunition and still slightly inferior damage would keep it in check, while still making it viable as a weapon. The inability to refill batteries on the spot without a tier 3 technology would make the Svalinn weak for extended work involving combat, and the overall damage of the Svalinn is still inferior to a decent amount of ballistic weapons. These changes should still give room for ballistic weapons and true infinite ammo laser weapons to still have their distinct advantages and disadvantages over this weapon.
## How to test
1. Start a local instance
2. Spawn in a Svalinn Laser Pistol and a target.
3. Shoot a target and check the damage number

## Changelog
- tweak: changed the power cell projectile type to RedLaser.

### CODE REVIEW

**Comment by dvir001** [comment]
This need to be on upstream as its an upstream gun, im not a fan of having the same gun with different numbers here.

**Comment by Cheackraze** [comment]
this instead makes the weapon the strongest laser weaponry available, with the easiest ammo to get, printable from lathes. Even for the stated rebalance, this is insanely way too far. Its fine how it is if you ask me, it fits fine in its place as a 'scrap' weapon

**Comment by The048** [comment]
> this instead makes the weapon the strongest laser weaponry available, with the easiest ammo to get, printable from lathes. Even for the stated rebalance, this is insanely way too far. Its fine how it is if you ask me, it fits fine in its place as a 'scrap' weapon

While I personally believe that the laser pistol should fit the role of "weakest energy weapon", I do understand how the ease of acquisition would make this a bit overpowered, at least among lasers. If it were to be removed from the lathes that don't have server access to the Svalinn's dedicated tier 3 research [which currently does not seem to serve any purpose], could that make it less of an issue?

**Comment by dvir001** [comment]
My main issues here is honestly with consistent changes before we even talk balance.

Here is the thing, if I see the same gun sprite, name, and info on any server, im going to say its 7 damage.

Unless you are making a new sprite for a Svalinn Tier 2 that make it clear its not the same gun anymore, this isn't a good change for an existing well known upstream gun right now.

**Comment by arimah** [comment]
I agree with Darin. I'm in favour of having a tier 2 laser gun that's better than the Svalinn, but we should avoid changing an instantly recognisable upstream gun to be twice as powerful. Even with a microreactor cell, it wouldn't be as good as the advanced or antique laser pistol, which both do 17 heat per hit and recharge faster, so in my mind there would still be value in researching tier 3 arsenal.

**Comment by ErhardSteinhauer** [comment]
The problem is: the damage for svalinn isn't tied to the gun itself, the damage is tied to the batteries. So the new gun doesn't solve the problem at hand: need new batteries instead.

**Comment by ErhardSteinhauer** [comment]
I find it very frustrating, that the projectile type is defined on the fucking batteries and not on the gun that uses batteries. Tbc it's not a jab against this PR.

**Pull request closed without merging**
