### PR TITLE
Buffed PTK-800

### PR DESCRIPTION
**Pull request by Eponymic-sys**
## About the PR

Set the kineticshuttle projectile to fire more than one shot and have spread, increased the power draw to discourage people running crazy numbers of em. Dropped from flatpackvend to hopefully drive people to science ships or get excited when they find one.

## Why / Balance

PTK-800s are kinda weaksauce compared to just using a crusher. Giving em spread is a nice buff. You still have to fight the mobs because it does basically no damage. Might need tuning.

## How to test

Spawn in, set up PTK-800 on ship, start blasting

## Media

blasting

## Requirements

- [ x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

 Buffed PTK-800, increased power draw, dropped from flatpackvend

### CODE REVIEW

**Comment by Cheackraze** [comment]
we could definitely play around with the PTK's values so long as we keep the actual *damage* it does low. I've also considered evening out the fire rate to be a bit more 'logical', so it doesnt do a burst of 5 in a row and then a slow recharge etc.

**Comment by dvir001** [comment]
``Dropped from flatpackvend to hopefully drive people to science ships or get excited when they find one.``
DId you actully test this 2 claims? since they dont work right now for the normal player.

**Comment by Eponymic-sys** [comment]
You're right about the board, saw it in https://github.com/new-frontiers-14/frontier-station-14/blob/master/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L566 and made the assumption.

I'll add it back to the flatpackvend and work on a research one when I get  to making a sprite.

**Comment by dvir001** [comment]
> You're right about the board, saw it in https://github.com/new-frontiers-14/frontier-station-14/blob/master/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L566 and made the assumption.
> 
> I'll add it back to the flatpackvend and work on a research one when I get to making a sprite.

Don't return to vend, just make sure it's in flat pack rewards pool for expo pool

**Comment by whatston3** [comment]
Here's a thought.

The PTK should be a niche tool instead of a blanket improvement.  There is no consistent, credible threat in space, so there should, at bare minimum, be some downside to using the platform, while certain uses should be given boons.

Suppose you replaced all walls on asteroids with some form of hardened rock, with the possibility of ore clusters inside.  These rocks could have larger deposits of ore (clusters of 10, 15?).  Add a check to MiningSystem.OnDestruction that looks for tags in the same way that the GatherableSystem does.  Bad tag?  Reduced chance of successful mining.  The PTK gives reduced payouts when mining normal rock (overpenetration, blasting the ore into dust?) - either a percentage chance of destruction (probably the best choice, easiest to tweak), or a separate spawn pool.

This way, you either make a time tradeoff (blast all the rocks and take whatever limited payout you get - needs to be a balance consideration for the destruction rate), or you go out and mine and come back.  Maybe you want to hand mine the particularly juicy ores and blast all the other rocks away.

**Comment by Eponymic-sys** [comment]
> > You're right about the board, saw it in https://github.com/new-frontiers-14/frontier-station-14/blob/master/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L566 and made the assumption.
> > I'll add it back to the flatpackvend and work on a research one when I get to making a sprite.
> 
> Don't return to vend, just make sure it's in flat pack rewards pool for expo pool

They show up in supply spawners, not sure if that's what you mean or somewhere else.

**Comment by whatston3** [comment]
Got a suggestion that essentially does what my previous comment says, changes up at [whatston3:2024-12-03-ptk-suggestions (vs. feature branch)](https://github.com/Eponymic-sys/frontier-station-14/compare/ptk_changes...whatston3:frontier-station-14:2024-12-03-ptk-suggestions?expand=1)

On the head of this branch, asteroids (currently only the ice asteroids) will spawn with ore in rocks, and occasionally ore in the walls.  The veins in walls are more dense than rock veins and contain more stuff.  The walls can be destroyed with PTK bolts, diamond drills, or a holopickaxe - nothing else.  The catch with the PTK bolts?  They destroy ore in softer rock.

This way, the PTK serves a purpose (destroying hardened mining targets), and if it's accessible without research, that's fine - there are practical upgrades that miners should want and be willing to buy off others, and these should get them out onto the rocks.

**Comment by dvir001** [comment]
Going to close this PR, were finishing https://github.com/new-frontiers-14/frontier-station-14/pull/2521

**Pull request closed without merging**
