### PR TITLE
Increase tall lizard density 

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Makes lizards with the tall trait have more "mass" again.

## Why / Balance

The mass was originally removed due to mass-contest issues and how it affected mostly combat with shoves insta stunning people with 1 or 2 shoves, but since it was removed it will not longer affect players with less mass.

On terms of what will affect on balance.

Pros:
More easy to pull crates and objects.

Cons:
- Harder to fit on tight spaces (already with the bigger size).
- Harder to move on low gravity areas or space since inertia will affect them more due to larger mass.
- When on critical or dead condition will be much harder to pull around and drag.
- Easier target to shoot at.

## Technical details

2 lines of YML

**Changelog**

:cl: Leander

- tweak: Tall lizards got into a new diet and all of them have gained more weight.

### CODE REVIEW

**Comment by dvir001** [comment]
No
Trait should never be a "click for buff"
Also this is bullshit as the hitbox stay the same

**Comment by Leander-0** [comment]
> No Trait should never be a "click for buff" Also this is bullshit as the hitbox stay the same

What is the buff? moving crates more easily? then honestly at this rate remove all the trait sizes then and more all species equal, tell me why then vulpkanins can "click for buff" for being small fit inside dufflebags and backpacks too since thats pretty much a real buff.

**Comment by Mnemotechnician** [comment]
> Also this is bullshit as the hitbox stay the same

False. All people have circular fixtures, whose mass depends on their density and radius (Pi * radius^2 * density) kg. The tall trait affects both the radius of the fixture and its density.

**Comment by dvir001** [comment]
> > Also this is bullshit as the hitbox stay the same
> 
> False. All people have circular fixtures, whose mass depends on their density and radius: (Pi * radius^2 * density) kg. The tall trait affects both the radius of the fixture and its density.

So the small trait buff you with a smaller hitbox?

**Comment by Mnemotechnician** [comment]
> So the small trait buff you with a smaller hitbox?

you pay a big price for it, and it's hardly a buff :p

or at least used to, before mass contests were removed - the attempt to "improve balance" broke the balance

**Comment by MagnusCrowe** [comment]
Does this not also increase the amount of biomass needed for cloning?

**Comment by VividPups** [comment]
> Does this not also increase the amount of biomass needed for cloning?

I remember Bigger things required more for cloning in the past

**Comment by dvir001** [comment]
I'm hopping, we can get size slider added then have some actual code based around it for mass later.
For now, I think we should not mess with any size related stuff till we can add a system that isn't trait based to replace it.
Said system will also need support to enable the "felinid" go into bags under X scale for vulps if its still needed.

**Comment by dvir001** [comment]
Closing this till someone add a new size system or just use the Cosmatic Drift one since we got Lank approval to do so anyway.

**Pull request closed without merging**
