### PR TITLE
Change NFSD radio color

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Changes the NFSD color of the radio and organizes the new keys to be included on the new headsets when spawned as officer.

## Why / Balance

All needs to be recolored and they require their own sprites for their encryption keys.

## Technical details

Changed the hotkey to use the radio from "S" to "G" to the original red security color and then the new NFSD radio color takes the "S" hotkey for radio also organized the files for more stuff to be on the _NF folders.

This PR will be a draft until the NFSD encryption keys are sprited.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Leander
- add: NFSD got a new color on their radio with new frequency.

### CODE REVIEW

**Comment by dvir001** [comment]
This is a bit cunfusing, ``s`` is now NFSD?
This will confuse people coming from other forks with macule memory, best to keep nfsd as the new ``g``.

**Comment by dvir001** [comment]
Also make sure the channel is replaced for systems like the M_EMP and the security records and shipyard.

**Comment by dvir001** [comment]
Also make sure there isn't a way to get headsets with keys from any vender that spawn on expo or we going to have bad time again.

**Comment by Leander-0** [comment]
> Also dont forget to make sure ghosts and admin ghosts can hear NFSD, we had this issue with the traffic channel when we just added it. Also make sure the solar event can disable the NFSD channel

Added the NFSD channel to the event, original Security one was not even there also for the MobObservers they have this already

**Comment by dvir001** [comment]
> > This is a bit confusing, `s` is now NFSD? This will confuse people coming from other forks with macule memory, best to keep nfsd as the new `g`.
> 
> NFSD basically acts and its the security department here, it replaces the "S" because all players have here muscle memory about that and new players don't have to change muscle memory to "G" when playing NFSD for the first time.
> 
> 'G' is for Station Guard and 'S' still for Security in NFSD.

This is confusing when you know that security exists and its now g.

**Comment by Leander-0** [comment]
> > > This is a bit confusing, `s` is now NFSD? This will confuse people coming from other forks with macule memory, best to keep nfsd as the new `g`.
> > 
> > 
> > NFSD basically acts and its the security department here, it replaces the "S" because all players have here muscle memory about that and new players don't have to change muscle memory to "G" when playing NFSD for the first time.
> > 'G' is for Station Guard and 'S' still for Security in NFSD.
> 
> This is confusing when you know that security exists and its now g.

The security that "matters" and its most played by everyone its the NFSD, the old security channel with its new "g" key will just remain as something for someone else that wants to make any other small guard or events. its more easy to learn for a new player that the frontier security NFSD is S and not for the whole playerbase to learn that G is the new channel to constantly talk on radio and change muscle memory.

**Comment by Leander-0** [comment]
> Also make sure there isn't a way to get headsets with keys from any vender that spawn on expo or we going to have bad time again.

made a whole new encryption key and only added it to the Ptech vendor only available for the sheriff and SR and added a new box for so it can also be bought on the security uplink.

**Comment by dvir001** [comment]
@Leander-0 Ok so after looking into this with Salvantrix the security channel should be renamed to "Guard" or something else to avoid it starting with S to be a bit less confusing the players seeing Security and assuming :s like every server.

**Comment by Leander-0** [comment]
> @Leander-0 Ok so after looking into this with Salvantrix the security channel should be renamed to "Guard" or something else to avoid it starting with S to be a bit less confusing the players seeing Security and assuming :s like every server.

got it, should be solved on latest commit and the encryption key label was added so the PR is ready for review.

**Review by dvir001 — APPROVED** [review]

**Comment by dvir001** [comment]
All seems fine but I didnt get around to test this in game, if someone gets to it and can confirm its all working this is good to go.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
