### PR TITLE
November '24 upstream merge

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

~~It's still October right?  Right?~~ **No.**

Merges against d4da9923ea0a053d1d96f424ca82ea59921313de (space-wizards#32940)

## Why / Balance

It's time.

## How to test

Very carefully.

## Media

oxygen
(Thank you, Stagnation.)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Frezon price reduced to 0.4, close to upstream values, allows for marginal profits vs. tritium.
- tweak: AME jars removed from cargo, livestock cubes moved to ChefVend.
- remove: Reverted Erhard's material reclaimer changes, it no longer functions as a lathe.

### CODE REVIEW

**Comment by whatston3** [comment]
Merged in current head of upstream stable branch (895648aa2c753181c261a6bed8461730f4248ec8).

**Comment by dvir001** [comment]
Going to finish testing this and get it merged when done.

**Review by dvir001 — APPROVED** [review]
Upstream changes and notes:
Going to miss WaddleAnimationSystem.cs but should have it removed for all its issues.
Gas changes can pass for now, if anyone want to update them just revert the upstream PR then edit numbers, we should wait for new system before fucking with it.
Might need to edit the new vote kick system cvars, disabled for now.
Gas mask is cancer again but so be it, admin issue no more "unknown" on radio.
Funny VendingMachineMenu.xaml, seems fine ajusted.
SuicideCommandTests.cs might be working without the DeltaV changes now, but honestly not worth fucking with.
AutoInternalsTests.cs might be working now, we should try to fix it later.
AME Noise is ok (Not much to say about it, might be hard to tell when its overloaded)
TechAnomaly ok on the code now
PriceGun code was remade, need to match contra one probably
Nuked SubdermalBionicSyrinxImplantSystem.cs + SyrinxVoiceMaskComponent.cs, DeltaV has new code but we wont need it.
Syringe gun should be added with the DeltaV pr later + the nerf one.
We should probably add a one hand diffib tech based on the "DefibrillatorCompact" one "This should be a research item at some point"
Add spectrallocator to loadout since its funny
BiomeSystem is hidden for ghosts, they see void on planets, good for CPU, admins wont have this issue
CameraBug was added, can add a version for STC

Sprites:
Half of the files here are sprites
hydroponics.rsi door a bit of an odd one but fine.
flaregun_security.rsi is a sin.

Added:
Moved the last animals off cargo to new hydrated box as part of the cargo cleanup
Removed ame jars out of cargo catalog, they are in vending
Added hidden fuel to the fuel vender (same logic https://github.com/space-wizards/space-station-14/pull/17503).

Need to fix:
Probably add the new loadout items to our loadout, towels, flowers etc.
There is now a "BodyEmotes" system, can add harpy wing flapping, or goblins goblin mod.
(I had a list here of bugs but whatstone fixed it all, dam you whatstone)

**Comment by whatston3** [comment]
Minor Frontier changes:

Cryo sign:
image

Atmos hall light moved off of a window:
image

Unlocked maints, firelock, floor decals:
image

**Comment by whatston3** [comment]
Merged in the mail fixes from Milon.  Looks good.  Under marginal tests, this upstream merge seems fine.

**Comment by dvir001** [comment]
Here we go.

**Comment by whatston3** [comment]
Personal TODO list:
- Need to apply the client/server/shared price gun to the medic, contraband price gun
- RadioSystem: use TransformSpeakerNameEvent instead of RadioTransformMessageEvent if possible.
- Need to add a whitelisted requirement to votekick
- Rerun the GitHub credits script
- Add an unclonable description to the health analyzer GUI
- should add a whitelist requirement for votekick voters, not just initiators.
- gestio should be moved to use the new burst fire stuff
- borg icons for paramedic and advanced engineering borg action

**Comment by whatston3** [comment]
Almost forgot:
- Remove Herobrine

**Pull request merged**
