### PR TITLE
New ship: Eden

### PR DESCRIPTION
**Pull request by drteaspoon420**
## About the PR

Eden ship is designed to be botanist dream.
- Large hydroponics area conjoined with piloting.
- Small chemist and atmos chamber for the more advanced botanists.
- AME to allow botanist to stay on the job and not worry about losing power.
- Green tinted uranium glass windows because colour theming.
- Double the engines, double the reliablility.

Not sure about the price, maybe too much, maybe too little.

## Why / Balance

Botanists need their heaven. This is it.

## Media

eden_ship

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: DrTeaSpoon
- add: New shuttle: Eden, Botanist dream boat.

### CODE REVIEW

**Comment by Everturning** [comment]
I noticed that the hydroponics trays are moveable. This would likely lead to people buying the ship, taking the trays, then selling the ship. Instead, place the unmovable variant.

**Comment by Helicaste** [comment]
Hydroponics trays are fairly easy to make, and evaluated as part of the ship's cost. Shipbreaking tactics are part of the game as long as specialized ships exist. 

I'm far more concerned about the chem dispenser, that should be at most a chemvend.

Uranium glass is also quite silly, but fitting.

**Comment by drteaspoon420** [comment]
Can someone explain what this chem dispenser hate is? It's fairly low level research, abundant in salvage missions. There is much more higher tier items in a lot of ships. Only real argument against it I can see is adding a cost of doing business to medical ships.
I absolutely dispise the vending machine aproach because they have such a horribly long delay, feels like shit to use.

**Comment by Cheackraze** [comment]
Im not really a fan of this design.  For one, like the others have pointed out, it needs immovable hydro trays, it needs the chem dispenser removed, and it needs a lot more effort put into an identity of the ship.  Uranium windows are also a no-go since they are the strongest glass in the game for one as well. Also, having giant sections of window like that is not great, and especially with the big 1 tile zigzag shape.

**Comment by MagnusCrowe** [comment]
This has been inactive for a while so I am going to close it for now.  Please feel free to reopen if you still want to work on it.

**Pull request closed without merging**
