### PR TITLE
AuroraX (New Shuttle)

### PR DESCRIPTION
**Pull request by SergeantEcho**
## About the PR

I wanted to create a shuttle that would be your "personal small station" in the likeness of the ship "Metastable", which unfortunately was abandoned and cut 

## Why / Balance

This is a medium-class ship that was inspired by the "Metastable", I like big ships, so I created it
I balanced the departments as best I could so that the player could progress them himself

## How to test

Run it on a local server and just buy it, lol

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

 
:cl: sergeantecho
- add: Medium-class ship AuroraX in scrap shipyard

### CODE REVIEW

**Comment by dvir001** [comment]
Few notes:

Ship freeze.
read the ship mapping requirements again please as this is breaking many items of the list.
This is not labeled as scrap when its clear this was the aim.
Missing guidebook entry.

**Comment by SergeantEcho** [comment]
> Few notes:
> 
> Ship freeze. read the ship mapping requirements again please as this is breaking many items of the list. This is not labeled as scrap when its clear this was the aim. Missing guidebook entry.

Okay, I'll fix it

**Comment by SergeantEcho** [comment]
@dvir001 @ErhardSteinhauer 
I would like to upload my shuttle's changes, is my pull frozen?

**Comment by ErhardSteinhauer** [comment]
> @dvir001 @ErhardSteinhauer I would like to upload my shuttle's changes, is my pull frozen?

Freeze means that your shuttle wont be reviewed until the freeze ends.

**Comment by SergeantEcho** [comment]
> So nothing stops you from continuing your work on it

Understood, thanks

**Comment by SergeantEcho** [comment]
Ouch...

**Pull request closed without merging**
