### PR TITLE
suit storage sprites for previous PR

### PR DESCRIPTION
**Pull request by terezi4real**
## About the PR

Alas! through a horrid event known as me not communicating my plans, my PR was merged before i had made the requested sprites. here are some of them, the ones i didnt have to put much effort into making, the rest will come,,, one day!

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by terezi4real** [comment]
what the fuck i hate RSIs so much ok im playing a round and will fix this later

**Comment by potato1234x** [comment]
why not do this on upstream too

**Comment by terezi4real** [comment]
1: this is kinda OP for upstream, but more necessary on frontier.
2: upstweam hates me im banned from the discord for being too silly

**Comment by terezi4real** [comment]
yeah alright 1 hour is my fuck this point. checkraze keep or revert or keep the changes the previous PR made but im no longer dealing with this RSIedit tool that does not edit or interact with RSIs in any meaningful way without a goat sacrifice and prayer. the tool didnt work for doing anything so i edited the meta.json just in a text editor, this clearly didnt work, if someone else knows how to fix this easy go for it. but i gotta stop lulw

**Pull request closed without merging**
