### PR TITLE
Brand New Announcer for New Frontier! (Attempt #2)

### PR DESCRIPTION
**Pull request by Wolfking6116**
## About the PR

This is a second-attempt PR (the first being #1136 ) after updating my repository to continue work on this addition. It is mostly a carbon copy so I will quote most of the previous PR and highlight any changes.

> This PR adds an entirely new announcer to Frontier with re-recorded lines of all the stock announcement audio files, several new recordings for many more vanilla Station Events, and recorded announcements for every currently existing event crafted specifically for New Frontier.
>
>This also comes with renaming "Shuttle called" to "Shift's End" in the game announcements, with accompanying audio recordings to match such a change.

The original work-in-progress sound files were left in this PR alongside the newest, finalized versions.
These were left in to give an option to swap the newest files out for the older versions by simply renaming the folders, as well as a sort of an example to anyone else who may wish to record their own version for Frontier to expand the Announcer pool.
If there are causes for concern about bloat, the folder size for the outdated versions is a total of 4.23 mb.

## Why / Balance

>Several people have been brought this up a couple times over the past few months as something that would be nice for the server. Given the popularity of Frontier and all of its wonderful growth and development it definitely feels like it deserves its own announcements!

~~I have not yet tested this in full, this PR in its current state exists for feedback that it is looking okay and to be certain that this is in fact a desired change before too much more effort is put into it only to be shot down.~~
>
>I've gone through and tested all of the events that these sound files are part of to the best of my abilities. The only issues I have encountered so far is that the 'Gas Leak' event seems to end abruptly after starting when tested on my local machine, so the endAudio overlaps the startAudio. I don't have the knowledge of a work around so I commented it out.
>
>For all of the 'Bluespace' events that are specific to Frontier there appears to be something baked into the "BluespaceErrorRule" that causes a global alert that plays the announcement "do-**do**-do!" noise. This overlaps with the 'startAudio' for each of them that may make some of them a bit harder to hear.
>
>Some sound files are quieter than the others. I'll be posting a thread in the Ideas section of the discord for feedback to see which ones need to have their volume increased. I attempted to do so via .yml with params: volume: 4 as a reverse to the one seen on line 232 of the basegame events.yml - but doing so did not seem to have any noticeable effect.
>
>I can't seem to get the original shuttle_dock.ogg to trigger, thus I cannot get the file replacing it - andy1_shift_end.ogg - to trigger to test that it is working correctly. The path for it replaces the original shuttle_dock.ogg so it should still trigger under normal server conditions even if I cannot do so locally.

I'll need to retest everything since many of the file locations were altered, as well as some noticeable changes on how the Bluespace events are handled now. But I wanted to get this PR set up ahead of time to put it on the list of things to be reviewed.

Some of the events in the NF events.yml file weren't standardized in some of their variables, likely left over from whoever would fiddle with them upstream. I standardized a few of them in the general file, if someone notices any issues with it I can correct it. 
I also re-included the RandomSentience event that was removed by upstream, but commented it out in case Frontier wishes to keep it gone. I did this due to Andy having recorded a specialty dialogue line for its event - but if there is no interest in this it can be removed.

I realized it isn't stated anywhere in the quoted sections, but more than half of the sound files included are brand new sound files that are specific and unique to Frontier - several of them involving the Bluespace events. If there are any additional new or specific events or dialogues that are of interest I can speak with Andy about getting them recorded.

Additionally, PocketSizedAndy has been toying around with the coding to implement a way for the server to choose from a selection of announcers randomly at the round start to allow some variance. If anyone is interested in helping him understand that I encourage them to reach out to him in the discord thread.

Oh. Also included a silly sound reel Andy recorded that a different mod/admin had expressed interest in including in the RoundEnd sound pool, but may never have made its way into it. I believe it's listed in that discord channel and if not I can submit it there if desired.

## How to test

If Andy or I don't respond quickly to commentary here please do not hesitate to reach out to use by pinging us on Discord. I'll likely respond quicker than he does, but we both are interested in seeing this added to the community!

## Media

>I'm not certain how easy it is to listen to the audio files via looking at them in this PR. If desired I'll see about getting together a video of all the clips together for ease of access.
>
>To solve an easy method of listening to all the audio files I've set up a post in the discord.
https://discord.com/channels/1123826877245694004/1221648600082157648
>If a different method is preferred, let me know!

The most recent zip file contains the audio that is set to be used for the announcements, found specifically here:
https://discord.com/channels/1123826877245694004/1221648600082157648/1266542077542531102

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: A new Broadcast signal has reached Frontier's Subspace Frequencies, providing clearer and more concise updates on local events!

### CODE REVIEW

**Comment by Cheackraze** [comment]
i was really hyped for this, and I felt we were nearly exactly over the target when we left off. I'll give these another listen this week and, if its still at all possible, I may write 2-4 more lines as a request for some future events I have coming up in the near-term

**Comment by Wolfking6116** [comment]
> i was really hyped for this, and I felt we were nearly exactly over the target when we left off. I'll give these another listen this week and, if its still at all possible, I may write 2-4 more lines as a request for some future events I have coming up in the near-term

I think he's more than happy to record more lines for you as you desire, as when I brought it up to him his response was and I quote:
"alright!!! lets fucking go!!"
We're at your service as you please

**Comment by arimah** [comment]
Due to several months of inactivity and no sign of anyone taking charge to get this merged, I will be closing this PR primarily so a seemingly dead PR doesn't appear as active. This does not mean the changes will never be incorporated. If anyone wants to fix up any outstanding issues and bring this to the finish line, comment to have this re-opened.

**Comment by Wolfking6116** [comment]
> Due to several months of inactivity and no sign of anyone taking charge to get this merged, I will be closing this PR primarily so a seemingly dead PR doesn't appear as active. This does not mean the changes will never be incorporated. If anyone wants to fix up any outstanding issues and bring this to the finish line, comment to have this re-opened.

It has been inactive because we have been awaiting a review for this for some time now, but have yet to hear anything back. The merge conflicts are something I can easily fix, but there's not much reason to fix it until we know what needs to be added or changed. 😅

**Pull request closed without merging**
