### PR TITLE
04/08/2024 - NFSD Completion.

### PR DESCRIPTION
**Pull request by Salvantrix**
Fixes:
Brigmedic Duffle.

Added:
Whistle
NFSD and Sheriff gas masks
Eyepatch HUD
On-spawn Brigmedic HUD (Medical and Security)
Bedsheets (NFSD, Brigmedic and Sheriff) {Wearable] NFSDLite
NFSD Survival box containing the same items aside from the new gas mask Circuit Boards for NFSD Fabricator. (Updated Sheriff spawn loadout to include)

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by VividPups** [comment]
Is this including the Space lockers also?

**Comment by Salvantrix** [comment]
> Is this including the Space lockers also?

They were added in the previous pr.

**Comment by Salvantrix** [comment]
boots

**Comment by dvir001** [comment]
Also did you make sure tiny nfsd gyro also there? its just a 0.8 scale gyro I think.

**Comment by dvir001** [comment]
Other then the big issue of
```
Suffix and descriptions need ``NFSD``
Names ``nfsd``
Proto ``Nfsd``
```

This is fine

**Review by dvir001 — APPROVED** [review]
I cannot find issues with this PR

**Pull request merged**
