### PR TITLE
Bahama Mama's: (New) Alternative POI to Tinnia's Rest

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Adds a new point of interest as an alternative shift spawn option to Tinnia's Rest: Bahama Mama's, a tropical/beach themed rest stop.

This is designed to be an alternative to Tinnia's. I've set the yml files so that either POIs have a 50/50 chance of spawning. That means at roundstart you have a 50% chance of this appearing and a 50% chance of Tinnia's.

Absolutely my biggest and most complex mapping project to date. 

## Why / Balance
A desire was expressed for more POI diversity, so this is the contribution I've come up with over the last few weeks.
I was inspired by a Hawaiian themed restaurant/bar in my town which happens to be my favourite watering hole. Very subdued lighting, surf boards everywhere, plants all over the place. It's very chill, feels like you're in a permanent sunset on a nice, warm sandy beach. So I thought to myself...why not make a beach bar in Frontier? And why not make it pineapple shaped for even more of a tropical feel?

Coming in at a slightly larger size than Tinnia's, this POI fills the same role: a bar/kitchen and general rest stop or chillout space for frontierspeople to come hang out. Functionally it is no different. Both the POI yaml for this and Tinnia's now have the 'RestStop' custom spawn group with a 50% chance of each to appear.

Uranium windows were chosen for the exterior windows largely for strength, but also to add to the 'floral' feel of the place. 

I've tested docking with all sizes of ship, in particular all the large ships. While it has one fewer dock compared to Tinnia's, there are still plenty of spaces. 

The kitchen and bar are equipped to the same level as Tinnia's, and there's a little bit of maints loot, but no contraband. I neither wanted to add or detract from the amount of stuff available at either. Regardless, the focus of this place is to hang out at a beach with your friends and drink far too many cocktails, not loot. 

I've designed the hydroponics bay to be able to efficiently serve both the bar and kitchen, with the outer lobby providing easy access to both. 

Some vending machines were also added for fun and to give some flavour.

## How to test
Checkout the branch, load the grid or let it appear naturally on roundstart.

## Media
2024-09-02 12_03_49-Window
Overview.
2024-09-02 12_04_32-Window
Mass scanner view.

2024-09-02 11_57_52-Window
Docking arms and solars. Initialised.

2024-09-02 14_48_41-Window
Upper section. Initiliased and showing subfloor.

2024-09-02 14_48_08-Window
Same but with neutral light.

2024-09-02 12_02_00-Window
Middle section. Uninit.

2024-09-02 11_59_09-Window
Middle section. Init.

2024-09-02 12_02_12-Window
Lower section. Uninit.

2024-09-02 11_59_28-Window
Lower section. Init.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None, I should hope.

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added Bahama Mama's, an alternative POI to Tinnia's Rest.

### CODE REVIEW

**Comment by dvir001** [comment]
No hidden syndicate room?

**Comment by Tych0theSynth** [comment]
> No hidden syndicate room?

What's a syndicate??

**Comment by Houtblokje** [comment]
Tinnia's but it has a BEACH?! I love this! It looks so cool!

**Comment by Ansome101** [comment]
I simply adore the theming of this replacement POI! I've never felt compelled to run Tinnia's as a proper restaurant, but I'd 100% be interested in running this little resort with a crew!

**Comment by Tych0theSynth** [comment]
> I simply adore the theming of this replacement POI! I've never felt compelled to run Tinnia's as a proper restaurant, but I'd 100% be interested in running this little resort with a crew!

I should clarify that this is **not** a replacement for Tinnia's. It will just have a chance to appear instead of Tinnia's - the same way you have a 50% chance of getting Grifty's or the McHobo.

**Comment by Ansome101** [comment]
I referred to it as a "replacement POI" as it has a chance to replace Tinnia's every round as you mentioned, apologies for the confusion. Also, you mentioned that the uranium glass windows were primarily added for strength in the PR description, but I personally cannot remember a time Tinnia's windows have been breached in recent memory. I do agree that they really add to the overall color of the place, I was just curious as to whether this was a genuine concern or not.

**Comment by Tych0theSynth** [comment]
> I referred to it as a "replacement POI" as it has a chance to replace Tinnia's every round as you mentioned, apologies for the confusion. Also, you mentioned that the uranium glass windows were primarily added for strength in the PR description, but I personally cannot remember a time Tinnia's windows have been breached in recent memory. I do agree that they really add to the overall color of the place, I was just curious as to whether this was a genuine concern or not.

No worries! It's good protection in case artifacts explode on a ship that's docked there (a Lyrae could do this), but also is good futureproofing in case meteors become a thing.

**Comment by Tych0theSynth** [comment]
Fax machine proto was causing a fatal on build for some weird reason to do with one of the components. Removed that component for now until it's fiddled with and fixed a bit more. 
Pun Pun has been replaced with Yip Yip with huge thanks to @whatston3 - Yip Yip is now a whitelist only role.
Removed the glass firelocks from over the counters and replaced them with edge firelocks. Much more discrete.
Tiny fans have been replaced with directional fans. 
Added a clothesmate to the dorms so people have a greater array of theme suitable clothing available.

**Comment by whatston3** [comment]
Just took another look at this.  Swapped out a few more posters with dead drop variants now that they're only potential spawns and not guaranteed spawns.  Added a POI prototype to ensure it gets dead drops.  Also swapped out the tiny fans in the freezer for directional fans (currently pointing outward, negate the angle for inward pointing fans - not sure if there's an issue with losing cold air when opening/closing the door repeatedly)

It seems like most of the fire alarms should probably be air alarms instead in case the place gets spaced - fire alarms need manual action, and don't seem to play nice with the non-glass airlocks.

For what it's worth, I think the layout of the hydroponics trays could benefit from changes.  If/when hydro trays collide with players, this layout seems inconvenient.  Maybe placing them along the sides of the walls would be best?  Haven't made any changes on that front, will defer to you.

Still getting reported errors about entity UIDs being zero, and for what it's worth, there seem to be complaints about missing networkconfigurator components on server shutdown.  Still not sure what's actually causing the issues, maybe it's something being linked improperly?

**Comment by Tych0theSynth** [comment]
Thanks for helping out more on this dude. Haven't had a chance to investigate the errors yet, but I'll test with relinking stuff. Best lead I have so far.
The trays felt fine when navigating around the space, but I'll test some more.
Fire alarms were introduced for the same reason Tinnia's has them: so people don't just make the place inhospitable by fucking with air alarms. Magnus was happy with it this way.

**Review by whatston3 — APPROVED** [review]
Pushed a fix for the invalid entity errors - at the moment, DeviceNetworkComponent seems to like storing invalid references to non-existent tools when saving a grid.

Branch seems alright to me, I do think there may be pain points with the hydro tray layout in the future, but this seems good enough.

**Comment by Tych0theSynth** [comment]
Ah, well diagnosed and found. Thanks muchly.
I'll ponder on the trays. Might rework that entire room if the layout is hated.

**Comment by Tych0theSynth** [comment]
Not committing the change yet, but WIP for a new hydro layout. 
image

Also, @whatston3 does the POI as a whole have everything it needs for smuggling? I see it has three poster locations now.

**Comment by whatston3** [comment]
> Not committing the change yet, but WIP for a new hydro layout. image
> 
> Also, @whatston3 does the POI as a whole have everything it needs for smuggling? I see it has three poster locations now.

That looks a lot nicer!  Should be fine, honestly I should probably just put the potential dead drop on the base poster and call it a day.

**Comment by Tych0theSynth** [comment]
2024-09-24 21_13_21-Frontier Station

Reworked hydroponics and added the DisableToolUse component to lots of vendors and machines.

**Comment by Cheackraze** [comment]
its all looking good to me, if it works in game lets merge it

**Comment by dvir001** [comment]
@whatston3 @arimah  If there are no issues just merge

**Comment by whatston3** [comment]
Gave the recent map edits a read through, seems alright.  I'll give the map a quick double check in-game but I think it should be fine.

**Comment by Tych0theSynth** [comment]
> Gave the recent map edits a read through, seems alright. I'll give the map a quick double check in-game but I think it should be fine.

Thanks dude. Could you give the fax one more check just to make sure it works properly?

I've only applied DisableToolUse to things I felt really needed it/were important, so if you find anything I've missed or anything that requires it, go ahead and add (or tell me and I'll do it when home from work in a couple of hours).

**Comment by Tych0theSynth** [comment]
Ah, I should've said I deliberately didn't anchor the smokes in case someone wanted to remove it (smoking is gross), but I guess you can just destroy it if you want to.

**Pull request merged**
