### PR TITLE
Fix up the NSF Templar

### PR DESCRIPTION
**Pull request by chrome-cirrus**
## About the PR
This PR modernizes the Templar substantially, quite similar to the Watchdog. Lots of changes including:
- Directional fans instead of tiny fans
- Two can atmos setup
- NFSD livery decals and airlocks

## Why / Balance
Compliance with tiny fan destruction guidelines, general modernization of one of the older/deadlier ship designs.

## How to test
Spawn one in game, fly around, arrest some perps maybe.

## Media
docked
subfloor
nodevis

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by chrome-cirrus** [comment]
Replaced the generator with some wall APUs per guidance from Dvir01. Moved the wall recharger to a table model in the cockpit so it's not accessible from outside.

**Comment by chrome-cirrus** [comment]
Also added some firelocks to the new Templar, and to the Watchdog.

**Comment by Tych0theSynth** [comment]
For additional neatness, you could move the waste vent under the port reverse thruster and remove that extra lattice. Looks good otherwise. I think the Templar has needed something like this for a while.

**Comment by chrome-cirrus** [comment]
> For additional neatness, you could move the waste vent under the port reverse thruster and remove that extra lattice. Looks good otherwise. I think the Templar has needed something like this for a while.

I've seen that on a few ships. Is that actually a valid placement if one had to rebuild it after damage or something? I kinda hate hiding components that way (as an engi/atmos player who has had a few "where is that goddamn vent?!" moments) but it would make for a cleaner look, it's true...

**Comment by Tych0theSynth** [comment]
> I've seen that on a few ships. Is that actually a valid placement if one had to rebuild it after damage or something? I kinda hate hiding components that way (as an engi/atmos player who has had a few "where is that goddamn vent?!" moments) but it would make for a cleaner look, it's true...

Yup, pretty certain it's valid. You can anchor machines on top of vents and scrubbers without affecting their output, plus if you need an engineer to fix something they will likely be using a t-ray and should be able to fathom it out.

**Comment by chrome-cirrus** [comment]
> > I've seen that on a few ships. Is that actually a valid placement if one had to rebuild it after damage or something? I kinda hate hiding components that way (as an engi/atmos player who has had a few "where is that goddamn vent?!" moments) but it would make for a cleaner look, it's true...
> 
> Yup, pretty certain it's valid. You can anchor machines on top of vents and scrubbers without affecting their output, plus if you need an engineer to fix something they will likely be using a t-ray and should be able to fathom it out.

Nice, tested it out and that's totally a valid placement, so I moved that exhaust vent under the thruster. Thanks for questioning how it was initially! Was bugging me that the extra grid modified the ship's profile on radar, too...

dockedupdate

**Comment by Tych0theSynth** [comment]
Looks good! It's what I always do unless I already have lots of external free lattice for practical reasons. It looks so much tidier.

**Comment by PeccNeck** [comment]
Hmm.
image
Not sure what this guy's doing here. Not present on the Watchdog, either. Also not sure what the consensus is on interior fans like this. Either way, let it be known this straggler exists... for now.

**Comment by chrome-cirrus** [comment]
> Not sure what this guy's doing here. Not present on the Watchdog, either. Also not sure what the consensus is on interior fans like this. Either way, let it be known this straggler exists... for now.

Whoops! That door didn't start as an interior door in the OG Templar design so it had a fan on it. It's gone now.

**Review by dvir001 — APPROVED** [review]
Good to go

**Pull request merged**
