### PR TITLE
Port playing cards from Estacao Pirata

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Ports playing cards and box of cards for everyone to enjoy from this PR https://github.com/rbertoche/space-station-14/pull/104.

## Why / Balance

Fun

## How to test

>choose playing cards loadout
>spawn
>open the box
>buy from the fun vendor

**Changelog**

:cl: Leander
- add: Trinkets loadout now comes with a pack of play cards.
- add: Ported playing cards, now gamble away all your money playing poker and other games!

### CODE REVIEW

**Review by whatston3 — COMMENTED** [review]
Pushed a set of changes onto [whatston3:port-cards-suggestions](https://github.com/Leander-0/frontier-station-14/compare/port-cards...whatston3:frontier-station-14:port-cards-suggestions?expand=1), I think the changes improve interaction consistency.

Left-click on a deck or hand when holding a card, hand, or deck now always draws a card, and alt-click on a deck or hand always pushes the contents of your hand/card/deck onto a stack.  Alt-click on a single card, even when holding a card, deck, or hand, will result in flipping it*.  Picking a card to draw from a hand of two leaves the remaining card on the table, and a deck with two cards left turns into a single card when drawn from.

Did a revision pass over the fluent entries, everything seems good to my eyes.  I would _highly_ request giving that branch a test, it involved more changes than I'd like.

Reverted the access change to StorageSystem.FillStorage (as it was unused),

Nice little feature though, looking forward to seeing it in use.

* I looked into getting this to push the entire deck onto the card, but it was fiddly.

**Comment by Leander-0** [comment]
Really nice, ill give it a try.

**Comment by Leander-0** [comment]
should be good to review

**Comment by Ansome101** [comment]
Are there any plans to update Casey's or Tinnia's to have decks of cards on their gambling tables round-start like the dice bags so they're readily available? Regardless, this PR might finally breath some life into Casey's and be good fun for creating player-driven RP scenarios, really looking forward to it!

**Review by whatston3 — APPROVED** [review]
Fixed a few remaining issues with the one-card hand/deck dropping out of your pockets on use.  One-card hands and decks are still a thing, and one-card hands are drawn properly.

Happy with the state of this.  Approving on my side.

**Comment by Leander-0** [comment]
Did a real dumb over there, sorry.

**Comment by whatston3** [comment]
Mapped three decks of cards.

Added animations for pretty much all card interactions.  Didn't see any server errors when testing with invalid entity references.

As far as I can see, it's good to go.

**Review by whatston3 — APPROVED** [review]

**Comment by whatston3** [comment]
Last set of changes, I swear.

Click to draw and alt+click to push all cards if any card/hand/deck is in your active hand _is always true_, targeting a hand, card, or deck.
Hands of cards can now be flipped and shuffled.  When selecting a card from a flipped hand of cards, the name of the cards are hidden, otherwise the cards say their rank/suit.  Go fish is real.
Inserting cards into hands, or forming hands from multiple cards always flips the cards into the flipped state of the target hand/card that is accepting the cards.

Small quality of life changes, but good ones.  One card hands/decks are still weird, but it's better than picking up two cards occasionally or having cards fall out of your pocket/backpack when swapping cards between hands.

image

**Comment by whatston3** [comment]
Still wasn't happy with the oddities in the deck, I've tried a new tack: activation verbs.

https://github.com/Leander-0/frontier-station-14/compare/port-cards...whatston3:frontier-station-14:port-cards-activate-verb?expand=1

With these changes, clicking a deck without anything in hand now picks it up, like any other item.  Pressing E on any card, hand, or deck in the world will now draw a single card from it (a bit odd for an activation verb, but better than oddball interaction via Z/LMB).  The verb to draw should show up in right-click menus, so that's normal, and the pick up verb behaves for all card sets in its correct order, same with alternate verbs.

Might rearrange shuffle and split functions for decks, and will need to give this another look with fresher eyes.

**Review by dvir001 — APPROVED** [review]
Can use some DoAfter for mixing etc,
But still working fine as is

**Comment by whatston3** [comment]
Cards ho.

**Pull request merged**
