### PR TITLE
Eggnog

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds eggnog as a craftable drink.

## Why / Balance

Woe, yuletide upon ye.

## How to test

1. Check the recipe in the guidebook.
2. Make some eggnog.

## Media

Christmas in medbay again.
image

Guidebook bar entry.
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Eggnog is now craftable by chefs and bartenders.

### CODE REVIEW

**Comment by whatston3** [comment]
Sprites probably need work.

**Review by dvir001 — APPROVED** [review]
Can probably also add this as a berrel.

**Comment by dvir001** [comment]
https://github.com/space-wizards/space-station-14/pull/34065

**Comment by whatston3** [comment]
> [space-wizards/space-station-14#34065](https://github.com/space-wizards/space-station-14/pull/34065)

milk?
half rum?
no sugar?
eh

**Pull request merged**
