### PR TITLE
Selective dropper for Service Roles

### PR DESCRIPTION
**Pull request by blueDev2**
## About the PR

Added a new entity, Service Selective Dropper
Act identically to a dropper except it a player may right click it to have the dropper only draw a certain reagent
The Service Selective Dropper only works on can discriminate on reagents that are in the Botanical, Foods, or Drinks Groups.

In terms of code, the entity depends on a new field on the InjectorComponent, ReagentWhitelist. If the ReagentWhitelist is null, all reagents are allowed to be drawn. Otherwise, only reagents on the ReagentWhitelist may be drawn.

A new Component, ReagentWhitelistChangeComponent, allows a UI to change the ReagentWhitelist if the new reagent is from a group in the AllowedReagentGroup field. Changint the whitelist using this component, the whitelist can have, at most, one reagent.

## Why / Balance

The main purpose of this entity is to allow chefs to remove certain contaminants, like nutriment in flour, from baking solutions.
For discussion, please look at the discord ideas thread on "Separate reagents with dropper"

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/89804215/da3109a2-e2d7-4319-8853-a17c948dc5db

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: blueDev2
- add: Added the Service Selective Dropper to help chefs make purer food

### CODE REVIEW

**Comment by blueDev2** [comment]
This PR works as-is though some improvements would be nice:
- A new sprite for the new dropper
- A new icon for the new action, Set Reagent Filter

I just code, I'm not good at art

**Comment by blueDev2** [comment]
Additionally, there is no way to create it at the moment. 
I personally think the best way to add it is via adding it to the Plasteel Chef vending machines, but I would like a maintainer to approve or suggest an alternative before I do so.

**Comment by dvir001** [comment]
Looking into it I don't think this will get abused with it only supporting basic regents groups.
Also its so simple to get chem machines by just buying a medical ship.

Plasteel Chef vending is fine but you should also be able to print it in service tech fab since some ship might get it soon to replace the Plasteel Chef.

**Comment by blueDev2** [comment]
Only thing I would personally like before this is merged is something for the filter verb icon. I tried to make one but it kept doing some weird stuff when I tried to use inkscape.

**Comment by blueDev2** [comment]
Also, while this is not the point of the PR, the components added here can be customized to make a general purpose selective dropper, if that would be useful.

**Comment by blueDev2** [comment]
Also Also, should the vendors for bartender and botanist also have this entity? I personally can't specifically think of a use case of the bartender, but the botanist would probably have some use with it for some growing purpose.

**Comment by blueDev2** [comment]
Closed to be fixed after disastrous rebase

**Pull request closed without merging**
