### PR TITLE
Better discord notifications

### PR DESCRIPTION
**Pull request by OCOtheOmega**
## About the PR
Notifications about the start of a round have been added, this is useful as the rounds in the frontier are very long, also notifications from the galactic bank have been made in the form of embed messages.

Also if i start talk about discord, here mine - Gados#1923

**Media**
изображение
Better use separeted channels for round notifications and bank leaderboard.
Reminder: NEVER PUT WEBHOOK URL IN GIT REPOSITORY!

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Round notification!
- tweak: Make bank notifications embed!

### CODE REVIEW

**Comment by Kesiath** [comment]
Can you add a ping for the New Round Notification role? 1135611365332111420 is the role ID, I'll be adding it to the selectable roles soon

**Comment by Cheackraze** [comment]
yea our existing webhooks i have in our server config.toml files to keep them private. the repo stays clean of any of that stuff.

**Review by Cheackraze — APPROVED** [review]
approved but going to wait to merge until I can replace my server config files and get our discord webhooks set up appropriately, likely later this evening or tomorrow

**Comment by Cheackraze** [comment]
this is still all good but as of now I plan on doing server maintenance this sunday/monday to merge this and a few other prep things like the discord bots and channels being reworked a touch, thanks for your patience and bare with us

**Pull request merged**
