### PR TITLE
Wearable Exoskeletons [EARLY DRAFT]

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
This PR is more invitation to tinker with it's contents rather than actual PR. But added entities are functional even in current state.

Right now there are 5 variants (complete with textures), each takes an outer suit clothing layer and sports a toggleable battery-powered flashlight (by default starts with high capacity power cell in battery slot) plus pocket with the volume of 30:
- greytider: +0% movement speed, 5% resist to brute and slash damage, normal flashlight;
- engi: same as greytider, different color scheme;
- medical: +0% movement speed, 5% resist to brute and slash damage, slightly brighter flashlight;
- salvage: +0% movement speed, 5% resist to brute and slash damage, brighter flashlight;
- sec: +0% movement speed, 10% resist to brute, slash and piercing, integrated Seclite and SecHUD.

P.S.: I'll continue adding textures for missing departmental exoskeletons and upon request. 

## Why / Balance
Seemed like a cool idea.

## Technical details
It sorta works as is right now, but there are some problems. For example, I tried to add SFX for walking, but it's not working.

## Media
models
Fig. 1 - Overview of available at the moment models.

exoskeleton_engi_off exoskeleton_engi_on
Fig. 2 - Engineer's Exoskeleton with lights off (left) and lights on (right).

exoskeleton_greytider_off exoskeleton_greytider_on
Fig. 3 - Greytider's Exoskeleton with lights off (left) and lights on (right).

exoskeleton_medical_off exoskeleton_medical_on
Fig. 4 - Doctor's Exoskeleton with lights off (left) and lights on (right).

exoskeleton_salvage_off exoskeleton_salvage_on
Fig. 5 - Salvage Specialist's Exoskeleton with lights off (left) and lights on (right).

exoskeleton_sec_off exoskeleton_sec_on
Fig. 6 - SecOff's Exoskeleton with lights off (left) and lights on (right).

flashlight-comparison-01 flashlight-comparison-02
flashlight-comparison-03 flashlight-comparison-04
Fig. 7 - Comparison of exoskeleton flashlights.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame,

**Changelog**
:cl: erhardsteinhauer
- add: Added 5 wearable exoskeletons: greytider's, engineer's, doctor's, salvage specialist's and security's. Takes the Outer Suit clothing layer.

### CODE REVIEW

**Comment by dvir001** [comment]
This is just hard suits with insane buffs
Speed?
Armor?
Storage?
All at the same time?

Why even use anything else..

**Comment by FoxxoTrystan** [comment]
I like the idea of Exoskeletons, but currently they are not used correctly in my opinion, those stats are overpowred.

My idea for an exoskeleton would be mostly utility and NOT armor:
Exoskeleton adds more weight making dragging or carring things extremly easly while others cannot shove you or drag you easly.
Or even add a stamina resistance, il allow a small 5% Resistance to blunt, but the speed is a very nono.

And also its should be better if linked up with a battery system if you wish to add like 5% Speed Hardcap max and its features.
Currently its just overpowred mess and il say no honestly for it.

**Comment by AjexRose** [comment]
Exosuits could be cool, but the current static stats aren't. 

I feel like a good way to use them could be similar to borgs, in which they start out as just a useless hunk of metal, that which with research, material, and time, you could mod your suit to fit more needs, but in exchange it consumes power faster from capacitors (or some other form of charging)
Examples:
20% Brute Damage Resistance module which increases power draw by 25%
Space Protection Module which increases power draw by 15%
Enhanced Carry Speed Module which increase power draw by 15%

**Comment by ErhardSteinhauer** [comment]
> This is just hard suits with insane buffs Speed? Armor? Storage? All at the same time?

It takes the hardsuit slot, but it doesn't provide high/low pressure protection.

I'd love to tie the speed bonus, or lack of speed penalty rather, to the battery charge (no juice in batteries = 20%-30% speed penalty), but I don't know how. There are toggleable speed boots upstream, I probably can grab .yml components from there, but I'm guessing that there is new .cs code accompanying it, without which new .yml components would be useless, and that's outside the realm of my abilities at the moment.

From the common sense perspective, it makes sense to me that metal rods strapped along your limbs and spine provide a modest amount of protection. 10% felt okay-ish (get sent into crit in 12 crowbar hits instead of 10), but I have no issue with lowering it to 5% or completely removing the armor component. Besides, the item takes the outer clothing slot, so you won't be able to layer more armor on top of it (well, maybe atmos/salvage gas masks, but that's it).

Suit storage space is there more as a placeholder for now because I don't have the skills to make a more meaningful representation of the benefits industrial exoskeleton can provide. I like FoxxoTrystan's idea of adding more weight, but I am personally unable to make it happen. Or Quigley's idea of making it "Ripley Lite": give it mech claw with 1 slot for carrying stuff. But again, skill issue on my end.

> Currently its just overpowred mess

It is, yeah. Currently.

**Comment by ErhardSteinhauer** [comment]
Tweaked exoskeleton stats:
- lowered armor values to 5% for civilian versions, and to 10% for security version;
- shrinked storage space from 30 to 20;
- removed speed buff;
- boosted medical and salvage integrated flashlights.

Added:
- wall mounted signs and a poster regarding safety around working exoskeleton operator.
exoskeletons_storage exoskeletons_safety exoskeletons_warning_big exoskeletons_warning_medium exoskeletons_warning_medium_alt poster_exoskeleton_safety

**Comment by ErhardSteinhauer** [comment]
Closing for the time being: going to rework .ymls (and fix my approach to the file management - its a mess rn and causes too much issues with merging).

**Pull request closed without merging**
