### PR TITLE
Randomized ATV sprite color, storage options for ATV/Bike, Hoverbike

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
- Split ATV sprite into hull and engine. Hull has randomized color on spawn.
- Adds slot for a storage container (backpack, satchel, duffel, anything wieldable with storage component really) to ATV.
- Adds satchel sized and shaped inventory grid to Skeleton Bike.
- Adds void-capable hoverbike. Functions just like ATV, but can fly in space, buyable from cargo for 15k.
- Additionally made variants for NFSD and mail carrier. Both variants instead of slot for duffel bag have satchel sized and shaped inventory grid. NFSD hoverbike has slot for stunbaton along with unique lights and honk sound, Mail Carrier has slot for RPDS.

## Why / Balance
To facilitate planet looting by biker gangs.

## Media (videos a a bit dated, screenshots are most recent)

https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/25a51301-6187-4a83-88b1-86e52bea3623

https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/71ee3842-2584-4da4-84a4-25149791c1d6

https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/f69ed932-bddc-40fd-8e3c-c9f50b813b1d

- [X] Added media showcase

## Notes
Vehicles with storage options are frontier specific entities, changes made to base game files: limited to 4 lines in order to substitute base game ATV with Frontier ATV

**Changelog**
:cl: erhardsteinhauer
- tweak: Added storage compartment to Skeleton Bike.
- tweak: It is possible to strap a duffel bag to ATV now.
- tweak: ATV hull color is now randomized.
- add: Added void-capable hoverbike. Buy one at cargo today!
- add: Added void-capable hoverbikes for NFSD and Mail Carrier.

### CODE REVIEW

**Comment by dvir001** [comment]
Have to ask, is the storage fucking with the click to ride, or the other way around?

**Comment by ErhardSteinhauer** [comment]
> Have to ask, is the storage fucking with the click to ride, or the other way around?
Can you open the storage only from the verb menu?

Click to ride has higher priority than opening storage, so if you want to open storage it's either through context menu or through `activate item in world` button on your keyboard (I have it mapped to `F` but I'm not sure if it's default key bind).

**Comment by ErhardSteinhauer** [comment]
> You could revert buckleable.yml, make a new file in _NF folder containing the new version, and mark the old one `abstract: true` and update all references to `VehicleATV` and give the new atv a updated name. This will make the old ATV not appear in spawn menu
> 
> Other than that i love the changes this makes ATV aspecially valuable to transport stuff

I thought about that. Right now this PR changes 2 existing files. If I'm to create Frontier specific ATV variant, I'm guessing I'll have to change more than 2 base game files to replace all the references to original so the new version would appear in the world instead. And I don't know which option is less problematic from maintainer point of view.

**Comment by ErhardSteinhauer** [comment]
> more than 2 base game files to replace all the references to original

Although I'm guessing it's just spawner and cargo crate fill.

**Comment by ErhardSteinhauer** [comment]
Alright, I'll make the change then

**Comment by ErhardSteinhauer** [comment]
> You could revert buckleable.yml, make a new file in _NF folder containing the new version, and mark the old one `abstract: true` and update all references to `VehicleATV` and give the new atv a updated name. This will make the old ATV not appear in spawn menu
> 
> Other than that i love the changes this makes ATV aspecially valuable to transport stuff

Made those changes. Also added enduro motorcycle for the hell of it. Functions just like new ATV, stat-wise in between ATV and skeleton bike.

**Comment by ErhardSteinhauer** [comment]
I removed newly added enduro motorbike in favor of adding something more unique later.

**Comment by ErhardSteinhauer** [comment]
Added void-capable hoverbike.

**Comment by ErhardSteinhauer** [comment]
I believe this PR is ready for review.

**Comment by ErhardSteinhauer** [comment]
Huh, upstream resprited ATVs. Updated this PR accordingly.

**Comment by Cheackraze** [comment]
sure these look great, thanks for the hard work on these

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
