### PR TITLE
PDA Programs in Loadout

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
WIP

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Medical PDAs no longer start with a health analyzer, all PDAs now start with an inherent GPS app.
- add: Loadouts now have a tab for selecting PDA cartridges (e.g. a health analyzer app).
- tweak: PDA cartridges are now consumed on install, and install on insert if not already present on the device.

### CODE REVIEW

**Review by ErhardSteinhauer — APPROVED** [review]
Works in game. Wouldn't mind seeing an option to buy MedTek cartridge from medical vendomat(s).

But this
image

This is a deal breaker. Denied.

**Comment by dvir001** [comment]
I still need to add changelog and actual explanation.

**Review by whatston3 — COMMENTED** [review]
Looks alright at first glance, will test and do a deeper inspection.

**Review by whatston3 — APPROVED** [review]
Gave the appraisal app a name to match the others and added a sprite I had lying around
image

Should've fixed the errors, think this is more or less good to go.

**Pull request merged**
