### PR TITLE
Crawdad and Clawbreaker

### PR DESCRIPTION
**Pull request by RealIHaveANameOfficial**
## About the PR

Adds the Crawdad and Clawbreaker. 
image
The Crawdad is a modest, fragile, salvaging vessel, with the intent to be for captains to use it as an alternative to the construct with a larger atmosable area. The ship is rather barebones, with only mining equipment, an ore processor, solars, and a few building materials. An industrious captain may find themselves in a cozier place than expected, if they don't find it too cramped. Priced at 21,000 MRSP.

image
The Clawbreaker is a robust, aggressive boarding platform. With grappling hooks, weapons, and an unorthodox power solution, what was originally a one of a kind modification is now available to anyone with the right connections. Rumors of illegal Cybersun bananium mines are hugely overblown. Priced at 54,000 MSRP.

## Why / Balance

I want to pilot these ships on the frontier personally myself. I'm still open to talks about balance for the weaponry included on the Clawbreaker.
## Technical details

Adds both ships to be purchaseable, the Crab from the Frontier and the Clawbreaker from the pirate cove.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

hopefully not

**Changelog**

:cl:
-Adds the Crawdad, a small, fragile, solar-powered salvaging ship.
-Adds the Clawbreaker, a pirate variant of the Crab that's equally fragile, but surprisingly well equipped, to the Pirate Cove.

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
I again see a lot of issues mostly with the "illegal one"

- Free power? hell nha! the only ship that has free power are extremly tiny shuttles, The bananium will mostly be a hard no, depands on check.
- The Clawbreaker feel extremly useless, its just a copy and paste of the Crab, peoples will just buy this ship for free guns and then sell it.
- Your changlog is tottaly incorrect, the changlog is what peoples will see in-game, and its like this ship was already in-game, i suggest you should change your changlog.
- Grills are still missing from the first ship.
- SMES is not correctly linked in the first ship and i think the second.

Now my overall opinion:
This ship feel, slightly like a joke and mostly the illegal one, peoples are just gona buy it for the loot or the power source and then sell it and for a pirate ship its is extremly weak and easy to destroy the engines or just fire lasers weapon to the inside, this ship as a "pirate" version feels like a joke, the legal one tho "Crab" i think that possible indeed.

**Comment by Carmell0** [comment]
If I’m being honest Im not sure that the battery connector things are necessary. From what I can tell SMES work without them

**Comment by FoxxoTrystan** [comment]
> The crab's SMES is charge only, so it won't be powering the ship if the solars become misaligned or blocked.
> 
> The bananium gen is not free power, and Mas as much maintenance as other generators, except for the fuel cost.
> 
> Joke ship or not, it's a compact shuttle that seems fairly maneuverable and very easy to modify.

Agree on the part when looking at the bananium (still got it in the mind before the collectors update)

Tho thinking of it its still need some slight changes for the SMES, fixes, and i still hold my point on the "buy gear and sell later"
but overall thats my opinion, tho il change my changes to fir it more.

**Comment by RealIHaveANameOfficial** [comment]
The "buy for weapons" concern is valid. However, the price is already highly, *highly* marked up compared to its appraisegrid sell value. If one were to buy this ship simply for the gear on it, they would be losing a hefty amount of cash. I'm about to fix the SMES on the crab and commit it, and I'm still open to changing up the weapons on offer for the clawbreaker if it really comes to it. I still don't want grilles underneath the crab glass, though.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
crab:
- Missing Gyroscope.
- Grid Appraised to 36480, your current price is 21000; i recomend fixing a price between 3700-4000.
- Minor but there some random unconnected HV Cables laying round.

clawbreaker:
- Replace Syndicate Fax Machine by a Ship Fax Machine.
- Minor but im not sure about Krammer as i honestly would be prefer to be a reward.

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Cheackraze — CHANGES_REQUESTED** [review]
My only critique is that they are all glass windowed. You should have at least some reinforced/shuttle/plastititanium walls, especially where you have wall devices like APC, substations, and signal switches.

**Comment by Cheackraze** [comment]
also kammerers are a bit strong, the concerns of buying them for the weapons is definitely valid, might want to downgrade them to double barrels

**Comment by RealIHaveANameOfficial** [comment]
On both notes:
I added some plastanium walls on essential/symmetrical tiles. It looks....okay, I guess. I'm not really one for aesthetics but I do miss the all-glass exterior.
image

Clawbreaker Krammerers: I still maintain that this is more of an issue with pump-action still being broken, and the expedition loot pool still being rather booty, but I will replace these with something less aggressive for the sake of getting merged. Maybe pistols, MK58s? Retro lasers? I'm not sure what to put there in their stead. I'll map in pistols and commit it again unless someone has a better suggestion.

**Comment by RealIHaveANameOfficial** [comment]
I am closing this PR as I have made suggested adjustments and people have still expressed their non-desire for the ships to be included, and the lack of re-review tells me it is not of a fitting design.

**Comment by Cheackraze** [comment]
are you converting this into your new idea of the asteroid cracker? The latest proposal i saw you post in discord is much better fit for frontier, and gladly help you get it working well n stuff!

**Comment by RealIHaveANameOfficial** [comment]
Still working on this one in the background. I still want a small construct alternative for one to two with a pirate variant.. I don't know why all my ships are themed after crustaceans, but eventually I'll make a Faction that retroactively justifies it.

**Comment by MagnusCrowe** [comment]
I'm going to close this PR for now.  The ships within don't really fit in on this server and it does not look like it has been touched since November.  If you want to keep working on them feel free to do so and re-open.

**Pull request closed without merging**
