### PR TITLE
Charon (New Shuttle)

### PR DESCRIPTION
**Pull request by chrome-cirrus**
## About the PR
Adds a new medium sized expedition capable ['RORO'](https://en.wikipedia.org/wiki/Roll-on/roll-off) ship with an engineer/cargo flavor to it. Set up with engineering tools, fab, and a bit of materials to provide a starting point for custom buildout in the large cargo area.

Stylistically I cribbed a lot from the LVHI ships, I like their aesthetics a lot and strongly prefer a dark mode vibe myself. Besides the basics I put a good chunk of time into hopefully living up to the strong standard for detailing set by some of the newer ships. I think I did a decent job of attaining a spartan industrial vibe, without it feeling empty or sterile. 

## Why / Balance
I was frustrated with how cramped many of the existing exped ship interior layouts are and how the heavy usage of reinforced interior walls with lots of small chambers makes them time consuming and annoying to customize. I wanted to add something to the fleet that starts you off with a good foundation of basic functions, and gives you a large interior volume to work with to build out to suit your workflow (or just run a lot of cargo!). 

Big design highlights are: 
- Massive blast door into the aft equipment bay, with some strobes active when opened to set the right mood as you step out onto a new alien planet.
- L-shaped docking and circulation corridor joining the crew and cargo zones, with three docking airlocks.
- Conveyor system connected to the two side docks for handling containerized cargo.
- Fishbowl bridge and galley areas.
- Reinforced midship 'capsule' with engineering plant systems inside.

Main loadout highlights are: 
- Engineering focused items, from the shuttle's previous history as an equipment transport and support craft, and to help maintain the ship in the new owners' hands
- Salvage focused items, because there's always room for scavenging on the frontier of a universe brimming with advanced civilizations, and you don't always known when real resupply is coming
- A few items geared toward helping customize the shuttle by adjusting its structure and adding new capabilities. Most notably the RCD included with the CE/captain's locker fill in the bridge, and a circuit printer and engineering techfab

Recommended crew complement of 2-5 members.

Weighs in at 24x33, 628 total tiles.

Priced at 81000 spesos.

Consumes 44.8kW at idle.

## How to test
Start up a local instance, buy a Charon on the exped shipyard console, take it for a spin.

## Media
docked

mapping

nodevis

detail3

detail4

detail1

detail2

detail5

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**

:cl:
- add: Added ITS Charon class medium size expedition ship

### CODE REVIEW

**Comment by dvir001** [comment]
Not going to lie but ITS as a ship maker not great since its looks like your just keep telling people "Its Charon"

**Comment by ZombieChibiXD** [comment]
Hey unless you're modifying your PR, you don't need to merge master every single time.
Not angry or anything, just thought to let you know.

**Comment by chrome-cirrus** [comment]
> Hey unless you're modifying your PR, you don't need to merge master every single time. Not angry or anything, just thought to let you know.

Eh, I'm in the habit of keeping PRs up to date so I can catch conflicts early and I know whatever I'm proposing is being tested against the latest upstream. I'd usually squash the commits too when doing so but the docs explicitly say not to do that while reviews and conversations are in flight :P

**Comment by ZombieChibiXD** [comment]
eh? can't you just do it on local? doing it like this seems like a reviewer hell because they must review each commit even though it's a master merge, we can never know, you know. plus if it's just a new xml file there will not be any conflict whatsoever, doing it like this might cause conflict if for some reason a git revert happen.

Additionally if you request review, I feel like the PR should be unchanged until changes are requested.

**Comment by ZombieChibiXD** [comment]
While talking about commits however, what's with @chrome-cirrus
[Add BecomesStation component](https://github.com/new-frontiers-14/frontier-station-14/pull/2119/commits/fef4ad162d401de7de1cac3c690eb87835bea8e6)?

**Comment by chrome-cirrus** [comment]
> eh? can't you just do it on local? doing it like this seems like a reviewer hell because they must review each commit even though it's a master merge, we can never know, you know. plus if it's just a new xml file there will not be any conflict whatsoever, doing it like this might cause conflict if for some reason a git revert happen.
> 
> Additionally if you request review, I feel like the PR should be unchanged until changes are requested.

Sure, like I said, habit from work life. If it's not the norm for this project I'll knock it off, I'm not strongly opinionated either way.

> While talking about commits however, what's with @chrome-cirrus [Add BecomesStation component](https://github.com/new-frontiers-14/frontier-station-14/pull/2119/commits/fef4ad162d401de7de1cac3c690eb87835bea8e6)?

I didn't realize ship grids needed that component added to them, since it's not mentioned in a lot of the material out there discussing the process. Then I found out it is needed from seeing it mentioned in one particular video and then searching backscroll in Discord to read more about it, so I added it.

**Comment by chrome-cirrus** [comment]
As of latest commit:

helperupdate

**Comment by chrome-cirrus** [comment]
First off, thank you for the fantastic feedback and review pass! Gonna respond inline to these since it's such a long list.

> Hi! Fellow community member taking a stroll about : )
> 
> I love the industrial approach and departure from the norm. Lovely ship to behold and a joy to poke around. I think there’s a lot of excellent potential here.
> 
> Bridge
> 
>     * May reconsider re-mapping wall charger for a table charger. Those are generally considered for weapons and not general purpose civilian use.

Yep, good idea! There are some merc ships that have them, but this one is definitely not a merc/military vessel so it's off base to include it. Scooted stuff around in the bridge vestibule to make a tabletop charge work.

> 
>     * Check that the shuttle, crew and expedition console are powered up and ready to roll when you purchase the shuttle. Something doesn’t seem to be cooperating there.

That was me not checking closely enough after de-electrifying the bridge windows. Fixed.

> 
>     * Big sink in the kitchen might draw some ire.

Keeping it and rolling those dice because I really like the visual variety vs. just having the same one as in the bathroom.

> 
>     * Defib on the bridge needs to be re-orientated for access.
> 
>     * The ship has a -lot- of emergency eva suit lockers mapped. Maybe some of those could be moved to the airlock?
> 
>     * The two extreme edge reinforced windows in the cockpit are doubled up. Whoops.

Fixed and changed up the emergency lockers to be all mixed versions. I originally mapped the specific ones because of the differing fills, but after rolling them a few times it looks like there's not really much difference aside from the guaranteed small bottles for both gas mixes from the dual type lockers.

> 
> 
> Main
> 
>     * I noticed a chemdrobe was mapped. Was this intentional?

Probably the random clothing vendor tile next to the galley door? It's intentional, I like that little bit of RNG from other vessels that have a random one mapped and decided to include it.

> 
> 
> Engineering
> 
>     * Set gas mixer to: Primary 21 Secondary 79. Currently the mix is oxygen primary nitrogen secondary.

Can't believe I flipped that. Fixed. 

> 
>     * If you’re trying to trap gas you’ll want a valve to disable the passive vent with the way your atmos is mapped.

Added a pump on the outlet side of the filter to the passive vent, good catch.

> 
> 
> General
> 
>     * Lots of variation in mixed, pure oxygen and pure nitrogen emergency wall lockers. Your choice but sticking to mixed might be preferable if the goal is to provide equal opportunity survival.

See above.

> 
>     * Suggest mapping a salvage techfab for the job.
> 
>     * This ship comes pre-mapped with a LOT of materials. Given the nature of the job I imagine you’ll be swimming in mats pretty quickly. Just a thought.
> 
>     * Ditto tools. This ship comes with a lot of spare toolboxes and mapped equipment. It might be best to let these be things that the grunions make themselves. Put the hapless clowns who purchase your ship to work!

I agree, but that's kind of the point! It's not, thematically, supposed to be a salvage rig (even though a lot of people will probably use it as such). It's more of a pure engineering and construction ship. I wanted to make sure there was a bit more than normal there to let people bootstrap custom builds.

> 
>     * My sense is that there’s room for additional decoration work on this ship. You’ve put together some interesting and well thought out spaces. Caution strips, a few “oh dang space” posters and a safety moth or two could go a long way!

Fleshed it out a bit. I was keeping the equipment bay area a little bit stripped down because my intent with the design is that people would tear that up and customize it anyway, but yeah, agreed it could use a bit more color and variety. Did some more decal work to hopefully liven it up.

> 
>     * It’s generally requested to not put catwalks under thrusters.

Didn't know that, thanks. Removed.

> 
>     * This ship would not suffer with a second gyro imo.

Good catch. Extended the engineering compartments off the equipment bay a bit to allow for a second gyro, and create a little stash/hiding spot. 

> 
>     * Might consider a pump to assist the waste gas system. There’s a lot of ship to clear out. It’s not a requirement but it does help.

Agreed. Added two booster pumps, one fore and one aft.

**Comment by chrome-cirrus** [comment]
dpass1
dpass2

**Comment by chrome-cirrus** [comment]
> Someone might question the booster pumps in the atmos waste system that are feeding into the gas filter.

My reasoning there is they'll pull from the further reaches of the system and get everything into the short stretch in front of the filter so that it always has as full a queue as possible, so to speak. Entirely possible that's a dumb idea lol

I'm curious to see more feedback about the loadout and materials complement... I was trying a bit to avoid making it salvage oriented, even if that's prooooobably how a lot of people will use it, purely for flavor and "make them work a bit for it!" reasons. Logic being that, I'm definitely giving a little more than standard to start in some categories, making other aspects need a bit of legwork to get running might help keep the scales in balance. The only role I really want to be outright baked into the ship is pure engineering/construction. I did add a salvage fabricator, since a lot of that gear is dual use, and it does also play into the core idea of this being a ship with a lot of different possibilities as to how one uses it.

Also, I totally agree with regards to more signage and decals. I just really, really hate how the 'large format' space danger signage and others in that family look. I should probably just get comfortable with spriting tools and add more of the less huge/more subdued color scheme stuff for my own use...

**Comment by chrome-cirrus** [comment]
It's been a really good critique, I appreciate it! I know you're not slagging on it, just helping me get it to a point where it's merge worthy, and then gets people to actually pick it at the shipyard! 

Make them work for it was maybe not the best phrasing. I was trying to get at this needing some assembly to do things besides the baseline "keep the ship and whatever it might be ferrying operating over a long deployment" mission that is its purpose from factory. Thus, raw materials and fabricators instead of pre-made kits for salvage (or any other department). 

But yeah I think my mental point of comparison for what to include was some ships in earlier revisions that came with quite a lot of material in the hold... I see taking a tour of them now that's been pared down substantially. So, like you say, probably would be an acceptance issue.

And thinking about it more, a salvage gear set in there would align alright with what I have in my head for how this shuttle would have been used before making it to market at the frontier. You're out in far off places in a universe where intelligent life is not just known, but abundant. Of course you're going to bring along some gear to scavenge whatever previous inhabitants and visitors may have left behind. And more importantly, it aligns with how a lot of people are going to _want_ to use it and feel like it should be used, like you've expressed. I know has a salvage locker or not has been a deciding factor in which shuttle I run, I don't know why I'm resisting putting such a priority item on this ship given the overall aesthetic I've had in my head. 

Thank you for the reality check! I'm going to rejig a bit to cut the raw material load, and accommodate some salvaging gear in there. 

And this...

> However there is no space that presents an "engineering" vibe in my own estimation. Tables with parts, welding lockers. Spaces that look as if they are meant to be worked within while building towards a goal. The vibe for cargo and rolling up to a place and throwing a lot of stuff into a large void is absolutely present and in spades. That is the vibe that this ship screams to me. If you were hoping to present more of a visage of building, crafting, assembling or working towards something I would ask what elements of the way machines are congregating or that props are assembled really communicates that piece.

Gives me some ideas for fleshing out the decor/set building situation a bit. Let's see what I can make work...

**Comment by chrome-cirrus** [comment]
Did some rework based on feedback. Reduced the materials a bunch, added some salvage gear that aligns with how it's expected a lot of people will actually want to use the shuttle. Made some arrangement changes to give the cargo bay corridor spaces more focus.

Changed:
- Replaced exterior wall lights with post lights by the bay door
- Reworked stuff in the cargo bay corridors to make one side salvage coded, one side engineering coded
- Replaced atmospherics locker in distro room with non-hardsuit filled variant
- Some decorative stuff - Floor markings, posters, etc...

Dropped:
- Flatpacker
- Steel crate
- Loose steel/glass stacks
- Loose set of mesons

Added:
- Salvage suit storage unit
- Salvage specialist tool kit
- Salvage EVA suit wall locker (near bay door)
- Wall fuel dispenser
- A few loose T1 parts

image

**Comment by Cheackraze** [comment]
updating master is fine, referring to an old conversation. We review PRs according to latest commits, not each individual commit, and we squash merge to create one singular merge commit, so you're doing just fine. As far as the ship goes, it looks great, high effort, good work, and we will be adding this in so that I can finish my work on modernizing the new ship submission guidelines. Thankn you for your contribution!

**Review by Cheackraze — APPROVED** [review]

**Comment by chrome-cirrus** [comment]
@dustylens that would be grand!

**Pull request merged**
