### PR TITLE
Hunter Shuttle

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Added the Hunter Shuttle a Black Market shuttle sold by the syndicate, this shuttle is perfect for those with devious ideas as this shuttle is quite armored and small and Black Markets need more shuttles!

## Why / Balance

Ship Name: Hunter
Ship Class: Small (168 Tiles)
Ship Price: 46k
Ship Purpose: "A small armored syndicate assault shuttle,  perfect for devious operations!"
Ship Equipment: 1 Captain Locker (No Hardsuit), 2 Syndicate EVA, 1 Esword, 1 Makeshift Laser Pistol.
Ship jobs: Passager.

## Technical details

Add 1 Map file in /Maps/Shuttle and add 1 Shipyard file.

## Media

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: FoxxoTrystan
- add: The syndicate is selling a old ship named "Hunter" in the Black Market!

### CODE REVIEW

**Comment by Cheackraze** [comment]
looks like in your screenshot there, one of your right side thrusters is unpowered. the exterior airlocks are nice, and I'll load the map up to double check the other stuff later tonight

**Comment by Cheackraze** [comment]
otherwise its a nice design overall, but you should spice it up a bit with some syndicate decal work in the center area

**Comment by FoxxoTrystan** [comment]
Added some decals and "illegal posters"
Tried to add the Syndicate logo but its not symmetric, sad.

Also the thrusters works correctly.

image

**Review by Cheackraze — APPROVED** [review]
was just missing the warp point and late join spawn points, i added them and gunna merge this

**Pull request merged**
