### PR TITLE
Syndicate bluespace events and LPB tweaks

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### Syndicate Cache:
- Replaced some ballistic turrets with laser turrets.
- Replaced syndicate mobs with syndicate mobs in soft/hardsuits.
- Replaced indestructible walls and windows with destructible.

### Intercepted Syndicate Vessel:
- Replaced some ballistic turrets with laser turrets.
- Replaced syndicate mobs with syndicate mobs in soft/hardsuits.
- Replaced indestructible walls and windows with destructible.

### LPB:
- Added ballistic turrets and one laser turret.
- Replaced syndicate mobs with syndicate mobs in soft/hardsuits.
- Added additional spawner with low chance to spawn either syndie captain/second officer/operator.
- Replaced opened shutters on windows with closed blast doors.
- Added atmos setup.

## Why / Balance
Pain

## How to test
1. Spawn Syndie Cache with command `addgamerule BluespaceCacheError`
2. Intercepted Syndicate Vessel with command `addgamerule BluespaceSyndicateFTLInterception`
3. Warp to Listening Point: Bravo

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Syndicate bluespace events and POI now has destructible walls, slightly different hostile mobs and turrets.

### CODE REVIEW

**Review by whatston3 — APPROVED** [review]
Works alright, I'll trust your opinion on the balance of this stuff.  LP Bravo's breathable.

One question about the syndie shuttle: is the disconnected wire at the back intended, or is it an error?  You can see it in your first picture here (top left corner, near the back of the ship):
image

Still owe you that laser turret vision feature.

**Comment by ErhardSteinhauer** [comment]
It is intentional

**Comment by ErhardSteinhauer** [comment]
> It is intentional

Because those six thrusters are power hungry. And because I can use that as an excuse for why the shuttle suddenly appeared in NT space.

**Comment by whatston3** [comment]
> Because those six thrusters are power hungry. And because I can use that as an excuse for why the shuttle suddenly appeared in NT space.

Imagine, a set of wirecutters at the scene. :eyes:

**Comment by dvir001** [comment]
headwear_syndicate.yml fucked

**Pull request merged**
