### PR TITLE
Fixes the Admeme Teleporter Despawns

### PR DESCRIPTION
**Pull request by Myzumi**
## About the PR

Makes a new Portal entity as `PortalArtifactNoDespawn` That is basicly the same as `PortalArtifact` but without the `TimedDespawn` component

I do not know if theres an better way to compress the YML, but it does its job.

## Why / Balance

The portal would disappear after 120 seconds, which is bad for the admeme teleporter as it is annoying to replace the portal every 120 seconds.

## How to test

Run fork
Spawn admeme Teleporter
Setup portals
See it not despawn after some time

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

No changelog needed.

:cl:
- fix: Admin portals no longer despawn.

### CODE REVIEW

**Comment by dvir001** [comment]
Can't you just add a TimedDespawn with 0 / 999999 ?

**Comment by Myzumi** [comment]
> Can't you just add a TimedDespawn with 0 / 999999 ?

I can put it to a TimedDespawn of 99999, but wouldn't this just kinda unnecessary give the server 2 timers to "manage" or even more?

**Comment by whatston3** [comment]
You should fix your inheritance issues in BasePortalAdmin.  Since both PortalArtifact and BasePortalAdmin inherit from BasePortal, you could fix your issue one layer in.

Try something like this:
```
- type: entity
  id: BasePortalAdmin
  parent: BasePortal
  name: divine portal
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: portal-artifact
  - type: PointLight
    color: "#ed85c2"
    radius: 3
    energy: 1
    netsync: false
  - type: Portal
    canTeleportToOtherMaps: true

- type: entity
  id: PortalAdminStart
  parent: BasePortalAdmin
  description: Ooh, this'll be fun!

- type: entity
  id: PortalAdminEnd
  parent: BasePortalAdmin
  description: Enough, let me out!
```

**Comment by neuPanda** [comment]
> You should fix your inheritance issues in BasePortalAdmin. Since both PortalArtifact and BasePortalAdmin inherit from BasePortal, you could fix your issue one layer in.
> 
> Try something like this:
> 
> ```yaml
> - type: entity
>   id: BasePortalAdmin
>   parent: BasePortal
>   name: divine portal
>   abstract: true
>   components:
>   - type: Sprite
>     layers:
>     - state: portal-artifact
>   - type: PointLight
>     color: "#ed85c2"
>     radius: 3
>     energy: 1
>     netsync: false
>   - type: Portal
>     canTeleportToOtherMaps: true
>     randomTeleport: false
> 
> - type: entity
>   id: PortalAdminStart
>   parent: BasePortalAdmin
>   description: Ooh, this'll be fun!
>   suffix: Start
> 
> - type: entity
>   id: PortalAdminEnd
>   parent: BasePortalAdmin
>   description: Enough, let me out!
>   suffix: End
> ```

i have not fully dug into this however from a quick glance (10-15 min) i agree with @dvir001.  if we remove portal artifact as the parent of the admin portal and make it the base portal that is the parent, it should achieve your end goal

alternatively use the PortalBlue and PortalRed as your start and end portals they also inherit from base portal which should remove the timer issue while also not adding additional code.  not that new code is a bad think necessarily, but every new line of code is a potential new bug,  if you are able to reuse, that is better.

I am pleased to see the use of O from the SOLID code principles 
O being Open close which says that Objects or entities should be open for extension but closed for modification.
not everything in this code base lends its self to this, but this area does and i am pleased to see it followed :)

**Comment by neuPanda** [comment]
@dvir001 after a bit more discussion, it sounds like the goal here is to utilize the multi map capabilities or the artifact portal.  what are your thoughts on making an abstract multi map portal that extends the base portal functionality that both the Admeme and the Artifact portal inherit from

**Comment by Myzumi** [comment]
I've merged the two components together now as one `BasePortalAdmin`, which should be better than the things i've done before. I have not tested this as i cannot run this locally (i blame windows)

**Review by whatston3 — APPROVED** [review]
1. Should've set randomTeleport to false
2. No reason to have identical Start and End IDs - at least give 'em a description.
3. Hates fun, hates names, hates descriptions.

Otherwise this is fine.

**Pull request merged**
