### PR TITLE
Mats Crate

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
A new crate for cargo,

1 sheet of glass, plastic, steel, plasma and plasteel.
Cost: 8400, based on the content of the crate.

This crate useful for people who want a bit of everything, but don't want to buy full crates.

### CODE REVIEW

**Comment by sTiKyt** [comment]
Woudn't it bring back circuits spam?

**Comment by dvir001** [comment]
> Woudn't it bring back circuits production spam?

In what way?

**Comment by potato1234x** [comment]
yeah if people wanted to do that they could just buy the crates seperately

**Comment by Graugr** [comment]
nope. its must cost at least 50k, someone can use it foi circuitboard spam. Noone neede 6 stacks of durathread

**Comment by dvir001** [comment]
> nope. its must cost at least 50k, someone can use it foi circuitboard spam. Noone neede 6 stacks of durathread

15 **_pieces_** of glass, plastic, steel, plasma and plasteel, 10 **_pieces_** of cloth and 6 **_pieces_** of durathread.

When you see SheetName**1** it means a single unit

**Comment by Cheackraze** [comment]
so a half stack or less variety pack of materials? I was also confused at first at the intent behind this but that makes much more sense, but at least now I can consider it properly

**Comment by dvir001** [comment]
> so a half stack or less variety pack of materials? I was also confused at first at the intent behind this but that makes much more sense, but at least now I can consider it properly

There is only 1 issue with this crate, the way the game handle the stacks will not make the items auto stack (It was removed from upstream since it was lagging the game)

So when you open it you have to combine the items back into 15 units or the crate wont lock itself with all the items, don't merge it yet I will either add a "15" entity or just make the crate cost 2 times more and have 2 times the items (to have full stack instead)

**Comment by dvir001** [comment]
Updated the content of it and the price.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
