### PR TITLE
August '24 Upstream Merge

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Updates Frontier to space-station-14's upstream at 9a68cf0b0e67da5f5246ff7be8c35e0f0351015d (space-station-14#29123).

## Why / Balance

It is time.

## How to test

Very carefully.

## Media

TBD, probably nothing.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** ***this PR does not require an ingame showcase***

## Breaking changes

**Changelog**

:cl: whatston3 and dvir001
- add: The majority of contraband items have been identified with their class.
- tweak: Pirate cannons are now anchored in place and rotatable.
- tweak: All shuttle guns show their active status when examined and state if disabled on use.
- add: EMP cannon balls are now available through the pirate uplink.
- tweak: The Prowler is no longer EMP immune.
- remove: Monkey, kobold and poultry cube boxes have been removed from cargo.
- tweak: More monkey, kobold and poultry cube boxes are available in ChefVend vendors.
- add: Three new lobby art screens were added, two by GhostPrince, and one by GentleButter.
- tweak: Signing with crayons no longer consumes a charge.
- add: The traits menu has been reorganized; the short/tall trait buttons are disabled for species that cannot take them.
- add: Envelopes are available in both PTech machines and in the MailDrobe. The mail bag now accepts envelopes.
- add: Diamonds are now available on asteroids. Asteroids' walls can now reflect PTK shots.
- tweak: The asteroids with a brown IFF outline are now easier to mine.
- add: Added a Clumsy trait.
- fix: All POIs apart from LP Bravo and the Pirate Cove cannot be hidden.
- tweak: The Janitor and Valet now have access to the mail room.
- add: Added a ValetDrobe and MailVend to Frontier Outpost.
- tweak: The Scrapyard console has been moved to Grifty's/McHobo, all mobs have been removed from the POIs.
- add: Added a FuelVend to McHobo.
- tweak: Coal and artifact fragments now have sell values of 3 and 160 spesos per ore.
- tweak: items printed from a blood cult forge are now not worth FUCs.
- add: A pet fox is randomly available as an emotional support pet.
- remove: The tile-meister 5000 has been replaced with the cutter machine, which now has all its recipes.

### CODE REVIEW

**Comment by VividPups** [comment]
Would this include the new Laser shotgun?

**Comment by whatston3** [comment]
> Would this include the new Laser shotgun?

If it was merged before #29123, yes.

**Comment by VividPups** [comment]
:(

**Comment by nyozzl** [comment]
how long can i expect this to be.. per chance?

**Comment by dvir001** [comment]
> how long can i expect this to be.. per chance?

As long as it takes to get it to run, balance, and working.
No timeframe

**Comment by Cheackraze** [comment]
Usually a 1-2 week time frame for testing, bug fixes, verification and modification, but that's entirely dependant on what's inside

**Comment by whatston3** [comment]
> how long can i expect this to be.. per chance?

It's maybe a day away from being reliably runnable.  Check back tomorrow, try building and running this branch then.  If you're still having issues with the branch as it exists, then I'm not quite sure what's up.

**Review by dvir001 — APPROVED** [review]
Looks fine, error seems to be false.
Ready to go.

**Pull request merged**
