### PR TITLE
Security Ship Line-up Alterations, Prowler Intro, Trident Retirement, and more!

### PR DESCRIPTION
**Pull request by Kesiath**
## About the PR
Introduces the Prowler. A medium-sized patrol craft, the prowler class is a dedicated deep space reconnaissance and enforcement vessel outfitted with ECM technology to avoid detection.

The Marauder's stealth coating, upon further investigation by the Office of the Admiralty, was initially highly effective but has unfortunately lost its capabilities after long term exposure to the high UV rays found in the Frontier sector. As a result, only the shape of the vessel assists with providing stealth through a reduced radar cross section, and so IFF returns are able to be mitigated for longer-range stealth to be much the same as it was before.

**Media**
image

**Changelog**
:cl: Kesiath
- add: Added the Prowler! A new Stealth capable Medium ship for Security.
- remove: Removed the Stealth IFF Console from the Marauder.
- remove: Removed the Trident from the Security catalog.
- fix: Fixed the gun cabinets on the Marauder to manually have the correct items.

### CODE REVIEW

**Comment by CrigCrag** [comment]
the carrier seems to be getting EMP-RPGs and blasters, it might be worth expanding upon the Marauder's niche, maybe by giving anything inside it immunity to EMP somehow, or changing the M_EMP to only effect the area outside of the vessel.

I've only seen the M_EMP used on accident, really. disabling ships within 100 meters is cool, but it also forces security to only use ballistics, which is meh for RP and gameplay alike.

i agree the Marauder in it's current state has split niches, and a separate stealth vessel helps alleviate that. if the Marauder's remaining niche is going to be shared, however, it needs to be the best at what it does imo.

**Comment by Cheackraze** [comment]
> the carrier seems to be getting EMP-RPGs and blasters, it might be worth expanding upon the Marauder's niche, maybe by giving anything inside it immunity to EMP somehow, or changing the M_EMP to only effect the area outside of the vessel.
> 
> I've only seen the M_EMP used on accident, really. disabling ships within 100 meters is cool, but it also forces security to only use ballistics, which is meh for RP and gameplay alike.
> 
> i agree the Marauder in it's current state has split niches, and a separate stealth vessel helps alleviate that. if the Marauder's remaining niche is going to be shared, however, it needs to be the best at what it does imo.

Defibs and health analyzers in general should be made immune.  The marauder is just too strong at what it does.  Having both EMP and stealth IFF is having 2 very powerful antipirate measures.  Maurader is more fully equipped and better for large groups but the prowler would be in the same niche at less than half the price, size, and better fitted for a smaller sec crew/lower pop.  The marauder with 3 or less is understaffed.  Ultimately they would fill similar roles just at 2 different crew sizes.

**Comment by CrigCrag** [comment]
yeah splitting prowler and stealth off into it's own thing is for the better, however unless M_EMP is made worth it the carrier will outclass the Marauder in pretty much every regard. 

Marauder would have EMP weaponry and the M_EMP, which at best is a last ditch fuck-you and at worst is a suicide button. The carrier would have EMP weaponry and uber long-range radar, along with convenient support ships to cover its weaknesses

ship thruster count doesn't really matter too much as they only affect acceleration and ship speed is capped. most ships go from 0-20 at a similar speed so the marauder doesn't really have that going for it either (if it even accelerates faster, i can't tell.)

**Comment by Cheackraze** [comment]
> yeah splitting prowler and stealth off into it's own thing is for the better, however unless M_EMP is made worth it the carrier will outclass the Marauder in pretty much every regard.
> 
> Marauder would have EMP weaponry and the M_EMP, which at best is a last ditch fuck-you and at worst is a suicide button. The carrier would have EMP weaponry and uber long-range radar, along with convenient support ships to cover its weaknesses
> 
> ship thruster count doesn't really matter too much as they only affect acceleration and ship speed is capped. most ships go from 0-20 at a similar speed so the marauder doesn't really have that going for it either (if it even accelerates faster, i can't tell.)

the thrusters matter surprisingly a lot for the bigger ships, especially once you get into the maurader/carrier range.  The EMP will be made better over time yet by making a few more things immune to help it out as the premier assault craft.  Replacing the trident is a good step I think, since its basically the black sheep of the sec lineup now

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
