### PR TITLE
Cargobucket (new)

### PR DESCRIPTION
**Pull request by nyozzl**
## About the PR
Added a new expedition shuttle

## Why / Balance
I think a bit more expedition ships would be a nice addition to the server and the idea of a satellite is interesting

## Media
image

Cargobucket blueprint

Cargobucket initalized

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->[X]

- [X] added screenshots and/or videos to the pr
:cl:
- add: adds new expedition shuttle cargobucket

### CODE REVIEW

**Comment by nyozzl** [comment]
*cricket noises*

**Comment by MagnusCrowe** [comment]
> _cricket noises_

There's quite a bit going on in this ship that needs to be checked, so you'll have to be patient while waiting for us to find a chunk of time to devote.

**Comment by nyozzl** [comment]
> > _cricket noises_
> 
> There's quite a bit going on in this ship that needs to be checked, so you'll have to be patient while waiting for us to find a chunk of time to devote.

yeah I understand I just did a little joke

**Comment by nyozzl** [comment]
redesigning

**Comment by nyozzl** [comment]
inform me of any needed changes also I rushed the faxes

**Comment by Cheackraze** [comment]
looks fine to me design-wise, though I havent looked at everything super close.

**Comment by nyozzl** [comment]
weh

**Review by dvir001 — CHANGES_REQUESTED** [review]

**Comment by nyozzl** [comment]
let me know if anything else needs to be changed

**Comment by MagnusCrowe** [comment]
1. Over 40% of your ship is hallways.  That seems high to me.
2. Don't map the SR's papercut-proof gloves.
3. Remove any papers that are stamped by centcom.
4. I'm confused on why this is being called a satellite.  Isn't it more than just a satellite?  It has an expedition console so it's presumably designed to land on planets regularly...  Conceptually I don't get it.
5. I can't put my finger on it but the size of each department seems out of proportion.  Engineering and cargo looks really cramped, but the bar is huge.

**Comment by MagnusCrowe** [comment]
It also looks like you didn't actually do anything to address any of the issues dvir brought up.

**Comment by nyozzl** [comment]
alright thanks for the info for the future. I will surely keep this in mind for future designs. the satellite theme doesn't fit frontier anyway

**Pull request closed without merging**
