### PR TITLE
Fix Cargo Trade

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Cleanup the market

## Why / Balance
Holy moly

## How to test
Look at new filters
Sell at cargo

## Media
N/A

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by whatston3** [comment]
Small set of changes:
* Fixes whitelist for uranium sheets (id not entities)
* Consistent component definition in trade outpost
* Disables purchase cart button when empty
* All button now fills your cart as much as it can - 5000 iron ore, empty cart: press all, 4100 in market, 900 in cart

All changes up on [whatston3:2024-08-07-CargoTime-suggestions](https://github.com/dvir001/frontier-station-14/compare/2024-08-07-CargoTime...whatston3:frontier-station-14:2024-08-07-CargoTime-suggestions).

**Comment by dvir001** [comment]
> Small set of changes:
> 
> * Fixes whitelist for uranium sheets (id not entities - my fault)
> * Consistent component definition in trade outpost
> * Disables purchase cart button when empty
> * All button now fills your cart as much as it can - 5000 iron ore, empty cart: press all, 4100 in market, 900 in cart
> 
> All changes up on [whatston3:2024-08-07-CargoTime-suggestions](https://github.com/dvir001/frontier-station-14/compare/2024-08-07-CargoTime...whatston3:frontier-station-14:2024-08-07-CargoTime-suggestions).

Just yeet it in.

**Comment by whatston3** [comment]
Got a function for some rudimentary entity sanitization, though it probably doesn't function well with purchase-side pricing.  I still think a better idea (possibly in combination with this) might be to map certain prototypes when sold to others to be stored (e.g. ShipyardRCD->ShipyardRCDEmpty).

Diff up here as before: [whatston3:2024-08-07-CargoTime-suggestions](https://github.com/dvir001/frontier-station-14/compare/2024-08-07-CargoTime...whatston3:frontier-station-14:2024-08-07-CargoTime-suggestions).

If we add handling for BallisticAmmoProvider, RevolverAmmoProvider, SolutionAmmoProvider, HitscanBatteryAmmoProvider, so the entities are actually empty, we could sell magazines without worries of duplication.

Also, another idea might be to enforce a minimal value (for argument, $10) on any item with an explicit value of zero (or allow purchasing carts with no value).

**Comment by dvir001** [comment]
> Got a function for some rudimentary entity sanitization, though it probably doesn't function well with purchase-side pricing. I still think a better idea (possibly in combination with this) might be to map certain prototypes when sold to others to be stored (e.g. ShipyardRCD->ShipyardRCDEmpty).
> 
> Diff up here as before: [whatston3:2024-08-07-CargoTime-suggestions](https://github.com/dvir001/frontier-station-14/compare/2024-08-07-CargoTime...whatston3:frontier-station-14:2024-08-07-CargoTime-suggestions).
> 
> If we add handling for BallisticAmmoProvider, RevolverAmmoProvider, SolutionAmmoProvider, HitscanBatteryAmmoProvider, so the entities are actually empty, we could sell magazines without worries of duplication.
> 
> Also, another idea might be to enforce a minimal value (for argument, $10) on any item with an explicit value of zero (or allow purchasing carts with no value).

Can we do it in a new PR?
For now I just want to clear the big issues before we add fixups.

**Review by whatston3 — APPROVED** [review]

**Pull request merged**
