### PR TITLE
Fixed bison doors + added mass scanner

### PR DESCRIPTION
**Pull request by MatthewBadger**
## About the PR
replaced all doors and added one mass scanner computer to bridge

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- fixed bison doors and added mass scanner to it

### CODE REVIEW

**Comment by Cheackraze** [comment]
why is github thinking these are new files

**Comment by MatthewBadger** [comment]
Eldritch github

**Comment by MatthewBadger** [comment]
What needs to be changed for this to be accepted?

**Comment by Cheackraze** [comment]
i see the issue, you need to make a new branch and commit your changes on that branch, and make a new PR

**Comment by MagnusCrowe** [comment]
This has been inactive for a while so I am going to close it for now.  Please feel free to reopen if you still want to work on it.

**Pull request closed without merging**
