### PR TITLE
Mercenary Hub

### PR DESCRIPTION
**Pull request by NkoKirkto**
## About the PR
Added the Mercenary Hub a new PoI

## Why / Balance
A place for mercs to hang out between contracts/clients and secure new contracts for themselves!
It Features:
-A Small Kitchen and Bar Area
-3 Generic Faction Bases in wich Factions can move in each round and customize them.
-Small Medbay
-And a firing range

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- add: Added the Mercenary Hub a Place for Mercs and factrions to hang out and secure new contracts.

### CODE REVIEW

**Comment by dvir001** [comment]
I personally don't see the point in adding another POI that is just a mix of other POIS when the expo lounge can be reworked to fit the merc theme.

This is adding poi blout, like the current state of the becon poi.

**Comment by NkoKirkto** [comment]
> current

Okay
-Why bloat the sector is so vast that it doesn't matter even 100 pois(if they are spread out far in between) wouldnt be an issue because space is vast.
-It provides Roleplay Value especially for factions. Now they can have an Headquarter from which they operate
-The exped longe has another target group.
Mercenarys arent only as a schmock which you hire for exped to save your sweet ass. They also do a number of other things like headhunts, bountyhunts,escort and personal protection.
-Since the new merc stuff a lot of mercs are just lingering around at the Fronteir this would give them a Hub as the name says to wait for new clients and or contracts and would make it easier for potential clients to find mercs.

**Comment by dvir001** [comment]
> > current
> 
> Okay -Why bloat the sector is so vast that it doesn't matter even 100 pois(if they are spread out far in between) wouldnt be an issue because space is vast. -It provides Roleplay Value especially for factions. Now they can have an Headquarter from which they operate. I think this will make the next step for factions to manifest themselve into the game -The exped longe has another target group. Mercenarys arent only as a schmock which you hire for exped to save your sweet ass. They also do a number of other things like headhunts, bountyhunts,escort and personal protection. -Since the new merc stuff a lot of mercs are just lingering around at the Fronteir this would give them a Hub as the name says to wait for new clients and or contracts and would make it easier for potential clients to find mercs.

Pois add lags, we're making a change soon that none gameplay critical pois will random shuffle In the future, merc poi having no critical function will mean it wont exist every round.

Keep it in mind when adding another POI that has no core game mechanics on it other then RP.

**Comment by NkoKirkto** [comment]
> > > current
> > 
> > Okay -Why bloat the sector is so vast that it doesn't matter even 100 pois(if they are spread out far in between) wouldnt be an issue because space is vast. -It provides Roleplay Value especially for factions. Now they can have an Headquarter from which they operate. I think this will make the next step for factions to manifest themselve into the game -The exped longe has another target group. Mercenarys arent only as a schmock which you hire for exped to save your sweet ass. They also do a number of other things like headhunts, bountyhunts,escort and personal protection. -Since the new merc stuff a lot of mercs are just lingering around at the Fronteir this would give them a Hub as the name says to wait for new clients and or contracts and would make it easier for potential clients to find mercs.
> 
> Pois add lags, we're making a change soon that none gameplay critical pois will random shuffle In the future, merc poi having no critical function will mean it wont exist every round.
> 
> Keep it in mind when adding another POI that has no core game mechanics on it other then RP.

Isn't Rp the main part of the Server? I still think there is a critical need for a place for factions to meet up make plans etc. I mean PoIs like griftys, omnichurch,tinias sure it could always only exist only one of them. But after that lotic where is the critical gameplay need for the exped longe you could just make AME ships buyable at the Fronteir again gamplay wise it had no right to exist. It only exists because of roleplay purposes and to stop shitters to break the immersion. And an attachment of the Exped longe with the same size as the PoI i submitted would create the same amount of lag or?

**Comment by NkoKirkto** [comment]
I just noticed some things i forgor befor review i will add as soon as i get home will be done probably 17 o clock CET.
-Janitor Closet
-Make the Medbay a bit bigger
-move the engie room and solars back for both of these things.

**Comment by MagnusCrowe** [comment]
Do mercenaries operate under the command of some organization that would bankroll such a station (I thought mercs on frontier were all independent freelancers, who owns this station)?  Is the station being run by someone that profits off of mercenaries hanging out?

Please explain the reasoning behind the existence of the station.

**Comment by NkoKirkto** [comment]
> Do mercenaries operate under the command of some organization that would bankroll such a station (I thought mercs on frontier were all independent freelancers, who owns this station)? Is the station being run by someone that profits off of mercenaries hanging out?
> 
> Please explain the reasoning behind the existence of the station.

Okay that is a good point i mean there is my facction wich i made a while back(https://discord.com/channels/1123826877245694004/1208581339410989086)
Also it depens it is designed (as already explained) generically so up to 3 Factions(or more if theyre sharing spaces) can move into the Station and can have a headquater. So i would say that it would be bankrolled by a coperation between all the differnt factions in the Fronteir(If you insit on it i can do extra lore for it)

I already explaind the general logical and RP reasoning in the post above.

**Comment by NkoKirkto** [comment]
> I think the bloat issue is less about server performance and more about spreading players too thinly across the server.
> 
> I'm not seeing a compelling argument for why mercenaries cannot do their business at Tinnias or Frontier outpost
> 
> I think we could still use something like this for admin events. It looks like a very nice station.

Its not only about Mercs in general but also about factions wich get next no no favour in the fronteir rigth now.
With this Factions would be able to grow to a bigger force and in return greatly favours RP.
Stuff like diplomacy between the faction faction wars(dont know if that is against the rules but would be pretty cool to have a shift long a war(even if its only trough sabotage)between factions.
Factions are way to small rigth now and have the potential for so much more.

**Comment by NkoKirkto** [comment]
> > I think the bloat issue is less about server performance and more about spreading players too thinly across the server.
> > I'm not seeing a compelling argument for why mercenaries cannot do their business at Tinnias or Frontier outpost
> > I think we could still use something like this for admin events. It looks like a very nice station.
> 
> Its not only about Mercs in general but also about factions wich get next no no favour in the fronteir rigth now. With this Factions would be able to grow to a bigger force and in return greatly favours RP. Stuff like diplomacy between the faction faction wars(dont know if that is against the rules but would be pretty cool to have a shift long a war(even if its only trough sabotage)between factions. Factions are way to small rigth now and have the potential for so much more.
> 
> And for mercs as said it gives them a central place to be at at be found at so if you want a merc to safe your sweet ass on a exped just go too the lHub and hire one. No more bloating the Radio with("Is there a merc willing to work for me" (Wich in turn also favours roleplay if there are multiple mercs at the hub competing for each arriving client)

Also i forgot to add Tinnias has a different target group also. Tinnias target group should be people wanting somthing to eat or to drink or gambel. Fronteir is for buying ships supplys and as a central outpost in the sector. And people are most of the time spread thinley but this Hub would solve the problem in regades to mercs. One Central Hub where all the Mercs can Chill between contracts and or clients.

**Comment by MagnusCrowe** [comment]
I don't understand why a bar doesn't include mercenaries as a primary user.  Ever see the cantina scene in Star wars?

**Comment by NkoKirkto** [comment]
> I don't understand why a bar doesn't include mercenaries as a primary user. Ever see the cantina scene in Star wars?

Yeah but that dosent refutes the:Factions argument,that it actually lowers players being spread out thinly,favours roleplay
And also Tinnas dosent have any living quaters it has like 3 rooms that you could call dorms.

**Comment by MagnusCrowe** [comment]
> > I don't understand why a bar doesn't include mercenaries as a primary user. Ever see the cantina scene in Star wars?
> 
> Yeah but that dosent refutes the:Factions argument,that it actually lowers players being spread out thinly,favours roleplay And also Tinnas dosent have any living quaters it has like 3 rooms that you could call dorms.

Well, I'm not trying to debate you I'm just trying to process for myself where exactly this puzzle piece fits in to the design of the server.  I admit that factions don't really have a focal point for organization outside of their own ships.

**Comment by dvir001** [comment]
While im not 100% against the idea of another POI I honestly think this won't get the use you are thinking it will as in order to have a POI used a lot it also need a gameplay function other than the RP one.

Sure it might have people visiting it from time to time but its hard to have it used often unless it has another thing to added to it that is unique.

Anomaly lab has the generator.
Expo has the shipyard.
The court house and nfsd used for security gameplay.

Tinia has a large kitchen and botanic zone (We should consider adding more to this one, like a shop for plants or animals)
Casino has the gambling and ticket vender to it (still need more stuff added to it, actual gambling system or mini game will be cool).

Then you have grifty's and the church that are full RP and as of right now it shows with the number of times they are used compared to other POI's.

If you got some gameplay idea that could add to it that can be unique to this POI it wont hurt.

**Comment by NkoKirkto** [comment]
> A training / shooting range or some kind of merc mission reward system would be fun for in here. like, successfully captivate a live space bear (or alien, or specific expedition-only loot) and bring it into the station for delivery & reward. As like, the only station where it's allowed to bring in some live aliens for giggles.
> 
> Then again, only time i see people on exped lounge is when they want to buy a ship. Never RP'ed there. This may as well be a good idea for expedition _lounge_ . 
> 
> The station you made here, is very pretty, however i do agree with Dvir. We can however alternate the exped lounge design randomly, but that may bring confusion. We got to be strict, if there are a handful of other requests to add a POI, the same answer is given.

"We got to be strict" yeah the exped longe and the merc hub have 2 completly different target groups and yeah a bounty system like that could be indeed very fun and maybe you could reuse the bounty hunter computer for that but that limits it to things that are only in creats and i think there arent a lot of unique items that fit in creates that cannot be researchd or aquierd otherwise. Means a new component to attach labels to pet carriers and machines and i cant code C# so yeah.
And there is a shooting range on the station in the upper left.

**Comment by MagnusCrowe** [comment]
I think I understand how this station would fit in.  Thanks.

I'll review it properly when I have the time.

**Comment by NkoKirkto** [comment]
> have

Thank you a bunch.
If you have any Issues i will fix them asap can be that i fucked up atmos or electricity somewhere(although i tripel checked) its my first PoI and map in General.

**Comment by NkoKirkto** [comment]
> > > A training / shooting range or some kind of merc mission reward system would be fun for in here. like, successfully captivate a live space bear (or alien, or specific expedition-only loot) and bring it into the station for delivery & reward. As like, the only station where it's allowed to bring in some live aliens for giggles.
> > > Then again, only time i see people on exped lounge is when they want to buy a ship. Never RP'ed there. This may as well be a good idea for expedition _lounge_ .
> > > The station you made here, is very pretty, however i do agree with Dvir. We can however alternate the exped lounge design randomly, but that may bring confusion. We got to be strict, if there are a handful of other requests to add a POI, the same answer is given.
> > 
> > 
> > "We got to be strict" yeah the exped longe and the merc hub have 2 completly different target groups and yeah a bounty system like that could be indeed very fun and maybe you could reuse the bounty hunter computer for that but that limits it to things that are only in creats and i think there arent a lot of unique items that fit in creates that cannot be researchd or aquierd otherwise. Means a new component to attach labels to pet carriers and machines and i cant code C# so yeah. And there is a shooting range on the station in the upper left.
> 
> We can add spawn markers to exped generated maps for random bounty items. Such as:
> 
> * Station Delivery notes
> * Experimental borg that must be carried back and cant be interacted with
> * Other strange items that add story to the expedition station you're visiting
> 
> I love the idea though, the expeditions are a unique part of frontier and this would add more incentive to play them

Yeah but that is far outside my reach with what
-I can code
-And what im trying to achive here.
That said if sombody reworks Expeds and helps me making a costum bounty console (Or a special selling consol where you only can sell those uniqe things from the expeds) I would be on it. Especially because that would also fit in with my Idea for a Salvage Yard PoI

**Comment by Cheackraze** [comment]
more POI are fine, but as was brought up before, if its a pure RP/faction type without a game-critical function, it will likely find its way into a 'pool' of random poi to spawn each round. Some of our existing POI fit into this criteria as well, such as the church, grifty's, the casino, etc. I may not personally be able to get to a review of it until this weekend however.

**Comment by NkoKirkto** [comment]
> may

How many POIs will be there at each round? 5? I mean we have 4 rigth now.
And will every nonessential point be in it?
So:Tinnias,Griftys,Curch and Pit?

**Comment by Cheackraze** [comment]
> > may
> 
> How many POIs will be there at each round? 5? I mean we have 5 rigth now. And will every nonessential point be in it? So:Tinnias,Griftys,Casino,Curch and Pit?

there will likely be around a dozen POI each round, and I'd like for around half of them to be taken from an RNG pool. As it stands, tinnia's is likely to stay permanent because its the main food POI still, but places like griftys, casino, church, and likely this one will be in a 'pool' to choose from.

**Comment by Cheackraze** [comment]
I want to let @MagnusCrowe give it a look over still, but so long as this isnt a loot pinata type POI im ok with adding it

**Comment by NkoKirkto** [comment]
> I want to let @MagnusCrowe give it a look over still, but so long as this isnt a loot pinata type POI im ok with adding it

I mean there isnt much to loot the only items being provided with the station are the plushies and training laser rifels wich both have 0 Value ig. 
Will it stay permanent for now then?

**Comment by MagnusCrowe** [comment]
I'll check this PR this weekend.

**Comment by MagnusCrowe** [comment]
image

You're missing a piece of LV cable here.  It's preventing these vending machines from being powered.

image
What's going on with disposals here?

image
The SMES is not set up correctly.

image
Even when I set it up correctly, the solar panels weren't working properly.  I'm not a solar expert so you may want to ask for help from the mapping section on discord.

image
You don't need air sensors.  All active vents and scrubbers have air sensors built into them.  Air sensors are for places where you do not want active vents and scrubbers, like in a passive vent atmos setup or in burn-chambers.

image
Please consider adding meteor shielding to the areas of your station where there are windows. Above is an example of what I mean.

You are missing vents and scrubbers in the medbay, somewhere I'd expect miasma to build up, especially because you lack a morgue or bodybags.  If you want, go ahead and slap a box or two of bodybags on the table in the medbay.

I kinda love the little office/dorms/lounges you've built for the different factions.  Very cool.  Makes me think that there should be a head office for some sort of station administrator to keep track of who's occupying the various rooms and manage the staff who would operate the kitchen/bar/janitorial, maybe even a place for a STC.  Up to you though, just some thoughts off the top of my head.

After the issues I mentioned are taken care of, I'll re-review this.  Good work.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
woops forgot to flag this as requested changes

**Comment by NkoKirkto** [comment]
> 
> image
> 
> You're missing a piece of LV cable here.  It's preventing these vending machines from being powered.
> 
> image
> What's going on with disposals here?
> 
> image
> The SMES is not set up correctly.
> 
> image
> Even when I set it up correctly, the solar panels weren't working properly.  I'm not a solar expert so you may want to ask for help from the mapping section on discord.
> 
> image
> You don't need air sensors.  All active vents and scrubbers have air sensors built into them.  Air sensors are for places where you do not want active vents and scrubbers, like in a passive vent atmos setup or in burn-chambers.
> 
> image
> Please consider adding meteor shielding to the areas of your station where there are windows. Above is an example of what I mean.
> 
> You are missing vents and scrubbers in the medbay, somewhere I'd expect miasma to build up, especially because you lack a morgue or bodybags.  If you want, go ahead and slap a box or two of bodybags on the table in the medbay.
> 
> I kinda love the little office/dorms/lounges you've built for the different factions.  Very cool.  Makes me think that there should be a head office for some sort of station administrator to keep track of who's occupying the various rooms and manage the staff who would operate the kitchen/bar/janitorial, maybe even a place for a STC.  Up to you though, just some thoughts off the top of my head.
> 
> After the issues I mentioned are taken care of, I'll re-review this.  Good work.

Should i just route the disposals into Space?

And hm a head office would require me to remap at least one of those lounges to make the station overall bigger. I mean if sombody wants to become SR 2.0 he can just occupy one of the offices and make the dorms faction unspecific and free for all.

**Comment by MagnusCrowe** [comment]
Does the power work when you load it?

**Comment by dvir001** [comment]
Remove all kitchen and botanic
Replace it with spot for cargo area. (Dont map working computers, broken for now)

**Comment by NkoKirkto** [comment]
Converted into a draft until dvir adds the computers.

**Comment by Vonsant** [comment]
@NkoKirkto wazzup, how is going? Need help?

**Comment by NkoKirkto** [comment]
Sombody is working on a civil contraband selling station that will get on here. But takes some time.

**Comment by NkoKirkto** [comment]
Uhhh i guess i rework this after my vacation. Onto the pile of shit i have to do it goes.

**Comment by dvir001** [comment]
Closing this for the main time, you can reopen if needed.

**Pull request closed without merging**
