### PR TITLE
Barrels

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added barrels to all wrecks, containing a big selection of regents, from chems to ketchup.
Added the more hard to get chems to cargo, but with a costly price to anyone that want to skip trading or finding them.

Barrels contain 1000u of liquids storage and have the same shape as an air canister. 

## Why / Balance
More ways to obtain chems.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl:
- add: Added barrels of chems, oil, water, fuel, booze, etc. to wrecks, rare chems to cargo.
- tweak: The ChefVend now contains one jar of each oil.

### CODE REVIEW

**Comment by dvir001** [comment]
Going to split this PR to Barrels only for now.

**Comment by dvir001** [comment]
I need to convert the paper labels to actual paper like the kegs / crates.

**Comment by whatston3** [comment]
Might make two slight changes to the sprites.
1. I think the barrel looks a bit less lumpy if the side ridges are a bit more subtle:
    Left is proposed, right is existing.
image
2. I think the paper label's perspective is wonky.
    Left is proposed, right is existing.
image

**Comment by dvir001** [comment]
> Might make two slight changes to the sprites.
> 
> 1. I think the barrel looks a bit less lumpy if the side ridges are a bit more subtle:
>    Left is proposed, right is existing.
>    image
> 2. I think the paper label's perspective is wonky.
>    Left is proposed, right is existing.
>    image

Yee
Should we also add an "Open/Close" mod for the top notch?

image

**Comment by whatston3** [comment]
> Should we also add an "Open/Close" mod for the top notch?

This is left as an exercise for the reader :^)
Reasonable ask, but I'll focus on getting the loot table for wrecks done for now - everything else is resprited, added a white/black variant (might look scuffed FWIW).

**Comment by whatston3** [comment]
Added barrels to wrecks.  The spawn rate seems fine to me, they aren't super common.  I've replaced the tank spawner in favour of the barrels (why not, local flavour) - high cap still exists, but is a lot less frequent (still about 20% more frequent than it was).

Added separate spawners for chem-y stuff (ethanol, iodine), less chem-y stuff (diethylamine, mayo),drinkables (water, absinthe), and a dedicated empty spawner.

Unless you want these on vgroids, this seems acceptable to me.  Shouldn't be absolutely tripping over chems, but you should find maybe a few barrels, mostly of chemical stuff, per wreck.

**Comment by whatston3** [comment]
Anyways, pending further goofs, I'll give this a soft approval - double check when you can, let me know if I missed anything dumb.

Paper labels are working as they should.

**Review by whatston3 — APPROVED** [review]

**Comment by whatston3** [comment]
Also, so I don't forget, might recommend increasing the cargo price on the barrels by about 2-5x, should foster player sale, and 5 speso per unit isn't exactly pricy.

**Comment by dvir001** [comment]
@whatston3 Its done, merge when you think its good.

**Comment by whatston3** [comment]
Reduced the oil jug count to 1 of each in the ChefVend (restocks now available via barrels).
Removed chem crates (preferring barrel restocks - I do think there isn't much harm in having them all available apart from filtering, but I'll leave the rare-only ones as-is for now).
Changelog updated.
Price might need work but I do think that the current values enable player arbitrage, which is good.

**Review by whatston3 — APPROVED** [review]

**Comment by whatston3** [comment]
> Is #2453 largely obsolete now?

Yes, if this PR is more or less acceptable as-is.

**Comment by whatston3** [comment]
Works alright, Liquidator's fine.

Curious to see how this lands.

Will merge #2453 and this once tests pass.

**Pull request merged**
