### PR TITLE
PMC hardsuit

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
i made a reskin of the HoS hardsuit with identical stats to merc hardsuit
also made the suit storage and wall suit storage for it of course
currently doesnt actually spawn anywhere, because editing random peoples shuttles is weird, and i dont really know how to edit exped/salvage/whatever else loot tables.

ignore the random commits related to my shuttle i submitted i dont know why they're there

## Why / Balance
i like HoS hardsuit look but i cant map it because it will confuse new players or something. also i personally think the current merc and private security hardsuits are kinda visually unappealing to me atleast

## How to test
search PMC in entity spawner, every result will be my hardsuit.

## Media
hardsuit + oxygen/nitrogen tank on human, vulpakin, and vox (to show the different race specific helmet sprites working)
image
image
image
image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: PMC hardsuit, a recolored HoS hardsuit with identical stats as merc/private sec hardsuit. Currently only way to get is via its suit storage lockers, which don't spawn anywhere right now because I do not want to edit peoples shuttles.

### CODE REVIEW

**Comment by starch70** [comment]
oh god my shuttles changes are in there for some reason please someone remove those

**Comment by starch70** [comment]
i added my hardsuit to the loot tables and lathe places i found merc hardsuits in and my shuttle is trying to invade me again help

**Comment by dvir001** [comment]
Please remove unrelated files or reopen the PR without the files.

**Comment by starch70** [comment]
ok i fixed my shuttle PR trying to invade this PR and i changed the .rsi folders to be lowercase instead of uppercase

**Comment by starch70** [comment]
just rememebered that there is no fucking PMC crate so i changed the pmc hardsuit crates to have merc crate parents instead of the non-existant PMC crate

**Comment by starch70** [comment]
should i change the color of the green parts on the helmt? if so what do i change it too?

**Comment by starch70** [comment]
i have just realized that the HoS hardsuit sprite (in wizden atleast) is kinda bulkier than the merc hardsuit, so i edited values to be a bit higher for armor protection, but slightly lowered rad protection and it makes you a bit slower than the merc hardsuit now. also changed the helmet light to be less-shit, and increased mat cost by 250 steel and 500 plasteel

**Comment by dvir001** [comment]
Please do not power creep armor
Keep it the same as the other one its based on by parenting.

I'm still waiting for a project art decision if we even want a recolor of the ugly HOS armor in the game.

**Comment by starch70** [comment]
ok, i will revert the stats

**Comment by starch70** [comment]
i have only now realized that the crate i made for this doesnt actually exist for some reason and isnt even in the entity spawner im gonna try to fix this when i get home

**Comment by starch70** [comment]
This shit sucks i cant bear the weight of this anymore im closing it and deleting the branch lol

**Pull request closed without merging**
