### PR TITLE
Magnet

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Code cleanup
Added magnets to all the bag belts (SO now Mail, Chems, Books bags also have magnet code)

## Why / Balance
Just adding on top of the magnet system, and cleaning the code work.

## Technical details
.yml
C#

## Media
- [X] this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by RealIHaveANameOfficial** [comment]
Does this fix the prediction/repeated collection error?

**Comment by dvir001** [comment]
> Does this fix the prediction/repeated collection error?

The visual issue?

**Comment by McBosserson** [comment]
Magnet for generators:
Will this prevent us from unloading the fuel?

**Comment by RealIHaveANameOfficial** [comment]
> > Does this fix the prediction/repeated collection error?
> 
> The visual issue?

Yeah, the issue where ore looks like it gets collected, but then reappears at its original location.

**Comment by dvir001** [comment]
> Magnet for generators: Will this prevent us from unloading the fuel?

Yes its an issue, removed it from this PR

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
