### PR TITLE
Separate Frontier and NFSD banks, sector-wide bank access, revamp the Station ATM UI

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Separates out the Frontier and NFSD bank accounts.  Extends the BankSystem with function to access sector-wide bank accounts.  Most sources of money were moved to only deposit to the Frontier bank account, and bluespace events were changed to pay out the NFSD account.

Also reworks the Station Administration console UI.  Adds a separate Withdraw and Deposit sections.

I've left all of the odd taxation sources (vending machines, black market shipyard purchases, black market ATM deposits/withdrawals) going into the Frontier Outpost, this might be a good time to revisit these.

The overall goals of this PR are to give Frontier Staff and NFSD rewards only for relevant activities - good mail performance should not lead to NFSD-wide raises.

Did a bit of cleanup to the MailSystem while I was there, suppressing C# warnings.

**NOTE: whatever the outcome of this PR, we need to make sure the NFSD and Frontier accounts can support minimal staffing requirements without shortages.**  Larger amounts of staff should require competent gameplay to ensure adequate funding for pay.

## Why / Balance

With this set of changes, it becomes possible to put a station admin console on the Bottleneck, Wasp, and Empress (didn't do this yet) - the Sheriff and Station Rep gain some autonomy and are less tied to their stations proper.  Should help for more off-station gameplay.  Payments to Big Ed's Power Plant can be put into a separate account.  This should allow better granularity for any additional accounts needed in the future.

## How to test

TBD - deposits and withdrawals from NFSD and Frontier consoles should be independent.  NFSD and Frontier accounts now have differing ticker rates.

## Media

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The Frontier and NFSD accounts can now be accessed off-station through station admin consoles.
- tweak: The Station Administration UI has been reworked.

### CODE REVIEW

**Comment by whatston3** [comment]
Marked as draft, my mistake.  Works as-is, but values may need tweaking.  A mail metrics-like ledger and end of round stat collection would be nice to have.

**Comment by Erol509** [comment]
Im affraid of not being able to pay all people, since events are sherrif locked. Yes, you need one to get paid, but joining late and seeing merly enough pay to supply one full shift worker or two is concerning. 

Would there be a way to implement a recompensation system, which gives at least 400k cash?

**Comment by dvir001** [comment]
> Im affraid of not being able to pay all people, since events are sherrif locked. Yes, you need one to get paid, but joining late and seeing merly enough pay to supply one full shift worker or two is concerning.
> 
> Would there be a way to implement a recompensation system, which gives at least 400k cash, in case there is not enough to support people in department?

We call it Ahelp

**Comment by whatston3** [comment]
> Im affraid of not being able to pay all people, since events are sherrif locked. Yes, you need one to get paid, but joining late and seeing merly enough pay to supply one full shift worker or two is concerning.

You have enough, hourly, by default, _without events_, to cover the minimum wage of the default staff of the NFSD less the sheriff.  This is not an issue on the current head of the branch.

**Comment by whatston3** [comment]
Added a ledger at [whatston3:2024-10-30-banks-ledger](https://github.com/whatston3/frontier-station-14/compare/2024-10-23-banks...whatston3:frontier-station-14:2024-10-30-banks-ledger?expand=1).  Modelled largely on the mail metrics app and the logistics stats service backing it, this adds a PDA app (suitable for top-ranking command [currently, SR, Sheriff] use) to view the state of all sector bank accounts at a glance.

Could use a bit of polish, particularly on the blasted PDA app, but if this was hooked into the end of round Discord bot, being able to get an end-of-round summary of all sector bank accounts, their balances, and a breakdown of where their money comes from would be useful.

Interface on current MVP shown below.  Top picture shows a shorter list of ledger items, bottom shows the picture with more income line items than will fit on the screen.
image
image

**Comment by Cheackraze** [comment]
As dvir said, theres always Ahelp. And, in fact, when this eventually does make it live,, we will likely give our whitelisted players a heads up and remind them that admins are always willing to help provide legit payroll, especially during changes/balance periods.

**Comment by whatston3** [comment]
Merged the ledger in this branch, current head looks like this.
image

Sector bank and ledger components were merged (avoiding initialization order issues, and combining the interface - all sector deposits now require a reason along with their amount and account, but generate a ledger entry automatically).  The LedgerSystem has been included into the BankSystem as a result.

All Bank systems are now namespaced under _NF.

**Comment by Cheackraze** [comment]
who has access to the ledger? I think so long as only SR/Sheriff can view the ledger, this should be good to go

**Comment by Cheackraze** [comment]
actually, we should have a way to split percentages to different departments, like 5% of vending machine sales goes NFSD, 10% to Frontier, etc.

**Comment by whatston3** [comment]
Added a printout for the ledger summary at round end.  This little test comes out at about 650 characters accounting for formatting, plenty of room to spare for extra info.  It's currently using the same webhook URL as the bank printout.
image

Assets added for ledger cartridge and PDA app icon.
image

**Review by dvir001 — APPROVED** [review]
Its working alright, didnt find anything weird.

We will need support for filter some of the SectorBankAccount in the case we add a pirate / syndicate one etc, so you can have a PDA only show the ones relevant to it, this is out of scope for this.

**Pull request merged**
