### PR TITLE
STC QoL Update

### PR DESCRIPTION
**Pull request by Kesiath**
## About the PR
Renames the docks to have the proper naming scheme, no more vague docking instructions! Also changes the bridge access requirement to 'command' access, and the shuttle console in the bridge up to 512 radar distance. Additionally, role timers were adjusted to combat griefing issues.

## Why / Balance
Over due quality of life change.

## Media
image

**Changelog**
:cl:
- add: Added the Station Traffic Controller access and job.
- add: Added the STC, Sergeant, Cadet, and Mail Carrier jobs as late-join hirable roles for the STC.
- tweak: Changed the bridge access to be restricted to frontier command instead of SR access.
- tweak: Changed the shuttle console in the bridge to a higher radar resolution.
- tweak: Changed most job playtime requirements to 3 hours.
- fix: Fixed missing dock labels on Frontier.

### CODE REVIEW

**Comment by Cheackraze** [comment]
you are aware that 'command' access is going to include CEs, CMOs, RDs, and similar? Its not really used as an access right now, we might want to make sure its still secure

**Comment by Kesiath** [comment]
Ah, I forgot those roles would be able to access it still. Since SR is whitelisted it's probably ideal to not hand out the access to that role anymore and a command restriction would be better, could we remove command access from those other roles?

**Comment by Cheackraze** [comment]
yes we could, alternatively we could make a new secure door prototype that is strictly SR and Sheriff only accessible and keep command how it is, I could still see command access being useful for general population ships somewhat.

**Comment by Kesiath** [comment]
A little rough around the edges, with a lack of actual STC gear and no round-start slot, but I figure the SR will just hire the STC each round. Door access to the bridge was changed to 'Frontier' access, which is the STC access, and both the Sheriff and SR have the same access.

**Comment by Kesiath** [comment]
Added Sergeant and STC to the jobs listing for the station for SR to use.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
