### PR TITLE
Caduceus Hospital ship

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About the PR

Adds the NM Caduceus; A large Medical ship equipped with cloning, cryo, a stasis bed, virology, surgery. Capable of acting as a mothership to a pulse, It fills the missing role of a large class Medical vessel, currently priced at 105k, though subject to change.

## Media

image

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Caduceus Large medical ship

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Note to self: Might require a few more defibs placed on walls, given the Helix has like.. 6 onboard...

**Review by YumiGumi — APPROVED** [review]
As a CMO, I have personally thought to myself that having a mobile hospital would be a much needed addition as there is currently no large class medical ships. While I don't have a good eye for missing components, or other such necessities, I would love to see the Caduceus in game and I find the design of this vessel very appealing.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
- Ship has 740 Tiles, this ship falls in the Medium category.
- AME is unpowred on init, you should at least put one fuel in the AME and put the correct power setting on init (and i suggest to remove also the AME Fuel Crate as we encorage peoples to buy supplies)
- Missing LateJoin Spawn Point
- Grid Appraised at 87272, your current price is 80000, change your price up!
- Power Monitor Console on the bridge is unconnected, for those to work they need an HV Cable under it.
- Cloning is unconnected, connect before map init or leave a Multitool/Link Device.

Suggestions:
- Both engineering sides has airlock with no tiny fans, open it and experience pain!
- Hallways and a lot of rooms feel extremly emtpy, i suggest putting more props/decals, trees, ect... tho keep in mind that hallway should have a bit of space for moving medical things.
- Medical Interns is a job not really used, unsure if its would work but its wont hurt to try.

**Comment by RadiantFlash7** [comment]
> * Ship has 740 Tiles, this ship falls in the Medium category.
> * AME is unpowred on init, you should at least put one fuel in the AME and put the correct power setting on init (and i suggest to remove also the AME Fuel Crate as we encorage peoples to buy supplies)
> * Missing LateJoin Spawn Point
> * Grid Appraised at 87272, your current price is 80000, change your price up!
> * Power Monitor Console on the bridge is unconnected, for those to work they need an HV Cable under it.
> * Cloning is unconnected, connect before map init or leave a Multitool/Link Device.
> 
> Suggestions:
> 
> * Both engineering sides has airlock with no tiny fans, open it and experience pain!
> * Hallways and a lot of rooms feel extremly emtpy, i suggest putting more props/decals, trees, ect... tho keep in mind that hallway should have a bit of space for moving medical things.
> * Medical Interns is a job not really used, unsure if its would work but its wont hurt to try.

Medical interns are kinda unused yeah, But I feel like if someones new to the server and wants to try medical... well, easy job slot! ((Engineering fans is a bit of an oversight on my part. They had them originally, but I had to redo the entire map minus the flooring cause the save bugged out and deleted /everything/ but the floor tiles.))

Is there anything you reccomend for props/ decorations? I was thinking of putting some stuff in the center of the hall by chemistry/CMOs office, maybe some stuff along the sides at the docking arm...

As for the rest, I can fix just about all of that, except the medium category.

**Comment by Temoffy** [comment]
Might want to add a grinder, knife, water tank, and a cooking vend or manual supplies to botany. You don't really have a way to cook what you grow.

**Comment by RadiantFlash7** [comment]
> Might want to add a grinder, knife, water tank, and a cooking vend or manual supplies to botany. You don't really have a way to cook what you grow.

It has the same amount of supplies as the empress. It also has a sink for water ,and they can use the chemistry grinder in a pinch. We've got a microwave as well. I don't want this ship to be able to replace dedicates growing ships for food, You know?

**Comment by Kesiath** [comment]
> * Ship has 740 Tiles, this ship falls in the Medium category.
This exceeds 32x32 in both directions, the tile count is the maximum guide, not definitive. This is comfortably a large ship.

I like the ship a lot for the most part, although I feel like the current state of Frontier might not be too incredibly suitable given the lack of depth to the medical system. I think you should alter your dock layout since the dock is super recessed into the design. The ship's shape itself is very neat. Good work on this.

**Comment by RadiantFlash7** [comment]
> > * Ship has 740 Tiles, this ship falls in the Medium category.
> 
> This exceeds 32x32 in both directions, the tile count is the maximum guide, not definitive. This is comfortably a large ship.
> 
> I like the ship a lot for the most part, although I feel like the current state of Frontier might not be too incredibly suitable given the lack of depth to the medical system. I think you should alter your dock layout since the dock is super recessed into the design. The ship's shape itself is very neat. Good work on this.

The dock on the back is more for a pulse then docking proper. It actually has two primary docks at the 'front' on either side of it.
The lack of surgery of virology systems in game isn't an issue. I figure the ship can have the stuff needed so when it does get added in, It's already got space for it on the ship!

The main treatment area is already a step up from the Helix which was kind of the main goal. As well as running on AME's, so I don't need to constantly get plasma for the hungry helix. having a small hydroponics area is mostly just a bonus that comes with being a ship so large.

**Comment by RadiantFlash7** [comment]
My current concern is in my attempt for aesthetics, I may have made it too manueverable/accelerateable. Theoretically I could get the Caduceus  down to a single core of AME power supply by drastically reducing thrusters, but I'll leave any actions on that up to whoever reviews this proper.

**Review by FoxxoTrystan — APPROVED** [review]
All issues as been fixed except for the Category, Tiles numbers is still 740 and should fall in "Medium" category.

**Comment by RadiantFlash7** [comment]
> All issues as been fixed except for the Category, Tiles numbers is still 740 and should fall in "Medium" category.

I was told the tile by tile was the ship size control, and the tile amount is only the maximum you can have for that class, per kesiath's comment.

**Review by Cheackraze — APPROVED** [review]
since it does extend quite a bit past one of the 32x32 dimensions, i would also classify this as large.  The classification system is just a touch subjective any how.

**Pull request merged**
