### PR TITLE
Adds a Wallmount Nitrogen Locker and Combined O2/N2 Emergency Lockers

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Added a wallmount N2 locker as this variant was not available, also added a combined o2/n2 emergency locker and wallmount.

## Why / Balance
We have a wallmount O2 locker, so why not have an N2 locker as well? 

25/08:
Now also adds combined emergency closets! These include the emergency suit and have the chance to give the bonus toolbox, airloss medkit, larger tanks and flare gun as the original closets.
Still including the N2 locker as it would feel weird to have the combined locker, the o2 locker and no n2 locker. 
If this is merged I imagine the combined lockers becoming the standard, so I can always remove the n2 locker from this PR. 

Increased friendliness to Slime people and Vox, yay!

29/08:
Combined lockers are now 'Emergency Internals Closet'. Much better name.
Fills were moved into the fills dir.

## How to test
Checkout the branch, load up and spawn the objects. 

## Media
Overview

2024-08-25 16_15_06-Frontier Station

2024-08-25 16_17_20-Frontier Station

2024-08-25 16_17_36-Frontier Station

2024-08-25 16_18_42-Frontier Station

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None!

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added combined o2/n2 closets and a n2 wallmount.

### CODE REVIEW

**Comment by whatston3** [comment]
Could this not be added to the O2 locker instead?  Maybe resprite the door if needed?

**Comment by Tych0theSynth** [comment]
> Could this not be added to the O2 locker instead? Maybe resprite the door if needed?

I'm not sure I understand what you mean. 
The colours are completely different across sprites, including with the fullsize lockers.

**Comment by ErhardSteinhauer** [comment]
You can look at [# Fuel / materials storage section in this file](https://github.com/new-frontiers-14/frontier-station-14/blob/master/Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/wall_lockers.yml) and make your empty locker with minimal spriting: you'll have to add sprite for "n2" decal in corresponding rsi folder and link it.

**Comment by whatston3** [comment]
> > Could this not be added to the O2 locker instead? Maybe resprite the door if needed?
> 
> I'm not sure I understand what you mean. The colours are completely different across sprites, including with the fullsize lockers.

Why not have one "air/breathables/internals/etc." locker with essentials for species-independent breathing?  It's not about the sprites.

**Comment by Tych0theSynth** [comment]
> > > Could this not be added to the O2 locker instead? Maybe resprite the door if needed?
> > 
> > 
> > I'm not sure I understand what you mean. The colours are completely different across sprites, including with the fullsize lockers.
> 
> Why not have one "air/breathables/internals/etc." locker with essentials for species-independent breathing? It's not about the sprites.

OH. You're talking about making a combined locker that just contains everything? 
Yeah. That can be done.

**Comment by Tych0theSynth** [comment]
Converting to draft while I work on the combined locker and bundle it in with this.

**Comment by Tych0theSynth** [comment]
I think I'm there with this one. Ready for review now.

**Comment by Tych0theSynth** [comment]
> Small set of suggestions up here: [whatston3:frontier-station-14:2024-08-28-wallmountn2-suggestions](https://github.com/Tych0theSynth/frontier-station-14/compare/wallmountn2...whatston3:frontier-station-14:2024-08-28-wallmountn2-suggestions?expand=1)
> 
>     * I've pushed the fills to the fills folder.  I've left the nitrogen one as its own fill instead of reparenting the existing standing nitrogen closet.
> 
>     * I think the term "emergency internals closet" works better than "emergency nitrogen and oxygen closet", matches with the "internals crate".
> 
> 
> Curious of your thoughts, otherwise this looks good.

This looks great, and the name change makes so much more sense and is far more concise. 
I'll take a proper look tomorrow but chances are I'll merge this into it! Cheers!

**Comment by Tych0theSynth** [comment]
Tested and working with some good adjustments by @whatston3. Good to go!

**Review by whatston3 — APPROVED** [review]
Made a small change adding an attribution to the standing lockers and renaming the nitrogen wall locker to match.  Looks good to me.

**Comment by whatston3** [comment]
Going to fix up the weld sprites on the wallmount versions, will pull from Erhard's wall lockers, they look pretty good.

**Comment by whatston3** [comment]
image
image

Finagled it a bit, looks like this now, I think it's an improvement.

**Comment by Tych0theSynth** [comment]
Yeah that's an improvement for sure!

**Pull request merged**
