### PR TITLE
RCD can deconstruct the more common walls/window

### PR DESCRIPTION
**Pull request by VividPups**
New wall destructions

## About the PR
adds more things to deconstruct on the RCD 
## Why / Balance
Request and its really annoying spending like 40 mins wacking at a wall just to remove it.  
I believe it would be ok since now it require the Captain ID to used the Shipyard RCD
## How to test

wall  plus RCD  together

## Media

- [X] this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The RCD can now deconstruct shuttle walls, shuttle windows, and most diagonal walls.

### CODE REVIEW

**Comment by dvir001** [comment]
Changelog need to be more clear, missing ``# Frontier`` comment on all the added lines

**Comment by VividPups** [comment]
> Changelog need to be more clear, missing `# Frontier` comment on all the added lines
> 
> Also note parenting that wont need to be added 2 times.

Huh?

**Comment by VividPups** [comment]
@dvir001 I believe I added all the tags

**Comment by whatston3** [comment]
https://github.com/VividPups/frontier-station-14/compare/RCD-change...whatston3:RCD-change-suggestions?expand=1

All deconstructable walls (diagonal or not) are 6/8 - added girders at 4/4 (happy to discuss this but it should maybe have less material than a grille - how thick are the grilles vs. the beams in the girder?  Single layers of fence?).  Seems more reasonable to me at any rate - existing deconstructable diagonal windows have the same cost as their non-diagonal versions.

Plastitanium walls and windows are still not deconstructable, and uranium and plasma windows have been left as RCD resistant (no idea why, the base walls are already deconstructable).

**Review by whatston3 — APPROVED** [review]
Without feedback, I pulled my changes in, seems reasonable.  Plasma and uranium windows are still not deconstructible, shuttle walls should be made constructible as well, but that's outside of the scope of this PR for now.

Would appreciate a second set of eyes on this, but it seems alright to me.

**Pull request merged**
