### PR TITLE
Mining, materials rework

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

WIP of a material/asteroid value rebalance.  Needs some tweaking and fiddling.

Goals are to have approximately equal value per tile between asteroid types, removing incentives behind making reinforced X glass (preferring more useful, base materials that other players can use).

## Why / Balance

Mining bad, make mining good.

## How to test

Very carefully.  WIP.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

WIP

### CODE REVIEW

**Comment by GreyMario** [comment]
My immediate knee-jerk reaction is "raaaagh mining profit nerf!!!" which sure, fine, whatever, omlette, eggs, but where do we strike _that_ balance? What has to happen to make "mining for general resources" a reasonably viable career without creating an environment where people will just go mine their own resources because it's plentiful?

I'm curious about the effective distribution changes to ores and might make a copy of my asteroid chart to see what happens in a more digestible format.

**Comment by dvir001** [comment]
Change Raw back to 100 and make the ores spawn more ore per rock and I'll merge it

**Comment by GreyMario** [comment]
> Change Raw back to 100 and make the ores spawn more ore per rock and I'll merge it

I had a thought in this line, actually; improving the ore quantity drops from the "correct" asteroids and the two harder asteroids might be a better way to handle this?

**Comment by dvir001** [comment]
> > Change Raw back to 100 and make the ores spawn more ore per rock and I'll merge it
> 
> I had a thought in this line, actually; improving the ore quantity drops from the "correct" asteroids and the two harder asteroids might be a better way to handle this?
> 
> Like, mining plasma ore tiles from a chromite asteroid could drop more ore than mining plasma ore tiles from a snow asteroid.

Fam this pr is a buff not a nerf

**Comment by GreyMario** [comment]
> Fam this pr is a buff not a nerf

How is "increase the amount of ore drops from the primary ore types found on special asteroids" a nerf

**Comment by dvir001** [comment]
> > Fam this pr is a buff not a nerf
> 
> How is "increase the amount of ore drops from the primary ore types found on special asteroids" a nerf

This PR is already doing this with the balance.

**Comment by GreyMario** [comment]
Actually, it's _sort of_ looking like it's on track to reduce the specialization of asteroids. Give me some time to digest the data as it stands so I can see with my own eyes what's going to happen.

**Comment by GreyMario** [comment]
Just finished picking at the new distribution of ore spawns.

Live ore distribution
image

This PR's ore distribution (as of time of writing)
image

This does reduce the amount of asteroid specialization in some areas, but that's not a bad thing. Coal and iron occur together more often (a big win, going from 3/7 asteroids to 5/7!), and snow-mining scientists are rewarded with a decent chance of gold and silver for crafting. Andesite loses its seat as king of the quartz hill and passes the crown to sand at a slightly reduced rate.

There is a slight overall decrease in ore-containing tiles. Salt and coal see well-needed reductions in average encounter rates. A slight increase in monster tiles has occurred overall, with a more noticeable increase in snow and andesite.

Diamond frequency has been halved in its relevant asteroid, but reinforced uranium glass crafting comes back with a _vengeance_ with only a very tiny price nerf and adding a potential requirement to stop at sand asteroids to prevent glass from being a bottleneck.

The price change to reinforced uranium glass doesn't strike me as significant enough to counter the incidental pickup of diamonds that will occur while mining andesite for steel. As a result, at the time of writing I expect this would actually result in a buff to mining for profit.

**Comment by whatston3** [comment]
Made a set of revisions, I think this is more or less good to go.

* Most ore now drops in stacks of 5 apart from diamonds, artifact fragments, and bluespace crystals.  The max stack size for these has been increased to 100 to compensate somewhat for material density.
* The value of composite materials like plasteel, and of composite or reinforced glass has been reduced to 80% of the sum of the components' cost.  This should reinforce miners selling either raw ore (without any major penalty, and at the potential buyer's gain) or refined base materials with upgraded ore processors.
* The base ore processor no longer processes materials into composite or reinforced glasses (now noob traps) - this has been kept in the industrial version for simplicity's sake - if somebody's running a combination mining and engineering shuttle, go nuts, use the industrial processor - the thought is that somebody that has one of these has a better idea of what they're doing than the average base ore processor enjoyer.
* The engineering techfab now has recipes for making composite materials and reinforced glass out of sheets.  These do not apply a discount - there should not be a meta of double dipping discounts to get a push button process to further refine materials into things nobody wants to buy.
* The plasteel recipe has been removed from the autolathe.
* All recipes from techfabs for making sheets of glass from ore were removed - they were unresearchable and as far as I can tell, unusable because of the whitelist in the fabs.
* The expected value of the refined material in an unupgraded lathe is about 60 spesos per tile on each asteroid, and this is roughly flat between all existing asteroid types.  Clear cutters will benefit from visiting the closest rocks to them, and pick-and-choosers can still hunt for particular asteroid types with the minerals they're looking for.

Might make a mining guidebook entry, might make a "materials" category for the engineering techfab, but apart from that, this seems good.

**Review by dvir001 — APPROVED** [review]

**Comment by GreyMario** [comment]
stack size to 100 hell fucking yes, this was something I thought could help compensate for One Ore One Sheet

Any further change to asteroid composition?

**Comment by whatston3** [comment]
> Any further change to asteroid composition?

No.

**Pull request merged**
