### PR TITLE
Fix EVA suits errors and suit fills

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Removed HandheldGPSBasic to remove some bloat and help with overfills
Added some of the cool magboots back
Cleaned other issues

Part of https://github.com/new-frontiers-14/frontier-station-14/pull/2209

## Why / Balance
Cleanup

## How to test
N/A

## Media
N/A
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
Not sure if removing gps from lockers is a right move to combat the bloat. I feel like the most useless item in suit locker fills is air tank - it's filled with air mix (which doesn't universally work for all species), it's troublesome to refill it with anything but air (there almost always some lingering moles left in tank when it's "empty", and gas mixes work weird if you're trying to top it off with oxygen), it is 2x2 item and you always start with either emergency tank or double emergency tank. You don't start with gps unless you take it (and there are other more appealing options in that menu).

**Comment by ErhardSteinhauer** [comment]
Also I removed most of the flashlights from departmental eva fills in [this PR](https://github.com/new-frontiers-14/frontier-station-14/pull/2163) which solves that one error with overfilling.

**Comment by dvir001** [comment]
GPS moving to PDA app, let it die here.

**Comment by ErhardSteinhauer** [comment]
Fair

**Comment by dvir001** [comment]
> Fair

Honestly the astro app should be a pre install on all PDA, it's not even conflicting with anything.

This PR also fix other issues related to storage errors.

**Comment by ErhardSteinhauer** [comment]
> Honestly the astro app should be a pre install on all PDA

Facts.

> it's not even conflicting with anything

I think there is a limit on how many apps you can have in your PDA. Should be fixable though.

**Comment by dvir001** [comment]
> > Honestly the astro app should be a pre install on all PDA
> 
> Facts.
> 
> > it's not even conflicting with anything
> 
> I think there is a limit on how many apps you can have in your PDA. Should be fixable though.

It's set to 10 on frontier from upstream 5

**Review by ErhardSteinhauer — APPROVED** [review]
Let it be known, that Darin swore on his legs that he'll add GPS app for PDAs today.

**Pull request merged**
