### PR TITLE
Vagabond (New) - Long-Haul Freighter [Updated]

### PR DESCRIPTION
**Pull request by MoistBiscuits**
## About the PR

Adds the medium-sized ship called the Vagabond, a modular long-haul freighter geared toward player remodeling and adaptation. Created by @DustScoundrel from #694, this pull request aims to make the changes requested to the original design and to adhere to the new shuttle guidlines, so that this great and nearly complete shuttle can still be added in the abscense of it's creator. 

## Why / Balance

- Added missing plastic flaps by dock doors
- Added an extior support beam to connect engi and cargo bay
- Changed second captains suitlocker to a QM one
- Adjusted atmos distro and paired scrubbers
- Added gas canisters for the air mix
- Removed the mapped disabler
- Added a salvage vend
- Added a small amount of decal work to some of the emptier sections
- Reduced buy price to 60,000 (sells for 48546)

## Technical details

n/a

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Vagabond medium freighter

### CODE REVIEW

**Comment by MoistBiscuits** [comment]
I have tried to keep the changes minimal to what is required as to try and preserve the original creators concept, Please let me know if the shuttle needs futher changes

**Comment by MagnusCrowe** [comment]
image
Can't get to the couch.
Can you feng shui the breakroom a little?
Please drop all the cigs.  If people want to smoke, they will bring their own.
Can you replace the booze dispenser with a water cooler please?

image
Please do not run wires under walls like the HV and MV in this picture.
I am not a fan of having wall mounted substations on such a large station, there's plenty of room for a normal substation in the engineering room.  If you really want two substations, you can configure them like this and they will remain centralized and be split between powering the front and back of the ship.
image

image
Replace all the diagonal solid walls with diagonal reinforced walls.

image
Not a big fan of the look of these engines, they look sorta like an afterthought that got tacked on.
There are little nooks that can be used as thruster housings...
image
You might have to massage the shape of the ship to enable this next suggestion, but you can build cowling around engines or set them into walls to make them look like they were installed into a hull that was designed to house them, instead of welded to the outside.
image

**Comment by MoistBiscuits** [comment]
Thank for the reply, Suggested changes are even more helpful for me since I never got a chance to talk to the original creator, Ill get on them as soon as I can!

As its another issue I was not sure on, what the oinion on the mappped donk pockets and fridge full of drinks? There has been a big push to make sure that service has relevence, but I've seen donk pockets mapped on other shuttles so Im not sure if they can stay.
image

**Comment by dvir001** [comment]
> Thank for the reply, Suggested changes are even more helpful for me since I never got a chance to talk to the original creator, Ill get on them as soon as I can!
> 
> As its another issue I was not sure on, what the oinion on the mappped donk pockets and fridge full of drinks? There has been a big push to make sure that service has relevence, but I've seen donk pockets mapped on other shuttles so Im not sure if they can stay. image

I say leave for now till we finalize it, but replace soda with booze machine

**Comment by MoistBiscuits** [comment]
Made the requested changes, would love for another review or any further suggestions from anyone else.
image

**Review by MagnusCrowe — APPROVED** [review]
Looks good to me.

**Pull request merged**
