### PR TITLE
Placebo Psychologist Ship

### PR DESCRIPTION
**Pull request by NkoKirkto**
## About the PR
Addes the Placebo a small Psychologist ship.

## Why / Balance
No psychologist ship so i made one.

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Added the Placebo a small Psychologist ship.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
I recommend adding decals to make your ship come to life a bit more, especially in the lobby section and the bridge of your ship. For the rest, this PR looks technically sound. Was not able to evaluate this at all in-game at this time.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
You need a couple tiny fans on your dock.

image
You might not want a button that will allow someone to lock you in your cockpit...

image
You should put plating and grille under this dock window to remain consistent with the other windows.

You should add a couple emergency lights.

You must replace the warp point with a ship warp point.

**Comment by NkoKirkto** [comment]
Will do as soon as i come back home. The idea of the button was so nobody can get in while sombody is in the therapy room but makes sense i will unlink it from the cockpit door.

**Comment by MagnusCrowe** [comment]
> Will do as soon as i come back home. The idea of the button was so nobody can get in while sombody is in the therapy room but makes sense i will unlink it from the cockpit door.

If you're planning on hiring a pilot you might want to connect the cockpit to the lobby as well, or instead.

**Comment by NkoKirkto** [comment]
> > Will do as soon as i come back home. The idea of the button was so nobody can get in while sombody is in the therapy room but makes sense i will unlink it from the cockpit door.
> 
> If you're planning on hiring a pilot you might want to connect the cockpit to the lobby as well, or instead.

Not really planning should be more of a stationary ship that is docked at the fronteir or a medical mother ship.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
