### PR TITLE
NSF Broadhead v1.1

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Based on some feedback, I've done a small update pass on the Broadhead to hopefully fix a couple of issues.

## Why / Balance
Visibility out of the cockpit was TERRIBLE, there's no denying that. I knew it would be when we designed it. 
Also, the front of the cockpit is a great 'net' for capturing things that might want to kill you. It was a bit weak.

Changes:
- Replaced exterior windows with plasma glass.
- Cockpit windows now have blast doors.
- A camera network has been added providing both interior and exterior cameras for better visibility in and around the ship.
- Mass scanner console was replaced with the longer range advanced radar.

## How to test
Buy it and have a look!

## Media
Broadhead Updated

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None, I hope!

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Applied some updates to the NSF Broadhead.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
Update:
Somehow the thrusters were still security thrusters. I think I had brainfart. Fixed now. (coulda sworn I did this shit in the original PR)
- Correct thrusters in place.
- Correct gyro.
- IFF console moved to the det's office. 
- Station records computer moved to the break room.
- Camera monitor is now tabletop and on the cockpit so you can use it while flying (the wallmount ones are shit).

**Comment by dvir001** [comment]
@Tych0theSynth Please merge upstream into this PR

**Comment by Tych0theSynth** [comment]
> @Tych0theSynth Please merge upstream into this PR

Done. Also committed some more changes.
New screenshots:
2024-07-04 21_27_23-Frontier Station

**Review by dvir001 — APPROVED** [review]
All good

**Pull request merged**
