### PR TITLE
PTS (Update)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Updating Personal Transport Shuttle to current mapping standards:
- Wiring rework.
- Atmos rework.
- Replaced consoles with tabletop variants.
- Added Vacuum Markers to exposed to space tiles.
- Separated engine from passenger area.
- Removed intercom.
- Enabled Pilot Job.
- Replaced gyro with minigyro.
- Moved ship.yml to Maps/_NF/Shuttles/

## Why / Balance
New mapping standards.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated PTS to current mapping standards.

### CODE REVIEW

**Comment by dvir001** [comment]
Weird intercom in bridge room placement and anyone can just walk to engine area but this issues been like this before
This is fine by me but im leaving this to @MagnusCrowe to give his final approve

**Comment by dvir001** [comment]
Might be wrong version, missing new engine area

**Comment by ErhardSteinhauer** [comment]
Fixed

**Review by dvir001 — APPROVED** [review]
Gave me PTSD

**Pull request merged**
