### PR TITLE
feat(posters): Magnus poster

### PR DESCRIPTION
**Pull request by exincore**
## About the PR

Adds a new legit poster based on lobby art.

## Why / Balance

Lobby art lore! Magnus lore!

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

nf_poster1_legit_scaled
> Always Watching
> This poster depicts an ethereal judge. You think you hear a 'BWOINK,' but it is just your imagination, right?

Screenshot_20240313_061151_cropped

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by exincore** [comment]
Whether this poster should appear as legit on Frontier Station or as contraband in maintenance (or sometimes dead drops) is still malleable.

**Comment by exincore** [comment]
Legit poster for now. Easy to change.

**Comment by VividPups** [comment]
Hey, Dont forget about the random Poster Spawners

**Comment by exincore** [comment]
> Hey, Dont forget about the random Poster Spawners 

Random poster spawner picks from random legit spawner and random contraband spawner, so no change is necessary there.

**Comment by MagnusCrowe** [comment]
> Whether this poster should appear as legit on Frontier Station hallways or as contraband in maintenance (or sometimes dead drops) is still malleable. Magnus suggests having it both legit and contraband, which has not been done before, so I leave this as draft until there are more opinions.

image
I thought you meant deaddrop poster when we talked. Was I right?

**Comment by exincore** [comment]
> > Whether this poster should appear as legit on Frontier Station hallways or as contraband in maintenance (or sometimes dead drops) is still malleable. Magnus suggests having it both legit and contraband, which has not been done before, so I leave this as draft until there are more opinions.
> 
> 
> 
> image
> 
> I thought you meant deaddrop poster when we talked. Was I right?

No, sorry, I should have been more clear.

"Legit" posters are approved by NT for display in stations, and may appear in hallways.

"Contraband" posters are not NT approved and may appear in maintenance areas.

"Dead drop" posters are randomly selected from the "Contraband" posters.

**Review by Cheackraze — APPROVED** [review]
I approve if @MagnusCrowe does

**Pull request merged**
