### PR TITLE
Medical hud

### PR DESCRIPTION
**Pull request by rbertoche**
Cherry picked working Medical Hud overlays from PrPleGoo, no original changes made

took from his PrPleeGoo/task/medical-hud branch after seeing it on some PR

well the one change for now is adding a now missing using for Vector2

### CODE REVIEW

**Comment by rbertoche** [comment]
image

**Comment by rbertoche** [comment]
tested just fine

**Comment by dvir001** [comment]
If this is coming from upstream we should wait for the actual update for this.

**Comment by rbertoche** [comment]
Why? worst case scenario, this diff gets thrown away tomorrow with the official rewrite/implementation
but it may not be on upstream that soon since it was PRed in july and didn't get in

**Comment by dvir001** [comment]
> Why? worst case scenario, this diff gets thrown away tomorrow with the official rewrite/implementation I'm not in any way making it look like I've done it, and it was made public by the author themselves. I see nothing wrong with having upstream stuff which wasn't merged before merged here, it may not be on upstream that soon since it was PRed in july and didn't get in, but if they do add it, then great, everyone will have it.

It didn't get in for having issues and possibly still has some, were in no real rush on it if it will be coming down the line.

**Comment by rbertoche** [comment]
what issues? the only issues I saw being mentioned on the PR were about naming convention, which technically don't cause any runtime issues, weird behavior or bugs

**Comment by Cheackraze** [comment]
was this one the exposed dev overlay or is this the actual working one, I'm willing to nab this one early and squash commit, then revert once upstream gets it. I think it would go a long way to helping med gameplay if they can patrol and just, *see* when people need help.

**Comment by potato1234x** [comment]
the health bar sprite looks bad as white on green

**Comment by rbertoche** [comment]
I am not sure if it's dev overlay or not but it's one which allows you to see people in lockers. Let me see if it's obviously different in any way from dev overlay

**Comment by rbertoche** [comment]
it's a white border gray background. It does read well on both dark and clear backgrounds 
maybe white comes from it being med stuff but I'm not sure

**Comment by rbertoche** [comment]
It looks exactly the same as dev overlay but it doesn't show people behind walls, only inside lockers.
But it's not the dev overlay, it just uses the same sprites, it has its own draw code for instance.
Now I fixed it so it doesn't show people inside containers, so trash cans, etc

**Comment by rbertoche** [comment]
by the way. From personal experience from playing in nyano, probably the dev overlay you are mentioning. It did a _lot_ of difference. Most times you don't even need a scanner, you usually have some cue for what hit the person and only have to scan when you see they have no bruises to check if it's poison or rad, or to be sure they have enough blood and won't die from it.
yeah in frontier medics get a harder time since a lot of players rather not visit them apparently, so knowing upfront who needs them and how much will probably be nice
cheers

**Comment by rbertoche** [comment]
there's a new branch for that from PrPleGoo pending merge. I drafted this and will check on that instead, to see if it's worth it to drop this one. I was already using this, so I was unaware of another PR.

**Comment by rbertoche** [comment]
So, I cherry picked the new branch, but that branch was merged with upstream at a changeset from 20 august. In order to get that cherry pick working I had to merge with the same changeset from upstream. Which did work, but apparently it break the map:

image

I've pushed that attempt anyway since the merge didn't fail that badly, other than for the terminal having missing walls. But it's useless to merge unless the terminal is fixed after that merge with 7d7e71b113 upstream.

Removing draft state, since this is what can work right now.

**Comment by rbertoche** [comment]
this is the other branch with what will most likely get actually merged, but which broke the terminal after merging upstream
https://github.com/rbertoche/frontier-station-14/tree/medical_hud_2

**Comment by rbertoche** [comment]
added these two commits I was unaware of until now

**Comment by Cheackraze** [comment]
ok im going through all the outstanding PRs, whats the status on this? was this merged upstream? I def. want them but I dont want them to conflict or otherwise. If upstream abandoned, im willing to squash merge and have them for now

**Comment by FoxxoTrystan** [comment]
Inst there a version on upstream?

**Comment by dvir001** [comment]
Last version:
https://github.com/space-wizards/space-station-14/pull/21980

**Comment by PrPleGoo** [comment]
it'll be a while

**Comment by dvir001** [comment]
> it'll be a while

If you dont mind and have the time we will like to have it added here if you can port it as a new PR.

**Comment by dvir001** [comment]
With it getting added upstream, im closing this and getting it merged from that repo.
Thanks.

**Pull request closed without merging**
