### PR TITLE
NR-Investigator

### PR DESCRIPTION
**Pull request by UbaserB**
## About the PR

I was wondering why there weren't any salvage/science shuttles that were small enough for one or two people, so i decided to make this one. The NR-Investigator is designed for long trips out in space, mining asteroids for artifacts and researching them to earn money. The difference compared to the Phoenix for example, is that this one has a bar for the crew onboard and is a lot smaller so it's more viable to use for a small crew.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image

**Changelog**

:cl: Ubaser
- add: Added the NR-Investigator, a small salvage shuttle designed for researching artifacts.

### CODE REVIEW

**Comment by Cheackraze** [comment]
error appears unrelated tbh.  Otherwise, i like the design and the decal work is :chefskiss:.  Overall, (in the future), try to aim for less-square rooms, though I do understand it gets difficult with smaller spaces. My only actual critique on it is the airlock 
image
Try to give it a full '2 stage' airlock, this helps engagements between ships much more neutral and helps with ship-ship interaction a ton, having a kind of 'entryway' on ships for players to kind of stand in... its kind of like walking on to your front porch, before ringing the door bell etc.

**Comment by Estataa** [comment]
hey your power setup is a bit funky, also for a ship of its size it should DEFINITELY have a SMES set up.
(made a github account just to say this)

**Comment by Estataa** [comment]
Also another thing to consider would be the science setup, i personally would replace the microwave with a grinder for artifixium, or maybe a circuit imprinter so you can build machines on your scientific/salv vessel.

**Comment by Wolfking6116** [comment]
A grinder seems a bit strong to start with for a ship that's meant to be split between science and salv. The Sparrow doesn't even come with one and it's dedicated to science.

Which direction is intended to be 'forward' for the ship? If it's top-down as forward-back it's odd that it has less thrusters in those directions. 

As far as the power goes... Where you have the Solars they are unlikely to get power very often, as I think ship walls and things can block the directional solar power. You could also make it so the artifact analyzer is unwrenched to start with, to save on power consumption.

**Comment by UbaserB** [comment]
Okay, ill update it shortly. Thanks for the reviews!

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
