### PR TITLE
LVHI Shuttles (Update)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
### General changes:
- Replaced tiny fans with directional fans.
- Reworked decals to be inline with unpublished LVHI style guidelines.
- Made shuttles slightly more friendly to vox/slime: split air canisters into O2+N2 canisters.
- Adjusted price tags.
- Added (and mapped) more station beacons.
- Added (and mapped) more wall lockers.
- Added magboots to salvager EVA locker.
- Added LVHI and Arcadia Industries EVA suits (the latter can be acquired from ArcadiaDrobe). Kind of experimented with stuff.

### Brigand
- Fuel storage now comes with 2 AME jars.
- Replaced salvager hardsuit storage units with mercenary EVA storage units.

### Gasbender
- Added station beacons and station map.
- Fuel storage now comes with 2 AME jars.
- Reduced amount of loose materials.
- Removed dart target and the box with darts.
- Moved defib from the Lounge to the Mess.

### Harbormaster
- Reworked engine room.
- Replaced pilot hardsuit storage unit with pilot EVA wall locker.

### Kilderkin
- Reworked engine room.
- Mapped disposals.
- Mapped jukebox flatpack.
- Changed docking port layout.
- Replaced regular EVA lockers with service worker eva lockers.

### Lantern
- Reworked engine room and morgue.
- Removed sink.
- Mapped chaplain EVA wall locker.

### Legman
- Replaced shuttle walls with reinforced walls.
- Mapped Withdraw-only ATM.
- Added service worker EVA locker.

### Liquidator
- Reworked engine room, mapped uranium fuel locker.
- Added janitor EVA locker.

### Pioneer
- Removed conveyor belt with its controls.
- Changed docking port layout.
- Replaced hardsuit wall storage with salvager EVA wall locker.

### Searchlight
- Replaced one of the stasis beds with medical bed.
- Replaced wall-mounted substation with regular one.
- Changed docking port layout.
- Replaced wall-mounted Nanomed with Nanomed Plus.
- Mapped medical techfab.
- Mapped free (!) medkit and 2 free (!) pill canisters: charcoal and dermalin.
- Replaced wall-mounted paramedic suit storage unit with regular one, mapped additional medical EVA storage unit.

## Why / Balance
Some of the shuttles were outdated, LVHI rebranding update.

## How to test
1. Buy LVHI shuttles from regular shipyard and expedition shipyard.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated all LVHI shuttles: Brigand, Gasbender, Harbormaster, Kilderkin, Lantern, Legman, Liquidator, Pioneer and Searchlight.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
A'ight, I think I'm done fiddling with things in this PR.

**Comment by arimah** [comment]
By updating loads of ships in the same PR, you have unfortunately made this difficult to review. This is not a full review, but I want to comment on the following Brigand change:

> * Added materials wall locker with 10 sheets of glass, steel and plastic.

Why? Expeditioners should have to collect their own materials! It's not like a kitchen with limited ability to get materials. You can map an _empty_ materials wall locker if you want, but don't use a filled variant, please.

**Comment by ErhardSteinhauer** [comment]
> By updating loads of ships in the same PR, you have unfortunately made this difficult to review

True, but then again, I don't feel like making 9 PRs is a right move either.

> Why? Expeditioners should have to collect their own materials!

The idea here is to provide some materials for the crew to print the most basic items (hence the locker with partial stacks) they might not have either because there was no option to obtain them in loadouts or there was no vendomat with tools on a POI they spawned/hired crew: glowsticks, crowbars/multitools and such. Can't collect materials on expeditions if you can't reach the ruins. Sure can jump around and loot wrecks in space or cannibalize the shuttle or starting POI for spare mats, but that feels a bit wrong.

**Comment by ErhardSteinhauer** [comment]
> don't use a filled variant, please.

Ended up removing the locker: 10 steel is not enough for printing even a barebones tool set and I don't want mapping locker variant with more stuff.

**Review by arimah — COMMENTED** [review]
I've looked at these ships on and off for about a month now, and while you have a clear, consistent style, I must confess I'm not as impressed by the near-universal use of dark tile. It looks cool, dark, edgy and stuff, but it leads to a highly homogenous appearance where rooms with different functions are not really visually distinct from each other beyond the colour of the trim.

For example:
* Medical on the Brigand: why _not_ use the white tile that's so strongly established as being the medical colour?
* Engineering on the Harbourmaster and the Gasbender: Why not techmaint or similar? Just a little bit, hiding in a corner somewhere?
* Common room on the Gasbender: Maybe something cosy could work better?

Variety is nice! Basically, avoid this:
image

---

In terms of functionality, I don't have any real issues. I am concerned about the Pioneer having an EVA suit instead of a proper hardsuit. Being basically the de facto newcomer salvage ship, I think EVA may result in more first-timer deaths. They may never even discover they can spend 10% of their starting spesos on a spationaut suit from the AstroVend. Though the Pioneer is meant to be a real cheap ship, its equipment has to match the job it's designed for!

**Comment by ZombieChibiXD** [comment]
I tested it out on my local branch, Gasbender does not have gravity gen.

**Comment by ErhardSteinhauer** [comment]
> I tested it out on my local branch, Gasbender does not have gravity gen.

Good catch, thank you. Fixed now.
Also moved defib to be more accessible.

**Review by arimah — APPROVED** [review]

**Pull request merged**
