### PR TITLE
DeltaV Anti EORG Code & Species vision cvar edit

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
PR https://github.com/DeltaV-Station/Delta-v/pull/350 https://github.com/DeltaV-Station/Delta-v/pull/2070

It was added but its set to false, can be changed by admins to true.

Also https://github.com/DeltaV-Station/Delta-v/pull/1953

## Why / Balance
QOL

## How to test
End the round, try to blowup NFSDO

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: Species vision filters are now disabled by default. You can re-enable them in the settings!

### CODE REVIEW

**Comment by MilonPL** [comment]
you might be interested in https://github.com/DeltaV-Station/Delta-v/pull/2070 if you're porting the EOR pacifism, it can be disabled with a cvar anyways

**Comment by dvir001** [comment]
> [DeltaV-Station/Delta-v#2070](https://github.com/DeltaV-Station/Delta-v/pull/2070)

Added https://github.com/DeltaV-Station/Delta-v/pull/2070

**Review by whatston3 — APPROVED** [review]
Fiddled with the popup layout, looks like this:
image

I prefer "griefing" to "grief", removed all references to "going to Central Command", and changed the title to "Frontier Station".

Seems to work alright.  Opt-in vision filters are nice, but you might get some "what happened to my bad vision". (edit: read the changelog entry, never mind)

**Comment by ErhardSteinhauer** [comment]
Notifications are cool

**Pull request merged**
