### PR TITLE
Merchant Shuttle (For real this time)

### PR DESCRIPTION
**Pull request by AjexRose**
## About the PR
Okay, so after some issues regarding IDE and not getting shuttle to work, the Merchant Shuttle is now ready for inspections. This shuttle, produced by Arcadia Industries, is a expeditions capable shuttle with room for 1 captain, 1 Merc, and 1 cargo tech. It's design is to easily allow players to set up shops for the neat trinkets they find on expeditions. 

edit: Forgot to mention that the items on the racks and the vending machines are random vendors/random maintanence items, so they wont be the same each time. 

**Media**
Merchant2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Arcadia Industries have started selling a new expedition capable shuttle known as the Merchant.

### CODE REVIEW

**Comment by potato1234x** [comment]
why does this shuttle need a whole ass ame and a pretty useless hallway
i'd just remove the hallway and have a generator and the shuttle console in the storeroom

**Comment by AjexRose** [comment]
> why does this shuttle need a whole ass ame and a pretty useless hallway
i'd just remove the hallway and have a generator and the shuttle console in the storeroom

the AME is something I've notice on every expedition capable shuttle, and is something I thought was needed as a standard for shuttles with expedition capabilities. 
As for the hall, I kinda based it off of the sparrow's long hall, but I could probably shorten it by pushing the pilot room lower south.

**Comment by potato1234x** [comment]
Yeah i think 2 generators would be able to power this shuttle

**Comment by AjexRose** [comment]
You think it would work/look better if I moved all the engineering/power to the end of the long hall to shorten it, and move some of the piloting consoles+captain's items in to the old engineering space?

**Comment by potato1234x** [comment]
> You think it would work/look better if I moved all the engineering/power to the end of the long hall to shorten it, and move some of the piloting consoles+captain's items in to the old engineering space?

Yes

**Comment by AjexRose** [comment]
Space Station 14 8_20_2023 6_26_49 PM

New merchant shuttle design with the recommended changes

**Comment by Cheackraze** [comment]
image
so overall I think the design is a bit lacking.  The rooms are all the same shape and orientation, and the ship lacks any kind of identity. Things like more decaling and RP spaces can go a long way, as well as changing up the shapes and sizes of your rooms.  The picture is just an example of maybe how to subdivide the interior a bit better to give it a more unique feel.  If its supposed to be a shop ship, maybe you have a manager's office in the back or something.  The floor tiles as well are mostly the same type between rooms, so knowing what the space is intended for is difficult as well. Things like wooden flooring and more private, sectioned-off bedrooms.

For expeditions, we also kind of hard-require an AME to start the ship off with, and also expect the ship to cost at minimum 50k (and be worth around that as well, according to the shipyard system.)

I think you have a good idea and the start of a decent ship profile going, but it just feels overall empty and simplistic.  Things like wooden flooring and more private, sectioned-off bedrooms.

**Comment by Cheackraze** [comment]
hows this one coming? ready for another review? if you're having some technical issues, feel free to DM me on discord and I should have plenty of time all weekend to assist

**Comment by AjexRose** [comment]
There is a weird issue that when I try saving it under gridID it instead saves a random wall or pipe, but if I try to save it as a map then it just freezes up when I try to test purchase it.

**Comment by Cheackraze** [comment]
> There is a weird issue that when I try saving it under gridID it instead saves a random wall or pipe, but if I try to save it as a map then it just freezes up when I try to test purchase it.

with the new changes, you need to find the real grid UID using a different method. F3 menu is now lying to you about what the *real* grid id is.  Kind of a pita.

To get the grid properly now, I suggest running the command `lsmap` in the console.  Then, find the correct map you are working on, and it will display the griduid there, and you can then use `savegrid` like we are used to.

**Comment by AjexRose** [comment]
I found another way to find the real gridID to be finding the "fake" gridID in the grids>object tab and vving it to see the real gridID, but your method is good to know too.

**Comment by FoxxoTrystan** [comment]
Another way to find the real GridID at least for me is just type in the console "fixatmos" and there the autocorrect with the real ID.

**Comment by AjexRose** [comment]
MerchantShuttle3
Third iteration of the shuttle, with some more RP space, including a bedroom, and a break room. Also adds a store manager (QM) and their office.
The tight corridors are inspired by my current retail experiences, and how the main area of customers is large and roomy while the depths that employees go in the back-of-house are cramped and narrow.

**Comment by MagnusCrowe** [comment]
This has been inactive for a while so I am going to close it for now.  Please feel free to reopen if you still want to work on it.

If this was the final iteration, reopen the PR.

**Pull request closed without merging**
