### PR TITLE
NC Aldente

### PR DESCRIPTION
**Pull request by birdie412**
About the PR
This PR introduces a small Italian restaurant ship to the game. While I enjoy the other food ships in Frontier, they are mostly just fast food trucks. This ship, however, is a classy Italian pasta and pizza restaurant—perfect for a small Italian mob to run.

Why / Balance
I wanted a food ship that could support cargo, allowing cargo ships to dock and supply it with goods. While the MC-Cargo is a fine functional ship, it's a bit too large for my taste and lacks the classy feel that this ship offers. For roleplay purposes, I envision this as a small, elegant restaurant run by an Italian mobster—maybe even hiding bodies in the freezer for another cargo ship to pick up, or storing illegal substances that other ships can temporarily stash in their freezer. It's perfect for those who enjoy a bit of self-antagonizing gameplay, /S

F.A.Q:
Q: Why is there no grill or fryer?
A: This is meant to be a classy pasta and pizza restaurant run by Italians. I know the microwave doesn't quite fit, but the game doesn't have spaghetti strainers or boiling pots yet. I’ll add those once they’re available in SS14.

Q: We already have three food ships in the game!
A: Hopefully, this ship brings a bit more uniqueness to the gameplay loop. Currently, we have the [NC Bocadillo], [NC Skipper], and [DC McCargo]. While I like those ships, they’re more like "food trucks" or "fast food restaurants." They come with outdated issues, like the NC Skipper not being drivable by lizards or lacking a nitrogen canister for our Vox friends. The NC-Aldente will hopefully add more fun RP moments, allowing you to dock the ship with other cargo vessels to exchange goods—or maybe even hide something from the authorities.

## Media

Docking

-Here are some inspiration Media aswell:
tiella (1)
MV5BMzNjYjM3MGEtNjkxNi00MTIwLThmMWItZTEwOTMyZDQ0ODAzXkEyXkFqcGdeQXVyMTQ2ODE0NDA@ _V1_
05-al-fresco

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

### CODE REVIEW

**Comment by jimmy12or** [comment]
I like it!
Side note, you forgot to mention the Ceres when listing food ships.

**Comment by SabatonShip** [comment]
Dats cool!

**Comment by Tych0theSynth** [comment]
This PR does not follow the form expected for contributions to the game. 
Please include images showing the ship's subfloor and states when uninitialised and initialised. 
There is no changelog. 
Please read the documentation for opening PRs before just going and deleting half of the form. I'd recommend reading other ship PRs also to get an idea of what's expected. 
Also, don't commit to master :godo:

**Comment by birdie412** [comment]
> I like it! Side note, you forgot to mention the Ceres when listing food ships.

ah yes the ceres, I was thinking in term of Ship sizes, the Ceres is even bigger then the Mc-Cargo if im not mistaking.
The Aldente i would say is a smaller ceres type of ship,

**Comment by birdie412** [comment]
> This PR does not follow the form expected for contributions to the game. Please include images showing the ship's subfloor and states when uninitialised and initialised. There is no changelog. Please read the documentation for opening PRs before just going and deleting half of the form. I'd recommend reading other ship PRs also to get an idea of what's expected. Also, don't commit to master :godo:
adding in the subfloor and also fixing the commit to master issue now, sorry about that.

**Comment by Tych0theSynth** [comment]
Also, while the flavour images are a bit amusing, they're kinda spammy and don't really add much that the maptainers will appreciate. Worth also adding that 'aldente' is actually two words, so it should be 'al-dente', no? Feel free to correct me if you're Italian.

**Comment by birdie412** [comment]
> Also, while the flavour images are a bit amusing, they're kinda spammy and don't really add much that the maptainers will appreciate. Worth also adding that 'aldente' is actually two words, so it should be 'al-dente', no? Feel free to correct me if you're Italian.

NC-Al-Dente is a bite mouthfull. i could change it if you feel like it sounds better.

**Comment by Tych0theSynth** [comment]
> > Also, while the flavour images are a bit amusing, they're kinda spammy and don't really add much that the maptainers will appreciate. Worth also adding that 'aldente' is actually two words, so it should be 'al-dente', no? Feel free to correct me if you're Italian.
> 
> NC-Al-Dente is a bite mouthfull. i could change it if you feel like it sounds better.

I mean, it's more than 'aldente' isn't a word. If you want it to be an Italian themed restaurant, you should know that Italians are very passionate about their food and language! You should spell it correctly to appease them.

**Comment by birdie412** [comment]
> > > Also, while the flavour images are a bit amusing, they're kinda spammy and don't really add much that the maptainers will appreciate. Worth also adding that 'aldente' is actually two words, so it should be 'al-dente', no? Feel free to correct me if you're Italian.
> > 
> > 
> > NC-Al-Dente is a bite mouthfull. i could change it if you feel like it sounds better.
> 
> I mean, it's more that 'aldente' isn't a word. If you want it to be an Italian themed restaurant, you should know that Italians are very passionate about their food and language! You should spell it correctly to appease them.

The itallian mob will come after me from boiling spaghetti in a microwave aswell.
For reference writing "Aldente" instead of "Al dente" is like writing "Abite" rather then "a bite"
does "NC-A-Bite" sound better then "Nc-Abite"? if it does, then its just an easy name change.

**Pull request closed without merging**
