### PR TITLE
FaxCopy

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added the option to copy papers

## Why / Balance
Why was this missing from the game to start with.

## Technical details
C# and UI, added a new copy option to all fax machines, it will just print the data from the inserted papar

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl: dvir01
- add: All fax machines are now also a copy machine.

### CODE REVIEW

**Review by Cheackraze — APPROVED** [review]

**Comment by PJB3005** [comment]
Hi, we received another complaint from @Cheackraze that an upstream PR (https://github.com/space-wizards/space-station-14/pull/22027) plagiarized this PR. We initially received a report when the upstream PR was opened, but after investigation found that this was not the case and decided to not act further on it. (The upstream PR author also clearly denies the accusastions).

We have now received yet another complaint from @Cheackraze, stating that the code is "identical", "very clearly ripped" and that we are "shameful" for "ignoring" the concerns. I am going to set the record straight publicly here:

The original functionality of a fax machine (before either PR) is to:
* Have a button labelled "send" that, when pressed,
* Causes a copy of the inserted paper to appear in the print queue of another fax machine.

The functionality of a copy button is to:
* Have a button labelled "copy" that, when pressed,
* Causes a copy of the inserted paper to appear in the print queue of _the same_ fax machine.

The reason the PRs are similar is because **they're both copy-pasting the existing fax machine code. Not because one is plagiarized.**

In more detail:

* The UI code is basically exactly what you get if you copy every single line related to "`Send`" and replace it with "`Copy`". There are minor differences in code order and in the actual UI the order is also different, but otherwise it's trivial to end with the same code.
* The downstream PR adds a separate copy timeout, directly copy pasted from the existing send timeout. The upstream PR does not do this and uses the same timeout (but doesn't rename it so it's mildly confusing now).
* Both PRs copy paste the boilerplate at the start of `Send()` to make sure the paper inserted is actually valid and such.
* Both PRs read all the paper parameters and then stuff those into a `FaxPrintout` instance, but the downstream PR first stuffs them in local variables, whereas the upstream PR directly reads them in the constructor.
* The downstream PR reads the stamp state, then checks if there is a stamp state at all, then reads it again. This doesn't make sense. The upstream PR reads it once.
* Both PRs (and the send code) are faced with the possibility of "what happens if the inserted paper doesn't have a prototype". For starters. The send code sends no prototype data in the device network message, which causes the `FaxPrintout` constructor to null-coalesce it to `""` later. `SpawnPaperFromQueue` then checks `printout.PrototypeId.Length == 0 ? DefaultPaperPrototypeId : printout.PrototypeId` to handle this.
	* **The downstream PR's handling of the above situation is incorrect**: it sets the prototype ID to a literal string `"0"` instead of the `""`  or `null`. It also copies the 4-line TODO comment from Send literally.
	* The upstream PR instead passes the fallback prototype ID to the `FaxPrintout` directly, but makes sure to put it into a constant so the magic value isn't copy pasted. It inserts a different TODO comment that refers to the existing one in Send.
* The downstream PR sends the `FaxPrintout` to `Receive()`, which means it makes a popup "unknown message from unknown". It would also notify admins if this were a centcomm fax machine. The upstream PR directly appends it to the print queue.
* The downstream PR creates an admin log entry. The downstream PR does not.
* The downstream PR plays the "send" sound when copying. The upstream PR explicitly calls out it does not do this as the sound overlaps with the print sound.
* Both PRs copy the fact that the timeouts are checked client side and a cheat client could spam faxes faster than the timeout.

Seriously, these are not differences that arise from "just copy my homework and change it up a bit".

@Cheackraze this has been a complete waste of my time (more than an hour and a half[^2]) to have to respond to. You always act extremely antagonistically towards us, instantly jumping to extreme assumptions of bad faith and accusations over the tiniest shit. This stupid drama is no different.

There is a good reason you have been banned from upstream GitHub, Discord, and most of the PMs have you outright blocked. You should consider yourself lucky that there are still PMs open to receive communication from you considering this is how you keep using the privilege.

[^2]: In part because my Firefox crashed and I had to rewrite half the damn thing.

**Comment by Cheackraze** [comment]
I'm not sure why a message to one of your project managers in private when I asked of their opinion and clarification on this matter turned into such an immense scree, but the harassment, insults, attempts at defamation, and your open hostilities and toxicity to contributors in the public, including here on public forum channels, and in your project's voice channels openly, will result in your ban from this repo.

Having 5/6 of the files be identical line by line, and the 6th file having sharing function structure down to the white space should be concerning to any FOSS project when brought to their attention.  The fact that my initial report of this went unanswered for months, and the code simply merged without a word, resulted in this form of intense harrasment and abuse, is incredibly alarming.  A simple credit, or even addressing any of the people who raised concerns, including the original contributor, could have gone a long way in resolving this.

**Comment by arimah** [comment]
I am the author of upstream's PR. For whatever it's worth, and I cannot possibly prove this assertion, at the time I wrote the code, I was not aware that Frontier had this functionality, nor that Frontier even existed; I had only interacted with upstream at that point.

I feel that PJB adequately highlighted the various differences between the two implementationen. Large swathes of my code were little more than copy-pasting and specialising existing functionality. Other changes - particularly around handling UI state, where the changes are indeed almost or completely identical - are a result of two developers attempting to solve the exact same problem and arriving at the same conclusion.

I do not plagiarise, and if I had knowingly used any part of any code from any other codebase, there would be attribution in a code comment and in the PR description. In this instance, I believe the similarities are fully explained by the saying "great minds think alike".

**Comment by Cheackraze** [comment]
The bigger problem was that I raised this issue initially with them months ago and received 0 response about it whatsoever, and so when I came across it while working on the merge and noticing the duplicate files I asked again and got a fairly toxic response about it. I am inclined to believe you and I wasnt going to accuse outright but it was close enough for it to be looked at and addressed, and we here on our code base have rejected PRs that clearly have come from other places without proper attribution.  The FOSS is vast and diverse and only grows healthier with cooperation, but many contributors' only benefit to contributing to projects is to have their work recognized and properly attributed.  I meant no ill will towards you in the slightest.

**Pull request merged**
