### PR TITLE
Mail Truck (Update)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Updated the ship to match the POD, and to match the new MailPress in the works.

## Why / Balance
Rework

## How to test
Spawn and buy the ship

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: The Mail Truck got a full rework,

### CODE REVIEW

**Comment by Cheackraze** [comment]
the iconic mail truck noo. I'm ok with this so long as everyone else is, i know lots of people really enjoy the current one.

**Comment by MagnusCrowe** [comment]
Not quite sure I understand the reason behind such a big change to this ship.  Can you elaborate?

**Comment by dvir001** [comment]
> Not quite sure I understand the reason behind such a big change to this ship. Can you elaborate?

Hover bike support, mailpress dock support, match the pod style

**Comment by MagnusCrowe** [comment]
> > Not quite sure I understand the reason behind such a big change to this ship. Can you elaborate?
> 
> Hover bike support, mailpress dock support, match the pod style

Alright, I'll try to review it tonight.

**Comment by MagnusCrowe** [comment]
Looks good as far as I can tell except for one, itsy bitsy little thing that will probably cause you hit your head on your desk.

Ship's too big for me to overlook the lack of 2 stage airlocks.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
Looks good as far as I can tell except for one, itsy bitsy little thing that will probably cause you hit your head on your desk.

Ship's too big for me to overlook the lack of 2 stage airlocks.

**Comment by dvir001** [comment]
> Looks good as far as I can tell except for one, itsy bitsy little thing that will probably cause you hit your head on your desk.
> 
> Ship's too big for me to overlook the lack of 2 stage airlocks.

Fair, I'll edit it

**Comment by dvir001** [comment]
Done

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
