### PR TITLE
New Asteroid Event - Research Bunker

### PR DESCRIPTION
**Pull request by VividPups**
## About the PR
Added a new asteroid event

## Why / Balance
There aren't a lot of events that don't have an NFZ in it The other asteroids has been Disable until they can get rework

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
N/A

**Changelog**

adds a New event

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: New Bluespace Asteroid

### CODE REVIEW

**Comment by VividPups** [comment]
as of right now, I can't get the Bluespace event to show up at or even get the bloodmoon, wizardprobe etc  to show up either
image

**Comment by VividPups** [comment]
So far the current problem is as soon as I spawn in the blue space gamerule.  Second later it just deletes,  Asking for assistance

**Comment by VividPups** [comment]
Hi, this PR has been open for 3 weeks now and haven't gotten a single reviewed. Could I please get someone to review it and also help me with the current problems it has

**Comment by dvir001** [comment]
Im working on some big changes to the events loot to be spawner based from the dungeon spawners, with the changed of removing the plasma chambers for AI mobs.

After that ill look into helping with this one

**Pull request closed without merging**
