### PR TITLE
Re-add sparrow.yml

### PR DESCRIPTION
**Pull request by ThatOneGoblin25**
## About the PR
Re-adds sparrow.yml from #955, which was reworked to be in line with updated mapping guidelines by ErhardSteinhauer. Solves #1012 issue. I'm not sure why after the upstream merge this file vanished and I couldn't find any info why. I would like it back. Also easy pr for first pr.

## Why / Balance
I like this ship a lot.

## Technical details
A separate sparrow.yml already exists in Maps/_NF/Shuttles, that is the grid. This sparrow.yml is for Prototypes/_NF/shipyard which gives the shuttle a price and ID so it can be listed and purchased by players in-game.

- [X] this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added sparrow.yml, which re-lists the vessel in the shipyard again.

### CODE REVIEW

**Comment by dvir001** [comment]
I believe it was removed for having too many sci ships and missing a proper rework, also no one wanted to maintaine it.

If you can rework the ship to match new guidelines we can consider readding it

**Comment by ErhardSteinhauer** [comment]
wdym "rework to new guidelines"? 'twas done

**Comment by ErhardSteinhauer** [comment]
*flips the table, runs away crying*

**Comment by ThatOneGoblin25** [comment]
> I believe it was removed for having too many sci ships and missing a proper rework, also no one wanted to maintaine it.
> 
> If you can rework the ship to match new guidelines we can consider readding it

Erhard reworked it for updated mapping guidelines so I was confused as to why it went missing, if you didn't want it back that fine.

**Comment by Cheackraze** [comment]
heh idc either way, im willing to retire it because i feel theres better ships in that role nowadays. this was one of my original prototype ships even. I'm willing to re-add it since its recently updated.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
