### PR TITLE
Nonlethal Vending Machine (Practice Rounds & Etc)

### PR DESCRIPTION
**Pull request by SirMcSlushers**
## About the PR
I added a Vending Machine that has mostly nonlethal stuff in it.

## Why / Balance
It felt weird the lessthenlethal vend had practice rounds as the Emagged thing you get.. While it's also selling rubber bullets and 'actual guns' at the same time which can be loaded with lethal rounds.

  _**startingInventory:**
    WeaponDisablerPractice: 4
    WeaponLaserCarbinePractice: 4
    MagazineBoxPistolPractice: 10
    MagazineBoxMagnumPractice: 10
    MagazineBoxLightRiflePractice: 10
    MagazineBoxCaselessRiflePractice: 10
    MagazineBoxRiflePractice: 10
    BoxShotgunPractice: 10
    FoamCrossbow: 8
    BoxDonkSoftBox: 10
    TargetDarts: 1
    BoxDarts: 4
  **contrabandInventory:**
    WeaponRifleBB: 2
    BoxCartridgeBB: 10
  **emaggedInventory:**
    SpeedLoaderPistoladPractice: 2
    SpeedLoaderMagnumPractice: 2
    ThrowingKnife: 4_

## How to test
Spawn it ingame and try to buy from it.

## Media
Screenshot 2024-05-12 045257

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
[X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase.

## Breaking changes
No major changes, just new additions.

### CODE REVIEW

**Comment by dvir001** [comment]
I'm not sure I get why this is needed and how this will be used.

**Comment by SirMcSlushers** [comment]
> I'm not sure I get why this is needed and how this will be used.

Pretty much a why not, since it seemed weird the only way to access them before was obtuse and pointless as is. Someone made em, so why not let people RP with em without having to Emag a machine for some useless things.

**Comment by SirMcSlushers** [comment]
Also I don't think its catching the edit to the meta.json, huh.

**Comment by dvir001** [comment]
Please pull master into this.

**Comment by SirMcSlushers** [comment]
Dunno whacha mean, says mine is up to date

**Comment by SirMcSlushers** [comment]
Working on fixing it

**Comment by SirMcSlushers** [comment]
Should be fixed 👌

**Comment by SirMcSlushers** [comment]
Decided to expand this into practice laser weapons, so don't approve yet.

**Comment by SirMcSlushers** [comment]
Nevermind, its good, the game is way too broken code-wise to make adding projectile sprites easy xD
I'm submitting this as is for now. If I wanna mess with weapons i'll make it it's own branch.

**Comment by dvir001** [comment]
YAML Linter and RSI Validator need fixing

**Comment by dvir001** [comment]
The sprite inst right, its jumping to the size when you vend items

**Comment by dvir001** [comment]
Fixed it up and cleaned it

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
