### PR TITLE
Upstream Diona

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Putting Diona back to what they were on upstream, no more walking over glass shared, thats part of what diona are.

## Why / Balance
Diona back to be diona.

## Technical details
Having tags system on any species can get us to have upstream conflicts since the tag system replaced tag, not carry tags over parent to child entity.

## Media
N/A

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: Diona DNA back to normal.

### CODE REVIEW

**Comment by Cheackraze** [comment]
Not only is this going to massively conflict, but we set those values to that for a reason.  Wait until after the upstream merge to assess this, and don't remove the frontier specific stuff.

**Comment by dvir001** [comment]
Why the closed? This can be left as a draft for after the upstream, so it can be here as a topic point.

We have a tag for topics that need assessments.
The close was not required for me to convert to draft..

**Comment by Cheackraze** [comment]
It's closed because it's going to conflict and also 90% of thar needs to stay

**Comment by Cheackraze** [comment]
Every line in this pr is either already handled in the merge, or is frontier specific and shouldn't be changed

**Pull request closed without merging**
