### PR TITLE
Crew monitor general tweaks and QoL changes

### PR DESCRIPTION
**Pull request by Qulibly**
## About the PR

Changes which coordinates are displayed on the crew monitoring, console and handheld. From relative coordinates from the user to target. To global coordinates which match ones on GPS.
Uses code from https://github.com/space-wizards/space-station-14/pull/25116

Additionally tweaks when signal is sent to allow detection of people from space and in expeditions.

Also shows name of the locations players are in. Like "Tinnia's Rest" or if they are in space or expedition.

Coordinates show only on coordinates mode. While rough location on coordinates and vital modes.

## Why / Balance

It should greatly aid the medics in finding exact people's location as well as corpse's.
As before they needed to compare roughly which direction their patient was or rely on medical implant.
This way they will be able to just take a look at monitor and know exactly where to head.

Could potentially make detective's job bit easier too.

Overall is mainly aimed at improving medical gameplay.

## Technical details

For GPS coordinates uses exact code from https://github.com/space-wizards/space-station-14/pull/25116

For detection, used abit from https://github.com/space-wizards/space-station-14/pull/24880
Then was made that when grid is null it will fallback on the map coordinates.

Location name showing was the hardest part to figure out.
But basically first checks for grid. If it detectes it then checks if its expedition one. When it detects it simply gets its metadata name.
If grid is null then will name location as space.

Otherwise will show as unknown.
It does replace the place for jobs. But in Frontier I dont think they are the most important. And icons should suffice.

## Media

obraz
obraz
obraz
obraz
obraz

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes

Pretty much ANY changes to crew monitor code or suit sensors have very high chance of breaking this. Quite extensive modification was needed to get it all working.

**Changelog**

:cl:
- tweak: Tweaked crew monitors with new QoL features

### CODE REVIEW

**Comment by Cheackraze** [comment]
@Qulibly what do you think? it shouldnt be too difficult to grab those other changes in that upstream commit to fix the console, however, that contributor also hinted that they would work on a different form of fixing this exact problem. In any case, this solution is incredibly small and simple and I wouldnt mind having it since its a good enough change. The map inside the crew monitor console isnt nearly as helpful here as it is upstream in any case.

**Comment by Qulibly** [comment]
> @Qulibly what do you think? it shouldnt be too difficult to grab those other changes in that upstream commit to fix the console, however, that contributor also hinted that they would work on a different form of fixing this exact problem. In any case, this solution is incredibly small and simple and I wouldnt mind having it since its a good enough change. The map inside the crew monitor console isnt nearly as helpful here as it is upstream in any case.

Alrighty so I tried the https://github.com/space-wizards/space-station-14/pull/25116 and its working decently well. It makes the monitor console work and show people when they are on same grid.

It does require bit more changes but works simiraliry, except bit nicer crew monitor.

One thing I'm wondering is: If its worth it and also, if there are any other things that I could improve about operation of the crew monitor to make it easier to use. Like perhaps having people still send signal when in space and also that if you have enabled suit coords it will show name of grid/vessel you are on, and in space show "in space".

Imma see if I can get that. If not then will just keep it as gps coordinates adding only.

**Comment by Qulibly** [comment]
@Cheackraze Alrighty worked abit. I ended up using code from that PR. Then looked further to try and fix some other issues like players not being detected if they arent on any grid and also one neat feature like showing location name.

Managed to code working both.

Although I really need it reviewed if there arent any things that need to be additionally commented. Tweaked and checked if it wont cause too high lag AND if its even maintanable.

Honestly really needing feedback.

**Review by Cheackraze — CHANGES_REQUESTED** [review]
idk if its github or just this system has some already bad whitespace formatting or something but its hard to read.

Clean up that name as GreaseMonk suggested and will merge it

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
