### PR TITLE
Added rubber ammo to NFSD TechFab

### PR DESCRIPTION
**Pull request by DmitriTheDemon**
## About the PR

Moved nonlethal recipes from dynamic to static for SecurityTechFab inherited by NfsdTechFab

## Why / Balance

Less-lethal ammunition is available from round start via vending machines already, but the NFSD techfab only has lethal ammunition by default.

Allowing the techfab to produce less-lethal rounds in the field will help encourage de-escalation

Typically there are only 1-2 nfsd fabricators in play at any given time, so impact will be limited.

## How to test

Create NFSD techfab from flatpack or spawn menu
Verify rubber recipes are available by default
Link with research server to ensure fabricator does not break if linked to R&D

## Media

NFSD Techfab Rubber

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

N/A

**Changelog**

:cl:
- tweak: Added less-lethal ammunition to NFSD techfab by default, with additional NFSD items.

### CODE REVIEW

**Review by dvir001 — APPROVED** [review]
Sure
Its in vending anyway

**Review by whatston3 — APPROVED** [review]
Commented out the beanbag recipes rather than removing them entirely, looks good to me.

**Comment by dvir001** [comment]
Moved the NFSD stuff to the NFSD and cleaned unused security to wizden point.

**Comment by dvir001** [comment]
Ok so looking into it we actually had missing Nfsd entity on it also, so fixed.

**Comment by blackknight954** [comment]
Could we also get mercfab included in this as well?

**Comment by dvir001** [comment]
> Could we also get mercfab included in this as well?

out of scope

**Pull request merged**
