### PR TITLE
Replace Whitelist flag usage with Ban flag

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Hotfix for admins: whitelist commands have a new permission that nobody has.

## Why / Balance

Code review is important!  The more reviewers you have, the more reliable your code is.

## How to test

Build, use the whitelist interface, it works.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

Nope.

### CODE REVIEW

**Comment by dvir001** [comment]
Can't we just add the perma to admins?

**Comment by whatston3** [comment]
> Can't we just add the perma to admins?

Somebody can; I can't.

**Comment by dvir001** [comment]
Keep the general perma in the list but remove its need for now

**Comment by dvir001** [comment]
So we can actully add it to admins

**Review by dvir001 — APPROVED** [review]

**Pull request closed without merging**
