### PR TITLE
Foxes

### PR DESCRIPTION
**Pull request by rbertoche**
Originally created by Vulpine and merged on upstream april's first branch.
Someone asked me to add this to frontier so there it is.
This have been used on Pirata's main branch for a while now so it's been maintained. Delta-V also recently picked it up, hence one cherry pick from Daemon.

I tested it briefly but should work since it works for us.

:cl: vulppine
- add: Foxes

edit: Should I move it to Prototypes/_Pirata or something like that?

### CODE REVIEW

**Comment by Cheackraze** [comment]
/sigh well I suppose. Ideally i would have liked to merge all the customizations in here with felinids themselves but if this is what people have on the other ones might as well why not.  How do they functionally differ gameplay-wise?

**Comment by rbertoche** [comment]
No gameplay changes. I need to double check their metabolism is the same as human's but the whole point was people who wanted to have characters who looked like that, I didn't want it to become advantageous our disadvantageous

**Comment by rbertoche** [comment]
They have a OrganAnimalStomach derived stomach, so the same as lizard's, can eat rats and stuff like that.
Feel free to request any tweaks

**Comment by Kesiath** [comment]
In my own opinion, I'd rather see the 'fox'-esque features, alongside various other animal type features, given as markings for felinid and expand upon the species we already have. This seems more fit as a customization enhancement for felinids then it does an actual distinct species, given that there is no distinct gameplay alterations. If there was more to this species to make it distinct gameplay-wise then I'd be more onboard.

Note that I'm not suggesting for the species to have advantages or disadvantages, just things that make it different instead of being an amalgamation of the different species we already have.

**Comment by rbertoche** [comment]
Oh alright
The main difference with felinids would be that felinids have human skin, can't have "weird" colored fur or usual cat colors like yellow or gray or like Khajiit
If the idea would be to have a more generic "canid" species then I would think it should have flexible skin color, not just human skin colors
I added it to our codebases and server as is for no other reason than so people could play as "foxes" since there were some people voicing that wish
The time I played nyano the most as sec there were some level of power gameish high occurence of felinid getting arrested and their speed boost was a bit annoying but anyway now I miss playing that :P
My point being, featureless races kinda look interesting to me in how people will only play with them for reasons that have nothing to do with any mechanics
if you people want any change, just ask. If it doesn't get merged, that's fine too, I'll find something else to contribute sometime soon hehe

**Comment by potato1234x** [comment]
:(

**Comment by Cheackraze** [comment]
I would like them to have some kind of defining gameplay feature.  Do we have any kind of dog vision filter or something? I think I saw something in nyano's code base? Im not denying them, I just want them to have at least something that can set them apart within the game even if its a minor inconvenience or trait or accent.  It can even be your own or some simple system like that, that adds a component onto fox persons etc.

**Comment by rbertoche** [comment]
I like the idea of dog vision, I'm just not fan of stuff like 30% faster move speed.
Can someone point me at such visual filter code? a changeset, file in nyano repo, PR or anything like that?

**Comment by Cheackraze** [comment]
> I like the idea of dog vision, I'm just not fan of stuff like 30% faster move speed. Can someone point me at such visual filter code? a changeset, file in nyano repo, PR or anything like that?

someone else is making an attempt instead at a "dog speak translator" or something that needs to be charged to translate your speak, which could be an interesting idea instead

**Comment by Cheackraze** [comment]
sorry to close this one on you Rber, but we got them added in with the custom language and translator instead. Feel free to take that PR to pirata though! Its actually really neat!

**Pull request closed without merging**
