### PR TITLE
Extend rotting/respawn times

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Rotting and with it also respawning times will be extended from 10 minutes to 15 mins.

## Why / Balance

Rounds last 6 hours and for a body to start rotting and start bloating in the same time frame that it takes the evac shuttle to go to the station is silly. this will also affect the time food like raw meat takes to rot way so that is also a plus.

## Technical details

changed 2 numbers for other 2 slightly larger numbers

**Changelog**

:cl: Leander

- tweak: Nanotrasen has managed to extend the time it takes for food to rot away and with it all biological related products like passengers of all species, somehow this has produced delayed times on the central command cloning facilities too.

### CODE REVIEW

**Comment by GentleButter** [comment]
i dont see an issue with this

**Comment by GrandKadoer** [comment]
Why such a small increase? Can we push it to like 20?

**Comment by arimah** [comment]
> this will also affect the time food like raw meat takes to rot way so that is also a plus.

FYI, this is not quite accurate. Raw meat has a custom rotAfter set to 5 minutes:

https://github.com/new-frontiers-14/frontier-station-14/blob/85b2bf307d100b5223b5d890f01e1a359b1c7cc6/Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml#L64

If you wish to influence the speed at which raw meat rots, this value must be updated too!

**Comment by Leander-0** [comment]
> > this will also affect the time food like raw meat takes to rot way so that is also a plus.
> 
> FYI, this is not quite accurate. Raw meat has a custom rotAfter set to 5 minutes:
> 
> https://github.com/new-frontiers-14/frontier-station-14/blob/85b2bf307d100b5223b5d890f01e1a359b1c7cc6/Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml#L64
> 
> If you wish to influence the speed at which raw meat rots, this value must be updated too!

wow okay thats way too short, setting it up to 15 mins too will do it, thanks.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
