### PR TITLE
Medical access for the Brigmedic

### PR DESCRIPTION
**Pull request by Houtblokje**
## About the PR

This PR gives medical access to the brigmedic.
## Why / Balance

The brigmedic can, by default, not access the medical areas in for example the empress when it would be expected that they could. This PR gives them the expected access.  
## How to test

Spawn in as a brigmedic.
Go to the empress and open the medbay door.
Give yourself a deputy ID card.
Try to open the medbay door and fail.
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Shouldn't be any.
**Changelog**

- fix: The Brigmedic now has medical access on their ID card by default.

### CODE REVIEW

**Comment by dvir001** [comment]
Why? just fix the doors on the ships with a yaml swap.

**Comment by Houtblokje** [comment]
> Why? just fix the doors on the ships with a yaml swap.

Deputies and other NFSD staff not being able to access medbay is a good thing. That should be the job of the brigmedic, and otherwise it is the business of the sherrif to assign permissions.

**Comment by whatston3** [comment]
> > Why? just fix the doors on the ships with a yaml swap.
> 
> Deputies and other NFSD staff not being able to access medbay is a good thing. That should be the job of the brigmedic, and otherwise it is the business of the sherrif to assign permissions.

Disagree, the facilities should be open to all NFSD staff.  The doc should have control over his fief, but you should still be able to have access at critical moments.

I've got a suggestion that makes all of the medical doors on both the empress and the wasp into security-locked doors: [whatston3:NFSD-Brigmed-Access-Fix-suggestions](https://github.com/Houtblokje/frontier-station-14/compare/NFSD-Brigmed-Access-Fix...whatston3:frontier-station-14:NFSD-Brigmed-Access-Fix-suggestions?expand=1)

This also addresses a few bits of cleanup:
* Fixes issues with inaccessible AME jars and start-on issues with the Empress and Wasp.
* Removes a few unwrenched pipes on the Wasp.
* Unrotates all airlocks on the Empress.
* Replaces hydro trays with anchored ones on the Wasp (added upon request).
* Replaces cloning on the empress with frames (added upon request).

**Comment by GreaseMonk** [comment]
move that bus

**Pull request closed without merging**
