### PR TITLE
Pirate Cove (Update)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added the ``fixgridatmo`` command fix PR, since I could not do this PR without it. 
Redid the pirate cove based on a "ship crashed a large meteore" idea.
Added a new IFF computer that cannot be broken, moved, or disassembled with a new IFF that only allow change of "hidden" status to allow the pirate cove and the syndicate point bravo to be set to be hidden.
Change the Freelance and Syndicate radio to no longer be global and require servers, moved the servers to POI (Pirate to pirate, syndicate to syndicate).
Fixed an issue with some machines and computer that were able to be broken for board (Hydro tray)
Added new water that is decorative to be used under catwalks.
Gave Clarrrrpy the ``FreelanceTrackingImplant`` to replace the syndicate one.

## Why / Balance
Long time coming, with the new pirates system under work I think its time for a facelift.

## How to test
Run the game, warp to the new pirate cove.

### Mapping mod:
Docking area
image

Cave start
image

Middle of cave
image

Side area
image

Top area
image

Far render
image

### In game:
Docking area
image

Cave start
image

Middle of cave
image

Side area
image

Top area
image

Far render
image

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: The pirates moved to a new base, McCove if you will.

### CODE REVIEW

**Comment by WallaceLordofOwls** [comment]
The cave looks like it's open to the vacuum of space along those tan areas on the left and top part of the cove. Is that the case?

**Comment by dvir001** [comment]
> The cave looks like it's open to the vacuum of space along those tan areas on the left and top part of the cove. Is that the case?

Why make the claim if you didn't test in game.
It's not.

**Review by MagnusCrowe — APPROVED** [review]

**Comment by WallaceLordofOwls** [comment]
@dvir001 Hi dvir, absolutely love the new cove updates, but I noticed two potential issues with the updated cove. Firstly, the soda dispenser doesn't have any soda in it, which I assume is an oversight. 

The other thing is that the pirate cove has Frontier sell values, instead of cargo depot values. I think it's a lot better to have pirates head back to the cove and sell their stuff there instead of awkwardly sneaking to a depot to sell, so if it could be changed to be depot sell values that would encourage pirates to sell at the cove.

**Comment by dvir001** [comment]
> @dvir001 Hi dvir, absolutely love the new cove updates, but I noticed two potential issues with the updated cove. Firstly, the soda dispenser doesn't have any soda in it, which I assume is an oversight.
> 
> The other thing is that the pirate cove has Frontier sell values, instead of cargo depot values. I think it's a lot better to have pirates head back to the cove and sell their stuff there instead of awkwardly sneaking to a depot to sell, so if it could be changed to be depot sell values that would encourage pirates to sell at the cove.

This 2 things are 100% intended, soda empty but boze full is a joke

The low sell was asked by check to be added.

Depo can go full IFF off also

**Comment by WallaceLordofOwls** [comment]
> > @dvir001 Hi dvir, absolutely love the new cove updates, but I noticed two potential issues with the updated cove. Firstly, the soda dispenser doesn't have any soda in it, which I assume is an oversight.
> > The other thing is that the pirate cove has Frontier sell values, instead of cargo depot values. I think it's a lot better to have pirates head back to the cove and sell their stuff there instead of awkwardly sneaking to a depot to sell, so if it could be changed to be depot sell values that would encourage pirates to sell at the cove.
> 
> This 2 things are 100% intended, soda empty but boze full is a joke
> 
> The low sell was asked by check to be added.
> 
> Cove can go full IFF off also

Understood, thanks for the response!

**Pull request merged**
