### PR TITLE
Species Custom Sprites

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Added a bunch of sprites for Vulpkanin, Lizard and felinds.

This PR also makes that tails/HeadTop does not peek out of hardsuits or some suits that has the tags.

Thanks for GentleButter and ghostprince for assisting with the sprites!

- [x] Lizard Helmets/Head/Hats
- [x] Vulpkanin Helmets/Head/Hats
- [x] Felinds Tail Cover
- [x] Lizard Tail Cover
- [x] Vulpkanin Tail Cover

## Why / Balance

Lizard have helmets now! and fixes some for the vulps!

Also added more tags to hide species features on clothes.

## Technical details

Sprite Hell.
Changed File regarding HiddenLayer Tag, added three new tags: "HidesSnout, HidesHeadTop, HidesTail"

NOTE: The "HidesTail" Tag is also visible on species comp for the reason that species comp with that tag will have their tail hidden.

## Media

image
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: FoxxoTrystan / GentleButter / GhostPrince
- add: Lizard Custom Helmets!
- fix: Fixes/Add Vulpkanin Custom Helmets, also hides HeadTop features on helmets.
- add: Tail Cover for Vulpkanin, Lizard and Felinds!

### CODE REVIEW

**Comment by Cheackraze** [comment]
The majority of these sprites were CC-BY-SA-3.0, which says you must indicate if the original was modified in anyway, in order to not misrepresent the original artists work or to imply the endorsement of the original author.

So in all those meta.json files, you should indicate that you 3 modified the designs.  I admit I didn't review every single one yet, but if you come across any that have different licenses than CC BY SA 3.0, I can help navigate how best to list the licensing.  On the bright side, you'll all get your names embedded into the artwork licensing for them all from the repo!

**Comment by FoxxoTrystan** [comment]
> The majority of these sprites were CC-BY-SA-3.0, which says you must indicate if the original was modified in anyway, in order to not misrepresent the original artists work or to imply the endorsement of the original author.
> 
> So in all those meta.json files, you should indicate that you 3 modified the designs. I admit I didn't review every single one yet, but if you come across any that have different licenses than CC BY SA 3.0, I can help navigate how best to list the licensing. On the bright side, you'll all get your names embedded into the artwork licensing for them all from the repo!

Id like assistance on how to correctly list it, as upstream merge and others issues may... conflict with it

**Comment by Cheackraze** [comment]
> > The majority of these sprites were CC-BY-SA-3.0, which says you must indicate if the original was modified in anyway, in order to not misrepresent the original artists work or to imply the endorsement of the original author.
> > So in all those meta.json files, you should indicate that you 3 modified the designs. I admit I didn't review every single one yet, but if you come across any that have different licenses than CC BY SA 3.0, I can help navigate how best to list the licensing. On the bright side, you'll all get your names embedded into the artwork licensing for them all from the repo!
> 
> Id like assistance on how to correctly list it, as upstream merge and others issues may... conflict with it
> 
> Anywho il edit Meta files, tomorrow.

That's fine, conflicts like this are inevitable but unlike code, are very simple to resolve by just amending all the additions.  The more difficult part about sprite merge conflicts is when we have conflicting states.  Anyways, do t worry about that too much for now.

**Comment by FoxxoTrystan** [comment]
> > > The majority of these sprites were CC-BY-SA-3.0, which says you must indicate if the original was modified in anyway, in order to not misrepresent the original artists work or to imply the endorsement of the original author.
> > > So in all those meta.json files, you should indicate that you 3 modified the designs. I admit I didn't review every single one yet, but if you come across any that have different licenses than CC BY SA 3.0, I can help navigate how best to list the licensing. On the bright side, you'll all get your names embedded into the artwork licensing for them all from the repo!
> > 
> > 
> > Id like assistance on how to correctly list it, as upstream merge and others issues may... conflict with it
> > Anywho il edit Meta files, tomorrow.
> 
> That's fine, conflicts like this are inevitable but unlike code, are very simple to resolve by just amending all the additions. The more difficult part about sprite merge conflicts is when we have conflicting states. Anyways, do t worry about that too much for now.

and compleated.

**Comment by Cheackraze** [comment]
RSI validation hit on one of your files.  It's fairly strict on syntaxes, so make sure the license is stated exactly how it wants it, i.e., CC-BY-SA-4.0 with all the appropriate dashes and stuff

**Comment by FoxxoTrystan** [comment]
> RSI validation hit on one of your files. It's fairly strict on syntaxes, so make sure the license is stated exactly how it wants it, i.e., CC-BY-SA-4.0 with all the appropriate dashes and stuff

:[
Thats silly, anywho fixed!

**Comment by dvir001** [comment]
Can you convert the ``HidesSnout`` and ``HidesHeadTop`` tags to comps?
I fear we will have a mess the moment a new tag is added on upstream.

**Comment by FoxxoTrystan** [comment]
The hell is that Linter upstream hell?

**Comment by dvir001** [comment]
> The hell is that Linter upstream hell?

Upstream lizard helmets

**Comment by FoxxoTrystan** [comment]
> > The hell is that Linter upstream hell?
> 
> Upstream lizard helmets

I fixed merge conflicts with it but linter seem unhappy with things not related to my PR.
Unless my PR got fucked.

**Comment by Cheackraze** [comment]
could you include a fix for attribution on a few? we are missing "vulpkanin version taken from Paradise station at https://github.com/ParadiseSS13/Paradise/commit/f0fa4e1fd809482fbc104a310aa34cebf7df157d edited by Floofers" proper crediting on a few of the vulp helm sprites:

https://github.com/new-frontiers-14/frontier-station-14/blob/f1d81417323294b204bcf0a1e2a2982d58cab7fb/Resources/Textures/Clothing/Mask/sexymime.rsi/meta.json#L18
https://github.com/new-frontiers-14/frontier-station-14/blob/f1d81417323294b204bcf0a1e2a2982d58cab7fb/Resources/Textures/Clothing/Mask/sadmime.rsi/meta.json#L18
https://github.com/new-frontiers-14/frontier-station-14/blob/f1d81417323294b204bcf0a1e2a2982d58cab7fb/Resources/Textures/Clothing/Mask/muzzle.rsi/meta.json#L30
https://github.com/new-frontiers-14/frontier-station-14/blob/f1d81417323294b204bcf0a1e2a2982d58cab7fb/Resources/Textures/Clothing/Mask/mime.rsi/meta.json#L18

**Comment by Cheackraze** [comment]
and I'll help fix this branch tonight or tomorrow

**Comment by FoxxoTrystan** [comment]
PR moved to Draft until i can fix the fucky fucky.

**Comment by dvir001** [comment]
> Any plans to update this ? ❤️

If this PR can use comps and avoid tags X_X

**Comment by FoxxoTrystan** [comment]
> Any plans to update this ? ❤️

I planned indeed to update this when i have access to my PC with the test server.
AND PLEASE LET ME USSSE TAAAAGS! A

**Pull request closed without merging**
