### PR TITLE
Pulse (Update)

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Updating NM Pulse to current mapping standards:
- Atmos rework.
- Added Vacuum Markers to exposed to space tiles.
- Replaced consoles with tabletop variants.
- Moved things around.
- Added firelocks.
- Enabled Pilot Job.
- Moved ship.yml to Maps/_NF/Shuttles/

## Why / Balance
New mapping standards.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated NM Pulse to current mapping standards.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Something janky is going on with the tabletop shuttle console on this ship.  It isn't highlighting properly when mousing over it.

Try it yourself, use different rotations of the ship during testing.

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
Fix the shuttle console please.

**Comment by MagnusCrowe** [comment]
image
This is the type of thing I'm talking about.

**Comment by ErhardSteinhauer** [comment]
Right.
I'll replace it with normal console until I figure out permanent solution for tabletop consoles issue.

**Comment by MagnusCrowe** [comment]
> Right. I'll replace it with normal console until I figure out permanent solution for tabletop consoles issue.

IDK if it's just me or something, Slips is here and they don't see an issue.  Do some testing, I have no earthly idea what's going on here.

**Comment by MagnusCrowe** [comment]
the intercom on the Frontier Outpost bridge does the same exact thing.  
image

**Comment by ErhardSteinhauer** [comment]
> > Right. I'll replace it with normal console until I figure out permanent solution for tabletop consoles issue.
> 
> IDK if it's just me or something, Slips is here and they don't see an issue. Do some testing, I have no earthly idea what's going on here.

This thing is weird: I've seen those consoles dip under the table for a split second when I FTL or buckle in a seat, yet, they always get back on foreground layer, but I was able to interact with them using LMB after, so figured it's not that big of an issue.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
