### PR TITLE
Adding gas tanks in the tankdispenser

### PR DESCRIPTION
**Pull request by Graugr**
## About the PR

Expands the number of gas tanks available for purchase

**Media**

- [ Х] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
29900-157de-30237285-m750x740

:cl: Gargant
- tweak: changed assortment of the Tank dispenser
- add: emergency gas tank n2
- add: Extended emergency n2
- add: Double emergency gas tank n2

### CODE REVIEW

**Comment by EmmaFaith** [comment]
Make a version for slimes too as well, double emergency N2 tank that has Nitrogen in it, would be really useful for them.

**Comment by Graugr** [comment]
> Make a version for slimes too as well, double emergency N2 tank that has Nitrogen in it, would be really useful for them.

by now I don't have enough knowledge to make Tanks with n2

**Comment by dvir001** [comment]
If you want I can fix the tanks to be filled and also add the n2

**Comment by Graugr** [comment]
> If you want I can fix the tanks to be filled and also add the n2

i can add filled o2 emergensy tanks, im not code it cos its not fair to add filled o2 tanks and not add filled n2 tanks. i cant code emergency n2 tanks and variation to it.
i tried to code it, but unfortunatly its not working properly.

**Comment by Cheackraze** [comment]
shouldnt be too hard to fix and add the tanks. They need to be red for nitrogen to keep with visual consistency. If you still need assistance in a few days come find me on discord.

**Pull request closed without merging**
