### PR TITLE
Medical Tracking Implanter enabled by default

### PR DESCRIPTION
**Pull request by KyuPolaris**
## About the PR
Made it so that by default the medical tracking implant will be selected in loadout

## Why / Balance
Change implemented to help with newer players or players loadouts that may be unmodified before they pick the role by mistake

## How to test

- Make new character
- Check implants tab
- See that medical implanter is selected
- ????
- Profit

## Media

https://github.com/user-attachments/assets/409dcbaf-8d06-4443-9126-29f4dade930c

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
n/a

**Changelog**

:cl:
- add: Medical Trackers are now supplied by default (if left unmodified)

### CODE REVIEW

**Comment by dvir001** [comment]
Not a fan of this, this is 2 storage slot waste in some people inventory.

Some people all gameplay is to avoid it and not using it.

**Comment by KyuPolaris** [comment]
> Not a fan of this, this is 2 storage slot waste in some people inventory.
> 
> Some people all gameplay is to avoid it and not using it.

That is something I considered, I personally don't see the issue of the 2 slots that can be discarded on start. I didn't see a way to do it as default be also keep minimum to 0 on the implants tab so that it could be unchecked. The idea was mainly for people that might not have the roles loadout configured. I am more than happy for discussion and feedback on this <3

**Comment by dvir001** [comment]
> I think this would be a phenomenal addition for the new player experience. This is a valuable tool that many on their first few visits to Frontier may not entirely understand even exists.
> 
> Players who understand the loadout system will have no issue clicking the "no" button, as much as they click "yeah sure" on a half dozen cosmetics.
> 
> If I'm not mistaken there isn't any combination of loadout equipment that would be blocked by the addition of this item even in the event of mistakenly bringing it along. In which case it is a simple Q click away from being thrown into the trash.

The fact I cannot remove it from my load-out isn't good

If this PR also added new code that still made it 0 but just auto selected it for new loadouts it will be fine.
We can also use this code for the traffic channel key.

**Comment by whatston3** [comment]
Need to take a look at the loadout code again, but I think an easy-ish fix here is to select a fallback item as default if/when it exists rather than the first item.

Open issues with this:
- what happens when you have more fallbacks than you have min items
- what happens when you have items that are unselectable for particular species (e.g. jumpsuits with pants for harpies)

**Comment by KyuPolaris** [comment]
> Need to take a look at the loadout code again, but I think an easy-ish fix here is to select a fallback item as default if/when it exists rather than the first items up to the minimum.
> 
> Open issues with this:
> 
> * what happens when you have more fallbacks than you have min items
> * what happens when you have items that are unselectable for particular species (e.g. jumpsuits with pants for harpies)

I can partially answer this. I had the minimum originally still at 0 when I had the fallback be the tracking implant. It wouldn't work at all and was essentially how it was without the change.

**Comment by whatston3** [comment]
Thank you for your work on this.  I think that #1717 supersedes this, and I'm curious for your feedback on it.

A few small issues to iron out there, but with the feature, new characters should default to having a medical implanter, and extra comms keys are now completely optional, with traffic as a default for new characters.

**Comment by dvir001** [comment]
Closing this for https://github.com/new-frontiers-14/frontier-station-14/pull/1717 since we will just enable the Medical Tracking Implanter for auto pick

**Pull request closed without merging**
