### PR TITLE
More recyclable items

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
While there should be more recyclable items in general, in my opinion, I'm not sure if the method proposed in this pull request is the correct approach.

Nonetheless, this PR does expand the list of recyclable items. It generally makes almost every single item that can be found on space wrecks recyclable (same goes for items players spawn with). However, the PR mostly disregards the crafting compositions of items, which results in recycling being quite inefficient and sometimes overlooks the actual sizes of items. For instance, a toolbox, despite being a "ginormous" item, is considered medium-sized for resource yield purposes.

Even though the material value of items is somewhat undercut, I believe this could potentially make salvaging a competitive alternative to mining as a source of raw materials.

## Why / Balance
Less entities, more raw resources for crafting.

## How to test
1. Spawn, get a shuttle with material reclaimer, recycle everything you can grab on wrecks 

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- tweak: Expanded the list of items that can be recycled to such an extent that salvaging may become a competitive alternative to mining for obtaining raw materials.

### CODE REVIEW

**Comment by chrome-cirrus** [comment]
Awesome! This will be such a nice QoL thing... I hate that the only way to get rid of so many items is leaving them on a planet or hurling them into space for GC to eventually delete.

**Comment by NafenX** [comment]
As someone who obsessively shoves things in the disposal and checks the reclaimer, often being disappointed at the large pile of things that somehow can't be processed in there, I'm especially happy to see this get amended. Things like ammo boxes not recycling is especially annoying, because isn't it just cardboard? Oftentimes people will dump spare ammo and magazines in the disposal and they just pile up. It also seems like individual bullets DO get recycled but I don't know if it's the sprite just being too small or something because they don't seem to automatically get taken in by the magnet when on a conveyor belt..

**Comment by ErhardSteinhauer** [comment]
Can't think of anything else that'd be worth adding to the list, so I guess this is ready for review

**Comment by dvir001** [comment]
Wait for https://github.com/new-frontiers-14/frontier-station-14/pull/2209 to confirm no issues.

**Comment by ErhardSteinhauer** [comment]
Watch "integration tests" start bitching about recycled ammo boxes giving you more "carboard" than you used for crafting them (you used 0).

**Review by GreaseMonk — APPROVED** [review]

**Comment by GreaseMonk** [comment]
wait for integration test testing still

**Pull request merged**
