### PR TITLE
Add tool kits to cargo

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

This PR adds two kits to cargo:
- the basic kit includes a full toolbelt (with a multitool), insulated gloves, and goggles
- the full kit includes the basic kit, a gas analyzer, a t-ray scanner, a holofan projector and a geiger counter.

## Why / Balance

I am too lazy to walk to the vending machines every time I want tools when the ship I buy doesn't have them.
The basic kit is priced at 3500, buying everything separately from vending machines costs 3205.
The full kit is priced at 5000, buying everything (besides the geiger and holofan) from vending machines costs 4705.

## Technical details

YML

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Tool kits are now available at cargo.

### CODE REVIEW

**Comment by dvir001** [comment]
You know electric supply crate exits right?

**Comment by Cheackraze** [comment]
eh the vending machines are there for a reason. crates like this tend to bloat the server with unwanted things when people buy a whole crate of something just for 1 or 2 items in it, and we are trying to move away from that.

**Comment by crystalHex** [comment]
image
I don't really feel like the electrical supplies crate is that useful at the moment, it does not contain half of the tools, the other half is duplicated, and the extra wire would be good if there wasn't a bulk cable crate available.

**Comment by dvir001** [comment]
> image I don't really feel like the electrical supplies crate is that useful at the moment, it does not contain half of the tools, the other half is duplicated, and the extra wire would be good if there wasn't a bulk cable crate available.

You can edit the crate content, it will be more simple to us then having another crate in game.

**Comment by dvir001** [comment]
Closing this for now has this PR had no new updates to it, 
feel free to reopen this at anytime if any changes are done,

Thanks.

**Pull request closed without merging**
