### PR TITLE
Eagle-(Update)

### PR DESCRIPTION
**Pull request by ThatOneGoblin25**
## About the PR
- swapped plasma for uranium generators
- swapped plasma stack for uranium
- swapped autolathe for engi techfab
- removed youtools, engivend, engidrobe, medrobe, chemdrobe
- removed air canister
- added chemdispenser
- added drain
- added radiation shutters
- changed the goods on the engi table
- minor decals

## Why / Balance
Updating the Eagle. No more engivends.

## Media
Screenshot 2024-07-10 193408
Screenshot 2024-07-10 193337

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: The NM Eagle has been updated.

### CODE REVIEW

**Comment by dvir001** [comment]
All Uranium generators have to be closed in rads protections setups

**Comment by dvir001** [comment]
Also since this ship Is a fully equipped medical ship how are you seeing it used by doctors ones it's moved to medical poi shipyard only?

**Comment by dvir001** [comment]
Please removed mapped food, please wrench canisters and use on mixer with 71 / 29 mix and pumps that are on

Entry doors should use external glass airlock not normal glass airlock

Is there a need for captain locker? It's a small medical based ship

**Comment by ThatOneGoblin25** [comment]
> All Uranium generators have to be closed in rads protections setups
> 
> This seems like it was added after design and not with it in design
Yes. Hopefully this change is sufficient.

> Also since this ship Is a fully equipped medical ship how are you seeing it used by doctors ones and if it's moved to medical poi shipyard only?
Its a niche ship focused on rescue and repair, I see doctors using to respond to blown up science ships, where possibly one or more critical machines are blown up and there's 1-2 possibly dead. Potentially also ships that have been blown up by pirates with ship weaponry. 

> Please removed mapped food, please wrench canisters and use on mixer with 71 / 29 mix and pumps that are on
Done, I want to keep the Doctor's Delight glass though.
> Entry doors should use external glass airlock not normal glass airlock
Done.
> Is there a need for captain locker? It's a small medical based ship
It has been replaced with a empty Chief Medical Officer locker
Screenshot 2024-07-10 210123

**Comment by ThatOneGoblin25** [comment]
This is fine.

Screenshot 2024-07-10 220822

**Comment by dvir001** [comment]
Based and ship pilled

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
