### PR TITLE
Craftable Tabletop Consoles

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
The title + adds missing tabletop variants for the following Frontier specific computers:
- Station Admin Console.
- contraband exchange computer.

## Why / Balance
A nice option to have.

## Technical details
Haven't tested every computer, but the following do appear to be constructible on my end:
- ID card computer.
- R&D computer.
- analysis console.
- body scanner computer.
- cloning console.
- mass scanner computer.
- solar control computer.
- IFF computer.
- shuttle console.
- power monitoring computer.
- mass-media console.
- cargo bounty computer.
- cargo request computer.
- station records computer.

## Media
- [X] This PR does not require an ingame showcase.

## Breaking changes
Changes to base game .ymls (new component added to afaik every computer board) and CS files.

**Changelog**
:cl: erhardsteinhauer, GreaseMonk (CS magic)
- add: A janitor found under one of the tables in the old SR office a manual on how to construct tabletop consoles.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
It's draft because CS part of this PR isn't working

**Comment by ErhardSteinhauer** [comment]
> Made it work locally , need permission to push

awesome news! although I don't know if I even can give the permission.

**Comment by ErhardSteinhauer** [comment]
> image will need more tabletop variants in Circuitboards\computer.yml ,
> 
> ```
>     - type: ComputerTabletopBoard # Frontier
>       prototype: ComputerTabletopAlert # Frontier
> ```
> 
> but here you go

Yeah, was reluctant to add a bunch of lines to .yml without having the base functionality work.

**Comment by ErhardSteinhauer** [comment]
Yeah, I might need you to walk me through the procedure.

But I have no problems with taking the fall for shit code. Beside, I'm going to put your name everywhere CS related.

**Comment by ErhardSteinhauer** [comment]
> It would be best to add the origin and then cherry pick - i'm ready to help with that if needed.. this would add my name to the code and people can blame me for shitcode

Alright, I think I might've pushed the right buttons and done did the thing

**Comment by ErhardSteinhauer** [comment]
But it looks like when you attempt to build regular, not tabletop computer terminal, you get tabletop instead

**Comment by ErhardSteinhauer** [comment]
No longer a draft.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
