### PR TITLE
Adds a crafting recipe for the Security Patrol Hardsuit, and a revert crafting recipe.

### PR DESCRIPTION
**Pull request by No-Dad-Not-The-Belt**
## About the PR
This PR adds two new crafting recipes to utilize the Security Patrol Hardsuit and hopefully get it into the players hands. The first recipe uses a regular Security Hardsuit to craft a Security Patrol Hardsuit while giving two plasteel and five durathread (the stripped armor from the crafting process). The second recipe takes the materials recieved from stripping the armor and the Patrol Hardsuit to craft a Regular Hardsuit. Both crafting recipes have a 10 second doafter for each to complete, and the recipes are found through the in game crafting (G) menu. The video below shows both recipes in usage.

**Media**

https://github.com/new-frontiers-14/frontier-station-14/assets/108775472/c187aa25-1a14-4791-84ce-03b9fc47ab87

:cl:
- Add: Adds a new crafting recipe for the Security Patrol Hardsuit using a regular Security Hardsuit
- Add: Adds a new crafting recipe for the regular Security Hardsuit using a Security Patrol Hardsuit, 2 plasteel, and 5 durathread.

### CODE REVIEW

**Comment by Cheackraze** [comment]
An interesting choice, to be honest, I was going to make a new hardsuit locker to hold these and place a few in some of the sec ships.  Even though this is pretty safe, not sure how I feel overall about crafting/changing hardsuits.  I'm gunna ask some Sec players their opinions first

**Comment by No-Dad-Not-The-Belt** [comment]
Sounds good! Honestly I meant this as a temp fix to get them in people's hands until we implement a proper way to create/get them. I didn't want to just throw it in the sec fab or sec vend. If you have any ideas im open to suggestion!

**Comment by Kesiath** [comment]
putting them in the sec department itself might be nice for lowpop, since the small ships that are good for lowpop don't have any hardsuits with them

**Comment by No-Dad-Not-The-Belt** [comment]
> putting them in the sec department itself might be nice for lowpop, since the small ships that are good for lowpop don't have any hardsuits with them

Do you think mapping them in is the way to go? Or some kind of vendor like the sec tech or something?

**Comment by Cheackraze** [comment]
yea mapping them will be the preffered method, especially since this would be the only suit with that kind of interaction, makes it kind of hidden and obscure.  They'll be in soon don't worry, I'm making a large sec ship right now and will probably put one on frontier to replace the regular sec one.

**Comment by No-Dad-Not-The-Belt** [comment]
> yea mapping them will be the preffered method, especially since this would be the only suit with that kind of interaction, makes it kind of hidden and obscure. They'll be in soon don't worry, I'm making a large sec ship right now and will probably put one on frontier to replace the regular sec one.

Completely fair, the idea didnt seem too obscure since Ive always had a mental headcannon of hardsuits=MODsuits but I see what you mean. Ill close the PR and leave it up to mappers to implement them.

**Pull request closed without merging**
