### PR TITLE
Frontier Market / Trading console v0.1

### PR DESCRIPTION
**Pull request by GreaseMonk**
## About the PR
This replaces https://github.com/new-frontiers-14/frontier-station-14/pull/1579.
The PR adds the Market console which is basically a buyback system. Its products will be entirely dependant upon players to sell to it by selling stuff through the currently available cargo selling stations. The market console will only hold prototype information so it will spawn new prototypes, erasing any data from whatever state it was sold as. Works with the market modifier component.
The data is stored on the grid it is sold on, and the 'cart' is kept on the console (for now).
Market data will stay as per-grid basis so you wont be able to buy from other stations afar, but we may expand this later on.

Because this system just receives events whenever something is sold from Cargo, it hooks into cargo events only and is a completely seperate system to minimize upstream merge conflicts.
Anything that can be sold through the regular cargo system is automatically recorded on the grid, and is filtered out on the server side when opening the market console. Because of this, cargo blacklists will automatically apply to it's contents.

TODO:
- [x] Deal with stacks (merging IronOre and IronOre1)
- [x] Add a blacklist (easy)
- [x] Fix crate machine animation bugs, it sometimes hangs so it doesnt deliver
- [x] transaction costs
- [x] enable/disable on power outage
- [x] case insensitive search
- [x] register container contents
- [x] Cart maximum contents of 30 items check
- [x] Limit purchases to maximum amount a generic steel crate can hold

Future plans:
- Contraband only market
- Checking the stock from handheld (pda?) device

## Why / Balance

This adds a new dimension to economy which we really need.

## How to test

This PR added the market console to cargo depots (for testing) that may get reverted.
- Teleport to a cargo depot using `tpto` command (use admin menus, last tab, to find the grid)
- Sell stuff
- Check market console on north side of the cargo depot
- Order stuff

## Media

image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added market system

### CODE REVIEW

**Comment by Cheackraze** [comment]
it looks like the 'cart' isnt being cleared out upon purchasing, leading to essentially a duplication machine. I'll update the trade station and cargo depots tomorrow to use these.

**Comment by whatston3** [comment]
Been working on a set of suggestions for a bit.

Here's a diff of what I have so far:
https://github.com/GreaseMonk/frontier-station-14/compare/cargo-vend...whatston3:2024-08-03-cargo-vend-suggestions?expand=1#diff-42adbf0e85435d5a4103ff5a930c924a220e35010b1a0476d379310567de59d1R313

1. Moved the MarketData to a sector service.  Might be arguably desirable, but if you wanted to sell in the cargo depots, for instance, and then buy at the Trade Station, this'll work alright.
2. Moved the whitelist to the MarketData.  I think it makes more sense to store fewer things, and if we're not going to show them to clients anyways, why store them?  I could maybe see an argument for logging/data collection, but it might make more sense to go through admin logs to get what players are selling in a round.
3. Added an EntProtoIdWhitelist entry to the MarketData storage to allow for particular entities (e.g. uranium) to avoid the blacklist (I believe the name in the entity def'n is currently incorrect, but it's there)
4. Added Prototype functions to the EntProtoIdWhitelist, should mirror EntityWhitelist.
5. Swapped over your stack spawning code to StackSystem.SpawnMultiple - seemed to work okay with modest testing.
6. Added ArtifactComponent to the MarketData blacklist.

I think these are overall improvements, but I'm curious of your thoughts.  Still needs work regardless, looking forward to getting this feature in.

**Comment by whatston3** [comment]
"Wonder why it's like that ?" it's something particular to our fork, I made it for the pirate bounties maybe a few weeks ago, things like the news and sector alerts should be pushed into them since we don't want them to only be readable on station, but I haven't put in the time there.

Currently looking into cart & UI consistency - a purchase or sale message should update all available consoles.  There's code that updates all open consoles in the bounty system (both pirate and cargo).  I'll let you know when I've got an updated suggestion branch that should do this, I don't think it'll be too bad.

Pardon the UI jank on the suggestion, really an afterthought, and more of an "eh, how does this look?" experiment.  Probably shouldn't have been pushed in the first place.

**Comment by Cheackraze** [comment]
> "Wonder why it's like that ?" it's something particular to our fork, I made it for the pirate bounties maybe a few weeks ago, things like the news and sector alerts should be pushed into them since we don't want them to only be readable on station, but I haven't put in the time there.
> 
> Currently looking into cart & UI consistency - a purchase or sale message should update all available consoles. There's code that updates all open consoles in the bounty system (both pirate and cargo). I'll let you know when I've got an updated suggestion branch that should do this, I don't think it'll be too bad.
> 
> Pardon the UI jank on the suggestion, really an afterthought, and more of an "eh, how does this look?" experiment. Probably shouldn't have been pushed in the first place.

Design-wise, we wanted the 'inventory' of each available market to be grid-specific, since the cargo pallets pay out at different rates as well, along with making a more believable 'world' with the items existing at that location still... just under your 'feet' in storage etc. And then the cart data needs to be specific to that specific console so that multiple 'carts' can exist on a grid with different people shopping at different locations.

**Comment by whatston3** [comment]
> Design-wise, we wanted the 'inventory' of each available market to be grid-specific, since the cargo pallets pay out at different rates as well, along with making a more believable 'world' with the items existing at that location still... just under your 'feet' in storage etc. And then the cart data needs to be specific to that specific console so that multiple 'carts' can exist on a grid with different people shopping at different locations.

My two cents:
Cart data already exists on the console, that is fine, no issue there - the cart data _should_ be consistent with whatever inventory is backing it - if something adds or removes items from that, the UI should be consistent with the current state of that inventory. This is true regardless of where the inventory actually is, and grabbing the bounty code to ensure that consistency is straightforward.

Would it not be better to have a centralized index that players buy from, say, the Trade Station?  Depots for selling, Trade Outpost for purchase, either from players directly, from cargo, or from this new market?  Ideally, rates are such that players are incentivized to trade from each other first, then from this player market, then from cargo.

If I wanted to check the player market, would it not be more convenient to check the index at one location rather than checking multiple depots, which would take maybe 10ish minutes to check, assuming you can actually get a dock at the depots?
Repurposing the cargo depots to both buy and sell would also increase potential traffic to either of them, and they don't have many docks as-is.

**Comment by Cheackraze** [comment]
> > Design-wise, we wanted the 'inventory' of each available market to be grid-specific, since the cargo pallets pay out at different rates as well, along with making a more believable 'world' with the items existing at that location still... just under your 'feet' in storage etc. And then the cart data needs to be specific to that specific console so that multiple 'carts' can exist on a grid with different people shopping at different locations.
> 
> My two cents: Cart data already exists on the console, that is fine, no issue there - the cart data _should_ be consistent with whatever inventory is backing it - if something adds or removes items from that, the UI should be consistent with the current state of that inventory. This is true regardless of where the inventory actually is, and grabbing the bounty code to ensure that consistency is straightforward.
> 
> Would it not be better to have a centralized index that players buy from, say, the Trade Station? Depots for selling, Trade Outpost for purchase, either from players directly, from cargo, or from this new market? Ideally, rates are such that players are incentivized to trade from each other first, then from this player market, then from cargo.
> 
> If I wanted to check the player market, would it not be more convenient to check the index at one location rather than checking multiple depots, which would take maybe 10ish minutes to check, assuming you can actually get a dock at the depots? Repurposing the cargo depots to both buy and sell would also increase potential traffic to either of them, and they don't have many docks as-is.

the idea is to intentionally draw people around to the various places that have these items at, to allow for varying/changing market rates or costs of items dynamically, and to try to capture more person-person interactions 'at the console'. This would also avoid any kind of usage where players might find a way to 'fast transport' an item across the sector by selling it at 1 cargo depot and then someone else buying it 10km+ away.

If instead it is 'sector wide', I can see people camping out just at the trade depot and 'reserving' a spot to sit and refresh their window for long periods to hopefully snag an item they are looking for, leading to people kind of hunkering down and not moving around the area or running into eachother at the same places etc.

**Comment by whatston3** [comment]
> the idea is to intentionally draw people around to the various places that have these items at, to allow for varying/changing market rates or costs of items dynamically, and to try to capture more person-person interactions 'at the console'. This would also avoid any kind of usage where players might find a way to 'fast transport' an item across the sector by selling it at 1 cargo depot and then someone else buying it 10km+ away.
> 
> If instead it is 'sector wide', I can see people camping out just at the trade depot and 'reserving' a spot to sit and refresh their window for long periods to hopefully snag an item they are looking for, leading to people kind of hunkering down and not moving around the area or running into eachother at the same places etc.

Varying/changing market rates is fine and good, but shouldn't necessitate the point of purchase being at a particular location.  I also think that'd be a good idea, but wouldn't you want it to be based off of the total amount of a particular good sold.

I don't think that you'll get person-person interactions at the console.  *I honestly think that the best way to enable person-person interaction is to set market rates to enable arbitrage, and to locate the point of commerce at a particular station*.  A player will tend not to buy a good from a player unless they can offer better rates considering space and time to make a sale, or if there is some form of goodwill between them.

If you want to make a forum/bazaar, I do think the Trade Outpost is a better spot than the Trade Depots because of the existence of the player stalls.  I do not think you will get additional player interaction by fragmenting the buyer's market into multiple POIs. The desirable tasks for a seller are to either run a profitable activity longer (e.g. staying out mining) to get resources to sell, or run to turn in profits, cash out, and reduce risk.  The places we encourage that at the moment are trade depots (with better sell rates).

The desirable tasks for a buyer are to run their task assuming they have the input they need (fuel for ships, construction materials, chemicals, etc.), or get their input at a minimum of cost and time.  At the moment, the Trade Outpost is great because you know what you can get from cargo, you can see what player stalls are open, and if this was added, you have the player market to draw from.  As a buyer, why would I want to go to the Trade Depot only to wait in line to dock, see that the item itself is sold out, and then it turns out it's available at another Depot that I didn't know about?  If there was a PDA store app where you could purchase a mail-like crate, secured to your ID, and see what's available, sure, I'd use that, but I wouldn't scramble between different points of sale with mystery inventories.

I see your points regarding teleporting items - a delay between point of sale and availability in the system could be done through a timed queue, just for sake of argument.  I also don't know how to prevent players from camping a console - either add more consoles, or enable more tradeoffs of time/convenience vs. spesos - make more commonly desirable things available from cargo - you purchase it now, but at very high prices.

**Comment by Cheackraze** [comment]
staring at your PDA ui hitting refresh and getting items teleported around to where youve been sitting alone isnt interacting with players, waiting in line to dock with them at a busy depot because you heard on the radio that depot is full of items is. The point is to encourage  people saying they sold something at such and such depot, or saying 'this place had a ton of ore'. Making this universal and cross-sector with a ton of buying points means people will just never speak or see eachother and get their wanted item teleported to their feet from someone 10k away.

This is supposed to be a tool to help simulate and encourage player to player interactions, so these kind of limits are what we have to design in to still make person-person interactions more desirable. Along with the market value price of the items needing to be much higher on a base line but i have some fixes for that being pushed in a few minutes

**Review by Cheackraze — APPROVED** [review]
yolo

**Pull request merged**
