### PR TITLE
Bodkin (New Shuttle)

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Adds the SBB Bodkin, a new medium salvage shuttle for 2-4 players 
Lore-wise, the shuttle is the younger sibling of the NSF Broadhead, which was designed by BlueBird on commission for the NFSD. As such, it shares some of the design philosophy when it comes to the shape, interior and flight performance. 
Like the Broadhead, the Bodkin gets its name from an arrowhead: The Bodkin Point was a fairly cheap, ubiquitous and far flying arrow. 
The intended use of this shuttle is very different, however, being a civilian-grade mining and salvaging shuttle.

## Why / Balance
I know, I know, there are a lot of mining and salvage ships in the game already, and we already have two that are in the 2-4 crew range. However, while they are functionally excellent, they're very functional in shape, mostly being rectangle or square with extra steps. Why can't we have something prettier? 
In terms of where this belongs, it's aimed around the same level as the Bulker. Though it has a smaller cargo hold, you have an office space for the captain/QM, and plenty of living space for the crew to prepare or just hang out. 

**Design Aspects**
Overall:
- Broadhead inspired design.
- Fast acceleration, nimble handling.
- SBB signature navigation lighting. 
- Simple and easy to maintain atmos/electrical infrastructure.

Flight Deck/Fore:
- High visibility helm position.
- Desk space and lockers for the Captain/QM.
- All important paperwork storage.

Engineering/Crew Living Quarters/Amidships:
- Efficient engineering design. SUPERPACMAN (preset to correct output) with fuel locker.
- Single APC design. 
- Linked air alarm. 
- Crew welfare area. 

Cargo Hold/Aft:
- Two stage airlocks with cargo loading/unloading ports (buttons and levers for control). 
- Aft blast doors for external access with catwalk for salvage loading. 
- Chisel-style ore processor layout.
- Hardsuit lockers for salvagers. Avoids dusty magboots in the lounge!
- ATM for making sales.

**Statistics:**
- Tile count: 215 (Medium)
- Price: 34000 (Appraises at approx 29500. 15% markup applied)
- Crew: 2-4 

## How to test
Checkout the branch, load the ship!

## Media
2024-08-28 21_32_40-Frontier Station
Uninitialised, no spawns or subfloor.

2024-08-28 21_33_11-Frontier Station
Uninitialised, spawns and subfloor showing.

2024-08-28 21_35_17-Frontier Station
Initialised.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None, I would hope!

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added the SBB Bodkin, a new medium salvage shuttle.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
2024-07-28 11_46_33-Window
Recent changes. Added an extra wallmount charger in the cargo hold. Added a saw for medical purposes. Halved the number of cargo pallets.

**Comment by Tych0theSynth** [comment]
Having discussed the shuttle with Arimah a bunch, it's evident that this frame isn't quite right as an exped ship.
Converting to draft so I can rework it for a different role that it'll hopefully be better placed in!

**Comment by VividPups** [comment]
Looks like the sprinter really

**Comment by Tych0theSynth** [comment]
> Looks like the sprinter really

Not really! Doesn't have the nacelles for one! 
If anything, the profile is more similar to that of the Kestrel.

**Comment by Tych0theSynth** [comment]
Following maintainer feedback, the Bodkin has now been reworked into a salvage/mining shuttle. 
PR description will be updated **properly** tomorrow when I'm more awake, but screenshots have been replaced.

**Comment by MatthewBadger** [comment]
Reminds me of the Kestrel. It has a good profile, and i like the focus on living space. I really like the sharp, thin front, combined with the swooped sides and the chunky engines. It might want something to differentiate it more, since we have a lot of small-medium salvage vessels.

**Comment by Tych0theSynth** [comment]
Directional fans have replaced tiny fans.

**Comment by Tych0theSynth** [comment]
Played with signs as upstream changed them all. Added some shelves for extra storage. Played with the lightning a little.

**Comment by Jakumba** [comment]
I really like this, it feels a lot like big brother to the Loader and different from the Kestrel.
 I think she'd fun to do cargo runs with!

**Comment by Cheackraze** [comment]
Is the kestrel maintained or used much at all? I liked the kestrel but this would be a very nice replacement. I dont see anything wrong with the design and so long as the map checkers dont see anything wrong, we should get this in

**Comment by Tych0theSynth** [comment]
> Is the kestrel maintained or used much at all? I liked the kestrel but this would be a very nice replacement. I dont see anything wrong with the design and so long as the map checkers dont see anything wrong, we should get this in

I was actually hoping someone might say this. The Kestrel has not been updated for a long long time, and while it was never my intention to make this as a replacement for it specifically, it can absolutely fill that space.

**Comment by ErhardSteinhauer** [comment]
I vaguely recall updating Kestrel like midsummer maybe, but I'm inclined to agree that this shuttle is (imo) better at what Kestrel does and thus should replace Kestrel.

**Review by Cheackraze — APPROVED** [review]

**Comment by Cheackraze** [comment]
well, I do plan to do a comprehensive review of the current lineup anyway, might as well get it in and into players hands in the mean time.

**Pull request merged**
