### PR TITLE
NC Lantern - a medium-sized ship for Chaplains

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
A new vessel to help frontier chaplains carry the light of faith to the distant corners of known space. Key features:
- Spacious chapel for big sermons.
- Сhurch organ.
- Coffin-chute for space burial.
- Morgue with incinerator.

## Why / Balance
I feel like Chaplains would benefit from having more ships to choose from. Also: "spess lantern".

## Technical details
New .ymls

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame,

## Wiki Info
_"The Lantern is a medium-sized chapel-vessel equipped with everything chaplain might need in their never ending battle for salvation of NT personnel souls.",_ - The Shipyard.

**Ship Size:** Medium
**Recommended Crew:** 2-3+
**Cost:** $33500
**Power Gen Type:** Plasma, Solar
**Expeditions:** No
**IFF Console:** No
**Available Roles:** Chaplain

**Changelog**
:cl: erhardsteinhauer
- add: Added NC Lantern - a medium-sized ship for Frontier Chaplains.

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]
Good job!

**Comment by Cheackraze** [comment]
i like the idea and the design overall, however those massive glass sections need to be split up.  It makes the ship far too open and doesnt look so great.  Large glass sections are ok sometimes, but not huge areas like that. I feel you could break up those glass walls with normal reinforced ones and still maintain your original design goals with the ship.

**Comment by ErhardSteinhauer** [comment]
Tweaked ship a bit:
- Panoramic windows are split up.
- Added shutters to the main hall and cockpit.
- Added preflight checklist.
- Remapped wasteloop in the morgue.
- Added bodybag box.
- Price gone up, updated wiki info.
Pictures in PR are obsolete, here is the most recent one:

**Review by TsjipTsjip — COMMENTED** [review]
Facts:
- Price: 33500
- Spawned sale value (shipyard console): 29486

Major notes:
- Hv net and the SMES has a cable terminal loop. The cable leading out of the SMES and into the substation should not touch the cables coming from the generators, otherwise it shorts out the SMES entirely and leads to funky behavior.

Minor notes:
- Chaplain's side of the confessional booth is very dark right now and could use a light.
- Any reason you chose the opaque airtight plastic flaps for the funeral conveyor?

I like this ship! It's a nice build adding considerable role-play value.

**Comment by ErhardSteinhauer** [comment]
> Facts:
> 
> * Price: 33500
> * Spawned sale value (shipyard console): 29486
> 
> Major notes:
> 
> * Hv net and the SMES has a cable terminal loop. The cable leading out of the SMES and into the substation should not touch the cables coming from the generators, otherwise it shorts out the SMES entirely and leads to funky behavior.
> 
> Minor notes:
> 
> * Chaplain's side of the confessional booth is very dark right now and could use a light.
> * Any reason you chose the opaque airtight plastic flaps for the funeral conveyor?
> 
> I like this ship! It's a nice build adding considerable role-play value.

Thanks for pointing out all that. Fixed HV-net-SMES-Substantion wire loop, moved the lamp in the cockpit so light from it could illuminate all important corners there and replaced opaque flaps with clear ones.

**Comment by ErhardSteinhauer** [comment]
As for price I believe that ships usually have 10-15% markup. About 13.5% in case of this ship.

**Review by TsjipTsjip — APPROVED** [review]
All of my remarks were addressed! This looks good to me.

**Comment by MagnusCrowe** [comment]
I like pretty much everything about this, I'll review it properly later today, fingers crossed.

**Comment by Cheackraze** [comment]
my favorite part is the fax machine is reachable by the priest doing confessions. It has my approval, so long as all the bits are mapped correctly.

**Review by MagnusCrowe — APPROVED** [review]
This ship is a very good example to the community on how to design a ship.  It does what it's designed to do very well, it is not bloated with extra features, and atmos/power is laid out in a logical and accessible way.

Not sure if we want players to have crematoriums on their ships but if it becomes a problem we can always take it out later.

**Pull request merged**
