### PR TITLE
Replace Spectre's passive vent with air injector

### PR DESCRIPTION
**Pull request by mnemosynium**
## About the PR
Passive air vent in the Spectre's waste loop has been replaced with an air injector.

## Why / Balance
Ships shouldn't be using passive vents.

## Media

- [X] This PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**

N/A

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]
I pray this.

**Comment by dvir001** [comment]
passive vents are 100% fine to use, and should be used for atmos distro
You can also weld them off to keep gases inside.

**Comment by TsjipTsjip** [comment]
> passive vents are 100% fine to use, and should be used for atmos distro You can also weld them off to keep gases inside.

Do NOT use passive vents for distro lines. This needs to be a normal vent, otherwise you'll get CO2 and other waste gases inside your distro piping. Passive vents appear to be fine to use for waste egress lines.

**Comment by dvir001** [comment]
> > passive vents are 100% fine to use, and should be used for atmos distro You can also weld them off to keep gases inside.
> 
> Do NOT use passive vents for distro lines. This needs to be a normal vent, otherwise you'll get CO2 and other waste gases inside your distro piping. Passive vents appear to be fine to use for waste egress lines.

Passive just let anything in and out of it, so if you have one in space it will let stuff out, you can test it by replacing a scrubber with an air vent and having all you ship air go to 0

**Comment by TsjipTsjip** [comment]
> Passive just let anything in and out of it, so if you have one in space it will let stuff out, you can test it by replacing a scrubber with an air vent and having all you ship air go to 0

Yes, that's what they do, but you mentioned the distro line (i.e. blue pipes) which delivers air into the shuttle, not waste gases out of it. Sorry for the confusion.

**Comment by dvir001** [comment]
> > Passive just let anything in and out of it, so if you have one in space it will let stuff out, you can test it by replacing a scrubber with an air vent and having all you ship air go to 0
> 
> Yes, that's what they do, but you mentioned the distro line (i.e. blue pipes) which delivers air into the shuttle, not waste gases out of it. Sorry for the confusion.

*waste, sorry morning brain

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
