### PR TITLE
Port gavel from Delta-V (#660), better powdered wig, courthouse revamp

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds the gavel from [Delta-V#660](https://github.com/DeltaV-Station/Delta-v/pull/660), along with the gavel block, trial timer, and a separate audio set.

Edits the powdered wig sprite to have a back when viewed facing north.

Touched up the Courthouse:
- Added powdered wig, judge's robe, gavel and gavel block to the table
- Added a trial timer to the courthouse
  - Sin: currently mapped on a window block just so the rest of the court is visible and the thing isn't floating in the air.  Sucks, but A: we need a timer, and B: you should be able to see the rest of the courthouse.
- Moved the camera down by a square, rerouted the gas piping beneath it.
- Moved the FuelVend machines in the middle of the docks to the corners, moved them out by a square.
- Made the giant, 7-square long benches into two 3-square long benches with potted plants in between.
- Timer in the brig swapped to a security-access locked brig timer.

## Why / Balance

The gavel's been talked about for ages, and it's a nice touch, the trial timer looks better than the black metal ones.
The powdered wig always bugged me.
The Courthouse changes should give better QoL for whenever that place is used.

## How to test

1. Visit the courthouse, bang the gavel.
2. View the rest of the changes listed above, see if I didn't mess anything up.

## Media

Changes to the courthouse.  Judge's attire laid out on the table, timer located on the reinforced glass block.  Camera and scrubber moved down a tile.
courthouse

West dock, note the FuelVend in the corner.
west_dock

East dock, note the FuelVend in the corner.
east-dock

Courtyard, note the smaller benches.
courtyard

Wolfgang Amadeus Mothzart in the fluff.
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: whatston3 and leonardo-dabepis
- add: Added a gavel, gavel block, powdered wig to the courthouse.
- tweak: Remodeled the Courthouse slightly.

### CODE REVIEW

**Comment by dvir001** [comment]
There are 1/2 doors next to the top area that missing tiles under.

**Comment by whatston3** [comment]
> There are 1/2 doors next to the top area that missing tiles under.

There were four, should be fixed now.
Changed the gavel sound to a single bang, picked four out of the same sample audio.
Changed the trial timer text to white for readability.

**Review by dvir001 — APPROVED** [review]
He fixed (some of) my sins.
Waiting for maptainer to give it a look.

**Comment by dvir001** [comment]
Looked at the map changes in game, all small, fine to go.

**Pull request merged**
