### PR TITLE
Add GPS app to pirate PDAs

### PR DESCRIPTION
**Pull request by Bonaout**
## About the PR

Added the AstroNav program on pirate PDAs !

## Why / Balance

Pirate players tend to get lost in space with no ability to find where they are!

## How to test

- Spawn as a pirate/pirate first mate/pirate captain
- Take the PDA in hand to check if the coordinates are shown on the held item interface
- Open the Programs tab to check if the AstroNav program is installed

## Media

piratepda1

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- tweak: Pirate PDAs now have the AstroNav program

### CODE REVIEW

**Comment by dvir001** [comment]
Frontier notes required as per all added lines.

**Comment by Bonaout** [comment]
Something like this ?

**Review by dvir001 — APPROVED** [review]
Added the note

**Comment by Bonaout** [comment]
Ohh, I see what you mean now! Thank you!

**Pull request merged**
