### PR TITLE
Squeeze Bottles

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added simple squeeze bottle for ketchup & mustard

## Why / Balance
Cool looking on tables

## Technical details
.yml

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame,

image

## Breaking changes
N/A

**Changelog**
:cl: gentlebutter, dvir01
- add: Added squeeze bottles for ketchup & mustard.

### CODE REVIEW

**Comment by ErhardSteinhauer** [comment]
Important questions:
Can you actually squeeze those bottles? 
Do they make that "diarrhea sound" when low on ketchup/mustard?

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by dvir001** [comment]
> Important questions: Can you actually squeeze those bottles? Do they make that "diarrhea sound" when low on ketchup/mustard?

Yes but the game code is a bit limited on it so its just when you drink from it since there was no "On apply" function 

> Important questions: Can you actually squeeze those bottles? Do they make that "diarrhea sound" when low on ketchup/mustard?

Yes, im also adding it for other interactions with it

**Comment by MagnusCrowe** [comment]
Make it not make the poot sound when you pick it up.  Instead, make it poot when you squeeze it.

**Comment by ErhardSteinhauer** [comment]
> > Important questions: Can you actually squeeze those bottles? Do they make that "diarrhea sound" when low on ketchup/mustard?
> 
> Yes but the game code is a bit limited on it so its just when you drink from it since there was no "On apply" function "TransferSound" isnt a common comp that I can use unless i add new code just for this.
> 
> > Important questions: Can you actually squeeze those bottles? Do they make that "diarrhea sound" when low on ketchup/mustard?
> 
> Yes, im also adding it for other interactions with it

Terrific. Or terrifying.

**Comment by GentleButter** [comment]
They better be fartin

**Comment by MagnusCrowe** [comment]
image
Prepare for people to be using them as noisemakers if there's not a cooldown.

**Review by MagnusCrowe — APPROVED** [review]

**Comment by dvir001** [comment]
> image Prepare for people to be using them as noisemakers if there's not a cooldown.

I removed it to only have the sound when you managed to add it to food, so now it wont be used for spam,
While sad, its for the best.

**Pull request merged**
