### PR TITLE
Pioneer Rework

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Tweaks:
- Removed ore processor.
- Added 2 ore boxes.
- Split salvage [filled, hardsuit] locker in two: salvage [filled] and suit storage [salvage].
- Updated preflight checklist.
- Price gone up slightly: whatever was -> 15950.

## Why / Balance
Downgraded slightly to make Prospector and Chisel more appealing.

## Media
image
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Tweaked Pioneer - replaced ore processor with ore boxes. Note that raw plasma ore can be used as a fuel for generator.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
YML-wise, changes look sane. I disagree on removing the ore processor from a solo ship, when the alternatives you provide are intended for crews. That aside, I am not commenting on the balancing discussion, this is something for maintainers.

**Comment by ErhardSteinhauer** [comment]
> YML-wise, changes look sane. I disagree on removing the ore processor from a solo ship, when the alternatives you provide are intended for crews. That aside, I am not commenting on the balancing discussion, this is something for maintainers.

This is the result of discussion that took place at the feedback thread regarding Pioneer (https://discord.com/channels/1123826877245694004/1183813298530025544)

**Comment by dvir001** [comment]
Need the ore processor back, this is the kind of ship a new player gets and wont know what to do not having one.
The prospector, chisel are multi miners ships, no need to compare that much since they are targeted for group use.

**Comment by Cheackraze** [comment]
> YML-wise, changes look sane. I disagree on removing the ore processor from a solo ship, when the alternatives you provide are intended for crews. That aside, I am not commenting on the balancing discussion, this is something for maintainers.

I believe the goal was more to have the pioneer as more of a drone-ship to a larger vessel like a crescent or spectre.  Raw ore sells for the same as a refined sheets from a tier 1 ore processor, so for solo players it's not necessarily a nerf, and could potentially actually make hauling and selling ore faster and easier.

**Comment by Cheackraze** [comment]
> Need the ore processor back, this is the kind of ship a new player gets and wont know what to do not having one. The prospector, chisel are multi miners ships, no need to compare that much since they are targeted for group use.

The ore processor doesn't need to be in there, it's good that such a tiny ship doesn't have it.  It would encourage a player to seek one out, either find out where to buy one or build one or have one built for them etc.  And since t1 processor makes the same money as raw ore, it's not even a nerf to the money making side

**Comment by ErhardSteinhauer** [comment]
It is indeed much faster and less fiddly this way: no need to sit and wait for ore processor to finish spewing sheets. And since QoL changes to ore boxes were merged it's even smoother experience now than it was when I tested those changes.

**Pull request merged**
