### PR TITLE
Millenia Manufacturing attempt, has problems

### PR DESCRIPTION
**Pull request by Shodhans**
## About the PR

This is the first pass of Millenia Manufacturing, an factory left abandoned after space spiders hatched onboard.

This PR has issues. I have been unable to get my POI to actually spawn in game, despite having multiple people try to help me out. Hopefully, we're able to figure out why; odds are that it's something simple that I just didn't know about or skipped over, but I'm having a very hard time finding out exactly what it is and several others can't find it, either.

Also - I am aware that I forgot a gravity generator and will fix it with the next iteration.
## Why / Balance

I've been making this because I wanted to have more enemy-filled POI's, since I find them very fun, personally, and Check suggested making an abandoned factory. Thus, Millenia Manufacturing was born!
## Technical details

I modified NfAdventureRuleSystem.cs to mirror the code that is used for Grifty's and changed instances that applied to Grifty's to instead apply to the factory. I've, of course, added it to the POI map list (/maps/_NF/POI). I have run into some inconsistencies with other POI's and the BecomesStation component and the prototype files, so please assume that I've done everything wrong regarding those.
## Media
https://youtu.be/J1ppDFjgK44

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Added Millenia Manufacturing POI

### CODE REVIEW

**Comment by dvir001** [comment]
For all new and OLD POI, please make sure that the POI cannot be moved by any means with ships.

Fix this by editing the YML

`    - bodyStatus: InAir
      angularDamping: 999999
      linearDamping: 999999`

**Comment by Shodhans** [comment]
Done that on my build, will be in on next push - any idea why the POI isn't showing up? I tried to just copy the stuff other POI's had as you suggested and haven't been able to get it to work. Had a few other people look at it as well and they weren't sure either.

**Comment by dvir001** [comment]
@Shodhans It spawn now if you want to work on it.

**Comment by dvir001** [comment]
Closing this, please reopen if you still working on this POI.

**Pull request closed without merging**
