### PR TITLE
Goblin throat singing

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Added new emotes to goblins - throat singing.
Added gasping sounds for goblins.
Allowed goblins to use 'mutter' emote.
Allowed goblins to use 'hiss' emote.

## Why / Balance
Important.

## How to test
Spawn as a goblin
Type `@mutter` in chat for  'mutter' emote.
Type `@sing` in chat for throat singing.
Type `@hiss` in chat for hissing.
Type `@gasp` in chat for gasping.
Die to hear goblin last gasp.

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/9583b8b7-a7c9-4c67-985f-5edd298c4c4f

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
sanity

**Changelog**
:cl: erhardsteinhauer
add: Added new emotes to goblins; singing and mutter.
tweak: Added gasping sounds for goblins.
fix: Allowed goblins to use 'hiss' emote.

### CODE REVIEW

**Comment by dvir001** [comment]
Worth adding it to Harpy or nah?

**Comment by ErhardSteinhauer** [comment]
> Worth adding it to Harpy or nah?

No. Goblins only. Also, don't merge yet.

**Comment by ErhardSteinhauer** [comment]
A'ight, all fixed now, ready for review.

**Comment by whatston3** [comment]
I think those singing emotes need to be cut down to maybe a second or two tops.
Apart from that, seems reasonable.

The cause for emote spam asphyxiation grows ever stronger.

**Comment by ErhardSteinhauer** [comment]
But that won't be a singing then. Just throat noises.

**Comment by ErhardSteinhauer** [comment]
> The cause for emote spam asphyxiation grows ever stronger.

Spamming emotes is NRP tbh

**Comment by ErhardSteinhauer** [comment]
But probably can chop files into ~10 sec fragments I guess. Not exactly stoked about it though.

**Comment by ErhardSteinhauer** [comment]
Cropped 30 sec long sound files to 4-10 sec length.

**Review by whatston3 — APPROVED** [review]
Looks alright, works alright.

Seems spammable, but I'm kind of curious to see how it gets used and I like the weird flavour.

**Comment by ErhardSteinhauer** [comment]
Added gasping sounds for goblins and enabled 'hiss' emote.

**Comment by ErhardSteinhauer** [comment]
@dvir001, yay or nay, eh?

P.S.: if it's "nay" I'll petition to ban you until it's "yay"

**Pull request merged**
