### PR TITLE
NC Harbormaster, a tugboat

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
_"A small tugboat"_, - Shipyard.
**Ship size:** Small (129 tiles)
**Recommended crew:** 1
**Cost:** 29500
**Power Gen Type:** Plasma
**Expeditions:** No
**IFF Console:** No
**Available Roles:** Pilot

## Why / Balance
An affordable ship for towing derelict ships to/from Frontier Station (or future Ship Building/Decommissioning Engineering POI) or a weapon of terror for STCs.

## Technical details
.yml

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- add: Added NC Harbormaster, a tugboat.

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]
I honestly dont really use the use for a "tugboat", like its very limited and its just look like a ship you can easly just make from Construct, i just dont see peoples using this ship.

Other then that, all seem in order.

**Comment by MagnusCrowe** [comment]
> I honestly dont really use the use for a "tugboat", like its very limited and its just look like a ship you can easly just make from Construct, i just dont see peoples using this ship.
> 
> Other then that, all seem in order.

I think the point is that it is a small ship with very strong thrusters for pulling ships away from the station or towing in ships that need to be dragged back to the station.  It's a niche ship for valet's.

**Comment by MagnusCrowe** [comment]
I like the aesthetics I'll give it a proper look soon.

**Comment by ErhardSteinhauer** [comment]
Updated the ship to current standards and updated the images in PR:
- Replaced Salvager Job with Pilot Job.
- Added Station Records Console.
- Swapped consoles for tabletop versions.
- Added Suit Wallstorage Unit [Pilot].
- Mapped defib.

**Comment by MagnusCrowe** [comment]
> Updated the ship to current standards and updated the images in PR:
> 
> * Replaced Salvager Job with Pilot Job.
> * Added Station Records Console.
> * Swapped consoles for tabletop versions.
> * Added Suit Wallstorage Unit [Pilot].
> * Mapped defib.

Are you sure you did all that?  This is what I see when I grab your branch.

image

**Comment by ErhardSteinhauer** [comment]
> > Updated the ship to current standards and updated the images in PR:
> > 
> > * Replaced Salvager Job with Pilot Job.
> > * Added Station Records Console.
> > * Swapped consoles for tabletop versions.
> > * Added Suit Wallstorage Unit [Pilot].
> > * Mapped defib.
> 
> Did you forget to push? This is what I see when I grab your branch.
> 
> [image]

ACK! Forgor to push the changes. Should be fixed now.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
