### PR TITLE
NM Spirit SAR Shuttle.

### PR DESCRIPTION
**Pull request by Actualcatmoment**
## About the PR

Adds a new shuttle, a very small SAR ship called the "Spirit"

## Why / Balance

Medical has absolutely abysmal profit margins as it is, an affordable bare-bones option seemed like a good idea. At 15.5K spesos this thing is barely more expensive than a pioneer and comes equipped with just the necessities for recovering casualties and little else.

## Media

V3.0 screenshot
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Cute ship, I'm concerned about the vending machines being a target for people.  I imagine a fair amount of players will purchase the ship just to take the machines off and then sell it.

I'm discussing a solution to this with the other maintainers.

In the meantime, consider re-working that airlock on the right side, it should be two doors, not just one that opens to space.

**Comment by Cheackraze** [comment]
the pulse should also have its vending machine status checked. I think for this size, we should stick with the walmount vending machine.

**Comment by ThatOneGoblin25** [comment]
Could make the vends unanchorable.

**Comment by Actualcatmoment** [comment]
Alright, I'll extend the airlock. As for the vendor, the wall mounted one seems like a good idea both to make yoinking it harder and to free some of the precious floor space. I may also replace all the walls with shuttle walls.

Also another thought I've just had is that given the minuscule size of the ship it's probably a fun option for the mother-ships that are already in the game to be able to spawn them.

**Comment by MagnusCrowe** [comment]
> the pulse should also have its vending machine status checked. I think for this size, we should stick with the walmount vending machine.

Perhaps instead of just adding a medical vendor to these types of ships, we should force them to rely on medical techfabs?  It might be more cost effective for the paramedics...you can find the materials you need off of wreckage in your downtime between calls or get it from salvagers...

**Comment by Actualcatmoment** [comment]
> > the pulse should also have its vending machine status checked. I think for this size, we should stick with the walmount vending machine.
> 
> Perhaps instead of just adding a medical vendor to these types of ships, we should force them to rely on medical techfabs? It might be more cost effective for the paramedics...you can find the materials you need off of wreckage in your downtime between calls or get it from salvagers...

That could work, in my experience though the cloth spawns are fairly rare, and epinephrine is likewise essential though very difficult to produce and would be a pain to acquire on such a tiny ship. The med vendor at frontier would be the only option to acquire that essential chem but it's usually sold out within 30 seconds of a round starting. that said having a medifab and a wall mount nanovend could be an option. IIRC the wall mounted vendor has a limited selection/stock anyway but it solves the epi problem through to midround. In my experience a bottle of epi is only really good for 2 revives, maybe 3 if you get there before they take too much damage.

OR, have a wall mounted para/med locker instead which will allow responding to distress calls early in the round but still necessitate engagement with scavenging to stock up the medfab/chemical supplies, or buy chems/be resupplied by a mothership. BUT, the problem still becomes people abusing the price of a ship this size to acquire easy roundstart medical supplies, essentially as a 5000 speso first-aid crate.

**Comment by Cheackraze** [comment]
> > > the pulse should also have its vending machine status checked. I think for this size, we should stick with the walmount vending machine.
> > 
> > 
> > Perhaps instead of just adding a medical vendor to these types of ships, we should force them to rely on medical techfabs? It might be more cost effective for the paramedics...you can find the materials you need off of wreckage in your downtime between calls or get it from salvagers...
> 
> That could work, in my experience though the cloth spawns are fairly rare, and epinephrine is likewise essential though very difficult to produce and would be a pain to acquire on such a tiny ship. The med vendor at frontier would be the only option to acquire that essential chem but it's usually sold out within 30 seconds of a round starting. that said having a medifab and a wall mount nanovend could be an option. IIRC the wall mounted vendor has a limited selection/stock anyway but it solves the epi problem through to midround. In my experience a bottle of epi is only really good for 2 revives, maybe 3 if you get there before they take too much damage.
> 
> OR, have a wall mounted para/med locker instead which will allow responding to distress calls early in the round but still necessitate engagement with scavenging to stock up the medfab/chemical supplies, or buy chems/be resupplied by a mothership. BUT, the problem still becomes people abusing the price of a ship this size to acquire easy roundstart medical supplies, essentially as a 5000 speso first-aid crate.

that is essentially the problem we have. We want these gameplay loop options to be relatively affordable for a newer player to participate in with the smaller med ships, but that then allows anyone with a bit of cash to just loot a ship for a high price. Its why we move to more vending machine available items vs. mapped/locker items in the first place.

Ideally, a larger med ship or a future medical POI would have more available facilities to assist a smaller med ship like this.

**Comment by Cheackraze** [comment]
> > the pulse should also have its vending machine status checked. I think for this size, we should stick with the walmount vending machine.
> 
> Perhaps instead of just adding a medical vendor to these types of ships, we should force them to rely on medical techfabs? It might be more cost effective for the paramedics...you can find the materials you need off of wreckage in your downtime between calls or get it from salvagers...

just noticed this reply. That is definitely an option, although the medical fab recipe list should probably get a good revision.

**Comment by Actualcatmoment** [comment]
Forgive my goofy commits and forced pushes, this is straight up the first time i have ever used git. HOPEFULLY everything should be set-up and good to go. I've not got any other ideas for the spirit right now.

**Review by MagnusCrowe — APPROVED** [review]
image

**Pull request merged**
