### PR TITLE
Handheld Mass Scanner

### PR DESCRIPTION
**Pull request by Temoffy**
## About the PR
Added handheld mass scanner.

## Why / Balance
Very useful for spacewalks, search and rescue, and related spacewalk-inducing situations, like guiding a ship toward you rather then hoping they are good enough with a gps. Or making a short trip to a spaceship that spawned near the station.

## Technical details

One yaml file, 2 pngs, and an extra if statement in the radar code.
## Media

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None
**Changelog**

:cl:
- add: Handheld mass scanner in AstroVend!

### CODE REVIEW

**Comment by Kesiath** [comment]
Would be perfect to add to either AstroVend or BountyVend. Thanks for this!

**Review by Cheackraze — APPROVED** [review]
amazing.

Only two very minor issues that I fixed to get this in asap: sprite location needs to use forward slashes not back slashes, and your license had an extra space at the end.

**Comment by TheShuEd** [comment]
Hi. I forgot to ask a bit, but I hope you don't mind if I use your builds in the main game repository?
https://github.com/space-wizards/space-station-14/pull/25526

**Comment by Temoffy** [comment]
I don't mind, but if you are making it official you really might want to see if you can lock the radar screen upward to the player's upward. It is currently based on the character's orientation because I couldn't figure out how to read the user's view angle. It would go in Content.Server/Shuttles/Systems/RadarConsoleSystem.cs line 39 if you can figure it out.

**Comment by TheShuEd** [comment]
We've got a big mass scanner refactor coming up, I'll pass that along.

**Pull request merged**
