### PR TITLE
Remove the science tech fab

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
[Removes the science techfab, as it's rendered useless compared to the protolathe], if you have a sci ship you will be using a normal [functional] Protolathe that [provides] the same [function.]

## Why / Balance
Its a copy paste machine, [it is superseded by the protolathe and not needed].

## How to test
Buy gourd, see 2 protolathes, asked yourself why it was even mapped to begin with.

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
- remove: Science techfabs have been removed in favor of using the protolathe.

### CODE REVIEW

**Comment by whatston3** [comment]
Honestly, fair.

**Comment by whatston3** [comment]
Might be worth replacing that extra science techfab with a machine frame on the gourd.

**Comment by dvir001** [comment]
> Might be worth replacing that extra science techfab with a machine frame on the gourd.

Fixed

**Comment by whatston3** [comment]
Given that the three ships that have them also have mapped protolathes, this seems fine to me.  Caution downstream, I suppose.

**Review by whatston3 — APPROVED** [review]
Makes sense to me - if others have stronger feelings for/against, all ears.

**Pull request merged**
