### PR TITLE
Make voice mask not working in radio

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Normal voice mask no longer fully work in radio, it shows name as unknown

Added 2 new masks for admins
One that fake the name on radio and one that only shows real name on radio

## Why / Balance
Its near impossible to locate someone who is pretending to be someone else on the radio in frontier.

## Technical details
A bit of a revert of https://github.com/space-wizards/space-station-14/pull/13858

## Media
N/A

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- tweak: Voice masks over radio shows you as "Unknown".

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
Heeey inst it like the goal of the Voice Mask? i seen many server use it for that purpose.

**Comment by IData-RedactedI** [comment]
Yeah I agree with Foxxo, it kinda defeats the point of the voice mask

**Comment by dvir001** [comment]
Ill see about adding 2 versions on the mask so admins can still have the old version
Also ill leave this open for more talking about it

**Comment by dvir001** [comment]
This is done

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by Cheackraze** [comment]
i understand the intent of the object, but dvir001 is correct that 9/10 times its being used to just LRP troll stc and security.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
