### PR TITLE
More descriptive ship sale & cryo pod messages

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds more descriptive error messages when trying to sell docked ships and enter a cryo pod.  If there are multiple organics aboard, the error message will name the first one that is onboard.

## Why / Balance

Hunting for something you don't know is annoying.  Trying to arrange a Crescent sale when somebody's gone SSD or something's gained consciousness without your knowledge is a pain.

## How to test

1. Start a server, join on two clients.
2. Buy a ship on client 1.
3. Walk onto the ship on client 2.
4. Try to sell the ship on client 1, it should tell you that client 2's character is aboard.
5. Move the ship on client 2.
6. Try to sell the ship on client 1, it should tell you that the ship is undocked.
7. On client 2, dock the ship, spawn a pAI, start looking for AI.
8. On client 2, /ghost and take the pAI.
9. On client 1, pick up the pAI, run to the cryo pod.
10. Try to enter the cryo pod, the pod should tell you about the pAI in your inventory.

## Media

crew must disembark
sus amogus
must be docked
syndie_ai_cryo

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: When selling a ship, the console will tell you who is onboard, or if the ship is undocked.

### CODE REVIEW

**Comment by dvir001** [comment]
Bless

**Comment by dvir001** [comment]
AAAAAAAAAAAAAAAAAAAAAAA

Can probably fit it in before the merge

**Comment by whatston3** [comment]
> AAAAAAAAAAAAAAAAAAAAAAA
> 
> Can probably fit it in before the merge

Give me a bit, I'll fix the issues and rework that cryo chamber message, wasn't super fond of how it read.  Working on pushing something to the upstream-merge.

**Comment by whatston3** [comment]
@dvir001 Good to go.

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
