### PR TITLE
Dragonfly (Update)

### PR DESCRIPTION
**Pull request by crystalHex**
## About the PR

- Fixed overlapping pipes

- Internal 'shuttle walls' are now 'internal shuttle walls'

- Fixed fuel jar not being in the controller on purchase

- Removed mapped trash spawners and food

- Removed bar

- Replaced chemistry equipment with a rollerbed and paramedic's equipment

- Re-decorated the lounge area

- Re-decorated the salvage bay

- Expanded cargo bay by moving table to lounge

- Added spare conveyor belt assemblies

- Added suit storages for all crew members

- Added port and starboard lighting

- Updated ship description

## Why / Balance

Major shipyard rebalance + Dragonfly's atmos set-up broke after a merge

## How to test

1. Open lodge shipyard console.
2. Purchase Dragonfly

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Fixed Dragonfly pipes, unpowered thrusters and interior walls.
- tweak: Re-balanced Dragonfly, replaced chem wing with triage wing, removed food and bar, increased cargo space.

### CODE REVIEW

**Comment by dvir001** [comment]
Picture?

**Comment by crystalHex** [comment]
The front:
dragonfly-fore
The back:
dragonfly-aft

(Yes, I know the wires don't have to extend that far, that was just to make routing power to any front expansions easier)

**Comment by dvir001** [comment]
Keep in mind were removing all mapped food, mapped trash spawn and bars from most ships that are mining focus

With major edits to chem areas and medical area to only have medical bed and locker. this ship will get a major refactor later, or now if you can assist on it now please.

**Comment by crystalHex** [comment]
Yeah I can probably do that next week, whenever I have time.

How extensive should the rework be?

**Comment by dvir001** [comment]
> Yeah I can probably do that next week, whenever I have time.
> 
> How extensive should the rework be?

Look at the bulker PR
https://github.com/new-frontiers-14/frontier-station-14/pull/1625

Were doing big balance changes to all ships, and stepping down the medical and food aspects of ships that don't have this function as the main ones (Isn't a medical / food ship)

**Comment by dvir001** [comment]
Either way im ok with this as a pre extended PR edit

**Comment by crystalHex** [comment]
Will try to re-fit the Dove before end of week as well.

**Comment by MagnusCrowe** [comment]
image
not sure if this is an issue with the ship itself or something else...can you look into this and provide a picture of it working if possible?

**Comment by dvir001** [comment]
image

**Review by ErhardSteinhauer — APPROVED** [review]
Tested, works fine.

**Pull request merged**
