### PR TITLE
Bocadillo Update

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
Updated Bocadillo:
- Added waste loop, mapped emergency lights, firelocks.
- Removed cables from under the walls.
- Mapped drain.

## Why / Balance
To curb CO2 build up.

## Technical details
.yml changes

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Tweaked Bocadillo - added atmos and drain.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
YML-wise, this PR does what was described.

**Comment by dvir001** [comment]
No desk bell on the table, unplayable.
Also you can just pre wrench the generator and air tank to remove the wrench.
Seem good.

**Comment by ErhardSteinhauer** [comment]
> O2 locker in weird place

Couldn't find not awkward place for it. Those wall lockers tend to grab every item in front of them, so can't really map it above tables or behind lockers/fridge.
Maybe should move it above Deep Fryer, to skim off couple milliseconds for chefs.

**Comment by dvir001** [comment]
> move it above Deep Fryer,

Open locker, deep fry the eva suit.

**Comment by ErhardSteinhauer** [comment]
> > move it above Deep Fryer,
> 
> Open locker, deep fry the eva suit.

As god intended

**Review by MagnusCrowe — APPROVED** [review]
Looks good.

**Pull request merged**
