### PR TITLE
Loadouts: fix Lawyer, Janitor slot names, remove Chaplain loadout

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Created loadout entries for the Janitor and Lawyer roles.
Originally: Reordered Chaplain loadout categories: mask should be in its correct place.
Edit: Removed Chaplain from Jobs tab in Character Setup window.

## Why / Balance

Consistent loadout screen look compared to other roles.  Originally brought up in #1422 ([comment here](https://github.com/new-frontiers-14/frontier-station-14/pull/1422#pullrequestreview-2079599715)).

## How to test

1. Build and run local server.
2. Open Loadouts screen for Janitor and Lawyer.
3. Check that all expected items are available in the proper tabs.  All role-specific items should be free.
4. There should be no entry for Chaplain under the Jobs tab in the Character Setup window.

## Media

New loadout screens:
janitor-layout-new
lawyer-loadout-new

Old loadout screens:
janitor-layout-old
lawyer-loadout-old

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Lawyer and Janitor loadouts now have consistent tab names and order.
- tweak: Removed Chaplain from Jobs tab in Character Setup.

### CODE REVIEW

**Comment by dvir001** [comment]
Based

**Review by dvir001 — APPROVED** [review]
Seems fine yml size, Ill try to test it today in game before merging.

**Comment by Cheackraze** [comment]
Chaplain gear is already in contractor loadouts and the role needs removal from ships n preferences

**Comment by whatston3** [comment]
> Chaplain gear is already in contractor loadouts and the role needs removal from ships n preferences

Revert Chaplain changes, then?

**Review by Cheackraze — CHANGES_REQUESTED** [review]
Remove chaplain loadiut stuff, instead remove all references to the chaplain on ships and in preference UIs

**Comment by whatston3** [comment]
> Remove chaplain loadiut stuff, instead remove all references to the chaplain on ships and in preference UIs

Chaplain files removed, Chaplain job prototype `setPreference` set to false, no entries for "Chaplain" in Shipyard files.  Looks good under local test, requesting another review.
image

**Comment by VividPups** [comment]
If the Chaplin is remove how would we be able to used the bible?

**Comment by whatston3** [comment]
> If the Chaplin is remove how would we be able to used the bible?

Admemes, sadly.  This PR doesn't remove hotjoining as a Chaplain - that's already been done (#1427 for ships, and #1346 for Frontier Outpost ([this particular commit](https://github.com/new-frontiers-14/frontier-station-14/pull/1346/commits/cbd2f9aab5536a920b9122fa01e9b81af35b6134))), this only updates the UI so you don't have controls to affect things you aren't able to use.

**Comment by VividPups** [comment]
Could it be where if you join with a Bible you get the worthyness?

**Comment by Cheackraze** [comment]
this is potentially do-able within loadouts themselves, since a loadout entry is capable of being multiple items already. Needs some testing but you might be able to move the comp to an implant or something and have it auto-implant you similar to other loadouts

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
