### PR TITLE
NC Piecrust: Update

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Updated the NC Piecrust. 
Shuttle had a few issues, and needed a little bit of love to fix those, and I made some improvements to the design also.

## Why / Balance
The shuttle had some problems such as multiple counters on one tile, a custom filled freezer and also required updates to use directional fans and proper mixed canister distro. Since its inception, we've also added things such as the service techfab, materials lockers, fuel lockers, button frames and fancy tables, so I added some of those things as well. 

I really like this shuttle, and I'd say it's my favourite small food ship, but being larger than the Bocadillo, it felt a little lacking in the hydroponics department. I'm hoping that with an extra tray and with vendors it will be a bit more attractive. 
It also felt like it needed extra windows for the customers to enjoy a view outside, so I added those too.

Grid appraises now at 23614, largely due to grav gen price changes, so the price has been reduced to 26000 which is a markup of around 10%.

## How to test
Checkout the branch, buy the ship.

## Media
image_2024-09-12_12-45-26

2024-09-12 12_45_45-Window

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None!

**Changelog**
:cl:
- tweak: Updated the NC Piecrust.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
@MoistBiscuits Tagging you as this PR suggests changes to a shuttle you designed.

**Comment by Tych0theSynth** [comment]
image

**Comment by Tych0theSynth** [comment]
> Ah ha, great timing. I was just typing up a question asking about the gun poster!

Yeah I just forgot to added an uninitialised pic

**Comment by MoistBiscuits** [comment]
Great wrok! Big fan of the decal improvments and moving the atmos to the bridge. The original design only had 3 trays to keep it in line with the other small ships since it came with a drinks dispencer whereas other service ships did not. 4 trays should be fine, it was a common complaint with the ship.
Overall good work, I'm more than happy with the proposed changes.

**Comment by dvir001** [comment]
Made a small edit

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
