### PR TITLE
KnuckleVerse (New) - Bboxing ship

### PR DESCRIPTION
**Pull request by Batuh1n**
## About the PR

Adds a new ship, SW KnuckleVerse

## Media
image
image

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Batuh1n** [comment]
I might've accidently used 2 accounts, it is all me though.

**Comment by Batuh1n** [comment]
-Added pilot job
-Added EVA storage closet, defib, fire extinguisher and changed the design a bit
-Adjusted the price again
-Decreased the amount of forward thrusts. It was too fast.
image
image

**Comment by Cheackraze** [comment]
i like the idea, however is this intended for the scrapyard? you seem to be going for more of the 'back alley maints rage cage' vibe with it, and I think you should lean into it a bit more if that is the case. You can also add the boxer job to the prototype if you'd like as well. I can fix up this branch's conflicts if not tonight, then soon this week.

**Comment by Batuh1n** [comment]
It was intended for the normal shipyard. The "SW" branding I put is quite similar to the scrapyard branding tho so, I should probably change that. I can try to lean more into the vibe you say, too. But not really sure how to.

**Comment by Cheackraze** [comment]
ok, i fixed up your mistaken file change. Make sure to update your local repository before making more changes. This all looks good to me, and we can put it in the main shipyard, but we may eventually move it to a different one or a 'themed' shipyard in the future. I'll let @MagnusCrowe do a review too

**Review by MagnusCrowe — CHANGES_REQUESTED** [review]
image
You're missing a wall here.

image
Replace these generators with the ship version.  The ship versions are half filled, anchored, and running on purchase.

image
Your atmos here is pretty sus.  The red pipe just ends at the wall, you have a scrubber attached to distro, and you have no other scrubbers in this part of the ship.  Generators produce CO2 so you need to fix this.

Also your power setup is not standard, please refer to a powering guide and fix your wiring in the generator room.

image
image

You don't need air sensors.  Every vent and scrubber has one built in.

image
Last but not least, you need to replace all the internal reinforced walls with normal walls.
The only place a ship like this could argue for reinforced walls is on tiles that border space.

**Comment by Batuh1n** [comment]
image
-Atmos probably fixed
-Fixed walls
-Boxer role added
-Changed company callsign to SSC so it is more unique
-The wirings in engine is still not standart. When I do it the normal way, power flickerings happen which is quite annoying sometimes. It works just fine this way so I think it should be ok?
image

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
