### PR TITLE
Adds the Gourd, A dedicated Science/Expo vessel with a kitchen and bar.

### PR DESCRIPTION
**Pull request by YumiGumi**
## About the PR

Added a new Expeditionary vessel called the Gourd

## Why / Balance
N/A

## Media
<Gourd2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the Gourd, the first introductory vessel of the S.L.E.S.I Faction. It's a dedicated Science Expeditionary vessels designed to fill a hole that is missing in the current ship lineup.

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
- One thruster is toggled off.
- AME is off on init, its very recomended to have all AME with at least 1 Fuel in it and online on init (and with correct power setting (for ya ship put a 4 Core injection))
- Missing Grills under windows near kitchen/bar.
- Captain Spawn Point is unneeded.
- Random Artifact Spawner is... extremly risky (you can buy a ship and its insta explode), tho if you really wana spawn one, make it spawn inside a Artfact Container.

Suggestions:
- Free AME Fuel Crate? i think its best that peoples should buy their fuel, but i recomend you leave like 1-3 fuel around. (most ship have 1 extra around ("take note that AME is already on on mapload"))
- Bridge with no grill? i undderstand there glass under it and this is just a suggestion but hell this may be easy to break... meh!
- Your file name/becomestation component should not be have any capital letters, could make issues.

**Comment by YumiGumi** [comment]
I'll make some adjustments as needed. Some points of my own would be:

- Are grilles required for internal windows, primarily regarding the kitchen and bar?
- The lack of grilles on the bridge is an aesthetic choice but i'll do my own testing to check general durability of it.
- I dunno how to spawn the artifact within the container, but if unable to figure things out, i'll just remove it.
- I'll look into changing the AME setup and the extra fuel crate.

I do appreciate the feedback and will look into adjusting as needed and fixing where necessary.

**Review by FoxxoTrystan — APPROVED** [review]
Good job overall!

Tiny suggestion:
Replace Cargo Pallet with Catwalks.

**Comment by YumiGumi** [comment]
if i get more notes regarding it, i will make the change, but i don't really wanna do another commit just for that.

**Comment by McBosserson** [comment]
I think the AME fuel crate is fine because other similarly sized ships come with one too.

If you're going to add some, it'd be nice if there were easy access points to all the thrusters, like the Praeda. At least at the middle clusters. I think a door with a tiny fan would do, and maybe replace the lattice under the maintenance area, and maybe thrusters, with plating.

Is that fireaxe cabnet in the bridge empty? I'm just going off the image.

**Comment by YumiGumi** [comment]
it's an uninitialized picture, so the fireaxe spawns when the ship is properly generated. adding the thruster access points would change the ship's hull and make it much more difficult to do, i can see about removing those windows in the center of the ship and adding a tiny fan airlock on either side. Regarding the lattice, i'm going to assume you mean on the rear blast doors and thrusters, which could be taken into consideration, but i don't think it's heavy enough of a change to warrant running another commit for. A few of the other issues have been taken care of in a prior commit and I've not taken a more updated picture.

**Comment by McBosserson** [comment]
I was asking for easy access, by airlock and tiny fan, to the thruster cluster next to science and cargo. There was space so I thought it could fit without any trouble. And if you were to do that, it would be nice to have plating instead of lattice incase the ship warps when someone is doing maintenance out there, for some reason.

**Comment by YumiGumi** [comment]
we can just freely ignore i pushed it twice since i'm a dumbass

**Comment by YumiGumi** [comment]
Gourd2
Updating with current and accurate image. Map has been initialized and Shadows were disabled.

**Review by Cheackraze — CHANGES_REQUESTED** [review]
I loaded this one up and did a full review, everything looks good except there are way too many lights. You could easily remove 3/4 of the lights and you wouldnt even know the difference. In particular, your science blast doors have a light on them that shouldnt be there, and also fixtures on top of glass windows isnt the greatest either.

Just a quick work over all the lights, try to use as few lights per room as possible, and once thats done we can merge!

**Comment by YumiGumi** [comment]
> I loaded this one up and did a full review, everything looks good except there are way too many lights. You could easily remove 3/4 of the lights and you wouldnt even know the difference. In particular, your science blast doors have a light on them that shouldnt be there, and also fixtures on top of glass windows isnt the greatest either.
> 
> Just a quick work over all the lights, try to use as few lights per room as possible, and once thats done we can merge!

I'll move to remove the excess lights, though will add the lights around the blast chamber on the windows is mainly to provide light within the chamber without them being at risk for going boom themselves. I can see about redoing them, but providing light inside is more of a pain if done any other way.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
