### PR TITLE
Sakuratsu

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
adds a new ship, the sakuratsu, its a medium sized ship that can do salvage and has a decent amount of living space that can be rennovated or whatever
its in the medium category for the shipyard, at a price of 65000, in the salvage category.

## Why / Balance
i wanted to make a ship for frontier, and i thought the current salvage/cargo ships were kinda boring ish.

## How to test
buy it in the shipyard, for 65000

## Media
image
image
image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
this doesnt change any other files

**Changelog**
:cl:
- add: Added the Sakuratsu to the shipyard.

### CODE REVIEW

**Comment by starch70** [comment]
Oh fuck dont accept this yet my cables are so fucked up i have to redo all of them

**Comment by whatston3** [comment]
> Oh fuck dont accept this yet my cables are so fucked up i have to redo all of them

All good, just mark it as ready when you think it's good to go.

**Comment by starch70** [comment]
> > Oh fuck dont accept this yet my cables are so fucked up i have to redo all of them
> 
> All good, just mark it as ready when you think it's good to go.

ok i think i updated the PR, how do i mark it as ready? never used github before this.

**Comment by whatston3** [comment]
> > > Oh fuck dont accept this yet my cables are so fucked up i have to redo all of them
> > 
> > 
> > All good, just mark it as ready when you think it's good to go.
> 
> ok i think i updated the PR, how do i mark it as ready? never used github before this.

image

**Comment by Tych0theSynth** [comment]
So I have some thoughts on this thing, simply based around the intended function.

I want to start by saying I think this is a good looking ship. While extremely similar to the Spectre, I think it looks nicer.

Now, I have some questions around the concept of this ship:
Why do you think there aren't any salvage ships with science equipment?

Why do you think most science ships generally don't come with salvage equipment?

As someone who has dumped a lot of hours into Frontier sci and mining, why would I pick this over one of the existing ships?
Why would I not just pick something with a full-size and far stronger xenoarch lab and just retrofit an ore processor? As it stands, one bad node could take out your research server.

Why does it have a fully functioning bar? Did you know that one of our existing science ships, the Investigator, used to have one? It used to have salvage, too, and that was removed.

There are also efforts underway to specifically reduce the number of multifunctional ships, instead making them really really good at one function, so they can efficiently work together.

I know you made this thing in a very short space of time, and while at a glance it seems like you've generally understood the mapping guidelines, it feels rushed and I genuinely feel like you need to give it more time in the oven in order to truly get the best out of it.

That being said, I'm not a maptainer. I don't make the decisions on whether it gets added or not, but I do know they'll raise the questions I've asked above.
Good luck!

**Comment by starch70** [comment]
yeah, i should remove the bar and move the research server somewhere else. i just thought it would be neat to have a salvage ship that can actually use the artifacts it finds

**Comment by starch70** [comment]
ok, i updated it a bit to remove the rooms that would make it multifunctional or whatever.

**Comment by starch70** [comment]
can i get a review yet?

**Comment by VividPups** [comment]
> can i get a review yet?

Reviews happen randomly when the Maptainers do them (there is only 2)

**Comment by starch70** [comment]
> > can i get a review yet?
> 
> Reviews happen randomly when the Maptainers do them (there is only 2)

ah ok

**Comment by Tych0theSynth** [comment]
Expect to be waiting upwards of a month. There are lots of other ships waiting!

**Comment by dvir001** [comment]
> Expect to be waiting upwards of a month. There are lots of other ships waiting!

A month? Are we speed running?

**Comment by starch70** [comment]
ok updated my ship yml and the pictures again

**Comment by dvir001** [comment]
Are you also adding ship guide entry?

**Pull request closed without merging**
