### PR TITLE
LGH Bonfire

### PR DESCRIPTION
**Pull request by Pixeltheaertist**
## About the PR

This adds a new small vessel called the Bonfire, a RP focused, recreational ship that allows crews to relax and have their own "cabin" in space. It could also be retrofitted relatively easy for food or a bar. 
(This is the first ship i've made for Frontier so let me know if i screwed something up lol)
## Why / Balance

I was told we needed more RP focused ships, and I've always wanted a ship that fit that homey, space cabin feeling that some other ships lack. It's also designed by the League of Galactic Hitchhikers, which is reflected in the relaxing build style. The catwalks on the exterior also reflect that as spots for hitchhikers to safely stay at if they wish, of course that's not a requirement for owning the ship.
## Media

image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Pixeltheaertist
- add: Added the LGH Bonfire, a new RP focused space lounge designed by the LGH!

### CODE REVIEW

**Comment by dvir001** [comment]
Fix your scrubber network and air to get into all rooms, auto start mixer and pumps.

**Comment by Pixeltheaertist** [comment]
> Fix your scrubber network and air to get into all rooms, auto start mixer and pumps, wrench the canisters.
> 
> Mini Gyro?
> 
> This ship is too small for a captain locker.
> 
> Fire hazard IRL image

Will do! Can I place pipes under walls for the air and scrubber system? Also if I move the fireplace to an adjacent corner or place steel around the flooring near it to have it closed away from wood is that fine? Thanks for the feedback! 🫡

**Comment by dvir001** [comment]
> > Fix your scrubber network and air to get into all rooms, auto start mixer and pumps, wrench the canisters.
> > Mini Gyro?
> > This ship is too small for a captain locker.
> > Fire hazard IRL image
> 
> Will do! Can I place pipes under walls for the air and scrubber system? Also if I move the fireplace to an adjacent corner or place steel around the flooring near it to have it closed away from wood is that fine? Thanks for the feedback! 🫡

Pipes under walls is fine if there is **no other options**, so most times one line will be under door and one under a wall next to it when you have to.

Not sure about the fireplace placement but should have a floor type under it that wont burn the place down + no wood Infront of it or close to its side, in general it need to have space around it or walls.

**Comment by Pixeltheaertist** [comment]
@dvir001, i've made the gyro small, anchored the canisters, and the pipes go into every room. I had to put the scrubber under the gyro since space was extremely tight, if that's 100% unacceptable i can figure something else out. I also made the area adjacent to the fireplace non-fire proof and added a empty storage crate to replace the table. Please let me know if you have any other notes, thank you!

For some reason, the distro loop won't save started. I start it and save the grid, merge it and everything and it stays off. How do i set it to begin on?

image
image

**Comment by dvir001** [comment]
As part of our attempt to modernize the shipyard guides, will it be possible for you to also add a guide entry for the ship?

**Comment by Pixeltheaertist** [comment]
> As part of our attempt to modernize the shipyard guides, will it be possible for you to also add a guide entry for the ship?

sure thing! i'll do that in a momento

**Comment by Pixeltheaertist** [comment]
> As part of our attempt to modernize the shipyard guides, will it be possible for you to also add a guide entry for the ship?

Is this good?

image
image

**Comment by Pixeltheaertist** [comment]
i see one of the changed files is the pioneer even though i haven't opened it before, i think it's just from me pulling recent updates before my latest commit?

**Comment by Pixeltheaertist** [comment]
ack wait there's a type in distribution

**Comment by ArkiveDev** [comment]
campfirePipeFixProposal
Have you tried running the waste line straight down?

**Comment by Pixeltheaertist** [comment]
> campfirePipeFixProposal Have you tried running the waste line straight down?

i don't think pipes are supposed to stack like that last i tested, i could be wrong though

**Review by arimah — CHANGES_REQUESTED** [review]
Hi! I've just had a look at this ship, and have a few remarks.

image
I will confess, I'm not hugely fond of this area. The wooden chair has practically endless space around it, while the bar stools, sofa and fireplace are cramped. Moreover, the dartboard in space seems pointless. You can't easily get to it, you can't bring it on board because there's no room inside...

I think if you were to shrink the table, move the bar chairs around and expand the space on the right, you could turn it into a much cosier space:
image

I'm also not convinced by the broken grille. What was that grille at some point – why is it there?
Is this ship meant to be new or used? If the latter, I think the ship could do with more dirt, maybe broken wood flooring, something more to make it look properly pre-owned.

Also, I can tell by the flooring that you haven't run `variantize` on this grid. Please do that on all ships you submit.

---

image

* Why is there a grappling gun there? Will people be doing a lot of EVA while on this ship? It seems unjustified, and should probably be removed.
* The scrubber corner is completely dead. Maybe it'd be nice to put a locker there. Even a basic secure closet would be preferable to... nothing.
* Cockpit visibility could be improved considerably by having just one more window tile here. At present, visibility is practically non-existent.

---

image

* Use "gas mixer [On]" (GasMixerOn) instead of a regular gas mixer.
* The ports are set up incorrectly: you want 21% oxygen and 79% nitrogen. Just flip the numbers.
* I don't love the presence of catwalk over atmos devices, because unfortunately the catwalk ends up *on top of* the device: image
* Another broken grille I don't fully understand.

---

image

These decals are intended to be overlaid on 2x2 tile floors, and don't work well on shuttle floor.

image

The decal/floor work here is a little bit confusing. From bottom to top, you have a wooden trim followed by not-wood followed by wood pattern flooring leading to a wooden stair surrounded by large wood floor. I'm all for varied floor surfaces, but this seems a bit... much? I think if you made it just wood floor (normal or large) , it would look overall cleaner:

image

In fact, this entrance area feels very cramped and small. If it were my ship, I might try to find ways to open it up, as that makes the space feel cosier and more welcoming. As an example, I might move the docking airlocks out and shuffle one or two things around:

image

---

Some notes about piping and wiring:

image

1. The branches here are unnecessary; just leave the wire in the middle.
2. This little branch is unnecessary.
3. Please avoid putting pipes under walls as far as you can... this corner under the wall is cursed as hell, and the piping on this ship could probably stand to be redone altogether.
4. This bit of LV is unnecessary. Also, why does the pipe bend around as if to do everything it can do go under a wall?
5. More unnecessary pipes under walls. This should be redone.
6. The APC is unreachable without opening the crate. I think it would do better on the wall south of the red airlock.
7. Don't put a cable under the wall when there's a perfectly good door next to it :(
8. This cable under the wall is unnecessary.
9. This cable under the wall is unnecessary. As is the second cable on the same tile. Use `nodevis` to detect things like this!

---

I think this ship has potential. I absolutely don't hate it; in fact, I'm enamoured by the thought of a small, cosy ship that's just for chilling in. Something about it really speaks to me (and not just because the Hitchhiker's Guide to the Galaxy is one of my favourite books of all time). To make this ship really stand out, the cosy parts of it could totally stand to be made _even cosier_. It's okay if the engineering-y bits are less pretty, but you really want the nice bit to be _nice_, right?

**Comment by Pixeltheaertist** [comment]
Allo! I will review all this as soon as I can, it’s a bit hectic right now but I’ll do it 

As for the grappling gun, it’s there because it’s kind of the iconic calling card the LGH has made for itself so I thought I’d include it, but I’ll remove it if it needs to be 🫡 
Thanks for the feedback!

**Comment by arimah** [comment]
As there has been no activity on this for nearly two months, I'm going to close the PR. This does not mean the ship will never make it into the game; it's just to clean up our own backlog of pending ship PRs. If you update the ship and want us to have a look at it, please comment here and we'll reopen the PR.

**Comment by Pixeltheaertist** [comment]
Now that i've finished the stuff i wanted to for Trieste I might come back to this idea with an entirely new design, if that's alright. Same idea, but new ship all together since this one is.. meh

**Pull request closed without merging**
