### PR TITLE
Felinid code cleanup

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Match Felinid code to DeltaV

## Why / Balance
It was a mess on our side.

## How to test
Spawn as Felinid, hairball, eat mice

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
As far as im aware this is all backend.

### CODE REVIEW

**Comment by whatston3** [comment]
Do think the markings should be kept capitalized for consistency, I'm doing a pass through the other markings.  Gave it a scan, everything seems fine, though it's a bit odd to me that the hairball action icon is Urist McFelinid if I'm reading it right.

**Comment by dvir001** [comment]
> Do think the markings should be kept capitalized for consistency, I'm doing a pass through the other markings. Gave it a scan, everything seems fine, though it's a bit odd to me that the hairball action icon is Urist McFelinid if I'm reading it right.
> 
> Edit: https://github.com/dvir001/frontier-station-14/compare/2024-11-10-Felinid...whatston3:frontier-station-14:2024-11-10-Felinid-suggestions?expand=1 marking consistency up here

This is fine

**Review by whatston3 — APPROVED** [review]
Pushed the change for marker consistency, added a new dragon hatch sound (repeated clacking timed to the egg animation and a pitched up, sped up roar before it exits), seems fine on my end.

Mouse hunger is equivalent to ~16.7 nutriment, not too crazy, and the hairball recharge on eating a mouse/rat seems like an alright change.  Double checked the guidebook entry, no change on their side, might want to remove the reference to OwOnavirus - either way, seems fine.

**Comment by dvir001** [comment]
Nice

**Comment by dvir001** [comment]
Going to merge this since this is all match up to DeltaV.

**Pull request merged**
