### PR TITLE
Removed hand teleporter from condor shuttle

### PR DESCRIPTION
**Pull request by TheEmber**
## About the PR

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Removed hand teleporter from condor shuttle

### CODE REVIEW

**Comment by dvir001** [comment]
Why?
Any issues related to it?

**Comment by TheEmber** [comment]
> Why? Any issues related to it?

Economics related issue. People can buy things on station and take it to cargo depot to earn money. And it is fair way. But they also can just use portals. So we can remove portals and still have way to earn money or balance economics so we will have portals but not money source.

**Comment by Cheackraze** [comment]
They could still be in as high level rewards but people are buying the ship just to get this item so yea, its gotta go

**Comment by dvir001** [comment]
> > Why? Any issues related to it?
> 
> Economics related issue. People can buy things on station and take it to cargo depot to earn money. And it is fair way. But they also can just use portals. So we can remove portals and still have way to earn money or balance economics so we will have portals but not money source.

Agree, we can re add it to sci tech tree later, or expo rewards.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
