### PR TITLE
Add Lobby Song: Shibamata

### PR DESCRIPTION
**Pull request by McBosserson**
## About the PR

Adds Shibamata to the list of songs played in the lobby.
The info in attributions may be flawed but is as accurate as I can get.

## Media

- [X] This PR does not require an ingame showcase

**Changelog**

:cl:
- add: Shibamata as lobby song

### CODE REVIEW

**Comment by Leander-0** [comment]
Nyanotrasen lobby song.

drunk

**Comment by Cheackraze** [comment]
you commited robust toolbox, gotta drop that change

**Comment by McBosserson** [comment]
> you commited robust toolbox, gotta drop that change

I have no idea how.

**Comment by dvir001** [comment]
> > you commited robust toolbox, gotta drop that change
> 
> I have no idea how, or even what I did.

Redo this PR and make sure you only commit what you need please.
Closing this so you can make a new PR.

**Pull request closed without merging**
