### PR TITLE
Cave (Event)

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Ooga, caveman cave got bluespace across time.

## Why / Balance
Needed more bluespace events that are not just gamer loot but fun

## How to test
gamerule add cave

## Media

image

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl:
- add: New bluespace event added, the cave.

### CODE REVIEW

**Comment by whatston3** [comment]
Put out a minor set of changes to Clugg (mostly description, will defer to you if you have strong thoughts), cleaned up the wooden cage base sprite, removed a bunch of unnecessary delays in the meta.json.  Event seems okay if you can clear out the dinos, should make about ~120k in diamonds if they can be refined.

Changes up on [whatston3:2024-09-21-CaveEvent-suggestions](https://github.com/dvir001/frontier-station-14/compare/2024-09-21-CaveEvent..whatston3:2024-09-21-CaveEvent-suggestions)

**Comment by dvir001** [comment]
> Put out a minor set of changes to Clugg (mostly description, will defer to you if you have strong thoughts), cleaned up the wooden cage base sprite, also removed the paper label, it didn't really fit, removed a bunch of unnecessary delays in the meta.json. Event seems okay if you can clear out the dinos, should make about ~80k in diamonds if they can be refined.
> 
> Changes up on [whatston3:2024-09-21-CaveEvent-suggestions](https://github.com/dvir001/frontier-station-14/compare/2024-09-21-CaveEvent..whatston3:2024-09-21-CaveEvent-suggestions)

Go for it

**Review by whatston3 — APPROVED** [review]
Good enough, cave time.

**Comment by whatston3** [comment]
https://github.com/whatston3/frontier-station-14/pull/3

Failing test passes here.  Going to merge this, seems fine.

**Pull request merged**
