### PR TITLE
Science gameplay changes (buffs)

### PR DESCRIPTION
**Pull request by GreaseMonk**
## WORK IN PROGRESS
todo: 
- [ ] : Fix research transferring
- [ ] : Fix point disks not inserting into tech disk terminal because it now has slots
- [ ] : Fix ancient code spasming over changes i made

## About the PR

My science changes are nearly done, here's whats changing in the pr i'm making and feel free to comment:
- Increase sci point gain by 20% (can be changed using a cvar)
- Increase technology cost by 0.014% for every unlocked technology (approx.50 unlocks makes future unlocks cost 50% more) (can be changed using cvar as well, and bool cvar that disables it completely)
- R&D Servers are no longer functional and are replaced with disk consoles to counter cheezing 4 R&D servers to combat the changes. The ship is now the R&D server (per grid basis)
- Technology disks and research point disks are now inserted into the disk console instead.
- Research can be ejected  and moved by inserting the captains id into the disk console and pressing eject button. This ejects a disk with all research and the grid's research points will be set to 0 to prevent that if you have over a million points, you can start selling full research t1 disks to people. Thats not the gameplay i'm trying to achieve.

## Why / Balance

This incentivizes playing science more as smaller crews and makes it a (configurable) harder for larger crews to finish all tech tiers.
### **The goal is to make science stuff more available (and earlier) to players instead of relying on one crew to solo the entire science for the rest of the server.** 

why:
- Getting to multiple t3 using xenoarcheology or anom is very difficult for one or two persons. you need to be mining, salvaging, upgrading machines, printing, and serve customers.  This is too much.
- Selling science is usually done by 4+ crew and depending on artifact kindness and luck, they start selling before halfways through the shift.
- Tech is sold too late to be used the rest of the shift.

opinions:
- I want sci crew to be able to easily reach their first tech and start producing and selling to people.
- They can continue to research a second t3 in their downtime, but a third and fourth should not be as feasible
- Selling should be doable after one hour of science gameplay to provide for players to benefit it the rest of the shift.
- Reaching t3 on all sci should become difficult, so that different science crews can specialize in specific disciplines
big crews should not have any problem reaching t3 on all sci even with the point gain deduction.
one person crews should be getting into t3 easily and have time to use it now too

how:
- Buff point gain by 20% on everything.
- The more research you obtain, the more points it will cost. (i will test this so it matches the timeframe which is appropriate)
nice to have: rebalance disciplines? i feel like people will only go sci or industry
 
some effects might be that a crew of 4 could split up into 4 ships - and the rebalance should be borderline the same effect.

## How to test

- Buy a sci ship
- Gain research points by anoms and xenoarcheology (this is buffed 20%)
- Spend it and watch as research becomes increasingly more expensive.
- at 50 unlocked techs, tech cost is now 200% the base cost.
- Try ejecting research and transferring it to another ship!

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

I had to make some additions to be able to get the owning station in shared code and keep everything consistent.
Also needed to move a station config component to make it work.
Please tell me if its actual dogshit code and i need to get off my ass to do it smarter. I just didnt know any better how to fix this

**Changelog**

:cl:
- tweak: Science buffs including 20% more point gain, easier first tech unlocks, encouraging early science

### CODE REVIEW

**Comment by ThatOneGoblin25** [comment]
This is good stuff. My only concern is that "The ship is now the R&D server (per grid basis)" won't be communicated and will potentially confuse players, especially ones new to Frontier specifically.

**Comment by GreaseMonk** [comment]
> This is good stuff. My only concern is that "The ship is now the R&D server (per grid basis)" won't be communicated and will potentially confuse players, especially ones new to Frontier specifically.

if thats the only concern... i am very happy with this feedback! ❤️

**Comment by blackknight954** [comment]
**"choose two out of three branches of science". If that's the goal that's the goal. But are those branches really equally attractive?**
 Not really, Industry and Sci have tons more usable research than speed boots and antique laser pistol

And I don't personally agree with having higher point costs the longer you research, that won't fix the problem of disk printing or 40% of the server being science ships already. Dusty has a point that if anything we need less ships with more bodies on them, not 70 different ships for 70 different players.

**Comment by Myzumi** [comment]
I Personally hate most of the changes;

- More Points from researches? Well sounds like more money to me!;
Basically just shoving more money in the economy, resulting in even more Science ships going out of everyone's way and just print even more disks in masses.
- No more R&D that could be stolen or be destroyed? I guess i can just let everything explode!;
This kind of removes a risk that small Science ships has that there could be a chance an Artifact exploding your R&D Server, which you should 100% keep protected in any cases. On some Bigger ships there's not really this risk, but also gives you a bit more reason to take on a bigger crew than venturing alone.
(This was a discussion in an Group chat with other SS14 Players)
- Why does this blender take more research than a really good weapon?
This kind of Discourages people from researching Service or Weaponry if they are not focusing onto them actively, why should Simple Research options now cost more when you just had a breakthrough research with Bluespace technology

Yes, Much hate, but there's also some nice things in this PR at least;
- A feature to be able to eject most research and points you had makes it simpler to let's say a ship change or you selling the ship to just hang out on the Anomalous Geode/POI Sci labs, needing you to drag an heavy ass server with you which basically only stores ones and zeros.
- Tech Disks and Research Points only insertable in Disk Terminals, i mean where does the server even have an input for disks on it? (sprite wise) you just magically touch the disk/Points with the server and it disappears?, This encourages when going for Vgroids/Salvages to start a bit of science beforehand

**Comment by ThatOneGoblin25** [comment]
> I don't personally agree with having higher point costs the longer you research, that won't fix the problem of disk printing or 40% of the server being science ships already.

The longer you research the more stuff you can get to increase the amount of points you gain, if you're serious to do science. Stuff like grinders for artifexium and advanced anomaly vessels once set up will pay their dividends. 

Disk printing is its own cans of worms but I like being able to turn research points into cash. 

As for smaller science vessels becoming more numerous that's also fine. Highpop rounds have ten or so pioneers (some are dead usually) so whether the players who want solo or small crews to do salvage or science is arbitrary. Doing science carries its own dangers, and also being able to yoink a ship's research points as a pirate with the captain hostage with this pr's changes could make for some more profitable piracy.

**Comment by GreaseMonk** [comment]
Heard.

I'm going to discuss this with other maintainers , sometimes the best thing to do is to do nothing, too. 

>More Points from researches? Well sounds like more money to me!;
But there is a PR open that is merged along with this one that makes them worth near nothing.

**Comment by GreaseMonk** [comment]
Linking this PR that deletes disk money farming:
https://github.com/new-frontiers-14/frontier-station-14/pull/2418

Why / Balance

This has made sci work into a single goal job, farm as many points as possible, print disks make millions.
No point in selling techs, no point in selling items, why even? when the profits wont match the millions made by just point farming for 6 hours.

**Comment by KieueCaprie** [comment]
On paper, I like how all this sounds. Science in general has always felt a bit monotonous because you either: research everything and try to sell the tech, only for your calls to go unanswered because you researched bluespace beakers at hour five on Maunder WAY past the time anyone would want anything OR you research nothing and hoard points to then spam disk printing at the cargo depot at hour five (hour six if you're feeling spicy).

So, changes to not entirely discourage sci-maxxing but to encourage a more focused research path similar to vanilla (minus the path-locking of course) sounds pretty neat but I do share the other's concerns: Are the branches attractive enough for me to bother? I already don't max out arsenal and just cap Experimental, Industrial, and Civilian, and even then, why should I bother maxing Civ or Arsenal outside of Experimental and Industrial, where the vast majority of useful items are, Basic and Advanced Food Service notwithstanding.

That said, I do feel like this may be a step to some direction, I can't quite tell if it'd be good or not but any change that moves away from hitting the print button like a mindless zombie is at least doing something.

**Comment by wolfchild1990** [comment]
This is a significant nerf to science availability in hypatia where you tend to get fewer crews in total. Also it will just mean arsenal tech never gets researched since no one pays for it anyway AND the coolest stuff from it the scientist cannot actually print

**Comment by pheenty** [comment]
This is terrible. Especially if the intention is to make science available to smaller crews. I always do science solo (of with just one miner buddy) and usually I research the full server at like the second hour of the shift. Cool, now I can research T1s faster, but... I would probably be unable to get the full server that fast since it takes more points total. And there's almost no way to sell tech before I get the full server since I'm the only crew member and I'm busy with the researching. On the contrary, that just straight up buffs bigger crews that don't really want to sell any techs and just want a couple for themselves,.like NFSD on the Empress buying RnD stuff just to research one arti to get incendiary and uranium rounds and nothing more

**Comment by ThatOneGoblin25** [comment]
> Cool, now I can research T1s faster, but... I would probably be unable to get the full server that fast since it takes more points total.

Now it requires a bit more planning and investment that will be harder for a solo to max out research so they can print anything, while still making tech disk printing viable for small crews. I think that's fine.

> On the contrary, that just straight up buffs bigger crews that don't really want to sell any techs and just want a couple for themselves

Larger crews who just want a little bit of science to have an easier gameplay experience can now just get what they want quicker. If they want a whole research tree done then they need to dedicate more resources and crew to the endeavour, which means you're probably going to end up selling tech to make back the investment.

> NFSD on the Empress buying RnD stuff just to research one arti to get incendiary and uranium rounds and nothing more

This is a lame thing for nfsd to do, but I think it comes more from how the Arsenal tree works and how nfsd are the only ones with the lathes to benefit off doing this. The PR's changes make it easier, but theres the initial setup for xeno arti, it's still an effort nfsd have to make.

**Comment by pheenty** [comment]
> > Cool, now I can research T1s faster, but... I would probably be unable to get the full server that fast since it takes more points total.
>
> Now it requires a bit more planning and investment that will be harder for a solo to max out research so they can print anything, while still making tech disk printing viable for small crews. I think that's fine.

Fuck the disk printing, I'm talking about selling printable things to other players. And if the problem is "Tech is sold too late to be used the rest of the shift." (with smaller crews) that just makes it worse. As I said, small crews can't sell tech before maxing the server since they are busy with the researching. 

> > On the contrary, that just straight up buffs bigger crews that don't really want to sell any techs and just want a couple for themselves
> 
> Larger crews who just want a little bit of science to have an easier gameplay experience can now just get what they want quicker. If they want a whole research tree done then they need to dedicate more resources and crew to the endeavour, which means you're probably going to end up selling tech to make back the investment.

Or they can buy what they need from a science ship, which is what science ships are made for

**Comment by GreaseMonk** [comment]
Thank you everyone so far for all the feedback. This PR stands as a rough workout of a idea, still debating if this is going to be any good, and when in doubt i might not merge it unless there is good reason to go on

**Comment by GreaseMonk** [comment]
Going to close this for now as a clear case. Thanks for everyone who attended this gathering :-)

**Pull request closed without merging**
