### PR TITLE
ATM: Feedback on invalid items

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds an error state to ATMs when non-speso currency (e.g. doubloons, FUCs, telecrystals) are inserted.  At time of writing, the ATM will output "ERR: INVALID" when an invalid item is inserted into the cash slot.

## Why / Balance

If somebody inserts some invalid currency, players might not think that something was inserted.

## How to test

1. Build and run local server.
2. Spawn in, open ATM.
3. ATM should display 0 in the deposit window.
4. Insert spesos.
5. ATM should display the value of the spesos in the deposit window.
6. Spawn and insert doubloons.
7. ATM should display "ERR: INVALID" in the deposit window.

## Media

image

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: ATMs now display an error if non-speso items are inserted.

### CODE REVIEW

**Comment by whatston3** [comment]
Need AGPL headers.
Need photos in PR description.

**Comment by dvir001** [comment]
Do we need to always add the
```
/*
 * New Frontiers - This file is licensed under AGPLv3
 * Copyright (c) 2024 New Frontiers Contributors
 * See AGPLv3.txt for details.
 */
 ```
 
 On frontier only files?
 💀

**Comment by Cheackraze** [comment]
Yes we should be marking all new files that way

**Review by dvir001 — APPROVED** [review]

**Comment by dvir001** [comment]
Works

If It was up to me ill just lazy the whitelist

**Pull request merged**
