### PR TITLE
Juggistry Nerf.

### PR DESCRIPTION
**Pull request by Actualcatmoment**
Part one of a set of tweaks to overhaul the medical economy.

## About the PR

Tweaked recipes for a handful of basic chemicals to introduce impurities to their synthesis in order to disincentivize the use of bath-tub medicine without completely removing them as an emergency option.
All recipes are the same but some have additional products that make them annoying to use excessively.

Dylo, Kelo, and Inap all now produce a small amount of mystery sludge. 
In the code there are three different types of sludge that can be produced with different effects tailored to each medicine.

Acidic Mystery Sludge: Produced when making Kelotane, causes caustic damage and makes you thirsty but metabolizes fast.
Viscous Mystery Sludge: Produced when making Dylovene, gets you really really drunk without any toxic effect.
Putrid Mystery Sludge: Produced when making Inaprovaline, essentially ipecac, but works at any amount in your system.

There is no other way to obtain these chemicals, and they cannot be broken down into useful materials. They also all taste like malpractice and have popup messages like "you feel sick", or "you feel your insides burning" to make it obvious that you probably shouldn't use them.

## Why / Balance

Ok there's quite a lot to this that I will summarize poorly here but see this discussion for the full discourse https://ptb.discord.com/channels/1123826877245694004/1255013042119507979

The ease of "bucket chemistry" undermines the role of medics and the use of proper lab equipment. By introducing impurities and side products, we can make this method less reliable and more hazardous, encouraging players to use lab equipment without entirely removing the option for emergency situations.

In real-world chemistry, there are always intermediate steps, purification processes, and byproducts that must be managed.
While one aim is for greater realism, the goal is not to create an overly complex system that frustrates players. 

The ideal implementation would be a more nuanced system incorporating a small handful of possible impurities and semi-randomized yields, as well as specific purification techniques. As of yet that kind of system is beyond my ability but repurposing the existing system with minor tweaks is entirely possible, and this project is the result. 

With this tweak basic chemicals are relatively simple to purify, the impurities produced from the synthesis only have inconvenient effects, they are not excessively punishing but should incentivize interaction with doctors/chemists for access to safer medication. 

~~One idea swimming is to implement new mystery sludge reagent(s?) to replace the reused chemicals with something that has zero value instead of ipecac and crypto which are both valuable in their own right.~~

This no longer reuses any reagents present in the game or changes the effect of kelotane. The mystery sludge cannot be synthesized any other way and does not have fringe use cases (except maybe as turbovodka in the case of viscous mystery sludge).

## How to test

Spawn a chem master and a chem vendor, get you some jugs and go for your life.
Some of the values may need tweaking to be more punishing to provoke the intended effect.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
lel

## Breaking changes

Changes the recipe products for dylovene, kelotane, and inaprovaline. the changes have been noted in the original file though I suspect it may be better to comment out those sections and move them to _NF/Reagents/medicine.yml

**Changelog**

:cl: 
tweak: Dangerous side products are produced in the synthesis of some medicines. Use of "bootleg" or "bucket" medicine is not recommended.

### CODE REVIEW

**Comment by dvir001** [comment]
I'm not a fan I'm making any changes to base chems downstream

This will confuse anyone coming from any other server

**Comment by Actualcatmoment** [comment]
> I'm not a fan on making any changes to base chems downstream
> 
> This will confuse anyone coming from any other server
> 
> Do this PR upstream as we cannot have base chems work differently from upstream withot it getting reported as bugs daily

It could be done upstream yes, but the change is part of a set intended to balance an issue that is specific to frontier, not upstream SS14.

The changes implemented do not affect existing chemicals or their functions, nor does it change their recipe, it simply adds very obvious side products to the reactions that I doubt will result in bug reports, especially if the guidebook entry is also updated to clarify things which I fully intend to do.

**Comment by dvir001** [comment]
The actual fix is to lower access to chems to be more medical poi workers / ships based since we're MRP.

Not to change nase game chems in anyway that make it less new players friendly.

Players should not be force to know different chems conditions per server.

**Comment by GreyMario** [comment]
But there's nothing to even really fix _there_ either, is there? You can say it's LRP to have people scavenge chemical jug crates off of wreck spawns and do jugchem with them when they're not chemists, but if you do I will counter that it's HRP to implement a _mechanical punishment_ for doing something that you might have to do _just to survive._

I don't think I really like the idea of punishing a player for being resourceful in an environment built around... being resourceful.

**Comment by FutufreForwards** [comment]
I have already discussed this in depth in the discord thread so I won’t repeat myself much. The short of it is that “busywork is not good roleplay nor gameplay “ + Dvir has a good point, as someone who plays on other servers I don’t want to memorise 2 different sets of chemical recipes.

If this PR gets merged, I suggest only one server receives the changes initially so we can compare the culture changes of medical between the old and the new

**Comment by BluCottonCandy** [comment]
First of all the argument of "busy work". 
If that's your reasoning for not wanting this, why make artifaxium work different from upstream? 
That just creates busy work. 
While on the topic of that, why did we change how artifaxium works different from upstream. 
We don't get constant complaints that it's a bug even though it's different from upstream, and if we do, then why is that more allowed but this isn't? 

As for the argument "punishing resourceful players" it's not. 

Jug chemist is still viable and possible albeit less easy and will require you to eventually go to a doctor. 

You can be a shady chemist selling meds dirt cheap that are less good. 

Also, as for the "don't want people reporting it as bugs" 
What about hardsuits? 
They don't protect you from fire like upstream does, is that not exactly the same? 

My point is, the "don't want to differ from upstream" argument is a weak one

**Comment by GreyMario** [comment]
>says things aren't what people are saying they are
>refuses to elaborate

**Comment by ThatOneGoblin25** [comment]
> While on the topic of that, why did we change how artifaxium works different from upstream.

It was changed because someone could spray 50 artifacts at once for infinite points with only a handful of artifact fragments making doing Xenoarch trivial. It was always felt that handling artifacts this way made science gameplay very short and powergamed by players who wanted tier 3 parts for themselves and nothing else. There have been 3 other PRs attempting to balance this issue.

In any case, how the actual chem works wasn't changed, just how to obtain it.

**Comment by FutufreForwards** [comment]
How the hell did artifaxium come into this?? I have no thoughts on it because I do not do science. I’m sorry but that’s just a straw man argument  and “whataboutism” . We are discussing chemistry so keep it to that. I now have doubts that you are doing this in good faith and are now pushing it just because it was your idea ignoring the concerns of others

**Comment by EaglePhntm** [comment]
it sounds like a good idea except kelotane stuff making instant mega thirst, could be maybe instead scale to amount consumed? Also how is that supposed to be purified to be effective if it is made into kelotane, likely people would meta-ize laser even more and who get shot by lasers will become some mega slow slug by thirst while trying to heal, and lack of mobility is certain death in such time.

**Comment by Actualcatmoment** [comment]
> as someone who plays on other servers I don’t want to memorize 2 different sets of chemical recipes.

The good news is that you don't need to memorize two different sets of recipes as there are no changes to the ingredients nor the proportions going in or coming out. If you attempt to make dylo, you will still make dylo, it will just have extra mystery sludge that makes it inadvisable (though not impossible) to use in the impure form. If you have access to a chemmaster the purified medicine behaves exactly as it always has.

> How the hell did artifaxium come into this
as an example of a mechanical change implemented on this server that makes chemistry different to upstream, to deal with an economic issue that is specific to frontier.

> We are discussing chemistry so keep it to that.
The artifaxium change was a chemistry change, this too is a chemistry change though it more greatly resembles the original behavior than the artifaxium tweak does.

> sounds like a good idea except kelotane
I'll clarify that the thirst change is only enough to increment your thirst bar by one stage per 20u dose of kelotane. Water is not particularly hard to access and the majority of ships come with a water supply, for the ships without one, water tanks and coolers are incredibly common on wrecks. 

The only time it becomes truly a pain in the ass is if you slam an overdose of kelotane into yourself and even then only for the duration of the chemical's metabolism. All other medications deal some form of damage on overdose, mechanically speaking kelotane is incredibly safe this just punishes you if you decide to drink a beaker of it for some reason.

**Comment by dvir001** [comment]
If anything after we added the arti mob spawn we might as well revert it

**Comment by Actualcatmoment** [comment]
> If anything after we added the arti mob spawn we might as well revert the Chem change

Fair enough but that still doesn't address the argument, it was needed at the time.

**Comment by FutufreForwards** [comment]
> > as someone who plays on other servers I don’t want to memorize 2 different sets of chemical recipes.
> > Players should not be force to know different chems conditions per server.
> 
> The good news is that you don't need to memorize two different sets of recipes as there are no changes to the ingredients nor the proportions going in or coming out. If you attempt to make dylo, you will still make dylo, it will just have extra mystery sludge that makes it inadvisable (though not impossible) to use in the impure form. If you have access to a chemmaster the purified medicine behaves exactly as it always has.
> 
> > How the hell did artifaxium come into this
> 
> as an example of a mechanical change implemented on this server that makes chemistry different to upstream, to deal with an economic issue that is specific to frontier.
> 
> > We are discussing chemistry so keep it to that.
> 
> The artifaxium change was a chemistry change, this too is a chemistry change though it more greatly resembles the original behavior than the artifaxium tweak does.
> 
> > sounds like a good idea except kelotane
> 
> I'll clarify that the thirst change is only enough to increment your thirst bar by one stage per 20u dose of kelotane. Water is not particularly hard to access and the majority of ships come with a water supply, for the ships without one, water tanks and coolers are incredibly common on wrecks.
> 
> The only time it becomes truly a pain in the ass is if you slam an overdose of kelotane into yourself and even then only for the duration of the chemical's metabolism. All other medications deal some form of damage on overdose, mechanically speaking kelotane is incredibly safe this just punishes you if you decide to drink a beaker of it for some reason.

Fair points, tough making less than usual of what I want  using the same recipes irks me as a chemist player.  I still do not buy the artifexium points tough. It might be a chemical by right but  No medical chemist has ever made artifexium and it’s something scientists choose to go for. As I am not a scientist I do not care about it. This is why I believed it was brought up not in good faith when the changes to it is irrevelant to medical and annoyed me a little.

I apologise for questioning your character in that regard. I still do not agree with the solution and I won’t repeat myself as to why. However, my original point of putting this changes to one server (Hypatia or Marauder) still stands so we can compare how medical culture is done in both servers. Who knows maybe I can be proven wrong on this if I experience it for myself and find it not as bad

**Comment by Actualcatmoment** [comment]
> making less than usual of what I want using the same recipes.

The yields are the same, there's just bonus trash, It might create an issue with overflowing a bit if people aren't careful but that's an avoidable thing

>I still do not buy the artifexium points tough. 

So, the argument itself was that we should not implement mechanical changes to chemistry to fix in game issues specific to frontier, and yet the artifexium tweak is a prime example of such a change. It's not that artifexium strictly has anything to do with medical, but that the problem I'm trying to address is of the same type, and this solution is similar. it is an analogical argument, making comparison between that previous PR and this new one. 

> I still do not agree with the solution. 

As is your right i won't hold it against ya

> putting this changes to one server (Hypatia or Marauder) 

I'm not opposed to the idea, though from my experience hypatia is typically dead, and it may not be so simple for the maintainers to keep track of something like that.

you're welcome to playtest the changes if you want too, just need to wait till i figure out how to squash the bugs.

**Comment by avosirenfal** [comment]
didn't the cryo PR that just got merged change chems from upstream?

**Comment by Actualcatmoment** [comment]
> didn't the cryo PR that just got merged change chems from upstream?

Very good point, and definitely yes.
The argument has been weak from the very start.

I'm happy to address concerns and discuss possible fixes but at this point the only points against this, (along with the supporting WIP tweaks) are "change bad", "I don't wanna have to think", "we're removing crates so why bother?", or "Med POI is just a week away"

The second to last the only good faith argument but I don't think that solution is going to really work as intended, nor is it the best way to go about it. for one it's going to fuck the Med POI over, watch it be raided every shift. or if there's some whitelisting involved in the access and you make the structure invulnerable the only medical options anyone has is to pray that someone logs on that shift. less choice/less gameplay options is not the answer. Mechanically encouraging RP interactions is the way.

**Comment by MagnusCrowe** [comment]
> I have already discussed this in depth in the discord thread so I won’t repeat myself much. The short of it is that “busywork is not good roleplay nor gameplay “ + Dvir has a good point, as someone who plays on other servers I don’t want to memorise 2 different sets of chemical recipes.
> 
> If this PR gets merged, I suggest only one server receives the changes initially so we can compare the culture changes of medical between the old and the new

I'm seeing the same ingredients in the same proportions creating the same amount of medicine.  That's not anything you have to memorize.

The only think that seems to be changing is that a harmful byproduct is also being produced that requires an extra step to filter out.  It's an additional step in the process to produce pure medicines.  I don't know why this would be considered busywork.  There is sound reasoning behind it.  In the real world, chemical reactions often create byproducts that need some sort of chemical filtration.  

Let's be real for a moment, it does not sound right to me that you could throw three chemicals into a bucket and produce a miracle wonder drug that is pure enough to draw with a syringe and inject into your bloodstream.  The current chemistry system is laughably simplistic.  This PR seems like a light change that can radically improve that.

I'd like to see chemistry/pharmacology become a job that people will appreciate and earn its pay, but when everyone can mix their own pharmaceuticals as easy as 1+1 = 2 in a bucket, it just isn't going to happen.  If this PR isn't suitable, then I'd like to hear some other propositions.

**Comment by Actualcatmoment** [comment]
Something has gone horrifically wrong with YAML Linter, it's failing on files that this PR does not even edit.

That or i'm just not smart enough to figure out how to fix it properly. dunno.

**Comment by Iajret** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1558 PR broke your lints, dont worry too much, i guess

**Comment by GiggIess** [comment]
Magnus put it perfectly.

If we're trying to still allow "back alley shady chemistry", this is a great step. Why would I go to a doctor, or hospital, when the guy jug mixing in his canister produces the exact same medicine the doctors use?

**Comment by Actualcatmoment** [comment]
> #1558 PR broke your lints, dont worry too much, i guess

I think I've narrowed the issue down, it's caused by not having the flavor file added by that PR, I originally added flavor-mysterysludge to a flavor file in _NF but it caused a duplicate prototype error. I'm unsure how, or if, the pumpkin spice PR fixes that.

Simply adding the missing files to my local copy does not fix the error.
Moving the flavor definition added to the original file does though.

**Comment by Eb-** [comment]
I am personally looking forwards to this change! Right now anyone can do chemistry without much of a second thought, meaning that having a chemist or doctor is in minimal demand and requires little setup. This change would encourage more diversity of play and more player to player interaction.

**Comment by Houtblokje** [comment]
I think that this would overall be a pretty good change, since its easy to understand (The recipes would be the same, you would just need to filter out the bad stuff) and I think it would definitely help combat bucket chemistry.

**Comment by ErhardSteinhauer** [comment]
Going to close this PR for a couple of reasons: it was stale for quite some time now, the discussion seems has reached it's conclusion and I believe a different solution to this problem is in the works (by @whatston3).

**Pull request closed without merging**
