### PR TITLE
NC Shepherd ship

### PR DESCRIPTION
**Pull request by saintmuntzer**
_Note: I'm away from my computer until 8/24, so I can make any proposed changes once I'm back._

## About the PR
Added the NC Shepherd, a medium-sized mining/salvage/cargo mothership intended for collaboration with Pioneer shuttles.

The Shepherd is meant to be an accessible way to expand from basic solo mining and salvage operations to collaborating with other players and ships, targeted toward working alongside the most ubiquitous and affordable mining vessel on Frontier: the Pioneer.

Pioneer captains benefit from this arrangement by gaining access to an ore processor, salvage techfab, and expanded storage. This could take the form of momentary, spontaneous agreements or collaborations lasting an entire shift.

The design suggests a rough conversion from a light cargo freighter into an improvised mining mothership; the cramped docking arm would have originally been intended for unloading shipping containers of the same size and profile as the Pioneer (described as being a converted shipping container itself).

This is my first time submitting a ship design so I'm sure it will require fixes and refinement if it's accepted at all. Thanks for taking a look!

## Why / Balance
The Shepherd encourages both player-to-player and ship-to-ship interactions and collaboration via mechanical and social incentives. Pioneer captains gain access to ore processing and fabrication machinery. Shepherd captains can negotiate contracts with miners and gain safety in numbers, all while spending less than 50000 credits, making it an easy progression from operating a Pioneer shuttle solo.

### Design Aspects

- Overall
  - Sodium lights by default for warm, industrial feel.
  - Crew quarters for two salvage contractors and one captain.
  - Spacious yet utilitarian cargo bay.
  - Docking arm designed for use by Pioneer shuttles, but adjoining catwalks can be removed to allow for other vessels.
- Cockpit
  - Sleeping area reminiscent of solo cargo pilot cabin.
  - Shutter control toggle.
  - "Panic button" closes all shutters and blast doors.
- Engineering / Maintenance Hall
  - SUPERPACMAN generator properly shielded for eventual radiation hazard.
- Miscellany
  - 332 tiles.
  - Uses roughly 25.3 kW of power.
  - Includes guidebook with shuttle map.

## How to test
Check out the branch and load the ship.

## Media

Shepherd-2024-8-13_21 30 57
Shepherd with subfloor and spawns.

Shepherd-2024-8-13_21 31 39
Shepherd initialized.

Intro to proposed guidebook entry.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None.

**Changelog**

:cl:
- add: Added the NC Shepherd, a medium-sized mining and salvage mothership.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
Looks decent! I feel like you could get away with far fewer APCs and Air Alarms, though - the current number feels excessive. APCs can easily power entire sections of larger ships, so thinning those down might be beneficial unless you have a very specific reason to have so many. Doing that will also simplify your wiring!

You can do the same thing with you air alarms: reduce the number and have them linked to firelocks/vents/scrubbers in entire sections instead of having almost one per room.

**Comment by saintmuntzer** [comment]
> Looks decent! I feel like you could get away with far fewer APCs and Air Alarms, though

Good advice, thanks! Was used to the station-based tendency toward one APC and alarm per room, but I can see how a space of this size could do with fewer. I'll do another pass of the power and atmospherics systems shortly.

**Comment by saintmuntzer** [comment]
Reduced the APC and air alarm quantity; re-organized wiring to account for fewer APCs; reduced thruster count.

Shepherd-2024-8-10_22 17 32

Shepherd-2024-8-10_22 17 17

**Comment by saintmuntzer** [comment]
I might revisit this in the future, but the rotation issues caused by flying with a docked ship make this pretty unwieldy to use in its ideal configuration (having one or two Pioneers docked). May need to reconsider the orientation of the docks entirely if I try another iteration.

**Pull request closed without merging**
