### PR TITLE
STC: Remote consoles for controlling Trade Outpost traffic

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Adds remote versions of the shuttle console to view a particular station.  Increases the radar range for the STC's monitoring consoles to 350 metres.

Adds a Frontier-centric version of the DroneConsole component that matches a matching console with a DroneConsoleTarget component that match by key.  This should allow for a sector-wide radar control room if such a thing were desirable.

The existing DroneConsole system isn't great - it requires changes to individual grids, and matches with the first console on that grid, rather than with a particular console.

Need to swap out sprites to better match (or have unique versions for each station to help visually disambiguate), should get navigation beacons showing on the map screen (which dock is dock 4A?)

Changes to the STC control will need matching adjustments to rules, Space Law, and the Guidebook, and an announcement to the player base (this proposes that the STC now monitors traffic around the Trade Outpost and that players must request docking if the STC is on-duty) - this also brings back the possibility for docking extensions and control at the Trade Outpost.

## Why / Balance

With cargo moved off of Frontier station, and with traffic being diminished, this should give the STC more to do, should help .  Also, the DroneComponent is neat and we don't use it at all - _but we could_.

## How to test

1. Spawn on Frontier Outpost, visit the bridge.
2. Check the radar consoles on the STC's desk.  They should be properly labelled, and only the local one should have a working intercom.
3. Warp to the Trade Depot.  You shouldn't teleport into a fax machine.
4. Orient the map to Trade Depot's North and walk to the west.  You'll end up at the STC's office.
5. Check the radar consoles on the STC's desk.  They should be properly labelled, and only the local one should have a working intercom.
6. Check the fax machine, it should be labelled as "Trade Outpost STC" and function as a fax machine.
7. Purchase a ship, the console should work properly.

## Media

Changes to the Frontier Outpost bridge.  Two radar consoles are on the desk, the comms console has been moved, and there are a fourth row of desks with an alerts console (pointless, but thought it made more sense than an empty desk space) and the wireless camera monitor.
frontier outpost STC revisions

The new Trade Outpost STC office.  A hole in the wall intended as a mobile base, close to the center of the POI for radar coverage.
trade_station_stc

Showing the new radar consoles in use.

https://github.com/user-attachments/assets/b8448ebb-92ea-421b-8c4f-ff27d39dc416

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: An extra radar has been added to the Frontier Outpost bridge to monitor Trade Outpost traffic.
- add: The STC now has an off-base office in the Trade Outpost near the gravity generator.
- fix: The SR's main office door is now accessible by the STC.

### CODE REVIEW

**Comment by whatston3** [comment]
Pushed a change to the maps - added a tiny broom closet STC office to the Trade Outpost for the STC and switched a few of the consoles in Frontier's bridge around (babby's first mapping work, please cut me a little slack).

Remote and local consoles seem to work fine.  Need to fix the intercoms on the consoles - remote shouldn't have one at all, may need to fiddle with reparenting. Might want to get the ship consoles also (selectively?) displaying docking labels.

frontier outpost STC revisions
trade_station_stc

https://github.com/user-attachments/assets/b8448ebb-92ea-421b-8c4f-ff27d39dc416

**Comment by whatston3** [comment]
Save any linter errors or mapping critique, I think this is good to go.  Haven't drafted any changes to space law for trade station docking, can line those up if this is deemed suitable.

**Comment by whatston3** [comment]
Map is once again fixed, this PR should be good to go.  Still needs a minor rewrite of the rules around docking requirement in space law.

**Comment by whatston3** [comment]
Think this is fine.  Computers now require STC access to work.

Didn't add an STC door remote (it would control all internal airlocks, which seems odd, and I don't think fiddling with the DoorRemoteSystem is a huge win in terms of gameplay).

**Review by dvir001 — APPROVED** [review]
Didnt test in game yet but seen it working in stream.

**Comment by whatston3** [comment]
STC gaming.

**Comment by MagnusCrowe** [comment]
Not happy about the SR door change.

**Comment by dvir001** [comment]
> Not happy about the SR door change.

The one to the SR room?

**Comment by whatston3** [comment]
> Not happy about the SR door change.

Wouldn't have done it if you'd have voiced your opinion in bug reports for it.

**Pull request merged**
