### PR TITLE
NM Searchlight - New paramedical ship

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
A new small (153 tiles) and affordable (29500 spesos) ship for paramedics that is meant to be used for search and rescue operations or as part of a medical fleet reacting to mass casualty catastrophes. In general, the ship is less focused on putting patients back on their feet and more on keeping wounded alive long enough to get them to a capital medical ship like Helix, for example. Or their corpses for cloning. Main features:
- Toggleable forward mounted "searchlight".
- An arm (platform) for ease of access to distressed ships when docking isn't an option.
- Stasis beds.
- Morgue.

## Why / Balance
Remembered a scene from "Event Horizon" movie when the rescue ship approached the derelict ship and before docking slowly flew around the wreck with beaming projectors shining at it. That gave me the urge to make a ship with forward-mounted spotlights that could be toggled on/off.

## Media
image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Wiki Info
_"A small vessel outfitted for the search and recovery of wounded NT personnel. Primarily for recovery. Search though? Well. You got that medical tracker implanted, right?",_ - The Shipyard.

**Ship Size:** Small
**Recommended Crew:** 1-2+
**Cost:** $29500
**Power Gen Type:** Plasma
**Expeditions:** No
**IFF Console:** No
**Available Roles:** Paramedic, Engineer

**Changelog**
:cl: erhardsteinhauer
- add: Added NM Searchlight - a small search and rescue vessel.

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
This ship use "StandardFrontierExpeditionVessel" stationProto, its should use "StandardFrontierVessel" instead.

**Comment by ErhardSteinhauer** [comment]
> This ship use "StandardFrontierExpeditionVessel" stationProto, its should use "StandardFrontierVessel" instead.

Oops. Fixed it.

**Comment by ErhardSteinhauer** [comment]
- Replaced `Paramedic Locker [Filled, Hardsuit]` with `Suit Storage Unit [Paramedic]`
- Replaced `Engineer's Locker [Filled, Hardsuit]` with `Suit Storage Unit [Station Engineer]` and `Engineer's Locker [Filled]`

**Comment by ErhardSteinhauer** [comment]
Changed the name of this ship because of this PR: https://github.com/new-frontiers-14/frontier-station-14/pull/712

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
