### PR TITLE
Adds an innate mineral scanner to dwarves

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

What it says on the tin.  Dwarves get a 5m innate mineral scanner (equivalent to the base mineral scanner, still inferior to the advanced version).

## Why / Balance

Dwarves are one of the more bland species in-game.  This gives them a nice little something that doesn't seem too gamey (though opinions may vary).

## How to test

1. Join as a dwarf.
2. Spawn a few asteroids with ore.
3. Equip an advanced mining scanner.
4. Your range should increase to 10 meters (check MiningScannerViewerComponent via VV)
5. Unequip the mining scanner.
6. Your range should revert to 5 meters (again, check MiningScannerViewerComponent via VV)
7. Re-equip, unequip, re-equip, unequip, you should always have the mining scanner viewer active.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Dwarves now have an innate mineral scanner that senses ore out to 5 meters.

### CODE REVIEW

**Comment by dvir001** [comment]
Please add this also to the race guidebook

**Review by dvir001 — APPROVED** [review]
Merge after added guidebook note update.

**Comment by whatston3** [comment]
> Merge after added guidebook note update.

Moved the Dwarf page (and Cryo too) to _NF.

in-game view for the dwarves (not much)
image

in-game view for the cryo med page (note the references to "cryogenic medications")
frontier_cryogenics

**Comment by whatston3** [comment]
> I know players prefer to have things added over removed, but is there a mechanical reason to not simply have dwarves run with the advanced scanner from the get go?

The goal here is that the advanced scanner should still have value, even for dwarves (better than their own innate sensing range).  I  can't see a huge value for a 10 vs. 5 meter radius (maybe apart from hunting in really large, ore sparse rocks), but if that niche exists, the advanced scanner should still have more value, and could be sought out if a player deemed it fit.

**Comment by dvir001** [comment]
Tbh right now dwarfs have no real bonus at all, so this is fine.

**Comment by ErhardSteinhauer** [comment]
Wdym "no real bonus"? They can smoke Stonecut Leaf without coughing or choking.

**Pull request merged**
