### PR TITLE
Salvage Mob Restrictions

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Restore Salvage Mob Restrictions

## Why / Balance
Missing code

## How to test
Run, have mobs around on grids, grid delete, mobs delete.

## Media
M/A

## Breaking changes
N/A

**Changelog**
N/A

### CODE REVIEW

**Comment by dvir001** [comment]
No longer need https://github.com/new-frontiers-14/frontier-station-14/pull/1312

**Comment by ErhardSteinhauer** [comment]
> No longer need #1312

Can you add `- type: SalvageMobRestrictionsNF` to `MobHumanoidHostileBase` and `MobNonHumanHostileBase` in `\Resources\Prototypes\_NF\Entities\Mobs\NPCs\base_humanoid_hostile.yml` then?

**Comment by dvir001** [comment]
> > No longer need #1312
> 
> Can you add `- type: SalvageMobRestrictionsNF` to `MobHumanoidHostileBase` and `MobNonHumanHostileBase` in `\Resources\Prototypes\_NF\Entities\Mobs\NPCs\base_humanoid_hostile.yml` then?

Anthing this is added to get deleted when leaving planets

**Comment by ErhardSteinhauer** [comment]
I'm using those 2 prototypes for all syndie/cultist/wizard mob both on expeds and on events, so should cover everything

**Comment by dvir001** [comment]
> I'm using those 2 prototypes for all syndie/cultist/wizard mobs both on expeds and on events, so should cover everything

MFW No more selling humans, oh well

**Comment by ErhardSteinhauer** [comment]
Gotta be Major Fast if ya wanna sell that dead meat

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
