### PR TITLE
04/01/2024 - NFSD Addons

### PR DESCRIPTION
**Pull request by Salvantrix**
Experimental hardsuit, Suit/wall storage for each NFSD role, updated over ear headsets to include encrpyts, added crates and crate filled variants, locked/unlocked nfsd colored doors, NFSDDrobe and inventory/ads, jetpack, sheriff stamp. Probably other things I'm forgetting.

## About the PR

Added a few fundamentals (I.e. on spawn loadout updates/doors/lockers/crates) so ships and the outpost can be updated.
Also added a couple quality of life and necessary machines, such as the NFSDDrobe.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by Cheackraze — APPROVED** [review]
looks good to me and passes tests. I cant test in-game at the moment so if someone is able to confirm, we can merge

**Comment by dvir001** [comment]
All stamps need to sit under the same folder or game bug

**Comment by dvir001** [comment]
DO NOT MERGE, THIS PR BREAKS ALL SHIPS WITH ``LockerBrigmedicFilledHardsuit`` IN THEM

**Comment by Salvantrix** [comment]
Issue resolved with hardsuit fill

**Pull request merged**
