### PR TITLE
Falcon (New Blackmarket pirate ship) 

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Adds the Falcon pirate ship, a medium sized ship with a hangar bay to store loot, vehicles and the riches. its meant to be used alongside hoverbikes so the pirate gang gets deployed to its victim while the ship pilot docks to the ship. 

Meant to look like the kestrel.

## Why / Balance

More ships for the pirates, yes.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Leander
- add: New falcon blackmarket ship.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
Nice.
- I noticed that the fire buttons are set to fire and toggle.  I recommend having it set to fire once per button press.
- You should add a chest with 4 of each type of cannonball to keep it in line with the other vessels...until we get a pirate uplink or a method to craft them anyway.
- You should add a defib closet, a box of bodybags, and a fire extinguisher.  Tools of the trade.
- You can add the single medicine walllocker back if you want.
image

**Comment by dvir001** [comment]
> Nice.
> 
> * I noticed that the fire buttons are set to fire and toggle.  I recommend having it set to fire once per button press.
> * You should add a chest with 4 of each type of cannonball to keep it in line with the other vessels...until we get a pirate uplink or a method to craft them anyway.
> * You should add a defib closet, a box of bodybags, and a fire extinguisher.  Tools of the trade.
> * You can add the single medicine walllocker back if you want.
>   image

Worst case we can always edit it again.

**Comment by dvir001** [comment]
Also make sure your job spawners are all 3 pirates (Just to make sure we aint got no pirate spawn on some weird place) and that there is no latejoin on it

**Review by MagnusCrowe — APPROVED** [review]
Looks great!

**Comment by WallaceLordofOwls** [comment]
This looks absolutely beautiful!

**Pull request merged**
