### PR TITLE
Bocakillo (New Blackmarket pirate ship)

### PR DESCRIPTION
**Pull request by MagnusCrowe**
## About the PR
It looks like a Bocadillo on radar to blend in with more innocent ships...
It's tight, it's uncomfortable, it's got almost no cargo room, but it will make NFSD think twice about getting in your personal space.

## Why / Balance

A tiny plastitanium vessel suited to a crew of 2 to 3 pirates. Has two broadside cannons and a rear-facing disposals launcher. Runs on plasma.

The disposals launcher will eject anything you put in it, at speed, toward whoever is following you...I suggest explosives or a particularly foolhardy boarding party.

## Media

image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Might break the meta.

**Changelog**

:cl:
- add: Adds the Bocakillo, pirate ship.

### CODE REVIEW

**Comment by ShinyStaraptor** [comment]
yo cool design but hear me out what if you made a mimic pirate ship of an investigator... hmmm? food for thought you know imagine the hijinks you could get up to with an investigator's shape esp since food trucks on frontier are rare nowadays

**Comment by Tych0theSynth** [comment]
The name and design made me laugh out loud when I saw it. This is brilliant and I love it.

**Comment by MagnusCrowe** [comment]
> yo cool design but hear me out what if you made a mimic pirate ship of an investigator... hmmm? food for thought you know imagine the hijinks you could get up to with an investigator's shape esp since food trucks on frontier are rare nowadays

I work best under tight constraints.  The concept here was, build a tricky pirate ship in 1 night.  Investigator is too much for me to deal with under that constraint.

**Comment by MagnusCrowe** [comment]
Might replace the walls with reinforced walls instead of plasteel...considering it.

**Comment by Wolfking6116** [comment]
Given that it's sort of a "scrappy fighter" style ship, it makes sense that they'd pull what sources they could to armour it

**Comment by MagnusCrowe** [comment]
New shuttle console?

**Comment by dvir001** [comment]
> New shuttle console?

The actual syndicate one has added range, this one is just skin

**Review by dvir001 — APPROVED** [review]

**Comment by WallaceLordofOwls** [comment]
@MagnusCrowe I took the bocadillo out briefly this last round, I love it! There was one issue I noticed with it though. The distro air tank actually starts completely empty! I assume that it's just an oversight, so if that could be fixed in a patch that would be great.

**Pull request merged**
