### PR TITLE
Preupdate Upstream Gas Changes and edits

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Updated gas worth numbers per upstream https://github.com/space-wizards/space-station-14/pull/32407

~~Removed all canisters buy options from cargo, in general you can always can visit trade depo and frontier for canisters refills.
Or pay someone to get them / get them yourself.~~

Canisters should be upped to 1000 to make canisters worth for salvage in a possible later PR, this will require ships price changes.

## Why / Balance
Much needed balance pass for gas worth + canister base worth.

Fix a long small issue with gas fucking ship prices on init since the added gas added price for ships, wack.

## How to test
N/A

## Media
N/A

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Ship prices might shift a bit up and down, but wont change the sell back price to be lower since the gas themself have no added worth.

**Changelog**
:cl:
- tweak: Atmos gas sell prices significantly lowered.
- tweak: Frezon now consumes significantly more tritium to produce.

~~Removed canisters from cargo catalog, free canisters refills available from frontier and trade outpost, added empty canisters to canisters loot pool.~~

### CODE REVIEW

**Comment by dvir001** [comment]
Numbers are not final, all up to change.

**Comment by tonotom1** [comment]
> Numbers are not final, all up to change.

Recommend partially restoring value to water vapor, co2, no2, and plasma for salvagers. 0.4 speso/mol would make them worth approximately 1000/can

The 0 price changes had station gameplay resource conditions in mind (miners)

**Comment by dvir001** [comment]
> > Numbers are not final, all up to change.
> 
> Recommend partially restoring value to water vapor, co2, no2, and plasma for salvagers. 0.4 speso/mol would make them worth approximately 1000/can
> 
> The 0 price changes had station gameplay resource conditions in mind (miners)

Canisters themself will get the base worth up, in another PR.

**Comment by blackknight954** [comment]
So with all respect... What's the point of using the gasbender or ambition if this were to be merged?
Gases having no/significantly less value kinda invalidates them. Frezon is already rarely made because there's just so much easier ways of making money, it's not like upstream where you have enough oxygen to feasibly make enough frezon to supply cargo with 200K, which is not as valuable on Frontier.

But this will kill atmos on Frontier.

**Comment by baldylabs** [comment]
What? No.

I don't see any real consideration for the already hurting atmos situation, and even then - have you ran the compound prices of salvaged can + new gas price? You'll be nerfing both a dying atmos and salvage. No one's gonna take 1k can, just cause of time/space/cost ratio.

**Comment by baldylabs** [comment]
After further thinking, if the issue it's trying to fix is as stated; atmos ships base init sell value does not correspond to the intended price, remove the cans from the ship - add buyable gas canisters like oxygen and nitrogen to Cargo. I don't remember any ship spawning with rarer/expensive gases.

**Comment by dvir001** [comment]
Alright few changes I'll be making here:

Atmost pricing going to be omited from buy at sell of ships to remove the issues.

New gas mining astroid events will be added before this PR to give new options.

Leaving this PR closed for now, reopen when ready.

**Comment by whatston3** [comment]
"already hurting atmos situation" - Atmos gameplay should consist more than making the largest room you can of supercooled plasma and then selling your ship wholesale for money.  That is dumb.  Players should be incentivized to do something with their gases beyond "fill big room".

In terms of ideas, a constructible "gas port" that functions like a specialized airlock and a beefy bidirectional pump could be useful, especially if Big Ed's needs copious amounts of gas.  We don't have a good way to transport decent quantities of gas that isn't a complete pain in the ass.  A drop-off point for larger gas tankers could be an interesting concept.

**Comment by blackknight954** [comment]
> "already hurting atmos situation" - Atmos gameplay should consist more than making the largest room you can of supercooled plasma and then selling your ship wholesale for money. That is dumb. Players should be incentivized to do something with their gases beyond "fill big room".
> 
> In terms of ideas, a constructible "gas port" that functions like a specialized airlock and a beefy bidirectional pump could be useful, especially if Big Ed's needs copious amounts of gas. We don't have a good way to transport decent quantities of gas that isn't a complete pain in the ass. A drop-off point for larger gas tankers could be an interesting concept.

People do this???

Only way I've done it is the normal way of freezeer and pipes, that's... what...

**Pull request closed without merging**
