### PR TITLE
New Ship Design: NT Liquidator - Dedicated Janitorial Vessel

### PR DESCRIPTION
**Pull request by ErhardSteinhauer**
## About the PR
A small ship (175 tiles) equipped with everything one might need to make even the dirtiest ship squeaky clean (ducky slippers included). Notable features:
- Wide array of janitorial supplies, a drain, a sink, and material/biomass recyclers;
- Small chemlab for cases when janitor needs to clean potassium spills;
- Small scale atmo setup for cleaning and replacing atmosphere in a ship if needed;
- Hull shape resembles Light Replacer tool (yet not entirely devoid of function);
- Galoshes!

## Why / Balance

According to my unsystematic observations that I absolutely can not back with statistics, by the mid-shift ships tend to become rather untidy (especially science oriented vessels) and sometimes it goes so far that air in them becomes barely breathable. Given that as of right now there are no dedicated janitorial vessels in the shipyard I decided that I can submit a design of such vessel.

## Media

Figure 1 - Map editor screenshot without subfloor and spawn view

Figure 2 - Map editor screenshot with subfloor and spawn view turned on

Figure 3 - "In game" screenshot after you buy it from shipyard

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- added NT Liquidator - a dedicated janitorial vessel

**Contact info**
Discord username: erhardsteinhauer

### CODE REVIEW

**Comment by dvir001** [comment]
Jani cart need to be spawner

**Comment by ErhardSteinhauer** [comment]
> Your change log just going to say "NT Liquidator" unless you fix it  
What should I put in the changelog for the first commit? Sorta added the whole ship hence just its name in changelog.

> Jani cart need to be spawner
I don't have janicart mapped there at all. Or are you talking about janitorial trolley?

> Axe storage no axe?
I used an entity named "Fire Axe Cabinet [Filled]". Axe was present when I tested the ship despite the sprite on screenshots suggesting otherwise.

**Comment by IData-RedactedI** [comment]
For the change log, put something like (added the liquidator, a dedicated janitorial ship).

**Comment by ErhardSteinhauer** [comment]
Updated PR title, changelog and added captions to screenshots. Also provided my discord contact.

**Comment by Cheackraze** [comment]
your price is too low, the cost of the ship is 24,201 so you should probably aim more for the 28-32k range for the cost of the ship.

Also, i know its pretty much cramped in there, but a janidrobe vending machine might be a better fit than maybe the stack of clothes. And a portable scrubber would be a good addition as well, since you can also then clean player's air.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
