### PR TITLE
Public Transit

### PR DESCRIPTION
**Pull request by Cheackraze**
## About the PR

This implements an automated public transport shuttle that moves between Frontier proper, and a select few POIs. At the moment, the bus stops at Frontier, at Tinnia's, and the Exped lodge, although the order of the stops is typically a bit random.  In the future, the NFSD will likely be added to the stop.
## Why / Balance

free transport, to help people get around, to bring back that wow classic feeling of waiting for the blimp with your homies to go raid stormwind
## Technical details

adding the `StationTransit` component to a grid while mapping, similar to adding the `BecomesStation` component, will allow a grid to be added to the list of bus stops dynamically whenever its loaded in.

Race conditions on component/map init events resulted in a slightly hacky workaround to prevent the system from adding a map that a mapper is working on, from being added to the bus stop list.  As a result of this less-than-ideal workaround, only grids/maps spawned into the default game map (the default playing field for players while in a game) are allowed to be put on to the bus stop list.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the Public Transit system to a limited number of Points of Interest
- fix: Fixed Janitors spawning on the wrong station at round-start.

### CODE REVIEW

**Comment by Cheackraze** [comment]
the map checker is going to fail because I used APUs I reckon

**Comment by Cheackraze** [comment]
also DNM until I clean up the comments, as they are wrong. Badly wrong.

**Comment by dvir001** [comment]
Only 2 issues I can think of is sound related with FTL but it will be fixed from upstream later.
And the gibbing issue if it spawn on someone standing on the place the ship about to teleport to (This was done upstream so people stop getting into command rooms in evac shuttles by knowing where the room going to spawn)

So if anyone fly in space where the ship about to show up, they will gib, just keep in mind we need to change it back when we merge.

**Comment by Cheackraze** [comment]
> Only 2 issues I can think of is sound related with FTL but it will be fixed from upstream later. And the gibbing issue if it spawn on someone standing on the place the ship about to teleport to (This was done upstream so people stop getting into command rooms in evac shuttles by knowing where the room going to spawn)
> 
> So if anyone fly in space with jetpack where the ship about to show up, they will gib, just keep in mind we need to change it back when we merge.

its just using regular ftl code, nothing special, so if it affects the bus, it will likely affect purchasing new ships as well, since its basically the same action that happens in regards to FTL.  Good to know for the future though

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
