### PR TITLE
Make APCs emp (when turned on) after a random delay during a power grid check

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Taken from https://github.com/Sector-Umbra/Sector-Umbra/pull/24

## Why / Balance
Adds a system which makes device emp itself when in a overloaded state. This can be adapted to be used for other devices which are not APCs.

## How to test
Buy any ship
add game event PowerGridCheck
Try to screwdriver the APC
Try to toggle the APC

## Media
N/A

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: APCs will now emp itself during a power grid check when they are turned on.

### CODE REVIEW

**Comment by Sinis-Boop** [comment]
I should not have told him how to reset APCs 😭

**Comment by Tych0theSynth** [comment]
I'm really not entirely sure how I feel about this, but I do feel largely negative. Having experienced this in the past, it works fine on a station where you can quickly have an engineer in with an APC board to fix it up.
It's going to be FAR more debilitating on shuttles and I feel like this effect will be even more punishing to newer players.

Of particular worry is if the cruise setting on the shuttle console continues when it's turned off. If this is the case, a destroyed APC could keep someone flying and unable to stop for a VERY long time and will make rescue extremely difficult.

How much damage does the explosion do? Could it cause hull breaches? Could it kill someone?

What do you do if there's nobody around who can fix it? That's basically your round over and ship dead for a tiny reason.

**Comment by Houtblokje** [comment]
> I'm really not entirely sure how I feel about this, but I do feel largely negative. Having experienced this in the past, it works fine on a station where you can quickly have an engineer in with an APC board to fix it up. It's going to be FAR more debilitating on shuttles and I feel like this effect will be even more punishing to newer players.
> 
> Of particular worry is if the cruise setting on the shuttle console continues when it's turned off. If this is the case, a destroyed APC could keep someone flying and unable to stop for a VERY long time and will make rescue extremely difficult.
> 
> How much damage does the explosion do? Could it cause hull breaches? Could it kill someone?
> 
> What do you do if there's nobody around who can fix it? That's basically your round over and ship dead for a tiny reason.

I mean I do like the idea of having more things for engineers to do, but I agree that this might be too punishing.

**Comment by Tych0theSynth** [comment]
> > I'm really not entirely sure how I feel about this, but I do feel largely negative. Having experienced this in the past, it works fine on a station where you can quickly have an engineer in with an APC board to fix it up. It's going to be FAR more debilitating on shuttles and I feel like this effect will be even more punishing to newer players.
> > Of particular worry is if the cruise setting on the shuttle console continues when it's turned off. If this is the case, a destroyed APC could keep someone flying and unable to stop for a VERY long time and will make rescue extremely difficult.
> > How much damage does the explosion do? Could it cause hull breaches? Could it kill someone?
> > What do you do if there's nobody around who can fix it? That's basically your round over and ship dead for a tiny reason.
> 
> I mean I do like the idea of having more things for engineers to do, but I agree that this might be too punishing.

Oh don't get me wrong, I'm ALL for giving engineers more to do. I don't exactly see this encouraging more people to play engineer, however.

**Comment by dvir001** [comment]
What explosion? this PR is about EMP, no idea what you all talking about.

**Comment by Houtblokje** [comment]
> What explosion? this PR is about EMP, no idea what you all talking about.

give EMP's a random chance to fry a non-essential circuitboard (so everything other than doors, apc's, shuttle consoles, station consoles and anything else you really need for the ship to function) haha

**Comment by Leander-0** [comment]
first half

**Comment by dvir001** [comment]
Remaking this into something else

**Pull request closed without merging**
