### PR TITLE
VGRoids events

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added a new event pool to spawn massive in world dungeons VGRoids, right now with 4 types:
Caves, Shadow, Snow, Lava

Starts 10 minutes into shift, last 30 minutes per event, waits 10 more minutes before spawning another one on a loop.

Upped expos cool-down 20 minutes on pass, 30 on lose.

## Why / Balance
Fun as hell

## How to test
Either spawn one by adding it to game rule or wait 10 minutes with cargo key on headset.

BluespaceDungeonCave
BluespaceDungeonChromite
BluespaceDungeonSnow
BluespaceDungeonBasalt

## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- add: New massive dungeon asteroids were added, keep an eye out for them on radar and be informed about them on supply radio, be prepared for a fight.
- tweak: The cooldown on expedition FTL has been extended, you will now need to wait longer to depart on another mission.
- remove: Space dungeons (the big orange platforms) no longer spawn.

### CODE REVIEW

**Comment by dvir001** [comment]
This is ready.
Keep in mind a lot of the code changes on upstream files isn't commented since its coming from upstream open PR's made by ED

**Comment by dvir001** [comment]
https://github.com/space-wizards/space-station-14/pull/33110
Reminder to update this

**Review by whatston3 — COMMENTED** [review]
Is there a way to easily despawn all the little gridlets that fragment off of the main chunk?  They seem to persist afterwards.

Maybe if we handled GridSplit events on some component that's only on the dungeon grids (and then anything that's marked as splitting _off_ of those, marked them as being tied to the big one's destruction, and queued them all for deletion when the big one's deleted?

Edit: **did it, works fine**

**Comment by whatston3** [comment]
> Maybe if we handled GridSplit events on some component that's only on the dungeon grids (and then anything that's marked as splitting off of those, marked them as being tied to the big one's destruction, and queued them all for deletion when the big one's deleted?

Possible benefits to this - tagging all shuttle grids with this should result in easy garbage collection when somebody sells a ship.

**Comment by dvir001** [comment]
I like where this is standing, I think its done, done unless you want to make more changes.

**Review by whatston3 — APPROVED** [review]
Forgot to leave a comment on this - I think this is a good step.  I think the ore that generates on vgroid itself isn't a huge draw, the dungeon might be interesting, but the loot tables, spawn timers, etc. could use a balance pass - waiting for feedback might make sense there.

Probably meets "good enough, polish later", I'll approve it.

Hope Ed's stuff makes it in upstream, though.

**Comment by GreaseMonk** [comment]
it's basically expeditions but available every other half hour, pretty nifty.
Good stuff. 

Needs more generation testing, this is very frustrating:
image
image
image

**Comment by TheShuEd** [comment]
Based dvir

**Review by GreaseMonk — APPROVED** [review]
tested to be working

**Pull request merged**
