### PR TITLE
Mix up atmos on planets

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Added more gas mixes to expo, made it more simple to tell what they are unless you select unknown.
Selecting unknown will give you one few crazy mixes.

## Why / Balance
Add more options and make them more easy to select
Make the "fun" ones random selection

## How to test
Open on release or debug
Get expo ship
Look at expo selection
Go on one and see the gas on planet. 

## Media
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: Changed and added more atmos selections on planets expeditions.

### CODE REVIEW

**Comment by dvir001** [comment]
> Ooooh, nice
> 
> Is there a chance of Tritium atmos by chance?
> 
> Also having ammonia as a toxic gas seems interesting
> 
> Overall a pretty neat change, albeit the changes from #2421 might discourage players from siphoning Co2, N2O, NH3, basically anything that isnt necesary for tritium/Frezon production.
> 
> Additionally, is this going to cause emptying gas canisters on expedition tilesets to actually change their atmos? or are they still going to be static

`- type: salvageAirMod
  id: Unknown1
  cost: 5
  desc: salvage-air-mod-unknown
  gases:
    - 5 # oxygen
    - 5 # nitrogen
    - 7.321316 # carbon dioxide
    - 5 # plasma
    - 0 # tritium
    - 34.642633 # water vapor
    - 12.321316 # miasma
    - 34.642633 # nitrous oxide
    - 0 # frezon

- type: salvageAirMod
  id: Unknown2
  cost: 5
  desc: salvage-air-mod-unknown
  gases:
    - 0 # oxygen
    - 0 # nitrogen
    - 17.321316 # carbon dioxide
    - 17.321316 # plasma
    - 0.3 # tritium
    - 33.642633 # water vapor
    - 0 # miasma
    - 34.642633 # nitrous oxide
    - 0.1 # frezon

- type: salvageAirMod
  id: Unknown3
  cost: 5
  desc: salvage-air-mod-unknown
  gases:
    - 20 # oxygen
    - 20 # nitrogen
    - 17.321316 # carbon dioxide
    - 2.321316 # plasma
    - 0.3 # tritium
    - 13.642633 # water vapor
    - 15 # miasma
    - 14.642633 # nitrous oxide
    - 0 # frezon

- type: salvageAirMod
  id: Unknown4
  cost: 5
  desc: salvage-air-mod-unknown
  gases:
    - 15 # oxygen
    - 15 # nitrogen
    - 12.321316 # carbon dioxide
    - 2.321316 # plasma
    - 0.1 # tritium
    - 13.642633 # water vapor
    - 20 # miasma
    - 14.642633 # nitrous oxide
    - 0.5 # frezon

- type: salvageAirMod
  id: Unknown5
  cost: 5
  desc: salvage-air-mod-unknown
  gases:
    - 20 # oxygen
    - 20 # nitrogen
    - 17.321316 # carbon dioxide
    - 1.321316 # plasma
    - 2 # tritium
    - 13.642633 # water vapor
    - 15 # miasma
    - 14.642633 # nitrous oxide
    - 0 # frezon`
    
    Nothing changed with canisters.

**Review by ErhardSteinhauer — APPROVED** [review]
Looks good.

**Comment by ErhardSteinhauer** [comment]
> Looks good.

Kinda
image

**Comment by dvir001** [comment]
> > Looks good.
> 

Yes.

**Comment by dvir001** [comment]
Probably might need to give this another edit but this is a good start point.

**Pull request merged**
