### PR TITLE
Medical Bounties

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

* Adds medical bounties to the game.
* Removed the dungeon and salvage corpse spawners from the salvage chest spawners found on wrecks.
* All corpses found on wrecks now have names and medical bounties associated with them.
* All corpses found on wrecks and dungeons now have loadouts associated with them (edited versions of the visitor loadouts)

### TO DO:
* [X] Revise loadouts for corpse classes (removing unwanted equipment) (note: some still have basic sec armor, all weapons and fluff removed)
* [X] Add HideSpawnMenu to new medical bounty loadout entities
* [X] Add replacement sprites for the body retrieval unit
* [X] Fix UI layout
* [ ] Fix the slot contents shown in the right-click 
* [X] Map a body retrieval unit (probably in the back rooms of Frontier's medbay)
* [X] Add a tool to view the maximum and current bounty value of a medical bounty. (No current at the moment)

Upon spawning, any entity with a medical bounty receives damage according to a randomly selected preset.  The value of the bounty associated with them is assigned based on the total amount of received damage (and possible reagents added to the patient) - the idea here is to reward medics proportionally to the amount of work or materials put in to restoring the patient to health.

## Why / Balance

Medical bounties are intended to give medics something to do during downtime without being so profitable as to supplant rescuing other injured players.  This should reduce downtime as a medic for slower or more populated shifts, and provides a lower-stress option for experimenting with treatment.

## How to test

1. Fly around to wrecks.
2. Find one with a corpse (should be somewhat rare, expecting one per few wrecks, ideally a few minutes per find).  The corpse should be clothed.
3. Heal the damage on the body using the restore trick.
4. Spawn a body retrieval unit (MachineMedicalBountyRedemption).
5. Check the value of the bounty using VV (MedicalBountyComponent).
6. Load the corpse into the unit, use the UI, redeem the bounty, the full value of the bounty should spawn on top of the machine.
7. Spawn another corpse.
8. Open the UI for the unit, it should say nothing's loaded in.
9. Load in the body, it should say that the body has too much damage.
10. Heal most of the damage (or restore it and hit it a few times with a weapon), make sure the target is alive and not critical.
11. Load the body into the body retrieval unit.
12. The bounty should redeem upon pressing the button and a reduced bounty price should be available given the amount of damage the corpse has.

## Media

TBD.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Medical bounties are available for all corpses found on wrecks.

### CODE REVIEW

**Comment by GreaseMonk** [comment]
I tested this in a 'real' scenario, here are my findings:

- it took me 9 wrecks to find a body, prefer to keep same amount of body spawn rate but lower their damage and bounty so you can learn medical as a new player
- i would say really rare chance a body needs a cryo system to get their 35k bounty for healing tons of damage
- When there is an occupant in the medical bounty, it still says empty
- by preference once the body is inside it immediately spawns spesos without using the ui

**Review by whatston3 — COMMENTED** [review]
This should be good to go.

1. Bodies now spawn in pods out on wrecks ("emergency medical pod").  These pods have little yellow lights that should stand out in the dark.  They're incredibly heavy to lug around (similar density to a trade crate), and keep the body stabilized in ~1 atm of water vapor at -10 C (for a "cryo open" effect if opened indoors) - effectively a freezer but worse to lug around.
2. The medical appraisal gun is now printable in the medical techfab, and costs 5 steel and 3 glass (OTOH, numbers may be reversed).
3. Fiddled with numbers to add more "easy to handle" bounties with lower overall amounts of damage.  Severe burns should now pay out better per point of cold/heat damage.
4. Spawned in an extra redemption pod in Frontier's medbay.  These should probably be moved at some point, but as a first pass, this is acceptable.
5. Increased the spawn rate of the medical pods.  It's effectively ~5x the original rate by spawning on plate and spawning at a higher rate.
6. Sanitized the spawned clothing further - no HoS gear, no HoP gear (confusing for other players), boxers have tank tops.
7. Moved the medical corpse spawns to a StorageFill (had to apply a fix to the Storage system to ensure they actually get inserted into the pod - not great, but it works)
8. Reduced redundant definitions of corpse loadouts using YAML anchors.
9. Medical bounty corpses no longer appear on crew monitors.  The idea here is that somebody should be scouring wrecks for bodies.

As-is, I think this makes for compelling medical gameplay with a team of about 3 (CMO/doctor, chemist, paramedic).  Doing it all yourself sucks but is possible.  I'll include pictures soon.

**Comment by whatston3** [comment]
Added a guidebook page about medical bounties (probably not great but it's something).
Added Erhard's sprites for the emergency medical pod, touched up the health analyzer display in them.
image

**Comment by Ansome101** [comment]
One hour test of the release candidate:

Going through 56 wrecks, I recovered a total of 15 corpses with a total value of 136,180 spesos.

This is not a terrible rate if you are exclusively jumping from wreck to wreck in search of them, but I am concerned about their spawn rate for the average medical crew that will be visiting significantly fewer wrecks and spending more time searching them on average.

**Review by ErhardSteinhauer — APPROVED** [review]
Works in game

**Pull request merged**
