### PR TITLE
Adjusts NFSD Time to more appropriate values

### PR DESCRIPTION
**Pull request by Salvantrix**
Updates the time to as follows:

> * Cadet - Requires 6 hours of Frontier and removed time cap for roleplay reasons. *This can be looked at a bit more, just for rp purposes but to not take up the job slot for people who need it*

> * Deputy - Remains the same 

> * Detective - Remains the same 

> * Brigmedic - Increased to 12 hours of Frontier gameplay and remains at 6 hours of NFSD gameplay. 

> * Sergeant - Increased to 18 hours of Deputy Gameplay and 12 hours of NFSD gameplay. 

> * Bailiff - Increased overall NFSD gameplay to 18 hours.

> * Sheriff - The biggest change, now requires 24 hours of NFSD gameplay overall and 6 hours for Bailiff and the same 12 hours for Sergeant.

> For context here's the current playtime requirements to compare:
> * Cadet - 6 hours general playtime
> * Deputy/Brigmed/Detective - 12 hours general playtime // 6 hours as cadet
> * Sergeant - 30 hours general playtime // 12 hours deputy
> * Bailiff - 30 hours general playtime // 6 hours as Sergeant
> * Sheriff - 36 hours general // 12 hours sergeant + 12 hours bailiff // Whitelist Accept

Also added a 3 hour NFSD playtime requirement for Pirate and Pirate first mate.
Added 3 hours of Sergeant playtime requirement for Pirate Captain.

## About the PR

> Adds a more balanced time spread, increases some base Frontier and NFSD gameplay hours but reduces the more specific role hours that are harder to come by i.e. the Bailiff. 
> This remains in draft format for a reason, to promote some discussion.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: NFSD time requirements have been increased, with alternate sets available for longtime players.
- tweak: Pirates, First Mate and Prisoner now require 3 hours of NFSD gametime, with Pirate Captain needing 3 hours of Sergeant.
- tweak: Station Representative now requires 3 hours of Security Guard playtime.

### CODE REVIEW

**Comment by dvir001** [comment]
I think we should just fix the time requirements to require Nfsd playtime **OR** Total playtime for all Nfsd jobs except sheriff.

Also please add 3 hours of Nfsd playtime for pirate and pirate first mate.
And dare I say, 3 hours of sheriff to Pirate Captain (Or other Nfsd job).

**Comment by BluCottonCandy** [comment]
Looks great
I wouldn't mind seeing needing a bit of sheriff time for pirate captain. 
Might get more people to play sheriff, and it'll give some others a much needed reality check for how difficult being a sheriff can be.

**Comment by Cheackraze** [comment]
I was under the impression we wanted to *lower* the requirements for some of the NFSD roles? And it looks like here they are all being increased instead?

**Comment by Salvantrix** [comment]
> I was under the impression we wanted to *lower* the requirements for some of the NFSD roles? And it looks like here they are all being increased instead?

Not necessarily a decrease overall really in the grand scheme of things, just adjusted general playtime and decreased the Bailiff requirement, was something just to get pushed into a pr and viewable at the very least. They can definitely be adjusted based on feedback, but it seemed the general consensus was that the Bailiff requirement is what was the biggest hurdle maybe? 

So instead of making Sheriff and Bailiff have hardcore time caps, reduce them and increase Sergeant time. The reasoning being there are typically more sergeants so more opportunities to gain time.

**Comment by Salvantrix** [comment]
Basically reduce specific role timers for the most part, and replace it with general department playtime. So even if you don't get Bailiff since it's typically a 1 of 1 role, you're still benefiting your time to unlock sheriff by being forced to play a lower ranked role.

**Comment by whatston3** [comment]
Added alternate sets for all of the NFSD jobs except for the cadet, cleaned up yaml entries (no need for Frontier tags, and a consistent order of job requirements - most broad to most specific) and fixed up a bug with job requirements - TryRequirementsMet wasn't respecting the alternate job sets.

Time requirements in the PR at the moment are as follows:
```
SHERIFF:
36h total
24h sec
12h sergeant
6h bailiff
-or-
300h total
18h sec
6h bailiff

BAILIFF:
30h total
18h sec
6h sergeant
-or-
200h total
12h sec
6h sergeant

SERGEANT:
30h total
18h sec (swapped with deputy)
12h deputy (swapped with sec)
-or-
150h total
6h deputy

BRIGMEDIC:
12h total (up from 10)
6h sec
-or-
100h total

DETECTIVE:
12h total (up from 10)
6h sec
-or-
100h total

DEPUTY:
12h total
6h sec
-or-
100h total

CADET:
6h total
```

For a new player with no NFSD time, they will need a minimum of 48 hours of gameplay (36 of that being in the NFSD) to unlock sheriff (assuming they were whitelisted).
With this set of changes, an experienced player can unlock that in 24 hours minimum assuming 276 hours of previous playtime.  I'm not entirely sure about removing the maximum from cadet, but I think any issues there will come out in the wash.

**Comment by Houtblokje** [comment]
I have also said this in the discord, but I also think that removing the max cap of cadets will bring more issues than it is worth.
Mainly that cadet slots will be even more scarce, and also that you won't have a guarantee that cadets know little about nfsd.

**Comment by Salvantrix** [comment]
> I have also said this in the discord, but I also think that removing the max cap of cadets will bring more issues than it is worth.
> Mainly that cadet slots will be even more scarce, and also that you won't have a guarantee that cadets know little about nfsd.

It was brought up and I agree, a single shift cap is a little low for those new in general so maybe like 2 (12 hours) or 3 (18 hours) shifts would be more balanced?

**Comment by Houtblokje** [comment]
> > I have also said this in the discord, but I also think that removing the max cap of cadets will bring more issues than it is worth.
> > Mainly that cadet slots will be even more scarce, and also that you won't have a guarantee that cadets know little about nfsd.
> 
> It was brought up and I agree, a single shift cap is a little low for those new in general so maybe like 2 (12 hours) or 3 (18 hours) shifts would be more balanced?

Definitely. Make them still able to pick deputy if they want after 6 hours, but if they feel unsure of themselves they could choose to stay a cadet for a little longer.

**Review by whatston3 — APPROVED** [review]
Restored an 18h sec cadet max.  Going to leave an approval with this as-is, but I'll leave it open for discussion.

**Pull request merged**
