### PR TITLE
Fuel vending in the back of nfsd

### PR DESCRIPTION
**Pull request by VividPups**
## About the PR
they talk about not having the ability to buy fuel. so I put them in the engi area in NFSD so they don't have to buy a 10k crate for 3
## Why / Balance
they need fuel
## How to test
look at nfsd engi
## Media
image

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

## Breaking changes
rip the pockets of no sheriff shifts 
**Changelog**

:cl:
- add: Fuel vending to NFSD

### CODE REVIEW

**Comment by dvir001** [comment]
This should probably be on the outside side to allow civs to also visit for fuel

**Comment by VividPups** [comment]
> This should probably be on the outside side to allow civs to also visit for fuel

Was going to but Whatstone was against it

**Comment by Tych0theSynth** [comment]
> This should probably be on the outside side to allow civs to also visit for fuel

I agree with this, it feels like it makes more sense.
Sometimes NFSD bring back the ships of people they've arrested and dock them to the outpost. If that person then spends time locked up, they might return to a depowered ship without any fuel, so it would be handy to have it publicly available to avoid that happening or avoid making the deputies run around refuelling the ships of criminals!

**Comment by dvir001** [comment]
> Endless (literally) jugs of petrol on display in the lobby of the NFSD may be cause for concern.
> 
> While having the vending machine buried in the bowels of the station may not make much sense it could be wise to have the vending machine close to where officers may wish to provide or rapidly gain access but not within casual reach.

Sound more like an admin issue since a round start shitter wont even be there
If anything this is more main area frontier issue with the fuel vending.

**Comment by dvir001** [comment]
Fixed on https://github.com/new-frontiers-14/frontier-station-14/pull/1759

**Pull request closed without merging**
