### PR TITLE
Nerf tranquilizer shells

### PR DESCRIPTION
**Pull request by Leander-0**
## About the PR

Tranq shell takes 4 shots now to stun someone

## Why / Balance

2 tapping people is cringe

## Technical details

changed 2 numbers

:cl: Leander
- tweak: Tranquilizer shells now come with with less amount of CH.

### CODE REVIEW

**Review by neuPanda — COMMENTED** [review]
this is to large of a nerf.  it requires 10 units for it to do anything.  it starts metabolizing out as soon as it enters the body.  this means that you are going to need 6 tranqs with your double barrel to be able to do anything.  i propose knocking it down to 5 but nothing lower than 4. or it will make tranqs useless

**Comment by Leander-0** [comment]
> this is to large of a nerf. it requires 10 units for it to do anything. it starts metabolizing out as soon as it enters the body. this means that you are going to need 6 tranqs with your double barrel to be able to do anything. i propose knocking it down to 5 but nothing lower than 4. or it will make tranqs useless

Tranquilizers being more effective than lethals should not be happening and they are being used in combat scenarios to basically 2 tap win anything be it lethal or not lethal combat, they should not even go trough armor int he first place and it should be even its own blowdart gun with his own dart ammo.

this is the same issue with the 2 shot beanbags and will be getting the same treatment, if you want o kill use lethal, else there is rubbers and disable shots.

**Review by dvir001 — APPROVED** [review]

**Comment by dvir001** [comment]
Can we change this to 5, see feedback and nerf it more if needed? @Leander-0

**Comment by ErhardSteinhauer** [comment]
If you change it to 5 it's still 2 shots 'til KO. 4 maybe?

**Comment by ThatOneGoblin25** [comment]
> If you change it to 5 it's still 2 shots 'til KO. 4 maybe?

When the first one injects it starts to metabolize immediately, meaning that when the second hits there's 9.5u and no sleeping. Maybe if you hit both within half a second but that's very impractical just considering average latency.

**Comment by Leander-0** [comment]
changed time upon request and settled at 4u for the tranquilizers.

**Comment by dvir001** [comment]
Note that this update also allow waking up 5 secs into a nap instead of 15,  base on amount of sleep toxins in your blood this timer gets ignored but in cases when you have low amounts it just allows you to wake up faster rather then forced 15 sec

This also effects return from cryo, normal sleep, and waking up from N2 or sleep trait.

That's a change for the best overall with how broken this timer was.

**Review by Cheackraze — APPROVED** [review]

**Pull request merged**
