### PR TITLE
sv orange cargo/salvage shuttle

### PR DESCRIPTION
**Pull request by Carolyn3114**
## About the PR

adds the SV-Orange, a cheap cargo / salvage shuttle

## Why / Balance
partly destroyed, no tiny fans on salvage airlocks, 16k cost w/ 14k appraisal

## Media
image 

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Cheackraze** [comment]
you should make sv-station, a mini station like this where people can choose to start with very minimal supply, minimal amenities and they can only buy these ships. The true challenge mode

**Review by Cheackraze — APPROVED** [review]

**Comment by Carolyn3114** [comment]
> you should make sv-station, a mini station like this where people can choose to start with very minimal supply, minimal amenities and they can only buy these ships. The true challenge mode

interesting idea, but I'm not entirely sure how to go through with that, and I was only going to add one more of these for a trio.

**Comment by Cheackraze** [comment]
well its mostly the same idea, you would make a station like these and give it a late join spot or two, maybe the bare minimum of a sealed atmos to spawn in and a suit vendor or something, and then when its ready I will write in a special shipyard console that sells these ships and make it spawn at round start for an 'alternate start'

**Comment by Carolyn3114** [comment]
> well its mostly the same idea, you would make a station like these and give it a late join spot or two, maybe the bare minimum of a sealed atmos to spawn in and a suit vendor or something, and then when its ready I will write in a special shipyard console that sells these ships and make it spawn at round start for an 'alternate start'

I'm just not sure how to make it spawn on round-start

**Comment by Cheackraze** [comment]
you wouldnt need the vessel prototype, just the map/station one. All of the world spawning stuff happens from the game rule, I can code that in if you'd like, it isnt difficult

**Comment by Carolyn3114** [comment]
alright, maybe

**Pull request merged**
