### PR TITLE
Quanana

### PR DESCRIPTION
**Pull request by VividPups**
Quack

## About the PR
adds banana quack

## Why / Balance
we got cak, bread dog, killer tomato now we have Quanana
## How to test
make the Quanana via microwave 

## Media
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes in-game.

## Breaking changes
Harry in the future 
**Changelog**
:cl:
- add: New Banana duck species

### CODE REVIEW

**Comment by whatston3** [comment]
-milk
+banana honk
:+1:

**Comment by KyuPolaris** [comment]
we're so back

**Comment by dvir001** [comment]
Please audit the yaml it seems like it could have used less added lines and more parenting.

**Comment by VividPups** [comment]
Like what?

**Comment by VividPups** [comment]
huh, thats interesting remove all the new food stuff. I'll fix that later

**Comment by VividPups** [comment]
Can you please convert this into a draft

**Comment by ErhardSteinhauer** [comment]
> Can you please convert this into a draft

You can push this button do do that:
image

**Pull request closed without merging**
