### PR TITLE
BlackMarketShipyard does not alert security

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
## About the PR

Gives less information about the BlackMarket vessel to security to avoid metagaming due to complaints.
Those are unchanged for Syndicate Communications, only Security.

Before:
shuttle {$vessel} en route, eta 10 seconds.
After:
Unregistered vessel detected entering your sector

Before:
shuttle {$vessel} sold.
After:
Unregistered vessel detected leaving your sector

## Why / Balance

From talks i have gotten and complains, This sucks, as soon you buy a ship Security will just hunt you, put a bounty on you as soon as they can and just Metagaming.

So, SHUS no more accurate information for sec when someone buy a ship there, only in syndicate comms, Now security will actully have to just LOOK normaly in their patrol instead of hunting down a ship that just spawned.

## Technical details

.ftl changes and .cs changes

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: FoxxoTrystan
- tweak: Security are unable to pick detailed signals from arriving BlackMarket Shipyards.

### CODE REVIEW

**Comment by dvir001** [comment]
This is part of security gameplay to keep awareness of illegal ships in the sector

**Comment by Cheackraze** [comment]
I think that we could just obfuscate more details. Maybe remove the name of the ship and just give it a generic "Black Market Ship has been purchased" so that they dont immediately put a bounty out on 'Schooner NX-123'

**Comment by FoxxoTrystan** [comment]
> I think that we could just obfuscate more details. Maybe remove the name of the ship and just give it a generic "Black Market Ship has been purchased" so that they dont immediately put a bounty out on 'Schooner NX-123'

Thats could be also indeed, il do something that does give any of the information, just blackmarket ship has FTL in.

**Comment by Wolfking6116** [comment]
Information like this can be very important to have. The current system is definitely /too much/ information.

Maybe don't have it say it has FTL'd in persay... Just "A suspicious vessel has been spotted in the Sector." or something of that nature. 
If you can add a variable timer to the message as well, so it only sends it out 5-15 minutes after it's been purchased, then that adds some more depth to it as well.

**Comment by FoxxoTrystan** [comment]
> I think that we could just obfuscate more details. Maybe remove the name of the ship and just give it a generic "Black Market Ship has been purchased" so that they dont immediately put a bounty out on 'Schooner NX-123'

The deeds has been done.

**Comment by dvir001** [comment]
Seem fine
Might as well add it

I have another bigger rework in mind to remove some of the hardcodded ftl stuff so best to fix this before.

**Review by dvir001 — APPROVED** [review]
Seem fine

image

**Pull request merged**
