### PR TITLE
Gas Station Sushi

### PR DESCRIPTION
**Pull request by dvir001**
## About the PR
Sometimes we need to risk it all.

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Everturning** [comment]
i ate this and woke up in the sewer with a bunch of fish one time. we dont talk about what happened after

**Comment by chrome-cirrus** [comment]
Bought a bunch of it. Projectile vomited all over the station. Cats refused to eat it. Mouse gorged itself on it until it died. Perfect, no notes.

whathaveidone
animaltesting

**Review by whatston3 — APPROVED** [review]
Changes seem fine.  Printable sushi containers are a nice touch, happy with the state of this.

**Comment by whatston3** [comment]
The craftable sushi tray (right) now has a fill that looks like it won't destroy your insides.

image

**Comment by dvir001** [comment]
> The craftable sushi tray (right) now has a fill that looks like it won't destroy your insides.
> 
> image

Millions most die

**Pull request merged**
