### PR TITLE
Bike Reversion Discussion

### PR DESCRIPTION
**Pull request by Ed-Head**
## About the PR
Add hoverbikes back to cargo
reduce FUC cost of NFSD hoverbikes from 35 to 10.
Removed hoverbike from emagged flatpack vend

## Why / Balance
The hoverbike is not worth 35 FUC, there is no sheriff in their right mind who would pay that for something that's slower than T1 thrusters and that you cant shoot off of.

Furthermore, I don't believe that there was a reason to remove them from cargo.
At the very least, the wider community should have more than a few hours to talk about it. If people overwhelmingly want them removed from cargo or kept then that should be at least considered.

Not having these discussions removes people from the pool of discourse and limits the eyes on important changes. 

## How to test
Buy it from cargo, observe the FUC catalog.

## Media

- [ x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**

-tweak: Put hoverbikes back into the cargo catalogue
-tweak: Reduced the FUC cost of NFSD hoverbikes.
-remove: Flatpack vend can no longer be emagged for hoverbike flatpacks.

### CODE REVIEW

**Comment by dvir001** [comment]
I'm fine with the price change for nfsd but we're moving them to Expedition find on planets to remove cost from them and make them sellable from expo teams

**Comment by Ed-Head** [comment]
I wouldn't mind that so much if buying things from exped teams didnt feel like pulling teeth for reasons everyone has talked about a million times. If you _really_ don't think they should be obtainable from cargo I think they should be able to be researched by science teams.

**Comment by ErhardSteinhauer** [comment]
Scientist have enough exclusive things to sell, not sure if adding another one to ever growing pile of things obtainable from sci needed. Exped exclusive things should be more common, hoverbike might be one of them.

**Comment by Ed-Head** [comment]
Again, I would be okay with more things being exped exclusive if I actually thought buying them from exped crews is a reasonable answer. Trying to buy from exped crews is extremely difficult considering half of the time they cant hear the radio and the other half they ignore it. 

If you want exped loot you pretty much have to run expeds. As someone who has tried to run a bazaar a number of times now this news makes me sad, but its true.

**Comment by ErhardSteinhauer** [comment]
Maybe the issue stems from expeds crews having nothing to offer for sale, that couldn't be obtained from scientist in absurd amounts before exped crews even finish their first planet dive?

**Comment by dvir001** [comment]
> Again, I would be okay with more things being exped exclusive if I actually thought buying them from exped crews is a reasonable answer. Trying to buy from exped crews is extremely difficult considering half of the time they cant hear the radio and the other half they ignore it.
> 
> If you want exped loot you pretty much have to run expeds. As someone who has tried to run a bazaar a number of times now this news makes me sad, but its true.

There is a new system in the works that allow selling the cargo and having the item be able to be bought back from it.

Allowing passive selling to a market.

**Comment by Ed-Head** [comment]
There are plenty of items from exped crews that I have tried to buy and have had laughably little success with and not due to a lack of effort.
To list a few

-IFF boards
-RTGs 
-High tier guns
-Stimulants
-Bombs
-Those crystals in the cave expeds (I like lights)
-Bluespace parts
-Dragon Flesh

There should be more that expeds crews can offer I agree, but I dont think the root of the issue stems from a lack of items. I feel the isolation inherent to running expeds and their inability to hear the radio on mission. Nor do I think adding the Hoverbike would fix this. 
People would sell it for about a week before they get bored of it, because its a fun gimmick item. Its a jetpack with storage thats slower than a ship.

For all these reasons, at least not at this time, should hoverbikes be limited to exped loot only

**Comment by Ed-Head** [comment]
> > Again, I would be okay with more things being exped exclusive if I actually thought buying them from exped crews is a reasonable answer. Trying to buy from exped crews is extremely difficult considering half of the time they cant hear the radio and the other half they ignore it.
> > If you want exped loot you pretty much have to run expeds. As someone who has tried to run a bazaar a number of times now this news makes me sad, but its true.
> 
> There is a new system in the works that allow selling the cargo and having the item be able to be bought back from it.
> 
> Allowing passive selling to a market.

Then perhaps we should hold off on its removal until that feature is ready.

**Comment by BluCottonCandy** [comment]
I agree that we shouldn't remove the hover bikes until the systems are added. 

If the Exped rewards were merged along with this I would be more alright with it. 

However as it stands hover bikes are all but gone with the merge and so I also agree we should revert the changes with this PR.

**Comment by WallaceLordofOwls** [comment]
Why not just have the hover bikes in cargo for a week or two and see if they cause issues? If they don't cause issues, then why not just have them in cargo?

**Comment by VividPups** [comment]
> I'm fine with the price change for nfsd but we're moving them to Expedition find on planets to remove cost from them and make them sellable from expo teams

Maybe as An extremely Rare salvage item would be neat. Not everyone is really good at expeditions, some Avoids it. I feel like having 2 types of way would be better then having to wait for an expedition

**Comment by mrscratch** [comment]
I don't know if something changed but I'm pretty sure you can shoot from them. I did an Exped with a couple people that had hover bikes and they were doing drive bys with them.

Amyways, Hover bikes are strong. Last night the powers that be put a bounty up on a pirate. The pirates ship was pinned by about 3-4 vessels and once it was locked in place there were about 4-6 hover bikes circling the pirates ship. I don't know how exactly the situation played out as I left laughing at all the hover bikes but I know in the end the pirate was caught or gave up.

In terms of E-mag I'm honestly not a big fan of emags gatekeeping a lot of our content. The average player will never see one of those cards. Sure there are things that really do need to be emagged that are powerful or illegal as fuck, but for the most part there's lots of cool shit that is wasteful of your emag uses so you never see them. Exclusive clothing that stat wise sucks if they even have any armor stats to begin with, a sweet ass bass guitar, the black and red smokes etc etc. To be honest what we really need is an E-Mag review to REMOVE stuff locked behind E-Mag unless it is an obviously game breaking illegal themed item.

FuC wise Hover Bikes are strong but probably not that strong. They're essentially invisible ships that you can fire a gun from. So if you catch a SUSPECT parked somewhere or you have ships crashing into them to slow them down any officer can jump on a bike and just ambush the SUSPECT's ship with an EMP, wrench their thrusters boom. Ship out of commission. We're not seeing stuff like this now but as the community becomes more familiar with them you'll start seeing some powerful moves coming from the bikes.

Finally, "put hoverbikes back into the cargo catalogue". I think we might need just a bit more time with this to see how it plays out, take more notes see how it truly effects gameplay as people get smarter with them. One change as weird as it may sound that I recommend is that instead of putting it in Cargo I would remove the Hoverbike and put it as a flatpack that you buy from the EngiVend that sells the screwdrivers, and remove the ATV and put it in the EngiVend that sells the multitools. It's super annoying when you join 2-3 hours into a shift and there are 0 multitools. And it's super fucking annoying when there are 0 multitools and 0 screwdrivers so you can't even buy a screwdriver to restock. I know there's a vending machine already dedicated to flatpacks but if we had these two modes of transportation tied to those vending machines we won't have to worry about losing the ability to restock important basic equipment.

**Comment by MagnusCrowe** [comment]
> I wouldn't mind that so much if buying things from exped teams didnt feel like pulling teeth for reasons everyone has talked about a million times. If you _really_ don't think they should be obtainable from cargo I think they should be able to be researched by science teams.

With the way I'm building the trade station POI, I'm hoping it is going to be less like pulling teeth.  The station will have shops that players can run, perhaps exped captains can find a middleman to offload their goods on once people get used to that RP environment.

**Comment by pupertino** [comment]
I have a small issue with them which is that I don't really like the 8-way movement scheme in space. I think when in space they should act more like ships, as in, have rotation at Q/E and WSAD controlling linear thrust. (And make them frictionless if the dampening PR goes through)
I think it's also a bit crazy that they're perpetual motion machines that need no maintenance. I'd add things like propellant and electricity that need to be restocked. Jetpacks don't go forever either. Speaking of electricity it would be nice if they had a recharger slot for batteries - would make the portable mass scanner less annoying to deal with. 
And as they're mini-ships I'm not sure if them being invisible to radar is a good thing either.

**Comment by dvir001** [comment]
Added back to loadouts

**Pull request closed without merging**
