### PR TITLE
Adds plasteel arming sword

### PR DESCRIPTION
**Pull request by MagnusCrowe**
## About the PR

New melee weapon.  Shout out to the Oni.

## Technical details

1.5 swing speed.
15 slash.

## Media
image

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: MagnusCrowe
- add: Added plasteel arming sword!

### CODE REVIEW

**Comment by GentleButter** [comment]
Given that Oni players need more melee options (especially with potential removal of gun use entirely?) i support and endorse this

**Review by FoxxoTrystan — APPROVED** [review]
This Sword sprite look very close to another sword.

**Comment by dvir001** [comment]
Please base it on another sword and not baseitem since it's going to be harder to support with grid bullshit

**Comment by MagnusCrowe** [comment]
> Please base it on another sword as perent and not baseitem since it's going to be harder to support with grid bullshit
> 
> If there is a sword that is also 15 base it from it

That might be a larger issue...almost all the swords seem to use BaseItem as their parent...except the energy katana.

**Comment by MagnusCrowe** [comment]
> This Sword sprite look very close to another sword.
Are you referring to the claymore? The Icon for the sword is in the same style as the claymore to keep art style's consistent but everything else is completely different (and higher quality IMO).
image

**Comment by MagnusCrowe** [comment]
> Please base it on another sword as perent and not baseitem since it's going to be harder to support with grid bullshit
> 
> If there is a sword that is also 15 base it from it

Done.

**Comment by YumiGumi** [comment]
As an Oni, I approve these changes and have some ideas of my own I am working on spriting.

**Review by Cheackraze — APPROVED** [review]

**Comment by Cheackraze** [comment]
Looks like 'Sword' isn't a tag yet.  You can either remove the tag (it seems unused) or add the tag prototype in the appropriate file and then this is good to merge

**Comment by MagnusCrowe** [comment]
> Looks like 'Sword' isn't a tag yet. You can either remove the tag (it seems unused) or add the tag prototype in the appropriate file and then this is good to merge

Dvir took care of it

**Comment by dvir001** [comment]
No errors all good

**Comment by ErhardSteinhauer** [comment]
Also while you at it, can you add this tag `WeaponMelee ` so the new sword could be stored in melee weapon racks?

**Comment by ErhardSteinhauer** [comment]
> Also while you at it, can you add this tag `WeaponMelee` so the new sword could be stored in melee weapon racks?

Oh, my bad, it's there

**Pull request merged**
