### PR TITLE
Refinement process follow-up

### PR DESCRIPTION
**Pull request by Wolfking6116**
## About the PR

This PR adds the inclusion of a few books being added to the Research Director Filled Hardsuit locker - of which only one can spawn per locker - to give a sort of hint in the direction of what they might want to do to process the Raw Artifexium added to the server from the previous PR.

These aren't incredibly informative books in their own right as it felt more on-brand for Nanotrasen to skirt around actually telling people outright. In addition it felt like a lame idea to just say "oh, yep, heres the recipe." This way it still leaves room for player interaction and mentorship as people figure things out and share it with one another.

## Why / Balance

This is a follow up of #1096 in response to this comment very immediately after it was merged into the server;
https://discord.com/channels/1123826877245694004/1123851369913266256/1217072502938009680

"What new ways? Do I need to build a fancy grinder? Or has artifexium been buffed? It sounds cool, but I don't know what to do with this information."

## Media

SS14ScienceTextbooks

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Breaking changes

**Changelog**

:cl:
- add: CentCom has sent out some educational texts about Artifexium Refinement to be included in a Research Director's Standard Kit across the Frontier Sector.

### CODE REVIEW

**Comment by Wolfking6116** [comment]
Darin has told me that apparently books are being done away with upstream...? For some reason.

If it is desired I can see about setting this up in a different way, either by recreating BaseBook here for us or by adding it to the Guide Book as Darin has suggested.

**Comment by dvir001** [comment]
About all books upstream send you into the in game guide book now with it being a process, we should not be going the other way around and keep adding guide information in books like this.

The all point of the guide books is that you are not required to carry an actual book around for game information.

**Comment by dvir001** [comment]
Leaving this as awaiting changes for change

**Comment by Wolfking6116** [comment]
> Dvir makes a good point however, that these should instead be in the random book spawner and not in a locker.

Normally I would agree, but given this is a relatively new change to how artifexium is handled I'd like to put forth the idea of these starting off in the locker and being moved to the random book spawner in the near future. 

My hope is to give some of the player base that is invested in the science scene an opportunity to have these presented to them initially so that some might figure out their meaning/purpose who can then share that knowledge with others, interacting and engaging via mentorship, before pulling these from rotation to become another random book with hints for those who give them more than a glance.

**Comment by dvir001** [comment]
Book have been nuked on upstream update, we will need to wait for after it before we look into this PR again as it will have alot of book related changes.

**Comment by Wolfking6116** [comment]
I figured. Partly why I was trying to get it in before merge, so it wouldn't be until well after it was done and settled before they got in 😅

**Comment by Wolfking6116** [comment]
Tested it with the merge. Changed the visuals to work with the new system. Actually really like it, honestly. Makes for a lot of graphic possibilities instead of set visuals per image. 

Works fine. All checks pass. However I still stand by;
> The direct reason I have for not wanting to put this into the guidebook is due to how previous Artifexium use was a rampant issue for how science was being bullrushed through most rounds, that by putting this information directly into the guidebook is pretty much counter intuitive to trying to fix it.

I can set up a follow up PR to have them removed from the locker and put into the spawner, with the intention for it to be merged after a month or so.

**Comment by dvir001** [comment]
image

This exists on the game guide itself

**Comment by Wolfking6116** [comment]
Excellent, then that part's already done. Since you agreed earlier when Stein mentioned that few people look at the guidebooks, it'll be useful to have an in-game reference to it as well as helps with world building, as check mentioned

> I think that having books be glorified paper is fine conceptually, even helps with the world building quite a bit, so as a stand-alone idea I'm not opposed to having this info in books.

**Comment by dvir001** [comment]
> Excellent, then that part's already done. Since you agreed earlier when Stein mentioned that few people look at the guidebooks, it'll be useful to have an in-game reference to it as well as helps with world building, as check mentioned
> 
> > I think that having books be glorified paper is fine conceptually, even helps with the world building quite a bit, so as a stand-alone idea I'm not opposed to having this info in books.

As said before if you remove them from lockers and move to random spawn pool it wont be an issue.

**Comment by Wolfking6116** [comment]
For clarity, what precisely is the issue with them being in lockers instead of the random poor?

**Comment by dvir001** [comment]
> For clarity, what precisely is the issue with them being in lockers instead of the random poor?

Avoid locker bloat when possible

**Comment by Wolfking6116** [comment]
Research Director locker has one of the least full lockers out of all of them, to my knowledge

**Comment by dvir001** [comment]
> Research Director locker has one of the least full lockers out of all of them, to my knowledge

Keep the locker as it was.

Make the book random to allow it show any place.
Not required to have the RD locker, not yo mention you didnt add it the the other RD locker also that show up on some ships.

If we just use the random book poo; we avoid mapping any books into lockers.

**Comment by Wolfking6116** [comment]
> not to mention you didnt add it the the other RD locker also that show up on some ships.

I've fixed that part. Though I don't really understand what you mean by 'not required to have the RD locker' when many ships do regardless.

But as said, I'm not opposed to it going into the random book pool - just that I believe having it in the lockers temporarily is worthwhile.

**Comment by dvir001** [comment]
Moved it to pool to avoid this PR going into limbo.

**Pull request merged**
