### PR TITLE
McDelivery Shuttle with McCargo shipyard

### PR DESCRIPTION
**Pull request by dvir001**
If #858 or #846 get added before im going to edit the McDelivery again, but nothing critical for this pr.

## About the PR
Added the McDelivery and the McCargo shipyard

Allowing for a dedicated food delivery solution.

Small changes to McCargo

## Why / Balance
Fast food.

## Technical details
.yml
Mapping

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame,

image

image

image

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- add: Added the McDelivery to the McCargo on ship shipyard, now you can do your fast food delivery with your very own fast food delivery ship.

### CODE REVIEW

**Comment by MagnusCrowe** [comment]
image
Add a poster or a cargo banner.

**Comment by dvir001** [comment]
image

**Comment by dvir001** [comment]
Im done

**Comment by dvir001** [comment]
Now its actually done.

**Review by MagnusCrowe — APPROVED** [review]

**Pull request merged**
