### PR TITLE
Fix ammunition icons in vendors

### PR DESCRIPTION
**Pull request by whatston3**
## About the PR

Add icons for each ammunition box type, and for the shotgun ammunition dispenser boxes.

## Why / Balance

Tricky to read ammunition types in the liberation station, especially for shotguns.  No more "why machine show red box but give blue box?" at LessLethalVend/Lib. Station pending #1388.

## How to test

1. Spawn LessLethalVend, Liberation Station, cryptographic sequencer.
2. Use cryptographic sequencer on both vendors.
3. View and buy each ammunition type.  The in-game sprite should match the picture in the vendor (no empty boxes, correct colours).

## Media

With change:
liberation_station_with_change

Without change:
liberation_station_without_change

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- fix: Liberation Station and LessLethalVend machines now show correct ammunition icons.

### CODE REVIEW

**Comment by dvir001** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1388 merged

**Comment by whatston3** [comment]
> #1388 merged

Glad it's in!  Pushed a set of updates.  Rubber ammunition and speedloaders (including .30 stripper clips and .35 speedloaders that are yet unused) now have their icons correctly displayed (spawn menu works fine).  Also, missed the EMP pistol round entry before.

Here's a shot of an emagged LessLethalVend with the new icons.
image

A few things I found of note:
* Argenti speedloader prototype currently isn't under _NF directories.
* LessLethalVend currently only offers .20 rubber ammunition in boxes, but live ammo in speedloaders.  This seems inconsistent to me.

**Comment by dvir001** [comment]
> > #1388 merged
> 
> Glad it's in! Pushed a set of updates. Rubber ammunition and speedloaders (including .30 stripper clips and .35 speedloaders that are yet unused) now have their icons correctly displayed (spawn menu works fine). Also, missed the EMP pistol round entry before.
> 
> Here's a shot of an emagged LessLethalVend with the new icons. image
> 
> A few things I found of note:
> 
> * Argenti speedloader prototype currently isn't under _NF directories.
> * LessLethalVend currently only offers .20 rubber ammunition in boxes, but live ammo in speedloaders.  This seems inconsistent to me.

I need to make a new PR to fix it and also move some ammo files around to new locations.

**Comment by dvir001** [comment]
> > #1388 merged
> 
> Glad it's in! Pushed a set of updates. Rubber ammunition and speedloaders (including .30 stripper clips and .35 speedloaders that are yet unused) now have their icons correctly displayed (spawn menu works fine). Also, missed the EMP pistol round entry before.
> 
> Here's a shot of an emagged LessLethalVend with the new icons. image
> 
> A few things I found of note:
> 
>     * Argenti speedloader prototype currently isn't under _NF directories. (Edit: this is a lie, I cannot read, but it should be under Entities/Objects/... where it currently is only under Objects/...)
> 
>     * LessLethalVend currently only offers .20 rubber ammunition in boxes, but live ammo in speedloaders.  This seems inconsistent to me.

https://github.com/new-frontiers-14/frontier-station-14/pull/1471/files

**Review by whatston3 — COMMENTED** [review]
Merge conflicts resolved, EMP box looks good under test, branch should be good to go.

**Review by ErhardSteinhauer — APPROVED** [review]
Tested on my end, look to be working fine. 
image

While this PR is aimed towards portion of larger upstream issue - inability of ui menus display layered sprites, it's a great QoL feature imo.

**Review by Cheackraze — APPROVED** [review]
just adding flat versions? works for now eh

**Comment by whatston3** [comment]
> just adding flat versions? works for now eh

A better solution might be to take the preview generation from whatever display the techfabs & lathes are using and port that over to the vendor window - they don't have this issue.

**Pull request merged**
