### PR TITLE
NSF Prowler: Update Again

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR
Updates the NSF Prowler a little bit, largely for compliance with space law changes and mapping requirements. 
- Directional fans have replaced tiny fans.
- Fuel locker was added.
- New airlocks.
- EVA suit storage.
- Shelving.
- Smoothed hull profile.
- Tiles under walls removed (hopefully I got them all) and some other tiles adjusted. 
- Small adjustments to engineering infrastructure.
- Added some posters. New NFSD signs.
- Shifted the radar console over a couple of tiles so it can't be used at the same time as the shuttle console.
- Adjusted price and ship description.

## Why / Balance
Space law now designates when NFSD officers should and shouldn't be using hardsuits, so the suit storage area was adjusted to now have EVA lockers as well as the hardsuit units. I had to remove the racks for this, so shelving was added around the ship so too much storage isn't lost. There's a sturdy shelf in the armoury now for storing ammunition.

Directional fans are now a thing, so the ship is compliant with those now. 

Price was adjusted also, as it appraises at just under 35k at purchase. 

## How to test
Checkout the branch, buy the ship. Go prowling.

## Media
2024-09-27 15_43_41-Frontier Station
Uninitialised. Spawns showing.

2024-09-27 15_45_08-Frontier Station
Uninitialised.

2024-09-27 15_45_59-Frontier Station
Initialised.

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Nil.

**Changelog**
:cl:
- tweak: Updated the NSF Prowler.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
Tagging @Kesiath as this PR concerns a ship they initially designed. 
Also tagging issue #1980 as this adds directional fans.

**Comment by ErhardSteinhauer** [comment]
Resolved the conflict, replaced old weapon racks with new ones.

**Comment by Tych0theSynth** [comment]
> Resolved the conflict, replaced old weapon racks with new ones.

Ah, thank you Erhard!

**Comment by Jakumba** [comment]
Sorry if this is an annoying question, but would it be possible to re-add the cellcharger removed from the cockpit? It could maybe fit in the dorm on the table.
Also, are the additional EVA lockers necessary? If my understanding of SOP is correct the patrol hardsuits are acceptable to wear at heat zero. Losing the vending machines would also be quite a blow to the ships flexability imo.

**Comment by Tych0theSynth** [comment]
> Sorry if this is an annoying question, but would it be possible to re-add the cellcharger removed from the cockpit? It could maybe fit in the dorm on the table. Also, are the additional EVA lockers necessary? If my understanding of SOP is correct the patrol hardsuits are acceptable to wear at heat zero. Losing the vending machines would also be quite a blow to the ships flexability imo.

Incorrect. From the SOP, softsuits are a requirement at both heat zero and heat one. Hardsuits are not authorised until heat two!
I'm not sure where I'd fit a charger in those places. You already get three omnidirectional wallmounts which can charge batteries as well as rechargeable equipment!

**Comment by Tych0theSynth** [comment]
> Ah to be clear re: the patrol suits, I was given to understand that they counted as soft suits, due to existing prior to the green armourless EVA suit, and that hard suit with regards to the SOP, specifically referenced the uplink purchasble combat suits and above. Is this no longer the case?

From my understanding, softsuits are softsuits and hardsuits are hardsuits. 
You'll notice that both the Broadhead and the Wendigo both have EVA and hardsuit storage also!

**Review by dvir001 — APPROVED** [review]

**Pull request merged**
